import {buildProductionPdf} from '../src/export.js';
import {buildLinkedWorkspaceModelV49} from '../src/linkedWorkspaceV49.js';
import {buildArtworkAtlas} from '../src/panelArtwork.js';
const results=[],assert=(value,label)=>{if(!value)throw new Error(label);results.push(label)};
const wait=async(fn,label)=>{const end=Date.now()+60000;while(Date.now()<end){if(fn())return;await new Promise(r=>setTimeout(r,60))}throw new Error('Timed out: '+label)};
const settle=()=>new Promise(r=>setTimeout(r,120));
try{
 await wait(()=>window.BoxStudioV65&&document.querySelector('[data-v61-studio]'),'complete runtime');
 const editor=window.BoxStudioEditor,token=`${Date.now()}-${Math.random()}`;window.liveArtworkToken=token;
 await document.fonts.load('14px "BoxStudio UI SC"','纸盒设计唛头出血安全区');await document.fonts.ready;
 assert(document.fonts.check('14px "BoxStudio UI SC"','纸盒设计唛头出血安全区'),'Local Chinese UI font loaded');
 const original=editor.getState();document.querySelector('[data-v63-stage="Structure"]').click();await wait(()=>document.querySelector('#templateSelect'),'Structure');
 assert(document.querySelector('#templateSelect').value===original.structure.template,'Structure selector matches project');
 const lengthInput=document.querySelector('[data-structure="length"]');lengthInput.value=original.structure.length+10;lengthInput.dispatchEvent(new Event('change',{bubbles:true}));await settle();
 assert(editor.getState().structure.length===original.structure.length+10,'Dimension change reaches core geometry');
 document.querySelector('#undo').click();await settle();assert(editor.getState().structure.length===original.structure.length,'Dimension undo');
 await wait(()=>document.querySelector('[data-v63-stage="Design"]'),'Structure stagebar');document.querySelector('[data-v63-stage="Design"]').click();await wait(()=>document.querySelector('[data-v61-panel]'),'Artwork');
 const id=document.querySelector('[data-v61-panel]').value;
 window.BoxStudioV61.applyPanelColor(id,'#0f766e');await settle();
 assert(editor.getState().elements.some(e=>e.v61PanelFill&&e.fillColor==='#0f766e'),'Panel color in core state');
 assert(document.querySelector('[data-v61-panel-fill]'),'Panel color on SVG');
 document.querySelector('#undo').click();await settle();
 assert(!editor.getState().elements.some(e=>e.v61PanelFill),'Color undo');
 document.querySelector('#redo').click();await settle();
 assert(editor.getState().elements.some(e=>e.v61PanelFill),'Color redo');
 const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=600;
 const ctx=canvas.getContext('2d');ctx.fillStyle='#0f766e';ctx.fillRect(0,0,1200,600);ctx.fillStyle='#fff';ctx.font='bold 90px sans-serif';ctx.fillText('ISUNOR',150,320);
 const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));
 await window.BoxStudioV60.addFile(new File([blob],'logo.png',{type:'image/png'}));await settle();
 let state=editor.getState(),image=state.elements.find(e=>e.type==='image');
 assert(Boolean(image),'PNG upload in core');assert(document.querySelector('[data-v60-image]'),'PNG visible in 2D');
 let linked=buildLinkedWorkspaceModelV49(state),atlas=buildArtworkAtlas(state,linked.review.geo);
 assert(atlas.imageCommands===1,'PNG in 3D artwork atlas');
 const art=window.BoxStudioV63.getSummary().artwork,expectedCount=art.images+art.texts+art.marks+art.styledPanels;assert(document.querySelector('.v63-work-status > span:nth-child(2) b').textContent===String(expectedCount),'Live Artwork object count');
 document.querySelector('#undo').click();await settle();assert(!editor.getState().elements.some(e=>e.type==='image'),'Image undo');
 document.querySelector('#redo').click();await settle();assert(editor.getState().elements.some(e=>e.type==='image'),'Image redo');
 document.querySelector('[data-v63-stage="Marks"]').click();await wait(()=>document.querySelector('[data-v58-marks-studio]'),'Marks');
 const mark=document.querySelector('[data-v58-mark]'),count=editor.getState().elements.length;mark.click();await settle();
 assert(editor.getState().elements.length>count,'Shipping mark preset committed');
 document.querySelector('[data-v63-stage="3D"]').click();await wait(()=>document.querySelector('#threeCanvas'),'3D');assert(true,'Full 3D mounted');
 await wait(()=>document.querySelector('[data-v63-stage="Preflight"]'),'3D stagebar');await settle();assert(document.querySelector('#threeCanvas').getBoundingClientRect().top<innerHeight*.7,'3D preview visible in viewport');document.querySelector('[data-v63-stage="Preflight"]').click();await wait(()=>document.querySelector('.preflight'),'Preflight');assert(document.querySelector('.preflight').textContent.length>50,'Preflight uses edited project');
 await wait(()=>document.querySelector('[data-v63-stage="Export"]'),'Preflight stagebar');document.querySelector('[data-v63-stage="Export"]').click();await wait(()=>document.querySelector('#exportPdf'),'Export');
 const pdf=buildProductionPdf(editor.getState());assert(pdf.length>10000,'Production PDF generated from edited state');
 await wait(()=>document.querySelector('[data-v63-stage="Design"]'),'Export stagebar');document.querySelector('[data-v63-stage="Design"]').click();await settle();editor.fitCanvas();await settle();
 assert(window.liveArtworkToken===token,'No document reload across edits');
 const rect=document.querySelector('.canvas-shell').getBoundingClientRect();assert(rect.height>=160,'Canvas has usable height');
 assert(document.documentElement.scrollWidth<=innerWidth+4,'No viewport overflow');
 assert(document.querySelector('#undo').getBoundingClientRect().height>0,'Undo control visible');if(innerWidth<=500)assert(document.querySelector('.rightpanel').getBoundingClientRect().height>0,'Mobile properties accessible');
 const runtime=window.BoxStudioUiRuntimeV64,start=runtime.stats().flushes;await new Promise(r=>setTimeout(r,800));
 assert(runtime.stats().flushes-start<=4,'Full-entry runtime stable at idle');
 assert(runtime.stats().errors.length===0,'Shared runtime has no errors');
 document.body.dataset.liveArtworkResult=JSON.stringify({status:'PASS',viewport:[innerWidth,innerHeight],checks:results,pdfBytes:pdf.length,objects:editor.getState().elements.length});
}catch(error){document.body.dataset.liveArtworkResult=JSON.stringify({status:'FAIL',checks:results,error:error.stack});console.error(error)}
