import assert from 'node:assert/strict';
import {setUiVersion,versionNumber} from '../src/uiVersion.js';
let writes=0,text='V0.8',title='BoxStudio V0.8';
const node={get textContent(){return text},set textContent(v){text=v;writes++}};
const doc={querySelector:()=>node,querySelectorAll:()=>[],get title(){return title},set title(v){title=v;writes++}};
assert(versionNumber('V0.65')>versionNumber('V0.9'));
assert.equal(setUiVersion('V0.65',doc),true);const first=writes;
for(let n=11;n<=65;n++)setUiVersion(`V0.${n}`,doc);
assert.equal(writes,first);assert.equal(title,'BoxStudio V0.65');assert.equal(text,'V0.65');
let visibleText='V0.75',visibleWrites=0;
const badge={get textContent(){return visibleText},set textContent(v){visibleText=v;visibleWrites++}};
let legacyWrites=0;
const legacy={get textContent(){return 'V0.65'},set textContent(v){legacyWrites++}};
doc.querySelectorAll=selector=>selector.includes('v67-version')?[badge]:[legacy];title='BoxStudio V0.76';text='V0.76';
assert.equal(setUiVersion('V0.76',doc),true);
assert.equal(visibleText,'V0.76');assert.equal(visibleWrites,1);
const afterRepair=writes;
assert.equal(setUiVersion('V0.76',doc),false);
assert.equal(setUiVersion('V0.75',doc),false);
assert.equal(writes,afterRepair);assert.equal(visibleWrites,1);
assert.equal(legacyWrites,0);
visibleText='V0.77';
assert.equal(setUiVersion('V0.76',doc),false);
assert.equal(visibleText,'V0.77');assert.equal(title,'BoxStudio V0.76');
console.log('PASS legacy version writers: monotonic version and no identical DOM writes');
