import assert from 'node:assert/strict';
import { defaultState } from '../src/model.js';
import { createBatchJobQueue, claimNextJob, completeJob, requestQueuePause, finalizeQueuePause, resumeQueue, queueProgress } from '../src/jobQueue.js';
import { setMarkPosition, nudgeMark, alignMarkToPanel, rotateMark, duplicateMark, deleteMark } from '../src/markLayout.js';
import { createProductionJob, submitProductionJob, approveProductionJob, rejectProductionJob, reviseProductionJob, approvalGate, upsertProductionJob, activeProductionJob } from '../src/productionJobs.js';

let queue=createBatchJobQueue([{SKU:'A'},{SKU:'B'}],{id:'v13-q'});
let claimed=claimNextJob(queue);queue=claimed.queue;
assert.equal(claimed.item.index,0);
queue=completeJob(queue,0,{fileName:'A.pdf'});
queue=requestQueuePause(queue);
assert.equal(queue.pauseRequested,true);
queue=finalizeQueuePause(queue);
assert.equal(queue.status,'paused');
assert.equal(queueProgress(queue).paused,true);
assert.equal(claimNextJob(queue).item,null);
queue=resumeQueue(queue);
assert.equal(queue.pauseRequested,false);
claimed=claimNextJob(queue);queue=claimed.queue;
assert.equal(claimed.item.index,1);

let state=structuredClone(defaultState);
state=setMarkPosition(state,'sku',99999,99999,{snap:1});
let sku=state.elements.find(element=>element.id==='sku');
assert.ok(sku.x<99999 && sku.y<99999,'position should clamp to panel');
state=alignMarkToPanel(state,'sku','left',{safeArea:true});
sku=state.elements.find(element=>element.id==='sku');
assert.equal(sku.x,Number(state.structure.safe));
state=nudgeMark(state,'sku',5,0,{snap:1});
assert.equal(state.elements.find(element=>element.id==='sku').x,Number(state.structure.safe)+5);
state=rotateMark(state,'sku',90);
assert.equal(state.elements.find(element=>element.id==='sku').r,90);
const before=state.elements.length;
state=duplicateMark(state,'sku',{newId:'sku-copy',offset:8});
assert.equal(state.elements.length,before+1);
assert.equal(state.selectedId,'sku-copy');
state=deleteMark(state,'sku-copy');
assert.equal(state.elements.some(element=>element.id==='sku-copy'),false);

state=structuredClone(defaultState);
let job=createProductionJob(state,{id:'prod-test',label:'Production Test',actor:'qa'});
assert.equal(job.status,'draft');
assert.equal(job.preflight.errorCount,0);
job=submitProductionJob(job,{actor:'operator',note:'ready'});
assert.equal(job.status,'submitted');
job=approveProductionJob(job,{actor:'approver',note:'approved'});
assert.equal(job.status,'approved');
assert.equal(approvalGate(state,job).ok,true);
let changed=structuredClone(state);changed.variables.sku='CHANGED-SKU';
assert.equal(approvalGate(changed,job).ok,false,'approved fingerprint must invalidate after artwork data changes');
job=reviseProductionJob(job,changed,{actor:'operator',note:'new sku'});
assert.equal(job.status,'draft');
assert.equal(job.revision,2);
assert.equal(job.project.sku,'CHANGED-SKU');
job=submitProductionJob(job,{actor:'operator'});
job=rejectProductionJob(job,{actor:'approver',note:'needs change'});
assert.equal(job.status,'rejected');
assert.ok(job.audit.length>=6);
changed=upsertProductionJob(changed,job);
assert.equal(activeProductionJob(changed).id,'prod-test');

console.log('BoxStudio V0.13 tests passed');
