import assert from 'node:assert/strict';
import { defaultState } from '../src/model.js';
import { generateGeometry } from '../src/geometry.js';
import { parseSvgMark, createSvgMarkElement } from '../src/svgMark.js';
import { createCrossPanelArtwork } from '../src/crossPanelArtwork.js';
import { buildNativePdfV21Plan, buildNativeGradientPdfV21 } from '../src/nativePdfV21.js';
import { setCrossSelection, toggleCrossSelection, translateCrossSelection, rotateCrossElement, selectionBounds } from '../src/crossPanelTransformV21.js';

const linearSvg=`<svg viewBox="0 0 100 60" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="lg" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" stop-color="#ff0000"/><stop offset="50%" stop-color="#00ff00"/><stop offset="100%" stop-color="#0000ff"/></linearGradient></defs><rect x="0" y="0" width="100" height="60" fill="url(#lg)" opacity="0.75"/></svg>`;
const radialSvg=`<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><defs><radialGradient id="rg" cx="50%" cy="50%" r="50%"><stop offset="0%" stop-color="#ffffff"/><stop offset="100%" stop-color="#111111"/></radialGradient></defs><circle cx="50" cy="50" r="48" fill="url(#rg)"/></svg>`;
const state=structuredClone(defaultState),geo=generateGeometry(state.structure),front=geo.panelMap.front;
assert.ok(front,'default geometry must expose front panel');
const linear=createSvgMarkElement(parseSvgMark(linearSvg,{name:'Linear'}),{id:'v21-linear',panelId:'front',x:20,y:20,width:160});
const radial=createSvgMarkElement(parseSvgMark(radialSvg,{name:'Radial'}),{id:'v21-radial',panelId:'front',x:220,y:20,width:90});
state.elements.push(linear,radial);
const plan=buildNativePdfV21Plan(state,geo);
assert.ok(plan.stats.axial>=1,'plan should contain axial shading');
assert.ok(plan.stats.radial>=1,'plan should contain radial shading');
assert.ok(plan.stats.alpha>=1,'uniform opacity should produce alpha ExtGState usage');
const pdf=buildNativeGradientPdfV21(state),text=new TextDecoder().decode(pdf);
assert.ok(text.startsWith('%PDF-1.6'));
assert.ok(text.includes('BoxStudio V0.21 Native Gradient Proof'));
assert.ok(text.includes('/ShadingType 2'),'PDF should contain native axial shading');
assert.ok(text.includes('/ShadingType 3'),'PDF should contain native radial shading');
assert.ok(text.includes('/FunctionType 3'),'three-stop gradient should use a stitching function');
assert.ok(text.includes('/ExtGState'),'uniform alpha should use ExtGState');
assert.ok(/\/Sh\d+ sh/.test(text),'content stream should invoke shading resources');

const crossA=createCrossPanelArtwork(parseSvgMark(linearSvg,{name:'Cross A'}),{id:'cross-a',x:front.x+8,y:front.y+8,width:80,height:48});
const crossB=createCrossPanelArtwork(parseSvgMark(radialSvg,{name:'Cross B'}),{id:'cross-b',x:front.x+108,y:front.y+8,width:55,height:55});
state.elements.push(crossA,crossB);
let edit=setCrossSelection(state,['cross-a']);
edit=toggleCrossSelection(edit,'cross-b',{additive:true});
assert.deepEqual(new Set(edit.crossPanelEdit.selection),new Set(['cross-a','cross-b']));
const moved=translateCrossSelection(edit,['cross-a','cross-b'],4.6,4.6,{panelMap:{}},{snap:true,gridMm:5,toleranceMm:1});
const after=selectionBounds(moved.state,['cross-a','cross-b']);
assert.ok(Math.abs(after.x/5-Math.round(after.x/5))<1e-6,'group left edge should snap to 5 mm grid');
assert.ok(Math.abs(after.y/5-Math.round(after.y/5))<1e-6,'group top edge should snap to 5 mm grid');
const edgeSnap=translateCrossSelection(edit,['cross-a','cross-b'],0,0,geo,{snap:true,gridMm:5,toleranceMm:10});
assert.ok(Array.isArray(edgeSnap.guides),'panel-edge snapping should return guide metadata');
const rotated=rotateCrossElement(moved.state,'cross-a',28,{snap:true,step:15});
assert.equal(rotated.elements.find(e=>e.id==='cross-a').r,30,'rotation should snap to 15 degree step');
const toggled=toggleCrossSelection(rotated,'cross-b',{additive:true});
assert.deepEqual(toggled.crossPanelEdit.selection,['cross-a']);
console.log('BoxStudio V0.21 tests passed');
