import assert from 'node:assert/strict';
import { defaultState } from '../src/model.js';
import { generateGeometry } from '../src/geometry.js';
import { parseSvgMark } from '../src/svgMark.js';
import { createCrossPanelArtwork, materializeCrossPanelArtworkElement, crossPanelArtworkDiagnostics } from '../src/crossPanelArtwork.js';
import { setCrossSelection } from '../src/crossPanelTransformV21.js';
import { scaleCrossSelection, rotateCrossSelection, alignCrossSelection, distributeCrossSelection, setCrossClipRect, parseNormalizedClipPolygon, crossClipText } from '../src/crossPanelTransformV22.js';
import { buildNativePdfV22Plan, buildNativeGradientPdfV22 } from '../src/nativePdfV22.js';

const alphaSvg=`<svg viewBox="0 0 100 60" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="fade" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" stop-color="#ff0000" stop-opacity="0.15"/><stop offset="50%" stop-color="#00ff00" stop-opacity="0.65"/><stop offset="100%" stop-color="#0000ff" stop-opacity="1"/></linearGradient></defs><rect x="0" y="0" width="100" height="60" fill="url(#fade)"/></svg>`;
const solidSvg=`<svg viewBox="0 0 100 60" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="100" height="60" fill="#cc2244"/></svg>`;
const state=structuredClone(defaultState),geo=generateGeometry(state.structure),front=geo.panelMap.front;
assert.ok(front);
const alpha=createCrossPanelArtwork(parseSvgMark(alphaSvg,{name:'Alpha gradient'}),{id:'alpha-cross',x:front.x+10,y:front.y+10,width:100,height:60});
state.elements.push(alpha);
const plan=buildNativePdfV22Plan(state);
assert.ok(plan.stats.softMasks>=1,'varying stop opacity must produce a soft mask plan');
const pdf=new TextDecoder().decode(buildNativeGradientPdfV22(state));
assert.ok(pdf.startsWith('%PDF-1.7'));
assert.ok(pdf.includes('BoxStudio V0.22 Native Gradient Soft Mask Proof'));
assert.ok(pdf.includes('/SMask << /S /Luminosity'),'PDF must contain a luminosity soft mask');
assert.ok(pdf.includes('/Group << /S /Transparency /CS /DeviceGray >>'));
assert.ok(pdf.includes('/ShadingType 2'));

const mark=parseSvgMark(solidSvg,{name:'Solid'});
const a=createCrossPanelArtwork(mark,{id:'a',x:front.x+10,y:front.y+15,width:80,height:48});
const b=createCrossPanelArtwork(mark,{id:'b',x:front.x+120,y:front.y+35,width:60,height:36});
const c=createCrossPanelArtwork(mark,{id:'c',x:front.x+230,y:front.y+55,width:50,height:30});
let edit=structuredClone(defaultState);edit.elements.push(a,b,c);edit=setCrossSelection(edit,['a','b','c']);
const scaled=scaleCrossSelection(edit,['a','b','c'],{scaleX:1.2,scaleY:1.1});
assert.ok(scaled.elements.find(e=>e.id==='a').w>a.w);
const rotated=rotateCrossSelection(edit,['a','b','c'],14,{snap:true,step:15});
assert.equal(rotated.elements.find(e=>e.id==='a').r,15);
const aligned=alignCrossSelection(edit,['a','b','c'],'left');
assert.equal(aligned.elements.find(e=>e.id==='a').x,aligned.elements.find(e=>e.id==='b').x);
const distributed=distributeCrossSelection(edit,['a','b','c'],'x');
const ordered=['a','b','c'].map(id=>distributed.elements.find(e=>e.id===id)).sort((x,y)=>x.x-y.x);
const gap1=ordered[1].x-(ordered[0].x+ordered[0].w),gap2=ordered[2].x-(ordered[1].x+ordered[1].w);assert.ok(Math.abs(gap1-gap2)<1e-6,'horizontal distribution should use equal gaps');
assert.deepEqual(parseNormalizedClipPolygon('0,0 1,0 1,1 0,1'),[[0,0],[1,0],[1,1],[0,1]]);
const clipped=setCrossClipRect(edit,'a',{x:0,y:0,w:.5,h:1}),clipEl=clipped.elements.find(e=>e.id==='a');assert.ok(crossClipText(clipEl).length>0);
const fullFragments=materializeCrossPanelArtworkElement(a,geo,{gradientDepth:0}),clipFragments=materializeCrossPanelArtworkElement(clipEl,geo,{gradientDepth:0});
const area=frags=>frags.filter(x=>x.type==='production-polygon').reduce((sum,x)=>sum+Math.abs((x.points||[]).reduce((s,p,i)=>{const n=x.points[(i+1)%x.points.length];return s+p[0]*n[1]-n[0]*p[1]},0))/2,0);
assert.ok(area(clipFragments)<area(fullFragments),'editable clip should reduce materialized fill area');
const diag=crossPanelArtworkDiagnostics(clipped,geo);assert.ok(diag.clipped>=1);
console.log('BoxStudio V0.22 tests passed');
