import assert from 'node:assert/strict';
import { defaultState } from '../src/model.js';
import { V47_FREE_POLICY,V47_WORKFLOW,actionableTemplatesV47,searchTemplatesV47,templateCategoriesV47,sanitizeQuickSizeV47,prepareTemplateStateV47,V47_MARK_GROUPS } from '../src/productExperienceV47.js';

assert.equal(V47_FREE_POLICY.freeForEveryone,true);assert.equal(V47_FREE_POLICY.loginRequired,false);assert.equal(V47_FREE_POLICY.paywall,false);assert.equal(V47_FREE_POLICY.trial,false);assert.equal(V47_WORKFLOW.length,6);assert.deepEqual(V47_WORKFLOW.map(x=>x.tab),['Structure','Structure','Design','3D','Marks','Export']);
const templates=actionableTemplatesV47();assert.ok(templates.length>=5,'All implemented/engineering-core templates should be discoverable');assert.ok(templates.every(t=>t.engine));assert.ok(searchTemplatesV47({query:'0427'}).some(t=>t.id==='fefco-0427'));assert.ok(searchTemplatesV47({query:'飞机盒'}).some(t=>t.id==='mailer-150010'));assert.equal(searchTemplatesV47({query:'definitely-not-a-template'}).length,0);assert.ok(templateCategoriesV47().includes('mailer'));assert.ok(templateCategoriesV47().includes('folding-carton'));
const size=sanitizeQuickSizeV47({length:-1,width:'bad',height:3,thickness:0,sizeType:'invalid',flute:'e'});assert.equal(size.length,25);assert.equal(size.width,200);assert.equal(size.height,15);assert.equal(size.thickness,.1);assert.equal(size.sizeType,'internal');assert.equal(size.flute,'E');
const next=prepareTemplateStateV47(defaultState,'mailer-150010',{length:320,width:210,height:85,sizeType:'external',materialId:'corrugated-kraft',flute:'B'});assert.equal(next.structure.template,'mailer-150010');assert.equal(next.structure.length,320);assert.equal(next.structure.width,210);assert.equal(next.structure.height,85);assert.equal(next.structure.sizeType,'external');assert.equal(next.structure.materialId,'corrugated-kraft');assert.equal(next.structure.flute,'B');assert.equal(next.page,'editor');assert.equal(next.editorTab,'Structure');assert.ok(next.elements.length>0);assert.match(next.projectName,/Free Project/);
assert.throws(()=>prepareTemplateStateV47(defaultState,'fefco-04xx-schema',{}),e=>e.code==='V47_TEMPLATE_NOT_ACTIONABLE');assert.throws(()=>prepareTemplateStateV47(defaultState,'unknown-template',{}),e=>e.code==='V47_TEMPLATE_NOT_ACTIONABLE');
assert.equal(V47_MARK_GROUPS.length,4);assert.ok(V47_MARK_GROUPS.some(g=>g.items.includes('GS1-128')));assert.ok(V47_MARK_GROUPS.some(g=>g.items.includes('箱号 / Package X/Y')));assert.ok(V47_MARK_GROUPS.some(g=>g.items.includes('易碎')));
console.log(`BoxStudio V0.47 product experience passed: templates=${templates.length} workflow=${V47_WORKFLOW.length} markGroups=${V47_MARK_GROUPS.length}`);
