import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { defaultState, stateForTemplate } from '../src/model.js';
import { actionableTemplatesV47 } from '../src/productExperienceV47.js';
import { buildLinkedWorkspaceModelV49 } from '../src/linkedWorkspaceV49.js';
import { ensureFoldAuthoringV50, selectFoldEdgeV50, setFoldEdgeAngleV50, flipFoldDirectionV50, moveFoldEdgeV50, setFoldTimelineV50, setSequenceEnabledV50, setExplodeV50, setDimensionsVisibleV50, buildFoldAuthoringModelV50, rendererAuthoringV50, foldAuthoringAcceptanceV50, V50_FOLD_SCHEMA } from '../src/foldAuthoringV50.js';
import { buildFoldTransformsV50 } from '../src/threeArtworkProofV50.js';

const projectFor=id=>{const preset=stateForTemplate(id,defaultState.variables),state=structuredClone(defaultState);state.structure=preset.structure;state.elements=preset.elements;state.variables=preset.variables;state.selectedId=preset.selectedId;state.page='editor';state.editorTab='3D';state.foldProgress=100;return state};
const templates=actionableTemplatesV47();assert.ok(templates.length>=8,'V0.50 must preserve the verified template catalog.');
for(const template of templates){const linked=buildLinkedWorkspaceModelV49(projectFor(template.id)),state=ensureFoldAuthoringV50(linked.state,linked.review.graph),accept=foldAuthoringAcceptanceV50(state,linked.review.graph,linked.review.geo),model=buildFoldAuthoringModelV50(state,linked.review.graph,linked.review.geo);assert.equal(state.foldAuthoringV50.schema,V50_FOLD_SCHEMA);assert.equal(accept.ok,true,`${template.id}: ${JSON.stringify(accept.errors)}`);assert.equal(model.edges.length,linked.review.graph.edges.length,`${template.id} fold authoring lost edges`);assert.equal(new Set(model.edges.map(edge=>edge.order)).size,model.edges.length,`${template.id} fold order duplicated`);assert.ok(model.edges.every(edge=>edge.hinge),`${template.id} editable edge lost physical hinge`)}

let linked=buildLinkedWorkspaceModelV49(projectFor('fefco-0203')),state=ensureFoldAuthoringV50(linked.state,linked.review.graph),model=buildFoldAuthoringModelV50(state,linked.review.graph,linked.review.geo);assert.ok(model.edges.length>=8);
const first=model.edges[0],second=model.edges[1];state=selectFoldEdgeV50(state,linked.review.graph,first.key);state=setFoldEdgeAngleV50(state,linked.review.graph,first.key,37);model=buildFoldAuthoringModelV50(state,linked.review.graph,linked.review.geo);assert.equal(model.selectedEdge.key,first.key);assert.equal(model.selectedEdge.angle,37);
state=flipFoldDirectionV50(state,linked.review.graph,first.key);model=buildFoldAuthoringModelV50(state,linked.review.graph,linked.review.geo);assert.equal(model.selectedEdge.angle,-37);
const beforeOrder=model.selectedEdge.order;state=moveFoldEdgeV50(state,linked.review.graph,first.key,1);model=buildFoldAuthoringModelV50(state,linked.review.graph,linked.review.geo);assert.equal(model.selectedEdge.order,Math.min(beforeOrder+1,model.edges.length));assert.equal(model.edges.find(edge=>edge.key===second.key).order,1);
state=setSequenceEnabledV50(state,linked.review.graph,true);state=setFoldTimelineV50(state,linked.review.graph,50);model=buildFoldAuthoringModelV50(state,linked.review.graph,linked.review.geo);assert.equal(model.sequenceEnabled,true);assert.ok(model.edges.some(edge=>edge.localProgress===100));assert.ok(model.edges.some(edge=>edge.localProgress===0));
state=setFoldTimelineV50(state,linked.review.graph,100);model=buildFoldAuthoringModelV50(state,linked.review.graph,linked.review.geo);assert.ok(model.edges.every(edge=>edge.localProgress===100));
state=setExplodeV50(state,linked.review.graph,65);state=setDimensionsVisibleV50(state,linked.review.graph,false);model=buildFoldAuthoringModelV50(state,linked.review.graph,linked.review.geo);const renderer=rendererAuthoringV50(model);assert.equal(renderer.explode,.65);assert.equal(renderer.dimensionsVisible,false);assert.equal(Object.keys(renderer.edgeAngles).length,model.edges.length);assert.equal(Object.keys(renderer.edgeProgress).length,model.edges.length);

const graph=linked.review.graph,geo=linked.review.geo,target=graph.edges[0],key=`${target.from}->${target.to}`,flat=buildFoldTransformsV50(graph,geo,100,{edgeAngles:{[key]:90},edgeProgress:{[key]:0}}),folded=buildFoldTransformsV50(graph,geo,100,{edgeAngles:{[key]:90},edgeProgress:{[key]:100}});assert.notDeepEqual(flat.get(target.to),folded.get(target.to),'per-edge fold progress must change the child transform.');
const reversed=buildFoldTransformsV50(graph,geo,100,{edgeAngles:{[key]:-90},edgeProgress:{[key]:100}});assert.notDeepEqual(folded.get(target.to),reversed.get(target.to),'direction flip must change the 3D transform.');

const index=await readFile(new URL('../index.html',import.meta.url),'utf8');const titleVersion=Number(index.match(/BoxStudio V0\.(\d+)/)?.[1]||0);assert.ok(titleVersion>=50,'Product title must stay at V0.50 or newer.');assert.ok(index.includes('v50Ui.css'));assert.ok(index.includes('v50Ui.js'));
const ui=await readFile(new URL('../src/v50Ui.js',import.meta.url),'utf8');assert.ok(ui.includes('单折线角度 / 方向 / 顺序 / 爆炸图 / 尺寸联动'));assert.ok(ui.includes('播放顺序'));assert.ok(ui.includes('3D 尺寸标注'));
const pkg=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8'));assert.ok(Number(pkg.version.split('.')[1])>=50,'Package version must stay at V0.50 or newer.');assert.equal(pkg.scripts['test:v50'],'node tests/v50.mjs');
console.log(`BoxStudio V0.50 fold authoring passed: templates=${templates.length} edges=${model.edges.length} explode=${model.explode}% timeline=${model.timeline}%`);
