import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { defaultState, stateForTemplate } from '../src/model.js';
import { buildLinkedWorkspaceModelV49 } from '../src/linkedWorkspaceV49.js';
import { ensureFoldSequenceV51, buildFoldSequenceModelV51, scanFoldSequenceV51 } from '../src/foldSequenceV51.js';
import { collisionEventsV52 } from '../src/collisionOptimizationV52.js';
import { buildCollisionRepairsV53, previewRepairV53, applyRepairV53, collisionRepairAcceptanceV53, V53_REPAIR_SCHEMA } from '../src/collisionRepairV53.js';

const preset=stateForTemplate('fefco-0203',defaultState.variables),project=structuredClone(defaultState);project.structure=preset.structure;project.elements=preset.elements;project.variables=preset.variables;project.selectedId=preset.selectedId;project.page='editor';project.editorTab='3D';project.foldProgress=100;
const linked=buildLinkedWorkspaceModelV49(project),graph=linked.review.graph,geo=linked.review.geo;let state=ensureFoldSequenceV51(linked.state,graph),report=scanFoldSequenceV51(state,graph,geo),events=collisionEventsV52(report);assert.ok(events.length>0,'V0.53 requires a reviewable collision event.');
const before=JSON.stringify(state),assistant=buildCollisionRepairsV53(state,graph,geo,report,events[0].id,{limit:8});assert.equal(assistant.schema,V53_REPAIR_SCHEMA);assert.equal(JSON.stringify(state),before,'Building repair candidates must not mutate the project state.');assert.equal(assistant.event.id,events[0].id);assert.ok(assistant.repairs.length>=2,'Collision event should produce multiple repair strategies.');assert.ok(assistant.repairs.some(r=>r.risk==='low'),'Repair assistant should include a low-risk sequence strategy.');assert.ok(assistant.repairs.some(r=>r.risk==='geometry'),'Repair assistant should include an explicitly marked geometry strategy.');
for(const repair of assistant.repairs){assert.ok(Number.isFinite(repair.score)&&repair.score>=0);assert.ok(repair.state?.foldSequenceV51);if(repair.risk==='geometry')assert.ok(repair.penalty>0,'Geometry-changing repair must carry a ranking penalty.');assert.equal(repair.eventId,assistant.event.id);}
const preview=previewRepairV53(assistant,assistant.repairs[0].id);assert.ok(preview?.changed);assert.equal(preview.repair.id,assistant.repairs[0].id);assert.equal(JSON.stringify(state),before,'Preview must remain non-destructive.');
const lowRisk=assistant.repairs.find(r=>r.risk==='low');const applied=applyRepairV53(state,graph,lowRisk),appliedModel=buildFoldSequenceModelV51(applied,graph,geo);assert.ok(appliedModel.stepCount>0);assert.notEqual(JSON.stringify(applied.foldSequenceV51.edgeSteps),JSON.stringify(state.foldSequenceV51.edgeSteps),'Applying a low-risk repair should change the fold sequence.');assert.equal(JSON.stringify(state),before,'Apply helper must return a new state without mutating the source.');
const geometry=assistant.repairs.find(r=>r.risk==='geometry');if(geometry){const geomApplied=applyRepairV53(state,graph,geometry),beforeAngle=state.foldAuthoringV50.edges.find(e=>e.key===geometry.edgeKey)?.angle,afterAngle=geomApplied.foldAuthoringV50.edges.find(e=>e.key===geometry.edgeKey)?.angle;assert.notEqual(afterAngle,beforeAngle,'Geometry repair should change the targeted fold angle/direction.');}
const acceptance=collisionRepairAcceptanceV53(state,graph,geo,report);assert.equal(acceptance.ok,true,JSON.stringify(acceptance.errors));assert.ok(acceptance.summary.repairs>0);
const ui=await readFile(new URL('../src/v53Ui.js',import.meta.url),'utf8');assert.ok(ui.includes('冲突定位 / 修复试算 / Before-After 对比 / 确认后应用'));assert.ok(ui.includes('试算预览'));assert.ok(ui.includes('确认应用'));
const index=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.ok(index.includes('v53Ui.css'));assert.ok(index.includes('v53Ui.js'));
const pkg=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8')),version=Number(pkg.version.split('.').slice(0,2).join('.'));assert.ok(version>=0.53,'V0.53 regression must remain valid on forward versions.');assert.equal(pkg.scripts['test:v53'],'node tests/v53.mjs');
console.log(`BoxStudio V0.53 repair assistant passed: event=${assistant.event.id} repairs=${assistant.repairs.length} improved=${assistant.repairs.filter(r=>r.improved).length} removedTarget=${assistant.repairs.filter(r=>r.removedTargetEvent).length}`);
