import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { defaultState, stateForTemplate } from '../src/model.js';
import { buildLinkedWorkspaceModelV49 } from '../src/linkedWorkspaceV49.js';
import { ensureFoldSequenceV51, scanFoldSequenceV51 } from '../src/foldSequenceV51.js';
import { buildRepairPlansV54, previewRepairPlanV54, applyRepairPlanV54, revertRepairPlanV54, repairPlanAcceptanceV54, V54_PLAN_SCHEMA } from '../src/repairPlanV54.js';

const preset=stateForTemplate('fefco-0203',defaultState.variables),project=structuredClone(defaultState);project.structure=preset.structure;project.elements=preset.elements;project.variables=preset.variables;project.selectedId=preset.selectedId;project.page='editor';project.editorTab='3D';project.foldProgress=100;
const linked=buildLinkedWorkspaceModelV49(project),graph=linked.review.graph,geo=linked.review.geo,state=ensureFoldSequenceV51(linked.state,graph),report=scanFoldSequenceV51(state,graph,geo),before=JSON.stringify(state);
const bundle=buildRepairPlansV54(state,graph,geo,report,{maxDepth:2,beamWidth:3});assert.equal(bundle.schema,V54_PLAN_SCHEMA);assert.equal(bundle.plans.length,3);assert.deepEqual(bundle.plans.map(p=>p.profile.id),['safe','balanced','aggressive']);assert.equal(JSON.stringify(state),before,'Repair plan search must not mutate source state.');assert.ok(bundle.evaluated>=3);
const safe=bundle.plans.find(p=>p.profile.id==='safe'),balanced=bundle.plans.find(p=>p.profile.id==='balanced'),aggressive=bundle.plans.find(p=>p.profile.id==='aggressive');assert.ok(safe&&balanced&&aggressive);assert.ok(safe.actions.every(a=>a.risk!=='geometry'),'Safe plan must never use geometry-changing repair actions.');for(const plan of bundle.plans){assert.ok(plan.state?.foldSequenceV51);assert.ok(Number.isFinite(plan.after.collisionScore));assert.ok(plan.evaluated>=1);}
const preview=previewRepairPlanV54(bundle,'safe');assert.ok(preview);assert.equal(preview.committed,false);assert.equal(JSON.stringify(state),before,'Plan preview must be non-destructive.');
const changed=bundle.plans.find(p=>p.changed);if(changed){const applied=applyRepairPlanV54(state,graph,changed);assert.notEqual(JSON.stringify(applied),before,'Applying a changed plan must return a different state.');assert.equal(JSON.stringify(state),before,'Apply helper must not mutate source state.');const reverted=revertRepairPlanV54(state,graph);assert.deepEqual(reverted.foldSequenceV51.edgeSteps,state.foldSequenceV51.edgeSteps,'Revert helper must restore original sequence snapshot.');assert.deepEqual(reverted.foldAuthoringV50.edges.map(e=>e.angle),state.foldAuthoringV50.edges.map(e=>e.angle),'Revert helper must restore original fold angles.');}
const acceptance=repairPlanAcceptanceV54(state,graph,geo,report);assert.equal(acceptance.ok,true,JSON.stringify(acceptance.errors));assert.equal(acceptance.summary.plans,3);
const ui=await readFile(new URL('../src/v54Ui.js',import.meta.url),'utf8');assert.ok(ui.includes('Safe / Balanced / Aggressive'));assert.ok(ui.includes('整套预览'));assert.ok(ui.includes('撤销上次 Repair Plan'));
const index=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.ok(index.includes('v54Ui.css'));assert.ok(index.includes('v54Ui.js'));
const pkg=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8')),version=Number(pkg.version.split('.').slice(0,2).join('.'));assert.ok(version>=.54,'V0.54 regression must allow forward product versions.');assert.equal(pkg.scripts['test:v54'],'node tests/v54.mjs');
console.log(`BoxStudio V0.54 repair plans passed: evaluated=${bundle.evaluated} safeActions=${safe.actions.length} balancedActions=${balanced.actions.length} aggressiveActions=${aggressive.actions.length} improved=${bundle.plans.filter(p=>p.improved).length}`);
