import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { defaultState, stateForTemplate } from '../src/model.js';
import { buildLinkedWorkspaceModelV49 } from '../src/linkedWorkspaceV49.js';
import { ensureFoldSequenceV51, scanFoldSequenceV51 } from '../src/foldSequenceV51.js';
import { buildManufacturingProfilesV55, manufacturingAcceptanceV55, manufacturingPreflightChecksV55, V55_MANUFACTURING_SCHEMA } from '../src/manufacturingIntelligenceV55.js';

const preset=stateForTemplate('fefco-0203',defaultState.variables),project=structuredClone(defaultState);project.structure=preset.structure;project.elements=preset.elements;project.variables=preset.variables;project.selectedId=preset.selectedId;project.page='editor';project.editorTab='3D';project.foldProgress=100;
const linked=buildLinkedWorkspaceModelV49(project),graph=linked.review.graph,geo=linked.review.geo,state=ensureFoldSequenceV51(linked.state,graph),report=scanFoldSequenceV51(state,graph,geo);
const bundle=buildManufacturingProfilesV55(state,graph,geo,report);assert.equal(bundle.schema,V55_MANUFACTURING_SCHEMA);assert.deepEqual(bundle.profiles.map(p=>p.profile.id),['safe','machine','manual']);assert.equal(bundle.context.templateId,'fefco-0203');assert.equal(bundle.context.material.flute,'B');assert.equal(bundle.context.material.thicknessMm,3);assert.ok(bundle.context.panelCount>0);assert.ok(bundle.context.crease.allowanceMm>0);assert.equal(bundle.factoryOverrideRequired,true);
for(const p of bundle.profiles){assert.ok(p.score>=0&&p.score<=100);assert.ok(['pass','review','fail'].includes(p.status));assert.ok(p.issues.length>=5);assert.ok(p.engineering.factoryOverrideRequired);}
const safe=bundle.profiles.find(p=>p.profile.id==='safe'),machine=bundle.profiles.find(p=>p.profile.id==='machine'),manual=bundle.profiles.find(p=>p.profile.id==='manual');assert.ok(safe.thresholds.minGlueMm>=machine.thresholds.minGlueMm);assert.ok(machine.thresholds.minGlueMm>=manual.thresholds.minGlueMm);assert.ok(safe.thresholds.minPanelMm>=manual.thresholds.minPanelMm);assert.ok(safe.thresholds.maxConcurrentFolds<=manual.thresholds.maxConcurrentFolds);
const thick=buildManufacturingProfilesV55(state,graph,geo,report,{thicknessMm:20}),thickSafe=thick.profiles.find(p=>p.profile.id==='safe');assert.ok(thickSafe.thresholds.minPanelMm>safe.thresholds.minPanelMm,'Factory thickness override must affect handling thresholds.');assert.ok(thickSafe.score<=safe.score,'Extreme factory thickness override should not improve the Safe score.');
const noComp=structuredClone(state);noComp.structure.compensation=false;const noCompBundle=buildManufacturingProfilesV55(noComp,graph,geo,report),safeComp=noCompBundle.profiles.find(p=>p.profile.id==='safe'),manualComp=noCompBundle.profiles.find(p=>p.profile.id==='manual');assert.equal(safeComp.issues.find(x=>x.code==='V55_THICKNESS_COMPENSATION_OFF')?.severity,'error');assert.equal(manualComp.issues.find(x=>x.code==='V55_THICKNESS_COMPENSATION_OFF')?.severity,'warning');
const fakeCollision={...report,penetrations:[{type:'penetration',a:'front',b:'back'}]},blocked=buildManufacturingProfilesV55(state,graph,geo,fakeCollision),machineBlocked=blocked.profiles.find(p=>p.profile.id==='machine');assert.equal(machineBlocked.issues.find(x=>x.code==='V55_FOLD_PENETRATION')?.severity,'error');assert.equal(machineBlocked.status,'fail');
const advisory=manufacturingPreflightChecksV55(blocked,'machine',{blocking:false}),hard=manufacturingPreflightChecksV55(blocked,'machine',{blocking:true});assert.equal(advisory.some(x=>x.code==='V55_FOLD_PENETRATION'&&x.severity==='error'),false,'Advisory manufacturing checks must not block production by default.');assert.equal(hard.some(x=>x.code==='V55_FOLD_PENETRATION'&&x.severity==='error'),true,'Explicit manufacturing blocking must preserve manufacturing errors.');
const acceptance=manufacturingAcceptanceV55(state,graph,geo,report);assert.equal(acceptance.ok,true,JSON.stringify(acceptance.errors));assert.equal(acceptance.summary.profiles,3);
const ui=await readFile(new URL('../src/v55Ui.js',import.meta.url),'utf8');assert.ok(ui.includes('V0.55 MANUFACTURING INTELLIGENCE'));assert.ok(ui.includes('工厂实测厚度'));assert.ok(ui.includes('Safe / Machine / Manual'));
const preflight=await readFile(new URL('../src/preflightV55.js',import.meta.url),'utf8');assert.ok(preflight.includes('manufacturingBlocking=false'));assert.ok(preflight.includes('manufacturingPreflightChecksV55'));
const index=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.ok(index.includes('BoxStudio V0.55'));assert.ok(index.includes('v55Ui.css'));assert.ok(index.includes('v55Ui.js'));
const pkg=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8'));assert.equal(pkg.version,'0.55.0');assert.equal(pkg.scripts['test:v55'],'node tests/v55.mjs');
console.log(`BoxStudio V0.55 manufacturing intelligence passed: material=${bundle.context.material.materialId}/${bundle.context.material.flute} T=${bundle.context.material.thicknessMm} safe=${safe.score} machine=${machine.score} manual=${manual.score} overlaps=${bundle.context.overlapCount}`);
