import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { defaultState, stateForTemplate } from '../src/model.js';
import { buildLinkedWorkspaceModelV49 } from '../src/linkedWorkspaceV49.js';
import { ensureFoldSequenceV51, scanFoldSequenceV51 } from '../src/foldSequenceV51.js';
import { createFactoryDatabaseV56, normalizeFactoryDatabaseV56, duplicateFactoryProfileV56, deleteFactoryProfileV56, upsertFactoryProfileV56, exportFactoryDatabaseV56, importFactoryDatabaseV56, evaluateFactoryCapabilityV56, factoryPreflightChecksV56, factoryAcceptanceV56, validateFactoryProfileV56, V56_DATABASE_SCHEMA } from '../src/factoryProfilesV56.js';
import { runPreflightV56 } from '../src/preflightV56.js';

const makeTemplate=id=>{const preset=stateForTemplate(id,defaultState.variables),project=structuredClone(defaultState);project.structure=preset.structure;project.elements=preset.elements;project.variables=preset.variables;project.selectedId=preset.selectedId;project.page='editor';project.editorTab='3D';project.foldProgress=100;const linked=buildLinkedWorkspaceModelV49(project),graph=linked.review.graph,geo=linked.review.geo,state=ensureFoldSequenceV51(linked.state,graph),report=scanFoldSequenceV51(state,graph,geo);return{project,linked,graph,geo,state,report}};
const fixture=makeTemplate('fefco-0203');
let db=createFactoryDatabaseV56();assert.equal(db.schema,V56_DATABASE_SCHEMA);assert.equal(db.profiles.length,3);assert.equal(db.profiles.filter(x=>x.builtIn).length,3);assert.equal(factoryAcceptanceV56(db).ok,true);
const corr=db.profiles.find(x=>x.id==='generic-corrugated-machine'),paper=db.profiles.find(x=>x.id==='generic-paperboard-folder-gluer');assert.ok(corr&&paper);
const good=evaluateFactoryCapabilityV56(fixture.state,fixture.graph,fixture.geo,fixture.report,corr);assert.equal(good.context.material.category,'corrugated');assert.equal(good.context.material.flute,'B');assert.equal(good.errors.length,0,JSON.stringify(good.errors));assert.equal(good.context.matchedCreaseMatrix?.id,'corr-bc');assert.ok(good.context.blank.widthMm>500);
const wrong=evaluateFactoryCapabilityV56(fixture.state,fixture.graph,fixture.geo,fixture.report,paper);assert.ok(wrong.errors.some(x=>x.code==='V56_MATERIAL_CATEGORY'));
const beforeBuiltIn=db.profiles.length;db=deleteFactoryProfileV56(db,'generic-corrugated-machine');assert.equal(db.profiles.length,beforeBuiltIn,'Built-in factory profiles must not be deletable.');
db=duplicateFactoryProfileV56(db,'generic-corrugated-machine','Plant A Corrugated');let custom=db.profiles.find(x=>x.id===db.selectedId);assert.ok(custom&&!custom.builtIn);assert.equal(custom.name,'Plant A Corrugated');custom={...custom,blank:{...custom.blank,maxWidthMm:500},dieCutter:{...custom.dieCutter,maxWidthMm:500},productionGate:{...custom.productionGate,enabled:true}};db=upsertFactoryProfileV56(db,custom);custom=db.profiles.find(x=>x.id===db.selectedId);const constrained=evaluateFactoryCapabilityV56(fixture.state,fixture.graph,fixture.geo,fixture.report,custom);assert.ok(constrained.errors.some(x=>x.code==='V56_BLANK_SIZE'));assert.ok(constrained.errors.some(x=>x.code==='V56_DIECUTTER_SIZE'));assert.equal(constrained.gate.blocked,true);
const advisory=factoryPreflightChecksV56(constrained,false),blocking=factoryPreflightChecksV56(constrained,true);assert.equal(advisory.some(x=>x.severity==='error'),false);assert.ok(blocking.some(x=>x.code==='V56_BLANK_SIZE'&&x.severity==='error'));
const softPreflight=runPreflightV56(fixture.state,{factoryProfile:custom,factoryBlocking:false}),hardPreflight=runPreflightV56(fixture.state,{factoryProfile:custom,factoryBlocking:true});assert.equal(softPreflight.errors.some(x=>x.code==='V56_BLANK_SIZE'),false,'Advisory factory checks must not hard-block.');assert.equal(hardPreflight.errors.some(x=>x.code==='V56_BLANK_SIZE'),true,'Factory blocking must preserve capability errors.');assert.equal(hardPreflight.factory.profileId,custom.id);
const exported=exportFactoryDatabaseV56(db),roundtrip=importFactoryDatabaseV56(exported);assert.equal(roundtrip.profiles.length,db.profiles.length);assert.equal(roundtrip.selectedId,db.selectedId);assert.equal(roundtrip.profiles.find(x=>x.id===custom.id)?.blank.maxWidthMm,500);
const invalid=validateFactoryProfileV56({...custom,materials:{...custom.materials,thicknessMinMm:8,thicknessMaxMm:2}});assert.equal(invalid.ok,false);assert.ok(invalid.errors.some(x=>x.code==='V56_FACTORY_THICKNESS_RANGE'));
const TEMPLATE_IDS=['side-seal-rsc','mailer-150010','fefco-0427','reverse-tuck-end','auto-lock-bottom','fefco-0203','straight-tuck-end','sleeve-carton'],matrix=[];const baseline=normalizeFactoryDatabaseV56(createFactoryDatabaseV56());for(const id of TEMPLATE_IDS){const f=makeTemplate(id),category=f.state.structure.materialId?.includes('paperboard')?'paperboard':null,actual=evaluateFactoryCapabilityV56(f.state,f.graph,f.geo,f.report,baseline.profiles.find(x=>x.id==='generic-corrugated-machine')).context.material.category,p=baseline.profiles.find(x=>x.id===(actual==='paperboard'?'generic-paperboard-folder-gluer':'generic-corrugated-machine')),ev=evaluateFactoryCapabilityV56(f.state,f.graph,f.geo,f.report,p);assert.equal(ev.errors.some(x=>x.code==='V56_MATERIAL_CATEGORY'),false,`${id}: material/profile mismatch`);assert.ok(ev.context.blank.widthMm>0&&ev.context.blank.heightMm>0,`${id}: blank dimensions missing`);matrix.push(`${id}:${actual}:${ev.status}:${ev.score}`)}
const ui=await readFile(new URL('../src/v56Ui.js',import.meta.url),'utf8');assert.ok(ui.includes('V0.56 FACTORY PROFILE / MACHINE CAPABILITY DATABASE'));assert.ok(ui.includes('复制当前'));assert.ok(ui.includes('Production Gate'));assert.ok(ui.includes('exportDatabase'));
const preflight=await readFile(new URL('../src/preflightV56.js',import.meta.url),'utf8');assert.ok(preflight.includes('boxstudio-preflight-v56'));assert.ok(preflight.includes('factoryBlocking'));
const index=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.ok(index.includes('BoxStudio V0.56'));assert.ok(index.includes('v56Ui.css'));assert.ok(index.includes('v56Ui.js'));
const pkg=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8'));assert.equal(pkg.version,'0.56.0');assert.equal(pkg.scripts['test:v56'],'node tests/v56.mjs');
console.log(`BoxStudio V0.56 factory capability passed: baselines=3 custom=${roundtrip.profiles.filter(x=>!x.builtIn).length} blank=${good.context.blank.widthMm}x${good.context.blank.heightMm} good=${good.score} constrained=${constrained.score} templates=${matrix.length}`);
