import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { defaultState,stateForTemplate } from '../src/model.js';
import { buildLinkedWorkspaceModelV49 } from '../src/linkedWorkspaceV49.js';
import { buildArtworkAtlas } from '../src/panelArtwork.js';
import { buildTextureProofModel } from '../src/threeArtworkProof.js';
import { buildProductionPdf } from '../src/export.js';
import { createImageElementV60,dataUrlByteSizeV60 } from '../src/artworkImageV60.js';
import { V61_PRODUCT_VERSION,V61_SWATCHES,normalizeColorV61,printablePanelsV61,panelFillForV61,upsertPanelFillV61,removePanelFillV61,clearPanelFillsV61,applyAllPanelFillsV61,syncPanelFillsV61,artworkStatsV61,artworkAcceptanceV61 } from '../src/artworkStudioV61.js';

const makeState=id=>{const p=stateForTemplate(id,defaultState.variables),s=structuredClone(defaultState);s.structure=p.structure;s.elements=p.elements;s.variables=p.variables;s.selectedId=p.selectedId;s.page='editor';s.editorTab='Design';s.foldProgress=100;return s};
assert.equal(V61_PRODUCT_VERSION,'V0.61');assert.ok(V61_SWATCHES.includes('#0f766e'));assert.equal(normalizeColorV61('#ABC'),'#aabbcc');assert.equal(artworkAcceptanceV61().ok,true);
let state=makeState('fefco-0427'),linked=buildLinkedWorkspaceModelV49(state),geo=linked.review.geo,panels=printablePanelsV61(geo),panel=geo.panelMap.front||geo.panelMap.base||panels[0];assert.ok(panel&&panels.length>2);
state=upsertPanelFillV61(state,geo,panel.id,'#0f766e');const fill=panelFillForV61(state,panel.id);assert.equal(fill.fillColor,'#0f766e');assert.equal(fill.type,'production-polygon');assert.equal(fill.zIndex,-100000);assert.deepEqual(fill.points.at(-1),[0,panel.h]);
const jpeg='data:image/jpeg;base64,/9j/2Q==',image=createImageElementV60({src:jpeg,mime:'image/jpeg',name:'logo.jpg',pixelWidth:1200,pixelHeight:600,assetBytes:dataUrlByteSizeV60(jpeg),pdfSrc:'',pdfBytes:0},panel,{id:'v61-logo',panelId:panel.id});state.elements.push(image);
let atlas=buildArtworkAtlas(state,geo),plan=atlas.plans.find(p=>p.panelId===panel.id);assert.ok(plan.commands.some(c=>c.type==='polygon'&&c.fillColor==='#0f766e'));assert.ok(plan.commands.some(c=>c.type==='image'&&c.source==='v61-logo'));assert.equal(atlas.imageCommands,1);
const proof=buildTextureProofModel(state,geo,linked.review.graph);assert.ok(proof.atlas.plans.find(p=>p.panelId===panel.id)?.commands.some(c=>c.type==='polygon'&&c.fillColor==='#0f766e'));
const stats=artworkStatsV61(state,geo);assert.equal(stats.styledPanels,1);assert.equal(stats.images,1);assert.ok(stats.marks>0);
state.structure={...state.structure,length:Number(state.structure.length)+37};linked=buildLinkedWorkspaceModelV49(state);geo=linked.review.geo;state=syncPanelFillsV61(state,geo);const resized=panelFillForV61(state,panel.id),resizedPanel=geo.panelMap[panel.id];assert.ok(resized&&resizedPanel);assert.deepEqual(resized.points,[[0,0],[resizedPanel.w,0],[resizedPanel.w,resizedPanel.h],[0,resizedPanel.h]],'Panel fill must synchronize to the current parametric panel geometry.');
state=applyAllPanelFillsV61(state,geo,'#1d4ed8');panels=printablePanelsV61(geo);assert.equal(state.elements.filter(e=>e.v61PanelFill).length,panels.length);assert.ok(state.elements.filter(e=>e.v61PanelFill).every(e=>e.fillColor==='#1d4ed8'));
state=removePanelFillV61(state,panels[0].id);assert.equal(panelFillForV61(state,panels[0].id),null);state=clearPanelFillsV61(state);assert.equal(state.elements.some(e=>e.v61PanelFill),false);assert.equal(state.elements.some(e=>e.id==='v61-logo'),true,'Clearing panel colors must not delete image artwork.');
const pdfState=makeState('fefco-0427'),pdfLinked=buildLinkedWorkspaceModelV49(pdfState),pdfPanel=pdfLinked.review.geo.panelMap.front||pdfLinked.review.geo.bodyPanels[0];let styled=upsertPanelFillV61(pdfState,pdfLinked.review.geo,pdfPanel.id,'#b91c1c');styled.elements.push(createImageElementV60({src:jpeg,mime:'image/jpeg',name:'logo.jpg',pixelWidth:1200,pixelHeight:600,assetBytes:dataUrlByteSizeV60(jpeg),pdfSrc:'',pdfBytes:0},pdfPanel,{id:'v61-pdf-logo',panelId:pdfPanel.id}));const pdf=buildProductionPdf(styled);assert.ok(pdf.length>1000);
const TEMPLATES=['side-seal-rsc','mailer-150010','fefco-0427','reverse-tuck-end','auto-lock-bottom','fefco-0203','straight-tuck-end','sleeve-carton'];let routed=0;for(const id of TEMPLATES){let s=makeState(id),m=buildLinkedWorkspaceModelV49(s),ps=printablePanelsV61(m.review.geo);assert.ok(ps.length,`${id}: no printable panel`);s=upsertPanelFillV61(s,m.review.geo,ps[0].id,'#d97706');const a=buildArtworkAtlas(s,m.review.geo);assert.ok(a.plans.some(p=>p.commands.some(c=>c.type==='polygon'&&c.fillColor==='#d97706')),`${id}: fill missing from atlas`);routed++}
const ui=await readFile(new URL('../src/v61Ui.js',import.meta.url),'utf8');for(const n of ['ARTWORK WORKSPACE','应用到当前面','应用到全部面','Logo / 图片','2D + 3D'])assert.ok(ui.includes(n),`V0.61 UI missing ${n}`);const css=await readFile(new URL('../src/v61Ui.css',import.meta.url),'utf8');assert.ok(css.includes('v61-artwork-studio'));assert.ok(css.includes('@media(max-width:760px)'));
const index=await readFile(new URL('../index.html',import.meta.url),'utf8');assert.ok(index.includes('v61Ui.css'));assert.ok(index.includes('v61Ui.js'));const pkg=JSON.parse(await readFile(new URL('../package.json',import.meta.url),'utf8'));assert.equal(pkg.version,'0.61.0');assert.equal(pkg.scripts['test:v61'],'node tests/v61.mjs');
console.log(`BoxStudio V0.61 artwork workspace passed: templates=${routed} panels=${panels.length} pdf=${pdf.length} swatches=${V61_SWATCHES.length}`);
