import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
import {defaultState} from '../src/model.js';
import {createMarkDocumentV67,setMarkArtboardV67,visibleMarkElementsV67,insertStandaloneMarkV67,patchStandaloneElementV67,duplicateStandaloneElementV67,parseMarkDocumentV67,markPreflightV67,buildMarkSvgV67,buildMarkPdfV67} from '../src/standaloneMarksV67.js';
import {applyMarkDataV66,rectanglesOverlapV66} from '../src/shippingMarkLayoutV66.js';
import {renderTemplate} from '../src/variables.js';
let count=0;const check=(fn)=>{fn();count++;};
const original=JSON.stringify(defaultState),s=createMarkDocumentV67();
check(()=>assert.equal(JSON.stringify(defaultState),original));
check(()=>assert.equal(s.schema,'boxstudio-standalone-mark'));
check(()=>assert.equal(s.syncDimensions,false));
check(()=>assert.equal(s.structure.importedGeometry.panels.length,1));
check(()=>assert.equal(s.structure.importedGeometry.cutLines.length,0));
check(()=>assert.equal(markPreflightV67(s).ok,true));
check(()=>assert.equal(visibleMarkElementsV67(s).some(e=>e.type==='notice'),false));
const multiple=applyMarkDataV66(s,{packageCount:'3',packageIndex:'2',crn:'BIND-CRN',sku:'TEST-067',qrValue:'TEST-067'},{syncDimensions:false});
check(()=>assert.equal(visibleMarkElementsV67(multiple).filter(e=>e.type==='notice').length,1));
check(()=>assert.equal(multiple.elements.filter(e=>e.template?.includes('{{crn}}')).map(e=>renderTemplate(e.template,multiple.variables)).join('|'),'CRN: BIND-CRN|CRN: BIND-CRN'));
check(()=>assert.equal(multiple.structure.length,s.structure.length));
check(()=>assert.equal(markPreflightV67(multiple).ok,true));
check(()=>{const e=multiple.elements.find(e=>e.type==='notice'),b=multiple.elements.find(e=>e.type==='barcode-qr-group');assert.equal(rectanglesOverlapV66(e,b,0),false);});
const changed=patchStandaloneElementV67(s,'label-barcode',{w:250});
check(()=>assert.equal(changed.elements.find(e=>e.id==='label-barcode').h,80));
check(()=>assert.equal(s.elements.find(e=>e.id==='label-barcode').w,250));
check(()=>assert.throws(()=>patchStandaloneElementV67(s,'label-barcode',{w:10}),/250 × 80/));
const copied=duplicateStandaloneElementV67(s,'label-sku');
check(()=>assert.equal(new Set(copied.elements.map(e=>e.id)).size,s.elements.length+1));
check(()=>assert.equal(copied.elements.at(-1).x,18));
const blank=createMarkDocumentV67('blank'),added=insertStandaloneMarkV67(blank,'barcodeQr');
check(()=>assert.equal(added.elements[0].w/added.elements[0].h,3.125));
check(()=>assert.equal(added.elements[0].panelId,'label'));
check(()=>assert.equal(markPreflightV67(added).ok,true));
check(()=>assert.throws(()=>setMarkArtboardV67(s,0,220),/画布/));
check(()=>assert.throws(()=>patchStandaloneElementV67(s,'label-sku',{fontSize:0}),/字号/));
check(()=>assert.equal(markPreflightV67(patchStandaloneElementV67(s,'label-sku',{x:-1})).ok,false));
const malformed=JSON.parse(JSON.stringify(s));malformed.elements[0].x='12';
check(()=>assert.throws(()=>parseMarkDocumentV67(JSON.stringify(malformed)),/位置/));
malformed.elements[0].x=12;malformed.elements[1].id=malformed.elements[0].id;
check(()=>assert.throws(()=>parseMarkDocumentV67(JSON.stringify(malformed)),/重复/));
check(()=>assert.throws(()=>parseMarkDocumentV67('{bad'),SyntaxError));
check(()=>assert.throws(()=>parseMarkDocumentV67(JSON.stringify({...s,schema:'boxstudio'})),/有效/));
check(()=>assert.equal(parseMarkDocumentV67(JSON.stringify(s)).artboard.width,320));
const chinese=patchStandaloneElementV67(s,'label-sku',{template:'中文 {{sku}}'});
check(()=>assert.equal(markPreflightV67(chinese,{pdf:true}).ok,false));
check(()=>assert.match(buildMarkSvgV67(chinese),/中文 ITEM-001/));
check(()=>assert.throws(()=>buildMarkPdfV67(chinese),/TTF/));
const pdf=buildMarkPdfV67(multiple),pdfText=new TextDecoder().decode(pdf);
check(()=>assert.match(pdfText,/\/MediaBox \[0 0 907\.087 623\.622\]/));
check(()=>assert.match(pdfText,/BIND-CRN/));
check(()=>assert.equal((pdfText.match(/BIND-CRN/g)||[]).length,2));
check(()=>assert.doesNotMatch(pdfText,/\/CSCUT cs|\/CSCREASE cs/));
check(()=>assert.match(pdfText,/product has 3 packages/));
check(()=>assert.match(buildMarkSvgV67(multiple),/width="320mm" height="220mm"/));
check(()=>assert.doesNotMatch(buildMarkSvgV67(multiple),/selection-box|mark-hit|pattern id="mark-grid"/));
check(()=>assert.match(buildMarkSvgV67(s,{ui:true}),/selection-box/));
check(()=>assert.doesNotMatch(buildMarkSvgV67(s),/product has/));
const invalid=applyMarkDataV66(s,{sku:'bad*invalid'},{syncDimensions:false});
check(()=>assert.equal(markPreflightV67(invalid).ok,false));
mkdirSync('artifacts/v67',{recursive:true});writeFileSync('artifacts/v67/standalone.svg',buildMarkSvgV67(multiple));writeFileSync('artifacts/v67/standalone.pdf',pdf);writeFileSync('artifacts/v67/model-results.json',JSON.stringify({status:'PASS',checks:count}));
console.log(`PASS V0.67: ${count} independent document, binding, layout and export checks`);
