import assert from 'node:assert/strict';
import {withPngDpiV70} from '../src/pngPrintV70.js';
import {mkdirSync,writeFileSync} from 'node:fs';
import {createMarkDocumentV67,setMarkArtboardV67,insertStandaloneMarkV67,patchStandaloneElementV67,markPreflightV67,buildMarkPdfV67,buildMarkSvgV67,parseMarkDocumentV67} from '../src/standaloneMarksV67.js';
import {barcodeGroupLayoutV70,barcodeChecksV70,assertBarcodeProductionV70} from '../src/barcodeGroupV70.js';
import {checkBarcodePdfV70,assertBarcodePdfV70} from '../src/barcodePdfCheckV70.js';
import {resizeStandaloneMarkV69} from '../src/standaloneTransformV69.js';
import {buildProductionPdf,buildMultiPagePdf} from '../src/export.js';
import {buildProductionPdfV27} from '../src/productionPdfV27.js';
import {defaultState} from '../src/model.js';

let checks=0;const check=fn=>{fn();checks++;};
const large=createMarkDocumentV67(),small=patchStandaloneElementV67(large,'label-barcode',{preset:'200x64'});
check(()=>assert.equal(markPreflightV67(large).ok,true));
check(()=>assert.equal(markPreflightV67({...large,variables:{...large.variables,packageCount:'3'}}).ok,true));
check(()=>assert.equal(markPreflightV67(small).ok,true));
check(()=>assert.deepEqual(large.elements.filter(e=>e.type==='barcode-qr-group').map(e=>[e.w,e.h]),[[250,80]]));
check(()=>assert.deepEqual(small.elements.filter(e=>e.type==='barcode-qr-group').map(e=>[e.w,e.h]),[[200,64]]));
const a=barcodeGroupLayoutV70({w:250,h:80}),b=barcodeGroupLayoutV70({w:200,h:64});
check(()=>{for(const key of Object.keys(a))assert.ok(Math.abs(b[key]/a[key]-.8)<1e-10,`${key} must scale uniformly`);});
for(const width of [20,100,180,225,300])check(()=>assert.throws(()=>patchStandaloneElementV67(large,'label-barcode',{w:width}),/禁止拆分/));
for(const corner of ['nw','ne','sw','se'])check(()=>{const s=resizeStandaloneMarkV69(large,'label-barcode',corner,1000,1000),e=s.elements.find(e=>e.id==='label-barcode');assert([200,250].includes(e.w));assert.equal(e.w/e.h,3.125);});
const blank=createMarkDocumentV67('blank');
check(()=>assert.equal(insertStandaloneMarkV67(blank,'barcodeQr').elements[0].w,250));
const narrow=setMarkArtboardV67(blank,220,100);
check(()=>assert.deepEqual(insertStandaloneMarkV67(narrow,'barcodeQr').elements.map(e=>[e.w,e.h]),[[200,64]]));
const occupied=setMarkArtboardV67(blank,320,100);occupied.elements=[{id:'block',type:'shape',panelId:'label',group:'marks',x:225,y:8,w:80,h:80,r:0}];
check(()=>assert.equal(insertStandaloneMarkV67(occupied,'barcodeQr').elements.at(-1).w,200));
const tiny=setMarkArtboardV67(blank,200,80),before=JSON.stringify(tiny);
check(()=>assert.throws(()=>insertStandaloneMarkV67(tiny,'barcodeQr'),e=>e.code==='MARK_NO_SPACE'));
check(()=>assert.equal(JSON.stringify(tiny),before));
for(const mutation of [e=>{e.w=100;e.h=32},e=>{e.w=225;e.h=72},e=>{e.r=90},e=>{e.x=2},e=>{e.lockAspect=false}]){
 const s=structuredClone(large);mutation(s.elements.find(e=>e.id==='label-barcode'));
 check(()=>assert.equal(markPreflightV67(s).ok,false));
 check(()=>assert.throws(()=>buildMarkPdfV67(s)));
}
const cover=structuredClone(large);cover.elements.push({id:'cover',type:'shape',panelId:'label',group:'marks',x:20,y:120,w:20,h:20,r:0});
check(()=>assert.ok(barcodeChecksV70(cover).some(c=>c.code==='BARCODE_OVERLAP'&&c.severity==='error')));
check(()=>assert.throws(()=>buildMarkPdfV67(cover),/重叠/));
cover.elements.at(-1).hidden=true;check(()=>assert.equal(markPreflightV67(cover).ok,true));
const split=structuredClone(large);split.elements.push({id:'split',type:'qr-code',panelId:'label',x:10,y:10,w:40,h:40,r:0});
check(()=>assert.throws(()=>parseMarkDocumentV67(JSON.stringify(split)),/无效/));
check(()=>assert.throws(()=>assertBarcodeProductionV70(split),/禁止拆分/));
const dense=patchStandaloneElementV67(large,'label-barcode',{barcodeValue:'A'.repeat(100)});
check(()=>assert.throws(()=>buildMarkPdfV67(dense),/过密/));
check(()=>assert.throws(()=>buildMarkPdfV67(patchStandaloneElementV67(large,'label-barcode',{qrValue:'X'.repeat(100)})),/QR/));
const borderline=patchStandaloneElementV67(large,'label-barcode',{barcodeValue:'A'.repeat(35)});
check(()=>assert.equal(markPreflightV67(borderline).ok,true));
check(()=>assert.equal(markPreflightV67(patchStandaloneElementV67(borderline,'label-barcode',{preset:'200x64'})).ok,false));
mkdirSync('artifacts/v70',{recursive:true});
const cases=[['CODE39','TEST-070'],['EAN13','5901234123457'],['UPCA','036000291452'],['ITF14','10012345000017'],['GS1_128','(01)09506000134352(10)LOT070']];
const manifest=[];
for(const [type,value]of cases)for(const width of [250,200]){
 let s=patchStandaloneElementV67(large,'label-barcode',{w:width,barcodeType:type,barcodeValue:value,qrValue:'BOXSTUDIO-070'});
 const bytes=buildMarkPdfV67(s),report=checkBarcodePdfV70(s,bytes)[0],file=`artifacts/v70/${type}-${width}.pdf`;
 check(()=>assert.equal(report.ok,true,JSON.stringify(report)));
 check(()=>assert.equal(report.qr.decoded,'BOXSTUDIO-070'));
 writeFileSync(file,bytes);manifest.push({file,barcode:type==='GS1_128'?'010950600013435210LOT070':value,qr:'BOXSTUDIO-070',width});
}
const multiple=setMarkArtboardV67(large,600,220);multiple.elements=multiple.elements.filter(e=>e.type==='barcode-qr-group');multiple.elements.push({...multiple.elements[0],id:'second-code',x:300,barcodeValue:'SECOND-070',qrValue:'SECOND-070'});
const multiplePdf=buildMarkPdfV67(multiple);
check(()=>assert.deepEqual(checkBarcodePdfV70(multiple,multiplePdf).map(x=>x.ok),[true,true]));
const damaged=new TextEncoder().encode(new TextDecoder().decode(multiplePdf).replace(/ re f/g,' re S'));
check(()=>assert.throws(()=>assertBarcodePdfV70(multiple,damaged),/解码失败/));
const badCarton=structuredClone(defaultState);badCarton.elements.find(e=>e.type==='barcode-qr-group').w=100;badCarton.elements.find(e=>e.type==='barcode-qr-group').h=32;
check(()=>assert.throws(()=>buildProductionPdf(badCarton),/250 × 80/));
check(()=>assert.throws(()=>buildProductionPdfV27(badCarton),/250 × 80/));
check(()=>assert.throws(()=>buildMultiPagePdf([defaultState,badCarton]),/250 × 80/));
check(()=>assert.doesNotMatch(buildMarkSvgV67(large),/selection-box|data-mark-resize/));
const sourcePng=new Uint8Array(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64'));
for(const dpi of [300,600]){const png=withPngDpiV70(sourcePng,dpi);let offset=8,physical=[];while(offset+12<=png.length){const view=new DataView(png.buffer),length=view.getUint32(offset),type=String.fromCharCode(...png.slice(offset+4,offset+8));if(type==='pHYs')physical.push([view.getUint32(offset+8),view.getUint32(offset+12),png[offset+16]]);offset+=length+12;}check(()=>assert.deepEqual(physical,[[Math.round(dpi/.0254),Math.round(dpi/.0254),1]]));writeFileSync(`artifacts/v70/metadata-${dpi}.png`,png);check(()=>assert.deepEqual(withPngDpiV70(png,dpi),png));}
check(()=>assert.throws(()=>withPngDpiV70(new Uint8Array([1]),300),/无效/));
check(()=>assert.throws(()=>withPngDpiV70(sourcePng,NaN),/无效/));
check(()=>assert.throws(()=>withPngDpiV70(sourcePng.slice(0,40),300),/不完整/));
writeFileSync('artifacts/v70/scan-manifest.json',JSON.stringify(manifest,null,2));
writeFileSync('artifacts/v70/model-results.json',JSON.stringify({status:'PASS',checks,printCases:manifest.length},null,2));
console.log(`PASS V0.70: ${checks} fixed-size, uniform layout, whole-group, fallback, obstruction, encoding density and generated-PDF decode checks; ${manifest.length} PDF scan fixtures`);
