import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {HANDLING_SYMBOLS_V72,handlingParamsV72,handlingPathsV72,handlingSvgV72,handlingPdfV72} from '../src/handlingSymbolsV72.js';
import {CODE_TYPES_V72,generatedCodeLayoutV72,generatedCodeFileSvgV72,insertGeneratedCodeV72} from '../src/codeGeneratorV72.js';
import {createMarkDocumentV67,patchStandaloneElementV67,parseMarkDocumentV67,buildMarkSvgV67,buildMarkPdfV67,markPreflightV67,insertStandaloneMarkV67} from '../src/standaloneMarksV67.js';
import {sceneAnimationFrameV72} from '../src/sceneAnimationV72.js';
let checks=0;const check=(ok,message)=>{assert.ok(ok,message);checks++;};mkdirSync('artifacts/v72/codes',{recursive:true});mkdirSync('artifacts/v72/symbols',{recursive:true});
check(HANDLING_SYMBOLS_V72.length===17,'17 different handling symbols');const unique=new Set();
for(const t of HANDLING_SYMBOLS_V72){let s=createMarkDocumentV67('blank');s=insertStandaloneMarkV67(s,t.id);const e=s.elements[0];check(e.icon===t.id,'Real symbol '+t.id);const ops=handlingPathsV72(e);unique.add(JSON.stringify(ops));check(ops.length>3&&ops.flatMap(x=>x.slice(1)).every(Number.isFinite),'Finite vector geometry '+t.id);check(parseMarkDocumentV67(JSON.stringify(s)).elements[0].icon===t.id,'Symbol survives JSON '+t.id);check(markPreflightV67(s).ok,'Symbol preflight '+t.id);const pdf=buildMarkPdfV67(s);check(pdf.length>800,'Vector PDF '+t.id);writeFileSync('artifacts/v72/symbols/'+t.id+'.pdf',pdf);writeFileSync('artifacts/v72/symbols/'+t.id+'.svg',buildMarkSvgV67(s));}
check(unique.size===17,'Every symbol has a distinct real path');
const stack=createMarkDocumentV67('blank'),stackState=insertStandaloneMarkV67(stack,'stackLimit'),stackEl=stackState.elements[0];
const updated=patchStandaloneElementV67(stackState,stackEl.id,{stackLimit:7});check(handlingSvgV72(updated.elements[0])!==handlingSvgV72(stackEl),'Layer count updates actual vector artwork');check(handlingPdfV72(updated.elements[0],8,8,100,72/25.4).join('\n')!==handlingPdfV72(stackEl,8,8,100,72/25.4).join('\n'),'Layer count updates actual PDF paths');assert.throws(()=>patchStandaloneElementV67(stackState,stackEl.id,{stackLimit:0}));assert.throws(()=>handlingParamsV72({icon:'temperature',temperatureMin:30,temperatureMax:20}));checks+=2;
const fixtures=[];for(const t of CODE_TYPES_V72){let s=createMarkDocumentV67('blank');const config={codeType:t.id,codeValue:t.example,w:160,h:55,codeShowText:true};s=insertGeneratedCodeV72(s,config);const e=s.elements[0],layout=generatedCodeLayoutV72(e,s.variables);check(layout.module>=layout.minimum,'Module size '+t.id);check(layout.rects.length>20,'Actual encoded modules '+t.id);check(layout.rects.every(r=>r.w>0&&r.h>0&&r.x>=0&&r.y>=0&&r.x+r.w<=e.w+1e-6&&r.y+r.h<=e.h+1e-6),'All encoded modules inside white quiet-zone box '+t.id);check(markPreflightV67(s).ok,'Code preflight '+t.id);check(parseMarkDocumentV67(JSON.stringify(s)).elements[0].codeValue===t.example,'Code editable JSON roundtrip '+t.id);writeFileSync(`artifacts/v72/codes/${t.id}.pdf`,buildMarkPdfV67(s));writeFileSync(`artifacts/v72/codes/${t.id}.svg`,generatedCodeFileSvgV72(e,s.variables));fixtures.push({type:t.id,value:layout.value,path:`${t.id}.pdf`});}
let unicode=createMarkDocumentV67('blank');unicode=insertGeneratedCodeV72(unicode,{codeType:'qrcode',codeValue:'箱子编号：测试-001',w:50,h:50,codeShowText:false});writeFileSync('artifacts/v72/codes/unicode-qr.pdf',buildMarkPdfV67(unicode));fixtures.push({type:'qrcode',value:'箱子编号：测试-001',path:'unicode-qr.pdf'});
check(generatedCodeLayoutV72({codeType:'ean13',codeValue:'690123456789',w:100,h:32}).value==='6901234567892','EAN check digit computed');assert.throws(()=>generatedCodeLayoutV72({codeType:'ean13',codeValue:'6901234567891',w:100,h:32}));assert.throws(()=>generatedCodeLayoutV72({codeType:'qrcode',codeValue:'A'.repeat(600),w:8,h:8}));assert.throws(()=>generatedCodeLayoutV72({codeType:'code128',codeValue:'',w:100,h:30}));checks+=3;
const vars=insertGeneratedCodeV72(createMarkDocumentV67('blank'),{codeType:'code128',codeValue:'{{sku}}',w:100,h:30});check(generatedCodeLayoutV72(vars.elements[0],{sku:'CUSTOM-001'}).value==='CUSTOM-001','Generated code binds editable variables');
const overlap=structuredClone(vars);overlap.elements.push({...overlap.elements[0],id:'duplicate'});check(!markPreflightV67(overlap).ok,'Overlapping white quiet zones block export');assert.throws(()=>buildMarkPdfV67(overlap));checks++;
const group=insertStandaloneMarkV67(createMarkDocumentV67('blank'),'barcodeQr');check(group.elements[0].type==='barcode-qr-group'&&group.elements[0].w===250&&group.elements[0].h===80,'Existing locked shipping combination remains intact');assert.throws(()=>patchStandaloneElementV67(group,group.selectedId,{w:100}));checks++;
const first=sceneAnimationFrameV72(0),last=sceneAnimationFrameV72(1),middle=sceneAnimationFrameV72(.5);check(first.progress===0&&last.progress===100&&Math.abs(middle.progress-50)<1e-6,'Recorded assembly uses actual continuous fold progression');check(Math.abs(sceneAnimationFrameV72(1,{mode:'turntable'}).settings.yaw-sceneAnimationFrameV72(0,{mode:'turntable'}).settings.yaw-Math.PI*2)<1e-6,'Turntable makes a full real revolution');
writeFileSync('artifacts/v72/codes/fixtures.json',JSON.stringify(fixtures,null,2));writeFileSync('artifacts/v72/model-results.json',JSON.stringify({status:'PASS',checks,symbols:17,codes:12}));console.log(`PASS V0.72: ${checks} handling-symbol, editable-parameter, encoding, production and animation checks`);
