import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {createMarkDocumentV67,setMarkArtboardV67,parseMarkDocumentV67,validateMarkDocumentV67,buildMarkSvgV67,buildMarkPdfV67,markPreflightV67} from '../src/standaloneMarksV67.js';
import {syncMarkFacesV74,switchMarkFaceV74} from '../src/markFacesV74.js';
import {FONTS_V74,registerFontV74,getFontV74,fontGlyphIssuesV74} from '../src/fontSystemV74.js';
import {ARTWORK_CATALOG_V74,createArtworkV74,artworkSvgV74,artworkPdfV74,artworkPrimitivesV74} from '../src/artworkLibraryV74.js';
import {zipStoredV74} from '../src/zipStoredV74.js';
import {lightingSettingsV74,LIGHT_RIGS_V74} from '../src/studioLightingV74.js';
let checks=0;const check=(condition,label)=>{assert.ok(condition,label);checks++;};
mkdirSync('artifacts/v74',{recursive:true});
let doc=syncMarkFacesV74(createMarkDocumentV67());const original=JSON.stringify(doc.elements);doc=switchMarkFaceV74(doc,'side',setMarkArtboardV67);check(doc.artboard.width===220&&doc.elements[0].id==='side-sku','Side has independent dimensions and objects');
doc=setMarkArtboardV67(doc,260,230);doc.elements[0].x=20;doc.variables.sku='SIDE-012';doc=syncMarkFacesV74(doc);doc=switchMarkFaceV74(doc,'front',setMarkArtboardV67);check(JSON.stringify(doc.elements)===original,'Switching preserves original front objects');check(doc.variables.sku==='SIDE-012','Faces share shipping data');doc=switchMarkFaceV74(doc,'side',setMarkArtboardV67);check(doc.artboard.width===260&&doc.elements[0].x===20,'Side dimensions and coordinates survive switching');doc=parseMarkDocumentV67(JSON.stringify(syncMarkFacesV74(doc)));check(doc.markFacesV74.front.elements.length===13,'Both faces survive JSON round trip');
const broken=structuredClone(doc);broken.markFacesV74.front.elements[0].panelId='outside';assert.throws(()=>validateMarkDocumentV67(broken));checks++;check(syncMarkFacesV74(createMarkDocumentV67('blank')).markFacesV74.front.elements.length===0,'Legacy blank files remain blank');
const fontSources=JSON.parse(readFileSync('assets/fonts-v74/sources.json','utf8'));
for(const row of fontSources){const bytes=readFileSync('assets/fonts-v74/'+row.file);check(createHash('sha256').update(bytes).digest('hex')===row.sha256,'Font hash '+row.file);registerFontV74(row.id,row.weight,bytes);check(Boolean(getFontV74(row.id,row.weight===700)?.cmap(65)),'Font has actual Latin outlines '+row.file);check(readFileSync('assets/fonts-v74/'+row.id+'-OFL.txt','utf8').includes('SIL OPEN FONT LICENSE'),'Font license '+row.id);}
for(const f of FONTS_V74){doc=createMarkDocumentV67('blank');doc.elements=[{id:'font-test',type:'text',group:'marks',panelId:'label',x:12,y:12,w:260,h:30,fontSize:7,r:0,template:f.id.endsWith('sc')?'纸箱正唛侧唛 · BOX 2026':'CARTON / BOX 2026',fontIdV74:f.id,bold:false}];check(markPreflightV67(doc,{pdf:true}).ok,'Per-object font supports PDF '+f.id);const svg=buildMarkSvgV67(doc),pdf=buildMarkPdfV67(doc);check(svg.includes('data-font-v74'),'SVG keeps chosen outline '+f.id);check(new TextDecoder().decode(pdf).includes(' c')||new TextDecoder().decode(pdf).includes(' l'),'PDF has vector text '+f.id);writeFileSync('artifacts/v74/font-'+f.id+'.svg',svg);writeFileSync('artifacts/v74/font-'+f.id+'.pdf',pdf);const bold=buildMarkSvgV67({...doc,elements:doc.elements.map(e=>({...e,bold:true}))});check(svg!==bold,'Real bold outlines differ '+f.id);}
check(fontGlyphIssuesV74({fontIdV74:'lato'},'侧唛').length===1,'Missing Chinese in Latin family is reported');
for(const asset of ARTWORK_CATALOG_V74){const original=readFileSync('assets/artwork-v74/'+asset.id+'.svg');check(createHash('sha256').update(original).digest('hex')===asset.sha256,'Asset source hash '+asset.id);const el=createArtworkV74(asset.id,{id:'label',w:320,h:220});el.group='marks';doc=createMarkDocumentV67('blank');doc.elements=[el];check(artworkPrimitivesV74(el).length>0&&artworkSvgV74(el).includes('<path'),'Asset keeps original vector '+asset.id);check(artworkPdfV74(el,0,0,220,72/25.4).some(x=>x==='S'||x==='f'||x==='B'),'Asset emits PDF path '+asset.id);writeFileSync('artifacts/v74/asset-'+asset.id+'.svg',buildMarkSvgV67(doc));writeFileSync('artifacts/v74/asset-'+asset.id+'.pdf',buildMarkPdfV67(doc));}
check(ARTWORK_CATALOG_V74.length===32,'32 actual source SVGs');
doc=syncMarkFacesV74(createMarkDocumentV67());const files=[];for(const face of ['front','side']){const s=switchMarkFaceV74(doc,face,setMarkArtboardV67);check(markPreflightV67(s).ok,'Default face scan preflight '+face);files.push({name:face+'.svg',bytes:buildMarkSvgV67(s)},{name:face+'.pdf',bytes:buildMarkPdfV67(s)});}files.push({name:'project.json',bytes:JSON.stringify(doc)});writeFileSync('artifacts/v74/both-marks.zip',zipStoredV74(files));
for(const rig of Object.keys(LIGHT_RIGS_V74)){const s=lightingSettingsV74({lightRig:rig});check(s.key>0&&s.elevation>=10,'Actual light rig '+rig);}const extreme=lightingSettingsV74({key:100,exposure:-10,elevation:200});check(extreme.key===8&&extreme.exposure===.3&&extreme.elevation===85,'Lighting validates bounds');
writeFileSync('artifacts/v74/model-results.json',JSON.stringify({status:'PASS',checks,assets:32,fontFamilies:4,faces:2}));console.log('PASS V0.74: '+checks+' face, font, source, vector export, ZIP and lighting checks');
