import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {FONTS_V74,registerFontV74,getFontV74,fontGlyphIssuesV74,fontTextSvgV74} from '../src/fontSystemV74.js';
import {layoutTextV76,textStyleV76,rotateTextCommandsV76} from '../src/textLayoutV76.js';
import {PATTERN_CATALOG_V76,createPatternV76,patternSvgV76,patternPrimitivesV76,patternSettingsV76} from '../src/patternLibraryV76.js';
import {createMarkDocumentV67,setMarkArtboardV67,buildMarkSvgV67,buildMarkPdfV67,parseMarkDocumentV67,validateMarkDocumentV67} from '../src/standaloneMarksV67.js';
import {syncMarkFacesV74,switchMarkFaceV74} from '../src/markFacesV74.js';
import {buildProductionPdf} from '../src/export.js';
import {buildProductionPdfV19} from '../src/exportV19.js';
import {buildProductionPdfV23} from '../src/productionPdfV23.js';
import {buildPanelArtworkPlan} from '../src/panelArtwork.js';
import {generateGeometry} from '../src/geometry.js';
import {commandsToSvgPath} from '../src/ttfOutline.js';
let checks=0;const check=(v,t)=>{assert.ok(v,t);checks++;};const proofNames=[];mkdirSync('artifacts/v76/proofs',{recursive:true});
const board=()=>setMarkArtboardV67(createMarkDocumentV67('blank'),120,90),write=(name,state,svg=buildMarkSvgV67(state),pdf=buildMarkPdfV67(state))=>{writeFileSync('artifacts/v76/proofs/'+name+'.svg',svg);writeFileSync('artifacts/v76/proofs/'+name+'.pdf',pdf);proofNames.push(name);};
for(const f of FONTS_V74)for(const weight of [400,700])registerFontV74(f.id,weight,readFileSync('assets/fonts-v74/'+f.id+'-'+weight+'.ttf'));
for(const f of FONTS_V74)for(const bold of [false,true])for(const direction of ['horizontal','vertical-rl'])for(const align of ['left','center','right','justify'])for(const decor of [false,true]){const el={id:'text',type:'text',panelId:'label',x:12,y:12,w:96,h:64,fontSize:6,fontIdV74:f.id,bold,r:0,template:f.id.endsWith('sc')?'纸箱正唛\nBOX 2026':'CARTON\nBOX 2026',textStyleV76:textStyleV76({direction,align,underline:decor,italic:decor,strike:decor,color:'#142e6b'})},l=layoutTextV76(getFontV74(f.id,bold),el.template,el);check(l.commands.length>20&&!l.overflow,'Font layout fits '+f.id+direction+align);check(l.commands.every(c=>Object.entries(c).filter(([k])=>k!=='op').every(([,n])=>Number.isFinite(n))),'Finite actual glyph geometry');check(!fontGlyphIssuesV74(el,el.template).length,'Loaded font and bounds preflight');check(fontTextSvgV74(el,el.template).includes('#142e6b'),'Real type color');}
for(const f of FONTS_V74)for(const [i,style]of [{align:'center',italic:true,underline:true},{align:'right',verticalAlign:'bottom',strike:true},{direction:'vertical-rl',align:'center'},{direction:'vertical-rl',align:'right',underline:true}].entries()){const doc=board();doc.elements=[{id:'proof',type:'text',group:'marks',panelId:'label',x:12,y:12,w:96,h:64,fontSize:6,fontIdV74:f.id,bold:i%2===1,r:0,template:f.id.endsWith('sc')?'纸箱正唛\nBOX 2026':'CARTON\nBOX 2026',textStyleV76:textStyleV76({...style,color:'#142e6b'})}];write('font-'+f.id+'-'+i,doc);}
const base={w:35,h:80,fontSize:6,textStyleV76:textStyleV76()},font=getFontV74('lato');check(layoutTextV76(font,'ONE TWO THREE FOUR FIVE SIX',base).lines>1,'Auto wrapping by actual glyph advances');check(layoutTextV76(font,'ONE TWO THREE FOUR FIVE SIX',{...base,textStyleV76:textStyleV76({wrap:false})}).overflow,'Unwrapped long type reports overflow');check(fontGlyphIssuesV74({...base,fontIdV74:'lato'},'侧唛').length>0,'Missing glyphs block export');for(const s of [{align:'bad'},{direction:'bad'},{color:'url(x)'},{letterSpacing:Infinity},{lineHeight:9},{wrap:'yes'}]){assert.throws(()=>textStyleV76(s));checks++;}
let dual=syncMarkFacesV74(createMarkDocumentV67());dual.elements[0].fontIdV74='sans-sc';dual.elements[0].textStyleV76=textStyleV76({align:'center'});dual=switchMarkFaceV74(dual,'side',setMarkArtboardV67);dual.elements[0].fontIdV74='serif-sc';dual.elements[0].textStyleV76=textStyleV76({direction:'vertical-rl',align:'right'});dual=syncMarkFacesV74(dual);dual=parseMarkDocumentV67(JSON.stringify(dual));check(dual.markFacesV74.front.elements[0].textStyleV76.align==='center'&&dual.markFacesV74.side.elements[0].textStyleV76.direction==='vertical-rl','Front and side type styles survive independent save/load');
for(const p of PATTERN_CATALOG_V76){const source=JSON.parse(readFileSync('assets/patterns-v76/sources.json')).find(s=>s.id===p.id),raw=readFileSync('assets/patterns-v76/'+p.id+'.svg');check(createHash('sha256').update(raw).digest('hex')===source.sha256,'Exact original SVG '+p.id);const el=createPatternV76(p.id,{id:'label',w:120,h:90},{tileSize:32,color:'#142e6b',background:'#f5f1e8'});Object.assign(el,{x:12,y:12,w:90,h:60,group:'marks'});const doc=board();doc.elements=[el];validateMarkDocumentV67(doc);check(patternPrimitivesV76(el).every(p=>p.ops.every(o=>o.slice(1).every(Number.isFinite))),'Finite original curves '+p.id);check(patternSvgV76(el).includes('Steve Schoger')&&!patternSvgV76(el).includes('<pattern'),'Explicit vectors and credit '+p.id);write('pattern-'+p.id,doc);check(parseMarkDocumentV67(JSON.stringify(doc)).elements[0].patternIdV76===p.id,'Pattern project round trip');check(buildPanelArtworkPlan(doc,generateGeometry(doc.structure),'label').commands[0].type==='pattern','Actual texture plan pattern');}
for(const id of ['leaf','houndstooth','topography','overcast']){const doc=board();doc.elements=[{...createPatternV76(id,{id:'label',w:120,h:90},{tileSize:32,color:'#142e6b',background:'#f5f1e8'}),x:12,y:12,w:90,h:60}];for(const [kind,build]of [['native',buildProductionPdfV23],['v19',buildProductionPdfV19]]){writeFileSync('artifacts/v76/proofs/'+kind+'-'+id+'.pdf',build(doc));}}
for(const [i,angle]of [15,45,90,-30].entries()){const doc=board(),el={id:'rotated',type:'text',group:'marks',panelId:'label',x:20,y:25,w:70,h:35,r:angle,fontSize:6,template:'BOX / 2026',fontIdV74:'lato',textStyleV76:textStyleV76({align:'center',verticalAlign:'center',italic:true,underline:true,color:'#142e6b'})};doc.elements=[el];const svg='<svg xmlns="http://www.w3.org/2000/svg" width="120mm" height="90mm" viewBox="0 0 120 90"><rect width="120" height="90" fill="white"/><g transform="translate(20 25) rotate('+angle+' 35 17.5)">'+fontTextSvgV74(el,el.template)+'</g></svg>';write('rotated-'+i,doc,svg,buildProductionPdf(doc));writeFileSync('artifacts/v76/proofs/native-rotated-'+i+'.pdf',buildProductionPdfV23(doc));check(rotateTextCommandsV76(layoutTextV76(font,el.template,el).commands,angle,70,35).length>20,'Rotated shared glyphs');}
assert.throws(()=>patternSettingsV76({...createPatternV76('leaf',{id:'label',w:120,h:90}),tileSizeV76:0}));checks++;check(PATTERN_CATALOG_V76.length===87,'87 actual patterns');writeFileSync('artifacts/v76/model-results.json',JSON.stringify({status:'PASS',checks,proofNames,fonts:12,patterns:87},null,2));console.log('PASS V0.76: '+checks+' glyph, physical layout, source, PDF, texture and independent-face assertions');
