import assert from 'node:assert/strict';import{createServer}from'node:http';import{createReadStream}from'node:fs';import{mkdir,writeFile}from'node:fs/promises';import{resolve,extname}from'node:path';import puppeteer from'puppeteer-core';
const root=resolve('.'),server=createServer((req,res)=>{const p=new URL(req.url,'http://local').pathname,file=resolve(root,'.'+(p==='/'||p==='/marks'?'/index.html':p));if(!file.startsWith(root+'/'))return res.writeHead(403).end();res.setHeader('Content-Type',({'.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.json':'application/json'}[extname(file)]||'application/octet-stream'));const s=createReadStream(file);s.on('error',()=>res.writeHead(404).end());s.pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));await mkdir('artifacts/v78',{recursive:true});
const browser=await puppeteer.launch({executablePath:process.argv[2]||'/tmp/boxstudio-v78-chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader']}),page=await browser.newPage(),errors=[];page.setDefaultTimeout(90000);page.on('pageerror',e=>errors.push(e.message));let checks=0;const check=(v,m)=>{assert.ok(v,m);checks++;},pause=ms=>new Promise(r=>setTimeout(r,ms));
const base=process.env.BOXSTUDIO_URL||'http://127.0.0.1:'+server.address().port;
try{await page.setViewport({width:1440,height:960});await page.goto(base);await page.waitForFunction(()=>window.BoxStudioV77);
await page.evaluate(async()=>{const{createArtworkProjectV71}=await import('/src/designTemplatesV71.js');window.BoxStudioEditor.commitState(createArtworkProjectV71(window.BoxStudioEditor.getState(),'coffee-roast',{templateId:'roll-lock-mailer'}));window.BoxStudioEditor.navigate('editor','3D');});await page.waitForSelector('[data-v78-player="stage"]');await page.waitForFunction(()=>window.BoxStudioV52?.getProof?.()?.getDebugState()?.renderCount>0);
const selector='[data-v78-player="stage"] ',debug=()=>page.evaluate(()=>window.BoxStudioV52.getProof().getDebugState());
await page.click(selector+'[data-v78-fit]');await page.screenshot({path:'artifacts/v78/closed-stage.png'});await page.click(selector+'[data-v78-stage="0"]');const flat=await debug();await page.click(selector+'[data-v78-play]');await pause(1200);await page.click(selector+'[data-v78-play]');const mid=await debug();check(mid.progress>0&&mid.progress<100,'Real model folds during playback');check(JSON.stringify(mid.meshes)!==JSON.stringify(flat.meshes),'Actual vertices move');await pause(300);check(Math.abs((await debug()).progress-mid.progress)<.01,'Pause freezes actual geometry');check(JSON.stringify(mid.framing)===JSON.stringify((await debug()).framing),'Assembly framing stays fixed');await page.screenshot({path:'artifacts/v78/paused-stage.png'});
await page.evaluate(()=>{const p=window.BoxStudioV78.getPlayer();p.configure({durationMs:12000});document.querySelector('[data-v78-player="stage"] [data-v78-direction]').click();document.querySelector('[data-v78-player="stage"] [data-v78-play]').click();});await pause(500);await page.evaluate(()=>document.querySelector('[data-v78-player="stage"] [data-v78-play]').click());check((await debug()).progress<mid.progress,'Reverse drives actual hinges backwards');
await page.$eval(selector+'[data-v78-progress]',e=>{e.value='65';e.dispatchEvent(new Event('input',{bubbles:true}));});await pause(80);check(Math.abs((await debug()).progress-65)<.01,'Scrub positions the real model');await page.select(selector+'[data-v78-speed]','2');await page.select(selector+'[data-v78-duration]','3000');await page.click(selector+'[data-v78-direction]');await page.click(selector+'[data-v78-play]');await page.waitForFunction(()=>window.BoxStudioV52.getProof().getDebugState().progress===100,{timeout:15000});check(true,'Speed/duration complete at actual endpoint');
await page.click(selector+'[data-v78-map]');check(await page.$eval('.v49-map-pane',e=>getComputedStyle(e).display!=='none'),'2D linked map toggles');await page.click(selector+'[data-v78-map]');
await page.evaluate(async()=>{const{openArtworkLibraryV75}=await import('/src/resourceUiV75.js');openArtworkLibraryV75();});await page.select('[data-v78-style]','filled');await page.type('[data-v74-search]','apple');await page.waitForSelector('[data-v74-asset="tabler-apple"]');await page.waitForFunction(()=>document.querySelector('[data-v74-asset="tabler-apple"] img')?.naturalWidth>0);check(await page.$eval('[data-v74-asset="tabler-apple"] img',e=>e.complete&&e.naturalWidth>0),'Original filled SVG thumbnail loads');await page.click('[data-v74-asset="tabler-apple"]');check(await page.evaluate(()=>window.BoxStudioEditor.getState().elements.some(e=>e.assetIdV74==='tabler-apple')),'New vector inserts in paper project');await page.screenshot({path:'artifacts/v78/filled-library.png'});await page.click('[data-v74-close]');
await page.evaluate(()=>window.BoxStudioEditor.navigate('editor','Structure'));await page.waitForSelector('[data-v78-player="sidebar"]');await page.click('[data-v78-player="sidebar"] [data-v78-play]');await pause(1100);await page.click('[data-v78-player="sidebar"] [data-v78-play]');check(await page.$eval('[data-v78-player="sidebar"] [data-v78-progress]',e=>+e.value>0&&+e.value<100),'Sidebar has real independent player');await page.screenshot({path:'artifacts/v78/sidebar.png'});
await page.goto(base.replace(/\/$/,'')+'/marks');await page.waitForFunction(()=>window.BoxStudioV67?.getMarkState?.());await page.evaluate(async()=>{const{createMarkDocumentV67}=await import('/src/standaloneMarksV67.js'),{standaloneMarkUiV67}=await import('/src/standaloneMarkUiV67.js');standaloneMarkUiV67.commit(createMarkDocumentV67('blank'));});await page.evaluate(async()=>{const{openArtworkLibraryV75}=await import('/src/resourceUiV75.js');openArtworkLibraryV75();});await page.select('[data-v78-style]','filled');await page.type('[data-v74-search]','apple');await page.click('[data-v74-asset="tabler-apple"]');check(await page.evaluate(()=>window.BoxStudioV67.getMarkState().elements.some(e=>e.assetIdV74==='tabler-apple')),'Standalone marks use same complete filled library');await page.click('[data-v74-close]');
for(const width of [1024,768,390]){await page.setViewport({width,height:844});await page.evaluate(()=>window.BoxStudioEditor.navigate('editor','3D'));await page.waitForSelector('[data-v78-player="stage"]');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No horizontal overflow '+width);check(await page.$eval('[data-v78-player="stage"]',e=>{const r=e.getBoundingClientRect();return r.width>0&&r.right<=innerWidth+1}),'Playback controls fit '+width);await page.click('[data-v78-player="stage"] [data-v78-fit]');check(await page.$eval('[data-v78-player="stage"] [data-v78-play]',e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('[data-v78-play]')===e;}),'Actual playback button is reachable '+width);await page.screenshot({path:'artifacts/v78/stage-'+width+'.png'});}
check(errors.length===0,'No page errors: '+errors.join(';'));await writeFile('artifacts/v78/browser-results.json',JSON.stringify({status:'PASS',checks,errors},null,2));console.log('PASS V78 browser: '+checks+' actual play/pause/reverse/scrub/library/sidebar/independent marks/responsive checks');
}catch(e){await page.screenshot({path:'artifacts/v78/failure.png'});console.error(errors);throw e;}finally{await browser.close();server.close();}
