import { randomBytes } from 'node:crypto';
import { BackendError, canHostedActionV36, canonicalJsonV36, sha256JsonV36, sha256TextV36, verifyPasswordCredentialV36 } from './domainV36.mjs';

export const V37_BACKEND_SCHEMA='boxstudio-hosted-backend-v37';
const AUDIT_LOCK=37003702;
const clone=value=>structuredClone(value);
const iso=value=>value==null?null:new Date(value).toISOString();
const normalizeEmail=value=>String(value||'').trim().toLowerCase();
const slug=value=>String(value||'project').trim().toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'project';
const revisionKey=(projectId,revision)=>`${projectId}@${revision}`;
const authError=(message='Authentication required.')=>new BackendError(message,{status:401,code:'UNAUTHENTICATED'});
const forbidden=action=>new BackendError(`Authenticated user cannot perform ${action}.`,{status:403,code:'FORBIDDEN'});
const missing=(kind,id)=>new BackendError(`${kind} not found: ${id}.`,{status:404,code:'NOT_FOUND'});
const conflict=(message,detail=null,code='CONFLICT')=>new BackendError(message,{status:409,code,detail});
function sanitizeUser(row){return{id:row.id,email:row.email,name:row.name,role:row.role,active:row.active!==false};}
function assertWorkflow(status,allowed,action){if(!allowed.includes(status))throw conflict(`${action} is not allowed while revision status is ${status||'unknown'}.`);}

async function withTx(pool,fn){const client=await pool.connect();try{await client.query('BEGIN');const result=await fn(client);await client.query('COMMIT');return result;}catch(error){try{await client.query('ROLLBACK');}catch{}throw error;}finally{client.release();}}

function publicWorkflow(row){return{status:row.status,submittedAt:iso(row.submitted_at),submittedBy:row.submitted_by,approvedAt:iso(row.approved_at),approvedBy:row.approved_by,rejectedAt:iso(row.rejected_at),rejectedBy:row.rejected_by,reason:String(row.workflow_reason||'')};}
function publicRevisionRow(row,{includeSnapshot=true}={}){const out={schema:'boxstudio-artwork-revision-v37',projectId:row.project_id,revision:Number(row.revision),parentRevision:row.parent_revision==null?null:Number(row.parent_revision),createdAt:iso(row.created_at),createdBy:row.created_by,reason:String(row.revision_reason||''),snapshotHash:row.snapshot_hash,workflow:publicWorkflow(row)};if(includeSnapshot)out.snapshot=clone(row.snapshot);return out;}
function projectSummaryRow(row){return{id:row.id,name:row.name,createdAt:iso(row.created_at),createdBy:row.created_by,updatedAt:iso(row.updated_at),updatedBy:row.updated_by,currentRevision:Number(row.current_revision),currentStatus:row.current_status||'draft',revisionCount:Number(row.revision_count||row.current_revision||0)};}

export function verifyAuditEventsV37(events=[]){let prev='GENESIS';for(let i=0;i<events.length;i++){const event=events[i];if(Number(event.seq)!==i+1||event.prevHash!==prev)return{ok:false,index:i,reason:'sequence-or-prev-hash'};const payload={...event};delete payload.hash;const expected=sha256JsonV36(payload);if(expected!==event.hash)return{ok:false,index:i,reason:'hash-mismatch',expected,actual:event.hash};prev=event.hash;}return{ok:true,count:events.length,head:prev};}

export function createHostedBackendV37({pool,sessionTtlMs=8*60*60*1000,now=()=>new Date(),tokenFactory=()=>randomBytes(24).toString('hex')}={}){
  if(!pool?.connect)throw new Error('V0.37 backend requires a PostgreSQL pool.');
  const nowIso=()=>now().toISOString();

  async function appendAudit(client,{actorId,action,resource='system',resourceId='',projectId='',revision=null,reason='',metadata={}}){
    await client.query('SELECT pg_advisory_xact_lock($1)',[AUDIT_LOCK]);
    const last=(await client.query('SELECT seq,hash FROM audit_events ORDER BY seq DESC LIMIT 1')).rows[0],seq=last?Number(last.seq)+1:1,prevHash=last?.hash||'GENESIS';
    const payload={schema:'boxstudio-audit-event-v37',seq,id:`audit-${seq}`,at:nowIso(),actorId:String(actorId||'system'),action:String(action),resource:String(resource),resourceId:String(resourceId||''),projectId:String(projectId||''),revision:revision==null?null:Number(revision),reason:String(reason||''),metadata:clone(metadata||{}),prevHash};
    payload.hash=sha256JsonV36(payload);
    await client.query(`INSERT INTO audit_events(seq,id,at,actor_id,action,resource,resource_id,project_id,revision,reason,metadata,prev_hash,hash)
      VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13)`,[seq,payload.id,payload.at,payload.actorId,payload.action,payload.resource,payload.resourceId,payload.projectId,payload.revision,payload.reason,JSON.stringify(payload.metadata),payload.prevHash,payload.hash]);
    return payload;
  }

  async function requireSession(client,token){
    const tokenHash=sha256TextV36(String(token||''));if(!token)throw authError();
    const result=await client.query(`SELECT s.token_hash,s.issued_at,s.expires_at,u.id,u.email,u.name,u.role,u.active
      FROM hosted_sessions s JOIN hosted_users u ON u.id=s.user_id WHERE s.token_hash=$1`,[tokenHash]);
    const row=result.rows[0];if(!row)throw authError();if(row.active===false)throw authError('User is inactive.');if(new Date(row.expires_at).getTime()<=now().getTime()){await client.query('DELETE FROM hosted_sessions WHERE token_hash=$1',[tokenHash]);throw authError('Session expired.');}
    return{session:{tokenHash,issuedAt:iso(row.issued_at),expiresAt:iso(row.expires_at)},user:sanitizeUser(row)};
  }
  async function authorize(client,token,action){const context=await requireSession(client,token);if(!canHostedActionV36(context.user.role,action))throw forbidden(action);return context;}

  async function mutation(token,{permission,operation,idempotencyKey='',request={}},perform){
    return withTx(pool,async client=>{
      const {user}=await authorize(client,token,permission),key=String(idempotencyKey||'').trim(),requestHash=sha256JsonV36(request);
      if(key){
        if(key.length>200)throw new BackendError('Idempotency-Key exceeds 200 characters.',{code:'IDEMPOTENCY_KEY_TOO_LONG'});
        const scope=`${user.id}|${operation}|${key}`;await client.query('SELECT pg_advisory_xact_lock(hashtext($1))',[scope]);
        const existing=(await client.query('SELECT request_hash,response_json FROM idempotency_records WHERE actor_id=$1 AND operation=$2 AND idempotency_key=$3',[user.id,operation,key])).rows[0];
        if(existing){if(existing.request_hash!==requestHash)throw conflict('Idempotency-Key was already used with a different request.',{operation,key},'IDEMPOTENCY_CONFLICT');return clone(existing.response_json);}
      }
      const response=await perform(client,user);
      if(key)await client.query('INSERT INTO idempotency_records(actor_id,operation,idempotency_key,request_hash,response_json,created_at) VALUES($1,$2,$3,$4,$5::jsonb,$6)',[user.id,operation,key,requestHash,JSON.stringify(response),nowIso()]);
      return response;
    });
  }

  async function fetchRevision(client,projectId,revision,{includeSnapshot=true,forUpdate=false}={}){
    const lock=forUpdate?' FOR UPDATE OF w':'';
    const result=await client.query(`SELECT r.project_id,r.revision,r.parent_revision,r.created_at,r.created_by,r.reason AS revision_reason,r.snapshot_hash,r.snapshot,
      w.status,w.submitted_at,w.submitted_by,w.approved_at,w.approved_by,w.rejected_at,w.rejected_by,w.reason AS workflow_reason
      FROM artwork_revisions r JOIN revision_workflows w ON w.project_id=r.project_id AND w.revision=r.revision
      WHERE r.project_id=$1 AND r.revision=$2${lock}`,[projectId,Number(revision)]);
    if(!result.rows[0])throw missing('Revision',revision);return publicRevisionRow(result.rows[0],{includeSnapshot});
  }

  return{
    schema:V37_BACKEND_SCHEMA,
    async health(){const migration=(await pool.query('SELECT version,checksum,applied_at FROM schema_migrations ORDER BY applied_at DESC LIMIT 1')).rows[0]||null;return{ok:true,schema:V37_BACKEND_SCHEMA,durable:true,migration:migration?{version:migration.version,checksum:migration.checksum,appliedAt:iso(migration.applied_at)}:null};},
    async login({email,password}){return withTx(pool,async client=>{const row=(await client.query('SELECT * FROM hosted_users WHERE email=$1',[normalizeEmail(email)])).rows[0];if(!row||row.active===false||!verifyPasswordCredentialV36(password,row.credential))throw authError('Invalid email or password.');const token=tokenFactory(),tokenHash=sha256TextV36(token),issuedAt=nowIso(),expiresAt=new Date(now().getTime()+sessionTtlMs).toISOString();await client.query('INSERT INTO hosted_sessions(token_hash,user_id,issued_at,expires_at) VALUES($1,$2,$3,$4)',[tokenHash,row.id,issuedAt,expiresAt]);await appendAudit(client,{actorId:row.id,action:'auth.login',resource:'session',resourceId:tokenHash.slice(0,16)});return{token,expiresAt,user:sanitizeUser(row)};});},
    async logout(token){return withTx(pool,async client=>{const tokenHash=sha256TextV36(String(token||'')),existing=(await client.query('DELETE FROM hosted_sessions WHERE token_hash=$1 RETURNING user_id',[tokenHash])).rows[0];if(existing)await appendAudit(client,{actorId:existing.user_id,action:'auth.logout',resource:'session'});return{ok:true};});},
    async getSession(token){const client=await pool.connect();try{const {session,user}=await requireSession(client,token);return{expiresAt:session.expiresAt,user};}finally{client.release();}},
    async listProjects(token){const client=await pool.connect();try{await authorize(client,token,'project:read');const result=await client.query(`SELECT p.*,w.status AS current_status,(SELECT count(*) FROM artwork_revisions r WHERE r.project_id=p.id) AS revision_count FROM hosted_projects p LEFT JOIN revision_workflows w ON w.project_id=p.id AND w.revision=p.current_revision ORDER BY p.updated_at DESC`);return result.rows.map(projectSummaryRow);}finally{client.release();}},
    async createProject(token,{id,name,state,reason=''}={},options={}){const request={id,name,state,reason};return mutation(token,{permission:'project:create',operation:'project.create',idempotencyKey:options.idempotencyKey,request},async(client,user)=>{const projectId=slug(id||name||state?.projectName||'boxstudio-project'),exists=(await client.query('SELECT 1 FROM hosted_projects WHERE id=$1',[projectId])).rows[0];if(exists)throw conflict(`Project already exists: ${projectId}.`);const at=nowIso(),snapshot=clone(state||{}),snapshotHash=sha256JsonV36(snapshot);await client.query('INSERT INTO hosted_projects(id,name,created_at,created_by,updated_at,updated_by,current_revision) VALUES($1,$2,$3,$4,$3,$4,1)',[projectId,String(name||state?.projectName||projectId),at,user.id]);await client.query('INSERT INTO artwork_revisions(project_id,revision,parent_revision,created_at,created_by,reason,snapshot_hash,snapshot) VALUES($1,1,NULL,$2,$3,$4,$5,$6::jsonb)',[projectId,at,user.id,String(reason||''),snapshotHash,JSON.stringify(snapshot)]);await client.query("INSERT INTO revision_workflows(project_id,revision,status,reason) VALUES($1,1,'draft','')",[projectId]);await appendAudit(client,{actorId:user.id,action:'project.created',resource:'project',resourceId:projectId,projectId,revision:1,reason,metadata:{snapshotHash}});await appendAudit(client,{actorId:user.id,action:'revision.created',resource:'revision',resourceId:revisionKey(projectId,1),projectId,revision:1,reason,metadata:{snapshotHash}});const row=(await client.query(`SELECT p.*,w.status AS current_status,1 AS revision_count FROM hosted_projects p JOIN revision_workflows w ON w.project_id=p.id AND w.revision=1 WHERE p.id=$1`,[projectId])).rows[0];return{...projectSummaryRow(row),revision:await fetchRevision(client,projectId,1)};});},
    async getProject(token,projectId){const client=await pool.connect();try{await authorize(client,token,'project:read');const row=(await client.query(`SELECT p.*,w.status AS current_status,(SELECT count(*) FROM artwork_revisions r WHERE r.project_id=p.id) AS revision_count FROM hosted_projects p JOIN revision_workflows w ON w.project_id=p.id AND w.revision=p.current_revision WHERE p.id=$1`,[projectId])).rows[0];if(!row)throw missing('Project',projectId);return{...projectSummaryRow(row),revision:await fetchRevision(client,projectId,row.current_revision)};}finally{client.release();}},
    async listRevisions(token,projectId){const client=await pool.connect();try{await authorize(client,token,'revision:read');const result=await client.query(`SELECT r.project_id,r.revision,r.parent_revision,r.created_at,r.created_by,r.reason AS revision_reason,r.snapshot_hash,r.snapshot,w.status,w.submitted_at,w.submitted_by,w.approved_at,w.approved_by,w.rejected_at,w.rejected_by,w.reason AS workflow_reason FROM artwork_revisions r JOIN revision_workflows w ON w.project_id=r.project_id AND w.revision=r.revision WHERE r.project_id=$1 ORDER BY r.revision DESC`,[projectId]);if(!result.rows.length&&(await client.query('SELECT 1 FROM hosted_projects WHERE id=$1',[projectId])).rowCount===0)throw missing('Project',projectId);return result.rows.map(row=>publicRevisionRow(row,{includeSnapshot:false}));}finally{client.release();}},
    async getRevision(token,projectId,revision){const client=await pool.connect();try{await authorize(client,token,'revision:read');return await fetchRevision(client,projectId,revision);}finally{client.release();}},
    async createRevision(token,projectId,{state,expectedRevision,reason=''}={},options={}){const request={projectId,state,expectedRevision,reason};return mutation(token,{permission:'revision:create',operation:'revision.create',idempotencyKey:options.idempotencyKey,request},async(client,user)=>{const project=(await client.query('SELECT * FROM hosted_projects WHERE id=$1 FOR UPDATE',[projectId])).rows[0];if(!project)throw missing('Project',projectId);const expected=Number(expectedRevision);if(!Number.isInteger(expected)||expected!==Number(project.current_revision))throw conflict('Project revision conflict.',{expected:Number(project.current_revision),actual:Number.isFinite(expected)?expected:null});const revision=expected+1,at=nowIso(),snapshot=clone(state||{}),snapshotHash=sha256JsonV36(snapshot);await client.query('INSERT INTO artwork_revisions(project_id,revision,parent_revision,created_at,created_by,reason,snapshot_hash,snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)',[projectId,revision,expected,at,user.id,String(reason||''),snapshotHash,JSON.stringify(snapshot)]);await client.query("INSERT INTO revision_workflows(project_id,revision,status,reason) VALUES($1,$2,'draft','')",[projectId,revision]);await client.query('UPDATE hosted_projects SET current_revision=$2,updated_at=$3,updated_by=$4 WHERE id=$1',[projectId,revision,at,user.id]);await appendAudit(client,{actorId:user.id,action:'revision.created',resource:'revision',resourceId:revisionKey(projectId,revision),projectId,revision,reason,metadata:{parentRevision:expected,snapshotHash}});return await fetchRevision(client,projectId,revision);});},
    async submitRevision(token,projectId,revision,{reason=''}={},options={}){const request={projectId,revision:Number(revision),reason};return mutation(token,{permission:'revision:submit',operation:'revision.submit',idempotencyKey:options.idempotencyKey,request},async(client,user)=>{const current=await fetchRevision(client,projectId,revision,{includeSnapshot:false,forUpdate:true});assertWorkflow(current.workflow.status,['draft'],'Submit');const at=nowIso();await client.query("UPDATE revision_workflows SET status='submitted',submitted_at=$3,submitted_by=$4,reason=$5 WHERE project_id=$1 AND revision=$2",[projectId,Number(revision),at,user.id,String(reason||'')]);await client.query('UPDATE hosted_projects SET updated_at=$2,updated_by=$3 WHERE id=$1',[projectId,at,user.id]);await appendAudit(client,{actorId:user.id,action:'revision.submitted',resource:'revision',resourceId:revisionKey(projectId,revision),projectId,revision:Number(revision),reason,metadata:{snapshotHash:current.snapshotHash}});return await fetchRevision(client,projectId,revision,{includeSnapshot:false});});},
    async approveRevision(token,projectId,revision,{reason=''}={},options={}){const request={projectId,revision:Number(revision),reason};return mutation(token,{permission:'revision:approve',operation:'revision.approve',idempotencyKey:options.idempotencyKey,request},async(client,user)=>{const current=await fetchRevision(client,projectId,revision,{includeSnapshot:false,forUpdate:true});assertWorkflow(current.workflow.status,['submitted'],'Approve');if(current.workflow.submittedBy===user.id||current.createdBy===user.id)throw new BackendError('Separation of duties: the revision author/submitter cannot approve the same revision.',{status:403,code:'SEPARATION_OF_DUTIES'});const at=nowIso();await client.query("UPDATE revision_workflows SET status='approved',approved_at=$3,approved_by=$4,reason=$5 WHERE project_id=$1 AND revision=$2",[projectId,Number(revision),at,user.id,String(reason||'')]);await client.query('UPDATE hosted_projects SET updated_at=$2,updated_by=$3 WHERE id=$1',[projectId,at,user.id]);await appendAudit(client,{actorId:user.id,action:'revision.approved',resource:'revision',resourceId:revisionKey(projectId,revision),projectId,revision:Number(revision),reason,metadata:{snapshotHash:current.snapshotHash}});return await fetchRevision(client,projectId,revision,{includeSnapshot:false});});},
    async rejectRevision(token,projectId,revision,{reason=''}={},options={}){if(!String(reason||'').trim())throw new BackendError('Rejection reason is required.',{code:'REJECTION_REASON_REQUIRED'});const request={projectId,revision:Number(revision),reason};return mutation(token,{permission:'revision:reject',operation:'revision.reject',idempotencyKey:options.idempotencyKey,request},async(client,user)=>{const current=await fetchRevision(client,projectId,revision,{includeSnapshot:false,forUpdate:true});assertWorkflow(current.workflow.status,['submitted'],'Reject');if(current.workflow.submittedBy===user.id)throw new BackendError('Separation of duties: the submitter cannot reject the same revision.',{status:403,code:'SEPARATION_OF_DUTIES'});const at=nowIso();await client.query("UPDATE revision_workflows SET status='rejected',rejected_at=$3,rejected_by=$4,reason=$5 WHERE project_id=$1 AND revision=$2",[projectId,Number(revision),at,user.id,String(reason)]);await client.query('UPDATE hosted_projects SET updated_at=$2,updated_by=$3 WHERE id=$1',[projectId,at,user.id]);await appendAudit(client,{actorId:user.id,action:'revision.rejected',resource:'revision',resourceId:revisionKey(projectId,revision),projectId,revision:Number(revision),reason,metadata:{snapshotHash:current.snapshotHash}});return await fetchRevision(client,projectId,revision,{includeSnapshot:false});});},
    async productionGate(token,projectId,revision){const client=await pool.connect();try{await authorize(client,token,'revision:export');const current=await fetchRevision(client,projectId,revision,{includeSnapshot:false});if(current.workflow.status!=='approved')throw conflict(`Revision ${revision} is ${current.workflow.status}, not approved.`);return{ok:true,projectId,revision:Number(revision),snapshotHash:current.snapshotHash,approvedAt:current.workflow.approvedAt,approvedBy:current.workflow.approvedBy};}finally{client.release();}},
    async createProductionArchive(token,projectId,revision,{reason=''}={},options={}){const request={projectId,revision:Number(revision),reason};return mutation(token,{permission:'revision:export',operation:'archive.create',idempotencyKey:options.idempotencyKey,request},async(client,user)=>{const existing=(await client.query('SELECT * FROM production_archives WHERE project_id=$1 AND revision=$2',[projectId,Number(revision)])).rows[0];if(existing)return{archiveId:existing.archive_id,projectId:existing.project_id,revision:Number(existing.revision),snapshotHash:existing.snapshot_hash,manifestHash:existing.manifest_hash,archiveHash:existing.archive_hash,createdAt:iso(existing.created_at),createdBy:existing.created_by,archive:clone(existing.archive_json)};const current=await fetchRevision(client,projectId,revision,{includeSnapshot:true});if(current.workflow.status!=='approved')throw conflict(`Revision ${revision} is ${current.workflow.status}, not approved.`);const createdAt=nowIso(),manifest={schema:'boxstudio-production-manifest-v37',projectId,revision:Number(revision),snapshotHash:current.snapshotHash,approvedAt:current.workflow.approvedAt,approvedBy:current.workflow.approvedBy,archivedAt:createdAt},manifestHash=sha256JsonV36(manifest),archive={schema:'boxstudio-production-archive-v37',manifest,snapshot:current.snapshot},archiveHash=sha256JsonV36(archive),archiveId=`archive-${slug(projectId)}-r${Number(revision)}-${current.snapshotHash.slice(0,12)}`;await client.query('INSERT INTO production_archives(archive_id,project_id,revision,snapshot_hash,manifest_hash,archive_hash,archive_json,created_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9)',[archiveId,projectId,Number(revision),current.snapshotHash,manifestHash,archiveHash,JSON.stringify(archive),createdAt,user.id]);await appendAudit(client,{actorId:user.id,action:'archive.created',resource:'production-archive',resourceId:archiveId,projectId,revision:Number(revision),reason,metadata:{snapshotHash:current.snapshotHash,manifestHash,archiveHash}});return{archiveId,projectId,revision:Number(revision),snapshotHash:current.snapshotHash,manifestHash,archiveHash,createdAt,createdBy:user.id,archive};});},
    async getProductionArchive(token,projectId,revision){const client=await pool.connect();try{await authorize(client,token,'revision:read');const row=(await client.query('SELECT * FROM production_archives WHERE project_id=$1 AND revision=$2',[projectId,Number(revision)])).rows[0];if(!row)throw missing('Production archive',`${projectId}@${revision}`);return{archiveId:row.archive_id,projectId:row.project_id,revision:Number(row.revision),snapshotHash:row.snapshot_hash,manifestHash:row.manifest_hash,archiveHash:row.archive_hash,createdAt:iso(row.created_at),createdBy:row.created_by,archive:clone(row.archive_json)};}finally{client.release();}},
    async getAudit(token,{projectId=null,afterSeq=0}={}){const client=await pool.connect();try{await authorize(client,token,'audit:read');const params=[Number(afterSeq||0)],where=['seq>$1'];if(projectId){params.push(projectId);where.push(`project_id=$${params.length}`);}const result=await client.query(`SELECT * FROM audit_events WHERE ${where.join(' AND ')} ORDER BY seq`,params);return result.rows.map(row=>({schema:'boxstudio-audit-event-v37',seq:Number(row.seq),id:row.id,at:iso(row.at),actorId:row.actor_id,action:row.action,resource:row.resource,resourceId:row.resource_id,projectId:row.project_id,revision:row.revision==null?null:Number(row.revision),reason:row.reason,metadata:clone(row.metadata),prevHash:row.prev_hash,hash:row.hash}));}finally{client.release();}},
    async verifyAudit(token){const client=await pool.connect();try{await authorize(client,token,'audit:verify');const rows=(await client.query('SELECT * FROM audit_events ORDER BY seq')).rows.map(row=>({schema:'boxstudio-audit-event-v37',seq:Number(row.seq),id:row.id,at:iso(row.at),actorId:row.actor_id,action:row.action,resource:row.resource,resourceId:row.resource_id,projectId:row.project_id,revision:row.revision==null?null:Number(row.revision),reason:row.reason,metadata:clone(row.metadata),prevHash:row.prev_hash,hash:row.hash}));return verifyAuditEventsV37(rows);}finally{client.release();}},
    async _debugCounts(){const names=['hosted_projects','artwork_revisions','audit_events','idempotency_records','production_archives','hosted_sessions'];const out={};for(const name of names)out[name]=Number((await pool.query(`SELECT count(*) AS count FROM ${name}`)).rows[0].count);return out;},
  };
}
