import { generateGeometry, resolveElementRect, uniqueLines } from './geometry.js';
import { renderTemplate, isPackageNoticeVisible } from './variables.js';
import { flattenCurves } from './importDieline.js';

const PT = 72 / 25.4;
const CODE39 = {
  '0':'nnnwwnwnn','1':'wnnwnnnnw','2':'nnwwnnnnw','3':'wnwwnnnnn','4':'nnnwwnnnw','5':'wnnwwnnnn','6':'nnwwwnnnn','7':'nnnwnnwnw','8':'wnnwnnwnn','9':'nnwwnnwnn',
  'A':'wnnnnwnnw','B':'nnwnnwnnw','C':'wnwnnwnnn','D':'nnnnwwnnw','E':'wnnnwwnnn','F':'nnwnwwnnn','G':'nnnnnwwnw','H':'wnnnnwwnn','I':'nnwnnwwnn','J':'nnnnwwwnn',
  'K':'wnnnnnnww','L':'nnwnnnnww','M':'wnwnnnnwn','N':'nnnnwnnww','O':'wnnnwnnwn','P':'nnwnwnnwn','Q':'nnnnnnwww','R':'wnnnnnwwn','S':'nnwnnnwwn','T':'nnnnwnwwn',
  'U':'wwnnnnnnw','V':'nwwnnnnnw','W':'wwwnnnnnn','X':'nwnnwnnnw','Y':'wwnnwnnnn','Z':'nwwnwnnnn','-':'nwnnnnwnw','.':'wwnnnnwnn',' ':'nwwnnnwnn','$':'nwnwnwnnn','/':'nwnwnnnwn','+':'nwnnnwnwn','%':'nnnwnwnwn','*':'nwnnwnwnn'
};
const CODE39_INV = Object.fromEntries(Object.entries(CODE39).map(([k,v])=>[v,k]));
const EAN_L=['0001101','0011001','0010011','0111101','0100011','0110001','0101111','0111011','0110111','0001011'];
const EAN_G=['0100111','0011011','0011011','0100001','0011101','0111001','0000101','0010001','0001001','0010111'];
EAN_G[0]='0100111'; EAN_G[1]='0110011';
const EAN_R=['1110010','1100110','1101100','1000010','1011100','1001110','1010000','1000100','1001000','1110100'];
const EAN_PARITY=['LLLLLL','LLGLGG','LLGGLG','LLGGGL','LGLLGG','LGGLLG','LGGGLL','LGLGLG','LGLGGL','LGGLGL'];
const ITF_PAT=['nnwwn','wnnnw','nwnnw','wwnnn','nnwnw','wnwnn','nwwnn','nnnww','wnnwn','nwnwn'];
const ITF_INV=Object.fromEntries(ITF_PAT.map((v,i)=>[v,String(i)]));
const C128=[
'212222','222122','222221','121223','121322','131222','122213','122312','132212','221213','221312','231212','112232','122132','122231','113222','123122','123221','223211','221132','221231','213212','223112','312131','311222','321122','321221','312212','322112','322211','212123','212321','232121','111323','131123','131321','112313','132113','132311','211313','231113','231311','112133','112331','132131','113123','113321','133121','313121','211331','231131','213113','213311','213131','311123','311321','331121','312113','312311','332111','314111','221411','431111','111224','111422','121124','121421','141122','141221','112214','112412','122114','122411','142112','142211','241211','221114','413111','241112','134111','111242','121142','121241','114212','124112','124211','411212','421112','421211','212141','214121','412121','111143','111341','131141','114113','114311','411113','411311','113141','114131','311141','411131','211412','211214','211232','2331112'
];
const C128_INV=Object.fromEntries(C128.map((v,i)=>[v,i]));
const QR_SPECS={1:{size:21,align:[]},2:{size:25,align:[6,18]},3:{size:29,align:[6,22]},4:{size:33,align:[6,26]}};
const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const mm=v=>num(v)/PT;
const round6=v=>Math.round(v*1e6)/1e6;

function latin1(bytes){
  if(typeof bytes==='string') return bytes;
  const a=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes||[]);let out='',step=0x8000;
  for(let i=0;i<a.length;i+=step)out+=String.fromCharCode(...a.subarray(i,Math.min(a.length,i+step)));
  return out;
}
export function parsePdfMediaBoxV31(pdfBytes){
  const text=latin1(pdfBytes),m=text.match(/\/MediaBox\s*\[\s*(-?[\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s*\]/);
  if(!m)throw new Error('Production PDF MediaBox not found.');
  const x0=mm(m[1]),y0=mm(m[2]),x1=mm(m[3]),y1=mm(m[4]);return{x:x0,y:y0,width:x1-x0,height:y1-y0};
}
export function extractPdfStreamsV31(pdfBytes){
  const text=latin1(pdfBytes),out=[];let at=0;
  while(true){const s=text.indexOf('stream',at);if(s<0)break;let start=s+6;if(text[start]==='\r'&&text[start+1]==='\n')start+=2;else if(text[start]==='\n'||text[start]==='\r')start++;const end=text.indexOf('endstream',start);if(end<0)break;const body=text.slice(start,end);if(/\bre\b|\bm\b|\bBT\b/.test(body))out.push(body);at=end+9;}
  return out;
}
function fillBlackFromLine(line,current){
  let c=current,m;const k=[...line.matchAll(/(-?[\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+k\b/g)];
  if(k.length){m=k[k.length-1];c=num(m[1])+num(m[2])+num(m[3])<.08&&num(m[4])>.72;}
  const rg=[...line.matchAll(/(-?[\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+rg\b/g)];if(rg.length){m=rg[rg.length-1];c=num(m[1])+num(m[2])+num(m[3])<.18;}
  const g=[...line.matchAll(/(?:^|\s)(-?[\d.]+)\s+g\b/g)];if(g.length){m=g[g.length-1];c=num(m[1])<.2;}return c;
}
export function parsePdfPaintGeometryV31(pdfBytes){
  const media=parsePdfMediaBoxV31(pdfBytes),rects=[],lines=[];
  for(const stream of extractPdfStreamsV31(pdfBytes)){let fillBlack=true;for(const line of stream.split(/\r?\n/)){fillBlack=fillBlackFromLine(line,fillBlack);for(const m of line.matchAll(/(-?[\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+(-?[\d.]+)\s+re\s+([fS])\b/g)){const x=mm(m[1]),yb=mm(m[2]),w=mm(m[3]),h=mm(m[4]),y=media.height-(yb+h);rects.push({x,y,w,h,paint:m[5],black:m[5]==='f'?fillBlack:true});}for(const m of line.matchAll(/(-?[\d.]+)\s+(-?[\d.]+)\s+m\s+(-?[\d.]+)\s+(-?[\d.]+)\s+l\s+S\b/g))lines.push({x1:mm(m[1]),y1:media.height-mm(m[2]),x2:mm(m[3]),y2:media.height-mm(m[4])});}}
  return{media,rects,lines};
}
function rectError(a,b){return Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y),Math.abs(a.w-b.w),Math.abs(a.h-b.h));}
function nearestRect(rects,target,{paint='S',maxSearch=12}={}){let best=null,bestError=Infinity;for(const r of rects){if(paint&&r.paint!==paint)continue;const e=rectError(r,target);if(e<bestError){best=r;bestError=e;}}return bestError<=maxSearch?{rect:best,error:bestError}:{rect:null,error:bestError};}
function linePairError(a,b){const direct=Math.max(Math.hypot(a.x1-b.x1,a.y1-b.y1),Math.hypot(a.x2-b.x2,a.y2-b.y2)),reverse=Math.max(Math.hypot(a.x1-b.x2,a.y1-b.y2),Math.hypot(a.x2-b.x1,a.y2-b.y1));return Math.min(direct,reverse);}
function nearestLine(lines,target){let best=null,bestError=Infinity;for(const l of lines){const e=linePairError(l,target);if(e<bestError){best=l;bestError=e;}}return{line:best,error:bestError};}
function visibleElements(state){if(state?.hiddenGroups?.marks)return[];return(state?.elements||[]).filter(e=>!(e.type==='notice'&&!isPackageNoticeVisible(state.variables||{})));}
export function geometryAcceptanceV31(state,pdfBytes,{toleranceMm=.2}={}){
  const actual=parsePdfPaintGeometryV31(pdfBytes),geo=generateGeometry(state.structure),checks=[],failures=[];
  const add=(id,error,detail,extra={})=>{const ok=Number.isFinite(error)&&error<=toleranceMm,item={id,ok,errorMm:round6(error),toleranceMm,detail,...extra};checks.push(item);if(!ok)failures.push(item);};
  add('page.width',Math.abs(actual.media.width-geo.width),`Preview ${geo.width} mm / PDF ${actual.media.width.toFixed(4)} mm`);add('page.height',Math.abs(actual.media.height-geo.height),`Preview ${geo.height} mm / PDF ${actual.media.height.toFixed(4)} mm`);
  for(const el of visibleElements(state).filter(e=>Math.abs(num(e.r))>.001)){const item={id:`rotation.${el.id}`,ok:false,errorMm:Infinity,toleranceMm,detail:`${el.id} rotation ${el.r}° is not applied by the current Production PDF serializer. Production is blocked instead of silently exporting mismatched geometry.`};checks.push(item);failures.push(item);}
  for(const el of visibleElements(state).filter(e=>e.type==='barcode-qr-group'||e.type==='shape')){const rr=resolveElementRect(el,geo),target={x:rr.absX,y:rr.absY,w:num(el.w),h:num(el.h)},found=nearestRect(actual.rects,target,{paint:'S'});add(`frame.${el.id}`,found.rect?found.error:Infinity,found.rect?`Frame ${el.id} matched in Production PDF.`:`Frame ${el.id} not found in Production PDF.`,{expected:target,actual:found.rect});}
  const expectedLines=uniqueLines([...(geo.cutLines||[]),...(geo.creaseLines||[]),...(geo.perfLines||[]),...(geo.glueLines||[]),...flattenCurves(geo.cutCurves||[],32),...flattenCurves(geo.creaseCurves||[],32),...flattenCurves(geo.perfCurves||[],32),...flattenCurves(geo.glueCurves||[],32)]);
  let maxLineError=0,missing=0;for(const target of expectedLines){const n=nearestLine(actual.lines,target);if(!n.line||!Number.isFinite(n.error)){missing++;maxLineError=Infinity;break;}maxLineError=Math.max(maxLineError,n.error);}add('dieline.endpoints',expectedLines.length?maxLineError:0,`${expectedLines.length} preview dieline segment(s) independently measured against PDF; ${missing} missing.`);
  return{ok:failures.length===0,toleranceMm,maxErrorMm:failures.some(x=>!Number.isFinite(x.errorMm))?Infinity:Math.max(0,...checks.map(x=>x.errorMm||0)),checks,failures,actual};
}
function rasterize(rects,crop,pxPerMm=10){const width=Math.max(1,Math.round(crop.w*pxPerMm)),height=Math.max(1,Math.round(crop.h*pxPerMm)),data=new Uint8Array(width*height);for(const r of rects){if(r.paint!=='f'||!r.black)continue;const x0=Math.max(crop.x,r.x),y0=Math.max(crop.y,r.y),x1=Math.min(crop.x+crop.w,r.x+r.w),y1=Math.min(crop.y+crop.h,r.y+r.h);if(x1<=x0||y1<=y0)continue;const ix0=Math.max(0,Math.floor((x0-crop.x)*pxPerMm)),iy0=Math.max(0,Math.floor((y0-crop.y)*pxPerMm)),ix1=Math.min(width,Math.ceil((x1-crop.x)*pxPerMm)),iy1=Math.min(height,Math.ceil((y1-crop.y)*pxPerMm));for(let y=iy0;y<iy1;y++)data.fill(1,y*width+ix0,y*width+ix1);}return{width,height,data,pxPerMm,crop};}
function bitAt(bitmap,x,y){const ix=Math.max(0,Math.min(bitmap.width-1,Math.floor(x))),iy=Math.max(0,Math.min(bitmap.height-1,Math.floor(y)));return bitmap.data[iy*bitmap.width+ix]?1:0;}
function sampleModules(bitmap,count,{quiet=0,y=.5}={}){const bits=[];for(let i=0;i<count;i++)bits.push(bitAt(bitmap,(i+.5)*bitmap.width/count,y*bitmap.height));return quiet?bits.slice(quiet,bits.length-quiet):bits;}
function rowRuns(bitmap,y=.5){const iy=Math.max(0,Math.min(bitmap.height-1,Math.floor(bitmap.height*y))),bits=[];for(let x=0;x<bitmap.width;x++)bits.push(bitmap.data[iy*bitmap.width+x]?1:0);const first=bits.indexOf(1),last=bits.lastIndexOf(1);if(first<0)return[];const runs=[];let bit=bits[first],start=first;for(let i=first+1;i<=last+1;i++){const b=i<=last?bits[i]:1-bit;if(b!==bit){runs.push({bit,length:i-start});bit=b;start=i;}}return runs;}
function quantizeRuns(runs){if(!runs.length)return[];const lens=runs.map(r=>r.length).sort((a,b)=>a-b),n=Math.max(1,Math.ceil(lens.length*.28)),unit=lens.slice(0,n).reduce((a,b)=>a+b,0)/n;return runs.map(r=>Math.max(1,Math.min(4,Math.round(r.length/Math.max(1,unit)))));}
function checkDigit(body){let sum=0,odd=true;for(let i=body.length-1;i>=0;i--,odd=!odd)sum+=Number(body[i])*(odd?3:1);return String((10-(sum%10))%10);}
function expectedBarcode(type,value){const t=String(type||'CODE39').toUpperCase(),src=String(value??'');if(t==='CODE39')return src.toUpperCase();const digits=src.replace(/\D/g,'');if(t==='EAN13')return digits.length===12?digits+checkDigit(digits):digits;if(t==='UPCA')return digits.length===11?digits+checkDigit(digits):digits;if(t==='ITF14')return digits.length===13?digits+checkDigit(digits):digits;if(t==='GS1_128')return expectedGs1Raw(src);return src;}
function expectedGs1Raw(src){const s=String(src||'').trim();if(!s.includes('('))return s.replace(/\|/g,'\u00f1');const fixed=new Set(['00','01','02','11','12','13','15','16','17','20','402','410','411','412','413','414','415','416','417','422','424','426','7003']),parts=[];for(const m of s.matchAll(/\((\d{2,4})\)([^()]*)/g))parts.push({ai:m[1],data:m[2].trim()});let out='';for(let i=0;i<parts.length;i++){const p=parts[i];out+=p.ai+p.data;if(!fixed.has(p.ai)&&i<parts.length-1)out+='\u00f1';}return out;}
function decodeEan13(bitmap){const bits=sampleModules(bitmap,117,{quiet:11}).join('');if(bits.length!==95||!bits.startsWith('101')||bits.slice(45,50)!=='01010'||!bits.endsWith('101'))throw new Error('EAN guard pattern not found after PDF rasterization.');let left='',par='';for(let i=0;i<6;i++){const s=bits.slice(3+i*7,10+i*7),li=EAN_L.indexOf(s),gi=EAN_G.indexOf(s);if(li>=0){left+=li;par+='L';}else if(gi>=0){left+=gi;par+='G';}else throw new Error(`EAN left digit ${i+1} is undecodable.`);}const first=EAN_PARITY.indexOf(par);if(first<0)throw new Error(`EAN parity ${par} is invalid.`);let right='';for(let i=0;i<6;i++){const s=bits.slice(50+i*7,57+i*7),ri=EAN_R.indexOf(s);if(ri<0)throw new Error(`EAN right digit ${i+1} is undecodable.`);right+=ri;}const value=String(first)+left+right;if(checkDigit(value.slice(0,12))!==value[12])throw new Error('EAN checksum mismatch after PDF rasterization.');return value;}
function decodeCode39(bitmap){const q=quantizeRuns(rowRuns(bitmap,.45));if(q.length<19)throw new Error('Code39 raster has too few runs.');const chars=[];for(let i=0;i<q.length;){if(i+9>q.length)break;const pat=q.slice(i,i+9).map(v=>v>=2?'w':'n').join(''),ch=CODE39_INV[pat];if(!ch)throw new Error(`Code39 pattern ${pat} is unknown.`);chars.push(ch);i+=9;if(i<q.length)i++;}if(chars[0]!=='*'||chars.at(-1)!=='*')throw new Error('Code39 start/stop missing.');return chars.slice(1,-1).join('');}
function decodeItf14(bitmap){const q=quantizeRuns(rowRuns(bitmap,.45));if(q.length<17)throw new Error('ITF-14 raster has too few runs.');const core=q.slice(4,-3);if(core.length%10)throw new Error('ITF-14 run count is invalid.');let out='';for(let i=0;i<core.length;i+=10){let a='',b='';for(let j=0;j<5;j++){a+=core[i+j*2]>=2?'w':'n';b+=core[i+j*2+1]>=2?'w':'n';}if(!(a in ITF_INV)||!(b in ITF_INV))throw new Error(`ITF-14 pair is undecodable (${a}/${b}).`);out+=ITF_INV[a]+ITF_INV[b];}if(out.length!==14||checkDigit(out.slice(0,13))!==out[13])throw new Error('ITF-14 checksum mismatch after PDF rasterization.');return out;}
function decodeCode128(bitmap){const q=quantizeRuns(rowRuns(bitmap,.45));if(q.length<19)throw new Error('Code128 raster has too few runs.');const stop=q.slice(-7).join('');if(stop!==C128[106])throw new Error(`Code128 stop pattern mismatch (${stop}).`);const body=q.slice(0,-7);if(body.length%6)throw new Error('Code128 symbol run count is invalid.');const vals=[];for(let i=0;i<body.length;i+=6){const p=body.slice(i,i+6).join(''),v=C128_INV[p];if(v==null||v===106)throw new Error(`Code128 symbol ${p} is unknown.`);vals.push(v);}if(vals.length<3||vals[0]!==104)throw new Error('Code128-B start code missing.');const checksum=vals.at(-1);let sum=vals[0];for(let i=1;i<vals.length-1;i++)sum+=vals[i]*i;if(sum%103!==checksum)throw new Error('Code128 checksum mismatch after PDF rasterization.');const data=vals.slice(1,-1);if(data[0]===102)data.shift();let out='';for(const v of data){if(v===102)out+='\u00f1';else if(v>=0&&v<=94)out+=String.fromCharCode(v+32);else throw new Error(`Unsupported Code128-B codeword ${v}.`);}return out;}
function markReserved(version){const{size:n,align}=QR_SPECS[version],r=Array.from({length:n},()=>Array(n).fill(false)),set=(row,col)=>{if(row>=0&&col>=0&&row<n&&col<n)r[row][col]=true;};const finder=(row,col)=>{for(let y=-1;y<=7;y++)for(let x=-1;x<=7;x++)set(row+y,col+x);};finder(0,0);finder(n-7,0);finder(0,n-7);for(let i=8;i<n-8;i++){set(i,6);set(6,i);}for(const y of align)for(const x of align){if(r[y][x])continue;for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++)set(y+dy,x+dx);}for(let i=0;i<15;i++){if(i<6)set(i,8);else if(i<8)set(i+1,8);else set(n-15+i,8);if(i<8)set(8,n-i-1);else if(i<9)set(8,15-i);else set(8,15-i-1);}set(n-8,8);return r;}
function finderOk(m,row,col){for(let r=0;r<7;r++)for(let c=0;c<7;c++){const dark=r===0||r===6||c===0||c===6||(r>=2&&r<=4&&c>=2&&c<=4);if(Boolean(m[row+r][col+c])!==dark)return false;}return true;}
function sampleQrMatrix(bitmap,version){const n=QR_SPECS[version].size,modules=n+8,m=Array.from({length:n},()=>Array(n).fill(false));for(let r=0;r<n;r++)for(let c=0;c<n;c++)m[r][c]=Boolean(bitAt(bitmap,(4+c+.5)*bitmap.width/modules,(4+r+.5)*bitmap.height/modules));return m;}
function decodeQrCandidate(bitmap,version){const n=QR_SPECS[version].size,m=sampleQrMatrix(bitmap,version);if(!finderOk(m,0,0)||!finderOk(m,n-7,0)||!finderOk(m,0,n-7))throw new Error('QR finder mismatch.');const reserved=markReserved(version),bits=[];let row=n-1,inc=-1;for(let col=n-1;col>0;col-=2){if(col===6)col--;while(true){for(let c=0;c<2;c++){const cc=col-c;if(!reserved[row][cc]){let dark=m[row][cc];if((row+cc)%2===0)dark=!dark;bits.push(dark?1:0);}}row+=inc;if(row<0||row>=n){row-=inc;inc=-inc;break;}}}const take=(at,count)=>{let v=0;for(let i=0;i<count;i++)v=(v<<1)|(bits[at+i]||0);return v;};if(take(0,4)!==0b0100)throw new Error('QR byte mode marker missing.');const count=take(4,8),bytes=[];let at=12;for(let i=0;i<count;i++,at+=8)bytes.push(take(at,8));return new TextDecoder().decode(new Uint8Array(bytes));}
function decodeQr(bitmap){const errors=[];for(let version=1;version<=4;version++){try{return{value:decodeQrCandidate(bitmap,version),version};}catch(err){errors.push(`v${version}: ${err.message}`);}}throw new Error(`QR raster decode failed (${errors.join(' | ')}).`);}
export function digitalDecodeRequiredCheckV31(state,pdfBytes,{pxPerMm=10,toleranceMm=.2}={}){
  const parsed=parsePdfPaintGeometryV31(pdfBytes),geo=generateGeometry(state.structure),results=[],failures=[],groups=visibleElements(state).filter(e=>e.type==='barcode-qr-group');if(!groups.length)return{ok:true,results,failures,note:'No visible Barcode/QR group requires digital decode.'};
  for(const el of groups){const rr=resolveElementRect(el,geo),expectedFrame={x:rr.absX,y:rr.absY,w:num(el.w),h:num(el.h)},found=nearestRect(parsed.rects,expectedFrame,{paint:'S'});if(!found.rect||found.error>toleranceMm){const failure={id:el.id,ok:false,stage:'frame',error:`Barcode/QR frame is missing or displaced by ${Number.isFinite(found.error)?found.error.toFixed(4):'∞'} mm.`};results.push(failure);failures.push(failure);continue;}if(Math.abs(num(el.r))>.001){const failure={id:el.id,ok:false,stage:'rotation',error:`Barcode/QR rotation ${el.r}° is unsupported by the current Production PDF serializer.`};results.push(failure);failures.push(failure);continue;}const frame=found.rect,pad=5,gap=7,qrSide=Math.max(20,Math.min(frame.h-pad*2,frame.w*.30)),barcodeCrop={x:frame.x+pad,y:frame.y+pad,w:Math.max(30,frame.w-pad*2-gap-qrSide),h:Math.max(16,frame.h-pad*2-11)},qrCrop={x:frame.x+frame.w-pad-qrSide,y:frame.y+pad,w:qrSide,h:qrSide},barcodeRaster=rasterize(parsed.rects,barcodeCrop,pxPerMm),qrRaster=rasterize(parsed.rects,qrCrop,pxPerMm),type=String(el.barcodeType||'CODE39').toUpperCase(),barcodeSource=renderTemplate(el.barcodeValue||'',state.variables||{}),qrSource=renderTemplate(el.qrValue||'',state.variables||{});let barcodeDecoded='',barcodeError=null;try{barcodeDecoded=type==='EAN13'?decodeEan13(barcodeRaster):type==='UPCA'?decodeEan13(barcodeRaster).replace(/^0/,''):type==='ITF14'?decodeItf14(barcodeRaster):type==='GS1_128'?decodeCode128(barcodeRaster):decodeCode39(barcodeRaster);}catch(err){barcodeError=err;}let qrDecoded='',qrVersion=null,qrError=null;try{const q=decodeQr(qrRaster);qrDecoded=q.value;qrVersion=q.version;}catch(err){qrError=err;}const expectedBc=expectedBarcode(type,barcodeSource),barcodeOk=!barcodeError&&barcodeDecoded===expectedBc,qrOk=!qrError&&qrDecoded===String(qrSource),ok=barcodeOk&&qrOk,result={id:el.id,ok,type,source:{barcode:expectedBc,qr:String(qrSource)},decoded:{barcode:barcodeDecoded,qr:qrDecoded,qrVersion},raster:{pxPerMm,barcodePx:[barcodeRaster.width,barcodeRaster.height],qrPx:[qrRaster.width,qrRaster.height]},barcodeOk,qrOk,error:[barcodeError?.message,qrError?.message,!barcodeError&&!barcodeOk?`Barcode decoded "${barcodeDecoded}" but source is "${expectedBc}".`:null,!qrError&&!qrOk?`QR decoded "${qrDecoded}" but source is "${qrSource}".`:null].filter(Boolean).join(' ')||null};results.push(result);if(!ok)failures.push(result);}
  return{ok:failures.length===0,results,failures};
}
export function runV31Acceptance(state,pdfBytes,options={}){const geometry=geometryAcceptanceV31(state,pdfBytes,options),digital=digitalDecodeRequiredCheckV31(state,pdfBytes,options),ok=geometry.ok&&digital.ok;return{version:'0.31',ok,required:true,geometry,digital,summary:ok?`PASS · geometry max error ${Number.isFinite(geometry.maxErrorMm)?geometry.maxErrorMm.toFixed(4):'∞'} mm · ${digital.results.length} Barcode/QR group(s) digitally decoded from Production PDF raster.`:`BLOCKED · ${geometry.failures.length} geometry failure(s) · ${digital.failures.length} digital decode failure(s).`};}
export function assertV31Acceptance(report){if(report?.ok)return report;const details=[...(report?.geometry?.failures||[]).map(x=>`${x.id}: ${x.detail}`),...(report?.digital?.failures||[]).map(x=>`${x.id}: ${x.error||x.stage}`)].slice(0,8);throw new Error(`V0.31 Production Required Check failed. ${details.join(' | ')||'Unknown acceptance failure.'}`);}
