import {ARTWORK_CATALOG_V74,ARTWORK_PATHS_V74} from './artworkDataV74.js';
import {ARTWORK_CATALOG_V75,ARTWORK_PATHS_V75} from './artworkDataV75.js';
export {ARTWORK_CATALOG_V74,ARTWORK_CATALOG_V75};
const f=n=>+n.toFixed(5);
export function artworkPrimitivesV74(el){const paths=ARTWORK_PATHS_V75[el.assetIdV74]||ARTWORK_PATHS_V74[el.assetIdV74];if(!paths)throw new Error('素材不存在。');if(!/^#[0-9a-f]{6}$/i.test(el.fillColor||'#111111'))throw new Error('素材颜色无效。');const size=Math.min(el.w,el.h);return paths.map(p=>({...p,stroke:p.stroke*size,ops:p.ops.map(([op,...v])=>[op,...v.map((n,i)=>(i%2?(el.h-size)/2:(el.w-size)/2)+n*size)])}));}
export function artworkSvgV74(el){const color=el.fillColor||'#111111';return artworkPrimitivesV74(el).map(p=>'<path data-asset-v74="'+el.assetIdV74+'" d="'+p.ops.map(([op,...v])=>op+v.map(f).join(' ')).join(' ')+'" fill="'+(p.fill?color:'none')+'" fill-rule="'+p.rule+'" stroke="'+(p.stroke?color:'none')+'" stroke-width="'+f(p.stroke)+'" stroke-linecap="'+p.cap+'" stroke-linejoin="'+p.join+'"/>').join('');}
export function artworkPdfV74(el,x,y,pageH,pt){const hex=(el.fillColor||'#111111').slice(1),rgb=[0,2,4].map(i=>parseInt(hex.slice(i,i+2),16)/255),k=1-Math.max(...rgb),cmyk=[...rgb.map(v=>k===1?0:(1-v-k)/(1-k)),k].map(f).join(' '),out=['q '+cmyk+' K '+cmyk+' k [] 0 d'];for(const p of artworkPrimitivesV74(el)){out.push(f(p.stroke*pt)+' w '+({butt:0,round:1,square:2}[p.cap]||0)+' J '+({miter:0,round:1,bevel:2}[p.join]||0)+' j');for(const[op,...v]of p.ops)out.push(op==='Z'?'h':v.map((n,i)=>f((i%2?pageH-y-n:x+n)*pt)).join(' ')+({M:' m',L:' l',C:' c'}[op]));out.push(p.fill?(p.stroke?'B':'f'):'S');}out.push('Q');return out;}
export function paintArtworkV74(ctx,el,sx,sy){ctx.save();ctx.translate(el.x*sx,el.y*sy);ctx.scale(sx,sy);ctx.fillStyle=ctx.strokeStyle=el.fillColor||'#111111';for(const p of artworkPrimitivesV74(el)){ctx.lineWidth=p.stroke;ctx.lineJoin=p.join;ctx.lineCap=p.cap;ctx.beginPath();for(const[op,...v]of p.ops){if(op==='M')ctx.moveTo(...v);else if(op==='L')ctx.lineTo(...v);else if(op==='C')ctx.bezierCurveTo(...v);else ctx.closePath();}if(p.fill)ctx.fill(p.rule);if(p.stroke)ctx.stroke();}ctx.restore();}
export function createArtworkV74(id,panel,{color='#111111'}={}){const t=ARTWORK_CATALOG_V75.find(t=>t.id===id);if(!t)throw new Error('素材不存在。');const size=Math.min(40,panel.w-16,panel.h-16);if(size<4)throw new Error('该印刷面没有足够的素材空间。');return{id:'asset-'+crypto.randomUUID(),type:'shape',assetIdV74:id,name:t.label,group:'artwork',panelId:panel.id,x:8,y:8,w:size,h:size,r:0,fillColor:color};}
