export const V60_PRODUCT_VERSION='V0.60';
export const V60_IMAGE_TYPES=['image/png','image/jpeg','image/webp'];
export const V60_IMAGE_LIMITS={inputBytes:12*1024*1024,storedBytes:1500*1024,maxDimension:1600,minDpi:72,warnDpi:150,targetDpi:300};

const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function dataUrlByteSizeV60(src=''){const comma=String(src).indexOf(',');if(comma<0)return 0;const payload=String(src).slice(comma+1);return Math.floor(payload.length*3/4)-(payload.endsWith('==')?2:payload.endsWith('=')?1:0)}
export function imagePreserveAspectRatioV60(fit='contain'){return fit==='stretch'?'none':fit==='cover'?'xMidYMid slice':'xMidYMid meet'}
export function normalizeImageElementV60(el={}){const src=String(el.src||''),mime=V60_IMAGE_TYPES.includes(el.mime)?el.mime:(/^data:image\/jpeg/i.test(src)?'image/jpeg':'image/png');return{...el,type:'image',group:el.group||'artwork',x:num(el.x),y:num(el.y),w:Math.max(.1,num(el.w,50)),h:Math.max(.1,num(el.h,50)),r:num(el.r),fit:['contain','cover','stretch'].includes(el.fit)?el.fit:'contain',opacity:clamp(num(el.opacity,1),0,1),src,name:String(el.name||'artwork-image'),mime,pixelWidth:Math.max(1,Math.round(num(el.pixelWidth,1))),pixelHeight:Math.max(1,Math.round(num(el.pixelHeight,1))),assetBytes:Math.max(0,Math.round(num(el.assetBytes,dataUrlByteSizeV60(src)))),pdfSrc:String(el.pdfSrc||''),pdfBytes:Math.max(0,Math.round(num(el.pdfBytes,dataUrlByteSizeV60(el.pdfSrc)))),pdfMatte:String(el.pdfMatte||'#ffffff'),pdfTransparencyFlattened:Boolean(el.pdfTransparencyFlattened)}}
export function createImageElementV60(asset,panel,{id=null,panelId=null,fit='contain'}={}){if(!asset?.src)throw new Error('V60_IMAGE_SOURCE_REQUIRED');if(!panel)throw new Error('V60_IMAGE_PANEL_REQUIRED');const pw=Math.max(20,num(panel.w,100)),ph=Math.max(20,num(panel.h,100)),aspect=Math.max(.05,num(asset.pixelWidth,1)/Math.max(1,num(asset.pixelHeight,1)));let w=pw*.58,h=w/aspect;if(h>ph*.58){h=ph*.58;w=h*aspect}w=Math.max(12,Math.min(pw-8,w));h=Math.max(12,Math.min(ph-8,h));return normalizeImageElementV60({id:id||`image-${Date.now().toString(36)}`,panelId:panelId||panel.id,x:Math.max(4,(pw-w)/2),y:Math.max(4,(ph-h)/2),w,h,r:0,fit,opacity:1,...asset})}
export function imageEffectiveDpiV60(el={}){const e=normalizeImageElementV60(el),inchW=Math.max(.001,e.w/25.4),inchH=Math.max(.001,e.h/25.4);return Math.round(Math.min(e.pixelWidth/inchW,e.pixelHeight/inchH))}
export function imagePdfSourceV60(el={}){const e=normalizeImageElementV60(el);if(e.mime==='image/jpeg'&&/^data:image\/jpeg;base64,/i.test(e.src))return e.src;if(/^data:image\/jpeg;base64,/i.test(e.pdfSrc))return e.pdfSrc;return''}
export function imagePreflightChecksV60(state={}){const checks=[];for(const raw of state.elements||[]){if(raw?.type!=='image')continue;const el=normalizeImageElementV60(raw),dpi=imageEffectiveDpiV60(el),pdfSrc=imagePdfSourceV60(el);if(!el.src||!/^data:image\/(png|jpeg|webp);base64,/i.test(el.src))checks.push({severity:'error',code:'V60_IMAGE_SOURCE',title:'图片源',detail:`${el.name} 缺少可持久化的 PNG/JPEG/WebP 图像数据。`,elementId:el.id});else checks.push({severity:'pass',code:'V60_IMAGE_SOURCE_OK',title:'图片源',detail:`${el.name} 已嵌入项目。`,elementId:el.id});if(dpi<V60_IMAGE_LIMITS.minDpi)checks.push({severity:'error',code:'V60_IMAGE_DPI',title:'图片有效分辨率',detail:`${el.name} 约 ${dpi} DPI，低于 ${V60_IMAGE_LIMITS.minDpi} DPI。`,elementId:el.id,metric:dpi});else if(dpi<V60_IMAGE_LIMITS.warnDpi)checks.push({severity:'warning',code:'V60_IMAGE_DPI',title:'图片有效分辨率',detail:`${el.name} 约 ${dpi} DPI，建议印刷图片 ≥ ${V60_IMAGE_LIMITS.warnDpi} DPI，优选 ${V60_IMAGE_LIMITS.targetDpi} DPI。`,elementId:el.id,metric:dpi});else checks.push({severity:'pass',code:'V60_IMAGE_DPI_OK',title:'图片有效分辨率',detail:`${el.name} 约 ${dpi} DPI。`,elementId:el.id,metric:dpi});if(!pdfSrc)checks.push({severity:'error',code:'V60_IMAGE_PDF_SOURCE',title:'Production PDF 图片',detail:`${el.name} 没有可嵌入 PDF 的 JPEG companion。请重新导入图片。`,elementId:el.id});else if(el.pdfTransparencyFlattened)checks.push({severity:'warning',code:'V60_IMAGE_PDF_FLATTEN',title:'Production PDF 透明度',detail:`${el.name} 的透明像素会在 Production PDF 中以 ${el.pdfMatte} 背景展平；SVG/PNG/3D 仍保留原透明度。`,elementId:el.id});else checks.push({severity:'pass',code:'V60_IMAGE_PDF_OK',title:'Production PDF 图片',detail:`${el.name} 可作为 JPEG XObject 嵌入 Production PDF。`,elementId:el.id});if(el.assetBytes+el.pdfBytes>V60_IMAGE_LIMITS.storedBytes*1.6)checks.push({severity:'warning',code:'V60_IMAGE_STORAGE',title:'图片项目体积',detail:`${el.name} 嵌入数据约 ${((el.assetBytes+el.pdfBytes)/1024).toFixed(0)} KB，可能接近浏览器本地存储上限。`,elementId:el.id,metric:el.assetBytes+el.pdfBytes})}return checks}
export function imageAcceptanceV60(){const sample=normalizeImageElementV60({id:'img',panelId:'front',w:50,h:25,src:'data:image/jpeg;base64,/9j/2Q==',pixelWidth:600,pixelHeight:300});const checks=imagePreflightChecksV60({elements:[sample]});return{ok:imagePreserveAspectRatioV60('contain')==='xMidYMid meet'&&imagePreserveAspectRatioV60('cover')==='xMidYMid slice'&&imagePreserveAspectRatioV60('stretch')==='none'&&imageEffectiveDpiV60(sample)>250&&imagePdfSourceV60(sample)===sample.src&&checks.some(x=>x.code==='V60_IMAGE_SOURCE_OK'),dpi:imageEffectiveDpiV60(sample),checks:checks.length}}

function loadBrowserImage(url){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('V60_IMAGE_DECODE_FAILED'));img.src=url})}
function canvasData(canvas,mime,quality=.88){try{return canvas.toDataURL(mime,quality)}catch{throw new Error('V60_IMAGE_ENCODE_FAILED')}}
function pdfCompanion(canvas,needsFlatten){if(!needsFlatten)return{pdfSrc:'',pdfBytes:0,pdfMatte:'#ffffff',pdfTransparencyFlattened:false};const flat=document.createElement('canvas');flat.width=canvas.width;flat.height=canvas.height;const fctx=flat.getContext('2d',{alpha:false});fctx.fillStyle='#ffffff';fctx.fillRect(0,0,flat.width,flat.height);fctx.drawImage(canvas,0,0);const pdfSrc=canvasData(flat,'image/jpeg',.9);return{pdfSrc,pdfBytes:dataUrlByteSizeV60(pdfSrc),pdfMatte:'#ffffff',pdfTransparencyFlattened:true}}
export async function processArtworkFileV60(file,{maxDimension=V60_IMAGE_LIMITS.maxDimension,maxStoredBytes=V60_IMAGE_LIMITS.storedBytes}={}){if(!file)throw new Error('V60_IMAGE_FILE_REQUIRED');const mime=String(file.type||'').toLowerCase();if(!V60_IMAGE_TYPES.includes(mime))throw new Error('V60_IMAGE_TYPE_UNSUPPORTED');if(Number(file.size)>V60_IMAGE_LIMITS.inputBytes)throw new Error('V60_IMAGE_FILE_TOO_LARGE');if(typeof document==='undefined'||typeof Image==='undefined'||typeof URL==='undefined')throw new Error('V60_IMAGE_BROWSER_REQUIRED');const url=URL.createObjectURL(file);let img;try{img=await loadBrowserImage(url)}finally{URL.revokeObjectURL(url)}const ow=Math.max(1,img.naturalWidth||img.width),oh=Math.max(1,img.naturalHeight||img.height);let scale=Math.min(1,maxDimension/Math.max(ow,oh)),quality=.9,last=null;for(let attempt=0;attempt<8;attempt++){const w=Math.max(1,Math.round(ow*scale)),h=Math.max(1,Math.round(oh*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:true});ctx.clearRect(0,0,w,h);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,w,h);const outMime=mime==='image/jpeg'?'image/jpeg':'image/png',src=canvasData(canvas,outMime,outMime==='image/jpeg'?quality:undefined),bytes=dataUrlByteSizeV60(src),pdf=pdfCompanion(canvas,outMime!=='image/jpeg');last={src,mime:outMime,name:file.name||'artwork-image',pixelWidth:w,pixelHeight:h,assetBytes:bytes,originalPixelWidth:ow,originalPixelHeight:oh,originalBytes:Number(file.size)||0,...pdf};const total=bytes+pdf.pdfBytes;if(bytes<=maxStoredBytes&&total<=maxStoredBytes*1.6)return last;if(outMime==='image/jpeg'&&quality>.68)quality-=.1;else scale*=.78}if(last&&last.assetBytes+last.pdfBytes<=maxStoredBytes*1.9)return last;throw new Error('V60_IMAGE_STORAGE_LIMIT')}
