function clone(v){return structuredClone(v)}
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])]));return value;}
function fnv1a(text=''){let hash=0x811c9dc5;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,0x01000193)>>>0;}return hash.toString(16).padStart(8,'0');}
export function rowsFingerprintV27(rows=[]){return fnv1a(JSON.stringify(stable(Array.isArray(rows)?rows:[])));}
export function captureBatchBaseStateV27(state){const base=clone(state||{});base.batch={...(base.batch||{}),rows:[],queue:null};base.productionJobs=[];base.activeProductionJobId=null;base.batchPipeline='v27-native-cubic';base.exportOptions={...(base.exportOptions||{}),nativeCubicClip:true};delete base.savedAt;return base;}
export function createBatchRunContextV27(state){const rows=Array.isArray(state?.batch?.rows)?state.batch.rows:[];return{schema:1,serializer:'v0.27-native-cubic-production',createdAt:new Date().toISOString(),rowCount:rows.length,rowsFingerprint:rowsFingerprintV27(rows),masterTemplateId:state?.batch?.masterTemplateId||'',deviceLinkRef:clone(state?.exportOptions?.deviceLinkRef||null),nativeCubicClip:true,baseState:captureBatchBaseStateV27(state)};}
export function attachBatchRunContextV27(queue,state,{restart=false}={}){const next=clone(queue||{});if(restart||!next.context||next.context.schema!==1||next.context.serializer!=='v0.27-native-cubic-production')next.context=createBatchRunContextV27(state);return next;}
export function batchRunCompatibilityV27(state,queue){const context=queue?.context;if(!context)return{ok:false,reason:'Batch queue has no frozen V0.27 run context.'};const rows=Array.isArray(state?.batch?.rows)?state.batch.rows:[],actual=rowsFingerprintV27(rows);if(rows.length!==Number(context.rowCount))return{ok:false,reason:`Batch row count changed after the run started: expected ${context.rowCount}, got ${rows.length}.`,expected:context.rowCount,actual:rows.length};if(actual!==context.rowsFingerprint)return{ok:false,reason:'Batch row data changed after the run started. Restart the V0.27 batch to create a new frozen run context.',expected:context.rowsFingerprint,actual};return{ok:true,reason:'Current batch rows match the frozen V0.27 run context.',fingerprint:actual};}
export function batchRunBaseStateV27(queue){if(!queue?.context?.baseState)throw new Error('V0.27 batch queue has no frozen base state.');return clone(queue.context.baseState);}
