const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clamp=(v,a=0,z=1)=>Math.max(a,Math.min(z,num(v)));
const clone=v=>structuredClone(v);
const EPS=1e-9;
function rotate(x,y,cx,cy,deg){const a=num(deg)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),dx=x-cx,dy=y-cy;return[cx+dx*c-dy*s,cy+dx*s+dy*c];}
function normalizePoint(p){return[clamp(p?.[0]),clamp(p?.[1])];}
function normalizeHandle(h){return[num(h?.[0]),num(h?.[1])];}
function nodeOf(value){if(Array.isArray(value))return{p:normalizePoint(value),in:[0,0],out:[0,0],smooth:false};return{p:normalizePoint(value?.p),in:normalizeHandle(value?.in),out:normalizeHandle(value?.out),smooth:Boolean(value?.smooth)};}
function same(a,b){return Math.abs(a[0]-b[0])<EPS&&Math.abs(a[1]-b[1])<EPS;}
function add(a,b){return[a[0]+b[0],a[1]+b[1]];}
function sub(a,b){return[a[0]-b[0],a[1]-b[1]];}
function lerp(a,b,t){return[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t];}
function cubic(p0,c1,c2,p3,t){const u=1-t,a=u*u*u,b=3*u*u*t,c=3*u*t*t,d=t*t*t;return[a*p0[0]+b*c1[0]+c*c2[0]+d*p3[0],a*p0[1]+b*c1[1]+c*c2[1]+d*p3[1]];}
function elementFrame(el){const x=num(el?.x),y=num(el?.y),w=Math.max(.001,num(el?.w,1)),h=Math.max(.001,num(el?.h,1));return{x,y,w,h,cx:x+w/2,cy:y+h/2,r:num(el?.r)};}
function normalizedToDocument(el,p){const f=elementFrame(el);return rotate(f.x+p[0]*f.w,f.y+p[1]*f.h,f.cx,f.cy,f.r);}
function documentToNormalized(el,x,y,{clamped=true}={}){const f=elementFrame(el),p=rotate(num(x),num(y),f.cx,f.cy,-f.r),q=[(p[0]-f.x)/f.w,(p[1]-f.y)/f.h];return clamped?[clamp(q[0]),clamp(q[1])]:q;}

export function crossClipNodes(element){const clip=element?.crossClip;if(Array.isArray(clip?.nodes)&&clip.nodes.length>=3)return clip.nodes.map(nodeOf);if(Array.isArray(clip?.points)&&clip.points.length>=3)return clip.points.map(nodeOf);return[];}
export function ensureBezierClipState(state,id,{inset=0}={}){const next=clone(state||{}),el=(next.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork');if(!el)return next;let nodes=crossClipNodes(el);if(nodes.length<3){const q=clamp(inset,0,.49);nodes=[[q,q],[1-q,q],[1-q,1-q],[q,1-q]].map(nodeOf);}el.crossClip={type:'bezier-polygon',closed:true,nodes};return next;}
export function flattenCrossClipNormalized(element,{stepsPerCurve=10}={}){const nodes=crossClipNodes(element);if(nodes.length<3)return[];const steps=Math.max(2,Math.min(64,Number(stepsPerCurve)||10)),out=[];for(let i=0;i<nodes.length;i++){const a=nodes[i],b=nodes[(i+1)%nodes.length],p0=a.p,p3=b.p,c1=add(p0,a.out),c2=add(p3,b.in),curve=!same(c1,p0)||!same(c2,p3);if(!out.length)out.push([...p0]);if(curve){for(let s=1;s<=steps;s++)out.push(cubic(p0,c1,c2,p3,s/steps));}else out.push([...p3]);}if(out.length>1&&same(out[0],out[out.length-1]))out.pop();return out.map(normalizePoint);}
export function clipGeometryV25(element,{stepsPerCurve=10}={}){const nodes=crossClipNodes(element),poly=flattenCrossClipNormalized(element,{stepsPerCurve});return{nodes:nodes.map((node,index)=>{const anchor=normalizedToDocument(element,node.p),inPoint=normalizedToDocument(element,add(node.p,node.in)),outPoint=normalizedToDocument(element,add(node.p,node.out));return{index,anchor,inPoint,outPoint,smooth:node.smooth,inActive:!same(node.in,[0,0]),outActive:!same(node.out,[0,0])};}),polygon:poly.map(p=>normalizedToDocument(element,p)),normalizedPolygon:poly};}
export function moveClipAnchorV25(state,id,index,docX,docY){const next=ensureBezierClipState(state,id),el=(next.elements||[]).find(e=>e.id===id);if(!el)return next;const nodes=crossClipNodes(el),i=Math.max(0,Math.min(nodes.length-1,Number(index)|0));nodes[i].p=documentToNormalized(el,docX,docY);el.crossClip={type:'bezier-polygon',closed:true,nodes};return next;}
export function moveClipHandleV25(state,id,index,side,docX,docY,{mirror=true}={}){const next=ensureBezierClipState(state,id),el=(next.elements||[]).find(e=>e.id===id);if(!el)return next;const nodes=crossClipNodes(el),i=Math.max(0,Math.min(nodes.length-1,Number(index)|0)),node=nodes[i],absolute=documentToNormalized(el,docX,docY,{clamped:false}),offset=sub(absolute,node.p),key=side==='in'?'in':'out',other=key==='in'?'out':'in';node[key]=offset;if(mirror||node.smooth){node[other]=[-offset[0],-offset[1]];node.smooth=true;}else node.smooth=false;el.crossClip={type:'bezier-polygon',closed:true,nodes};return next;}
export function toggleClipNodeSmoothV25(state,id,index,smooth=true){const next=ensureBezierClipState(state,id),el=(next.elements||[]).find(e=>e.id===id);if(!el)return next;const nodes=crossClipNodes(el),i=Math.max(0,Math.min(nodes.length-1,Number(index)|0)),node=nodes[i];node.smooth=Boolean(smooth);if(node.smooth){const source=Math.hypot(...node.out)>EPS?node.out:node.in;node.out=[num(source[0]),num(source[1])];node.in=[-node.out[0],-node.out[1]];}el.crossClip={type:'bezier-polygon',closed:true,nodes};return next;}
export function resetClipNodeHandlesV25(state,id,index){const next=ensureBezierClipState(state,id),el=(next.elements||[]).find(e=>e.id===id);if(!el)return next;const nodes=crossClipNodes(el),i=Math.max(0,Math.min(nodes.length-1,Number(index)|0));nodes[i].in=[0,0];nodes[i].out=[0,0];nodes[i].smooth=false;el.crossClip={type:'bezier-polygon',closed:true,nodes};return next;}
export function insertClipNodeV25(state,id,segmentIndex,t=.5){const next=ensureBezierClipState(state,id),el=(next.elements||[]).find(e=>e.id===id);if(!el)return next;const nodes=crossClipNodes(el),i=Math.max(0,Math.min(nodes.length-1,Number(segmentIndex)|0)),j=(i+1)%nodes.length,a=nodes[i],b=nodes[j],tt=clamp(t,0.05,.95),p0=a.p,p1=add(a.p,a.out),p2=add(b.p,b.in),p3=b.p,q0=lerp(p0,p1,tt),q1=lerp(p1,p2,tt),q2=lerp(p2,p3,tt),r0=lerp(q0,q1,tt),r1=lerp(q1,q2,tt),s=lerp(r0,r1,tt),curve=!same(p0,p1)||!same(p2,p3);if(curve){a.out=sub(q0,p0);b.in=sub(q2,p3);}const inserted={p:s,in:curve?sub(r0,s):[0,0],out:curve?sub(r1,s):[0,0],smooth:curve};if(j===0)nodes.push(inserted);else nodes.splice(j,0,inserted);el.crossClip={type:'bezier-polygon',closed:true,nodes};return next;}
export function removeClipNodeV25(state,id,index){const next=ensureBezierClipState(state,id),el=(next.elements||[]).find(e=>e.id===id);if(!el)return next;const nodes=crossClipNodes(el);if(nodes.length<=3)return next;const i=Math.max(0,Math.min(nodes.length-1,Number(index)|0));nodes.splice(i,1);el.crossClip={type:'bezier-polygon',closed:true,nodes};return next;}
export function setClipNodeHandlePresetV25(state,id,index,{length=.12,angleDeg=0}={}){const next=ensureBezierClipState(state,id),el=(next.elements||[]).find(e=>e.id===id);if(!el)return next;const nodes=crossClipNodes(el),i=Math.max(0,Math.min(nodes.length-1,Number(index)|0)),a=num(angleDeg)*Math.PI/180,l=Math.max(0,Math.min(.45,num(length,.12))),v=[Math.cos(a)*l,Math.sin(a)*l];nodes[i].out=v;nodes[i].in=[-v[0],-v[1]];nodes[i].smooth=true;el.crossClip={type:'bezier-polygon',closed:true,nodes};return next;}
export function clipPathDiagnosticsV25(element){const nodes=crossClipNodes(element),flat=flattenCrossClipNormalized(element);return{nodeCount:nodes.length,curvedNodes:nodes.filter(n=>Math.hypot(...n.in)>EPS||Math.hypot(...n.out)>EPS).length,smoothNodes:nodes.filter(n=>n.smooth).length,flattenedPoints:flat.length};}
export {normalizedToDocument as clipNormalizedToDocumentV25,documentToNormalized as clipDocumentToNormalizedV25};
