import { crossClipNodes, ensureBezierClipState } from './clipPathV25.js';

const clone=v=>structuredClone(v);
const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clamp=(v,a=0,z=1)=>Math.max(a,Math.min(z,num(v)));
function nodeIndex(nodes,index){return Math.max(0,Math.min(Math.max(0,nodes.length-1),Number(index)|0));}
function normHandle(v){return Math.max(-2,Math.min(2,num(v)));}
export function clipNodeNumericV26(element,index=0){const nodes=crossClipNodes(element);if(!nodes.length)return null;const i=nodeIndex(nodes,index),n=nodes[i],next=nodes[(i+1)%nodes.length],curve=Math.hypot(...n.out)>1e-9||Math.hypot(...next.in)>1e-9;return{index:i,x:n.p[0],y:n.p[1],inX:n.in[0],inY:n.in[1],outX:n.out[0],outY:n.out[1],smooth:Boolean(n.smooth),segmentType:curve?'curve':'line'};}
export function setClipNodeNumericV26(state,id,index,values={}){const next=ensureBezierClipState(state,id),el=(next.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork');if(!el)return next;const nodes=crossClipNodes(el),i=nodeIndex(nodes,index),node=nodes[i];node.p=[values.x==null?node.p[0]:clamp(values.x),values.y==null?node.p[1]:clamp(values.y)];node.in=[values.inX==null?node.in[0]:normHandle(values.inX),values.inY==null?node.in[1]:normHandle(values.inY)];node.out=[values.outX==null?node.out[0]:normHandle(values.outX),values.outY==null?node.out[1]:normHandle(values.outY)];if(values.smooth!=null)node.smooth=Boolean(values.smooth);if(node.smooth){const ox=node.out[0],oy=node.out[1],ix=node.in[0],iy=node.in[1],ol=Math.hypot(ox,oy),il=Math.hypot(ix,iy);if(ol>1e-9){const len=il>1e-9?il:ol,u=[ox/ol,oy/ol];node.in=[-u[0]*len,-u[1]*len];}else if(il>1e-9){const u=[ix/il,iy/il];node.out=[-u[0]*il,-u[1]*il];}}
  el.crossClip={type:'bezier-polygon',closed:true,nodes};return next;}
export function setClipSegmentTypeV26(state,id,index,type='curve'){const next=ensureBezierClipState(state,id),el=(next.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork');if(!el)return next;const nodes=crossClipNodes(el),i=nodeIndex(nodes,index),j=(i+1)%nodes.length,a=nodes[i],b=nodes[j];if(type==='line'){a.out=[0,0];b.in=[0,0];a.smooth=false;b.smooth=false;}else if(Math.hypot(...a.out)<1e-9&&Math.hypot(...b.in)<1e-9){const dx=b.p[0]-a.p[0],dy=b.p[1]-a.p[1];a.out=[dx/3,dy/3];b.in=[-dx/3,-dy/3];}
  el.crossClip={type:'bezier-polygon',closed:true,nodes};return next;}
export function setClipSelectedNodeV26(state,index){const next=clone(state||{});next.crossPanelEdit={...(next.crossPanelEdit||{}),clipNodeIndex:Math.max(0,Number(index)|0)};return next;}
export function clipSegmentDiagnosticsV26(element){const nodes=crossClipNodes(element),segments=[];for(let i=0;i<nodes.length;i++){const a=nodes[i],b=nodes[(i+1)%nodes.length],curve=Math.hypot(...a.out)>1e-9||Math.hypot(...b.in)>1e-9;segments.push({index:i,type:curve?'curve':'line',from:[...a.p],to:[...b.p],out:[...a.out],incomingNext:[...b.in]});}return{nodeCount:nodes.length,lineSegments:segments.filter(s=>s.type==='line').length,curveSegments:segments.filter(s=>s.type==='curve').length,segments};}
