const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clamp=(v,a=0,z=1)=>Math.max(a,Math.min(z,num(v)));
const clone=v=>structuredClone(v);
function rotate(x,y,cx,cy,deg){const a=num(deg)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),dx=x-cx,dy=y-cy;return[cx+dx*c-dy*s,cy+dx*s+dy*c];}
export function normalizedClipPointToDocument(element,point){const x=num(element?.x),y=num(element?.y),w=Math.max(.001,num(element?.w,1)),h=Math.max(.001,num(element?.h,1)),cx=x+w/2,cy=y+h/2,px=x+clamp(point?.[0])*w,py=y+clamp(point?.[1])*h;return rotate(px,py,cx,cy,num(element?.r));}
export function documentPointToNormalizedClip(element,docX,docY){const x=num(element?.x),y=num(element?.y),w=Math.max(.001,num(element?.w,1)),h=Math.max(.001,num(element?.h,1)),cx=x+w/2,cy=y+h/2,p=rotate(num(docX),num(docY),cx,cy,-num(element?.r));return[clamp((p[0]-x)/w),clamp((p[1]-y)/h)];}
export function ensureCrossClip(state,id,{inset=0}={}){const next=clone(state||{}),el=(next.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork');if(!el)return next;if(!Array.isArray(el.crossClip?.points)||el.crossClip.points.length<3){const q=clamp(inset,0,.49);el.crossClip={type:'polygon',points:[[q,q],[1-q,q],[1-q,1-q],[q,1-q]]};}return next;}
export function moveCrossClipPoint(state,id,index,docX,docY){const next=clone(state||{}),el=(next.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork');if(!el||!Array.isArray(el.crossClip?.points)||el.crossClip.points.length<3)return next;const i=Math.max(0,Math.min(el.crossClip.points.length-1,Number(index)|0));el.crossClip.points[i]=documentPointToNormalizedClip(el,docX,docY);return next;}
export function insertCrossClipPoint(state,id,index,normalizedPoint){const next=clone(state||{}),el=(next.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork');if(!el)return next;if(!Array.isArray(el.crossClip?.points)||el.crossClip.points.length<3)el.crossClip={type:'polygon',points:[[0,0],[1,0],[1,1],[0,1]]};const i=Math.max(0,Math.min(el.crossClip.points.length,Number(index)|0)),p=[clamp(normalizedPoint?.[0]),clamp(normalizedPoint?.[1])];el.crossClip.points.splice(i,0,p);return next;}
export function removeCrossClipPoint(state,id,index){const next=clone(state||{}),el=(next.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork');if(!el||!Array.isArray(el.crossClip?.points)||el.crossClip.points.length<=3)return next;const i=Math.max(0,Math.min(el.crossClip.points.length-1,Number(index)|0));el.crossClip.points.splice(i,1);return next;}
export function clipPointDiagnostics(element){const pts=Array.isArray(element?.crossClip?.points)?element.crossClip.points:[];return{count:pts.length,documentPoints:pts.map(p=>normalizedClipPointToDocument(element,p)),normalizedPoints:pts.map(p=>[clamp(p[0]),clamp(p[1])])};}
