import {CODE_TYPES_V72,codeTypeV72,generatedCodeLayoutV72,generatedCodeFileSvgV72} from './codeGeneratorV72.js';
import {withPngDpiV70} from './pngPrintV70.js';
import {iconV67} from './uiIconsV67.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export async function codePngV72(config,variables={},dpi=300){
 const width=Math.round(config.w/25.4*dpi),height=Math.round(config.h/25.4*dpi);if(width*height>40e6)throw new Error('图片超过 4000 万像素，请降低尺寸或使用 SVG。');
 const url=URL.createObjectURL(new Blob([generatedCodeFileSvgV72(config,variables)],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);ctx.drawImage(img,0,0,width,height);const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('PNG 编码失败。')),'image/png'));return new Blob([withPngDpiV70(new Uint8Array(await blob.arrayBuffer()),dpi)],{type:'image/png'});}finally{URL.revokeObjectURL(url);}
}
export function openCodeGeneratorV72({variables={},onInsert,initial}={}){
 const start=initial||{codeType:'code128',codeValue:'ITEM-2026-001',w:100,h:32,codeShowText:true},d=document.createElement('dialog');d.className='v67-dialog v72-code-dialog';d.dataset.v72CodeDialog='true';d.setAttribute('aria-labelledby','v72-code-title');
 d.innerHTML=`<header><div><span class="v67-eyebrow">CODE GENERATOR</span><h2 id="v72-code-title">条码与二维码生成器</h2></div><button data-close aria-label="关闭生成器">${iconV67('close')}</button></header><div class="v72-code-layout"><form data-v72-code-form><label>编码类型<select name="codeType">${CODE_TYPES_V72.map(t=>`<option value="${t.id}" ${t.id===start.codeType?'selected':''}>${t.label}</option>`).join('')}</select></label><label>编码内容<textarea name="codeValue" rows="4" maxlength="2048" spellcheck="false">${esc(start.codeValue)}</textarea></label><p class="v72-code-help" data-help></p><div class="v72-code-size"><label>宽度 · mm<input name="w" type="number" min="8" max="1500" step="0.5" value="${start.w}"></label><label>高度 · mm<input name="h" type="number" min="8" max="1500" step="0.5" value="${start.h}"></label></div><label class="v72-check"><input name="codeShowText" type="checkbox" ${start.codeShowText?'checked':''}>显示条码下方文字</label><button type="submit">生成预览</button></form><section class="v72-code-result"><div class="v72-code-preview" data-preview aria-label="编码预览"></div><p role="status" data-status></p><p role="alert" data-error></p><div class="v72-code-actions"><button class="primary" data-insert ${onInsert?'':'hidden'}>${initial?'更新所选编码':'插入唛头'}</button><button data-svg>下载 SVG</button><button data-png>下载 PNG · 300 DPI</button></div><small>在当前浏览器生成。SVG 可按原尺寸打印；QR 与二维编码始终保持原生模块比例。运输唛头已有的条码＋QR组合仍保持整体。</small></section></div>`;
 document.body.append(d);let config=null,valid=false,timer=null,disposed=false;
 const close=()=>{disposed=true;clearTimeout(timer);d.close();d.remove();};d.querySelector('[data-close]').onclick=close;d.addEventListener('cancel',e=>{e.preventDefault();close();});
 const form=d.querySelector('form'),buttons=[...d.querySelectorAll('[data-insert],[data-svg],[data-png]')];
 const read=()=>({...Object.fromEntries(new FormData(form)),w:Number(form.elements.w.value),h:Number(form.elements.h.value),codeShowText:form.elements.codeShowText.checked});
 function generate(){clearTimeout(timer);valid=false;buttons.forEach(b=>b.disabled=true);d.querySelector('[data-error]').textContent='';d.querySelector('[data-status]').textContent='';config=read();const t=codeTypeV72(config.codeType),matrix=t.category==='二维码';form.elements.codeShowText.disabled=matrix;d.querySelector('[data-help]').textContent=config.codeType==='gs1-128'?'GS1 使用 (01)…(10)… 格式，输入已有的商品及批次编号。':config.codeType==='qrcode'?'可输入网址、中文或追溯内容，也可使用 {{sku}} 等变量。':`示例：${t.example}`;
  try{const l=generatedCodeLayoutV72(config,variables);d.querySelector('[data-preview]').innerHTML=generatedCodeFileSvgV72(config,variables);d.querySelector('[data-status]').textContent=`${t.label} · ${config.w} × ${config.h} mm · 模块 ${l.module.toFixed(3)} mm · 已保留静区${l.value!==config.codeValue?" · 实际编码："+l.value:""}`;valid=true;buttons.forEach(b=>b.disabled=false);}catch(e){d.querySelector('[data-preview]').innerHTML='<span>修正内容或尺寸后生成</span>';d.querySelector('[data-error]').textContent=e.message;}
 }
 let lastType=start.codeType;form.elements.codeType.onchange=()=>{const previous=codeTypeV72(lastType),next=codeTypeV72(form.elements.codeType.value);if(form.elements.codeValue.value===previous.example)form.elements.codeValue.value=next.example;const matrix=next.category==='二维码';form.elements.w.value=matrix?(next.id==='pdf417'?100:40):100;form.elements.h.value=matrix?40:32;lastType=next.id;generate();};
 form.addEventListener('input',()=>{valid=false;buttons.forEach(b=>b.disabled=true);clearTimeout(timer);timer=setTimeout(generate,150);});form.onsubmit=e=>{e.preventDefault();generate();};
 d.querySelector('[data-insert]').onclick=()=>{if(!valid)return;try{onInsert(config);close();}catch(e){d.querySelector('[data-error]').textContent=e.message;}};
 d.querySelector('[data-svg]').onclick=()=>{if(valid)download(new Blob([generatedCodeFileSvgV72(config,variables)],{type:'image/svg+xml'}),`boxstudio-${config.codeType}.svg`);};
 d.querySelector('[data-png]').onclick=async()=>{if(!valid)return;const snapshot=structuredClone(config);buttons.forEach(b=>b.disabled=true);try{const blob=await codePngV72(snapshot,variables);if(disposed)return;download(blob,`boxstudio-${snapshot.codeType}-300dpi.png`);d.querySelector('[data-status]').textContent='300 DPI PNG 已生成并下载。';}catch(e){if(!disposed)d.querySelector('[data-error]').textContent=e.message;}finally{if(!disposed)generate();}};
 generate();d.showModal();return d;
}
