function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function clone(v){return structuredClone(v)}
function selectedIds(state){const list=Array.isArray(state?.crossPanelEdit?.selection)?state.crossPanelEdit.selection:[];const valid=list.filter(id=>(state?.elements||[]).some(e=>e.id===id&&e.type==='cross-panel-artwork'));if(valid.length)return valid;const one=(state?.elements||[]).find(e=>e.id===state?.selectedId&&e.type==='cross-panel-artwork');return one?[one.id]:[]}
function candidates(geo,axis){const out=[];for(const p of Object.values(geo?.panelMap||{})){if(!p)continue;const x=num(p.x),y=num(p.y),w=num(p.w),h=num(p.h);if(axis==='x')out.push(x,x+w,x+w/2);else out.push(y,y+h,y+h/2)}return out}
function bestSnap(value,list,tol){let best=null;for(const c of list){const d=c-value;if(Math.abs(d)<=tol&&(!best||Math.abs(d)<Math.abs(best.delta)))best={value:c,delta:d}}return best}
function boxFor(elements=[]){if(!elements.length)return{x:0,y:0,w:0,h:0};const xs=elements.flatMap(e=>[num(e.x),num(e.x)+num(e.w)]),ys=elements.flatMap(e=>[num(e.y),num(e.y)+num(e.h)]);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);return{x:minX,y:minY,w:maxX-minX,h:maxY-minY}}
export function getCrossSelection(state){return selectedIds(state)}
export function setCrossSelection(state,ids=[]){const next=clone(state||{}),valid=[...new Set(ids)].filter(id=>(next.elements||[]).some(e=>e.id===id&&e.type==='cross-panel-artwork'));next.crossPanelEdit={snap:true,gridMm:5,toleranceMm:3,angleStep:15,...(next.crossPanelEdit||{}),selection:valid};next.selectedId=valid.at(-1)||next.selectedId;return next}
export function toggleCrossSelection(state,id,{additive=false}={}){const current=selectedIds(state);if(!additive)return setCrossSelection(state,[id]);return setCrossSelection(state,current.includes(id)?current.filter(x=>x!==id):[...current,id])}
export function snapGroupDelta(state,ids,dx,dy,geo,{gridMm=5,toleranceMm=3,snap=true}={}){if(!snap)return{dx,dy,guides:[]};const els=(state?.elements||[]).filter(e=>ids.includes(e.id)),box=boxFor(els),grid=Math.max(.1,num(gridMm,5)),tol=Math.max(0,num(toleranceMm,3)),xs=candidates(geo,'x'),ys=candidates(geo,'y'),xTargets=[box.x+dx,box.x+box.w/2+dx,box.x+box.w+dx],yTargets=[box.y+dy,box.y+box.h/2+dy,box.y+box.h+dy];let sx=null,sy=null;for(const v of xTargets){const hit=bestSnap(v,xs,tol);if(hit&&(!sx||Math.abs(hit.delta)<Math.abs(sx.delta)))sx=hit}for(const v of yTargets){const hit=bestSnap(v,ys,tol);if(hit&&(!sy||Math.abs(hit.delta)<Math.abs(sy.delta)))sy=hit}let ndx=dx+(sx?.delta||0),ndy=dy+(sy?.delta||0);if(!sx){const left=box.x+ndx,gridHit=Math.round(left/grid)*grid-left;if(Math.abs(gridHit)<=tol)ndx+=gridHit}if(!sy){const top=box.y+ndy,gridHit=Math.round(top/grid)*grid-top;if(Math.abs(gridHit)<=tol)ndy+=gridHit}return{dx:ndx,dy:ndy,guides:[sx&&{axis:'x',value:sx.value},sy&&{axis:'y',value:sy.value}].filter(Boolean)}}
export function translateCrossSelection(state,ids,dx,dy,geo,options={}){const next=clone(state||{}),snap=snapGroupDelta(next,ids,dx,dy,geo,options);for(const el of next.elements||[])if(ids.includes(el.id)&&el.type==='cross-panel-artwork'){el.x=num(el.x)+snap.dx;el.y=num(el.y)+snap.dy}next.crossPanelEdit={snap:true,gridMm:5,toleranceMm:3,angleStep:15,...(next.crossPanelEdit||{}),selection:[...ids]};next.selectedId=ids.at(-1)||next.selectedId;return{state:next,guides:snap.guides,delta:{x:snap.dx,y:snap.dy}}}
export function resizeCrossElement(state,id,w,h,{lockAspect=true,minSize=4}={}){const next=clone(state||{}),el=(next.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork');if(!el)return next;const ow=Math.max(.001,num(el.w,1)),oh=Math.max(.001,num(el.h,1)),aspect=ow/oh;let nw=Math.max(minSize,num(w,ow)),nh=Math.max(minSize,num(h,oh));if(lockAspect&&el.lockAspect!==false){if(Math.abs(nw-ow)>=Math.abs(nh-oh))nh=nw/aspect;else nw=nh*aspect}el.w=nw;el.h=nh;return next}
export function rotateCrossElement(state,id,angle,{snap=true,step=15}={}){const next=clone(state||{}),el=(next.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork');if(!el)return next;let a=num(angle);const s=Math.max(1,num(step,15));if(snap)a=Math.round(a/s)*s;el.r=((a%360)+360)%360;return next}
export function selectionBounds(state,ids=getCrossSelection(state)){return boxFor((state?.elements||[]).filter(e=>ids.includes(e.id)&&e.type==='cross-panel-artwork'))}
