import { materializeSvgAppearanceElement, clipPolygonConvex, triangulateSimple } from './productionAppearance.js';
import { materializeSvgMarkElement, validateSvgMark } from './svgMark.js';

function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function panelPoly(panel){if(Array.isArray(panel?.points)&&panel.points.length>=3)return panel.points.map(p=>[num(p[0]),num(p[1])]);const x=num(panel?.x),y=num(panel?.y),w=num(panel?.w),h=num(panel?.h);return[[x,y],[x+w,y],[x+w,y+h],[x,y+h]]}
function pointInPoly(p,poly=[]){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j],hit=((a[1]>p[1])!==(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/((b[1]-a[1])||1e-12)+a[0]);if(hit)inside=!inside}return inside}
function segHit(a,b,c,d){const dx1=b[0]-a[0],dy1=b[1]-a[1],dx2=d[0]-c[0],dy2=d[1]-c[1],den=dx1*dy2-dy1*dx2;if(Math.abs(den)<1e-10)return null;const t=((c[0]-a[0])*dy2-(c[1]-a[1])*dx2)/den,u=((c[0]-a[0])*dy1-(c[1]-a[1])*dx1)/den;if(t<-1e-9||t>1+1e-9||u<-1e-9||u>1+1e-9)return null;return Math.max(0,Math.min(1,t))}
function clipLineToPoly(a,b,poly=[]){const ts=[0,1];for(let i=0;i<poly.length;i++){const t=segHit(a,b,poly[i],poly[(i+1)%poly.length]);if(t!=null)ts.push(t)}ts.sort((x,y)=>x-y);const uniq=ts.filter((t,i)=>!i||Math.abs(t-ts[i-1])>1e-7),out=[];for(let i=0;i<uniq.length-1;i++){const t0=uniq[i],t1=uniq[i+1],tm=(t0+t1)/2,p=[a[0]+(b[0]-a[0])*tm,a[1]+(b[1]-a[1])*tm];if(!pointInPoly(p,poly))continue;out.push([[a[0]+(b[0]-a[0])*t0,a[1]+(b[1]-a[1])*t0],[a[0]+(b[0]-a[0])*t1,a[1]+(b[1]-a[1])*t1]])}return out}
function localize(points,panel){return points.map(p=>[p[0]-num(panel.x),p[1]-num(panel.y)])}
function polygonFragments(points,panel){const pp=panelPoly(panel),tris=triangulateSimple(pp),out=[];for(const tri of tris){const q=clipPolygonConvex(points,tri);if(q.length>=3&&Math.abs(q.reduce((a,p,i)=>{const n=q[(i+1)%q.length];return a+p[0]*n[1]-n[0]*p[1]},0))>1e-7)out.push(q)}return out}
export function createCrossPanelArtwork(svgMark,{id=null,x=0,y=0,width=120,height=null,rotation=0,label=null,zIndex=null}={}){const check=validateSvgMark(svgMark);if(!check.ok)throw new Error(check.errors.join(' '));const w=Math.max(1,num(width,120)),h=Math.max(1,height==null?w*num(svgMark.height,1)/Math.max(.001,num(svgMark.width,1)):num(height));return{id:id||`cross-art-${Date.now().toString(36)}`,type:'cross-panel-artwork',group:'marks',x:num(x),y:num(y),w,h,r:num(rotation),lockAspect:true,zIndex:Number.isFinite(Number(zIndex))?Number(zIndex):undefined,svgMark:structuredClone(svgMark),label:label||svgMark.name||'Cross-panel artwork'} }
export function promoteSvgSymbolToCrossPanel(element,geo){if(element?.type!=='svg-symbol')throw new Error('Only an imported SVG symbol can be promoted to cross-panel artwork.');const panel=geo?.panelMap?.[element.panelId];if(!panel)throw new Error(`Panel not found: ${element.panelId}`);return createCrossPanelArtwork(element.svgMark,{id:`cross-${element.id}`,x:num(panel.x)+num(element.x),y:num(panel.y)+num(element.y),width:num(element.w),height:num(element.h),rotation:num(element.r),label:element.label||element.svgMark?.name,zIndex:element.zIndex})}
export function materializeCrossPanelArtworkElement(element,geo,{gradientDepth=2}={}){
  if(element?.type!=='cross-panel-artwork')return[];const temp={...structuredClone(element),type:'svg-symbol',panelId:'__global__'},fills=materializeSvgAppearanceElement(temp,{gradientDepth}),lines=materializeSvgMarkElement(temp),out=[],zIndex=Number.isFinite(Number(element.zIndex))?Number(element.zIndex):0;
  for(const [panelId,panel] of Object.entries(geo?.panelMap||{})){
    if(!panel||num(panel.w)<=0||num(panel.h)<=0)continue;
    for(const fill of fills)for(const frag of polygonFragments(fill.points,panel))out.push({...fill,id:`${fill.id}-${panelId}-${out.length}`,panelId,points:localize(frag,panel),crossPanelSourceId:element.id,zIndex});
    const poly=panelPoly(panel);for(const ln of lines){const a=[num(ln.x),num(ln.y)],b=[num(ln.x)+num(ln.w),num(ln.y)+num(ln.h)];for(const seg of clipLineToPoly(a,b,poly)){const la=[seg[0][0]-num(panel.x),seg[0][1]-num(panel.y)],lb=[seg[1][0]-num(panel.x),seg[1][1]-num(panel.y)];out.push({id:`${element.id}-line-${panelId}-${out.length}`,type:'line',group:'marks',panelId,x:la[0],y:la[1],w:lb[0]-la[0],h:lb[1]-la[1],r:0,crossPanelSourceId:element.id,zIndex})}}
  }
  return out;
}
export function materializeCrossPanelArtworkState(state,geo,{gradientDepth=2}={}){const next=structuredClone(state||{}),out=[];for(const el of next.elements||[]){if(el?.type==='cross-panel-artwork')out.push(...materializeCrossPanelArtworkElement(el,geo,{gradientDepth}));else out.push(el)}next.elements=out;return next}
export function crossPanelArtworkDiagnostics(state,geo){const items=[];for(const el of state?.elements||[]){if(el?.type!=='cross-panel-artwork')continue;const fragments=materializeCrossPanelArtworkElement(el,geo),panels=[...new Set(fragments.map(x=>x.panelId))];items.push({id:el.id,label:el.label||el.id,panels,fragmentCount:fragments.length,polygonFragments:fragments.filter(x=>x.type==='production-polygon').length,lineFragments:fragments.filter(x=>x.type==='line').length,status:panels.length>=2?'cross-panel':panels.length===1?'single-panel':'outside'});}return{items,count:items.length,crossPanel:items.filter(x=>x.panels.length>=2).length,outside:items.filter(x=>!x.panels.length).length,fragments:items.reduce((n,x)=>n+x.fragmentCount,0)}}
