import {generatedCodeLayoutV72,generatedCodeChecksV72} from './codeGeneratorV72.js';
import {assertBarcodePdfV70} from './barcodePdfCheckV70.js';
import {barcodeGroupLayoutV70,assertBarcodeProductionV70} from './barcodeGroupV70.js';
import {standaloneIconPdfV67} from './standaloneIconV67.js';
import { renderTemplate, isPackageNoticeVisible } from './variables.js';
import { generateGeometry, resolveElementRect, uniqueLines } from './geometry.js';
import { barcodeLayout } from './barcode.js';
import { qrMatrix } from './qrcode.js';
import { flattenCurves } from './importDieline.js';
import { vectorTextRects, supportsVectorText } from './vectorText.js';
import { getUserTtf } from './fontRegistry.js';
import { textOutlineCommands, commandsToSvgPath } from './ttfOutline.js';
import { getOutputIcc } from './iccRegistry.js';
import { spotNameFor } from './printProfiles.js';
import { imagePdfSourceV60, normalizeImageElementV60 } from './artworkImageV60.js';

export function downloadText(filename, text, type='text/plain;charset=utf-8') {const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function downloadBytes(filename, bytes, type='application/octet-stream') {const blob=new Blob([bytes],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

function commandBounds(cmds=[]){const xs=[],ys=[];for(const c of cmds){for(const k of ['x','cx','c1x','c2x'])if(Number.isFinite(c[k]))xs.push(c[k]);for(const k of ['y','cy','c1y','c2y'])if(Number.isFinite(c[k]))ys.push(c[k])}return xs.length?{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}:{minX:0,maxX:0,minY:0,maxY:0}}
function shiftCommands(cmds=[],dx=0,dy=0){return cmds.map(c=>{const z={...c};for(const k of ['x','cx','c1x','c2x'])if(k in z)z[k]+=dx;for(const k of ['y','cy','c1y','c2y'])if(k in z)z[k]+=dy;return z})}
function outlineSvgTexts(svg,options={}){
  const ns='http://www.w3.org/2000/svg',font=options.fontMode==='ttf'?getUserTtf():null;
  svg.querySelectorAll('text.svg-text').forEach(t=>{
    const text=t.textContent||'',size=Number(t.getAttribute('font-size'))||7,bold=/bold|700|800|900/i.test(t.getAttribute('font-weight')||''),x0=Number(t.getAttribute('x'))||0,y=Number(t.getAttribute('y'))||0,anchor=t.getAttribute('text-anchor');
    if(font){let cmds=textOutlineCommands(font,text,0,y-size,size),b=commandBounds(cmds),x=x0;if(anchor==='middle')x-=((b.maxX-b.minX)/2);else if(anchor==='end')x-=(b.maxX-b.minX);cmds=shiftCommands(cmds,x-b.minX,0);const path=document.createElementNS(ns,'path');path.setAttribute('d',commandsToSvgPath(cmds));path.setAttribute('fill','#111');path.setAttribute('data-text-outlined','true');path.setAttribute('data-font-outline',font.name);t.replaceWith(path);return}
    let x=x0;const cell=size/7,width=Math.max(0,[...text].length*cell*6-cell);if(anchor==='middle')x-=width/2;else if(anchor==='end')x-=width;const g=document.createElementNS(ns,'g');g.setAttribute('fill','#111');g.setAttribute('data-text-outlined','true');g.setAttribute('data-font-outline','BoxStudioTechnical');for(const r of vectorTextRects(text,x,y-size,size,{bold})){const rect=document.createElementNS(ns,'rect');rect.setAttribute('x',r.x.toFixed(3));rect.setAttribute('y',r.y.toFixed(3));rect.setAttribute('width',r.w.toFixed(3));rect.setAttribute('height',r.h.toFixed(3));g.appendChild(rect)}t.replaceWith(g);
  });
}
function annotateSvgSpots(svg,options={}){const map=[['.dieline-cut','CUT'],['.dieline-crease','CREASE'],['.dieline-perf','PERF'],['.dieline-glue','GLUE']];for(const [sel,kind] of map)svg.querySelectorAll(sel).forEach(n=>{n.setAttribute('data-spot-name',spotNameFor(options,kind));n.setAttribute('data-overprint',options.overprintDielines!==false?'true':'false')})}
export function cleanSvg(svgEl,options={}){const clone=svgEl.cloneNode(true);clone.querySelectorAll('.selection-box,.selection-handle,.ui-only').forEach(n=>n.remove());if(options.outlineText)outlineSvgTexts(clone,options);if(options.spotDielines!==false)annotateSvgSpots(clone,options);clone.removeAttribute('style');clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const vb=clone.viewBox.baseVal;clone.setAttribute('width',vb.width+'mm');clone.setAttribute('height',vb.height+'mm');return new XMLSerializer().serializeToString(clone)}
export function exportSvg(svgEl,options={}){downloadText('boxstudio-production.svg',cleanSvg(svgEl,options),'image/svg+xml;charset=utf-8')}
export async function exportPng(svgEl,options={}){const svgText=cleanSvg(svgEl,options),blob=new Blob([svgText],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});const maxW=2600,ratio=img.naturalHeight/img.naturalWidth,canvas=document.createElement('canvas');canvas.width=maxW;canvas.height=Math.max(1,Math.round(maxW*ratio));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);const pngBlob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png')),pngUrl=URL.createObjectURL(pngBlob),a=document.createElement('a');a.href=pngUrl;a.download='boxstudio-preview.png';a.click();setTimeout(()=>URL.revokeObjectURL(pngUrl),1000)}

function asciiPdf(s=''){return String(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'?')}
const PT=72/25.4,f=n=>(Number(n)||0).toFixed(3);
function pdfLine(cmds,pageH,l,{dash=false,width=.45}={}){cmds.push(`${f(width)} w ${dash?'[8 5] 0 d':'[] 0 d'} ${f(l.x1*PT)} ${f((pageH-l.y1)*PT)} m ${f(l.x2*PT)} ${f((pageH-l.y2)*PT)} l S`)}
function pdfSpotLine(cmds,pageH,l,resource,{dash=false,width=.45,overprint=true}={}){cmds.push(`q ${overprint?'/GSOP gs ':''}/${resource} CS 1 SCN ${f(width)} w ${dash?'[8 5] 0 d':'[] 0 d'} ${f(l.x1*PT)} ${f((pageH-l.y1)*PT)} m ${f(l.x2*PT)} ${f((pageH-l.y2)*PT)} l S Q`)}
function pdfRect(cmds,pageH,x,y,w,h,fill=true){cmds.push(`${f(x*PT)} ${f((pageH-y-h)*PT)} ${f(w*PT)} ${f(h*PT)} re ${fill?'f':'S'}`)}
function pdfText(cmds,pageH,x,yTop,sizeMm,text,{bold=false}={}){const font=bold?'/F2':'/F1',sizePt=Math.max(3,sizeMm*PT);String(text).split('\n').forEach((line,i)=>{const baseline=pageH-(yTop+(i+1)*sizeMm*1.15);cmds.push(`BT ${font} ${f(sizePt)} Tf ${f(x*PT)} ${f(baseline*PT)} Td (${asciiPdf(line)}) Tj ET`)})}
function pdfVectorText(cmds,pageH,x,yTop,sizeMm,text,{bold=false}={}){cmds.push('0 0 0 1 k');for(const r of vectorTextRects(String(text),x,yTop,sizeMm,{bold}))pdfRect(cmds,pageH,r.x,r.y,r.w,r.h,true)}
function pdfTtfPath(cmds,pageH,commands=[]){let cur=null;for(const c of commands){if(c.op==='M'){cmds.push(`${f(c.x*PT)} ${f((pageH-c.y)*PT)} m`);cur={x:c.x,y:c.y}}else if(c.op==='L'){cmds.push(`${f(c.x*PT)} ${f((pageH-c.y)*PT)} l`);cur={x:c.x,y:c.y}}else if(c.op==='Q'&&cur){const c1x=cur.x+2/3*(c.cx-cur.x),c1y=cur.y+2/3*(c.cy-cur.y),c2x=c.x+2/3*(c.cx-c.x),c2y=c.y+2/3*(c.cy-c.y);cmds.push(`${f(c1x*PT)} ${f((pageH-c1y)*PT)} ${f(c2x*PT)} ${f((pageH-c2y)*PT)} ${f(c.x*PT)} ${f((pageH-c.y)*PT)} c`);cur={x:c.x,y:c.y}}else if(c.op==='Z')cmds.push('h')}cmds.push('f')}
function pdfTtfText(cmds,pageH,x,yTop,sizeMm,text){const font=getUserTtf();if(!font)throw new Error('TTF outline mode 已启用但当前会话未加载字体文件');cmds.push('0 0 0 1 k');pdfTtfPath(cmds,pageH,textOutlineCommands(font,String(text),x,yTop,sizeMm))}
function pdfTextMode(cmds,pageH,x,yTop,sizeMm,text,{bold=false,outline=false,fontMode='technical'}={}){if(outline&&fontMode==='ttf')return pdfTtfText(cmds,pageH,x,yTop,sizeMm,text);if(outline)return pdfVectorText(cmds,pageH,x,yTop,sizeMm,text,{bold});return pdfText(cmds,pageH,x,yTop,sizeMm,text,{bold})}

function renderBarcodeQrPdf(cmds,pageH,el,absX,absY,variables,textOpts={}){const barcodeValue=renderTemplate(el.barcodeValue,variables),qrValue=renderTemplate(el.qrValue,variables),{pad,qrSide,bw,bh,fontSize,labelTop,stroke}=barcodeGroupLayoutV70(el),bx=absX+pad,by=absY+pad;cmds.push('q 0 0 0 0 k');pdfRect(cmds,pageH,absX,absY,el.w,el.h,true);cmds.push(`Q 0 0 0 1 K 0 0 0 1 k ${f(stroke*PT)} w [] 0 d`);cmds.push(`${f(absX*PT)} ${f((pageH-absY-el.h)*PT)} ${f(el.w*PT)} ${f(el.h*PT)} re S`);const layout=barcodeLayout(el.barcodeType||'CODE39',barcodeValue,bw,bh);for(const b of layout.bars)pdfRect(cmds,pageH,bx+b.x,by+b.y,b.w,b.h,true);if(layout.bearer)cmds.push(`${f(bx*PT)} ${f((pageH-by-bh)*PT)} ${f(bw*PT)} ${f(bh*PT)} re S`);pdfTextMode(cmds,pageH,bx,absY+labelTop,fontSize,layout.label,textOpts);const qx=absX+el.w-pad-qrSide,qy=absY+pad;pdfRect(cmds,pageH,qx,qy,qrSide,qrSide,false);const qr=qrMatrix(qrValue),quiet=4,modules=qr.size+quiet*2,cell=qrSide/modules;for(let r=0;r<qr.size;r++)for(let c=0;c<qr.size;c++)if(qr.matrix[r][c])pdfRect(cmds,pageH,qx+(quiet+c)*cell,qy+(quiet+r)*cell,cell+.001,cell+.001,true)}
function renderGeneratedCodePdfV72(cmds,pageH,el,x,y,vars,textOpts){const l=generatedCodeLayoutV72(el,vars);cmds.push('q 0 0 0 0 k');pdfRect(cmds,pageH,x,y,el.w,el.h,true);cmds.push('0 0 0 1 k');for(const r of l.rects)pdfRect(cmds,pageH,x+r.x,y+r.y,r.w,r.h,true);if(l.label)pdfTextMode(cmds,pageH,x+el.w*.04,y+el.h-l.fontSize*1.3,l.fontSize,l.label,textOpts);cmds.push('Q');}
function renderIconPdf(cmds,pageH,el,absX,absY){cmds.push(...standaloneIconPdfV67(el,absX,absY,pageH,PT));}

function base64Bytes(src=''){const data=String(src).split(',')[1]||'';if(typeof atob==='function'){const bin=atob(data),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}if(typeof Buffer!=='undefined')return new Uint8Array(Buffer.from(data,'base64'));throw new Error('Base64 decoder unavailable')}
function pdfImagePlacement(el,absX,absY){const iw=Math.max(1,Number(el.pixelWidth)||1),ih=Math.max(1,Number(el.pixelHeight)||1),boxW=Math.max(.1,Number(el.w)||1),boxH=Math.max(.1,Number(el.h)||1),fit=el.fit||'contain';if(fit==='stretch')return{x:absX,y:absY,w:boxW,h:boxH,clip:false};const scale=fit==='cover'?Math.max(boxW/iw,boxH/ih):Math.min(boxW/iw,boxH/ih),w=iw*scale,h=ih*scale;return{x:absX+(boxW-w)/2,y:absY+(boxH-h)/2,w,h,clip:fit==='cover'}}
function renderImagePdf(cmds,pageH,raw,absX,absY,resource){const el=normalizeImageElementV60(raw),p=pdfImagePlacement(el,absX,absY),boxX=absX*PT,boxY=(pageH-absY-el.h)*PT,boxW=el.w*PT,boxH=el.h*PT,x=p.x*PT,y=(pageH-p.y-p.h)*PT,w=p.w*PT,h=p.h*PT,deg=Number(el.r)||0,cx=(absX+el.w/2)*PT,cy=(pageH-(absY+el.h/2))*PT;cmds.push('q');if(deg){const a=deg*Math.PI/180,c=Math.cos(a),s=Math.sin(a),tx=cx-c*cx+s*cy,ty=cy-s*cx-c*cy;cmds.push(`${f(c)} ${f(s)} ${f(-s)} ${f(c)} ${f(tx)} ${f(ty)} cm`)}if(p.clip)cmds.push(`${f(boxX)} ${f(boxY)} ${f(boxW)} ${f(boxH)} re W n`);if(el.opacity<.999)cmds.push(`/${resource.gs} gs`);cmds.push(`${f(w)} 0 0 ${f(h)} ${f(x)} ${f(y)} cm /${resource.name} Do Q`)}

function drawDielines(cmds,geo,options={}){const spot=options.spotDielines!==false,op=options.overprintDielines!==false,sets=[['CUT','CSCUT',geo.cutLines,geo.cutCurves,false,.35],['CREASE','CSCREASE',geo.creaseLines,geo.creaseCurves,true,.30],['PERF','CSPERF',geo.perfLines,geo.perfCurves,true,.30],['GLUE','CSGLUE',geo.glueLines,geo.glueCurves,true,.28]];for(const [kind,res,lines,curves,dash,width] of sets)for(const l of uniqueLines([...(lines||[]),...flattenCurves(curves||[],32)])){if(spot)pdfSpotLine(cmds,geo.height,l,res,{dash,width,overprint:op});else{cmds.push('0 0 0 1 K');pdfLine(cmds,geo.height,l,{dash,width})}}}
function buildPageContent(state){const geo=generateGeometry(state.structure),outline=Boolean(state.exportOptions?.outlineText),fontMode=state.exportOptions?.fontMode||'technical',cmds=['q','0 0 0 0 k',`0 0 ${f(geo.width*PT)} ${f(geo.height*PT)} re f`,'Q'],images=[];drawDielines(cmds,geo,state.exportOptions||{});cmds.push('0 0 0 1 K 0 0 0 1 k');const textOpts={outline,fontMode};if(!state.hiddenGroups.marks)for(const el of state.elements){if(el.hidden||el.type==='notice'&&!isPackageNoticeVisible(state.variables))continue;const rr=resolveElementRect(el,geo),x=rr.absX,y=rr.absY;if(el.type==='text'||el.type==='notice')pdfTextMode(cmds,geo.height,x+3,y,el.fontSize||4.5,renderTemplate(el.template,state.variables),{bold:el.bold,...textOpts});else if(el.type==='image'){const src=imagePdfSourceV60(el);if(!src)throw new Error(`Production PDF image source missing: ${el.name||el.id}`);const index=images.length+1,resource={name:`Im${index}`,gs:`GSIm${index}`};images.push({resource,...normalizeImageElementV60(el),bytes:base64Bytes(src)});renderImagePdf(cmds,geo.height,el,x,y,resource)}else if(el.type==='generated-code')renderGeneratedCodePdfV72(cmds,geo.height,el,x,y,state.variables,textOpts);else if(el.type==='barcode-qr-group')renderBarcodeQrPdf(cmds,geo.height,el,x,y,state.variables,textOpts);else if(el.type==='icon')renderIconPdf(cmds,geo.height,el,x,y,textOpts);else if(el.type==='shape'){cmds.push('0 0 0 1 K [] 0 d 0.6 w');pdfRect(cmds,geo.height,x,y,el.w,el.h,false)}else if(el.type==='line'){cmds.push('0 0 0 1 K [] 0 d 0.6 w');pdfLine(cmds,geo.height,{x1:x,y1:y,x2:x+el.w,y2:y+el.h},{width:.6})}}return{geo,stream:cmds.join('\n')+'\n',options:state.exportOptions||{},images}}

function pdfName(s='Spot'){return String(s).replace(/[^A-Za-z0-9_.-]/g,ch=>'#'+ch.charCodeAt(0).toString(16).toUpperCase().padStart(2,'0'))}
function spotResources(options={}){const names={CUT:pdfName(spotNameFor(options,'CUT')),CREASE:pdfName(spotNameFor(options,'CREASE')),PERF:pdfName(spotNameFor(options,'PERF')),GLUE:pdfName(spotNameFor(options,'GLUE'))};return `/ColorSpace << /CSCUT [/Separation /${names.CUT} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [0 1 0 0] /N 1 >>] /CSCREASE [/Separation /${names.CREASE} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [1 0 0 0] /N 1 >>] /CSPERF [/Separation /${names.PERF} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [0 0 1 0] /N 1 >>] /CSGLUE [/Separation /${names.GLUE} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [1 0 1 0] /N 1 >>] >>`}
function extStateResources(page){const entries=[];if(page.options?.spotDielines!==false&&page.options?.overprintDielines!==false)entries.push('/GSOP << /Type /ExtGState /OP true /op true /OPM 1 >>');for(const im of page.images||[])if(im.opacity<.999)entries.push(`/${im.resource.gs} << /Type /ExtGState /ca ${f(im.opacity)} /CA ${f(im.opacity)} >>`);return entries.length?`/ExtGState << ${entries.join(' ')} >>`:''}
function concatBytes(chunks){let total=0;for(const c of chunks)total+=c.length;const out=new Uint8Array(total);let at=0;for(const c of chunks){out.set(c,at);at+=c.length}return out}
function xmlEsc(s=''){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
export function pdfxCandidateIssues(state){if(state.exportOptions?.pdfxMode!=='candidate')return[];const issues=[],icc=getOutputIcc(),visible=(state.elements||[]).filter(e=>!(e.type==='notice'&&!isPackageNoticeVisible(state.variables||{})));if(!icc)issues.push('未加载 CMYK ICC OutputIntent');else if(!icc.isCmyk)issues.push(`当前 ICC 色彩空间为 ${icc.colorSpace||'Unknown'}，V0.8 Candidate 仅接受 CMYK profile`);if(!state.exportOptions?.outlineText)issues.push('PDF/X Candidate 要求文字转曲，避免未嵌入 Base14 字体');const rotated=visible.filter(e=>Math.abs(Number(e.r)||0)>0.001&&e.type!=='image');if(rotated.length)issues.push(`当前 PDF serializer 尚未实现非图片对象旋转：${rotated.map(e=>e.id).join(', ')}`);if(visible.some(e=>e.type==='image'))issues.push('PDF/X-4 Candidate 暂不接收 RGB raster artwork；请使用 Production PDF，或在专业印前流程中完成 CMYK 图像转换后再认证 PDF/X');return issues}
function buildXmp(options={},icc){const id=xmlEsc(options.outputConditionIdentifier||icc?.name||'Custom CMYK');return `<?xpacket begin="\ufeff" id="W5M0MpCehiHzreSzNTczkc9"?>\n<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="BoxStudio V0.8">\n<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n<rdf:Description rdf:about="" xmlns:pdfxid="http://www.npes.org/pdfx/ns/id/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:pdf="http://ns.adobe.com/pdf/1.3/">\n<pdfxid:GTS_PDFXVersion>PDF/X-4</pdfxid:GTS_PDFXVersion><dc:format>application/pdf</dc:format><xmp:CreatorTool>BoxStudio V0.8</xmp:CreatorTool><pdf:Producer>BoxStudio V0.8</pdf:Producer><pdf:Keywords>${id}</pdf:Keywords>\n</rdf:Description></rdf:RDF></x:xmpmeta>\n<?xpacket end="w"?>`}
function assemblePdf(pages){
  const enc=new TextEncoder(),n=pages.length,candidate=pages.some(p=>p.options?.pdfxMode==='candidate'),icc=candidate?getOutputIcc():null;
  let next=3;const pageIds=Array.from({length:n},()=>next++),contentIds=Array.from({length:n},()=>next++),fontRegular=candidate?0:next++,fontBold=candidate?0:next++,info=next++;let iccId=0,outputIntentId=0,metadataId=0;if(candidate){iccId=next++;outputIntentId=next++;metadataId=next++}const imageIds=pages.map(p=>(p.images||[]).map(()=>next++)),total=next-1,kids=pageIds.map(id=>`${id} 0 R`).join(' '),objects=new Array(total+1);
  const catalogExtras=candidate?` /Metadata ${metadataId} 0 R /OutputIntents [${outputIntentId} 0 R]`:'';objects[1]=`<< /Type /Catalog /Pages 2 0 R${catalogExtras} >>`;objects[2]=`<< /Type /Pages /Kids [${kids}] /Count ${n} >>`;
  pages.forEach((p,i)=>{const W=f(p.geo.width*PT),H=f(p.geo.height*PT),spot=p.options?.spotDielines!==false?spotResources(p.options):'',fontRes=candidate?'':`/Font << /F1 ${fontRegular} 0 R /F2 ${fontBold} 0 R >>`,xobj=(p.images||[]).length?`/XObject << ${(p.images||[]).map((im,j)=>`/${im.resource.name} ${imageIds[i][j]} 0 R`).join(' ')} >>`:'',ext=extStateResources(p);objects[pageIds[i]]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /TrimBox [0 0 ${W} ${H}] /BleedBox [0 0 ${W} ${H}] /Resources << ${fontRes} ${spot} ${xobj} ${ext} >> /Contents ${contentIds[i]} 0 R >>`;objects[contentIds[i]]=`<< /Length ${enc.encode(p.stream).length} >>\nstream\n${p.stream}endstream`;for(let j=0;j<(p.images||[]).length;j++){const im=p.images[j],bytes=im.bytes,head=enc.encode(`<< /Type /XObject /Subtype /Image /Width ${Math.max(1,Math.round(im.pixelWidth))} /Height ${Math.max(1,Math.round(im.pixelHeight))} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bytes.length} >>\nstream\n`),tail=enc.encode('\nendstream');objects[imageIds[i][j]]=concatBytes([head,bytes,tail])}});
  if(!candidate){objects[fontRegular]=`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>`;objects[fontBold]=`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>`;}
  objects[info]=`<< /Producer (${asciiPdf(pages[0]?.options?.producer||'BoxStudio V0.8')}) /Creator (BoxStudio) /Title (${asciiPdf(pages[0]?.options?.documentTitle||'Packaging Production Artwork')}) /Trapped /False${candidate?' /GTS_PDFXVersion (PDF/X-4)':''} >>`;
  if(candidate){if(!icc?.isCmyk)throw new Error('PDF/X Candidate requires a loaded CMYK ICC profile');const iccHead=enc.encode(`<< /N 4 /Alternate /DeviceCMYK /Length ${icc.bytes.length} >>\nstream\n`),iccTail=enc.encode('\nendstream');objects[iccId]=concatBytes([iccHead,icc.bytes,iccTail]);const opt=pages[0]?.options||{},identifier=asciiPdf(opt.outputConditionIdentifier||icc.name||'Custom CMYK'),infoText=asciiPdf(opt.outputConditionInfo||`User supplied ICC: ${icc.name}`);objects[outputIntentId]=`<< /Type /OutputIntent /S /GTS_PDFX /OutputConditionIdentifier (${identifier}) /Info (${infoText}) /RegistryName (http://www.color.org) /DestOutputProfile ${iccId} 0 R >>`;const xmp=enc.encode(buildXmp(opt,icc));objects[metadataId]=concatBytes([enc.encode(`<< /Type /Metadata /Subtype /XML /Length ${xmp.length} >>\nstream\n`),xmp,enc.encode('\nendstream')])}
  const chunks=[enc.encode('%PDF-1.6\n%BoxStudio V0.8\n')],offsets=new Array(total+1).fill(0);let pos=chunks[0].length;
  for(let i=1;i<=total;i++){offsets[i]=pos;const body=objects[i] instanceof Uint8Array?objects[i]:enc.encode(String(objects[i]));const obj=concatBytes([enc.encode(`${i} 0 obj\n`),body,enc.encode('\nendobj\n')]);chunks.push(obj);pos+=obj.length}
  const xref=pos;let tail=`xref\n0 ${total+1}\n0000000000 65535 f \n`;for(let i=1;i<=total;i++)tail+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;tail+=`trailer\n<< /Size ${total+1} /Root 1 0 R /Info ${info} 0 R >>\nstartxref\n${xref}\n%%EOF\n`;chunks.push(enc.encode(tail));return concatBytes(chunks)
}
export function buildProductionPdf(state){const generatedErrors=generatedCodeChecksV72(state);if(generatedErrors.length)throw new Error(generatedErrors.map(e=>e.message).join('\n'));assertBarcodeProductionV70(state);const issues=pdfxCandidateIssues(state);if(issues.length)throw new Error('PDF/X Candidate blocked: '+issues.join('；'));return assertBarcodePdfV70(state,assemblePdf([buildPageContent(state)]))}
export function buildMultiPagePdf(states=[]){if(!states.length)throw new Error('No pages to export');for(const s of states){assertBarcodeProductionV70(s);const issues=pdfxCandidateIssues(s);if(issues.length)throw new Error('PDF/X Candidate blocked: '+issues.join('；'))}return assemblePdf(states.map(s=>{const page=buildPageContent(s);assertBarcodePdfV70(s,assemblePdf([page]));return page;}))}
export function exportPdf(state){downloadBytes('boxstudio-production-1to1.pdf',buildProductionPdf(state),'application/pdf')}
export {supportsVectorText};
export function exportMultiPagePdf(states,filename='boxstudio-batch-combined.pdf'){downloadBytes(filename,buildMultiPagePdf(states),'application/pdf')}

export function buildDxf(state){const geo=generateGeometry(state.structure),lines=[],add=s=>lines.push(String(s));add('0');add('SECTION');add('2');add('HEADER');add('9');add('$INSUNITS');add('70');add('4');add('0');add('ENDSEC');add('0');add('SECTION');add('2');add('TABLES');add('0');add('TABLE');add('2');add('LAYER');add('70');add('4');for(const [name,color] of [['CUT','7'],['CREASE','1'],['PERF','6'],['GLUE','3']]){add('0');add('LAYER');add('2');add(name);add('70');add('0');add('62');add(color);add('6');add('CONTINUOUS')}add('0');add('ENDTAB');add('0');add('ENDSEC');add('0');add('SECTION');add('2');add('ENTITIES');const putLine=(l,layer)=>{add('0');add('LINE');add('8');add(layer);add('10');add(f(l.x1));add('20');add(f(geo.height-l.y1));add('30');add('0');add('11');add(f(l.x2));add('21');add(f(geo.height-l.y2));add('31');add('0')};uniqueLines([...(geo.cutLines||[]),...flattenCurves(geo.cutCurves||[],32)]).forEach(l=>putLine(l,'CUT'));uniqueLines([...(geo.creaseLines||[]),...flattenCurves(geo.creaseCurves||[],32)]).forEach(l=>putLine(l,'CREASE'));uniqueLines([...(geo.perfLines||[]),...flattenCurves(geo.perfCurves||[],32)]).forEach(l=>putLine(l,'PERF'));uniqueLines([...(geo.glueLines||[]),...flattenCurves(geo.glueCurves||[],32)]).forEach(l=>putLine(l,'GLUE'));add('0');add('ENDSEC');add('0');add('EOF');return lines.join('\r\n')+'\r\n'}
export function exportDxf(state){downloadText('boxstudio-structure.dxf',buildDxf(state),'application/dxf;charset=utf-8')}
