import { renderTemplate, isPackageNoticeVisible } from './variables.js';
import { generateGeometry, resolveElementRect, uniqueLines } from './geometry.js';
import { barcodeLayout } from './barcode.js';
import { qrMatrix } from './qrcode.js';
import { flattenCurves } from './importDieline.js';
import { vectorTextRects } from './vectorText.js';
import { getUserTtf } from './fontRegistry.js';
import { textOutlineCommands } from './ttfOutline.js';
import { getOutputIcc } from './iccRegistry.js';
import { spotNameFor } from './printProfiles.js';
import { cleanSvg, downloadText, downloadBytes, pdfxCandidateIssues } from './export.js';
import { materializeSvgAppearanceState, parseColor } from './productionAppearance.js';
import { materializeCrossPanelArtworkState } from './crossPanelArtwork.js';

const PT=72/25.4,f=n=>(Number(n)||0).toFixed(3);
function asciiPdf(s=''){return String(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'?')}
function xmlEsc(s=''){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function escAttr(s=''){return xmlEsc(s)}
function pdfLine(cmds,pageH,l,{dash=false,width=.45}={}){cmds.push(`${f(width)} w ${dash?'[8 5] 0 d':'[] 0 d'} ${f(l.x1*PT)} ${f((pageH-l.y1)*PT)} m ${f(l.x2*PT)} ${f((pageH-l.y2)*PT)} l S`)}
function pdfSpotLine(cmds,pageH,l,resource,{dash=false,width=.45,overprint=true}={}){cmds.push(`q ${overprint?'/GSOP gs ':''}/${resource} CS 1 SCN ${f(width)} w ${dash?'[8 5] 0 d':'[] 0 d'} ${f(l.x1*PT)} ${f((pageH-l.y1)*PT)} m ${f(l.x2*PT)} ${f((pageH-l.y2)*PT)} l S Q`)}
function pdfRect(cmds,pageH,x,y,w,h,fill=true){cmds.push(`${f(x*PT)} ${f((pageH-y-h)*PT)} ${f(w*PT)} ${f(h*PT)} re ${fill?'f':'S'}`)}
function pdfText(cmds,pageH,x,yTop,sizeMm,text,{bold=false}={}){const font=bold?'/F2':'/F1',sizePt=Math.max(3,sizeMm*PT);String(text).split('\n').forEach((line,i)=>{const baseline=pageH-(yTop+(i+1)*sizeMm*1.15);cmds.push(`BT ${font} ${f(sizePt)} Tf ${f(x*PT)} ${f(baseline*PT)} Td (${asciiPdf(line)}) Tj ET`)})}
function pdfVectorText(cmds,pageH,x,yTop,sizeMm,text,{bold=false}={}){cmds.push('0 0 0 1 k');for(const r of vectorTextRects(String(text),x,yTop,sizeMm,{bold}))pdfRect(cmds,pageH,r.x,r.y,r.w,r.h,true)}
function pdfTtfPath(cmds,pageH,commands=[]){let cur=null;for(const c of commands){if(c.op==='M'){cmds.push(`${f(c.x*PT)} ${f((pageH-c.y)*PT)} m`);cur={x:c.x,y:c.y}}else if(c.op==='L'){cmds.push(`${f(c.x*PT)} ${f((pageH-c.y)*PT)} l`);cur={x:c.x,y:c.y}}else if(c.op==='Q'&&cur){const c1x=cur.x+2/3*(c.cx-cur.x),c1y=cur.y+2/3*(c.cy-cur.y),c2x=c.x+2/3*(c.cx-c.x),c2y=c.y+2/3*(c.cy-c.y);cmds.push(`${f(c1x*PT)} ${f((pageH-c1y)*PT)} ${f(c2x*PT)} ${f((pageH-c2y)*PT)} ${f(c.x*PT)} ${f((pageH-c.y)*PT)} c`);cur={x:c.x,y:c.y}}else if(c.op==='Z')cmds.push('h')}cmds.push('f')}
function pdfTtfText(cmds,pageH,x,yTop,sizeMm,text){const font=getUserTtf();if(!font)throw new Error('TTF outline mode enabled but no user TTF is loaded.');cmds.push('0 0 0 1 k');pdfTtfPath(cmds,pageH,textOutlineCommands(font,String(text),x,yTop,sizeMm))}
function pdfTextMode(cmds,pageH,x,yTop,sizeMm,text,{bold=false,outline=false,fontMode='technical'}={}){if(outline&&fontMode==='ttf')return pdfTtfText(cmds,pageH,x,yTop,sizeMm,text);if(outline)return pdfVectorText(cmds,pageH,x,yTop,sizeMm,text,{bold});return pdfText(cmds,pageH,x,yTop,sizeMm,text,{bold})}
function pdfPolygon(cmds,pageH,points,color='#000'){if(!points?.length)return;const [r,g,b]=parseColor(color);cmds.push(`${f(r)} ${f(g)} ${f(b)} rg`);cmds.push(`${f(points[0][0]*PT)} ${f((pageH-points[0][1])*PT)} m`);for(let i=1;i<points.length;i++)cmds.push(`${f(points[i][0]*PT)} ${f((pageH-points[i][1])*PT)} l`);cmds.push('h f')}
function renderBarcodeQrPdf(cmds,pageH,el,absX,absY,variables,textOpts={}){const barcodeValue=renderTemplate(el.barcodeValue,variables),qrValue=renderTemplate(el.qrValue,variables),pad=5,gap=7,qrSide=Math.max(20,Math.min(el.h-pad*2,el.w*.30)),bx=absX+pad,by=absY+pad,bw=Math.max(30,el.w-pad*2-gap-qrSide),bh=Math.max(16,el.h-pad*2-11);cmds.push('0 0 0 1 K 0 0 0 1 k');cmds.push(`${f(absX*PT)} ${f((pageH-absY-el.h)*PT)} ${f(el.w*PT)} ${f(el.h*PT)} re S`);const layout=barcodeLayout(el.barcodeType||'CODE39',barcodeValue,bw,bh);for(const bar of layout.bars)pdfRect(cmds,pageH,bx+bar.x,by+bar.y,bar.w,bar.h,true);if(layout.bearer)cmds.push(`${f(bx*PT)} ${f((pageH-by-bh)*PT)} ${f(bw*PT)} ${f(bh*PT)} re S`);pdfTextMode(cmds,pageH,bx,absY+el.h-10,3.3,layout.label,textOpts);const qx=absX+el.w-pad-qrSide,qy=absY+pad;pdfRect(cmds,pageH,qx,qy,qrSide,qrSide,false);const qr=qrMatrix(qrValue),quiet=4,modules=qr.size+quiet*2,cell=qrSide/modules;for(let rr=0;rr<qr.size;rr++)for(let c=0;c<qr.size;c++)if(qr.matrix[rr][c])pdfRect(cmds,pageH,qx+(quiet+c)*cell,qy+(quiet+rr)*cell,cell+.001,cell+.001,true)}
function renderIconPdf(cmds,pageH,el,absX,absY,textOpts={}){cmds.push('0 0 0 1 K [] 0 d 0.8 w');cmds.push(`${f(absX*PT)} ${f((pageH-absY-el.h)*PT)} ${f(el.w*PT)} ${f(el.h*PT)} re S`);const cx=absX+el.w/2;if(el.icon==='up'){for(const dx of [-el.w*.18,el.w*.18]){pdfLine(cmds,pageH,{x1:cx+dx,y1:absY+el.h*.72,x2:cx+dx,y2:absY+el.h*.27},{width:.8});pdfLine(cmds,pageH,{x1:cx+dx,y1:absY+el.h*.27,x2:cx+dx-el.w*.10,y2:absY+el.h*.42},{width:.8});pdfLine(cmds,pageH,{x1:cx+dx,y1:absY+el.h*.27,x2:cx+dx+el.w*.10,y2:absY+el.h*.42},{width:.8})}}else if(el.icon==='fragile')pdfTextMode(cmds,pageH,absX+el.w*.31,absY+el.h*.18,el.h*.42,'Y',textOpts);else{pdfLine(cmds,pageH,{x1:absX+el.w*.18,y1:absY+el.h*.48,x2:absX+el.w*.5,y2:absY+el.h*.20},{width:.7});pdfLine(cmds,pageH,{x1:absX+el.w*.5,y1:absY+el.h*.20,x2:absX+el.w*.82,y2:absY+el.h*.48},{width:.7});pdfLine(cmds,pageH,{x1:absX+el.w*.5,y1:absY+el.h*.20,x2:absX+el.w*.5,y2:absY+el.h*.78},{width:.7})}}
function drawDielines(cmds,geo,options={}){const spot=options.spotDielines!==false,op=options.overprintDielines!==false,sets=[['CUT','CSCUT',geo.cutLines,geo.cutCurves,false,.35],['CREASE','CSCREASE',geo.creaseLines,geo.creaseCurves,true,.30],['PERF','CSPERF',geo.perfLines,geo.perfCurves,true,.30],['GLUE','CSGLUE',geo.glueLines,geo.glueCurves,true,.28]];for(const [kind,res,lines,curves,dash,width] of sets)for(const l of uniqueLines([...(lines||[]),...flattenCurves(curves||[],32)])){if(spot)pdfSpotLine(cmds,geo.height,l,res,{dash,width,overprint:op});else{cmds.push('0 0 0 1 K');pdfLine(cmds,geo.height,l,{dash,width})}}}
export function prepareV19ProductionState(state,{gradientDepth=2}={}){const geo=generateGeometry(state.structure),cross=materializeCrossPanelArtworkState(state,geo,{gradientDepth}),prepared=materializeSvgAppearanceState(cross,{includeOutlines:true,gradientDepth});return{state:prepared,geo}}
function buildPageContent(state){const geo=generateGeometry(state.structure),outline=Boolean(state.exportOptions?.outlineText),fontMode=state.exportOptions?.fontMode||'technical',cmds=['q','0 0 0 0 k',`0 0 ${f(geo.width*PT)} ${f(geo.height*PT)} re f`,'Q'];drawDielines(cmds,geo,state.exportOptions||{});cmds.push('0 0 0 1 K 0 0 0 1 k');const textOpts={outline,fontMode};if(!state.hiddenGroups?.marks)for(const el of state.elements||[]){if(el.type==='notice'&&!isPackageNoticeVisible(state.variables))continue;if(el.type==='production-polygon'){const panel=geo.panelMap?.[el.panelId];if(!panel)continue;pdfPolygon(cmds,geo.height,(el.points||[]).map(p=>[num(panel.x)+num(p[0]),num(panel.y)+num(p[1])]),el.fillColor||'#000');continue}const rr=resolveElementRect(el,geo),x=rr.absX,y=rr.absY;if(el.type==='text'||el.type==='notice')pdfTextMode(cmds,geo.height,x+3,y,el.fontSize||4.5,renderTemplate(el.template,state.variables),{bold:el.bold,...textOpts});else if(el.type==='barcode-qr-group')renderBarcodeQrPdf(cmds,geo.height,el,x,y,state.variables,textOpts);else if(el.type==='icon')renderIconPdf(cmds,geo.height,el,x,y,textOpts);else if(el.type==='shape'){cmds.push('0 0 0 1 K [] 0 d 0.6 w');pdfRect(cmds,geo.height,x,y,el.w,el.h,false)}else if(el.type==='line'){cmds.push('0 0 0 1 K [] 0 d 0.6 w');pdfLine(cmds,geo.height,{x1:x,y1:y,x2:x+el.w,y2:y+el.h},{width:.6})}}return{geo,stream:cmds.join('\n')+'\n',options:state.exportOptions||{}}}
function pdfName(s='Spot'){return String(s).replace(/[^A-Za-z0-9_.-]/g,ch=>'#'+ch.charCodeAt(0).toString(16).toUpperCase().padStart(2,'0'))}
function spotResources(options={}){const names={CUT:pdfName(spotNameFor(options,'CUT')),CREASE:pdfName(spotNameFor(options,'CREASE')),PERF:pdfName(spotNameFor(options,'PERF')),GLUE:pdfName(spotNameFor(options,'GLUE'))};return `/ColorSpace << /CSCUT [/Separation /${names.CUT} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [0 1 0 0] /N 1 >>] /CSCREASE [/Separation /${names.CREASE} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [1 0 0 0] /N 1 >>] /CSPERF [/Separation /${names.PERF} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [0 0 1 0] /N 1 >>] /CSGLUE [/Separation /${names.GLUE} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [1 0 1 0] /N 1 >>] >> /ExtGState << /GSOP << /Type /ExtGState /OP true /op true /OPM 1 >> >>`}
function concatBytes(chunks){let total=0;for(const c of chunks)total+=c.length;const out=new Uint8Array(total);let at=0;for(const c of chunks){out.set(c,at);at+=c.length}return out}
function buildXmp(options={},icc){const id=xmlEsc(options.outputConditionIdentifier||icc?.name||'Custom CMYK');return `<?xpacket begin="\ufeff" id="W5M0MpCehiHzreSzNTczkc9w"?>\n<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="BoxStudio V0.19"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description rdf:about="" xmlns:pdfxid="http://www.npes.org/pdfx/ns/id/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:pdf="http://ns.adobe.com/pdf/1.3/"><pdfxid:GTS_PDFXVersion>PDF/X-4</pdfxid:GTS_PDFXVersion><dc:format>application/pdf</dc:format><xmp:CreatorTool>BoxStudio V0.19</xmp:CreatorTool><pdf:Producer>BoxStudio V0.19</pdf:Producer><pdf:Keywords>${id}</pdf:Keywords></rdf:Description></rdf:RDF></x:xmpmeta>\n<?xpacket end="w"?>`}
function assemblePdf(page){const enc=new TextEncoder(),candidate=page.options?.pdfxMode==='candidate',icc=candidate?getOutputIcc():null;let next=3,pageId=next++,contentId=next++,fontRegular=candidate?0:next++,fontBold=candidate?0:next++,info=next++,iccId=0,outputIntentId=0,metadataId=0;if(candidate){iccId=next++;outputIntentId=next++;metadataId=next++}const total=next-1,objects=new Array(total+1),extras=candidate?` /Metadata ${metadataId} 0 R /OutputIntents [${outputIntentId} 0 R]`:'';objects[1]=`<< /Type /Catalog /Pages 2 0 R${extras} >>`;objects[2]=`<< /Type /Pages /Kids [${pageId} 0 R] /Count 1 >>`;const W=f(page.geo.width*PT),H=f(page.geo.height*PT),spot=page.options?.spotDielines!==false?spotResources(page.options):'',fontRes=candidate?'':`/Font << /F1 ${fontRegular} 0 R /F2 ${fontBold} 0 R >>`;objects[pageId]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /TrimBox [0 0 ${W} ${H}] /BleedBox [0 0 ${W} ${H}] /Resources << ${fontRes} ${spot} >> /Contents ${contentId} 0 R >>`;objects[contentId]=`<< /Length ${enc.encode(page.stream).length} >>\nstream\n${page.stream}endstream`;if(!candidate){objects[fontRegular]=`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>`;objects[fontBold]=`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>`}objects[info]=`<< /Producer (BoxStudio V0.19) /Creator (BoxStudio) /Title (Packaging Production Artwork V0.19) /Trapped /False${candidate?' /GTS_PDFXVersion (PDF/X-4)':''} >>`;if(candidate){if(!icc?.isCmyk)throw new Error('PDF/X Candidate requires a loaded CMYK ICC profile');const head=enc.encode(`<< /N 4 /Alternate /DeviceCMYK /Length ${icc.bytes.length} >>\nstream\n`);objects[iccId]=concatBytes([head,icc.bytes,enc.encode('\nendstream')]);const opt=page.options||{},identifier=asciiPdf(opt.outputConditionIdentifier||icc.name||'Custom CMYK'),infoText=asciiPdf(opt.outputConditionInfo||`User supplied ICC: ${icc.name}`);objects[outputIntentId]=`<< /Type /OutputIntent /S /GTS_PDFX /OutputConditionIdentifier (${identifier}) /Info (${infoText}) /RegistryName (http://www.color.org) /DestOutputProfile ${iccId} 0 R >>`;const xmp=enc.encode(buildXmp(opt,icc));objects[metadataId]=concatBytes([enc.encode(`<< /Type /Metadata /Subtype /XML /Length ${xmp.length} >>\nstream\n`),xmp,enc.encode('\nendstream')])}const chunks=[enc.encode('%PDF-1.6\n%BoxStudio V0.19\n')],offsets=new Array(total+1).fill(0);let pos=chunks[0].length;for(let i=1;i<=total;i++){offsets[i]=pos;const body=objects[i] instanceof Uint8Array?objects[i]:enc.encode(String(objects[i])),obj=concatBytes([enc.encode(`${i} 0 obj\n`),body,enc.encode('\nendobj\n')]);chunks.push(obj);pos+=obj.length}const xref=pos;let tail=`xref\n0 ${total+1}\n0000000000 65535 f \n`;for(let i=1;i<=total;i++)tail+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;tail+=`trailer\n<< /Size ${total+1} /Root 1 0 R /Info ${info} 0 R >>\nstartxref\n${xref}\n%%EOF\n`;chunks.push(enc.encode(tail));return concatBytes(chunks)}
export function buildProductionPdfV19(state,options={}){const prepared=prepareV19ProductionState(state,options).state,issues=pdfxCandidateIssues(prepared);if(issues.length)throw new Error('PDF/X Candidate blocked: '+issues.join('；'));return assemblePdf(buildPageContent(prepared))}
function overlayMarkup(prepared,geo){const out=['<g data-boxstudio-v19="production-appearance">'];for(const el of prepared.elements||[]){const panel=geo.panelMap?.[el.panelId];if(el.type==='production-polygon'&&panel){const pts=(el.points||[]).map(p=>`${f(num(panel.x)+num(p[0]))},${f(num(panel.y)+num(p[1]))}`).join(' ');out.push(`<polygon points="${pts}" fill="${escAttr(el.fillColor||'#000')}" stroke="none" data-source="${escAttr(el.appearanceSourceId||el.crossPanelSourceId||'')}"/>`)}else if(el.type==='line'&&el.crossPanelSourceId&&panel){const x1=num(panel.x)+num(el.x),y1=num(panel.y)+num(el.y),x2=x1+num(el.w),y2=y1+num(el.h);out.push(`<line x1="${f(x1)}" y1="${f(y1)}" x2="${f(x2)}" y2="${f(y2)}" stroke="#111" stroke-width="0.35" fill="none" data-source="${escAttr(el.crossPanelSourceId)}"/>`)}}out.push('</g>');return out.join('')}
export function buildProductionSvgV19(svgEl,state,options={}){if(!svgEl)throw new Error('Open the 2D editor before exporting the appearance-aware SVG.');const geo=generateGeometry(state.structure),prepared=prepareV19ProductionState(state,options).state,base=cleanSvg(svgEl,state.exportOptions||{}),overlay=overlayMarkup(prepared,geo),m=base.match(/<(?:g|path|line|polyline|polygon)[^>]*class="[^"]*dieline-/i);if(m&&Number.isFinite(m.index))return base.slice(0,m.index)+overlay+base.slice(m.index);return base.replace(/<\/svg>\s*$/i,overlay+'</svg>')}
export function exportProductionPdfV19(state,options={}){downloadBytes('boxstudio-v0.19-production.pdf',buildProductionPdfV19(state,options),'application/pdf')}
export function exportProductionSvgV19(svgEl,state,options={}){downloadText('boxstudio-v0.19-production.svg',buildProductionSvgV19(svgEl,state,options),'image/svg+xml;charset=utf-8')}
