import {actionableTemplatesV47} from './productExperienceV47.js';
import {defaultsForTemplate,generateGeometry} from './geometry.js';
import {presetsForTemplateV48,previewSvgForTemplateV48} from './productExperienceV48.js';
import {foldedMeshesV71} from './threeExportV71.js';
import {buildFoldGraph} from './foldgraph.js';
import {scenePointV71} from './scene3dV71.js';
import {defaultState} from './model.js';
import {DESIGN_PRESETS_V71} from './designTemplatesV71.js';
const specimen=id=>({...defaultsForTemplate(id),...(presetsForTemplateV48(id)[0]||{})});
const CACHE=new Map(),KEY='boxstudio-v75-box-favorites';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function favorites(){try{const rows=JSON.parse(localStorage.getItem(KEY)||'[]');return new Set(Array.isArray(rows)?rows:[]);}catch{return new Set();}}
export function modelPreviewSvgV75(id){
 if(CACHE.has(id))return CACHE.get(id);
 const structure=specimen(id),geo=generateGeometry(structure),meshes=foldedMeshesV71({...defaultState,structure,elements:[]},geo,buildFoldGraph(geo)),yaw=.65,pitch=.38;
 const view=p=>{const q=scenePointV71(meshes,p),x=Math.cos(yaw)*q[0]+Math.sin(yaw)*q[2],z=-Math.sin(yaw)*q[0]+Math.cos(yaw)*q[2];return[x,-Math.cos(pitch)*q[1]+Math.sin(pitch)*z,Math.sin(pitch)*q[1]+Math.cos(pitch)*z];};
 const panels=meshes.panels.filter(p=>!/(^glue$|(?:^|-)(?:glue|tab)$)/.test(p.nodeId)).map(p=>({p,points:p.points.map(view)})).sort((a,b)=>a.points.reduce((s,q)=>s+q[2],0)/a.points.length-b.points.reduce((s,q)=>s+q[2],0)/b.points.length),all=panels.flatMap(p=>p.points),xmin=Math.min(...all.map(p=>p[0])),xmax=Math.max(...all.map(p=>p[0])),ymin=Math.min(...all.map(p=>p[1])),ymax=Math.max(...all.map(p=>p[1])),scale=Math.min(254/Math.max(1,xmax-xmin),152/Math.max(1,ymax-ymin)),paper=structure.materialId?.includes('kraft')?[204,175,128]:[235,230,219];
 const svg='<svg viewBox="0 0 320 210" role="img" aria-label="'+esc(geo.documentTitle||id)+'真实折叠模型" data-v75-model="'+id+'"><ellipse cx="160" cy="183" rx="88" ry="8" fill="#202733" opacity=".06"/>'+panels.map(({p,points})=>{const shade=.72+.24*Math.abs(p.normal[0]*.5+p.normal[1]*.7+p.normal[2]*.4),color=paper.map(v=>Math.round(v*shade));return '<polygon data-panel="'+esc(p.nodeId)+'" points="'+points.map(q=>[(160+(q[0]-(xmin+xmax)/2)*scale).toFixed(2),(99+(q[1]-(ymin+ymax)/2)*scale).toFixed(2)].join(',')).join(' ')+'" fill="rgb('+color.join(',')+')" stroke="#a39d92" stroke-width=".7" stroke-linejoin="round"/>';}).join('')+'</svg>';
 CACHE.set(id,svg);return svg;
}
function enhance(){const page=document.querySelector('.page:has(.v47-template-grid)');if(!page)return;const grid=page.querySelector('[data-v47-grid]');if(!grid)return;
 if(!page.dataset.v75Library){page.dataset.v75Library='true';const hero=page.querySelector('.v47-hero');if(hero){hero.querySelector('h1').textContent='盒型 / 模型库';hero.querySelector('p').textContent='选择结构，定制尺寸，开始你的包装设计。平面刀版与立体模型来自同一套参数。';const k=hero.querySelector('.v47-kicker');if(k)k.textContent='THE PAPER STUDIO · '+actionableTemplatesV47().length+' PARAMETRIC STRUCTURES';}
  const toolbar=page.querySelector('.v47-template-toolbar'),tools=document.createElement('div');tools.className='v75-library-controls';tools.innerHTML='<div role="group" aria-label="模型浏览方式"><button data-v75-view="3d" aria-pressed="true">3D 模型</button><button data-v75-view="2d" aria-pressed="false">2D 刀版</button></div><button data-v75-box-favorites aria-pressed="false">☆ 我的收藏</button><label>排序<select data-v75-sort><option value="default">结构分类</option><option value="name">名称 A → Z</option></select></label><span data-v75-box-count></span>';toolbar.append(tools);page.dataset.v75View='3d';
  tools.querySelectorAll('[data-v75-view]').forEach(b=>b.onclick=()=>{page.dataset.v75View=b.dataset.v75View;tools.querySelectorAll('[data-v75-view]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));apply(page);});tools.querySelector('[data-v75-box-favorites]').onclick=e=>{const b=e.currentTarget;b.setAttribute('aria-pressed',String(b.getAttribute('aria-pressed')!=='true'));apply(page);};tools.querySelector('[data-v75-sort]').onchange=()=>apply(page);
 }
 let changed=false;for(const card of grid.querySelectorAll('.v47-template-card')){if(card.dataset.v75Card)continue;const id=card.querySelector('[data-v47-template]')?.dataset.v47Template,t=actionableTemplatesV47().find(t=>t.id===id);if(!t)continue;card.dataset.v75Card=id;card.dataset.v48Preview='true';const visual=card.querySelector('.v47-template-visual'),s=specimen(id);visual.innerHTML='<div data-v75-model-preview>'+modelPreviewSvgV75(id)+'</div><div data-v75-dieline-preview hidden>'+previewSvgForTemplateV48(id)+'</div><small>'+esc(t.standard==='CUSTOM'?'CUSTOM':t.code)+'</small><button class="v75-box-star" data-v75-box-star="'+id+'" aria-label="收藏 '+esc(t.nameZh)+'" aria-pressed="false">☆</button>';card.querySelector('.v47-template-copy p').textContent=t.name;const meta=document.createElement('div');meta.className='v75-box-meta';meta.innerHTML='<span>示例 '+s.length+' × '+s.width+' × '+s.height+' mm</span><span>'+(s.materialId?.includes('kraft')?'牛皮纸':(!s.materialId||s.materialId?.includes('corrugated'))?'瓦楞纸':'白卡纸')+'</span>';card.querySelector('[data-v47-template]').before(meta);visual.querySelector('[data-v75-box-star]').onclick=e=>{try{const rows=favorites();if(rows.has(id))rows.delete(id);else rows.add(id);localStorage.setItem(KEY,JSON.stringify([...rows]));apply(page);}catch{window.BoxStudioV67?.toast?.('收藏未保存，请检查浏览器存储空间。');}};changed=true;}
 if(changed)apply(page);const designText=page.querySelector('[data-v71-design-center] p');if(designText&&!designText.dataset.v75Count){designText.textContent=DESIGN_PRESETS_V71.length+' 款原创设计 · 创建副本后，每个元素均可继续编辑';designText.dataset.v75Count='true';}
}
function apply(page){const rows=favorites(),only=page.querySelector('[data-v75-box-favorites]')?.getAttribute('aria-pressed')==='true',grid=page.querySelector('[data-v47-grid]');let count=0;for(const card of grid.querySelectorAll('[data-v75-card]')){card.hidden=only&&!rows.has(card.dataset.v75Card);if(!card.hidden)count++;const star=card.querySelector('[data-v75-box-star]'),liked=rows.has(card.dataset.v75Card);star.setAttribute('aria-pressed',String(liked));star.setAttribute('aria-label',(liked?'取消收藏 ':'收藏 ')+card.querySelector('h3').textContent);if(star.textContent!==(liked?'★':'☆'))star.textContent=liked?'★':'☆';card.querySelector('[data-v75-model-preview]').hidden=page.dataset.v75View==='2d';card.querySelector('[data-v75-dieline-preview]').hidden=page.dataset.v75View!=='2d';}
 const order=page.querySelector('[data-v75-sort]')?.value,cards=[...grid.querySelectorAll('[data-v75-card]')],catalog=actionableTemplatesV47();const sorted=[...cards].sort((a,b)=>order==='name'?a.querySelector('h3').textContent.localeCompare(b.querySelector('h3').textContent,'zh-CN'):catalog.findIndex(t=>t.id===a.dataset.v75Card)-catalog.findIndex(t=>t.id===b.dataset.v75Card));if(cards.some((c,i)=>c!==sorted[i]))grid.append(...sorted);const label=count+' 个可用盒型',status=page.querySelector('[data-v75-box-count]');if(status&&status.textContent!==label)status.textContent=label;let empty=grid.querySelector('[data-v75-empty]');if(!count&&!empty){empty=document.createElement('p');empty.dataset.v75Empty='true';empty.className='v75-empty';empty.textContent='当前筛选没有盒型。试试其他分类，或点击卡片星标收藏。';grid.append(empty);}if(empty)empty.hidden=count>0;}
window.BoxStudioUiRuntimeV64?.register('v75-library',enhance);
