import { resolveMaterialV32 } from './materialsV32.js';
import { templateCatalogById } from './templates.js';
import { ensureFoldSequenceV51, buildFoldSequenceModelV51 } from './foldSequenceV51.js';

export const V55_MANUFACTURING_SCHEMA='boxstudio-v55-manufacturing-intelligence';
export const V55_PRODUCT_VERSION='V0.55';
export const V55_MANUFACTURING_VERSION=1;
const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const round=(v,p=2)=>{const m=10**p;return Math.round(num(v)*m)/m};
const WEIGHT={error:28,warning:9,info:0,pass:0};
const MACHINE_PREFERRED=new Set(['side-seal-rsc','fefco-0203','reverse-tuck-end','straight-tuck-end','auto-lock-bottom','sleeve-carton']);
const PROFILES=Object.freeze({
  safe:{id:'safe',label:'Safe',description:'保守制造检查；适合出生产文件前的风险筛查。',panelFactor:7,glueFactor:6,minGlue:18,tuckFactor:5,maxConcurrent:3,strictCollision:true,strictCompensation:true},
  machine:{id:'machine',label:'Machine',description:'自动/半自动模切、折叠、糊盒路径；对胶舌、同步折叠和小面更严格。',panelFactor:6,glueFactor:5,minGlue:15,tuckFactor:4,maxConcurrent:4,strictCollision:true,strictCompensation:true},
  manual:{id:'manual',label:'Manual',description:'人工装盒路径；允许更小操作空间，但仍保留结构和碰撞底线。',panelFactor:4,glueFactor:2.5,minGlue:8,tuckFactor:3,maxConcurrent:7,strictCollision:false,strictCompensation:false},
});
function bounds(p={}){if(Array.isArray(p.points)&&p.points.length>=3){const xs=p.points.map(q=>num(q?.[0])),ys=p.points.map(q=>num(q?.[1]));return{w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}return{w:Math.max(0,num(p.w)),h:Math.max(0,num(p.h))}}
function panels(geo={}){return(geo.panels?.length?geo.panels:geo.bodyPanels||[]).filter(Boolean)}
function isAction(p={}){return/tuck|tab|lock|flap|glue|lid|wing/.test(`${p.id||''} ${p.kind||''} ${p.role||''}`.toLowerCase())}
function issue(severity,code,title,detail,metric=null,recommendation=null,entityId=null){return{severity,code,title,detail,metric,recommendation,entityId}}
function creaseAdvisory(material){const t=material.thicknessMm,cat=material.category,factor=cat==='corrugated'?1.2:cat==='paperboard'?.65:1.4;return{factor,allowanceMm:round(t*factor),note:'Engineering advisory only; factory tooling/creasing matrix must override this value.'}}
function processClass(id){if(id==='side-seal-rsc'||id==='fefco-0203')return'flexo-folder-gluer / slotter compatible family';if(['reverse-tuck-end','straight-tuck-end','auto-lock-bottom','sleeve-carton'].includes(id))return'die-cut + folder-gluer family';if(['mailer-150010','fefco-0427'].includes(id))return'die-cut / erection-oriented family';return'custom converting path'}
function failOrWarn(profile){return profile.id==='manual'?'warning':'error'}
export function buildManufacturingContextV55(state={},graph={},geo={},collisionReport={}){
  const structure=state.structure||{},material=resolveMaterialV32(structure),templateId=structure.template||'side-seal-rsc',dims=panels(geo).map(p=>({id:p.id,...bounds(p),action:isAction(p)})).filter(p=>p.w>0&&p.h>0),minPanel=dims.length?Math.min(...dims.map(p=>Math.min(p.w,p.h))):0,act=dims.filter(p=>p.action),minAction=act.length?Math.min(...act.map(p=>Math.min(p.w,p.h))):minPanel;
  const seq=ensureFoldSequenceV51(state,graph),model=buildFoldSequenceModelV51(seq,graph,geo),groups=model.steps.map(s=>s.edgeKeys.length),angles=(seq.foldAuthoringV50?.edges||[]).map(e=>Math.abs(num(e.angle))).filter(Number.isFinite);
  return{schema:V55_MANUFACTURING_SCHEMA,version:V55_MANUFACTURING_VERSION,templateId,template:templateCatalogById(templateId),structure,material,process:processClass(templateId),panels:dims,panelCount:dims.length,minPanelMm:round(minPanel),minActionPanelMm:round(minAction),folds:model.edges.length,stepCount:model.stepCount,maxConcurrentFolds:groups.length?Math.max(...groups):0,maxAngleDeg:angles.length?round(Math.max(...angles),1):0,penetrationCount:collisionReport?.penetrations?.length||0,overlapCount:collisionReport?.overlaps?.length||0,crease:creaseAdvisory(material),machinePreferred:MACHINE_PREFERRED.has(templateId)};
}
export function assessManufacturingProfileV55(ctx={},profileId='safe',overrides={}){
  const p=PROFILES[profileId]||PROFILES.safe,t=Math.max(.1,num(overrides.thicknessMm,ctx.material?.thicknessMm||.1)),s=ctx.structure||{},out=[],minPanelReq=Math.max(p.id==='manual'?8:12,t*p.panelFactor),minActionReq=Math.max(p.id==='manual'?7:10,t*p.tuckFactor),glueReq=Math.max(p.minGlue,t*p.glueFactor),glue=num(s.glue,0);
  out.push(issue('pass','V55_MATERIAL_RESOLVED','材料与厚度',`${ctx.material?.name||'Unknown'} · ${ctx.material?.flute||'CUSTOM'} · ${round(t)} mm`,round(t),'工厂纸板实测厚度可覆盖工程预设。'));
  out.push(ctx.minPanelMm<minPanelReq?issue(failOrWarn(p),'V55_PANEL_HANDLING_MARGIN','最小面板操作余量',`最小语义面板 ${ctx.minPanelMm} mm，小于 ${p.label} 建议 ${round(minPanelReq)} mm。`,ctx.minPanelMm,'增大最小面板/翼片，或切换 Manual 路径并做实样装配。'):issue('pass','V55_PANEL_HANDLING_OK','最小面板操作余量',`${ctx.minPanelMm} mm ≥ 建议 ${round(minPanelReq)} mm。`,ctx.minPanelMm));
  out.push(ctx.minActionPanelMm<minActionReq?issue(failOrWarn(p),'V55_TUCK_FLAP_MARGIN','插舌/翼片余量',`最小动作面 ${ctx.minActionPanelMm} mm，小于建议 ${round(minActionReq)} mm。`,ctx.minActionPanelMm,'增加 tuck/flap 深度或降低自动化要求。'):issue('pass','V55_TUCK_FLAP_OK','插舌/翼片余量',`${ctx.minActionPanelMm} mm ≥ 建议 ${round(minActionReq)} mm。`,ctx.minActionPanelMm));
  const glueRelevant=glue>0||ctx.panels.some(x=>/glue/i.test(x.id||''));if(glueRelevant)out.push(glue<glueReq?issue(failOrWarn(p),'V55_GLUE_FLAP_MARGIN','胶舌宽度',`当前胶舌 ${round(glue)} mm，小于 ${p.label} 建议 ${round(glueReq)} mm。`,glue,`建议胶舌 ≥ ${round(glueReq)} mm；最终以胶型、上胶轮和机台要求为准。`):issue('pass','V55_GLUE_FLAP_OK','胶舌宽度',`${round(glue)} mm ≥ 建议 ${round(glueReq)} mm。`,glue));else out.push(issue('info','V55_GLUE_NOT_REQUIRED','胶舌检查','当前结构没有显式胶舌宽度要求。'));
  out.push(!s.compensation&&t>=1.5?issue(p.strictCompensation?'error':'warning','V55_THICKNESS_COMPENSATION_OFF','材料厚度补偿关闭',`板厚 ${round(t)} mm，但尺寸补偿关闭。厚板结构的 crease-center / inside-outside 换算风险较高。`,t,'启用 thickness compensation，或使用工厂提供的 crease allowance / score-to-score 数据。'):issue('pass','V55_THICKNESS_COMPENSATION','材料厚度补偿',s.compensation===false?'薄板手工路径允许关闭，但需实样确认。':'已启用尺寸/厚度补偿。'));
  out.push(ctx.penetrationCount>0?issue('error','V55_FOLD_PENETRATION','折叠路径穿插',`${ctx.penetrationCount} 个 penetration 仍存在；不能判定为制造可行。`,ctx.penetrationCount,'先使用 V0.53/V0.54 修复折叠路径。'):issue('pass','V55_NO_PENETRATION','折叠路径穿插','完整折叠路径未检测到 penetration。',0));
  if(ctx.overlapCount>0)out.push(issue(p.strictCollision?'warning':'info','V55_FOLD_OVERLAP','折叠搭接/接触',`${ctx.overlapCount} 个 overlap/contact；可能是设计搭接，也可能影响高速装盒。`,ctx.overlapCount,'检查对应关键帧，确认属于预期搭接。'));
  out.push(ctx.maxConcurrentFolds>p.maxConcurrent?issue(p.id==='machine'?'warning':'info','V55_CONCURRENT_FOLDS','同步折叠复杂度',`单 Step 最多 ${ctx.maxConcurrentFolds} 条折线同步，${p.label} 建议 ≤ ${p.maxConcurrent}。`,ctx.maxConcurrentFolds,'拆分 Fold Step，减少同一阶段同时运动的面板。'):issue('pass','V55_CONCURRENT_FOLDS_OK','同步折叠复杂度',`最大 ${ctx.maxConcurrentFolds} 条/Step，处于建议范围。`,ctx.maxConcurrentFolds));
  if(p.id==='machine'&&!ctx.machinePreferred)out.push(issue('warning','V55_MACHINE_TEMPLATE_PATH','自动化结构适配',`${ctx.templateId} 当前更偏 ${ctx.process}，需要具体设备能力确认。`,null,'用实际 die-cutter / folder-gluer 的尺寸、进料、折叠单元限制覆盖默认判断。'));else out.push(issue('info','V55_PROCESS_CLASS','建议制造路径',ctx.process));
  if(ctx.material?.category==='rigid-board')out.push(issue('warning','V55_RIGID_BOARD_SPECIAL_PROCESS','灰板/硬板特殊工艺','Rigid board 通常需要独立开槽/裱糊/包边工艺，当前折叠启发式不能替代专用工艺卡。'));
  const errors=out.filter(x=>x.severity==='error'),warnings=out.filter(x=>x.severity==='warning'),score=clamp(100-out.reduce((sum,x)=>sum+(WEIGHT[x.severity]||0),0),0,100),status=errors.length?'fail':warnings.length?'review':'pass';
  return{schema:V55_MANUFACTURING_SCHEMA,version:V55_MANUFACTURING_VERSION,profile:{id:p.id,label:p.label,description:p.description},status,score,errors,warnings,issues:out,recommendations:out.filter(x=>x.recommendation).map(x=>({code:x.code,text:x.recommendation})),thresholds:{minPanelMm:round(minPanelReq),minActionPanelMm:round(minActionReq),minGlueMm:round(glueReq),maxConcurrentFolds:p.maxConcurrent},engineering:{creaseAllowanceMm:ctx.crease?.allowanceMm||0,creaseFactor:ctx.crease?.factor||0,factoryOverrideRequired:true}};
}
export function buildManufacturingProfilesV55(state={},graph={},geo={},collisionReport={},overrides={}){const context=buildManufacturingContextV55(state,graph,geo,collisionReport),profiles=['safe','machine','manual'].map(id=>assessManufacturingProfileV55(context,id,overrides)),recommended=[...profiles].sort((a,b)=>Number(a.status==='fail')-Number(b.status==='fail')||b.score-a.score)[0]||profiles[0];return{schema:V55_MANUFACTURING_SCHEMA,version:V55_MANUFACTURING_VERSION,context,profiles,recommendedProfileId:recommended?.profile.id||'safe',factoryOverrideRequired:true,disclaimer:'Engineering feasibility guidance only. Final production settings must be confirmed with actual board, tooling and converting equipment.'}}
export function manufacturingPreflightChecksV55(bundle={},profileId='safe',{blocking=false}={}){const p=(bundle.profiles||[]).find(x=>x.profile.id===profileId)||bundle.profiles?.[0];return p?p.issues.map(x=>({...x,severity:!blocking&&x.severity==='error'?'warning':x.severity,title:`Manufacturing · ${x.title}`})):[]}
export function manufacturingAcceptanceV55(state={},graph={},geo={},collisionReport={}){const bundle=buildManufacturingProfilesV55(state,graph,geo,collisionReport),issues=[];if(bundle.profiles.length!==3)issues.push(issue('error','V55_PROFILE_COUNT','Profile count','Safe / Machine / Manual profiles are required.'));for(const p of bundle.profiles){if(!Number.isFinite(p.score)||p.score<0||p.score>100)issues.push(issue('error','V55_SCORE_RANGE','Manufacturing score',`${p.profile.id} score must be within 0–100.`));if(!p.issues.length)issues.push(issue('error','V55_EMPTY_PROFILE','Manufacturing checks',`${p.profile.id} requires inspectable checks.`))}const safe=bundle.profiles.find(x=>x.profile.id==='safe'),manual=bundle.profiles.find(x=>x.profile.id==='manual');if(safe&&manual&&safe.thresholds.minGlueMm<manual.thresholds.minGlueMm)issues.push(issue('error','V55_PROFILE_ORDER','Profile strictness','Safe glue threshold cannot be looser than Manual.'));const errors=issues.filter(x=>x.severity==='error');return{schema:'boxstudio-v55-manufacturing-acceptance',version:1,ok:errors.length===0,issues,errors,bundle,summary:{profiles:bundle.profiles.length,recommended:bundle.recommendedProfileId,material:bundle.context.material?.materialId||null,thickness:bundle.context.material?.thicknessMm||0,penetrations:bundle.context.penetrationCount,overlaps:bundle.context.overlapCount}}}
