import { resolveMaterialV32 } from './materialsV32.js';
import { templateCatalogById } from './templates.js';
import { ensureFoldSequenceV51, buildFoldSequenceModelV51 } from './foldSequenceV51.js';

export const V55_MANUFACTURING_SCHEMA='boxstudio-v55-manufacturing-intelligence';
export const V55_PRODUCT_VERSION='V0.55';
export const V55_MANUFACTURING_VERSION=1;
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const r=(v,p=2)=>{const m=10**p;return Math.round(n(v)*m)/m};
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const W={error:28,warning:9,info:0,pass:0};
const MACHINE=new Set(['side-seal-rsc','fefco-0203','reverse-tuck-end','straight-tuck-end','auto-lock-bottom','sleeve-carton']);
const PROFILES={
 safe:{id:'safe',label:'Safe',description:'保守制造检查；适合出生产文件前的风险筛查。',panel:7,tuck:5,glue:6,minGlue:18,maxConcurrent:3,strict:true},
 machine:{id:'machine',label:'Machine',description:'自动/半自动模切、折叠、糊盒路径。',panel:6,tuck:4,glue:5,minGlue:15,maxConcurrent:4,strict:true},
 manual:{id:'manual',label:'Manual',description:'人工装盒路径；允许更小操作空间。',panel:4,tuck:3,glue:2.5,minGlue:8,maxConcurrent:7,strict:false},
};
const mk=(severity,code,title,detail,metric=null,recommendation=null)=>({severity,code,title,detail,metric,recommendation});
function box(p={}){if(Array.isArray(p.points)&&p.points.length>=3){const xs=p.points.map(q=>n(q?.[0])),ys=p.points.map(q=>n(q?.[1]));return{w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}return{w:Math.max(0,n(p.w)),h:Math.max(0,n(p.h))}}
function actionPanel(p={}){return/tuck|tab|lock|flap|glue|lid|wing/.test(`${p.id||''} ${p.kind||''} ${p.role||''}`.toLowerCase())}
function processClass(id){if(id==='side-seal-rsc'||id==='fefco-0203')return'flexo-folder-gluer / slotter compatible family';if(['reverse-tuck-end','straight-tuck-end','auto-lock-bottom','sleeve-carton'].includes(id))return'die-cut + folder-gluer family';if(['mailer-150010','fefco-0427'].includes(id))return'die-cut / erection-oriented family';return'custom converting path'}
function crease(material){let factor=1.4;if(material.category==='corrugated')factor=1.2;else if(material.category==='paperboard')factor=.65;return{factor,allowanceMm:r(material.thicknessMm*factor),note:'Engineering advisory only; factory tooling/creasing matrix must override this value.'}}
export function buildManufacturingContextV55(state={},graph={},geo={},collisionReport={}){
 const s=state.structure||{},material=resolveMaterialV32(s),templateId=s.template||'side-seal-rsc',raw=(geo.panels?.length?geo.panels:geo.bodyPanels||[]).filter(Boolean),dims=raw.map(p=>({id:p.id,...box(p),action:actionPanel(p)})).filter(p=>p.w>0&&p.h>0),mins=dims.map(p=>Math.min(p.w,p.h)),acts=dims.filter(p=>p.action).map(p=>Math.min(p.w,p.h)),seq=ensureFoldSequenceV51(state,graph),model=buildFoldSequenceModelV51(seq,graph,geo),groups=model.steps.map(x=>x.edgeKeys.length),angles=(seq.foldAuthoringV50?.edges||[]).map(e=>Math.abs(n(e.angle))).filter(Number.isFinite);
 return{schema:V55_MANUFACTURING_SCHEMA,version:1,templateId,template:templateCatalogById(templateId),structure:s,material,process:processClass(templateId),panels:dims,panelCount:dims.length,minPanelMm:r(mins.length?Math.min(...mins):0),minActionPanelMm:r(acts.length?Math.min(...acts):(mins.length?Math.min(...mins):0)),folds:model.edges.length,stepCount:model.stepCount,maxConcurrentFolds:groups.length?Math.max(...groups):0,maxAngleDeg:angles.length?r(Math.max(...angles),1):0,penetrationCount:collisionReport?.penetrations?.length||0,overlapCount:collisionReport?.overlaps?.length||0,crease:crease(material),machinePreferred:MACHINE.has(templateId)};
}
export function assessManufacturingProfileV55(ctx={},profileId='safe',overrides={}){
 const p=PROFILES[profileId]||PROFILES.safe,t=Math.max(.1,n(overrides.thicknessMm,ctx.material?.thicknessMm||.1)),s=ctx.structure||{},issues=[],minPanel=Math.max(p.id==='manual'?8:12,t*p.panel),minAction=Math.max(p.id==='manual'?7:10,t*p.tuck),minGlue=Math.max(p.minGlue,t*p.glue),glue=n(s.glue),sev=p.id==='manual'?'warning':'error';
 issues.push(mk('pass','V55_MATERIAL_RESOLVED','材料与厚度',`${ctx.material?.name||'Unknown'} · ${ctx.material?.flute||'CUSTOM'} · ${r(t)} mm`,r(t),'工厂纸板实测厚度可覆盖工程预设。'));
 issues.push(ctx.minPanelMm<minPanel?mk(sev,'V55_PANEL_HANDLING_MARGIN','最小面板操作余量',`最小语义面板 ${ctx.minPanelMm} mm，小于 ${p.label} 建议 ${r(minPanel)} mm。`,ctx.minPanelMm,'增大最小面板/翼片，或切换 Manual 路径并做实样装配。'):mk('pass','V55_PANEL_HANDLING_OK','最小面板操作余量',`${ctx.minPanelMm} mm ≥ 建议 ${r(minPanel)} mm。`,ctx.minPanelMm));
 issues.push(ctx.minActionPanelMm<minAction?mk(sev,'V55_TUCK_FLAP_MARGIN','插舌/翼片余量',`最小动作面 ${ctx.minActionPanelMm} mm，小于建议 ${r(minAction)} mm。`,ctx.minActionPanelMm,'增加 tuck/flap 深度或降低自动化要求。'):mk('pass','V55_TUCK_FLAP_OK','插舌/翼片余量',`${ctx.minActionPanelMm} mm ≥ 建议 ${r(minAction)} mm。`,ctx.minActionPanelMm));
 const glueNeeded=glue>0||ctx.panels.some(x=>/glue/i.test(x.id||''));if(glueNeeded)issues.push(glue<minGlue?mk(sev,'V55_GLUE_FLAP_MARGIN','胶舌宽度',`当前胶舌 ${r(glue)} mm，小于 ${p.label} 建议 ${r(minGlue)} mm。`,glue,`建议胶舌 ≥ ${r(minGlue)} mm；最终以胶型、上胶轮和机台要求为准。`):mk('pass','V55_GLUE_FLAP_OK','胶舌宽度',`${r(glue)} mm ≥ 建议 ${r(minGlue)} mm。`,glue));else issues.push(mk('info','V55_GLUE_NOT_REQUIRED','胶舌检查','当前结构没有显式胶舌宽度要求。'));
 issues.push(!s.compensation&&t>=1.5?mk(p.strict?'error':'warning','V55_THICKNESS_COMPENSATION_OFF','材料厚度补偿关闭',`板厚 ${r(t)} mm，但尺寸补偿关闭。`,t,'启用 thickness compensation，或使用工厂 crease allowance / score-to-score 数据。'):mk('pass','V55_THICKNESS_COMPENSATION','材料厚度补偿',s.compensation===false?'薄板手工路径允许关闭，但需实样确认。':'已启用尺寸/厚度补偿。'));
 issues.push(ctx.penetrationCount>0?mk('error','V55_FOLD_PENETRATION','折叠路径穿插',`${ctx.penetrationCount} 个 penetration 仍存在。`,ctx.penetrationCount,'先使用 V0.53/V0.54 修复折叠路径。'):mk('pass','V55_NO_PENETRATION','折叠路径穿插','完整折叠路径未检测到 penetration。',0));
 if(ctx.overlapCount>0)issues.push(mk(p.strict?'warning':'info','V55_FOLD_OVERLAP','折叠搭接/接触',`${ctx.overlapCount} 个 overlap/contact；需确认是否属于设计搭接。`,ctx.overlapCount,'检查对应关键帧；高速装盒应使用实机确认。'));
 issues.push(ctx.maxConcurrentFolds>p.maxConcurrent?mk(p.id==='machine'?'warning':'info','V55_CONCURRENT_FOLDS','同步折叠复杂度',`单 Step 最多 ${ctx.maxConcurrentFolds} 条折线同步，建议 ≤ ${p.maxConcurrent}。`,ctx.maxConcurrentFolds,'拆分 Fold Step，减少同时运动面板。'):mk('pass','V55_CONCURRENT_FOLDS_OK','同步折叠复杂度',`最大 ${ctx.maxConcurrentFolds} 条/Step，处于建议范围。`,ctx.maxConcurrentFolds));
 if(p.id==='machine'&&!ctx.machinePreferred)issues.push(mk('warning','V55_MACHINE_TEMPLATE_PATH','自动化结构适配',`${ctx.templateId} 当前更偏 ${ctx.process}。`,null,'用实际 die-cutter / folder-gluer 的进料与折叠单元限制覆盖默认判断。'));else issues.push(mk('info','V55_PROCESS_CLASS','建议制造路径',ctx.process));
 if(ctx.material?.category==='rigid-board')issues.push(mk('warning','V55_RIGID_BOARD_SPECIAL_PROCESS','灰板/硬板特殊工艺','Rigid board 需要专用开槽/裱糊/包边工艺卡。'));
 const errors=issues.filter(x=>x.severity==='error'),warnings=issues.filter(x=>x.severity==='warning'),score=clamp(100-issues.reduce((a,x)=>a+(W[x.severity]||0),0),0,100);
 return{schema:V55_MANUFACTURING_SCHEMA,version:1,profile:{id:p.id,label:p.label,description:p.description},status:errors.length?'fail':warnings.length?'review':'pass',score,errors,warnings,issues,recommendations:issues.filter(x=>x.recommendation).map(x=>({code:x.code,text:x.recommendation})),thresholds:{minPanelMm:r(minPanel),minActionPanelMm:r(minAction),minGlueMm:r(minGlue),maxConcurrentFolds:p.maxConcurrent},engineering:{creaseAllowanceMm:ctx.crease?.allowanceMm||0,creaseFactor:ctx.crease?.factor||0,factoryOverrideRequired:true}};
}
export function buildManufacturingProfilesV55(state={},graph={},geo={},collisionReport={},overrides={}){const context=buildManufacturingContextV55(state,graph,geo,collisionReport),profiles=['safe','machine','manual'].map(id=>assessManufacturingProfileV55(context,id,overrides)),recommended=[...profiles].sort((a,b)=>Number(a.status==='fail')-Number(b.status==='fail')||b.score-a.score)[0]||profiles[0];return{schema:V55_MANUFACTURING_SCHEMA,version:1,context,profiles,recommendedProfileId:recommended.profile.id,factoryOverrideRequired:true,disclaimer:'Engineering feasibility guidance only. Final production settings must be confirmed with actual board, tooling and converting equipment.'}}
export function manufacturingPreflightChecksV55(bundle={},profileId='safe',{blocking=false}={}){const p=bundle.profiles?.find(x=>x.profile.id===profileId)||bundle.profiles?.[0];return p?p.issues.map(x=>({...x,severity:!blocking&&x.severity==='error'?'warning':x.severity,title:`Manufacturing · ${x.title}`})):[]}
export function manufacturingAcceptanceV55(state={},graph={},geo={},collisionReport={}){const bundle=buildManufacturingProfilesV55(state,graph,geo,collisionReport),issues=[];if(bundle.profiles.length!==3)issues.push(mk('error','V55_PROFILE_COUNT','Profile count','Safe / Machine / Manual profiles are required.'));for(const p of bundle.profiles){if(!Number.isFinite(p.score)||p.score<0||p.score>100)issues.push(mk('error','V55_SCORE_RANGE','Manufacturing score',`${p.profile.id} score must be within 0–100.`));if(!p.issues.length)issues.push(mk('error','V55_EMPTY_PROFILE','Manufacturing checks',`${p.profile.id} requires inspectable checks.`))}const safe=bundle.profiles.find(x=>x.profile.id==='safe'),manual=bundle.profiles.find(x=>x.profile.id==='manual');if(safe&&manual&&safe.thresholds.minGlueMm<manual.thresholds.minGlueMm)issues.push(mk('error','V55_PROFILE_ORDER','Profile strictness','Safe glue threshold cannot be looser than Manual.'));const errors=issues.filter(x=>x.severity==='error');return{schema:'boxstudio-v55-manufacturing-acceptance',version:1,ok:!errors.length,issues,errors,bundle,summary:{profiles:3,recommended:bundle.recommendedProfileId,material:bundle.context.material?.materialId||null,thickness:bundle.context.material?.thicknessMm||0,penetrations:bundle.context.penetrationCount,overlaps:bundle.context.overlapCount}}}
