const clone=v=>structuredClone(v);
const norm=v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' ');
const now=()=>new Date().toISOString();
function id(){return`map-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}

export function mappingHeaderSignatureV30(headers=[]){return(headers||[]).map(norm).join('\u001f');}
export function normalizeMappingV30(headers=[],mapping={}){const out={};for(const h of headers||[]){const value=String(mapping?.[h]||'').trim();if(value)out[h]=value;}return out;}
export function mappingProfilesV30(state){return(Array.isArray(state?.batchMappingProfiles)?state.batchMappingProfiles:[]).map(p=>({...p,mapping:{...(p?.mapping||{})}}));}
export function resolveMappingProfileV30(state,headers=[]){const sig=mappingHeaderSignatureV30(headers),profiles=mappingProfilesV30(state);return profiles.find(p=>p.headerSignature===sig)||null;}
export function saveMappingProfileV30(state,{label='Mapping Profile',headers=state?.batch?.columns||[],mapping=state?.batch?.mapping||{}}={}){const next=clone(state||{}),profiles=mappingProfilesV30(next),signature=mappingHeaderSignatureV30(headers),clean=normalizeMappingV30(headers,mapping),existing=profiles.find(p=>p.headerSignature===signature&&p.label===String(label||'Mapping Profile').trim());if(existing){existing.mapping=clean;existing.updatedAt=now();}else profiles.push({id:id(),label:String(label||'Mapping Profile').trim()||'Mapping Profile',headerSignature:signature,headers:[...(headers||[])],mapping:clean,createdAt:now(),updatedAt:now()});next.batchMappingProfiles=profiles;return{state:next,profile:existing||profiles.at(-1)};}
export function deleteMappingProfileV30(state,profileId){const next=clone(state||{});next.batchMappingProfiles=mappingProfilesV30(next).filter(p=>p.id!==profileId);if(next.batch?.mappingProfileId===profileId)next.batch={...(next.batch||{}),mappingProfileId:''};return next;}
export function applyMappingProfileV30(state,profileId,{requireExactHeaders=true}={}){const next=clone(state||{}),profile=mappingProfilesV30(next).find(p=>p.id===profileId);if(!profile)return next;const headers=next.batch?.columns||[],signature=mappingHeaderSignatureV30(headers);if(requireExactHeaders&&signature!==profile.headerSignature)throw new Error('Mapping Profile headers do not match the active sheet.');next.batch={...(next.batch||{}),mapping:{...profile.mapping},mappingProfileId:profile.id};return next;}
export function autoApplyMappingProfileV30(state){const current=state?.batch||{};if(current.mappingProfileId||!current.columns?.length)return{state:clone(state||{}),profile:null,applied:false};const profile=resolveMappingProfileV30(state,current.columns);if(!profile)return{state:clone(state||{}),profile:null,applied:false};return{state:applyMappingProfileV30(state,profile.id),profile,applied:true};}
