import { buildNativePdfV22Plan } from './nativePdfV22.js';
import { crossClipNodes, clipGeometryV25 } from './clipPathV25.js';
import { getRgbCmykDeviceLink, convertRgbToCmyk } from './iccDeviceLinkV23.js';
import { downloadBytes } from './export.js';

const PT=72/25.4;
const f=n=>(Number(n)||0).toFixed(4);
const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,num(v)));
function concatBytes(chunks){let total=0;for(const c of chunks)total+=c.length;const out=new Uint8Array(total);let at=0;for(const c of chunks){out.set(c,at);at+=c.length;}return out;}
function path(points,pageH){if(!points?.length)return'';let s=`${f(points[0][0]*PT)} ${f((pageH-points[0][1])*PT)} m`;for(let i=1;i<points.length;i++)s+=` ${f(points[i][0]*PT)} ${f((pageH-points[i][1])*PT)} l`;return s+' h';}
function polygonClipCmd(polys,pageH){return(polys||[]).length?polys.map(p=>path(p,pageH)).join(' ')+' W n':'';}
function cubicClipPath(nodes,pageH){if(!nodes?.length)return'';let s=`${f(nodes[0].anchor[0]*PT)} ${f((pageH-nodes[0].anchor[1])*PT)} m`;for(let i=0;i<nodes.length;i++){const a=nodes[i],b=nodes[(i+1)%nodes.length];if(a.outActive||b.inActive)s+=` ${f(a.outPoint[0]*PT)} ${f((pageH-a.outPoint[1])*PT)} ${f(b.inPoint[0]*PT)} ${f((pageH-b.inPoint[1])*PT)} ${f(b.anchor[0]*PT)} ${f((pageH-b.anchor[1])*PT)} c`;else s+=` ${f(b.anchor[0]*PT)} ${f((pageH-b.anchor[1])*PT)} l`;}return s+' h W n';}
function nativeClipForOp(state,op,pageH){const src=(state?.elements||[]).find(e=>e.id===op.source),nodes=src?crossClipNodes(src):[];if(src?.type!=='cross-panel-artwork'||nodes.length<3)return{polygonCmd:polygonClipCmd(op.clips,pageH),cubicCmd:'',native:false};const geo=clipGeometryV25(src,{stepsPerCurve:12});const polys=(op.clips||[]).slice(0,-1);return{polygonCmd:polygonClipCmd(polys,pageH),cubicCmd:cubicClipPath(geo.nodes,pageH),native:true};}
function varyingStopAlpha(stops=[]){if(!stops.length)return false;const a=stops.map(s=>clamp(s.opacity));return Math.max(...a)-Math.min(...a)>1e-6;}
function colorValues(rgb,useCmyk){if(useCmyk){const c=convertRgbToCmyk(rgb);if(!c)throw new Error('DeviceLink unavailable during native cubic proof generation.');return c.map(x=>clamp(x));}return(rgb||[0,0,0]).map(x=>clamp(x));}
function values(v){return(v||[]).map(x=>f(x)).join(' ');}
function makeFunction(stops,add,useCmyk){const seg=[];for(let i=0;i<stops.length-1;i++){const a=colorValues(stops[i].color,useCmyk),b=colorValues(stops[i+1].color,useCmyk);seg.push(add(`<< /FunctionType 2 /Domain [0 1] /C0 [${values(a)}] /C1 [${values(b)}] /N 1 >>`));}if(seg.length===1)return seg[0];const bounds=stops.slice(1,-1).map(s=>f(s.offset)).join(' '),encode=seg.map(()=>'0 1').join(' ');return add(`<< /FunctionType 3 /Domain [0 1] /Functions [${seg.map(id=>`${id} 0 R`).join(' ')}] /Bounds [${bounds}] /Encode [${encode}] >>`);}
function makeAlphaFunction(stops,opacity,add){const seg=[];for(let i=0;i<stops.length-1;i++){const a=clamp(stops[i].opacity*opacity),b=clamp(stops[i+1].opacity*opacity);seg.push(add(`<< /FunctionType 2 /Domain [0 1] /C0 [${f(a)}] /C1 [${f(b)}] /N 1 >>`));}if(seg.length===1)return seg[0];const bounds=stops.slice(1,-1).map(s=>f(s.offset)).join(' '),encode=seg.map(()=>'0 1').join(' ');return add(`<< /FunctionType 3 /Domain [0 1] /Functions [${seg.map(id=>`${id} 0 R`).join(' ')}] /Bounds [${bounds}] /Encode [${encode}] >>`);}
function shadingDictionary(g,functionId,pageH,colorSpace){const c=g.coords.map((v,i)=>i%2===1?((pageH-v)*PT):(v*PT)),type=g.type==='radial'?3:2;return`<< /ShadingType ${type} /ColorSpace ${colorSpace} /Coords [${c.map(f).join(' ')}] /Function ${functionId} 0 R /Extend [true true] >>`;}
function panelPolygon(panel){if(Array.isArray(panel?.points)&&panel.points.length>=3)return panel.points.map(p=>[num(p[0]),num(p[1])]);const x=num(panel?.x),y=num(panel?.y),w=num(panel?.w),h=num(panel?.h);return[[x,y],[x+w,y],[x+w,y+h],[x,y+h]];}
function clipSequence(state,op,pageH){const c=nativeClipForOp(state,op,pageH);return[c.polygonCmd,c.cubicCmd,path(op.points,pageH)+' W n'].filter(Boolean);}

export function buildNativeCubicClipPdfV26(state,{includePanelOutline=true}={}){
  const plan=buildNativePdfV22Plan(state),pageH=plan.geo.height,pageW=plan.geo.width,useCmyk=Boolean(getRgbCmykDeviceLink()),colorSpace=useCmyk?'/DeviceCMYK':'/DeviceRGB',enc=new TextEncoder(),objects=[null],add=body=>{objects.push(body);return objects.length-1},alphaRefs=new Map(),softMasks=[],shadings=[],entries=[];
  const alphaName=opacity=>{const a=clamp(opacity);if(a>=.999)return null;const key=a.toFixed(4);if(!alphaRefs.has(key))alphaRefs.set(key,{name:`GS${alphaRefs.size+1}`,id:add(`<< /Type /ExtGState /ca ${f(a)} /CA ${f(a)} >>`)});return alphaRefs.get(key).name;};
  for(const op of plan.ops||[]){if(op.kind==='gradient'){const fn=makeFunction(op.gradient.stops,add,useCmyk),sid=add(shadingDictionary(op.gradient,fn,pageH,colorSpace)),entry={op,name:`Sh${shadings.length+1}`,sid,gs:null};if(varyingStopAlpha(op.gradient.stops)){const af=makeAlphaFunction(op.gradient.stops,clamp(op.opacity),add),asid=add(shadingDictionary(op.gradient,af,pageH,'/DeviceGray')),maskName=`MS${softMasks.length+1}`,maskContent=['q',...clipSequence(state,op,pageH),`/${maskName} sh`,'Q'].join('\n')+'\n',formId=add(`<< /Type /XObject /Subtype /Form /BBox [0 0 ${f(pageW*PT)} ${f(pageH*PT)}] /Group << /S /Transparency /CS /DeviceGray >> /Resources << /Shading << /${maskName} ${asid} 0 R >> >> /Length ${enc.encode(maskContent).length} >>\nstream\n${maskContent}endstream`),gsName=`SM${softMasks.length+1}`,gsId=add(`<< /Type /ExtGState /SMask << /S /Luminosity /G ${formId} 0 R >> >>`);entry.gs=gsName;softMasks.push({name:gsName,id:gsId});}else entry.gs=alphaName(op.opacity);shadings.push(entry);entries.push(entry);}else entries.push({op,gs:alphaName(op.opacity)});}
  const cmds=['q','1 1 1 rg',`0 0 ${f(pageW*PT)} ${f(pageH*PT)} re f`,'Q'];let gi=0;for(const entry of entries){const op=entry.op;cmds.push('q',...clipSequence(state,op,pageH));if(entry.gs)cmds.push(`/${entry.gs} gs`);if(op.kind==='gradient'){const sh=shadings[gi++];cmds.push(`/${sh.name} sh`);}else{const c=colorValues(op.color,useCmyk);cmds.push(`${values(c)} ${useCmyk?'k':'rg'}`,`0 0 ${f(pageW*PT)} ${f(pageH*PT)} re f`);}cmds.push('Q');}
  if(includePanelOutline){cmds.push('q','0.68 0.68 0.68 RG','0.32 w');for(const p of Object.values(plan.geo.panelMap||{})){if(!p||num(p.w)<=0||num(p.h)<=0)continue;cmds.push(path(panelPolygon(p),pageH),'S');}cmds.push('Q');}
  const content=cmds.join('\n')+'\n',contentId=add(`<< /Length ${enc.encode(content).length} >>\nstream\n${content}endstream`),pagesId=add(''),pageId=add(''),catalogId=add(''),infoId=add(''),shadeRes=shadings.map(x=>`/${x.name} ${x.sid} 0 R`).join(' '),gsRes=[...alphaRefs.values(),...softMasks].map(x=>`/${x.name} ${x.id} 0 R`).join(' ');
  objects[pagesId]=`<< /Type /Pages /Kids [${pageId} 0 R] /Count 1 >>`;objects[pageId]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${f(pageW*PT)} ${f(pageH*PT)}] /Resources << /Shading << ${shadeRes} >> /ExtGState << ${gsRes} >> >> /Contents ${contentId} 0 R >>`;objects[catalogId]=`<< /Type /Catalog /Pages ${pagesId} 0 R >>`;objects[infoId]='<< /Producer (BoxStudio V0.26 Native Cubic Clip Proof) /Creator (BoxStudio) /Title (Native Cubic Cross-panel Clip Proof) >>';
  const chunks=[enc.encode('%PDF-1.7\n%BoxStudio V0.26 Native Cubic Clip Proof\n')],offsets=new Array(objects.length).fill(0);let pos=chunks[0].length;for(let i=1;i<objects.length;i++){offsets[i]=pos;const body=enc.encode(`${i} 0 obj\n${objects[i]}\nendobj\n`);chunks.push(body);pos+=body.length;}const xref=pos;let tail=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)tail+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;tail+=`trailer\n<< /Size ${objects.length} /Root ${catalogId} 0 R /Info ${infoId} 0 R >>\nstartxref\n${xref}\n%%EOF\n`;chunks.push(enc.encode(tail));return concatBytes(chunks);
}
export function nativeCubicClipPdfDiagnosticsV26(state){const plan=buildNativePdfV22Plan(state),items=(state?.elements||[]).filter(e=>e?.type==='cross-panel-artwork'&&crossClipNodes(e).length>=3),curved=items.filter(e=>crossClipNodes(e).some((n,i,arr)=>Math.hypot(...n.out)>1e-9||Math.hypot(...arr[(i+1)%arr.length].in)>1e-9));return{objects:plan.stats.objects,nativeClipObjects:items.length,curvedClipObjects:curved.length,colorSpace:getRgbCmykDeviceLink()?'DeviceCMYK':'DeviceRGB'};}
export function exportNativeCubicClipPdfV26(state){downloadBytes('boxstudio-v0.26-native-cubic-clip-proof.pdf',buildNativeCubicClipPdfV26(state),'application/pdf');}
