import { renderTemplate, isPackageNoticeVisible } from './variables.js';
import { barcodeLayout } from './barcode.js';
import { qrMatrix } from './qrcode.js';

function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function rotate(x,y,cx,cy,deg=0){const a=num(deg)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),dx=x-cx,dy=y-cy;return[cx+dx*c-dy*s,cy+dx*s+dy*c]}
function panelRect(panel){return{x:num(panel?.x),y:num(panel?.y),w:Math.max(.001,num(panel?.w,1)),h:Math.max(.001,num(panel?.h,1)),points:Array.isArray(panel?.points)?panel.points:null}}
function visibleElement(el,state){return !(el?.type==='notice'&&!isPackageNoticeVisible(state.variables||{}));}
function pushSvg(commands,el){const mark=el.svgMark;if(!mark?.lines?.length)return;const sx=num(el.w,mark.width)/Math.max(.001,num(mark.width,1)),sy=num(el.h,mark.height)/Math.max(.001,num(mark.height,1)),cx=num(el.x)+num(el.w)/2,cy=num(el.y)+num(el.h)/2;for(const l of mark.lines){const a=rotate(num(el.x)+num(l.x1)*sx,num(el.y)+num(l.y1)*sy,cx,cy,el.r),b=rotate(num(el.x)+num(l.x2)*sx,num(el.y)+num(l.y2)*sy,cx,cy,el.r);commands.push({type:'line',x1:a[0],y1:a[1],x2:b[0],y2:b[1],source:el.id});}}
function pushBarcode(commands,el,state){const pad=Math.max(1,Math.min(5,num(el.h)*.08)),gap=Math.max(1,Math.min(7,num(el.w)*.03)),qrSide=Math.max(8,Math.min(num(el.h)-pad*2,num(el.w)*.30)),bw=Math.max(10,num(el.w)-pad*2-gap-qrSide),bh=Math.max(8,num(el.h)-pad*2-5),value=renderTemplate(el.barcodeValue,state.variables||{}),layout=barcodeLayout(el.barcodeType||'CODE39',value,bw,bh),ox=num(el.x)+pad,oy=num(el.y)+pad;commands.push({type:'rect',x:num(el.x),y:num(el.y),w:num(el.w),h:num(el.h),fill:false,source:el.id});for(const bar of layout.bars)commands.push({type:'rect',x:ox+bar.x,y:oy+bar.y,w:bar.w,h:bar.h,fill:true,source:el.id});const qr=qrMatrix(renderTemplate(el.qrValue,state.variables||{})),quiet=4,modules=qr.size+quiet*2,cell=qrSide/modules,qx=num(el.x)+num(el.w)-pad-qrSide,qy=num(el.y)+pad;for(let r=0;r<qr.size;r++)for(let c=0;c<qr.size;c++)if(qr.matrix[r][c])commands.push({type:'rect',x:qx+(quiet+c)*cell,y:qy+(quiet+r)*cell,w:cell+.001,h:cell+.001,fill:true,source:el.id});}

export function buildPanelArtworkPlan(state,geo,panelId){
  const panel=panelRect(geo?.panelMap?.[panelId]);if(!geo?.panelMap?.[panelId])throw new Error(`Panel not found: ${panelId}`);const commands=[],elements=(state?.elements||[]).filter(el=>el?.panelId===panelId&&visibleElement(el,state));
  for(const el of elements){const x=num(el.x),y=num(el.y),w=num(el.w),h=num(el.h),r=num(el.r);if(el.type==='text'||el.type==='notice')commands.push({type:'text',x,y,w,h,r,text:renderTemplate(el.template,state.variables||{}),fontSize:num(el.fontSize,6),bold:Boolean(el.bold),source:el.id});else if(el.type==='line'){const a=rotate(x,y,x+w/2,y+h/2,r),b=rotate(x+w,y+h,x+w/2,y+h/2,r);commands.push({type:'line',x1:a[0],y1:a[1],x2:b[0],y2:b[1],source:el.id});}else if(el.type==='shape')commands.push({type:'rect',x,y,w,h,r,fill:false,source:el.id});else if(el.type==='icon')commands.push({type:'icon',x,y,w,h,r,icon:el.icon||'mark',source:el.id});else if(el.type==='barcode-qr-group')pushBarcode(commands,el,state);else if(el.type==='svg-symbol')pushSvg(commands,el);}
  return{panelId,label:geo.panelMap[panelId]?.label||panelId,width:panel.w,height:panel.h,points:panel.points,elements:elements.length,commands};
}

export function artworkPlanBounds(plan){const bad=[];for(const c of plan?.commands||[]){let minX=0,minY=0,maxX=0,maxY=0;if(c.type==='line'){minX=Math.min(c.x1,c.x2);maxX=Math.max(c.x1,c.x2);minY=Math.min(c.y1,c.y2);maxY=Math.max(c.y1,c.y2);}else{minX=num(c.x);minY=num(c.y);maxX=minX+Math.max(0,num(c.w));maxY=minY+Math.max(0,num(c.h));}if(minX<-.01||minY<-.01||maxX>num(plan.width)+.01||maxY>num(plan.height)+.01)bad.push({source:c.source||'',minX,minY,maxX,maxY});}return{ok:bad.length===0,outside:bad};}

export function buildArtworkAtlas(state,geo){const plans=[];for(const [id,panel] of Object.entries(geo?.panelMap||{})){if(!panel||num(panel.w)<=0||num(panel.h)<=0)continue;plans.push(buildPanelArtworkPlan(state,geo,id));}return{plans,panelCount:plans.length,elementCount:plans.reduce((n,p)=>n+p.elements,0),commandCount:plans.reduce((n,p)=>n+p.commands.length,0),outside:plans.flatMap(p=>artworkPlanBounds(p).outside.map(x=>({...x,panelId:p.panelId})))};}

export function renderPanelArtworkCanvas(plan,{maxPixels=900,background='#d8c2a0',ink='#171717'}={}){
  if(typeof document==='undefined')throw new Error('Canvas rendering requires a browser document.');const ratio=Math.max(.15,Math.min(6,num(plan.width)/Math.max(.001,num(plan.height)))),canvas=document.createElement('canvas');canvas.width=ratio>=1?maxPixels:Math.max(80,Math.round(maxPixels*ratio));canvas.height=ratio>=1?Math.max(80,Math.round(maxPixels/ratio)):maxPixels;const ctx=canvas.getContext('2d'),sx=canvas.width/plan.width,sy=canvas.height/plan.height,scale=Math.min(sx,sy);ctx.fillStyle=background;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle=ink;ctx.fillStyle=ink;ctx.lineWidth=Math.max(1,scale*.35);
  const withRotation=(c,fn)=>{ctx.save();if(c.r){const cx=(c.x+c.w/2)*sx,cy=(c.y+c.h/2)*sy;ctx.translate(cx,cy);ctx.rotate(c.r*Math.PI/180);ctx.translate(-cx,-cy);}fn();ctx.restore();};
  for(const c of plan.commands){if(c.type==='line'){ctx.beginPath();ctx.moveTo(c.x1*sx,c.y1*sy);ctx.lineTo(c.x2*sx,c.y2*sy);ctx.stroke();}else if(c.type==='rect')withRotation(c,()=>{if(c.fill)ctx.fillRect(c.x*sx,c.y*sy,c.w*sx,c.h*sy);else ctx.strokeRect(c.x*sx,c.y*sy,c.w*sx,c.h*sy);});else if(c.type==='text')withRotation(c,()=>{const fs=Math.max(7,c.fontSize*scale);ctx.font=`${c.bold?'700':'500'} ${fs}px Arial`;ctx.textBaseline='top';ctx.fillStyle=ink;String(c.text).split('\n').forEach((line,i)=>ctx.fillText(line,c.x*sx,(c.y*s y??0)));});else if(c.type==='icon')withRotation(c,()=>{ctx.strokeRect(c.x*sx,c.y*sy,c.w*sx,c.h*sy);ctx.font=`700 ${Math.max(9,c.h*sy*.48)}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(c.icon==='up'?'↑↑':c.icon==='fragile'?'Y':'☂',(c.x+c.w/2)*sx,(c.y+c.h/2)*sy);});}
  ctx.strokeStyle='rgba(60,45,30,.65)';ctx.lineWidth=2;ctx.strokeRect(1,1,canvas.width-2,canvas.height-2);return canvas;
}
