import {paintPatternV76} from './patternLibraryV76.js';
import {paintArtworkV74} from './artworkLibraryV74.js';
import {paintFontV74} from './fontSystemV74.js';
import {paintHandlingV72,handlingParamsV72} from './handlingSymbolsV72.js';
import {barcodeGroupLayoutV70} from './barcodeGroupV70.js';
import { renderTemplate, isPackageNoticeVisible } from './variables.js';
import { barcodeLayout } from './barcode.js';
import { qrMatrix } from './qrcode.js';
import { materializeCrossPanelArtworkElement } from './crossPanelArtwork.js';
import { orderedElements } from './objectOrder.js';

function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function rotate(x,y,cx,cy,deg=0){const a=num(deg)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),dx=x-cx,dy=y-cy;return[cx+dx*c-dy*s,cy+dx*s+dy*c]}
function panelRect(panel){return{x:num(panel?.x),y:num(panel?.y),w:Math.max(.001,num(panel?.w,1)),h:Math.max(.001,num(panel?.h,1)),points:Array.isArray(panel?.points)?panel.points:null}}
function visibleElement(el,state){return el?.hidden!==true && !(el?.type==='notice'&&!isPackageNoticeVisible(state.variables||{}));}
function pushSvg(commands,el){const mark=el.svgMark;if(!mark?.lines?.length)return;const sx=num(el.w,mark.width)/Math.max(.001,num(mark.width,1)),sy=num(el.h,mark.height)/Math.max(.001,num(mark.height,1)),cx=num(el.x)+num(el.w)/2,cy=num(el.y)+num(el.h)/2;if(mark.appearance?.hasPaintedFill)commands.push({type:'svg-appearance',x:num(el.x),y:num(el.y),w:num(el.w),h:num(el.h),r:num(el.r),markWidth:num(mark.width,1),markHeight:num(mark.height,1),appearance:structuredClone(mark.appearance),source:el.id,zIndex:num(el.zIndex)});for(const l of mark.lines){const a=rotate(num(el.x)+num(l.x1)*sx,num(el.y)+num(l.y1)*sy,cx,cy,el.r),b=rotate(num(el.x)+num(l.x2)*sx,num(el.y)+num(l.y2)*sy,cx,cy,el.r);commands.push({type:'line',x1:a[0],y1:a[1],x2:b[0],y2:b[1],source:el.id,zIndex:num(el.zIndex)});}}
function pushBarcode(commands,el,state){const {pad,qrSide,bw,bh}=barcodeGroupLayoutV70(el),value=renderTemplate(el.barcodeValue,state.variables||{}),layout=barcodeLayout(el.barcodeType||'CODE39',value,bw,bh),ox=num(el.x)+pad,oy=num(el.y)+pad,zIndex=num(el.zIndex);commands.push({type:'rect',x:num(el.x),y:num(el.y),w:num(el.w),h:num(el.h),fill:true,fillColor:'#ffffff',source:el.id,zIndex});commands.push({type:'rect',x:num(el.x),y:num(el.y),w:num(el.w),h:num(el.h),fill:false,source:el.id,zIndex});for(const bar of layout.bars)commands.push({type:'rect',x:ox+bar.x,y:oy+bar.y,w:bar.w,h:bar.h,fill:true,source:el.id,zIndex});const qr=qrMatrix(renderTemplate(el.qrValue,state.variables||{})),quiet=4,modules=qr.size+quiet*2,cell=qrSide/modules,qx=num(el.x)+num(el.w)-pad-qrSide,qy=num(el.y)+pad;for(let r=0;r<qr.size;r++)for(let c=0;c<qr.size;c++)if(qr.matrix[r][c])commands.push({type:'rect',x:qx+(quiet+c)*cell,y:qy+(quiet+r)*cell,w:cell+.001,h:cell+.001,fill:true,source:el.id,zIndex});}
function panelElements(state,geo,panelId){const local=(state?.elements||[]).filter(el=>el?.type!=='cross-panel-artwork'&&el?.panelId===panelId),virtual=[];for(const el of state?.elements||[])if(el?.type==='cross-panel-artwork')virtual.push(...materializeCrossPanelArtworkElement(el,geo,{gradientDepth:2}).filter(x=>x.panelId===panelId));return orderedElements([...local,...virtual]).filter(el=>visibleElement(el,state));}

export function buildPanelArtworkPlan(state,geo,panelId){
  const panel=panelRect(geo?.panelMap?.[panelId]);if(!geo?.panelMap?.[panelId])throw new Error(`Panel not found: ${panelId}`);const commands=[],elements=panelElements(state,geo,panelId);
  for(const el of elements){const x=num(el.x),y=num(el.y),w=num(el.w),h=num(el.h),r=num(el.r),zIndex=num(el.zIndex);if(el.type==='text'||el.type==='notice')commands.push({type:'text',x,y,w,h,r,text:renderTemplate(el.template,state.variables||{}),fontSize:num(el.fontSize,6),bold:Boolean(el.bold),fontIdV74:el.fontIdV74,textStyleV76:el.textStyleV76?structuredClone(el.textStyleV76):undefined,source:el.id,zIndex});else if(el.type==='image')commands.push({type:'image',x,y,w,h,r,src:String(el.src||''),name:String(el.name||'artwork-image'),mime:String(el.mime||''),pixelWidth:num(el.pixelWidth),pixelHeight:num(el.pixelHeight),fit:['contain','cover','stretch'].includes(el.fit)?el.fit:'contain',opacity:Math.max(0,Math.min(1,num(el.opacity,1))),source:el.id,zIndex});else if(el.type==='line'){const a=rotate(x,y,x+w/2,y+h/2,r),b=rotate(x+w,y+h,x+w/2,y+h/2,r);commands.push({type:'line',x1:a[0],y1:a[1],x2:b[0],y2:b[1],source:el.id,zIndex});}else if(el.patternIdV76)commands.push({...structuredClone(el),type:'pattern',source:el.id,zIndex});else if(el.assetIdV74)commands.push({type:'asset',x,y,w,h,r,assetIdV74:el.assetIdV74,fillColor:el.fillColor,source:el.id,zIndex});else if(el.type==='shape')commands.push({type:'rect',x,y,w,h,r,fill:false,source:el.id,zIndex});else if(el.type==='production-polygon')commands.push({type:'polygon',points:(el.points||[]).map(p=>[num(p[0]),num(p[1])]),fill:true,fillColor:el.fillColor||'#000',source:el.id,zIndex,crossPanelSourceId:el.crossPanelSourceId||null});else if(el.type==='icon')commands.push({type:'icon',x,y,w,h,r,icon:el.icon||'up',...handlingParamsV72({...el,icon:el.icon||'up'}),source:el.id,zIndex});else if(el.type==='barcode-qr-group')pushBarcode(commands,el,state);else if(el.type==='svg-symbol')pushSvg(commands,el);}
  commands.sort((a,b)=>num(a.zIndex)-num(b.zIndex));return{panelId,label:geo.panelMap[panelId]?.label||panelId,width:panel.w,height:panel.h,points:panel.points,elements:elements.length,commands,crossPanelFragments:elements.filter(e=>e.crossPanelSourceId).length};
}

export function artworkPlanBounds(plan){const bad=[];for(const c of plan?.commands||[]){let minX=0,minY=0,maxX=0,maxY=0;if(c.type==='line'){minX=Math.min(c.x1,c.x2);maxX=Math.max(c.x1,c.x2);minY=Math.min(c.y1,c.y2);maxY=Math.max(c.y1,c.y2);}else if(c.type==='polygon'){const xs=(c.points||[]).map(p=>p[0]),ys=(c.points||[]).map(p=>p[1]);if(!xs.length)continue;minX=Math.min(...xs);maxX=Math.max(...xs);minY=Math.min(...ys);maxY=Math.max(...ys);}else{minX=num(c.x);minY=num(c.y);maxX=minX+Math.max(0,num(c.w));maxY=minY+Math.max(0,num(c.h));}if(minX<-.01||minY<-.01||maxX>num(plan.width)+.01||maxY>num(plan.height)+.01)bad.push({source:c.source||'',minX,minY,maxX,maxY});}return{ok:bad.length===0,outside:bad};}

export function buildArtworkAtlas(state,geo){const plans=[];for(const [id,panel] of Object.entries(geo?.panelMap||{})){if(!panel||num(panel.w)<=0||num(panel.h)<=0)continue;plans.push(buildPanelArtworkPlan(state,geo,id));}return{plans,panelCount:plans.length,elementCount:plans.reduce((n,p)=>n+p.elements,0),commandCount:plans.reduce((n,p)=>n+p.commands.length,0),imageCommands:plans.reduce((n,p)=>n+p.commands.filter(c=>c.type==='image').length,0),appearanceCommands:plans.reduce((n,p)=>n+p.commands.filter(c=>c.type==='svg-appearance').length,0),crossPanelFragments:plans.reduce((n,p)=>n+p.crossPanelFragments,0),outside:plans.flatMap(p=>artworkPlanBounds(p).outside.map(x=>({...x,panelId:p.panelId})))};}

function alphaColor(color,alpha=1){const a=Math.max(0,Math.min(1,num(alpha,1))),s=String(color||'#000').trim();if(a>=.999)return s;let m=s.match(/^#([0-9a-f]{6})$/i);if(m){const n=parseInt(m[1],16);return`rgba(${n>>16},${(n>>8)&255},${n&255},${a})`}m=s.match(/^#([0-9a-f]{3})$/i);if(m){const h=m[1],r=parseInt(h[0]+h[0],16),g=parseInt(h[1]+h[1],16),b=parseInt(h[2]+h[2],16);return`rgba(${r},${g},${b},${a})`}m=s.match(/^rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/i);if(m)return`rgba(${m[1]},${m[2]},${m[3]},${a})`;return s}
function coord(v,min,size,sourceSize,elementSize){const s=String(v??'0').trim();if(s.endsWith('%'))return min+num(s.slice(0,-1))/100*size;return min+(num(s)/Math.max(.001,sourceSize))*elementSize}
function pathPolygons(ctx,polys,c,sx,sy){for(const poly of polys||[]){if(poly.length<3)continue;poly.forEach(([px,py],i)=>{const x=(c.x+px/c.markWidth*c.w)*sx,y=(c.y+py/c.markHeight*c.h)*sy;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath()}}
function primitivePixelPoints(p,c,sx,sy){return(p.points||[]).map(([px,py])=>[(c.x+px/c.markWidth*c.w)*sx,(c.y+py/c.markHeight*c.h)*sy])}
function applyClipOrMask(ctx,appearance,id,kind,c,sx,sy){if(!id)return;const map=kind==='clip'?appearance.clips:appearance.masks,polys=map?.[id];if(!polys?.length)return;ctx.beginPath();pathPolygons(ctx,polys,c,sx,sy);ctx.clip('nonzero')}
function gradientFor(ctx,g,pixelBounds,c,sx,sy){if(!g)return'#000';const w=Math.max(.001,pixelBounds.maxX-pixelBounds.minX),h=Math.max(.001,pixelBounds.maxY-pixelBounds.minY),objectBox=String(g.units||'').toLowerCase()!=='userspaceonuse';let grad;if(g.type==='radial'){const cx=objectBox?coord(g.cx,pixelBounds.minX,w,1,w):coord(g.cx,c.x*sx,c.w*sx,c.markWidth,c.w*sx),cy=objectBox?coord(g.cy,pixelBounds.minY,h,1,h):coord(g.cy,c.y*sy,c.h*sy,c.markHeight,c.h*sy),r=objectBox?Math.abs(coord(g.r,0,Math.max(w,h),1,Math.max(w,h))):Math.abs(num(g.r)*Math.min(c.w*sx/c.markWidth,c.h*sy/c.markHeight));grad=ctx.createRadialGradient(cx,cy,0,cx,cy,Math.max(1,r))}else{const x1=objectBox?coord(g.x1,pixelBounds.minX,w,1,w):coord(g.x1,c.x*sx,c.w*sx,c.markWidth,c.w*sx),y1=objectBox?coord(g.y1,pixelBounds.minY,h,1,h):coord(g.y1,c.y*sy,c.h*sy,c.markHeight,c.h*sy),x2=objectBox?coord(g.x2,pixelBounds.minX,w,1,w):coord(g.x2,c.x*sx,c.w*sx,c.markWidth,c.w*sx),y2=objectBox?coord(g.y2,pixelBounds.minY,h,1,h):coord(g.y2,c.y*sy,c.h*sy,c.markHeight,c.h*sy);grad=ctx.createLinearGradient(x1,y1,x2,y2)}for(const stop of g.stops||[])grad.addColorStop(Math.max(0,Math.min(1,num(stop.offset))),alphaColor(stop.color,stop.opacity));return grad}
function renderSvgAppearance(ctx,c,sx,sy){const appearance=c.appearance;if(!appearance?.primitives?.length)return;ctx.save();if(c.r){const cx=(c.x+c.w/2)*sx,cy=(c.y+c.h/2)*sy;ctx.translate(cx,cy);ctx.rotate(c.r*Math.PI/180);ctx.translate(-cx,-cy)}for(const p of appearance.primitives){const pts=primitivePixelPoints(p,c,sx,sy);if(pts.length<3)continue;ctx.save();applyClipOrMask(ctx,appearance,p.clipId,'clip',c,sx,sy);applyClipOrMask(ctx,appearance,p.maskId,'mask',c,sx,sy);ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();const xs=pts.map(q=>q[0]),ys=pts.map(q=>q[1]),bb={minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};ctx.globalAlpha=Math.max(0,Math.min(1,num(p.opacity,1)));if(p.fill?.type==='gradient')ctx.fillStyle=gradientFor(ctx,appearance.gradients?.[p.fill.id],bb,c,sx,sy);else ctx.fillStyle=String(p.fill?.color||'#000');ctx.fill('nonzero');ctx.restore()}ctx.restore()}
function renderPolygon(ctx,c,sx,sy){if(!c.points?.length)return;ctx.save();ctx.beginPath();c.points.forEach(([x,y],i)=>i?ctx.lineTo(x*sx,y*sy):ctx.moveTo(x*sx,y*sy));ctx.closePath();ctx.fillStyle=c.fillColor||'#000';ctx.fill();ctx.restore()}

const rasterCache=new Map();
function rasterRecord(src,onReady){if(!src||typeof Image==='undefined')return null;let rec=rasterCache.get(src);if(!rec){const img=new Image();rec={img,ready:false,error:false,listeners:new Set()};rasterCache.set(src,rec);img.onload=()=>{rec.ready=true;for(const fn of rec.listeners){try{fn()}catch{}}rec.listeners.clear()};img.onerror=()=>{rec.error=true;rec.listeners.clear()};img.src=src}if(onReady&&!rec.ready&&!rec.error)rec.listeners.add(onReady);return rec}
function drawRaster(ctx,c,img,sx,sy){const x=c.x*sx,y=c.y*sy,w=c.w*sx,h=c.h*sy,iw=Math.max(1,img.naturalWidth||img.width),ih=Math.max(1,img.naturalHeight||img.height),fit=c.fit||'contain';ctx.save();const cx=x+w/2,cy=y+h/2;if(c.r){ctx.translate(cx,cy);ctx.rotate(c.r*Math.PI/180);ctx.translate(-cx,-cy)}ctx.globalAlpha=Math.max(0,Math.min(1,num(c.opacity,1)));ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();if(fit==='stretch')ctx.drawImage(img,x,y,w,h);else{const scale=fit==='cover'?Math.max(w/iw,h/ih):Math.min(w/iw,h/ih),dw=iw*scale,dh=ih*scale;ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}ctx.restore()}

export function renderPanelArtworkCanvas(plan,{maxPixels=900,background='#d8c2a0',ink='#171717',onUpdate=null}={}){
  if(typeof document==='undefined')throw new Error('Canvas rendering requires a browser document.');const ratio=Math.max(.15,Math.min(6,num(plan.width)/Math.max(.001,num(plan.height)))),canvas=document.createElement('canvas');canvas.width=ratio>=1?maxPixels:Math.max(80,Math.round(maxPixels*ratio));canvas.height=ratio>=1?Math.max(80,Math.round(maxPixels/ratio)):maxPixels;const ctx=canvas.getContext('2d'),sx=canvas.width/plan.width,sy=canvas.height/plan.height,scale=Math.min(sx,sy);let redrawing=false;
  const withRotation=(c,fn)=>{ctx.save();if(c.r){const cx=(c.x+c.w/2)*sx,cy=(c.y+c.h/2)*sy;ctx.translate(cx,cy);ctx.rotate(c.r*Math.PI/180);ctx.translate(-cx,-cy);}fn();ctx.restore();};
  const draw=()=>{if(redrawing)return;redrawing=true;ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle=background;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle=ink;ctx.fillStyle=ink;ctx.lineWidth=Math.max(1,scale*.35);for(const c of plan.commands){if(c.type==='svg-appearance')renderSvgAppearance(ctx,c,sx,sy);else if(c.type==='polygon')renderPolygon(ctx,c,sx,sy);else if(c.type==='image'){const rec=rasterRecord(c.src,()=>{draw();onUpdate?.(canvas)});if(rec?.ready)drawRaster(ctx,c,rec.img,sx,sy)}else if(c.type==='line'){ctx.beginPath();ctx.moveTo(c.x1*sx,c.y1*sy);ctx.lineTo(c.x2*sx,c.y2*sy);ctx.stroke();}else if(c.type==='pattern')withRotation(c,()=>paintPatternV76(ctx,c,sx,sy));else if(c.type==='asset')withRotation(c,()=>paintArtworkV74(ctx,c,sx,sy));else if(c.type==='rect')withRotation(c,()=>{if(c.fill){ctx.fillStyle=c.fillColor||ink;ctx.fillRect(c.x*sx,c.y*sy,c.w*sx,c.h*sy);}else ctx.strokeRect(c.x*sx,c.y*sy,c.w*sx,c.h*sy);});else if(c.type==='text')withRotation(c,()=>{if(paintFontV74(ctx,c,c.text,c.x+4,c.y+1,scale))return;const fs=Math.max(7,c.fontSize*scale);ctx.font=`${c.bold?'700':'500'} ${fs}px Arial`;ctx.textBaseline='top';ctx.fillStyle=ink;String(c.text).split('\n').forEach((line,i)=>ctx.fillText(line,c.x*sx,c.y*sy+i*fs*1.12,Math.max(4,c.w*sx)));});else if(c.type==='icon')withRotation(c,()=>{paintHandlingV72(ctx,c,sx,sy);});}ctx.globalAlpha=1;ctx.strokeStyle='rgba(60,45,30,.65)';ctx.lineWidth=2;ctx.strokeRect(1,1,canvas.width-2,canvas.height-2);redrawing=false};draw();return canvas;
}
