import {renderPanelArtworkCanvas} from './panelArtwork.js';
import {prepareFontsV74} from './fontSystemV74.js';
import {loadPhysicalStudioV74,physicalStudioReadyV74,renderPhysicalStudioV74} from './studioLightingV74.js';
import {sceneSettingsV71} from './scene3dV71.js';
import {paperAppearanceV77} from './paperMaterialsV77.js';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
const apply=(m,q)=>[m[0]*q[0]+m[1]*q[1]+m[2]*q[2]+m[3],m[4]*q[0]+m[5]*q[1]+m[6]*q[2]+m[7],m[8]*q[0]+m[9]*q[1]+m[10]*q[2]+m[11]];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const hit=(p,points)=>{let yes=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;};
const area=p=>p.reduce((s,a,i)=>{const b=p[(i+1)%p.length];return s+a[0]*b[1]-b[0]*a[1];},0);
function triangle(ctx,image,src,dst){const[a,b,c]=src,[A,B,C]=dst,dx=b[0]-a[0],dy=b[1]-a[1],ex=c[0]-a[0],ey=c[1]-a[1],det=dx*ey-dy*ex;if(Math.abs(det)<1e-8)return;const x=((B[0]-A[0])*ey-(C[0]-A[0])*dy)/det,y=((B[1]-A[1])*ey-(C[1]-A[1])*dy)/det,u=(dx*(C[0]-A[0])-ex*(B[0]-A[0]))/det,v=(dx*(C[1]-A[1])-ex*(B[1]-A[1]))/det;ctx.save();ctx.beginPath();dst.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.clip();ctx.transform(x,y,u,v,A[0]-x*a[0]-u*a[1],A[1]-y*a[0]-v*a[1]);ctx.drawImage(image,0,0);ctx.restore();}
export function mountPaperPreviewV77(container,state,geo,graph,model,{buildTransforms,materialStyle,onStatus,onSelectPanel,selectedPanelId,authoring={},maxTexturePixels=900}={}){
 container.replaceChildren();const canvas=document.createElement('canvas');canvas.className='v17-proof-renderer v77-paper-renderer';container.append(canvas);const ctx=canvas.getContext('2d'),paper=paperAppearanceV77(state.structure),face=paper.face,textures=new Map();
 let disposed=false,progress=state.foldProgress??100,opts=structuredClone(authoring),selected=selectedPanelId,yaw=.62,pitch=.35,zoom=1,draw=[],meshes,drag=null,frame=0,renderCount=0;
 function refreshTextures(){for(const p of model.panels)textures.set(p.nodeId,renderPanelArtworkCanvas(p.plan||{width:p.panel.w,height:p.panel.h,commands:[]},{maxPixels:maxTexturePixels,background:face,onUpdate:paint}));}
 function geometry(){const transforms=buildTransforms(graph,geo,progress,opts),panels=model.panels.map(p=>{const m=transforms.get(p.nodeId),points=p.uvMap.points.map(q=>apply(m,[q[0]-geo.width/2,geo.height/2-q[1],0])),tri=[...p.uvMap.triangles[0]].reverse(),a=points[tri[0]],b=points[tri[1]].map((v,i)=>v-a[i]),c=points[tri[2]].map((v,i)=>v-a[i]),n=cross(b,c),l=Math.hypot(...n)||1;return{...p,points,normal:n.map(v=>v/l),uvMap:{...p.uvMap,triangles:p.uvMap.triangles.map(t=>[...t].reverse())}};});if(opts.explode){const spread=Math.max(geo.width,geo.height)*.13*opts.explode;for(const p of panels){p.points=p.points.map(q=>q.map((v,i)=>v+p.normal[i]*spread));}}const all=panels.flatMap(p=>p.points),min=[0,1,2].map(i=>Math.min(...all.map(p=>p[i]))),max=[0,1,2].map(i=>Math.max(...all.map(p=>p[i])));return{panels,min,max,center:min.map((v,i)=>(v+max[i])/2),span:Math.max(1,...max.map((v,i)=>v-min[i])),upAxis:geo.foldRoot==='base'?'Z':'Y',progress,innerColor:paper.inner,thicknessMm:state.structure.thickness||.5};}
 function paint(){if(disposed||!canvas.width)return;meshes=geometry();const d=Math.min(devicePixelRatio||1,2),w=canvas.width/d,h=canvas.height/d,s=sceneSettingsV71({...state.sceneV71,preset:'paper',background:'#f1f1ef',yaw,pitch,zoom,contrast:1,finish:paper.finish,innerColor:paper.inner});
 const unit=q=>{const p=q.map((v,i)=>(v-meshes.center[i])/meshes.span);return meshes.upAxis==='Z'?[p[0],-p[2],p[1]]:p;},view=q=>{const[x,y,z]=unit(q),cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x1=cy*x-sy*z,z1=sy*x+cy*z;return[x1,cp*y-sp*z1,sp*y+cp*z1];};
 const scale=h/(2*Math.tan(s.fov*Math.PI/360)),distance=2.6/zoom,project=q=>{const[x,y,z]=view(q),k=scale/(distance-z);return[w/2+x*k,h/2-y*k];};draw=meshes.panels.map(p=>({p,points:p.points.map(project),depth:p.points.reduce((sum,q)=>sum+view(q)[2],0)/p.points.length})).sort((a,b)=>a.depth-b.depth);
 if(physicalStudioReadyV74())try{renderPhysicalStudioV74(meshes,textures,s,canvas.width,canvas.height,canvas);}catch{software();}else software();
 function software(){ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle=s.background;ctx.fillRect(0,0,w,h);ctx.save();ctx.filter='blur(10px)';ctx.fillStyle='rgba(37,35,30,.13)';ctx.beginPath();ctx.ellipse(w/2,h*.78,w*.22,h*.035,0,0,Math.PI*2);ctx.fill();ctx.restore();for(const {p,points}of draw){ctx.beginPath();points.forEach((q,i)=>i?ctx.lineTo(...q):ctx.moveTo(...q));ctx.closePath();const outside=area(points)>0;ctx.fillStyle=outside?face:paper.inner;ctx.fill();if(outside){const image=textures.get(p.nodeId);for(const tri of p.uvMap.triangles)triangle(ctx,image,tri.map(i=>[p.uvMap.uv[i][0]*image.width,p.uvMap.uv[i][1]*image.height]),tri.map(i=>points[i]));}ctx.beginPath();points.forEach((q,i)=>i?ctx.lineTo(...q):ctx.moveTo(...q));ctx.closePath();ctx.fillStyle='rgba(39,34,26,'+(outside?.035:.075)+')';ctx.fill();ctx.strokeStyle='rgba(80,65,43,.28)';ctx.lineWidth=.65;ctx.stroke();}canvas.dataset.renderer='software2d';}
 ctx.setTransform(d,0,0,d,0,0);const penetration=new Set(opts.collisionPanels||opts.penetrationPanels||[]),overlap=new Set(opts.overlapPanels||[]),active=new Set(opts.activePanels||[]);for(const{p,points}of draw){if(area(points)<=0)continue;if(p.panelId!==selected&&!penetration.has(p.panelId)&&!overlap.has(p.panelId)&&!active.has(p.panelId))continue;ctx.beginPath();points.forEach((q,i)=>i?ctx.lineTo(...q):ctx.moveTo(...q));ctx.closePath();ctx.strokeStyle=active.has(p.panelId)?'#ffe08a':penetration.has(p.panelId)?'#ff4d5a':overlap.has(p.panelId)?'#ff9f43':'rgba(49,92,218,.65)';ctx.lineWidth=penetration.has(p.panelId)?2:1.4;ctx.stroke();}if(opts.dimensionsVisible===true){const item=draw.find(x=>x.p.panelId===selected);if(item){const x=Math.max(6,Math.min(w-146,item.points.reduce((a,p)=>a+p[0],0)/item.points.length-70)),y=Math.max(18,Math.min(h-6,Math.max(...item.points.map(p=>p[1]))+18));ctx.fillStyle='rgba(255,255,255,.94)';ctx.fillRect(x-4,y-13,148,20);ctx.fillStyle='#315cda';ctx.font='11px sans-serif';ctx.fillText(item.p.panel.w.toFixed(1)+' × '+item.p.panel.h.toFixed(1)+' mm',x,y);}}renderCount++;canvas.dataset.fold=String(progress);canvas.dataset.renderCount=String(renderCount);
 }
 function resize(){const r=container.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.floor(r.width))*d;canvas.height=Math.max(1,Math.floor(r.height))*d;canvas.style.width='100%';canvas.style.height='100%';paint();}
 const down=e=>{drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};canvas.setPointerCapture?.(e.pointerId);},move=e=>{if(!drag)return;drag.moved||=Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4;yaw-=(e.clientX-drag.x)*.008;pitch=clamp(pitch+(e.clientY-drag.y)*.008,-1.4,1.4);drag.x=e.clientX;drag.y=e.clientY;paint();},up=e=>{if(!drag)return;const moved=drag.moved;drag=null;if(moved||!onSelectPanel)return;const r=canvas.getBoundingClientRect(),point=[e.clientX-r.left,e.clientY-r.top];for(const item of [...draw].reverse())if(hit(point,item.points)){selected=item.p.panelId;onSelectPanel(selected);paint();break;}},wheel=e=>{e.preventDefault();zoom=clamp(zoom*Math.exp(-e.deltaY*.001),.3,3);paint();};
 canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',wheel,{passive:false});const ro=new ResizeObserver(resize);ro.observe(container);refreshTextures();resize();onStatus?.({mode:'paper-studio-v77',...model.stats});prepareFontsV74(state).then(()=>{if(!disposed){refreshTextures();paint();}}).catch(()=>{});loadPhysicalStudioV74().then(()=>{if(!disposed)paint();}).catch(()=>{});
 return{model,setProgress(v){progress=clamp(v,0,100);paint();},setAuthoring(v){opts=structuredClone(v||{});paint();},setSelectedPanel(id){selected=id;paint();},getSelectedPanel:()=>selected,getAuthoring:()=>structuredClone(opts),setView(v={}){if(Number.isFinite(v.yaw))yaw=v.yaw;if(Number.isFinite(v.pitch))pitch=v.pitch;if(Number.isFinite(v.zoom))zoom=v.zoom;paint();},getDebugState:()=>({progress,selected,authoring:structuredClone(opts),drawnPanels:draw.map(x=>x.p.panelId),exteriorPanels:draw.filter(x=>area(x.points)>0).map(x=>x.p.panelId),renderCount,meshes:meshes?.panels.map(p=>({id:p.panelId,points:p.points})),penetrationPanels:[...(opts.collisionPanels||opts.penetrationPanels||[])],overlapPanels:[...(opts.overlapPanels||[])],activePanels:[...(opts.activePanels||[])]}),repaint:paint,dispose(){disposed=true;cancelAnimationFrame(frame);ro.disconnect();canvas.remove();}};
}
