import {PATTERN_CATALOG_V76,PATTERN_TILES_V76} from './patternDataV76.js';
export {PATTERN_CATALOG_V76};
const f=n=>Number(n.toFixed(5));
export function patternSettingsV76(el){const tile=PATTERN_TILES_V76[el.patternIdV76];if(!tile)throw new Error('底纹不存在。');const size=Number(el.tileSizeV76??24),ink=el.fillColor||'#315cda',background=el.backgroundV76??'transparent';if(!Number.isFinite(size)||size<2||size>100||!/^#[0-9a-f]{6}$/i.test(ink)||(background!=='transparent'&&!/^#[0-9a-f]{6}$/i.test(background)))throw new Error('底纹重复宽度需为 2–100 mm，颜色需为有效色值。');if(!Number.isFinite(el.w)||!Number.isFinite(el.h)||el.w<4||el.h<4||el.w>1500||el.h>1500)throw new Error('底纹区域尺寸无效。');const height=size*tile.height/tile.width,nx=Math.ceil(el.w/size),ny=Math.ceil(el.h/height),ops=tile.paths.reduce((n,p)=>n+p.ops.length,0);if(nx*ny>1600||nx*ny*ops>180000)throw new Error('底纹过密，请增大重复宽度或缩小区域后再应用。');return{tile,size,height,ink,background,nx,ny};}
export function patternPrimitivesV76(el){const s=patternSettingsV76(el),scale=s.size/s.tile.width,rows=[];for(let iy=0;iy<s.ny;iy++)for(let ix=0;ix<s.nx;ix++)for(const p of s.tile.paths)rows.push({rule:p.rule,opacity:p.opacity,tile:{x:ix*s.size,y:iy*s.height,w:s.size,h:s.height},ops:p.ops.map(([op,...v])=>[op,...v.map((n,i)=>f(n*scale+(i%2?iy*s.height:ix*s.size)))])});return rows;}
export function patternSvgV76(el){const s=patternSettingsV76(el),id='v76-pattern-'+String(el.id||el.patternIdV76).replace(/[^a-zA-Z0-9_-]/g,'-'),clips=['<clipPath id="'+id+'-frame"><rect width="'+el.w+'" height="'+el.h+'"/></clipPath>'],tiles=new Map();for(const p of patternPrimitivesV76(el)){const key=p.tile.x+','+p.tile.y;let tile=tiles.get(key);if(!tile){const clip=id+'-tile-'+tiles.size,t=p.tile;clips.push('<clipPath id="'+clip+'"><rect x="'+f(t.x)+'" y="'+f(t.y)+'" width="'+f(t.w)+'" height="'+f(t.h)+'"/></clipPath>');tile={clip,paths:[]};tiles.set(key,tile);}tile.paths.push('<path d="'+p.ops.map(([op,...v])=>op+v.join(' ')).join(' ')+'" fill="'+s.ink+'" fill-rule="'+p.rule+'" opacity="'+p.opacity+'"/>');}const paths=[...tiles.values()].map(t=>'<g clip-path="url(#'+t.clip+')">'+t.paths.join('')+'</g>').join('');return '<g data-pattern-v76="'+el.patternIdV76+'"><metadata>Hero Patterns by Steve Schoger · CC BY 4.0 · https://heropatterns.com/ · https://creativecommons.org/licenses/by/4.0/ · adapted colors and physical repetition</metadata><defs>'+clips.join('')+'</defs><g clip-path="url(#'+id+'-frame)">'+(s.background==='transparent'?'':'<rect width="'+el.w+'" height="'+el.h+'" fill="'+s.background+'"/>')+paths+'</g></g>';}
export const patternAlphaResourcesV76='/V76A05 << /Type /ExtGState /ca 0.5 /CA 0.5 >>';
export function patternPdfV76(el,x,y,pageH,pt,{colorCommand=null}={}){const s=patternSettingsV76(el),color=c=>{const rgb=c.slice(1).match(/../g).map(v=>parseInt(v,16)/255);return colorCommand?colorCommand(rgb):rgb.map(f).join(' ')+' rg';},rows=['% Hero Patterns by Steve Schoger - CC BY 4.0 - https://heropatterns.com/','q'];if(el.r){const a=-el.r*Math.PI/180,c=Math.cos(a),sn=Math.sin(a),cx=(x+el.w/2)*pt,cy=(pageH-y-el.h/2)*pt;rows.push([c,sn,-sn,c,cx-c*cx+sn*cy,cy-sn*cx-c*cy].map(f).join(' ')+' cm');}rows.push(f(x*pt)+' '+f((pageH-y-el.h)*pt)+' '+f(el.w*pt)+' '+f(el.h*pt)+' re W n');if(s.background!=='transparent')rows.push(color(s.background)+' '+f(x*pt)+' '+f((pageH-y-el.h)*pt)+' '+f(el.w*pt)+' '+f(el.h*pt)+' re f');rows.push(color(s.ink));for(const p of patternPrimitivesV76(el)){const t=p.tile;rows.push('q '+f((x+t.x)*pt)+' '+f((pageH-y-t.y-t.h)*pt)+' '+f(t.w*pt)+' '+f(t.h*pt)+' re W n');if(p.opacity!==1){if(p.opacity!==.5)throw new Error('底纹透明度暂不支持。');rows.push('/V76A05 gs');}for(const[op,...v]of p.ops)rows.push(op==='Z'?'h':v.map((n,i)=>f((i%2?pageH-y-n:x+n)*pt)).join(' ')+({M:' m',L:' l',C:' c'}[op]));rows.push((p.rule==='evenodd'?'f*':'f')+' Q');}rows.push('Q');return rows;}
export function paintPatternV76(ctx,el,sx,sy){const s=patternSettingsV76(el);ctx.save();ctx.translate(el.x*sx,el.y*sy);ctx.scale(sx,sy);ctx.beginPath();ctx.rect(0,0,el.w,el.h);ctx.clip();if(s.background!=='transparent'){ctx.fillStyle=s.background;ctx.fillRect(0,0,el.w,el.h);}ctx.fillStyle=s.ink;for(const p of patternPrimitivesV76(el)){ctx.save();ctx.globalAlpha*=p.opacity;ctx.beginPath();ctx.rect(p.tile.x,p.tile.y,p.tile.w,p.tile.h);ctx.clip();ctx.beginPath();for(const[op,...v]of p.ops){if(op==='M')ctx.moveTo(...v);else if(op==='L')ctx.lineTo(...v);else if(op==='C')ctx.bezierCurveTo(...v);else ctx.closePath();}ctx.fill(p.rule);ctx.restore();}ctx.restore();}
export function createPatternV76(id,panel,{tileSize=24,color='#315cda',background='transparent',fullPanel=false}={}){const entry=PATTERN_CATALOG_V76.find(p=>p.id===id);if(!entry)throw new Error('底纹不存在。');const el={id:'pattern-'+crypto.randomUUID(),type:'shape',group:'artwork',panelId:panel.id,x:fullPanel?0:8,y:fullPanel?0:8,w:fullPanel?panel.w:Math.min(100,panel.w-16),h:fullPanel?panel.h:Math.min(70,panel.h-16),r:0,patternIdV76:id,tileSizeV76:tileSize,fillColor:color,backgroundV76:background,name:entry.label,attributionV76:{author:entry.author,license:entry.license,source:entry.website}};patternSettingsV76(el);return el;}
