import { runPreflight } from './preflight.js';
import { generateGeometry, resolveElementRect } from './geometry.js';
import { dielineDocumentFromGeometryV38, validateDielineDocumentV38, geometryFromDielineDocumentV38 } from './dielineCadV38.js';

const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
function check(severity,code,title,detail,entityId=null){return{severity,code,title,detail,entityId}}
function rectLineCross(rect,line,tol=.01){const left=rect.x,right=rect.x+rect.w,top=rect.y,bottom=rect.y+rect.h;if(Math.abs(line.x1-line.x2)<=tol){const x=line.x1,y1=Math.min(line.y1,line.y2),y2=Math.max(line.y1,line.y2);return x>left+tol&&x<right-tol&&Math.max(top,y1)<Math.min(bottom,y2)-tol}if(Math.abs(line.y1-line.y2)<=tol){const y=line.y1,x1=Math.min(line.x1,line.x2),x2=Math.max(line.x1,line.x2);return y>top+tol&&y<bottom-tol&&Math.max(left,x1)<Math.min(right,x2)-tol}return false}
function imageDpiChecks(state){const out=[];for(const el of state?.elements||[]){if(!String(el.type||'').toLowerCase().includes('image'))continue;const pxW=finite(el.pixelWidth||el.intrinsicWidthPx||el.naturalWidth),pxH=finite(el.pixelHeight||el.intrinsicHeightPx||el.naturalHeight),mmW=Math.abs(finite(el.w)),mmH=Math.abs(finite(el.h));if(!pxW||!pxH||!mmW||!mmH){out.push(check('warning','IMAGE_DPI_UNKNOWN','Image DPI',`${el.id}: 缺少像素尺寸元数据，无法验证有效 DPI。`,el.id));continue}const dpi=Math.min(pxW/(mmW/25.4),pxH/(mmH/25.4));out.push(check(dpi<150?'error':dpi<300?'warning':'pass','IMAGE_DPI',`Image DPI · ${el.id}`,`${dpi.toFixed(1)} DPI · ${pxW}×${pxH}px @ ${mmW.toFixed(1)}×${mmH.toFixed(1)}mm`,el.id))}return out}
function foldCrossChecks(state,geo){const out=[];for(const el of state?.elements||[]){if(el.hidden)continue;let rr;try{rr=resolveElementRect(el,geo)}catch{continue}const rect={x:rr.absX,y:rr.absY,w:Math.max(0,finite(el.w)),h:Math.max(0,finite(el.h))},hits=(geo.creaseLines||[]).filter(line=>rectLineCross(rect,line));if(hits.length)out.push(check('warning','ARTWORK_CROSSES_CREASE','Artwork crosses fold',`${el.id} crosses ${hits.length} edited crease line${hits.length===1?'':'s'}.`,el.id))}return out}
function normalizeLegacy(item,index){const sev=item.severity==='error'?'error':item.severity==='warning'?'warning':'pass',slug=String(item.title||'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'');return{...item,severity:sev,code:item.code||`LEGACY_${slug||index}`}}
function typeCounts(doc){const out={CUT:0,CREASE:0,PERF:0,GLUE:0};for(const e of doc.edges||[])if(e.lineType in out)out[e.lineType]++;return out}
export function runPreflightV38(state,{doc=null,tolerance=.01}={}){
  const sourceGeo=generateGeometry(state?.structure||{}),baseline=dielineDocumentFromGeometryV38(sourceGeo),dieline=doc||baseline,structural=validateDielineDocumentV38(dieline,{tolerance}),checks=[];
  for(const item of runPreflight(state).map(normalizeLegacy))checks.push(item);
  for(const item of structural.issues)checks.push(check(item.severity,item.code,'Dieline structure',item.detail,item.entityId));
  const rectangular=(dieline.panels||[]).filter(p=>Number.isFinite(p.x)&&p.w>0),polygons=(dieline.panels||[]).filter(p=>Array.isArray(p.points)&&p.points.length>=3),bleedPanels=new Set((dieline.zones?.bleed||[]).map(z=>z.panelId)),safePanels=new Set((dieline.zones?.safe||[]).map(z=>z.panelId));const missingBleed=rectangular.filter(p=>!bleedPanels.has(p.id)),missingSafe=rectangular.filter(p=>!safePanels.has(p.id));checks.push(check(missingBleed.length?'error':'pass','BLEED_COVERAGE','Bleed zone coverage',missingBleed.length?`Missing bleed zones: ${missingBleed.map(p=>p.id).join(', ')}`:`${rectangular.length} rectangular panels covered.`));checks.push(check(missingSafe.length?'warning':'pass','SAFE_COVERAGE','Safe zone coverage',missingSafe.length?`Missing safe zones: ${missingSafe.map(p=>p.id).join(', ')}`:`${rectangular.length} rectangular panels covered.`));if(polygons.length)checks.push(check('warning','POLYGON_OFFSET_REVIEW','Polygon bleed/safe offset',`${polygons.length} polygon panel${polygons.length===1?'':'s'} require a true polygon/Bezier offset review; rectangular zone generation is not claimed for them.`));
  const editedGeo=geometryFromDielineDocumentV38(dieline);editedGeo.panelMap=Object.fromEntries((editedGeo.panels||[]).map(p=>[p.id,p]));checks.push(...foldCrossChecks(state,editedGeo));checks.push(...imageDpiChecks(state));
  if(doc){const before=typeCounts(baseline),after=typeCounts(dieline),changed=Object.keys(before).filter(k=>before[k]!==after[k]);if(changed.length)checks.push(check('warning','FOLD_GRAPH_REVIEW_REQUIRED','Fold graph review after CAD edit',`Semantic edge counts changed (${changed.map(k=>`${k} ${before[k]}→${after[k]}`).join(', ')}). Reconfirm hinge/fold topology before factory release.`))}
  const errors=checks.filter(x=>x.severity==='error'),warnings=checks.filter(x=>x.severity==='warning'),passes=checks.filter(x=>x.severity==='pass');return{schema:'boxstudio-preflight-v38',ok:errors.length===0,errors,warnings,passes,checks,dieline,structural,summary:{errors:errors.length,warnings:warnings.length,passes:passes.length,total:checks.length}};
}
export function productionGateV38(state,options={}){const report=runPreflightV38(state,options);return{ok:report.ok,blocked:!report.ok,summary:report.summary,blockingCodes:[...new Set(report.errors.map(x=>x.code))],report}}
