import { renderTemplate, isPackageNoticeVisible } from './variables.js';
import { generateGeometry, resolveElementRect, uniqueLines } from './geometry.js';
import { barcodeLayout } from './barcode.js';
import { qrMatrix } from './qrcode.js';
import { flattenCurves } from './importDieline.js';
import { vectorTextRects } from './vectorText.js';
import { getUserTtf } from './fontRegistry.js';
import { textOutlineCommands } from './ttfOutline.js';
import { getOutputIcc } from './iccRegistry.js';
import { spotNameFor } from './printProfiles.js';
import { downloadBytes, pdfxCandidateIssues } from './export.js';
import { buildNativePdfV22Plan } from './nativePdfV22.js';
import { materializeSvgMarkElement } from './svgMark.js';
import { materializeCrossPanelArtworkElement } from './crossPanelArtwork.js';
import { orderedElements } from './objectOrder.js';
import { getRgbCmykDeviceLink, convertRgbToCmyk } from './iccDeviceLinkV23.js';

const PT=72/25.4;
const f=n=>(Number(n)||0).toFixed(4);
const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,num(v)));
function asciiPdf(s=''){return String(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'?');}
function xmlEsc(s=''){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
function concatBytes(chunks){let total=0;for(const c of chunks)total+=c.length;const out=new Uint8Array(total);let at=0;for(const c of chunks){out.set(c,at);at+=c.length;}return out;}
function pdfLine(cmds,pageH,l,{dash=false,width=.45}={}){cmds.push(`${f(width)} w ${dash?'[8 5] 0 d':'[] 0 d'} ${f(l.x1*PT)} ${f((pageH-l.y1)*PT)} m ${f(l.x2*PT)} ${f((pageH-l.y2)*PT)} l S`);}
function pdfSpotLine(cmds,pageH,l,resource,{dash=false,width=.45,overprint=true}={}){cmds.push(`q ${overprint?'/GSOP gs ':''}/${resource} CS 1 SCN ${f(width)} w ${dash?'[8 5] 0 d':'[] 0 d'} ${f(l.x1*PT)} ${f((pageH-l.y1)*PT)} m ${f(l.x2*PT)} ${f((pageH-l.y2)*PT)} l S Q`);}
function pdfRect(cmds,pageH,x,y,w,h,fill=true){cmds.push(`${f(x*PT)} ${f((pageH-y-h)*PT)} ${f(w*PT)} ${f(h*PT)} re ${fill?'f':'S'}`);}
function pdfText(cmds,pageH,x,yTop,sizeMm,text,{bold=false}={}){const font=bold?'/F2':'/F1',sizePt=Math.max(3,sizeMm*PT);String(text).split('\n').forEach((line,i)=>{const baseline=pageH-(yTop+(i+1)*sizeMm*1.15);cmds.push(`BT ${font} ${f(sizePt)} Tf ${f(x*PT)} ${f(baseline*PT)} Td (${asciiPdf(line)}) Tj ET`);});}
function pdfVectorText(cmds,pageH,x,yTop,sizeMm,text,{bold=false}={}){cmds.push('0 0 0 1 k');for(const r of vectorTextRects(String(text),x,yTop,sizeMm,{bold}))pdfRect(cmds,pageH,r.x,r.y,r.w,r.h,true);}
function pdfTtfPath(cmds,pageH,commands=[]){let cur=null;for(const c of commands){if(c.op==='M'){cmds.push(`${f(c.x*PT)} ${f((pageH-c.y)*PT)} m`);cur={x:c.x,y:c.y};}else if(c.op==='L'){cmds.push(`${f(c.x*PT)} ${f((pageH-c.y)*PT)} l`);cur={x:c.x,y:c.y};}else if(c.op==='Q'&&cur){const c1x=cur.x+2/3*(c.cx-cur.x),c1y=cur.y+2/3*(c.cy-cur.y),c2x=c.x+2/3*(c.cx-c.x),c2y=c.y+2/3*(c.cy-c.y);cmds.push(`${f(c1x*PT)} ${f((pageH-c1y)*PT)} ${f(c2x*PT)} ${f((pageH-c2y)*PT)} ${f(c.x*PT)} ${f((pageH-c.y)*PT)} c`);cur={x:c.x,y:c.y};}else if(c.op==='Z')cmds.push('h');}cmds.push('f');}
function pdfTtfText(cmds,pageH,x,yTop,sizeMm,text){const font=getUserTtf();if(!font)throw new Error('TTF outline mode enabled but no user TTF is loaded.');cmds.push('0 0 0 1 k');pdfTtfPath(cmds,pageH,textOutlineCommands(font,String(text),x,yTop,sizeMm));}
function pdfTextMode(cmds,pageH,x,yTop,sizeMm,text,{bold=false,outline=false,fontMode='technical'}={}){if(outline&&fontMode==='ttf')return pdfTtfText(cmds,pageH,x,yTop,sizeMm,text);if(outline)return pdfVectorText(cmds,pageH,x,yTop,sizeMm,text,{bold});return pdfText(cmds,pageH,x,yTop,sizeMm,text,{bold});}
function renderBarcodeQrPdf(cmds,pageH,el,absX,absY,variables,textOpts={}){const barcodeValue=renderTemplate(el.barcodeValue,variables),qrValue=renderTemplate(el.qrValue,variables),pad=5,gap=7,qrSide=Math.max(20,Math.min(el.h-pad*2,el.w*.30)),bx=absX+pad,by=absY+pad,bw=Math.max(30,el.w-pad*2-gap-qrSide),bh=Math.max(16,el.h-pad*2-11);cmds.push('0 0 0 1 K 0 0 0 1 k');cmds.push(`${f(absX*PT)} ${f((pageH-absY-el.h)*PT)} ${f(el.w*PT)} ${f(el.h*PT)} re S`);const layout=barcodeLayout(el.barcodeType||'CODE39',barcodeValue,bw,bh);for(const bar of layout.bars)pdfRect(cmds,pageH,bx+bar.x,by+bar.y,bar.w,bar.h,true);if(layout.bearer)cmds.push(`${f(bx*PT)} ${f((pageH-by-bh)*PT)} ${f(bw*PT)} ${f(bh*PT)} re S`);pdfTextMode(cmds,pageH,bx,absY+el.h-10,3.3,layout.label,textOpts);const qx=absX+el.w-pad-qrSide,qy=absY+pad;pdfRect(cmds,pageH,qx,qy,qrSide,qrSide,false);const qr=qrMatrix(qrValue),quiet=4,modules=qr.size+quiet*2,cell=qrSide/modules;for(let rr=0;rr<qr.size;rr++)for(let c=0;c<qr.size;c++)if(qr.matrix[rr][c])pdfRect(cmds,pageH,qx+(quiet+c)*cell,qy+(quiet+rr)*cell,cell+.001,cell+.001,true);}
function renderIconPdf(cmds,pageH,el,absX,absY,textOpts={}){cmds.push('0 0 0 1 K [] 0 d 0.8 w');cmds.push(`${f(absX*PT)} ${f((pageH-absY-el.h)*PT)} ${f(el.w*PT)} ${f(el.h*PT)} re S`);const cx=absX+el.w/2;if(el.icon==='up'){for(const dx of [-el.w*.18,el.w*.18]){pdfLine(cmds,pageH,{x1:cx+dx,y1:absY+el.h*.72,x2:cx+dx,y2:absY+el.h*.27},{width:.8});pdfLine(cmds,pageH,{x1:cx+dx,y1:absY+el.h*.27,x2:cx+dx-el.w*.10,y2:absY+el.h*.42},{width:.8});pdfLine(cmds,pageH,{x1:cx+dx,y1:absY+el.h*.27,x2:cx+dx+el.w*.10,y2:absY+el.h*.42},{width:.8});}}else if(el.icon==='fragile')pdfTextMode(cmds,pageH,absX+el.w*.31,absY+el.h*.18,el.h*.42,'Y',textOpts);else{pdfLine(cmds,pageH,{x1:absX+el.w*.18,y1:absY+el.h*.48,x2:absX+el.w*.5,y2:absY+el.h*.20},{width:.7});pdfLine(cmds,pageH,{x1:absX+el.w*.5,y1:absY+el.h*.20,x2:absX+el.w*.82,y2:absY+el.h*.48},{width:.7});pdfLine(cmds,pageH,{x1:absX+el.w*.5,y1:absY+el.h*.20,x2:absX+el.w*.5,y2:absY+el.h*.78},{width:.7});}}
function drawDielines(cmds,geo,options={}){const spot=options.spotDielines!==false,overprint=options.overprintDielines!==false,sets=[['CSCUT',geo.cutLines,geo.cutCurves,false,.35],['CSCREASE',geo.creaseLines,geo.creaseCurves,true,.30],['CSPERF',geo.perfLines,geo.perfCurves,true,.30],['CSGLUE',geo.glueLines,geo.glueCurves,true,.28]];for(const [res,lines,curves,dash,width] of sets)for(const l of uniqueLines([...(lines||[]),...flattenCurves(curves||[],32)])){if(spot)pdfSpotLine(cmds,geo.height,l,res,{dash,width,overprint});else{cmds.push('0 0 0 1 K');pdfLine(cmds,geo.height,l,{dash,width});}}}
function panelPolygon(panel){if(Array.isArray(panel?.points)&&panel.points.length>=3)return panel.points.map(p=>[num(p[0]),num(p[1])]);const x=num(panel?.x),y=num(panel?.y),w=num(panel?.w),h=num(panel?.h);return[[x,y],[x+w,y],[x+w,y+h],[x,y+h]];}
function path(points,pageH){if(!points?.length)return'';let s=`${f(points[0][0]*PT)} ${f((pageH-points[0][1])*PT)} m`;for(let i=1;i<points.length;i++)s+=` ${f(points[i][0]*PT)} ${f((pageH-points[i][1])*PT)} l`;return s+' h';}
function clipCmd(polys,pageH){return(polys||[]).length?polys.map(p=>path(p,pageH)).join(' ')+' W n':'';}
function varyingStopAlpha(stops=[]){if(!stops.length)return false;const a=stops.map(s=>clamp(s.opacity,0,1));return Math.max(...a)-Math.min(...a)>1e-6;}
function colorValues(rgb,useCmyk){if(useCmyk){const v=convertRgbToCmyk(rgb);if(!v)throw new Error('ICC DeviceLink became unavailable during PDF export.');return v.map(x=>clamp(x));}return(rgb||[0,0,0]).map(x=>clamp(x));}
function colorText(v){return(v||[]).map(x=>f(x)).join(' ');}
function makeFunction(stops,add,useCmyk){const seg=[];for(let i=0;i<stops.length-1;i++){const a=colorValues(stops[i].color,useCmyk),b=colorValues(stops[i+1].color,useCmyk);seg.push(add(`<< /FunctionType 2 /Domain [0 1] /C0 [${colorText(a)}] /C1 [${colorText(b)}] /N 1 >>`));}if(seg.length===1)return seg[0];const bounds=stops.slice(1,-1).map(s=>f(s.offset)).join(' '),encode=seg.map(()=>'0 1').join(' ');return add(`<< /FunctionType 3 /Domain [0 1] /Functions [${seg.map(id=>`${id} 0 R`).join(' ')}] /Bounds [${bounds}] /Encode [${encode}] >>`);}
function makeAlphaFunction(stops,primitiveOpacity,add){const seg=[];for(let i=0;i<stops.length-1;i++){const a=clamp(stops[i].opacity*primitiveOpacity),b=clamp(stops[i+1].opacity*primitiveOpacity);seg.push(add(`<< /FunctionType 2 /Domain [0 1] /C0 [${f(a)}] /C1 [${f(b)}] /N 1 >>`));}if(seg.length===1)return seg[0];const bounds=stops.slice(1,-1).map(s=>f(s.offset)).join(' '),encode=seg.map(()=>'0 1').join(' ');return add(`<< /FunctionType 3 /Domain [0 1] /Functions [${seg.map(id=>`${id} 0 R`).join(' ')}] /Bounds [${bounds}] /Encode [${encode}] >>`);}
function shadingDictionary(g,functionId,pageH,colorSpace){const c=g.coords.map((v,i)=>i%2===1?((pageH-v)*PT):(v*PT)),type=g.type==='radial'?3:2;return`<< /ShadingType ${type} /ColorSpace ${colorSpace} /Coords [${c.map(f).join(' ')}] /Function ${functionId} 0 R /Extend [true true] >>`;}
function pdfName(s='Spot'){return String(s).replace(/[^A-Za-z0-9_.-]/g,ch=>'#'+ch.charCodeAt(0).toString(16).toUpperCase().padStart(2,'0'));}
function spotColorSpaces(options={}){const names={CUT:pdfName(spotNameFor(options,'CUT')),CREASE:pdfName(spotNameFor(options,'CREASE')),PERF:pdfName(spotNameFor(options,'PERF')),GLUE:pdfName(spotNameFor(options,'GLUE'))};return`/CSCUT [/Separation /${names.CUT} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [0 1 0 0] /N 1 >>] /CSCREASE [/Separation /${names.CREASE} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [1 0 0 0] /N 1 >>] /CSPERF [/Separation /${names.PERF} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [0 0 1 0] /N 1 >>] /CSGLUE [/Separation /${names.GLUE} /DeviceCMYK << /FunctionType 2 /Domain [0 1] /C0 [0 0 0 0] /C1 [1 0 1 0] /N 1 >>]`;}
function buildXmp(options={},icc){const id=xmlEsc(options.outputConditionIdentifier||icc?.name||'Custom CMYK');return`<?xpacket begin="\ufeff" id="W5M0MpCehiHzreSzNTczkc9w"?>\n<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="BoxStudio V0.23"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description rdf:about="" xmlns:pdfxid="http://www.npes.org/pdfx/ns/id/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmlns:pdf="http://ns.adobe.com/pdf/1.3/"><pdfxid:GTS_PDFXVersion>PDF/X-4</pdfxid:GTS_PDFXVersion><dc:format>application/pdf</dc:format><xmp:CreatorTool>BoxStudio V0.23</xmp:CreatorTool><pdf:Producer>BoxStudio V0.23</pdf:Producer><pdf:Keywords>${id}</pdf:Keywords></rdf:Description></rdf:RDF></x:xmpmeta>\n<?xpacket end="w"?>`;}
function appearanceOutlineLines(el,geo){if(el.type==='svg-symbol'){const panel=geo.panelMap?.[el.panelId];if(!panel)return[];return materializeSvgMarkElement(el).map(l=>({x1:num(panel.x)+num(l.x),y1:num(panel.y)+num(l.y),x2:num(panel.x)+num(l.x)+num(l.w),y2:num(panel.y)+num(l.y)+num(l.h)}));}if(el.type==='cross-panel-artwork'){return materializeCrossPanelArtworkElement(el,geo).filter(l=>l.type==='line').map(l=>{const p=geo.panelMap?.[l.panelId];return{x1:num(p?.x)+num(l.x),y1:num(p?.y)+num(l.y),x2:num(p?.x)+num(l.x)+num(l.w),y2:num(p?.y)+num(l.y)+num(l.h)};});}return[];}
function candidateIssuesV23(state){const check=structuredClone(state);for(const e of check.elements||[])if(e.type==='svg-symbol'||e.type==='cross-panel-artwork')e.r=0;return pdfxCandidateIssues(check);}

export function buildProductionPdfV23(state){
  const issues=candidateIssuesV23(state);if(issues.length)throw new Error('PDF/X Candidate blocked: '+issues.join('；'));const geo=generateGeometry(state.structure),plan=buildNativePdfV22Plan(state),useCmyk=Boolean(getRgbCmykDeviceLink()),pageW=geo.width,pageH=geo.height,enc=new TextEncoder(),objects=[null],add=body=>{objects.push(body);return objects.length-1},alphaRefs=new Map(),softMaskRefs=[],shadingRefs=[],appearance=[];
  const alphaName=opacity=>{const a=clamp(opacity);if(a>=.999)return null;const key=a.toFixed(4);if(!alphaRefs.has(key))alphaRefs.set(key,{name:`GS${alphaRefs.size+1}`,id:add(`<< /Type /ExtGState /ca ${f(a)} /CA ${f(a)} >>`)});return alphaRefs.get(key).name;};
  for(const op of plan.ops||[]){if(op.kind==='gradient'){const fn=makeFunction(op.gradient.stops,add,useCmyk),sid=add(shadingDictionary(op.gradient,fn,pageH,useCmyk?'/DeviceCMYK':'/DeviceRGB')),entry={op,name:`Sh${shadingRefs.length+1}`,sid,gs:null};if(varyingStopAlpha(op.gradient.stops)){const af=makeAlphaFunction(op.gradient.stops,clamp(op.opacity),add),asid=add(shadingDictionary(op.gradient,af,pageH,'/DeviceGray')),maskName=`MS${softMaskRefs.length+1}`,maskContent=['q',clipCmd(op.clips,pageH),path(op.points,pageH),'W n',`/${maskName} sh`,'Q'].filter(Boolean).join('\n')+'\n',formId=add(`<< /Type /XObject /Subtype /Form /BBox [0 0 ${f(pageW*PT)} ${f(pageH*PT)}] /Group << /S /Transparency /CS /DeviceGray >> /Resources << /Shading << /${maskName} ${asid} 0 R >> >> /Length ${enc.encode(maskContent).length} >>\nstream\n${maskContent}endstream`),gsName=`SM${softMaskRefs.length+1}`,gsId=add(`<< /Type /ExtGState /SMask << /S /Luminosity /G ${formId} 0 R >> >>`);entry.gs=gsName;softMaskRefs.push({name:gsName,id:gsId});}else entry.gs=alphaName(op.opacity);shadingRefs.push(entry);appearance.push(entry);}else appearance.push({op,gs:alphaName(op.opacity)});}
  const appearanceBySource=new Map();for(const a of appearance){const id=a.op.source;if(!appearanceBySource.has(id))appearanceBySource.set(id,[]);appearanceBySource.get(id).push(a);}
  const cmds=['q','0 0 0 0 k',`0 0 ${f(pageW*PT)} ${f(pageH*PT)} re f`,'Q'];drawDielines(cmds,geo,state.exportOptions||{});const textOpts={outline:Boolean(state.exportOptions?.outlineText),fontMode:state.exportOptions?.fontMode||'technical'};
  if(!state.hiddenGroups?.marks)for(const el of orderedElements(state.elements||[])){
    if(el.type==='notice'&&!isPackageNoticeVisible(state.variables))continue;
    if(el.type==='svg-symbol'||el.type==='cross-panel-artwork'){
      for(const entry of appearanceBySource.get(el.id)||[]){const op=entry.op;cmds.push('q');if(op.clips?.length)cmds.push(clipCmd(op.clips,pageH));cmds.push(path(op.points,pageH),'W n');if(entry.gs)cmds.push(`/${entry.gs} gs`);if(op.kind==='gradient')cmds.push(`/${entry.name} sh`);else{const values=colorValues(op.color,useCmyk);cmds.push(`${colorText(values)} ${useCmyk?'k':'rg'}`,`0 0 ${f(pageW*PT)} ${f(pageH*PT)} re f`);}cmds.push('Q');}
      cmds.push('0 0 0 1 K');for(const l of appearanceOutlineLines(el,geo))pdfLine(cmds,pageH,l,{width:.35});continue;
    }
    const rr=resolveElementRect(el,geo),x=rr.absX,y=rr.absY;if(el.type==='text'||el.type==='notice')pdfTextMode(cmds,pageH,x+3,y,el.fontSize||4.5,renderTemplate(el.template,state.variables),{bold:el.bold,...textOpts});else if(el.type==='barcode-qr-group')renderBarcodeQrPdf(cmds,pageH,el,x,y,state.variables,textOpts);else if(el.type==='icon')renderIconPdf(cmds,pageH,el,x,y,textOpts);else if(el.type==='shape'){cmds.push('0 0 0 1 K [] 0 d 0.6 w');pdfRect(cmds,pageH,x,y,el.w,el.h,false);}else if(el.type==='line'){cmds.push('0 0 0 1 K [] 0 d 0.6 w');pdfLine(cmds,pageH,{x1:x,y1:y,x2:x+el.w,y2:y+el.h},{width:.6});}
  }
  const content=cmds.join('\n')+'\n',contentId=add(`<< /Length ${enc.encode(content).length} >>\nstream\n${content}endstream`),candidate=state.exportOptions?.pdfxMode==='candidate',fontRegular=candidate?0:add(''),fontBold=candidate?0:add('');if(!candidate){objects[fontRegular]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';objects[fontBold]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>';}
  let iccId=0,outputIntentId=0,metadataId=0;if(candidate){const icc=getOutputIcc();if(!icc?.isCmyk)throw new Error('PDF/X Candidate requires a loaded CMYK ICC profile.');iccId=add(concatBytes([enc.encode(`<< /N 4 /Alternate /DeviceCMYK /Length ${icc.bytes.length} >>\nstream\n`),icc.bytes,enc.encode('\nendstream')]));const opt=state.exportOptions||{},identifier=asciiPdf(opt.outputConditionIdentifier||icc.name||'Custom CMYK'),infoText=asciiPdf(opt.outputConditionInfo||`User supplied ICC: ${icc.name}`);outputIntentId=add(`<< /Type /OutputIntent /S /GTS_PDFX /OutputConditionIdentifier (${identifier}) /Info (${infoText}) /RegistryName (http://www.color.org) /DestOutputProfile ${iccId} 0 R >>`);const xmp=enc.encode(buildXmp(opt,icc));metadataId=add(concatBytes([enc.encode(`<< /Type /Metadata /Subtype /XML /Length ${xmp.length} >>\nstream\n`),xmp,enc.encode('\nendstream')]));}
  const pagesId=add(''),pageId=add(''),catalogId=add(''),infoId=add(''),shadingRes=shadingRefs.map(x=>`/${x.name} ${x.sid} 0 R`).join(' '),gsRes=[...alphaRefs.values(),...softMaskRefs].map(x=>`/${x.name} ${x.id} 0 R`).join(' '),spot=state.exportOptions?.spotDielines!==false?spotColorSpaces(state.exportOptions):'',fontRes=candidate?'':`/Font << /F1 ${fontRegular} 0 R /F2 ${fontBold} 0 R >>`,colorRes=spot?`/ColorSpace << ${spot} >>`:'',extRes=`/ExtGState << /GSOP << /Type /ExtGState /OP true /op true /OPM 1 >> ${gsRes} >>`,shadeRes=shadingRes?`/Shading << ${shadingRes} >>`:'',extras=candidate?` /Metadata ${metadataId} 0 R /OutputIntents [${outputIntentId} 0 R]`:'';
  objects[pagesId]=`<< /Type /Pages /Kids [${pageId} 0 R] /Count 1 >>`;objects[pageId]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${f(pageW*PT)} ${f(pageH*PT)}] /TrimBox [0 0 ${f(pageW*PT)} ${f(pageH*PT)}] /BleedBox [0 0 ${f(pageW*PT)} ${f(pageH*PT)}] /Resources << ${fontRes} ${colorRes} ${extRes} ${shadeRes} >> /Contents ${contentId} 0 R >>`;objects[catalogId]=`<< /Type /Catalog /Pages ${pagesId} 0 R${extras} >>`;objects[infoId]=`<< /Producer (BoxStudio V0.23) /Creator (BoxStudio) /Title (Packaging Production Artwork V0.23) /Trapped /False${candidate?' /GTS_PDFXVersion (PDF/X-4)':''} >>`;
  const chunks=[enc.encode('%PDF-1.7\n%BoxStudio V0.23 Integrated Production PDF\n')],offsets=new Array(objects.length).fill(0);let pos=chunks[0].length;for(let i=1;i<objects.length;i++){offsets[i]=pos;const body=objects[i] instanceof Uint8Array?objects[i]:enc.encode(String(objects[i])),obj=concatBytes([enc.encode(`${i} 0 obj\n`),body,enc.encode('\nendobj\n')]);chunks.push(obj);pos+=obj.length;}const xref=pos;let tail=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)tail+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;tail+=`trailer\n<< /Size ${objects.length} /Root ${catalogId} 0 R /Info ${infoId} 0 R >>\nstartxref\n${xref}\n%%EOF\n`;chunks.push(enc.encode(tail));return concatBytes(chunks);
}
export function productionPdfV23Diagnostics(state){const plan=buildNativePdfV22Plan(state),link=getRgbCmykDeviceLink();return{nativeAppearanceObjects:plan.stats.objects,axial:plan.stats.axial,radial:plan.stats.radial,softMasks:plan.stats.softMasks||0,colorSpace:link?'DeviceCMYK (ICC DeviceLink LUT8)':'DeviceRGB',deviceLink:link?{name:link.profile.name,tagType:link.profile.tagType,gridPoints:link.profile.gridPoints}:null,pdfxCandidate:state.exportOptions?.pdfxMode==='candidate'};}
export function exportProductionPdfV23(state){downloadBytes('boxstudio-v0.23-production-native.pdf',buildProductionPdfV23(state),'application/pdf');}
