import { materializeSvgMarkElement } from './svgMark.js';

function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function clamp(v,a=0,b=1){return Math.max(a,Math.min(b,v))}
function rot(p,cx,cy,deg=0){const a=num(deg)*Math.PI/180,co=Math.cos(a),si=Math.sin(a),dx=p[0]-cx,dy=p[1]-cy;return[cx+dx*co-dy*si,cy+dx*si+dy*co]}
function polyArea(p=[]){let a=0;for(let i=0;i<p.length;i++){const q=p[(i+1)%p.length];a+=p[i][0]*q[1]-q[0]*p[i][1]}return a/2}
function inside(p,a,b,sign){return ((b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]))*sign>=-1e-8}
function intersect(s,e,a,b){const x1=s[0],y1=s[1],x2=e[0],y2=e[1],x3=a[0],y3=a[1],x4=b[0],y4=b[1],d=(x1-x2)*(y3-y4)-(y1-y2)*(x3-x4);if(Math.abs(d)<1e-10)return e;const px=((x1*y2-y1*x2)*(x3-x4)-(x1-x2)*(x3*y4-y3*x4))/d,py=((x1*y2-y1*x2)*(y3-y4)-(y1-y2)*(x3*y4-y3*x4))/d;return[px,py]}
export function clipPolygonConvex(subject=[],clip=[]){if(subject.length<3||clip.length<3)return[];let out=subject.map(p=>[num(p[0]),num(p[1])]),sign=polyArea(clip)>=0?1:-1;for(let i=0;i<clip.length;i++){const a=clip[i],b=clip[(i+1)%clip.length],input=out;out=[];if(!input.length)break;let s=input[input.length-1];for(const e of input){const ein=inside(e,a,b,sign),sin=inside(s,a,b,sign);if(ein){if(!sin)out.push(intersect(s,e,a,b));out.push(e)}else if(sin)out.push(intersect(s,e,a,b));s=e}}return out}
function pointInTri(p,a,b,c){const s=(p1,p2,p3)=>(p1[0]-p3[0])*(p2[1]-p3[1])-(p2[0]-p3[0])*(p1[1]-p3[1]),d1=s(p,a,b),d2=s(p,b,c),d3=s(p,c,a),n=d1<0||d2<0||d3<0,pz=d1>0||d2>0||d3>0;return !(n&&pz)}
export function triangulateSimple(points=[]){const p=points.map(q=>[num(q[0]),num(q[1])]);if(p.length<3)return[];if(p.length===3)return[[...p]];const sign=polyArea(p)>=0?1:-1,idx=p.map((_,i)=>i),out=[];let guard=0;while(idx.length>3&&guard++<p.length*p.length*2){let cut=false;for(let k=0;k<idx.length;k++){const ia=idx[(k-1+idx.length)%idx.length],ib=idx[k],ic=idx[(k+1)%idx.length],a=p[ia],b=p[ib],c=p[ic],cross=((b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]))*sign;if(cross<=1e-9)continue;let hit=false;for(const j of idx){if(j===ia||j===ib||j===ic)continue;if(pointInTri(p[j],a,b,c)){hit=true;break}}if(hit)continue;out.push([a,b,c]);idx.splice(k,1);cut=true;break}if(!cut)break}if(idx.length===3)out.push([p[idx[0]],p[idx[1]],p[idx[2]]]);if(!out.length)for(let i=1;i<p.length-1;i++)out.push([p[0],p[i],p[i+1]]);return out}
function subdivideTri(t,depth){let tris=[t];for(let d=0;d<depth;d++){const next=[];for(const [a,b,c] of tris){const ab=[(a[0]+b[0])/2,(a[1]+b[1])/2],bc=[(b[0]+c[0])/2,(b[1]+c[1])/2],ca=[(c[0]+a[0])/2,(c[1]+a[1])/2];next.push([a,ab,ca],[ab,b,bc],[ca,bc,c],[ab,bc,ca])}tris=next}return tris}
function parseColor(c='#000'){const s=String(c||'#000').trim().toLowerCase(),named={black:'#000000',white:'#ffffff',red:'#ff0000',green:'#008000',blue:'#0000ff',yellow:'#ffff00',cyan:'#00ffff',magenta:'#ff00ff',gray:'#808080',grey:'#808080',orange:'#ffa500',purple:'#800080'};const v=named[s]||s;if(/^#([0-9a-f]{3})$/.test(v)){const m=v.slice(1);return[m[0]+m[0],m[1]+m[1],m[2]+m[2]].map(x=>parseInt(x,16)/255)}if(/^#([0-9a-f]{6})$/.test(v))return[1,3,5].map(i=>parseInt(v.slice(i,i+2),16)/255);const m=v.match(/^rgba?\(\s*([\d.]+)[, ]+([\d.]+)[, ]+([\d.]+)/);if(m)return[m[1],m[2],m[3]].map(x=>clamp(Number(x)/255));return[0,0,0]}
function toHex(rgb){return'#'+rgb.map(v=>Math.round(clamp(v)*255).toString(16).padStart(2,'0')).join('')}
function mix(a,b,t){return[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t]}
function colorAtStops(stops=[],t=0){const s=[...stops].sort((a,b)=>a.offset-b.offset);if(!s.length)return[0,0,0];t=clamp(t);if(t<=s[0].offset)return parseColor(s[0].color);for(let i=1;i<s.length;i++){if(t<=s[i].offset){const a=s[i-1],b=s[i],q=(t-a.offset)/Math.max(1e-9,b.offset-a.offset);return mix(parseColor(a.color),parseColor(b.color),q)}}return parseColor(s.at(-1).color)}
function len(v,size,origin=0){const s=String(v??'0').trim();if(s.endsWith('%'))return origin+(Number.isFinite(parseFloat(s))?parseFloat(s):0)*size/100;return origin+num(s)}
function bounds(points=[]){const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys),w:Math.max(.001,Math.max(...xs)-Math.min(...xs)),h:Math.max(.001,Math.max(...ys)-Math.min(...ys))}}
function gradientColor(g,p,b){if(!g)return[0,0,0];if(g.type==='linear'){const x1=len(g.x1,b.w,b.minX),y1=len(g.y1,b.h,b.minY),x2=len(g.x2,b.w,b.minX),y2=len(g.y2,b.h,b.minY),dx=x2-x1,dy=y2-y1,t=((p[0]-x1)*dx+(p[1]-y1)*dy)/Math.max(1e-9,dx*dx+dy*dy);return colorAtStops(g.stops,t)}const cx=len(g.cx,b.w,b.minX),cy=len(g.cy,b.h,b.minY),rr=Math.max(1e-9,len(g.r,Math.max(b.w,b.h),0));return colorAtStops(g.stops,Math.hypot(p[0]-cx,p[1]-cy)/rr)}
function transformPts(points,el,mark){const sx=num(el.w,mark.width)/Math.max(.001,num(mark.width,1)),sy=num(el.h,mark.height)/Math.max(.001,num(mark.height,1)),cx=num(el.x)+num(el.w)/2,cy=num(el.y)+num(el.h)/2;return points.map(p=>rot([num(el.x)+p[0]*sx,num(el.y)+p[1]*sy],cx,cy,el.r))}
function clipAgainstContainers(points,appearance,primitive,el,mark){let pieces=[points];for(const id of [primitive.clipId,primitive.maskId]){if(!id)continue;const polys=(primitive.clipId===id?appearance.clips?.[id]:appearance.masks?.[id])||[];if(!polys.length)continue;const clips=polys.flatMap(p=>triangulateSimple(transformPts(p,el,mark)));const next=[];for(const piece of pieces)for(const cp of clips){const q=clipPolygonConvex(piece,cp);if(q.length>=3)next.push(q)}pieces=next}return pieces}
export function materializeSvgAppearanceElement(element,{gradientDepth=2,preblendOpacity=true}={}){
  const mark=element?.svgMark,appearance=mark?.appearance;if(!appearance?.primitives?.length)return[];const out=[];
  for(let pi=0;pi<appearance.primitives.length;pi++){
    const primitive=appearance.primitives[pi],raw=transformPts(primitive.points||[],element,mark),pieces=clipAgainstContainers(raw,appearance,primitive,element,mark);
    for(const piece of pieces){if(piece.length<3)continue;const alpha=clamp(num(primitive.opacity,1));if(primitive.fill?.type==='solid'){let rgb=parseColor(primitive.fill.color);if(preblendOpacity&&alpha<1)rgb=mix([1,1,1],rgb,alpha);out.push({id:`${element.id}-fill-${pi}-${out.length}`,type:'production-polygon',group:'marks',panelId:element.panelId,points:piece,fillColor:toHex(rgb),opacity:preblendOpacity?1:alpha,appearanceSourceId:element.id});continue}
      const g=appearance.gradients?.[primitive.fill?.id],b=bounds(piece);for(const tri of triangulateSimple(piece).flatMap(t=>subdivideTri(t,Math.max(0,Math.min(3,gradientDepth))))){const c=[(tri[0][0]+tri[1][0]+tri[2][0])/3,(tri[0][1]+tri[1][1]+tri[2][1])/3];let rgb=gradientColor(g,c,b);if(preblendOpacity&&alpha<1)rgb=mix([1,1,1],rgb,alpha);out.push({id:`${element.id}-grad-${pi}-${out.length}`,type:'production-polygon',group:'marks',panelId:element.panelId,points:tri,fillColor:toHex(rgb),opacity:preblendOpacity?1:alpha,appearanceSourceId:element.id,gradientApproximation:true})}
    }
  }
  return out;
}
export function materializeSvgAppearanceState(state,{includeOutlines=true,gradientDepth=2}={}){const next=structuredClone(state||{}),elements=[];for(const el of next.elements||[]){if(el?.type!=='svg-symbol'){elements.push(el);continue}elements.push(...materializeSvgAppearanceElement(el,{gradientDepth}));if(includeOutlines)elements.push(...materializeSvgMarkElement(el))}next.elements=elements;return next}
export function productionAppearanceStats(state){let marks=0,primitives=0,gradients=0,warnings=0;for(const el of state?.elements||[]){const a=el?.type==='svg-symbol'?el.svgMark?.appearance:null;if(!a)continue;marks++;primitives+=a.primitives?.length||0;gradients+=new Set((a.primitives||[]).filter(p=>p.fill?.type==='gradient').map(p=>p.fill.id)).size;warnings+=a.warnings?.length||0}return{marks,primitives,gradients,warnings}}
export {parseColor,toHex};
