import {ARTWORK_CATALOG_V74,ARTWORK_CATALOG_V75,createArtworkV74} from './artworkLibraryV74.js';
import {FONTS_V74,fontOptionsV74,loadFontV74,fontTextSvgV74,fontGlyphIssuesV74} from './fontSystemV74.js';
import {standaloneMarkUiV67} from './standaloneMarkUiV67.js';
import {insertStandaloneMarkV67} from './standaloneMarksV67.js';
import {generateGeometry} from './geometry.js';
import {renderTemplate} from './variables.js';
import {iconV67} from './uiIconsV67.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const marks=()=>window.BoxStudioEditor.getState().page==='mark-studio';
const state=()=>marks()?standaloneMarkUiV67.getState():window.BoxStudioEditor.getState();
const commit=s=>marks()?standaloneMarkUiV67.commit(s):window.BoxStudioEditor.commitState(s);
function stored(key){try{const a=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(a)?a.filter(x=>typeof x==='string'):[];}catch{return [];}}
function save(key,rows){localStorage.setItem(key,JSON.stringify(rows));}
function modal(title,content){const d=document.createElement('dialog');d.className='v67-dialog v74-resource-dialog v75-resource-dialog';d.setAttribute('aria-label',title);d.innerHTML='<header><div><span class="v67-eyebrow">BOXSTUDIO · FREE RESOURCE LIBRARY</span><h2>'+title+'</h2></div><button data-v74-close aria-label="关闭窗口">'+iconV67('close')+'</button></header>'+content;document.body.append(d);const close=()=>{d.close();d.remove();};d.querySelector('[data-v74-close]').onclick=close;d.addEventListener('cancel',e=>{e.preventDefault();close();});d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d;}
export function openArtworkLibraryV75(){
 const initial=state(),inMarks=marks(),geo=inMarks?null:generateGeometry(initial.structure),panels=inMarks?[{id:'label',label:initial.activeMarkFaceV74==='side'?'侧唛':'正唛',w:initial.artboard.width,h:initial.artboard.height}]:geo.panels.filter(p=>p.kind==='panel'),selected=initial.elements.find(e=>e.id===initial.selectedId);
 let category='全部',page=0,collection='all';const limit=72,curated=new Set(ARTWORK_CATALOG_V74.map(r=>r.id)),catalog=[...ARTWORK_CATALOG_V75].sort((a,b)=>Number(curated.has(b.id))-Number(curated.has(a.id))),favoriteKey='boxstudio-v75-artwork-favorites',recentKey='boxstudio-v75-artwork-recent';
 const d=modal('包装素材库','<p class="v74-resource-intro">'+catalog.length+' 款 Lucide 原版矢量 · ISC 免费商用 · 可改色、缩放并导出原始曲线</p><div class="v74-resource-toolbar"><label>搜索素材<input data-v74-search type="search" placeholder="叶片、食品、礼品，或输入英文关键词"></label><label>插入到<select data-v74-panel>'+panels.map(p=>'<option value="'+esc(p.id)+'" '+(selected?.panelId===p.id?'selected':'')+'>'+esc(p.label)+'</option>').join('')+'</select></label><label>颜色<input data-v74-color type="color" value="'+(selected?.fillColor||'#111111')+'"></label></div><div class="v75-collections" role="group" aria-label="素材收藏"><button data-v75-collection="all" aria-pressed="true">全部素材</button><button data-v75-collection="favorites" aria-pressed="false">我的收藏</button><button data-v75-collection="recent" aria-pressed="false">最近使用</button></div><nav class="v74-resource-filter" aria-label="素材分类">'+['全部','自然','食品','护理','装饰','行业','数码','界面','其他'].map(c=>'<button data-v74-category="'+c+'" aria-pressed="'+(c==='全部')+'">'+c+'</button>').join('')+'</nav><div class="v74-asset-grid v75-asset-grid" data-v74-assets></div><div class="v75-pager"><button data-v75-prev>上一页</button><span data-v75-page aria-live="polite"></span><button data-v75-next>下一页</button></div><p role="status" data-v74-status></p><footer><span>Lucide 0.468.0 · 原始 SVG 与许可均自托管</span><a href="/assets/artwork-v75/LICENSE" target="_blank" rel="noopener">素材许可 ↗</a>'+(selected?.assetIdV74?'<button data-v74-recolor>应用颜色到所选素材</button>':'')+'</footer>');
 const status=t=>d.querySelector('[data-v74-status]').textContent=t;
 function render(){const query=d.querySelector('[data-v74-search]').value.trim().toLowerCase(),favorites=new Set(stored(favoriteKey)),recent=stored(recentKey);let rows=catalog.filter(t=>(category==='全部'||t.category===category)&&(t.label+' '+t.id+' '+t.category+' '+t.keywords.join(' ')).toLowerCase().includes(query)&&(collection==='all'||(collection==='favorites'?favorites.has(t.id):recent.includes(t.id))));if(collection==='recent')rows.sort((a,b)=>recent.indexOf(a.id)-recent.indexOf(b.id));page=Math.min(page,Math.max(0,Math.ceil(rows.length/limit)-1));
  d.querySelector('[data-v74-assets]').innerHTML=rows.slice(page*limit,(page+1)*limit).map(t=>'<article class="v75-asset-tile"><button data-v74-asset="'+t.id+'" aria-label="添加'+esc(t.label)+'"><img src="/assets/artwork-v75/'+t.id+'.svg" width="48" height="48" loading="lazy" alt=""><span>'+esc(t.label)+'</span></button><button class="v75-star" data-v75-favorite="'+t.id+'" aria-label="'+(favorites.has(t.id)?'取消收藏':'收藏')+esc(t.label)+'" aria-pressed="'+favorites.has(t.id)+'">'+(favorites.has(t.id)?'★':'☆')+'</button></article>').join('')||'<p class="v75-empty">'+(collection==='favorites'?'还没有收藏的素材。点击素材右上角星标，即可在这里找到。':'没有匹配的素材，请更换分类或关键词。')+'</p>';
  d.querySelector('[data-v75-page]').textContent=rows.length+' 款 · '+(rows.length?page+1:0)+' / '+Math.ceil(rows.length/limit)+' 页';d.querySelector('[data-v75-prev]').disabled=page===0;d.querySelector('[data-v75-next]').disabled=(page+1)*limit>=rows.length;
  for(const b of d.querySelectorAll('[data-v75-favorite]'))b.onclick=()=>{try{const id=b.dataset.v75Favorite;if(favorites.has(id))favorites.delete(id);else favorites.add(id);save(favoriteKey,[...favorites]);render();status(favorites.has(id)?'已收藏素材。':'已取消收藏。');}catch(e){status('收藏未保存：'+e.message);}};
  for(const b of d.querySelectorAll('[data-v74-asset]'))b.onclick=()=>{try{const next=state(),panel=panels.find(p=>p.id===d.querySelector('[data-v74-panel]').value);if(!panel)throw new Error('请选择有效印刷面。');const el=createArtworkV74(b.dataset.v74Asset,panel,{color:d.querySelector('[data-v74-color]').value});if(inMarks){const withSlot=insertStandaloneMarkV67(next,'fragile'),slot=withSlot.elements.findIndex(e=>e.id===withSlot.selectedId),position=withSlot.elements[slot];Object.assign(el,{x:position.x,y:position.y,w:position.w,h:position.h,group:'marks'});withSlot.elements[slot]=el;withSlot.selectedId=el.id;commit(withSlot);}else{next.elements.push(el);next.selectedId=el.id;commit(next);}status('已添加 '+el.name+'，可继续调整位置和尺寸。');try{save(recentKey,[el.assetIdV74,...stored(recentKey).filter(id=>id!==el.assetIdV74)].slice(0,80));}catch{status('素材已添加；最近使用记录未保存。');}}catch(e){status(e.message);}};
 }
 for(const b of d.querySelectorAll('[data-v74-category]'))b.onclick=()=>{category=b.dataset.v74Category;page=0;d.querySelectorAll('[data-v74-category]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));render();};
 for(const b of d.querySelectorAll('[data-v75-collection]'))b.onclick=()=>{collection=b.dataset.v75Collection;page=0;d.querySelectorAll('[data-v75-collection]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));render();};
 d.querySelector('[data-v74-search]').oninput=()=>{page=0;render();};d.querySelector('[data-v75-prev]').onclick=()=>{page--;render();d.querySelector('[data-v74-assets]').scrollTop=0;};d.querySelector('[data-v75-next]').onclick=()=>{page++;render();d.querySelector('[data-v74-assets]').scrollTop=0;};
 d.querySelector('[data-v74-recolor]')?.addEventListener('click',()=>{const next=state(),e=next.elements.find(e=>e.id===selected.id);if(!e||e.locked){status('请先选择并解锁该素材。');return;}e.fillColor=d.querySelector('[data-v74-color]').value;commit(next);status('所选素材颜色已更新。');});render();return d;
}
export function openFontLibraryV75(){
 const initial=state(),selected=initial.elements.find(e=>e.id===initial.selectedId),isText=selected&&['text','notice'].includes(selected.type);let filter='全部',token=0;
 const d=modal('免费字体库','<p class="v74-resource-intro">'+FONTS_V74.length+' 个真实字体家族 · 常规 / 粗体 · OFL 免费商用。中英字体覆盖 GB2312，拉丁字体适合品牌与数字排版。</p><div class="v75-font-toolbar"><label>搜索字体<input data-v75-font-search type="search" placeholder="字体名、中文、衬线…"></label><label>预览文字<input data-v75-font-sample value="PACKAGING / 2026" maxlength="80"></label><label>预览字重<select data-v75-font-weight><option value="400">400 常规</option><option value="700" '+(selected?.bold?'selected':'')+'>700 粗体</option></select></label></div><nav class="v74-resource-filter" aria-label="字体分类">'+['全部','中文','无衬线','衬线','展示','等宽'].map(c=>'<button data-v75-font-category="'+c+'" aria-pressed="'+(c==='全部')+'">'+c+'</button>').join('')+'</nav><div class="v75-font-grid" data-v75-font-grid></div><div class="v75-font-selection"><label>选中字体<select data-v74-font>'+fontOptionsV74(selected?.fontIdV74)+'</select></label><div class="v74-font-preview" data-v74-font-preview></div></div><p role="status" data-v74-status></p><footer><span>字形转曲用于 SVG / PDF 与 3D 贴图</span><button class="primary" data-v74-apply-font disabled>应用到当前文字</button></footer>');
 const bold=()=>d.querySelector('[data-v75-font-weight]').value==='700',sample=()=>d.querySelector('[data-v75-font-sample]').value,status=t=>d.querySelector('[data-v74-status]').textContent=t;
 function group(f){return f.id.endsWith('sc')?'中文':f.id==='mono'?'等宽':f.kind.includes('展示')?'展示':f.kind.includes('衬线')&&!f.kind.includes('无衬线')?'衬线':'无衬线';}
 function render(){const query=d.querySelector('[data-v75-font-search]').value.trim().toLowerCase(),id=d.querySelector('[data-v74-font]').value,rows=FONTS_V74.filter(f=>(filter==='全部'||group(f)===filter)&&(f.label+' '+f.name+' '+f.kind+' '+group(f)).toLowerCase().includes(query));d.querySelector('[data-v75-font-grid]').innerHTML=rows.map(f=>'<button data-v75-font-card="'+f.id+'" aria-pressed="'+(f.id===id)+'"><span class="v75-font-label">'+esc(f.label)+'<small>'+esc(group(f))+' · OFL</small></span><span class="v75-font-card-sample" data-v75-sample="'+f.id+'" style="font-family:&quot;'+f.name+'&quot;;font-weight:'+d.querySelector('[data-v75-font-weight]').value+'">加载字形…</span></button>').join('')||'<p class="v75-empty">没有匹配字体。</p>';
  for(const b of d.querySelectorAll('[data-v75-font-card]')){b.onclick=()=>{d.querySelector('[data-v74-font]').value=b.dataset.v75FontCard;render();preview();};const f=FONTS_V74.find(f=>f.id===b.dataset.v75FontCard),weight=bold();loadFontV74(f.id,weight).then(()=>{if(!b.isConnected)return;const text=sample(),issues=fontGlyphIssuesV74({fontIdV74:f.id,bold:weight},text);b.querySelector('[data-v75-sample]').textContent=issues.length?'PACKAGING / 2026':text||'Aa 0123';}).catch(()=>{if(b.isConnected)b.querySelector('[data-v75-sample]').textContent='加载失败，点击重试';});}
 }
 async function preview(){const current=++token,id=d.querySelector('[data-v74-font]').value,b=d.querySelector('[data-v74-apply-font]');b.disabled=true;status('正在准备字体…');try{await loadFontV74(id,bold());if(current!==token||!d.open)return;const text=sample(),el={fontIdV74:id,bold:bold(),fontSize:Math.min(10,220/Math.max(1,text.length))},issues=fontGlyphIssuesV74(el,text),actual=isText?fontGlyphIssuesV74(el,renderTemplate(selected.template,initial.variables)):[];d.querySelector('[data-v74-font-preview]').innerHTML=id&&!issues.length?'<svg viewBox="0 0 260 42" role="img" aria-label="真实字体轮廓预览">'+fontTextSvgV74(el,text,8,12)+'</svg>':'<p>'+esc(issues[0]||text)+'</p>';status(actual[0]||issues[0]||(isText?(selected.locked?'当前文字已锁定，请先解锁。':'字体已就绪，可应用到当前文字。'):'请先在画布或图层中选择文字对象。'));b.disabled=!isText||Boolean(selected.locked)||issues.length>0||actual.length>0;}catch(e){status(e.message);}}
 d.querySelector('[data-v74-font]').onchange=()=>{render();preview();};d.querySelector('[data-v75-font-search]').oninput=render;d.querySelector('[data-v75-font-sample]').oninput=()=>{render();preview();};d.querySelector('[data-v75-font-weight]').onchange=()=>{render();preview();};for(const b of d.querySelectorAll('[data-v75-font-category]'))b.onclick=()=>{filter=b.dataset.v75FontCategory;d.querySelectorAll('[data-v75-font-category]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));render();};
 d.querySelector('[data-v74-apply-font]').onclick=async()=>{const b=d.querySelector('[data-v74-apply-font]');b.disabled=true;try{const next=state(),e=next.elements.find(e=>e.id===selected.id),id=d.querySelector('[data-v74-font]').value;if(!e||e.locked)throw new Error('文字对象不存在或已锁定。');await loadFontV74(id,bold());const issues=fontGlyphIssuesV74({fontIdV74:id,bold:bold()},renderTemplate(e.template,next.variables));if(issues.length)throw new Error(issues[0]);e.fontIdV74=id;e.bold=bold();commit(next);d.close();}catch(e){status(e.message);b.disabled=false;}};render();preview();return d;
}
