import{FONTS_V74}from'./fontSystemV74.js';
export function installRichTextUiV77(form,draft,refresh){
 const section=document.createElement('fieldset');section.className='v77-rich-controls';section.innerHTML=`<legend>混合富文本 · 选中文字后应用</legend><p data-rich-selection>在上方文字内容中选中一段文字。</p><label>片段字体<select data-rich-font>${FONTS_V74.map(f=>`<option value="${f.id}">${f.label}</option>`).join('')}</select></label><div class="v76-fields"><label>片段字号 · mm<input data-rich-size type="number" min="1" max="80" step=".1" value="6"></label><label>片段颜色<input data-rich-color type="color" value="#315cda"></label></div><div class="v76-style-toggles">${[['bold','粗体'],['italic','斜体'],['underline','下划线'],['strike','删除线']].map(([k,label])=>`<label><input data-rich-style="${k}" type="checkbox">${label}</label>`).join('')}</div><div class="v77-rich-actions"><button type="button" data-rich-apply>应用到选中文字</button><button type="button" data-rich-clear>清除混合样式</button></div><small data-rich-count></small>`;
 form.querySelector('.v76-text-controls').append(section);const text=form.elements.template;let range=null,content=text.value;
 function count(){section.querySelector('[data-rich-count]').textContent=(draft.textRunsV77?.length||0)+' 个样式片段 · 同步矢量导出';}
 function select(){if(text.selectionEnd>text.selectionStart){range={start:text.selectionStart,end:text.selectionEnd};section.querySelector('[data-rich-selection]').textContent='已选：'+text.value.slice(range.start,range.end).slice(0,30);}}
 text.addEventListener('select',select);text.addEventListener('keyup',select);text.addEventListener('pointerup',select);text.addEventListener('input',()=>{if(text.value!==content){draft.textRunsV77=[];content=text.value;range=null;count();}});
 section.querySelector('[data-rich-apply]').onclick=()=>{try{select();if(!range)throw new Error('请先在文字内容中选中一段文字。');if(/\{\{/.test(text.value))throw new Error('运输变量文字使用统一样式。请用直接输入的文字编辑混合样式。');const run={...range,fontId:section.querySelector('[data-rich-font]').value,fontSize:Number(section.querySelector('[data-rich-size]').value),color:section.querySelector('[data-rich-color]').value};for(const input of section.querySelectorAll('[data-rich-style]'))run[input.dataset.richStyle]=input.checked;if(!Number.isFinite(run.fontSize)||run.fontSize<1||run.fontSize>80)throw new Error('片段字号必须为 1–80 mm。');const runs=[];for(const r of draft.textRunsV77||[]){if(r.end<=range.start||r.start>=range.end)runs.push(r);else{if(r.start<range.start)runs.push({...r,end:range.start});if(r.end>range.end)runs.push({...r,start:range.end});}}runs.push(run);draft.textRunsV77=runs.sort((a,b)=>a.start-b.start);form.elements.direction.value='horizontal';count();refresh();}catch(e){section.querySelector('[data-rich-selection]').textContent=e.message;}};
 section.querySelector('[data-rich-clear]').onclick=()=>{draft.textRunsV77=[];count();refresh();};count();
}
