import {glyphCommands} from './ttfOutline.js';
const fonts=new Map();export function registerRichFontV77(id,weight,font){fonts.set(id+'-'+weight,font);}
export function validateRichRunsV77(runs,text){if(!Array.isArray(runs)||runs.length>80||typeof text!=='string')throw new Error('富文本片段无效。');let previous=0;for(const r of runs){if(!Number.isInteger(r.start)||!Number.isInteger(r.end)||r.start<previous||r.end<=r.start||r.end>text.length||typeof r.fontId!=='string'||![true,false].includes(r.bold)||!Number.isFinite(r.fontSize)||r.fontSize<1||r.fontSize>80||!/^#[0-9a-f]{6}$/i.test(r.color)||['italic','underline','strike'].some(k=>typeof r[k]!=='boolean'))throw new Error('富文本范围、字体或样式无效。');previous=r.end;}return runs;}
const shift=(commands,x,y)=>commands.map(c=>{const n={...c};for(const[a,b]of[['x','y'],['cx','cy'],['c1x','c1y'],['c2x','c2y']])if(a in c){n[a]+=x;n[b]+=y;}return n;});
const rectangle=(x,y,w,h)=>[{op:'M',x,y},{op:'L',x:x+w,y},{op:'L',x:x+w,y:y+h},{op:'L',x,y:y+h},{op:'Z'}];
function bounds(commands){const xs=[],ys=[];for(const c of commands)for(const[x,y]of[['x','y'],['cx','cy'],['c1x','c1y'],['c2x','c2y']])if(x in c){xs.push(c[x]);ys.push(c[y]);}return xs.length?{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}:{minX:0,maxX:0,minY:0,maxY:0,w:0,h:0};}
export function layoutRichTextV77(font,text,el,s){
 validateRichRunsV77(el.textRunsV77,text);if(s.direction!=='horizontal')throw new Error('混合富文本使用横向排版，请先切换排版方向。');if(/\{\{/.test(el.template||''))throw new Error('混合富文本请使用直接输入的文字。运输变量文字使用统一样式。');if(text.length>3000)throw new Error('文字最多支持 3000 字符。');const w=Number(el.w),h=Number(el.h),available=w-6;if(![w,h].every(n=>Number.isFinite(n)&&n>=4&&n<=1500))throw new Error('文字框尺寸无效。');
 let rows=[],row={tokens:[],width:0,fs:Number(el.fontSize||5),soft:false},offset=0;for(const char of [...text]){const run=el.textRunsV77.find(r=>offset>=r.start&&offset<r.end);offset+=char.length;const style=run||{fontId:el.fontIdV74,fontSize:el.fontSize||5,bold:el.bold||false,...s};if(char==='\n'){rows.push(row);row={tokens:[],width:0,fs:el.fontSize||5,soft:false};continue;}const f=run?fonts.get(run.fontId+'-'+(run.bold?700:400)):font;if(!f)throw new Error('富文本字体尚未加载。');const id=f.cmap(char.codePointAt(0));if(char.codePointAt(0)>32&&!id)throw new Error('所选字体缺少字符：'+char);const scale=style.fontSize/f.unitsPerEm,advance=Math.max(.05*style.fontSize,(f.advance[id]||f.unitsPerEm*.5)*scale+s.letterSpacing);if(s.wrap&&row.tokens.length&&row.width+advance-s.letterSpacing>available){row.soft=true;rows.push(row);row={tokens:[],width:0,fs:style.fontSize,soft:false};}row.tokens.push({char,id,f,style,scale,advance});row.width+=advance;row.fs=Math.max(row.fs,style.fontSize);}rows.push(row);
 let baseline=0,paintRuns=[],lines=[];for(const row of rows){baseline+=row.fs;const width=Math.max(0,row.width-s.letterSpacing),start=3+(s.align==='center'?(available-width)/2:s.align==='right'?available-width:0),spaces=row.tokens.filter(t=>t.char===' ').length,extra=s.align==='justify'&&row.soft&&spaces?(available-width)/spaces:0;let x=start;for(const t of row.tokens){const {style,scale}=t,slant=style.italic?Math.tan(13*Math.PI/180):0,commands=glyphCommands(t.f,t.id).map(c=>{const n={...c};for(const[a,b]of[['x','y'],['cx','cy'],['c1x','c1y'],['c2x','c2y']])if(a in c){n[a]=x+(c[a]+c[b]*slant)*scale;n[b]=baseline-c[b]*scale;}return n;});const width=Math.max(.01,t.advance-s.letterSpacing),thickness=Math.max(.12,style.fontSize*.055);if(style.underline)commands.push(...rectangle(x,baseline+style.fontSize*.1,width,thickness));if(style.strike)commands.push(...rectangle(x,baseline-style.fontSize*.32,width,thickness));paintRuns.push({commands,color:style.color,fontId:style.fontId});x+=t.advance+(t.char===' '?extra:0);}lines.push({x:start,y:baseline,width,text:row.tokens.map(t=>t.char).join('')});baseline+=row.fs*(s.lineHeight-1);}
 const b=bounds(paintRuns.flatMap(r=>r.commands)),dy=(s.verticalAlign==='center'?(h-b.h)/2:s.verticalAlign==='bottom'?h-b.h:0)-b.minY;paintRuns=paintRuns.map(r=>({...r,commands:shift(r.commands,0,dy)}));const commands=paintRuns.flatMap(r=>r.commands),bb=bounds(commands);return{commands,paintRuns,bounds:bb,runs:lines,lines:rows.length,color:s.color,style:s,overflow:bb.minX<-.01||bb.minY<-.01||bb.maxX>w+.01||bb.maxY>h+.01};
}
