import {paperAppearanceV77} from './paperMaterialsV77.js';
import {loadBackdropV75,paintBackdropV75} from './backdropV75.js';
import {studioSettingsV75} from './studioConfigV75.js';
import {lightingSettingsV74,loadPhysicalStudioV74,physicalStudioReadyV74,renderPhysicalStudioV74} from './studioLightingV74.js';
import {prepareFontsV74} from './fontSystemV74.js';
import {foldedMeshesV71,artworkTexturesV71} from './threeExportV71.js';

export const SCENES_V71=Object.freeze({paper:{label:'自然白底',background:'#f4f5f7',light:.28},warm:{label:'暖调棚拍',background:'#ede6dc',light:.4},sage:{label:'鼠尾草绿',background:'#dfe6dd',light:.3},rose:{label:'柔粉纸品',background:'#efdddd',light:.28},sand:{label:'沙色展台',background:'#e8ddcb',light:.3},blue:{label:'冷灰蓝棚',background:'#dce5ed',light:.28},dark:{label:'深色棚拍',background:'#202733',light:.32},transparent:{label:'透明背景',background:null,light:.22}});
export function scenePointV71(meshes,point){const p=point.map((v,i)=>v-meshes.center[i]);return meshes.upAxis==='Z'?[p[0],-p[2],p[1]]:p;}
export function sceneSettingsV71(input={}){const preset=Object.hasOwn(SCENES_V71,input.preset)?input.preset:'paper',clamp=(v,a,b,d)=>Number.isFinite(Number(v))?Math.min(b,Math.max(a,Number(v))):d;return{...lightingSettingsV74(input),...studioSettingsV75(input),preset,...SCENES_V71[preset],...(preset==='transparent'?{backgroundImage:''}:{}),...(input.background&&/^#[0-9a-f]{6}$/i.test(input.background)?{background:input.background}:{}),yaw:clamp(input.yaw,-Math.PI*2,Math.PI*2,.6),pitch:clamp(input.pitch,-1.5,1.5,.45),zoom:clamp(input.zoom,.3,3,1),shadow:input.shadow!==false,contrast:clamp(input.contrast,.5,1.8,1.08)};}
function affine(src,dst){const[x0,y0]=src[0],[x1,y1]=src[1],[x2,y2]=src[2],[X0,Y0]=dst[0],[X1,Y1]=dst[1],[X2,Y2]=dst[2],det=x0*(y1-y2)+x1*(y2-y0)+x2*(y0-y1);if(Math.abs(det)<1e-9)return null;return[(X0*(y1-y2)+X1*(y2-y0)+X2*(y0-y1))/det,(Y0*(y1-y2)+Y1*(y2-y0)+Y2*(y0-y1))/det,(X0*(x2-x1)+X1*(x0-x2)+X2*(x1-x0))/det,(Y0*(x2-x1)+Y1*(x0-x2)+Y2*(x1-x0))/det,(X0*(x1*y2-x2*y1)+X1*(x2*y0-x0*y2)+X2*(x0*y1-x1*y0))/det,(Y0*(x1*y2-x2*y1)+Y1*(x2*y0-x0*y2)+Y2*(x0*y1-x1*y0))/det];}
export function renderSceneV71(meshes,textures,settings={},width=1600,height=1200,canvasTarget=null){
 width=Math.min(4096,Math.max(320,Math.round(width)));height=Math.min(4096,Math.max(240,Math.round(height)));const s=sceneSettingsV71(settings);if(physicalStudioReadyV74())try{return renderPhysicalStudioV74(meshes,textures,s,width,height,canvasTarget);}catch(error){console.warn('摄影棚 WebGL 不可用，使用兼容渲染：',error.message);}const canvas=canvasTarget||document.createElement('canvas');if(canvas.width!==width)canvas.width=width;if(canvas.height!==height)canvas.height=height;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,width,height);if(s.background){ctx.fillStyle=s.background;ctx.fillRect(0,0,width,height);}paintBackdropV75(ctx,s.backgroundImage,width,height);
 const view=q=>{const p=scenePointV71(meshes,q),cy=Math.cos(s.yaw),sy=Math.sin(s.yaw),cx=Math.cos(s.pitch),sx=Math.sin(s.pitch),x=cy*p[0]-sy*p[2],z=sy*p[0]+cy*p[2];return[x,cx*p[1]-sx*z,sx*p[1]+cx*z];};
 const distance=Math.max(1,meshes.span)*3,scale=Math.min(width,height)*.68/Math.max(1,meshes.span)*s.zoom*(Math.tan(32*Math.PI/360)/Math.tan(s.fov*Math.PI/360)),project=q=>{const v=view(q),k=s.projection==='orthographic'?1:distance/(distance-v[2]);return[width/2+v[0]*scale*k,height/2-v[1]*scale*k];};
 if(s.shadow&&s.background){ctx.save();ctx.fillStyle='rgba(22,29,42,.12)';ctx.filter=`blur(${Math.max(4,width*.018)}px)`;ctx.beginPath();ctx.ellipse(width/2,height*.79,width*.22,height*.035,0,0,Math.PI*2);ctx.fill();ctx.restore();}
 const draw=meshes.panels.map(p=>({p,points:p.points.map(project),z:p.points.reduce((a,q)=>a+view(q)[2],0)/p.points.length})).sort((a,b)=>a.z-b.z);
 for(const{p,points}of draw){const outside=points.reduce((a,q,i)=>{const r=points[(i+1)%points.length];return a+q[0]*r[1]-r[0]*q[1];},0)>0;ctx.beginPath();points.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.closePath();ctx.fillStyle=meshes.innerColor||'#c7b799';ctx.fill();const texture=textures.get(p.nodeId);if(outside)for(const tri of p.uvMap.triangles){const dst=tri.map(i=>points[i]),src=tri.map(i=>[p.uvMap.uv[i][0]*texture.width,p.uvMap.uv[i][1]*texture.height]),m=affine(src,dst);if(!m)continue;ctx.save();ctx.beginPath();dst.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.closePath();ctx.clip();ctx.setTransform(...m);ctx.filter=`contrast(${s.contrast})`;ctx.drawImage(texture,0,0);ctx.restore();}
  ctx.beginPath();points.forEach((v,i)=>i?ctx.lineTo(...v):ctx.moveTo(...v));ctx.closePath();const shade=(1-Math.abs(p.normal[0]*.6+p.normal[1]*.7+p.normal[2]*.4))*s.light;ctx.fillStyle=`rgba(20,27,36,${Math.max(0,Math.min(.35,shade))})`;ctx.fill();ctx.strokeStyle='rgba(47,44,39,.35)';ctx.lineWidth=Math.max(.6,width/1600);ctx.stroke();
 }canvas.dataset.renderer='software2d';return canvas;
}
export async function prepareSceneV71(state,geo,graph,options={}){await prepareFontsV74(state);await loadBackdropV75(state.sceneV71?.backgroundImage);await loadPhysicalStudioV74();const paper=paperAppearanceV77(state.structure),meshes={...foldedMeshesV71(state,geo,graph,options),innerColor:paper.inner,thicknessMm:state.structure?.thickness||paper.thickness},textures=await artworkTexturesV71(meshes,{background:paper.face,...options});return{meshes,textures,render:(settings,width,height)=>renderSceneV71(meshes,textures,settings,width,height)};}
