const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clone=v=>structuredClone(v);
function bounds(elements=[]){if(!elements.length)return{x:0,y:0,w:0,h:0};const xs=elements.flatMap(e=>[num(e.x),num(e.x)+num(e.w)]),ys=elements.flatMap(e=>[num(e.y),num(e.y)+num(e.h)]),x=Math.min(...xs),y=Math.min(...ys),r=Math.max(...xs),b=Math.max(...ys);return{x,y,w:r-x,h:b-y};}
function angleDelta(a,b){let d=(num(b)-num(a))%360;if(d>180)d-=360;if(d<-180)d+=360;return d;}
function id(){return`guide-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}
export function normalizeUserGuidesV26(guides=[]){return(Array.isArray(guides)?guides:[]).map(g=>({id:String(g?.id||id()),axis:g?.axis==='y'?'y':'x',value:num(g?.value),label:String(g?.label||'User guide'),locked:Boolean(g?.locked)}));}
export function addUserGuideV26(state,axis,value,{label='User guide',locked=false}={}){const next=clone(state||{}),guides=normalizeUserGuidesV26(next.userGuides);guides.push({id:id(),axis:axis==='y'?'y':'x',value:num(value),label:String(label||'User guide'),locked:Boolean(locked)});next.userGuides=guides;return next;}
export function updateUserGuideV26(state,guideId,patch={}){const next=clone(state||{});next.userGuides=normalizeUserGuidesV26(next.userGuides).map(g=>g.id===guideId?{...g,axis:patch.axis==='y'?'y':patch.axis==='x'?'x':g.axis,value:patch.value==null?g.value:num(patch.value),label:patch.label==null?g.label:String(patch.label),locked:patch.locked==null?g.locked:Boolean(patch.locked)}:g);return next;}
export function removeUserGuideV26(state,guideId){const next=clone(state||{});next.userGuides=normalizeUserGuidesV26(next.userGuides).filter(g=>g.id!==guideId);return next;}
export function userGuideSnapV26(state,ids,dx,dy,{enabled=true,toleranceMm=3}={}){const selected=(state?.elements||[]).filter(e=>ids.includes(e.id)&&e.type==='cross-panel-artwork'),guides=normalizeUserGuidesV26(state?.userGuides),tol=Math.max(0,num(toleranceMm,3));if(!enabled||!selected.length||!guides.length)return{dx:num(dx),dy:num(dy),guides:[]};const b=bounds(selected),moving={x:b.x+num(dx),y:b.y+num(dy),w:b.w,h:b.h},xAnch=[moving.x,moving.x+moving.w/2,moving.x+moving.w],yAnch=[moving.y,moving.y+moving.h/2,moving.y+moving.h];let bx=null,by=null;for(const g of guides){const anchors=g.axis==='x'?xAnch:yAnch;for(const a of anchors){const adjust=g.value-a;if(Math.abs(adjust)>tol)continue;const candidate={adjust,guide:g};if(g.axis==='x'){if(!bx||Math.abs(adjust)<Math.abs(bx.adjust))bx=candidate;}else if(!by||Math.abs(adjust)<Math.abs(by.adjust))by=candidate;}}
  const out=[];let ndx=num(dx),ndy=num(dy);if(bx){ndx+=bx.adjust;out.push({kind:'user-guide',axis:'x',value:bx.guide.value,guideId:bx.guide.id,label:bx.guide.label});}if(by){ndy+=by.adjust;out.push({kind:'user-guide',axis:'y',value:by.guide.value,guideId:by.guide.id,label:by.guide.label});}return{dx:ndx,dy:ndy,guides:out};}
export function textBaselinesV26(state,geo){const out=[];for(const el of state?.elements||[]){if(!['text','notice'].includes(el?.type))continue;const panel=geo?.panelMap?.[el.panelId];if(!panel)continue;const size=Math.max(.1,num(el.fontSize,4.5)),lines=Math.max(1,String(el.template||'').split('\n').length),top=num(panel.y)+num(el.y);for(let i=0;i<lines;i++)out.push({id:el.id,line:i,value:top+(i+1)*size*1.15,label:`${el.id} baseline ${i+1}`});}return out;}
export function textBaselineSnapV26(state,ids,dx,dy,geo,{enabled=true,toleranceMm=3}={}){const selected=(state?.elements||[]).filter(e=>ids.includes(e.id)&&e.type==='cross-panel-artwork'),tol=Math.max(0,num(toleranceMm,3));if(!enabled||!selected.length)return{dx:num(dx),dy:num(dy),guides:[]};const b=bounds(selected),moving={y:b.y+num(dy),h:b.h},anchors=[moving.y,moving.y+moving.h/2,moving.y+moving.h];let best=null;for(const baseline of textBaselinesV26(state,geo))for(const a of anchors){const adjust=baseline.value-a;if(Math.abs(adjust)>tol)continue;if(!best||Math.abs(adjust)<Math.abs(best.adjust))best={adjust,baseline};}if(!best)return{dx:num(dx),dy:num(dy),guides:[]};return{dx:num(dx),dy:num(dy)+best.adjust,guides:[{kind:'text-baseline',axis:'y',value:best.baseline.value,targetId:best.baseline.id,label:best.baseline.label}]};}
export function smartRotationV26(state,id,rawAngle,{enabled=true,toleranceDeg=3,step=15,includeOrthogonal=true}={}){const raw=num(rawAngle),tol=Math.max(0,num(toleranceDeg,3)),candidates=[];if(!enabled)return{angle:raw,guides:[]};const gridStep=Math.max(.1,num(step,15)),grid=Math.round(raw/gridStep)*gridStep;candidates.push({angle:grid,kind:'rotation-grid',label:`${grid.toFixed(1)}°`});for(const el of state?.elements||[]){if(el?.type!=='cross-panel-artwork'||el.id===id)continue;const base=num(el.r);candidates.push({angle:base,kind:'rotation-match',targetId:el.id,label:`match ${el.id} ${base.toFixed(1)}°`});if(includeOrthogonal)for(const off of [90,180,270])candidates.push({angle:base+off,kind:'rotation-axis',targetId:el.id,label:`${el.id} + ${off}°`});}
  let best=null;for(const c of candidates){const d=angleDelta(raw,c.angle);if(Math.abs(d)>tol)continue;if(!best||Math.abs(d)<Math.abs(best.delta))best={...c,delta:d};}if(!best)return{angle:raw,guides:[]};return{angle:raw+best.delta,guides:[{kind:best.kind,axis:'angle',value:raw+best.delta,targetId:best.targetId||null,label:best.label}]};}
export function smartGuideDiagnosticsV26(state,geo){return{userGuides:normalizeUserGuidesV26(state?.userGuides).length,textBaselines:textBaselinesV26(state,geo).length,rotationTargets:(state?.elements||[]).filter(e=>e?.type==='cross-panel-artwork').length};}
