const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
function bounds(elements=[]){if(!elements.length)return{x:0,y:0,w:0,h:0};const xs=elements.flatMap(e=>[num(e.x),num(e.x)+num(e.w)]),ys=elements.flatMap(e=>[num(e.y),num(e.y)+num(e.h)]),x=Math.min(...xs),y=Math.min(...ys),r=Math.max(...xs),b=Math.max(...ys);return{x,y,w:r-x,h:b-y};}
function xAnchors(b){return[{name:'left',value:b.x},{name:'center',value:b.x+b.w/2},{name:'right',value:b.x+b.w}];}
function yAnchors(b){return[{name:'top',value:b.y},{name:'middle',value:b.y+b.h/2},{name:'bottom',value:b.y+b.h}];}
function candidate(axis,movingAnchor,targetAnchor,targetId){return{axis,adjust:targetAnchor.value-movingAnchor.value,value:targetAnchor.value,movingEdge:movingAnchor.name,targetEdge:targetAnchor.name,targetId};}
function bestCandidate(candidates,tolerance){let best=null;for(const c of candidates){if(Math.abs(c.adjust)>tolerance)continue;if(!best||Math.abs(c.adjust)<Math.abs(best.adjust)-1e-9)best=c;else if(best&&Math.abs(Math.abs(c.adjust)-Math.abs(best.adjust))<1e-9){const sameName=c.movingEdge===c.targetEdge,bestSame=best.movingEdge===best.targetEdge;if(sameName&&!bestSame)best=c;}}return best;}
export function smartAlignmentDeltaV25(state,ids,dx,dy,{enabled=true,toleranceMm=3}={}){if(!enabled)return{dx:num(dx),dy:num(dy),guides:[]};const selected=(state?.elements||[]).filter(e=>ids.includes(e.id)&&e.type==='cross-panel-artwork'),others=(state?.elements||[]).filter(e=>!ids.includes(e.id)&&e.type==='cross-panel-artwork');if(!selected.length||!others.length)return{dx:num(dx),dy:num(dy),guides:[]};const base=bounds(selected),moving={x:base.x+num(dx),y:base.y+num(dy),w:base.w,h:base.h},tol=Math.max(0,num(toleranceMm,3)),xc=[],yc=[];for(const e of others){const b=bounds([e]);for(const ma of xAnchors(moving))for(const ta of xAnchors(b))xc.push(candidate('x',ma,ta,e.id));for(const ma of yAnchors(moving))for(const ta of yAnchors(b))yc.push(candidate('y',ma,ta,e.id));}
  const bx=bestCandidate(xc,tol),by=bestCandidate(yc,tol),guides=[];let ndx=num(dx),ndy=num(dy);if(bx){ndx+=bx.adjust;guides.push({kind:'object-align',axis:'x',value:bx.value,targetId:bx.targetId,movingEdge:bx.movingEdge,targetEdge:bx.targetEdge,label:`${bx.movingEdge} ↔ ${bx.targetEdge}`});}if(by){ndy+=by.adjust;guides.push({kind:'object-align',axis:'y',value:by.value,targetId:by.targetId,movingEdge:by.movingEdge,targetEdge:by.targetEdge,label:`${by.movingEdge} ↔ ${by.targetEdge}`});}return{dx:ndx,dy:ndy,guides};}
export function smartSizeMatchV25(state,id,width,height,{enabled=true,toleranceMm=3,lockAspect=false}={}){const el=(state?.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork');if(!enabled||!el)return{width:num(width),height:num(height),guides:[]};const others=(state?.elements||[]).filter(e=>e.id!==id&&e.type==='cross-panel-artwork'),tol=Math.max(0,num(toleranceMm,3)),w=Math.max(.1,num(width)),h=Math.max(.1,num(height)),ratio=Math.max(.001,num(el.w,1))/Math.max(.001,num(el.h,1));let bestW=null,bestH=null;for(const other of others){const dw=num(other.w)-w,dh=num(other.h)-h;if(Math.abs(dw)<=tol&&(!bestW||Math.abs(dw)<Math.abs(bestW.adjust)))bestW={adjust:dw,targetId:other.id,value:num(other.w)};if(Math.abs(dh)<=tol&&(!bestH||Math.abs(dh)<Math.abs(bestH.adjust)))bestH={adjust:dh,targetId:other.id,value:num(other.h)};}
  if(lockAspect&&bestW&&bestH){if(Math.abs(bestW.adjust)<=Math.abs(bestH.adjust))return{width:bestW.value,height:bestW.value/ratio,guides:[{kind:'size-match',axis:'x',value:bestW.value,targetId:bestW.targetId,label:`match width ${bestW.value.toFixed(1)} mm`}]} ;return{width:bestH.value*ratio,height:bestH.value,guides:[{kind:'size-match',axis:'y',value:bestH.value,targetId:bestH.targetId,label:`match height ${bestH.value.toFixed(1)} mm`}]} ;}
  let nw=w,nh=h;const guides=[];if(bestW){nw=bestW.value;guides.push({kind:'size-match',axis:'x',value:nw,targetId:bestW.targetId,label:`match width ${nw.toFixed(1)} mm`});}if(bestH){nh=bestH.value;guides.push({kind:'size-match',axis:'y',value:nh,targetId:bestH.targetId,label:`match height ${nh.toFixed(1)} mm`});}return{width:nw,height:nh,guides};}
export function smartGuideDiagnosticsV25(state,ids,dx=0,dy=0,options={}){const r=smartAlignmentDeltaV25(state,ids,dx,dy,options);return{selection:ids.length,dx:r.dx,dy:r.dy,guideCount:r.guides.length,guides:r.guides};}
