const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
function box(elements=[]){if(!elements.length)return{x:0,y:0,w:0,h:0};const xs=elements.flatMap(e=>[num(e.x),num(e.x)+num(e.w)]),ys=elements.flatMap(e=>[num(e.y),num(e.y)+num(e.h)]);const x=Math.min(...xs),y=Math.min(...ys),r=Math.max(...xs),b=Math.max(...ys);return{x,y,w:r-x,h:b-y};}
function overlap(a0,a1,b0,b1){return Math.min(a1,b1)-Math.max(a0,b0)>0;}
function nearestHorizontal(moving,others){let left=null,right=null;for(const e of others){const b={x:num(e.x),y:num(e.y),w:num(e.w),h:num(e.h)};if(!overlap(moving.y,moving.y+moving.h,b.y,b.y+b.h))continue;const br=b.x+b.w,mr=moving.x+moving.w;if(br<=moving.x&&(!left||br>left.edge))left={id:e.id,edge:br,box:b};if(b.x>=mr&&(!right||b.x<right.edge))right={id:e.id,edge:b.x,box:b};}return{left,right};}
function nearestVertical(moving,others){let top=null,bottom=null;for(const e of others){const b={x:num(e.x),y:num(e.y),w:num(e.w),h:num(e.h)};if(!overlap(moving.x,moving.x+moving.w,b.x,b.x+b.w))continue;const bb=b.y+b.h,mb=moving.y+moving.h;if(bb<=moving.y&&(!top||bb>top.edge))top={id:e.id,edge:bb,box:b};if(b.y>=mb&&(!bottom||b.y<bottom.edge))bottom={id:e.id,edge:b.y,box:b};}return{top,bottom};}
export function smartSpacingDelta(state,ids,dx,dy,{enabled=true,toleranceMm=3}={}){if(!enabled)return{dx,dy,guides:[]};const selected=(state?.elements||[]).filter(e=>ids.includes(e.id)&&e.type==='cross-panel-artwork'),others=(state?.elements||[]).filter(e=>!ids.includes(e.id)&&e.type==='cross-panel-artwork');if(!selected.length||!others.length)return{dx,dy,guides:[]};const base=box(selected),moving={x:base.x+num(dx),y:base.y+num(dy),w:base.w,h:base.h},tol=Math.max(0,num(toleranceMm,3)),guides=[];let ndx=num(dx),ndy=num(dy);
  const h=nearestHorizontal(moving,others);if(h.left&&h.right){const gapL=moving.x-h.left.edge,gapR=h.right.edge-(moving.x+moving.w),adjust=(gapR-gapL)/2;if(Math.abs(adjust)<=tol){ndx+=adjust;guides.push({kind:'spacing',axis:'x',gap:(gapL+gapR)/2,leftId:h.left.id,rightId:h.right.id,value:moving.y+moving.h/2});}}
  const shifted={...moving,x:base.x+ndx};const v=nearestVertical(shifted,others);if(v.top&&v.bottom){const gapT=shifted.y-v.top.edge,gapB=v.bottom.edge-(shifted.y+shifted.h),adjust=(gapB-gapT)/2;if(Math.abs(adjust)<=tol){ndy+=adjust;guides.push({kind:'spacing',axis:'y',gap:(gapT+gapB)/2,topId:v.top.id,bottomId:v.bottom.id,value:shifted.x+shifted.w/2});}}
  return{dx:ndx,dy:ndy,guides};}
export function applySmartSpacingToTranslation(state,ids,translation,{enabled=true,toleranceMm=3}={}){const d=translation?.delta||translation||{x:0,y:0},r=smartSpacingDelta(state,ids,num(d.x),num(d.y),{enabled,toleranceMm});const next=structuredClone(state||{});for(const el of next.elements||[])if(ids.includes(el.id)&&el.type==='cross-panel-artwork'){el.x=num(el.x)+r.dx;el.y=num(el.y)+r.dy;}return{state:next,delta:{x:r.dx,y:r.dy},guides:r.guides};}
