import { generateGeometry } from './geometry.js';
import { buildFoldGraph } from './foldgraph.js';
import { dielineDocumentFromStateV38, geometryFromDielineDocumentV38, buildProductionZonesV38 } from './dielineCadV38.js';
import { flattenCurves } from './importDieline.js';

export const V39_TOPOLOGY_SCHEMA='boxstudio-structural-topology-v39';
const clone=v=>structuredClone(v);
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const r=(v,p=6)=>{const m=10**p;return Math.round(n(v)*m)/m};
const pkey=(p,t)=>`${Math.round(n(p.x)/t)}:${Math.round(n(p.y)/t)}`;
const pair=(a,b)=>a<b?`${a}|${b}`:`${b}|${a}`;
const segKey=(a,b,t)=>{const x=pkey(a,t),y=pkey(b,t);return x<y?`${x}|${y}`:`${y}|${x}`};
const area=pts=>pts.reduce((s,p,i)=>{const q=pts[(i+1)%pts.length];return s+p[0]*q[1]-q[0]*p[1]},0)/2;
const cross=(ax,ay,bx,by)=>ax*by-ay*bx;
function box(points){const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),x=Math.min(...xs),y=Math.min(...ys),x2=Math.max(...xs),y2=Math.max(...ys);return{x:r(x),y:r(y),w:r(x2-x),h:r(y2-y)}}
function center(points){const a=area(points);if(Math.abs(a)<1e-9){const b=box(points);return{x:b.x+b.w/2,y:b.y+b.h/2}}let x=0,y=0;for(let i=0;i<points.length;i++){const p=points[i],q=points[(i+1)%points.length],c=p[0]*q[1]-q[0]*p[1];x+=(p[0]+q[0])*c;y+=(p[1]+q[1])*c}return{x:x/(6*a),y:y/(6*a)}}
function polyOf(panel){if(Array.isArray(panel?.points)&&panel.points.length>=3)return panel.points.map(q=>[n(q[0]),n(q[1])]);const x=n(panel?.x),y=n(panel?.y),w=n(panel?.w),h=n(panel?.h);return[[x,y],[x+w,y],[x+w,y+h],[x,y+h]]}
function inside(pt,poly){let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if(((a[1]>pt.y)!=(b[1]>pt.y))&&(pt.x<(b[0]-a[0])*(pt.y-a[1])/((b[1]-a[1])||1e-12)+a[0]))yes=!yes}return yes}
function problem(severity,code,detail,extra={}){return{severity,code,detail,...extra}}

function sampleEdge(doc,edge,steps){const nodes=new Map((doc.nodes||[]).map(x=>[x.id,x])),a=nodes.get(edge.a),b=nodes.get(edge.b);if(!a||!b)return[];if(!edge.curve||edge.curve==='line')return[{a:{x:n(a.x),y:n(a.y)},b:{x:n(b.x),y:n(b.y)}}];const raw=edge.curve==='cubic'?{type:'C',kind:edge.lineType,x1:a.x,y1:a.y,c1x:edge.c1?.x,c1y:edge.c1?.y,c2x:edge.c2?.x,c2y:edge.c2?.y,x2:b.x,y2:b.y}:{type:'A',kind:edge.lineType,x1:a.x,y1:a.y,...edge.arc,largeArc:edge.arc?.largeArc?1:0,sweep:edge.arc?.sweep?1:0,x2:b.x,y2:b.y};return flattenCurves([raw],Math.max(4,steps)).map(s=>({a:{x:n(s.x1),y:n(s.y1)},b:{x:n(s.x2),y:n(s.y2)}}))}
function rawSegments(doc,steps,tol){const out=[],issues=[];for(const e of doc.edges||[]){if(!['CUT','CREASE'].includes(e.lineType))continue;const list=sampleEdge(doc,e,steps);if(!list.length){issues.push(problem('error','TOPOLOGY_EDGE_EMPTY',`Edge ${e.id} could not be sampled.`,{edgeId:e.id}));continue}for(const s of list)if(Math.hypot(s.b.x-s.a.x,s.b.y-s.a.y)>tol)out.push({...s,lineType:e.lineType,sourceEdgeId:e.id,curved:e.curve&&e.curve!=='line'})}return{segments:out,issues}}
function addT(list,t){const v=Math.max(0,Math.min(1,t));if(!list.some(x=>Math.abs(x-v)<1e-8))list.push(v)}
function pointOnSegment(p,s,tol){const dx=s.b.x-s.a.x,dy=s.b.y-s.a.y,len2=dx*dx+dy*dy;if(len2<1e-12)return null;const u=((p.x-s.a.x)*dx+(p.y-s.a.y)*dy)/len2,q={x:s.a.x+u*dx,y:s.a.y+u*dy};return u>=-tol&&u<=1+tol&&Math.hypot(q.x-p.x,q.y-p.y)<=tol?u:null}
function intersectionParams(a,b,tol){const rx=a.b.x-a.a.x,ry=a.b.y-a.a.y,sx=b.b.x-b.a.x,sy=b.b.y-b.a.y,qx=b.a.x-a.a.x,qy=b.a.y-a.a.y,den=cross(rx,ry,sx,sy);if(Math.abs(den)>1e-10){const t=cross(qx,qy,sx,sy)/den,u=cross(qx,qy,rx,ry)/den;if(t>=-tol&&t<=1+tol&&u>=-tol&&u<=1+tol)return[[t,u]];return[]}const col=Math.abs(cross(qx,qy,rx,ry))<=tol*Math.max(1,Math.hypot(rx,ry));if(!col)return[];const hits=[];for(const [p,which] of [[a.a,'a0'],[a.b,'a1'],[b.a,'b0'],[b.b,'b1']]){const ta=pointOnSegment(p,a,tol),tb=pointOnSegment(p,b,tol);if(ta!=null&&tb!=null)hits.push([ta,tb,which])}return hits}
function planarize(raw,tol){const ts=raw.map(()=>[0,1]);for(let i=0;i<raw.length;i++)for(let j=i+1;j<raw.length;j++)for(const [a,b] of intersectionParams(raw[i],raw[j],tol)){addT(ts[i],a);addT(ts[j],b)}const grouped=new Map();for(let i=0;i<raw.length;i++){const s=raw[i],list=ts[i].sort((a,b)=>a-b);for(let j=0;j<list.length-1;j++){const a=list[j],b=list[j+1];if(b-a<1e-8)continue;const p={x:r(s.a.x+(s.b.x-s.a.x)*a),y:r(s.a.y+(s.b.y-s.a.y)*a)},q={x:r(s.a.x+(s.b.x-s.a.x)*b),y:r(s.a.y+(s.b.y-s.a.y)*b)};if(Math.hypot(q.x-p.x,q.y-p.y)<=tol)continue;const k=segKey(p,q,tol),g=grouped.get(k);if(g){g.types.add(s.lineType);g.sourceEdgeIds.add(s.sourceEdgeId);g.curved=g.curved||s.curved}else grouped.set(k,{a:p,b:q,types:new Set([s.lineType]),sourceEdgeIds:new Set([s.sourceEdgeId]),curved:Boolean(s.curved)})}}return[...grouped.values()].map((s,i)=>({id:`s${i+1}`,a:s.a,b:s.b,lineType:s.types.has('CREASE')?'CREASE':'CUT',sourceEdgeIds:[...s.sourceEdgeIds],curved:s.curved}))}

function facesFromSegments(segments,tol,minArea){const vertices=new Map(),half=[],out=new Map(),vertex=p=>{const id=pkey(p,tol);if(!vertices.has(id))vertices.set(id,{id,x:r(p.x),y:r(p.y)});return vertices.get(id)};for(let i=0;i<segments.length;i++){const s=segments[i],a=vertex(s.a),b=vertex(s.b),h={id:i*2,segment:i,from:a.id,to:b.id,twin:i*2+1},t={id:i*2+1,segment:i,from:b.id,to:a.id,twin:i*2};half.push(h,t);for(const x of [h,t]){if(!out.has(x.from))out.set(x.from,[]);out.get(x.from).push(x)}}for(const list of out.values())list.sort((u,v)=>{const a=vertices.get(u.from),b=vertices.get(u.to),c=vertices.get(v.to);return Math.atan2(b.y-a.y,b.x-a.x)-Math.atan2(c.y-a.y,c.x-a.x)});const next=new Map();for(const h of half){const list=out.get(h.to)||[],at=list.findIndex(x=>x.id===h.twin);if(at>=0)next.set(h.id,list[(at-1+list.length)%list.length].id)}const visited=new Set(),faces=[];for(const start of half){if(visited.has(start.id))continue;let cur=start.id,guard=0,closed=false;const hs=[],pts=[];while(cur!=null&&!visited.has(cur)&&guard++<half.length+8){visited.add(cur);const h=half[cur],v=vertices.get(h.from);hs.push(cur);pts.push([v.x,v.y]);cur=next.get(cur);if(cur===start.id){closed=true;break}}const clean=[];for(const p of pts){const z=clean.at(-1);if(!z||Math.hypot(z[0]-p[0],z[1]-p[1])>tol)clean.push(p)}if(clean.length>2&&Math.hypot(clean[0][0]-clean.at(-1)[0],clean[0][1]-clean.at(-1)[1])<=tol)clean.pop();const a=clean.length>=3?area(clean):0;if(closed&&clean.length>=3&&a>minArea)faces.push({points:clean,area:a,halfEdges:hs})}return{faces,half,vertices}}

function matchFaces(faces,oldPanels){const old=oldPanels.map(p=>{const poly=polyOf(p),b=box(poly),c=center(poly);return{p,poly,b,c,area:Math.abs(area(poly))}}),unused=new Set(old.map(x=>x.p.id)),idMap={},panels=[];for(let i=0;i<faces.length;i++){const f=faces[i],b=box(f.points),c=center(f.points),candidates=old.filter(o=>unused.has(o.p.id)&&inside(c,o.poly)).sort((x,y)=>Math.abs(x.area-Math.abs(f.area))-Math.abs(y.area-Math.abs(f.area)));let m=candidates[0];if(!m){const nearest=old.filter(o=>unused.has(o.p.id)).map(o=>({o,d:Math.hypot(o.c.x-c.x,o.c.y-c.y)})).sort((x,y)=>x.d-y.d)[0],limit=Math.max(b.w,b.h,nearest?.o.b.w||0,nearest?.o.b.h||0)*.35;if(nearest&&nearest.d<=limit)m=nearest.o}const id=m?.p.id||`panel-v39-${i+1}`;if(m){unused.delete(id);idMap[id]=id}panels.push({id,label:m?.p.label||id,kind:m?.p.kind||'panel',role:m?.p.role||'',parent:m?.p.parent??null,points:f.points,x:b.x,y:b.y,w:b.w,h:b.h,area:r(Math.abs(f.area)),centroid:{x:r(c.x),y:r(c.y)},_halfEdges:f.halfEdges})}for(const o of old)if(!idMap[o.p.id]&&panels.length){const best=panels.map(p=>({p,d:Math.hypot(p.centroid.x-o.c.x,p.centroid.y-o.c.y)})).sort((a,b)=>a.d-b.d)[0];idMap[o.p.id]=best.p.id}return{panels,idMap,unmatched:[...unused]}}
function legacyHints(state){try{const geo=generateGeometry(state?.structure||{}),graph=buildFoldGraph(geo),map=new Map();for(const e of graph.edges||[])map.set(pair(e.from,e.to),e);return{graph,map}}catch{return{graph:null,map:new Map()}}}
function longestHinge(segments){const pts=[];for(const s of segments)pts.push(s.a,s.b);let best=null,d=-1;for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const x=Math.hypot(pts[i].x-pts[j].x,pts[i].y-pts[j].y);if(x>d){d=x;best=[pts[i],pts[j]]}}return best?{x1:r(best[0].x),y1:r(best[0].y),x2:r(best[1].x),y2:r(best[1].y)}:null}
function folds(doc,segments,faceData,panels,legacy){const byHalf=new Map();for(const p of panels)for(const h of p._halfEdges)byHalf.set(h,p.id);const links=new Map(),issues=[];for(let i=0;i<segments.length;i++){const s=segments[i];if(s.lineType!=='CREASE')continue;const a=byHalf.get(i*2),b=byHalf.get(i*2+1);if(!a||!b||a===b){issues.push(problem('warning','CREASE_FACE_REVIEW',`Crease ${s.id} is not shared by two bounded panels.`,{sourceEdgeIds:s.sourceEdgeIds}));continue}const k=pair(a,b),v=links.get(k)||{a,b,segments:[],sourceEdgeIds:new Set(),curved:false};v.segments.push(s);for(const id of s.sourceEdgeIds)v.sourceEdgeIds.add(id);v.curved=v.curved||s.curved;links.set(k,v)}const panelMap=Object.fromEntries(panels.map(p=>[p.id,p])),root=panelMap[legacy.graph?.root]?legacy.graph.root:(panels.filter(p=>p.kind!=='glue'&&p.role!=='glue').sort((a,b)=>b.area-a.area)[0]?.id||panels[0]?.id||null),adj=new Map(panels.map(p=>[p.id,[]]));for(const l of links.values()){adj.get(l.a)?.push({...l,to:l.b});adj.get(l.b)?.push({...l,to:l.a})}const nodes=panels.map(p=>({id:p.id,label:p.label,w:p.w,h:p.h,points:clone(p.points),role:p.role||'panel',artPanel:p.id,flat:{pos:[p.centroid.x-doc.width/2,-(p.centroid.y-doc.height/2),0],rot:[0,0,0]}})),edges=[],roots=legacy.graph?.roots?.filter(id=>panelMap[id])|| (root?[root]:[]),seen=new Set(roots),q=[...roots];while(q.length){const from=q.shift();for(const l of adj.get(from)||[]){if(seen.has(l.to))continue;seen.add(l.to);q.push(l.to);const hint=legacy.map.get(pair(from,l.to)),angle=hint?(hint.from===from?n(hint.angle,90):-n(hint.angle,90)):90,angleSource=hint?'legacy-semantic':'review-default',hinge=longestHinge(l.segments);if(!hint)issues.push(problem('warning','FOLD_ANGLE_REVIEW',`No semantic angle hint for ${from} → ${l.to}; 90° requires review.`,{from,to:l.to}));if(l.curved&&hinge){hinge.curveApproximation=true;issues.push(problem('warning','CURVED_HINGE_REVIEW',`Curved crease between ${from} and ${l.to} uses a straight endpoint hinge for 3D review.`,{from,to:l.to}))}edges.push({from,to:l.to,label:hint?.label||`${from}/${l.to}`,angle,angleSource,hinge,sourceEdgeIds:[...l.sourceEdgeIds]})}}const unreached=panels.map(p=>p.id).filter(x=>!seen.has(x));if(unreached.length)issues.push(problem('warning','FOLD_UNREACHED',`Panels outside fold traversal: ${unreached.join(', ')}.`,{panels:unreached}));return{graph:{schema:'boxstudio-foldgraph-v39',template:doc.template,root,roots,nodes,edges,unreached,...(legacy.graph?.components?.length&&roots.length===legacy.graph.components.length?{components:clone(legacy.graph.components)}:{})},links:[...links.values()].map(l=>({...l,sourceEdgeIds:[...l.sourceEdgeIds]})),issues}}
function classify(panels){const body=[],flap=[];for(const p of panels){const s=`${p.kind} ${p.role}`.toLowerCase();(s.includes('flap')||s.includes('tab')||s.includes('tuck')||s.includes('wing')?flap:body).push(p)}return{body,flap}}

export function buildStructuralTopologyV39(state,{doc=null,curveSteps=18,tolerance=.01,minArea=.1}={}){const source=clone(doc||state?.dielineV38||dielineDocumentFromStateV38(state||{})),raw=rawSegments(source,curveSteps,tolerance),segments=planarize(raw.segments,tolerance),faceData=facesFromSegments(segments,tolerance,minArea),matched=matchFaces(faceData.faces,source.panels||[]),legacy=legacyHints(state),fold=folds(source,segments,faceData,matched.panels,legacy),issues=[...raw.issues,...fold.issues];if(!matched.panels.length)issues.push(problem('error','TOPOLOGY_NO_PANELS','No bounded panel faces could be rebuilt from the edited CUT/CREASE graph.'));if(matched.unmatched.length)issues.push(problem('warning','PANEL_REMAP_REVIEW',`Original panels not directly matched: ${matched.unmatched.join(', ')}.`,{panels:matched.unmatched}));const c=classify(matched.panels),base=geometryFromDielineDocumentV38(source),cleanPanels=matched.panels.map(({_halfEdges,...p})=>p),panelMap=Object.fromEntries(cleanPanels.map(p=>[p.id,p])),foldCandidates=fold.graph.edges.map((e,i)=>({id:`v39-fold-${i+1}`,a:e.from,b:e.to,confirmed:true,angle:e.angle,hinge:clone(e.hinge),sourceEdgeIds:clone(e.sourceEdgeIds),angleSource:e.angleSource})),geometry={...base,template:source.template,width:source.width,height:source.height,panels:clone(cleanPanels),bodyPanels:clone(c.body.map(({_halfEdges,...p})=>p)),flapPanels:clone(c.flap.map(({_halfEdges,...p})=>p)),panelMap,structure:{...(state?.structure||{}),template:source.template,bleed:source.settings?.bleedMm??3,safe:source.settings?.safeMm??5},foldCandidates,foldRoot:fold.graph.root};const rebuiltDoc=buildProductionZonesV38({...source,panels:cleanPanels,metadata:{...(source.metadata||{}),topologySchema:V39_TOPOLOGY_SCHEMA}},{bleed:source.settings?.bleedMm??3,safe:source.settings?.safeMm??5}),errors=issues.filter(x=>x.severity==='error'),warnings=issues.filter(x=>x.severity==='warning');return{schema:V39_TOPOLOGY_SCHEMA,version:1,ok:!errors.length,doc:rebuiltDoc,geometry,panels:cleanPanels,panelMap,panelIdMap:matched.idMap,graph:fold.graph,adjacency:fold.links,issues,errors,warnings,stats:{sampledSegments:raw.segments.length,planarSegments:segments.length,faces:cleanPanels.length,foldLinks:fold.links.length,foldTreeEdges:fold.graph.edges.length,errors:errors.length,warnings:warnings.length}}}
export function reconcileArtworkToTopologyV39(state,topology){const next=clone(state||{}),valid=new Set(Object.keys(topology?.panelMap||{})),remapped=[],orphaned=[];for(const el of next.elements||[]){if(el?.type==='cross-panel-artwork'||!el?.panelId||valid.has(el.panelId))continue;const to=topology?.panelIdMap?.[el.panelId];if(to&&valid.has(to)){remapped.push({elementId:el.id,from:el.panelId,to});el.panelId=to}else orphaned.push({elementId:el.id,panelId:el.panelId})}next.dielineV38=clone(topology.doc);next.topologyV39={schema:topology.schema,stats:clone(topology.stats),panelIdMap:clone(topology.panelIdMap),graph:clone(topology.graph)};return{state:next,remapped,orphaned,ok:!orphaned.length}}
export function topologyProductionGateV39(state,topology){const reconciled=reconcileArtworkToTopologyV39(state,topology),issues=[...(topology?.issues||[])];for(const o of reconciled.orphaned)issues.push(problem('error','ARTWORK_PANEL_ORPHAN',`Artwork ${o.elementId} references removed panel ${o.panelId}.`,o));const errors=issues.filter(x=>x.severity==='error'),warnings=issues.filter(x=>x.severity==='warning');return{ok:!errors.length,issues,errors,warnings,reconciled}}
