let THREE=null,engine=null,pending=null,unavailable=false;
const clamp=(n,a,b,d)=>Number.isFinite(Number(n))?Math.min(b,Math.max(a,Number(n))):d;
export const LIGHT_RIGS_V74={soft:{label:'柔光商品棚',key:3,fill:1.1,ambient:.45,azimuth:45,elevation:55,temperature:5500,exposure:1,roughness:.7},contrast:{label:'侧光轮廓棚',key:4.2,fill:.3,ambient:.22,azimuth:100,elevation:35,temperature:5500,exposure:1,roughness:.55},warm:{label:'暖光纸品棚',key:3,fill:.7,ambient:.4,azimuth:-40,elevation:48,temperature:3600,exposure:1.05,roughness:.85},flat:{label:'均匀印刷检查',key:2,fill:2,ambient:.9,azimuth:30,elevation:70,temperature:6500,exposure:1,roughness:1}};
export function lightingSettingsV74(input={}){const rig=Object.hasOwn(LIGHT_RIGS_V74,input.lightRig)?input.lightRig:'soft',r=LIGHT_RIGS_V74[rig];return{lightRig:rig,key:clamp(input.key,0,8,r.key),fill:clamp(input.fill,0,5,r.fill),ambient:clamp(input.ambient,0,2,r.ambient),azimuth:clamp(input.azimuth,-180,180,r.azimuth),elevation:clamp(input.elevation,10,85,r.elevation),temperature:clamp(input.temperature,2700,7500,r.temperature),exposure:clamp(input.exposure,.3,2,r.exposure),roughness:clamp(input.roughness,.25,1,r.roughness)};}
export async function loadPhysicalStudioV74(){if(!pending)pending=import('../vendor/three/three.module.min.js').then(m=>{THREE=m;return true;}).catch(e=>{pending=null;throw e;});return pending;}
export function physicalStudioReadyV74(){return Boolean(THREE)&&!unavailable;}
const unitPoint=(meshes,q)=>{const p=q.map((v,i)=>(v-meshes.center[i])/meshes.span);return meshes.upAxis==='Z'?[p[0],p[2],-p[1]]:p;};
function kelvin(k){const t=k/100,r=t<=66?255:329.698727446*(t-60)**-.1332047592,g=t<=66?99.4708025861*Math.log(t)-161.1195681661:288.1221695283*(t-60)**-.0755148492,b=t>=66?255:t<=19?0:138.5177312231*Math.log(t-10)-305.0447927307;return new THREE.Color(...[r,g,b].map(v=>Math.max(0,Math.min(255,v))/255));}
function createEngine(){
 const canvas=document.createElement('canvas'),context=canvas.getContext('webgl2',{antialias:true,alpha:true,preserveDrawingBuffer:true});if(!context){unavailable=true;throw new Error('此设备不支持 WebGL 2。');}const renderer=new THREE.WebGLRenderer({canvas,context,antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,4/3,.01,100),group=new THREE.Group();scene.add(group);
 const key=new THREE.DirectionalLight(0xffffff,3),fill=new THREE.DirectionalLight(0xffffff,1),rim=new THREE.DirectionalLight(0xffffff,1);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-2,right:2,top:2,bottom:-2,near:.1,far:12});key.shadow.bias=-.00015;key.shadow.normalBias=.003;key.shadow.radius=3;scene.add(key,fill,rim);
 const ambient=new THREE.HemisphereLight(0xffffff,0x6e655a,.45);scene.add(ambient);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({color:0x151c25,opacity:.22}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
 // An actual radiance environment, generated locally from studio walls and softboxes.
 const room=new THREE.Scene();room.background=new THREE.Color('#e5e5e5');const wall=new THREE.Mesh(new THREE.BoxGeometry(20,20,20),new THREE.MeshBasicMaterial({color:0xaaaaaa,side:THREE.BackSide}));room.add(wall);
 for(const [x,y,z,w,h]of [[-5,4,0,3,7],[5,3,0,3,7],[0,6,-5,6,3]]){const p=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({color:new THREE.Color(4,4,4),side:THREE.DoubleSide}));p.position.set(x,y,z);p.lookAt(0,0,0);room.add(p);}
 const pmrem=new THREE.PMREMGenerator(renderer),env=pmrem.fromScene(room,.04);scene.environment=env.texture;pmrem.dispose();room.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});
 return{renderer,scene,camera,group,key,fill,rim,ambient,ground,env,meshSource:null,textureSource:null};
}
function clearGroup(group){for(const o of [...group.children]){group.remove(o);o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){m.map?.dispose();m.dispose();}}}
function buildMeshes(e,meshes,textures,roughness,contrast=1){
 clearGroup(e.group);for(const p of meshes.panels){const positions=[],uv=[];for(const tri of p.uvMap.triangles)for(const i of tri){positions.push(...unitPoint(meshes,p.points[i]));uv.push(...p.uvMap.uv[i]);}
  const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.computeVertexNormals();const original=textures.get(p.nodeId),paper=document.createElement('canvas');paper.width=original.width;paper.height=original.height;const ctx=paper.getContext('2d');ctx.filter='contrast('+contrast+')';ctx.drawImage(original,0,0);const map=new THREE.CanvasTexture(paper);map.colorSpace=THREE.SRGBColorSpace;map.flipY=false;map.anisotropy=Math.min(8,e.renderer.capabilities.getMaxAnisotropy());
  const material=new THREE.MeshPhysicalMaterial({map,side:THREE.DoubleSide,roughness,metalness:0,clearcoat:.08,clearcoatRoughness:.8,polygonOffset:true,polygonOffsetFactor:/tab|glue/.test(p.nodeId)?4:/return/.test(p.nodeId)?2:-2,polygonOffsetUnits:/tab|glue/.test(p.nodeId)?4:/return/.test(p.nodeId)?2:-2});const mesh=new THREE.Mesh(g,material);mesh.castShadow=true;mesh.receiveShadow=true;e.group.add(mesh);
 }e.meshSource=meshes;e.textureSource=textures;e.contrast=contrast;e.signature=meshes.panels.map(p=>p.nodeId+':'+p.uvMap.triangles.length).join(',');
}
export function renderPhysicalStudioV74(meshes,textures,settings,width,height,target=null){
 if(!THREE)throw new Error('摄影棚渲染器尚未加载。');if(!engine)engine=createEngine();const e=engine,s=lightingSettingsV74(settings);
 const signature=meshes.panels.map(p=>p.nodeId+':'+p.uvMap.triangles.length).join(',');if(e.signature!==signature||e.textureSource!==textures||e.contrast!==settings.contrast)buildMeshes(e,meshes,textures,s.roughness,settings.contrast);else{if(e.meshSource!==meshes){meshes.panels.forEach((p,i)=>{const geometry=e.group.children[i].geometry,positions=geometry.attributes.position;let n=0;for(const tri of p.uvMap.triangles)for(const index of tri){const v=unitPoint(meshes,p.points[index]);positions.setXYZ(n++,...v);}positions.needsUpdate=true;geometry.computeVertexNormals();geometry.computeBoundingSphere();});e.meshSource=meshes;}for(const m of e.group.children)m.material.roughness=s.roughness;}
 e.renderer.setSize(width,height,false);e.renderer.toneMappingExposure=s.exposure;e.scene.background=settings.background?new THREE.Color(settings.background):null;
 const az=s.azimuth*Math.PI/180,el=s.elevation*Math.PI/180;e.key.position.set(Math.sin(az)*Math.cos(el)*4,Math.sin(el)*4,Math.cos(az)*Math.cos(el)*4);e.key.color.copy(kelvin(s.temperature));e.key.intensity=s.key;e.fill.position.set(-3,2,-2);e.fill.intensity=s.fill;e.rim.position.set(1,3,-3);e.rim.intensity=s.key*.25;e.ambient.intensity=s.ambient;
 const minY=Math.min(...meshes.panels.flatMap(p=>p.points.map(q=>unitPoint(meshes,q)[1])));e.ground.position.y=minY-.002;e.ground.visible=settings.shadow!==false;e.ground.material.opacity=.24;
 const distance=2.6/Math.max(.3,settings.zoom||1),yaw=settings.yaw??.6,pitch=settings.pitch??.45;e.camera.position.set(Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance);e.camera.lookAt(0,0,0);e.camera.aspect=width/height;e.camera.updateProjectionMatrix();e.renderer.render(e.scene,e.camera);
 const canvas=target||document.createElement('canvas');if(canvas.width!==width)canvas.width=width;if(canvas.height!==height)canvas.height=height;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,width,height);ctx.drawImage(e.renderer.domElement,0,0);canvas.dataset.renderer='physical-webgl';return canvas;
}
export function disposePhysicalStudioV74(){unavailable=false;if(!engine)return;clearGroup(engine.group);engine.ground.geometry.dispose();engine.ground.material.dispose();engine.env.dispose();engine.renderer.dispose();engine.renderer.forceContextLoss();engine=null;}
