import {boardSurfacesV77} from './boardSurfaceV77.js';
import {paintBackdropV75} from './backdropV75.js';
import {PAPER_FINISHES_V75,studioSettingsV75} from './studioConfigV75.js';
let THREE=null,engine=null,pending=null,unavailable=false;
const clamp=(n,a,b,d)=>Number.isFinite(Number(n))?Math.min(b,Math.max(a,Number(n))):d;
export const LIGHT_RIGS_V74={window:{label:'窗边自然光',key:3.4,fill:.45,ambient:.5,azimuth:-70,elevation:45,temperature:6500,exposure:1,roughness:.8,rim:.5},lowkey:{label:'暗调轮廓光',key:5.5,fill:.2,ambient:.12,azimuth:110,elevation:35,temperature:5500,exposure:1.05,roughness:.55,rim:2},beauty:{label:'美妆高调光',key:3.2,fill:1.6,ambient:.65,azimuth:35,elevation:40,temperature:6000,exposure:1.15,roughness:.4,rim:.5},daylight:{label:'冷调日光',key:3.3,fill:1,ambient:.4,azimuth:-35,elevation:60,temperature:7500,exposure:1,roughness:.75,rim:.8},soft:{label:'柔光商品棚',key:3,fill:1.1,ambient:.45,azimuth:45,elevation:55,temperature:5500,exposure:1,roughness:.7},contrast:{label:'侧光轮廓棚',key:4.2,fill:.3,ambient:.22,azimuth:100,elevation:35,temperature:5500,exposure:1,roughness:.55},warm:{label:'暖光纸品棚',key:3,fill:.7,ambient:.4,azimuth:-40,elevation:48,temperature:3600,exposure:1.05,roughness:.85},flat:{label:'均匀印刷检查',key:2,fill:2,ambient:.9,azimuth:30,elevation:70,temperature:6500,exposure:1,roughness:1}};
export function lightingSettingsV74(input={}){const rig=Object.hasOwn(LIGHT_RIGS_V74,input.lightRig)?input.lightRig:'soft',r=LIGHT_RIGS_V74[rig];return{lightRig:rig,rim:clamp(input.rim,0,5,r.rim??r.key*.25),key:clamp(input.key,0,8,r.key),fill:clamp(input.fill,0,5,r.fill),ambient:clamp(input.ambient,0,2,r.ambient),azimuth:clamp(input.azimuth,-180,180,r.azimuth),elevation:clamp(input.elevation,10,85,r.elevation),temperature:clamp(input.temperature,2700,7500,r.temperature),exposure:clamp(input.exposure,.3,2,r.exposure),roughness:clamp(input.roughness,.25,1,r.roughness)};}
export async function loadPhysicalStudioV74(){if(!pending)pending=import('../vendor/three/three.module.min.js').then(m=>{THREE=m;return true;}).catch(e=>{pending=null;throw e;});return pending;}
export function physicalStudioReadyV74(){return Boolean(THREE)&&!unavailable;}
const unitPoint=(meshes,q)=>{const p=q.map((v,i)=>(v-meshes.center[i])/meshes.span);return meshes.upAxis==='Z'?[p[0],-p[2],p[1]]:p;};
function kelvin(k){const t=k/100,r=t<=66?255:329.698727446*(t-60)**-.1332047592,g=t<=66?99.4708025861*Math.log(t)-161.1195681661:288.1221695283*(t-60)**-.0755148492,b=t>=66?255:t<=19?0:138.5177312231*Math.log(t-10)-305.0447927307;return new THREE.Color(...[r,g,b].map(v=>Math.max(0,Math.min(255,v))/255));}
function createEngine(){
 const canvas=document.createElement('canvas'),context=canvas.getContext('webgl2',{antialias:true,alpha:true,preserveDrawingBuffer:true});if(!context){unavailable=true;throw new Error('此设备不支持 WebGL 2。');}const renderer=new THREE.WebGLRenderer({canvas,context,antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,4/3,.01,100),orthographic=new THREE.OrthographicCamera(-1,1,1,-1,.01,100),group=new THREE.Group();scene.add(group);
 const key=new THREE.DirectionalLight(0xffffff,3),fill=new THREE.DirectionalLight(0xffffff,1),rim=new THREE.DirectionalLight(0xffffff,1);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-2,right:2,top:2,bottom:-2,near:.1,far:12});key.shadow.bias=-.00015;key.shadow.normalBias=.003;key.shadow.radius=3;scene.add(key,fill,rim);
 const ambient=new THREE.HemisphereLight(0xffffff,0x6e655a,.45);scene.add(ambient);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({color:0x151c25,opacity:.22}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
 const pedestalBlock=new THREE.Mesh(new THREE.BoxGeometry(1.15,.16,.9),new THREE.MeshStandardMaterial({color:0xe5e1d9,roughness:.9})),pedestalRound=new THREE.Mesh(new THREE.CylinderGeometry(.65,.65,.16,64),new THREE.MeshStandardMaterial({color:0xe5e1d9,roughness:.9}));for(const p of [pedestalBlock,pedestalRound]){p.castShadow=p.receiveShadow=true;p.visible=false;scene.add(p);}
 // An actual radiance environment, generated locally from studio walls and softboxes.
 const room=new THREE.Scene();room.background=new THREE.Color('#e5e5e5');const wall=new THREE.Mesh(new THREE.BoxGeometry(20,20,20),new THREE.MeshBasicMaterial({color:0xaaaaaa,side:THREE.BackSide}));room.add(wall);
 for(const [x,y,z,w,h]of [[-5,4,0,3,7],[5,3,0,3,7],[0,6,-5,6,3]]){const p=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({color:new THREE.Color(4,4,4),side:THREE.DoubleSide}));p.position.set(x,y,z);p.lookAt(0,0,0);room.add(p);}
 const pmrem=new THREE.PMREMGenerator(renderer),env=pmrem.fromScene(room,.04);scene.environment=env.texture;pmrem.dispose();room.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});
 return{renderer,scene,camera,orthographic,pedestalBlock,pedestalRound,group,key,fill,rim,ambient,ground,env,meshSource:null,textureSource:null};
}
function clearGroup(group){const geometries=new Set(),materials=new Set();group.traverse(o=>{if(o.geometry)geometries.add(o.geometry);for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m)materials.add(m);});group.clear();for(const g of geometries)g.dispose();for(const m of materials){m.map?.dispose();m.dispose();}}
function paperGeometry(meshes,surface){const positions=[];for(let i=0;i<surface.positions.length;i+=3)positions.push(...unitPoint(meshes,surface.positions.slice(i,i+3)));const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(surface.uv,2));g.computeVertexNormals();return g;}
function buildMeshes(e,meshes,textures,roughness,contrast=1){
 clearGroup(e.group);for(const p of meshes.panels){const surfaces=boardSurfacesV77(p,meshes.thicknessMm||0),g=paperGeometry(meshes,surfaces[0]);
  const original=textures.get(p.nodeId),paper=document.createElement('canvas');paper.width=original.width;paper.height=original.height;const ctx=paper.getContext('2d');ctx.filter='contrast('+contrast+')';ctx.drawImage(original,0,0);const map=new THREE.CanvasTexture(paper);map.colorSpace=THREE.SRGBColorSpace;map.flipY=false;map.anisotropy=Math.min(8,e.renderer.capabilities.getMaxAnisotropy());
  const material=new THREE.MeshPhysicalMaterial({map,side:THREE.FrontSide,roughness,metalness:0,clearcoat:.08,clearcoatRoughness:.8,polygonOffset:true,polygonOffsetFactor:/tab|glue/.test(p.nodeId)?4:/return/.test(p.nodeId)?2:-2,polygonOffsetUnits:/tab|glue/.test(p.nodeId)?4:/return/.test(p.nodeId)?2:-2});const mesh=new THREE.Mesh(g,material);mesh.castShadow=true;mesh.receiveShadow=true;e.group.add(mesh);for(const surface of surfaces.slice(1)){const insideMaterial=new THREE.MeshPhysicalMaterial({color:meshes.innerColor||'#c7b799',side:THREE.FrontSide,roughness:.95,metalness:0});const inside=new THREE.Mesh(paperGeometry(meshes,surface),insideMaterial);inside.name=surface.name;inside.castShadow=inside.receiveShadow=true;mesh.add(inside);}
 }e.meshSource=meshes;e.textureSource=textures;e.contrast=contrast;e.signature=meshes.panels.map(p=>p.nodeId+':'+p.uvMap.triangles.length).join(',');
}
export function renderPhysicalStudioV74(meshes,textures,settings,width,height,target=null){
 if(!THREE)throw new Error('摄影棚渲染器尚未加载。');if(!engine)engine=createEngine();const e=engine,s={...lightingSettingsV74(settings),...studioSettingsV75(settings)};
 const signature=meshes.panels.map(p=>p.nodeId+':'+p.uvMap.triangles.length).join(',');if(e.signature!==signature||e.textureSource!==textures||e.contrast!==settings.contrast||e.thickness!==(meshes.thicknessMm||0)||e.innerColor!==meshes.innerColor)buildMeshes(e,meshes,textures,s.roughness,settings.contrast);else{if(e.meshSource!==meshes){meshes.panels.forEach((p,i)=>{const front=e.group.children[i],surfaces=boardSurfacesV77(p,meshes.thicknessMm||0);[front,...front.children].forEach((mesh,j)=>{const next=paperGeometry(meshes,surfaces[j]);mesh.geometry.dispose();mesh.geometry=next;});});e.meshSource=meshes;}for(const m of e.group.children)m.material.roughness=s.roughness;}
 e.thickness=meshes.thicknessMm||0;e.innerColor=meshes.innerColor;const finish=PAPER_FINISHES_V75[s.finish];for(const mesh of e.group.children){mesh.material.metalness=finish.metalness;mesh.material.clearcoat=finish.clearcoat;mesh.material.color.set(finish.color);if(e.finish!==s.finish)mesh.material.needsUpdate=true;}e.finish=s.finish;
 e.renderer.setSize(width,height,false);e.renderer.toneMappingExposure=s.exposure;e.scene.background=!settings.backgroundImage&&settings.background?new THREE.Color(settings.background):null;
 const az=s.azimuth*Math.PI/180,el=s.elevation*Math.PI/180;e.key.position.set(Math.sin(az)*Math.cos(el)*4,Math.sin(el)*4,Math.cos(az)*Math.cos(el)*4);e.key.color.copy(kelvin(s.temperature));e.key.intensity=s.key;e.fill.position.set(-3,2,-2);e.fill.intensity=s.fill;e.rim.position.set(1,3,-3);e.rim.intensity=s.rim;e.ambient.intensity=s.ambient;
 const minY=Math.min(...meshes.panels.flatMap(p=>p.points.map(q=>unitPoint(meshes,q)[1])));e.ground.position.y=(meshes.floorY??minY)-.002;e.ground.visible=settings.shadow!==false;e.ground.material.opacity=s.shadowOpacity;const lift=s.pedestal==='none'?0:.16;e.group.position.y=lift;for(const [p,id]of [[e.pedestalBlock,'block'],[e.pedestalRound,'round']]){p.visible=s.pedestal===id;p.position.y=minY+.08;p.material.color.set(s.pedestalColor);}
 const distance=2.6/Math.max(.3,settings.zoom||1),yaw=settings.yaw??.6,pitch=settings.pitch??.45;const camera=s.projection==='orthographic'?e.orthographic:e.camera;camera.position.set(Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(0,lift*.5,0);if(s.projection==='orthographic'){const half=.88/Math.max(.3,settings.zoom||1),aspect=width/height;camera.left=-half*aspect;camera.right=half*aspect;camera.top=half;camera.bottom=-half;}else{camera.fov=s.fov;camera.aspect=width/height;}camera.updateProjectionMatrix();e.renderer.render(e.scene,camera);
 const canvas=target||document.createElement('canvas');if(canvas.width!==width)canvas.width=width;if(canvas.height!==height)canvas.height=height;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,width,height);paintBackdropV75(ctx,settings.backgroundImage,width,height);ctx.drawImage(e.renderer.domElement,0,0);canvas.dataset.renderer='physical-webgl';return canvas;
}
export function disposePhysicalStudioV74(){unavailable=false;if(!engine)return;clearGroup(engine.group);for(const p of [engine.pedestalBlock,engine.pedestalRound]){p.geometry.dispose();p.material.dispose();}engine.ground.geometry.dispose();engine.ground.material.dispose();engine.env.dispose();engine.renderer.dispose();engine.renderer.forceContextLoss();engine=null;}
