import {installRichTextUiV77} from './richTextUiV77.js';
import {FONTS_V74,loadFontV74,getFontV74,fontTextSvgV74,fontGlyphIssuesV74} from './fontSystemV74.js';
import {textStyleV76,layoutTextV76} from './textLayoutV76.js';
import {standaloneMarkUiV67} from './standaloneMarkUiV67.js';
import {renderTemplate} from './variables.js';
import {iconV67} from './uiIconsV67.js';
import {setUiVersion} from './uiVersion.js';
export const escV76=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function workspaceV76(){const inMarks=window.BoxStudioEditor.getState().page==='mark-studio';return{inMarks,state:inMarks?standaloneMarkUiV67.getState():window.BoxStudioEditor.getState(),commit:next=>inMarks?standaloneMarkUiV67.commit(next):window.BoxStudioEditor.commitState(next)};}
export function resourceDialogV76(title,content){const d=document.createElement('dialog');d.className='v67-dialog v76-resource-dialog';d.setAttribute('aria-label',title);d.innerHTML='<header><div><span class="v67-eyebrow">BOXSTUDIO · PRINT WORKBENCH</span><h2>'+title+'</h2></div><button type="button" data-v76-close aria-label="关闭窗口">'+iconV67('close')+'</button></header>'+content;document.body.append(d);d.querySelector('[data-v76-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d;}
export function openTextLayoutV76(){
 const context=workspaceV76(),initial=context.state,selected=initial.elements.find(e=>e.id===initial.selectedId);if(!selected||!['text','notice'].includes(selected.type))return null;
 const e=structuredClone(selected),s=textStyleV76(e.textStyleV76);let token=0,ready=null;
 const select=(name,options,value)=>'<select name="'+name+'">'+options.map(([id,label])=>'<option value="'+id+'" '+(id===value?'selected':'')+'>'+label+'</option>').join('')+'</select>',number=(name,value,min,max,step=.1)=>'<input name="'+name+'" type="number" value="'+value+'" min="'+min+'" max="'+max+'" step="'+step+'" required>',checkbox=(name,label,checked)=>'<label class="v76-toggle"><input type="checkbox" name="'+name+'" '+(checked?'checked':'')+'>'+label+'</label>';
 const d=resourceDialogV76('文字排版','<form data-v76-text-form><div class="v76-text-body"><section class="v76-text-preview"><div class="v76-preview-caption"><b>实际字形预览</b><span data-v76-text-size></span></div><div class="v76-text-paper" data-v76-text-preview></div><p>预览、PDF / SVG 与 3D 贴图共用字形轮廓。</p><p role="status" data-v76-text-status></p></section><section class="v76-text-controls"><fieldset '+(e.locked?'disabled':'')+'><legend>字体与内容</legend><label>字体<select name="fontIdV74">'+FONTS_V74.map(f=>'<option value="'+f.id+'" '+((e.fontIdV74||'sans-sc')===f.id?'selected':'')+'>'+escV76(f.label)+'</option>').join('')+'</select></label><label>文字内容<textarea name="template" rows="4" maxlength="3000">'+escV76(e.template)+'</textarea></label><small>可保留 {{sku}}、{{crn}} 等变量，使用运输数据同步更新。</small><div class="v76-fields"><label>字号 · mm'+number('fontSize',e.fontSize||5,1,80,'any')+'</label><label>文字颜色<input name="color" type="color" value="'+s.color+'"></label><label>框宽 · mm'+number('w',e.w,4,1500,'any')+'</label><label>框高 · mm'+number('h',e.h,4,1500,'any')+'</label></div></fieldset><fieldset '+(e.locked?'disabled':'')+'><legend>段落排版</legend><div class="v76-fields"><label>对齐'+select('align',[['left','左 / 顶部'],['center','居中'],['right','右 / 底部'],['justify','两端对齐']],s.align)+'</label><label>块位置'+select('verticalAlign',[['top','顶部'],['center','垂直居中'],['bottom','底部']],s.verticalAlign)+'</label><label>字间距 · mm'+number('letterSpacing',s.letterSpacing,-2,20)+'</label><label>行距 · %'+number('lineHeight',Math.round(s.lineHeight*100),80,300,5)+'</label></div><label>排版方向'+select('direction',[['horizontal','横排 · 从左至右'],['vertical-rl','竖排 · 列从右至左，字符直立']],s.direction)+'</label>'+checkbox('wrap','按文字框自动换行',s.wrap)+'</fieldset><fieldset '+(e.locked?'disabled':'')+'><legend>文字样式</legend><div class="v76-style-toggles">'+checkbox('bold','粗体',e.bold)+checkbox('italic','倾斜 · 13°',s.italic)+checkbox('underline','下划线',s.underline)+checkbox('strike','删除线',s.strike)+'</div></fieldset></section></div><footer><span>'+(e.locked?'当前文字已锁定，请先解锁。':'调整后点击应用；关闭窗口保留原排版。')+'</span><button type="button" data-v76-reset>重置排版</button><button class="primary" type="submit" data-v76-apply-text disabled>应用文字排版</button></footer></form>');
 const form=d.querySelector('form'),status=d.querySelector('[data-v76-text-status]'),apply=d.querySelector('[data-v76-apply-text]');
 function draft(){const f=form.elements,style=textStyleV76({align:f.align.value,verticalAlign:f.verticalAlign.value,direction:f.direction.value,letterSpacing:Number(f.letterSpacing.value),lineHeight:Number(f.lineHeight.value)/100,wrap:f.wrap.checked,italic:f.italic.checked,underline:f.underline.checked,strike:f.strike.checked,color:f.color.value});return{...e,w:Number(f.w.value),h:Number(f.h.value),fontSize:Number(f.fontSize.value),fontIdV74:f.fontIdV74.value,bold:f.bold.checked,template:f.template.value,textStyleV76:style};}
 installRichTextUiV77(form,e,()=>preview());
 async function preview(){const current=++token;ready=null;apply.disabled=true;try{const next=draft();status.textContent='正在准备实际字体…';await Promise.all([loadFontV74(next.fontIdV74,next.bold),...(next.textRunsV77||[]).map(r=>loadFontV74(r.fontId,r.bold))]);if(current!==token||!d.open)return;form.elements.verticalAlign.disabled=next.textStyleV76.direction==='vertical-rl';const text=renderTemplate(next.template,initial.variables),issues=fontGlyphIssuesV74(next,text),layout=layoutTextV76(getFontV74(next.fontIdV74,next.bold),text,next);d.querySelector('[data-v76-text-size]').textContent=next.w+' × '+next.h+' mm';d.querySelector('[data-v76-text-preview]').innerHTML='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+next.w+' '+next.h+'" aria-label="排版预览"><rect width="'+next.w+'" height="'+next.h+'" fill="white"/>'+fontTextSvgV74(next,text)+'</svg>';status.textContent=issues[0]||layout.lines+' '+(next.textStyleV76.direction==='horizontal'?'行':'列')+' · 字体已就绪';status.dataset.error=String(issues.length>0);if(!issues.length&&!e.locked){ready=next;apply.disabled=false;}}catch(error){if(current===token){status.textContent=error.message;status.dataset.error='true';}}}
 form.addEventListener('input',preview);form.addEventListener('change',preview);
 form.onsubmit=event=>{event.preventDefault();if(!ready||apply.disabled)return;apply.disabled=true;try{const now=workspaceV76();if(now.inMarks!==context.inMarks||now.state.projectId!==initial.projectId||now.state.activeMarkFaceV74!==initial.activeMarkFaceV74)throw new Error('当前项目或唛头面已切换，请重新打开文字排版。');const target=now.state.elements.find(n=>n.id===e.id);if(!target||target.locked)throw new Error('文字对象不存在或已锁定。');if(context.inMarks&&(target.x+ready.w>now.state.artboard.width||target.y+ready.h>now.state.artboard.height))throw new Error('文字框超出唛头画布，请缩小框宽高。');Object.assign(target,{w:ready.w,h:ready.h,fontSize:ready.fontSize,fontIdV74:ready.fontIdV74,bold:ready.bold,template:ready.template,textStyleV76:ready.textStyleV76,textRunsV77:ready.textRunsV77||[]});now.commit(now.state);d.close();}catch(error){status.textContent=error.message;status.dataset.error='true';apply.disabled=false;}};
 d.querySelector('[data-v76-reset]').onclick=()=>{for(const[k,v]of Object.entries(textStyleV76())){const f=form.elements[k];if(!f)continue;if(f.type==='checkbox')f.checked=v;else f.value=k==='lineHeight'?v*100:v;}preview();};preview();return d;
}
function enhance(){if(!window.BoxStudioEditor)return;setUiVersion('V0.76');const{state}=workspaceV76(),e=state.elements.find(e=>e.id===state.selectedId);if(!e||!['text','notice'].includes(e.type))return;const field=document.querySelector('[data-mark-properties] textarea[name="template"]')?.closest('label')||document.querySelector('.rightpanel [data-prop="template"]')?.closest('.field');if(field&&!field.parentElement.querySelector('[data-v76-typeset]')){const b=document.createElement('button');b.type='button';b.dataset.v76Typeset='true';b.className='v76-typeset-button';b.textContent='文字排版 · 间距 / 横竖排 / 样式';b.disabled=Boolean(e.locked);b.onclick=openTextLayoutV76;field.after(b);}}
window.BoxStudioUiRuntimeV64?.register('v76-text',enhance);
window.BoxStudioV76={openTextLayout:openTextLayoutV76};
