import {layoutRichTextV77} from './richTextLayoutV77.js';
import {glyphCommands} from './ttfOutline.js';
const DEFAULT={align:'left',verticalAlign:'top',direction:'horizontal',wrap:true,letterSpacing:0,lineHeight:1.15,italic:false,underline:false,strike:false,color:'#111111'};
export function textStyleV76(value={}){const s={...DEFAULT,...value};if(!['left','center','right','justify'].includes(s.align)||!['top','center','bottom'].includes(s.verticalAlign)||!['horizontal','vertical-rl'].includes(s.direction)||!Number.isFinite(s.letterSpacing)||s.letterSpacing< -2||s.letterSpacing>20||!Number.isFinite(s.lineHeight)||s.lineHeight<.8||s.lineHeight>3||!/^#[0-9a-f]{6}$/i.test(s.color)||['wrap','italic','underline','strike'].some(k=>typeof s[k]!=='boolean'))throw new Error('文字排版参数无效。');return s;}
function transform(commands,fn){return commands.map(c=>{const n={...c};for(const[x,y]of [['x','y'],['cx','cy'],['c1x','c1y'],['c2x','c2y']])if(x in c)[n[x],n[y]]=fn(c[x],c[y]);return n;});}
export const moveTextCommandsV76=(c,x,y)=>transform(c,(a,b)=>[a+x,b+y]);
export function rotateTextCommandsV76(c,r,w,h){const a=r*Math.PI/180,co=Math.cos(a),si=Math.sin(a);return transform(c,(x,y)=>[(x-w/2)*co-(y-h/2)*si+w/2,(x-w/2)*si+(y-h/2)*co+h/2]);}
export function textCommandBoundsV76(commands){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const c of commands)for(const[x,y]of [['x','y'],['cx','cy'],['c1x','c1y'],['c2x','c2y']])if(x in c){minX=Math.min(minX,c[x]);minY=Math.min(minY,c[y]);maxX=Math.max(maxX,c[x]);maxY=Math.max(maxY,c[y]);}return Number.isFinite(minX)?{minX,minY,maxX,maxY,w:maxX-minX,h:maxY-minY}:{minX:0,minY:0,maxX:0,maxY:0,w:0,h:0};}
function rectangle(x,y,w,h){return[{op:'M',x,y},{op:'L',x:x+w,y},{op:'L',x:x+w,y:y+h},{op:'L',x,y:y+h},{op:'Z'}];}
export function layoutTextV76(font,text,el){
 if(!font)throw new Error('字体尚未加载。');text=String(text).replace(/\r\n?/g,'\n');const s=textStyleV76(el.textStyleV76),fs=Number(el.fontSize||5),w=Number(el.w),h=Number(el.h);if(text.length>3000||!Number.isFinite(fs)||fs<1||fs>80||![w,h].every(n=>Number.isFinite(n)&&n>=4&&n<=1500))throw new Error('文字最多 3000 字符，字号 1–80 mm，文字框 4–1500 mm。');
 if(el.textRunsV77?.length)return layoutRichTextV77(font,text,el,s);
 const sc=fs/font.unitsPerEm,slant=s.italic?Math.tan(13*Math.PI/180):0,advance=c=>Math.max(fs*.05,(font.advance[font.cmap(c.codePointAt(0))]||font.unitsPerEm*.5)*sc+s.letterSpacing),glyph=c=>transform(glyphCommands(font,font.cmap(c.codePointAt(0))||0),(x,y)=>[(x+y*slant)*sc,-y*sc]),rows=[],runs=[];let commands=[];
 if(s.direction==='horizontal'){
  const available=Math.max(.01,w-6);for(const para of text.split('\n')){let chars=[],width=0;for(const c of [...para]){const n=advance(c);if(s.wrap&&chars.length&&width+n-s.letterSpacing>available){rows.push({chars,width:width-s.letterSpacing,soft:true});chars=[];width=0;}chars.push(c);width+=n;}rows.push({chars,width:Math.max(0,width-s.letterSpacing),soft:false});}
  rows.forEach((row,i)=>{let x=3+(s.align==='center'?(available-row.width)/2:s.align==='right'?available-row.width:0),y=fs+i*fs*s.lineHeight;const spaces=row.chars.filter(c=>c===' ').length,extra=s.align==='justify'&&row.soft&&spaces?(available-row.width)/spaces:0,start=x;for(const c of row.chars){commands.push(...moveTextCommandsV76(glyph(c),x,y));x+=advance(c)+(c===' '?extra:0);}const width=Math.max(0,x-start-s.letterSpacing),thick=Math.max(.12,fs*.055);if(s.underline&&width)commands.push(...rectangle(start,y+fs*.1,width,thick));if(s.strike&&width)commands.push(...rectangle(start,y-fs*.32,width,thick));runs.push({x:start,y,width,text:row.chars.join('')});});
  const b=textCommandBoundsV76(commands),dy=(s.verticalAlign==='center'?(h-b.h)/2:s.verticalAlign==='bottom'?h-b.h:0)-b.minY;commands=moveTextCommandsV76(commands,0,dy);
 }else{
  const step=Math.max(fs*.05,fs+s.letterSpacing),available=h;for(const para of text.split('\n')){let chars=[];for(const c of [...para]){if(s.wrap&&chars.length&&(chars.length+1)*step-s.letterSpacing>available){rows.push(chars);chars=[];}chars.push(c);}rows.push(chars);}
  rows.forEach((chars,i)=>{const width=fs,x=w-3-fs-i*fs*s.lineHeight,total=Math.max(0,chars.length*step-s.letterSpacing),start=s.align==='center'?(h-total)/2:s.align==='right'?h-total:0;chars.forEach((c,j)=>{const g=glyph(c),b=textCommandBoundsV76(g);commands.push(...moveTextCommandsV76(g,x+(width-b.w)/2-b.minX,start+j*step+(fs-b.h)/2-b.minY));});const thick=Math.max(.12,fs*.055);if(s.underline&&total)commands.push(...rectangle(x+fs+fs*.08,start,thick,total));if(s.strike&&total)commands.push(...rectangle(x+fs*.5,start,thick,total));runs.push({x,y:start,width:fs,text:chars.join('')});});
 }
 const bounds=textCommandBoundsV76(commands),overflow=bounds.minX< -.01||bounds.minY< -.01||bounds.maxX>w+.01||bounds.maxY>h+.01;return{commands,bounds,runs,lines:rows.length,color:s.color,style:s,overflow};
}
