import { buildFoldGraph } from './foldgraph.js';
import { renderTemplate, isPackageNoticeVisible } from './variables.js';

let currentDispose=null;
async function loadThree(){if(globalThis.THREE)return globalThis.THREE;throw new Error('Three.js runtime not bundled; use offline canvas renderer')}

function smooth(t){return t*t*(3-2*t)}
function panelLabel(node,state){const pid=node.artPanel||node.id,els=(state.elements||[]).filter(e=>e.panelId===pid&&!(e.type==='notice'&&!isPackageNoticeVisible(state.variables)));const sku=els.find(e=>e.id==='sku'||String(e.template||'').includes('{{sku}}'));return sku?renderTemplate(sku.template,state.variables):node.label}

function panelTexture(THREE,node,state){
  const canvas=document.createElement('canvas'),ratio=Math.max(.35,Math.min(4,node.w/Math.max(node.h,1)));canvas.width=ratio>=1?768:Math.round(768*ratio);canvas.height=ratio>=1?Math.round(768/ratio):768;
  const ctx=canvas.getContext('2d');ctx.fillStyle='#d8c2a0';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#6d5b45';ctx.lineWidth=3;ctx.strokeRect(2,2,canvas.width-4,canvas.height-4);
  const panelId=node.artPanel||node.id,els=(state.elements||[]).filter(e=>e.panelId===panelId&&!(e.type==='notice'&&!isPackageNoticeVisible(state.variables))),sx=canvas.width/Math.max(node.w,1),sy=canvas.height/Math.max(node.h,1);
  for(const el of els){const x=Number(el.x||0)*sx,y=Number(el.y||0)*sy,w=Number(el.w||0)*sx,h=Number(el.h||0)*sy;ctx.save();ctx.translate(x+w/2,y+h/2);ctx.rotate((Number(el.r)||0)*Math.PI/180);ctx.translate(-w/2,-h/2);ctx.strokeStyle='#1c1c1c';ctx.fillStyle='#1c1c1c';if(el.type==='text'||el.type==='notice'){const text=renderTemplate(el.template,state.variables),fs=Math.max(8,Math.min(34,(Number(el.fontSize)||8)*Math.min(sx,sy)*.9));ctx.font=`${el.bold?'700 ':'600 '}${fs}px Arial`;ctx.textBaseline='top';text.split('\n').forEach((line,i)=>ctx.fillText(line,2,2+i*fs*1.12,Math.max(4,w-4)))}else if(el.type==='icon'){ctx.lineWidth=Math.max(2,Math.min(8,w*.05));ctx.strokeRect(1,1,Math.max(2,w-2),Math.max(2,h-2));ctx.font=`700 ${Math.max(12,h*.55)}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(el.icon==='up'?'↑↑':el.icon==='fragile'?'Y':'☂',w/2,h/2)}else if(el.type==='barcode-qr-group'){ctx.strokeRect(1,1,Math.max(2,w-2),Math.max(2,h-2));const q=Math.min(h*.78,w*.28);ctx.strokeRect(w-q-4,4,q,q);const bw=Math.max(10,w-q-14);for(let bx=5,i=0;bx<bw;bx+=Math.max(2,w*.012),i++)ctx.fillRect(bx,6,i%3?Math.max(1,w*.006):Math.max(2,w*.012),Math.max(8,h*.65));ctx.font=`600 ${Math.max(7,h*.12)}px Arial`;ctx.textAlign='left';ctx.textBaseline='bottom';ctx.fillText(renderTemplate(el.barcodeValue,state.variables),5,h-3,Math.max(5,bw-6))}else if(el.type==='shape')ctx.strokeRect(1,1,Math.max(2,w-2),Math.max(2,h-2));else if(el.type==='line'){ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(w,h);ctx.stroke()}ctx.restore()}
  if(!els.length){ctx.fillStyle='rgba(20,20,20,.28)';ctx.font='600 24px Arial';ctx.textAlign='center';ctx.fillText(node.label,canvas.width/2,canvas.height/2)}
  const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=4;return tex;
}

function centeredPoint(THREE,geo,x,y){return new THREE.Vector3(x-geo.width/2,-(y-geo.height/2),0)}
function rotationAboutLine(THREE,geo,hinge,angle){const p1=centeredPoint(THREE,geo,hinge.x1,hinge.y1),p2=centeredPoint(THREE,geo,hinge.x2,hinge.y2),axis=p2.clone().sub(p1).normalize(),t1=new THREE.Matrix4().makeTranslation(p1.x,p1.y,p1.z),r=new THREE.Matrix4().makeRotationAxis(axis,angle),t2=new THREE.Matrix4().makeTranslation(-p1.x,-p1.y,-p1.z);return t1.multiply(r).multiply(t2)}

function mountThree(container,state,geo,graph,THREE,onStatus){
  onStatus?.('three');container.innerHTML='';const scene=new THREE.Scene();scene.background=new THREE.Color(0x20242b);const camera=new THREE.PerspectiveCamera(42,1,.01,3000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;container.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x4d4438,2.4));const dl=new THREE.DirectionalLight(0xffffff,2);dl.position.set(5,8,7);scene.add(dl);
  const group=new THREE.Group(),scale=1/Math.max(80,Math.max(geo.structure.length,geo.structure.width,geo.structure.height)/5);group.scale.setScalar(scale);group.rotation.x=-.34;group.rotation.y=.55;scene.add(group);const nodeMap=new Map(graph.nodes.map(n=>[n.id,n])),meshMap=new Map();
  for(const node of graph.nodes){let geom,map=null;if(node.points?.length>=3){const p=geo.panelMap[node.id]||geo.panelMap[node.artPanel],cx=p.x+p.w/2,cy=p.y+p.h/2,shape=new THREE.Shape();node.points.forEach((q,i)=>{const x=q[0]-cx,y=-(q[1]-cy);i?shape.lineTo(x,y):shape.moveTo(x,y)});shape.closePath();geom=new THREE.ShapeGeometry(shape)}else{geom=new THREE.PlaneGeometry(Math.max(.01,node.w),Math.max(.01,node.h));map=panelTexture(THREE,node,state)}const mat=new THREE.MeshStandardMaterial({map,color:map?0xffffff:0xd8c2a0,side:THREE.DoubleSide,roughness:.78,metalness:0,transparent:(node.opacity??1)<1,opacity:node.opacity??1});const mesh=new THREE.Mesh(geom,mat);mesh.matrixAutoUpdate=false;group.add(mesh);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(geom),new THREE.LineBasicMaterial({color:0x2b261f,transparent:true,opacity:.75}));mesh.add(edge);meshMap.set(node.id,mesh)}
  const children=new Map();for(const e of graph.edges){if(!children.has(e.from))children.set(e.from,[]);children.get(e.from).push(e)}
  function applyNode(id,parentMatrix,t){const node=nodeMap.get(id),mesh=meshMap.get(id);if(!node||!mesh)return;const p=geo.panelMap[id]||geo.panelMap[node.artPanel];if(!p)return;const c=centeredPoint(THREE,geo,p.x+p.w/2,p.y+p.h/2),centerT=new THREE.Matrix4().makeTranslation(c.x,c.y,c.z);mesh.matrix.copy(parentMatrix).multiply(centerT);mesh.matrixWorldNeedsUpdate=true;for(const edge of children.get(id)||[]){const theta=(Number(edge.angle)||0)*Math.PI/180*t,rot=edge.hinge?rotationAboutLine(THREE,geo,edge.hinge,theta):new THREE.Matrix4(),childM=parentMatrix.clone().multiply(rot);applyNode(edge.to,childM,t)}}
  function setProgress(v){const t=smooth(Math.max(0,Math.min(1,Number(v)/100))),rootM=new THREE.Matrix4();applyNode(graph.root,rootM,t);const reached=new Set([graph.root]),walk=id=>{for(const e of children.get(id)||[]){reached.add(e.to);walk(e.to)}};walk(graph.root);for(const n of graph.nodes){if(reached.has(n.id))continue;const p=geo.panelMap[n.id];if(!p)continue;const c=centeredPoint(THREE,geo,p.x+p.w/2,p.y+p.h/2);meshMap.get(n.id)?.matrix.makeTranslation(c.x,c.y,c.z)}}
  setProgress(state.foldProgress??100);const maxWorld=Math.max(geo.width,geo.height,geo.structure.length+geo.structure.width+geo.structure.height)*scale;camera.position.set(maxWorld*.35,maxWorld*.32,maxWorld*1.2+3);camera.lookAt(0,0,0);let dragging=false,lastX=0,lastY=0;const down=e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)},move=e=>{if(!dragging)return;group.rotation.y+=(e.clientX-lastX)*.008;group.rotation.x+=(e.clientY-lastY)*.008;lastX=e.clientX;lastY=e.clientY},up=()=>dragging=false,wheel=e=>{e.preventDefault();camera.position.multiplyScalar(e.deltaY>0?1.08:.92)};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);renderer.domElement.addEventListener('wheel',wheel,{passive:false});const resize=()=>{const r=container.getBoundingClientRect(),w=Math.max(320,Math.floor(r.width)),h=Math.max(260,Math.floor(r.height));renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()},ro=new ResizeObserver(resize);ro.observe(container);resize();let raf=0;const tick=()=>{renderer.render(scene,camera);raf=requestAnimationFrame(tick)};tick();const dispose=()=>{cancelAnimationFrame(raf);ro.disconnect();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointercancel',up);renderer.domElement.removeEventListener('wheel',wheel);for(const mesh of meshMap.values()){mesh.geometry.dispose();mesh.material.map?.dispose();mesh.material.dispose()}renderer.dispose();container.innerHTML=''};return{setProgress,dispose,graph};
}

// Offline fallback: a small hinge-pivot renderer with no third-party runtime dependency.
const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
function mmul(A,B){const C=new Array(16).fill(0);for(let r=0;r<4;r++)for(let c=0;c<4;c++)for(let k=0;k<4;k++)C[r*4+c]+=A[r*4+k]*B[k*4+c];return C}
function tr(x,y,z){const m=I();m[3]=x;m[7]=y;m[11]=z;return m}
function rotAxis(ax,ay,az,a){const n=Math.hypot(ax,ay,az)||1,x=ax/n,y=ay/n,z=az/n,c=Math.cos(a),s=Math.sin(a),t=1-c;return[t*x*x+c,t*x*y-s*z,t*x*z+s*y,0,t*x*y+s*z,t*y*y+c,t*y*z-s*x,0,t*x*z-s*y,t*y*z+s*x,t*z*z+c,0,0,0,0,1]}
function applyM(m,p){const [x,y,z]=p;return[m[0]*x+m[1]*y+m[2]*z+m[3],m[4]*x+m[5]*y+m[6]*z+m[7],m[8]*x+m[9]*y+m[10]*z+m[11]]}
function rotLine(geo,h,a){const p1=[h.x1-geo.width/2,-(h.y1-geo.height/2),0],p2=[h.x2-geo.width/2,-(h.y2-geo.height/2),0],axis=[p2[0]-p1[0],p2[1]-p1[1],p2[2]-p1[2]];return mmul(mmul(tr(...p1),rotAxis(...axis,a)),tr(-p1[0],-p1[1],-p1[2]))}
function mountOffline(container,state,geo,graph,onStatus){
  onStatus?.('offline-canvas');container.innerHTML='';const canvas=document.createElement('canvas');canvas.className='offline-3d-canvas';container.appendChild(canvas);const ctx=canvas.getContext('2d'),nodeMap=new Map(graph.nodes.map(n=>[n.id,n])),children=new Map();for(const e of graph.edges){if(!children.has(e.from))children.set(e.from,[]);children.get(e.from).push(e)}let transforms=new Map(),progress=Number(state.foldProgress??100),yaw=.55,pitch=-.34,zoom=1,drag=false,lx=0,ly=0;
  function calculate(){transforms=new Map();const t=smooth(Math.max(0,Math.min(1,progress/100)));const visit=(id,M)=>{transforms.set(id,M);for(const e of children.get(id)||[]){const R=e.hinge?rotLine(geo,e.hinge,(Number(e.angle)||0)*Math.PI/180*t):I();visit(e.to,mmul(M,R))}};visit(graph.root,I());for(const n of graph.nodes)if(!transforms.has(n.id))transforms.set(n.id,I())}
  function view(p){let[x,y,z]=p;const cy=Math.cos(yaw),sy=Math.sin(yaw),cx=Math.cos(pitch),sx=Math.sin(pitch),x1=cy*x+sy*z,z1=-sy*x+cy*z,y1=cx*y-sx*z1,z2=sx*y+cx*z1;return[x1,y1,z2]}
  function paint(){const w=canvas.width/devicePixelRatio,h=canvas.height/devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#20242b';ctx.fillRect(0,0,w,h);const base=Math.min(w,h)*.72/Math.max(100,Math.max(geo.width,geo.height)),cam=Math.max(500,Math.max(geo.width,geo.height)*1.35),polys=[];for(const n of graph.nodes){const p=geo.panelMap[n.id]||geo.panelMap[n.artPanel];if(!p)continue;const M=transforms.get(n.id)||I(),basePts=p.points?.length>=3?p.points.map(q=>[q[0]-geo.width/2,-(q[1]-geo.height/2),0]):[[p.x-geo.width/2,-(p.y-geo.height/2),0],[p.x+p.w-geo.width/2,-(p.y-geo.height/2),0],[p.x+p.w-geo.width/2,-(p.y+p.h-geo.height/2),0],[p.x-geo.width/2,-(p.y+p.h-geo.height/2),0]],corners=basePts.map(q=>view(applyM(M,q))),avg=corners.reduce((a,q)=>a+q[2],0)/corners.length,pts=corners.map(q=>{const k=cam/(cam-q[2]);return[w/2+q[0]*base*zoom*k,h/2-q[1]*base*zoom*k]});polys.push({n,pts,z:avg})}polys.sort((a,b)=>a.z-b.z);for(const poly of polys){ctx.beginPath();poly.pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fillStyle='rgba(216,194,160,.93)';ctx.fill();ctx.strokeStyle='#5f5140';ctx.lineWidth=1.3;ctx.stroke();const cx=poly.pts.reduce((a,p)=>a+p[0],0)/poly.pts.length,cy=poly.pts.reduce((a,p)=>a+p[1],0)/poly.pts.length;ctx.fillStyle='rgba(25,25,25,.72)';ctx.font='600 11px Arial';ctx.textAlign='center';ctx.fillText(panelLabel(poly.n,state).slice(0,26),cx,cy)}}
  calculate();const resize=()=>{const r=container.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(320,Math.floor(r.width))*d;canvas.height=Math.max(260,Math.floor(r.height))*d;canvas.style.width=Math.max(320,Math.floor(r.width))+'px';canvas.style.height=Math.max(260,Math.floor(r.height))+'px';paint()},ro=new ResizeObserver(resize);ro.observe(container);const down=e=>{drag=true;lx=e.clientX;ly=e.clientY;canvas.setPointerCapture?.(e.pointerId)},move=e=>{if(!drag)return;yaw+=(e.clientX-lx)*.008;pitch+=(e.clientY-ly)*.008;pitch=Math.max(-1.45,Math.min(1.45,pitch));lx=e.clientX;ly=e.clientY;paint()},up=()=>drag=false,wheel=e=>{e.preventDefault();zoom*=e.deltaY>0?.92:1.08;zoom=Math.max(.25,Math.min(4,zoom));paint()};canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('wheel',wheel,{passive:false});resize();const dispose=()=>{ro.disconnect();canvas.remove();};return{setProgress(v){progress=Number(v);calculate();paint()},dispose,graph};
}

export async function mountThreePreview(container,state,geo,{onStatus}={}){if(currentDispose){currentDispose();currentDispose=null}if(!container)return null;const graph=buildFoldGraph(geo);container.innerHTML='<div class="three-loading">Loading 3D renderer…</div>';let ctrl;try{const THREE=await loadThree();ctrl=mountThree(container,state,geo,graph,THREE,onStatus)}catch(err){ctrl=mountOffline(container,state,geo,graph,onStatus);const note=document.createElement('div');note.className='offline-3d-badge';note.textContent='OFFLINE 3D · no CDN required';container.appendChild(note)}currentDispose=ctrl.dispose;return ctrl}
export function disposeThreePreview(){if(currentDispose){currentDispose();currentDispose=null}}
