import { buildTextureProofModel } from './threeArtworkProof.js';
import { renderPanelArtworkCanvas } from './panelArtwork.js';
import { buildFoldTransformsV50 } from './threeArtworkProofV50.js';

const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clamp=(v,min,max)=>Math.min(max,Math.max(min,num(v,min)));
const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
const applyM=(m,p)=>[m[0]*p[0]+m[1]*p[1]+m[2]*p[2]+m[3],m[4]*p[0]+m[5]*p[1]+m[6]*p[2]+m[7],m[8]*p[0]+m[9]*p[1]+m[10]*p[2]+m[11]];
const add3=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];
const clone=v=>structuredClone(v);

function affineFromTriangles(src,dst){const[x0,y0]=src[0],[x1,y1]=src[1],[x2,y2]=src[2],[X0,Y0]=dst[0],[X1,Y1]=dst[1],[X2,Y2]=dst[2],det=x0*(y1-y2)+x1*(y2-y0)+x2*(y0-y1);if(Math.abs(det)<1e-9)return null;const a=(X0*(y1-y2)+X1*(y2-y0)+X2*(y0-y1))/det,c=(X0*(x2-x1)+X1*(x0-x2)+X2*(x1-x0))/det,e=(X0*(x1*y2-x2*y1)+X1*(x2*y0-x0*y2)+X2*(x0*y1-x1*y0))/det,b=(Y0*(y1-y2)+Y1*(y2-y0)+Y2*(y0-y1))/det,d=(Y0*(x2-x1)+Y1*(x0-x2)+Y2*(x1-x0))/det,f=(Y0*(x1*y2-x2*y1)+Y1*(x2*y0-x0*y2)+Y2*(x0*y1-x1*y0))/det;return[a,b,c,d,e,f]}
function drawTextureTriangle(ctx,image,src,dst){const m=affineFromTriangles(src,dst);if(!m)return;ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.beginPath();ctx.moveTo(...dst[0]);ctx.lineTo(...dst[1]);ctx.lineTo(...dst[2]);ctx.closePath();ctx.clip();ctx.setTransform(...m);ctx.drawImage(image,0,0);ctx.restore()}
function pointInPolygon(point,polygon=[]){let inside=false;const[x,y]=point;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const[xi,yi]=polygon[i],[xj,yj]=polygon[j],intersect=((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi||1e-9)+xi);if(intersect)inside=!inside}return inside}
function panelBounds(panel={}){if(Array.isArray(panel.points)&&panel.points.length>=3){const xs=panel.points.map(p=>num(p?.[0])),ys=panel.points.map(p=>num(p?.[1]));const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);return{x:minX,y:minY,w:maxX-minX,h:maxY-minY}}return{x:num(panel.x),y:num(panel.y),w:Math.max(.001,num(panel.w,1)),h:Math.max(.001,num(panel.h,1))}}
function depthMap(graph){const out=new Map([[graph?.root,0]]),children=new Map();for(const edge of graph?.edges||[]){if(!children.has(edge.from))children.set(edge.from,[]);children.get(edge.from).push(edge.to)}const q=graph?.root?[graph.root]:[];while(q.length){const id=q.shift(),depth=out.get(id)||0;for(const child of children.get(id)||[])if(!out.has(child)){out.set(child,depth+1);q.push(child)}}return out}
function normalizeAuthoring(value={}){return{edgeAngles:{...(value.edgeAngles||{})},edgeProgress:{...(value.edgeProgress||{})},explode:clamp(value.explode??0,0,1),dimensionsVisible:value.dimensionsVisible!==false,selectedEdgeKey:value.selectedEdgeKey||null,penetrationPanels:[...(value.collisionPanels||value.penetrationPanels||[])],overlapPanels:[...(value.overlapPanels||[])],activePanels:[...(value.activePanels||[])]}}

export function mountCollisionProofV52(container,state,geo,graph,{selectedPanelId=null,onSelectPanel=null,materialStyle=null,authoring=null,maxTexturePixels=720,onStatus=null}={}){
  if(typeof document==='undefined')throw new Error('V0.52 collision renderer requires a browser document.');if(!container)throw new Error('V0.52 collision renderer container is required.');
  container.innerHTML='';const model=buildTextureProofModel(state,geo,graph),canvas=document.createElement('canvas');canvas.className='v17-proof-renderer v50-proof-renderer v52-collision-renderer';canvas.dataset.v52Renderer='true';container.appendChild(canvas);const ctx=canvas.getContext('2d'),textures=new Map(),face=materialStyle?.face||'#d8c2a0',edgeColor=materialStyle?.edge||'rgba(70,58,44,.88)',edgeWidth=Math.max(1,num(materialStyle?.edgePreviewPx,1.2));for(const panel of model.panels){if(panel.plan)textures.set(panel.nodeId,renderPanelArtworkCanvas(panel.plan,{maxPixels:maxTexturePixels,background:face}))}
  let progress=num(state?.foldProgress,100),yaw=.55,pitch=-.34,zoom=1,drag=false,lx=0,ly=0,downX=0,downY=0,moved=false,disposed=false,lastDraw=[],selected=selectedPanelId,opts=normalizeAuthoring(authoring||{});const depths=depthMap(graph),nodeIndex=new Map((graph?.nodes||[]).map((node,index)=>[node.id,index]));onStatus?.({mode:'software-texture-3d-v52',collisionVisualization:true,...model.stats});
  const view=p=>{const[x,y,z]=p,cy=Math.cos(yaw),sy=Math.sin(yaw),cx=Math.cos(pitch),sx=Math.sin(pitch),x1=cy*x+sy*z,z1=-sy*x+cy*z,y1=cx*y-sx*z1,z2=sx*y+cx*z1;return[x1,y1,z2]};
  const panelOffset=(nodeId,panel)=>{const amount=opts.explode*Math.max(geo.width,geo.height)*.2;if(amount<=.0001||nodeId===graph.root)return[0,0,0];const b=panelBounds(panel),cx=b.x+b.w/2-geo.width/2,cy=-(b.y+b.h/2-geo.height/2),mag=Math.hypot(cx,cy);let dx,dy;if(mag>.001){dx=cx/mag;dy=cy/mag}else{const a=((nodeIndex.get(nodeId)||1)*2.3999632297);dx=Math.cos(a);dy=Math.sin(a)}return[dx*amount,dy*amount,(depths.get(nodeId)||1)*amount*.12]};
  const projectFactory=(w,h,base,cam)=>p=>{const q=view(p),k=cam/(cam-q[2]);return[w/2+q[0]*base*zoom*k,h/2-q[1]*base*zoom*k]};
  function label(pts,text,fill='#111820',color='#fff'){const cx=pts.reduce((s,p)=>s+p[0],0)/pts.length,cy=pts.reduce((s,p)=>s+p[1],0)/pts.length;ctx.save();ctx.font='700 10px system-ui,sans-serif';const tw=ctx.measureText(text).width+12;ctx.fillStyle=fill;ctx.fillRect(cx-tw/2,cy-9,tw,18);ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,cx,cy);ctx.restore()}
  function paint(){if(disposed)return;const d=Math.min(globalThis.devicePixelRatio||1,2),w=canvas.width/d,h=canvas.height/d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#181b20';ctx.fillRect(0,0,w,h);const transforms=buildFoldTransformsV50(graph,geo,progress,opts),base=Math.min(w,h)*.72/Math.max(100,Math.max(geo.width,geo.height)),cam=Math.max(500,Math.max(geo.width,geo.height)*1.35),project=projectFactory(w,h,base,cam),draw=[];
    for(const item of model.panels){const M=transforms.get(item.nodeId)||I(),offset=panelOffset(item.nodeId,item.panel),world=item.uvMap.points.map(q=>add3(applyM(M,[q[0]-geo.width/2,-(q[1]-geo.height/2),0]),offset)),projected=world.map(project),z=world.reduce((sum,q)=>sum+view(q)[2],0)/Math.max(1,world.length);draw.push({item,projected,z})}
    draw.sort((a,b)=>a.z-b.z);lastDraw=draw;const penetration=new Set(opts.penetrationPanels),overlap=new Set(opts.overlapPanels),active=new Set(opts.activePanels);
    for(const entry of draw){const item=entry.item,texture=textures.get(item.nodeId),uv=item.uvMap.uv,pts=entry.projected;if(texture){for(const tri of item.uvMap.triangles){const src=tri.map(i=>[uv[i][0]*texture.width,uv[i][1]*texture.height]),dst=tri.map(i=>pts[i]);drawTextureTriangle(ctx,texture,src,dst)}}else{ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(...q):ctx.moveTo(...q));ctx.closePath();ctx.fillStyle=face;ctx.fill()}
      ctx.setTransform(d,0,0,d,0,0);ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(...q):ctx.moveTo(...q));ctx.closePath();const id=item.panelId,isP=penetration.has(id),isO=overlap.has(id),isA=active.has(id),isS=id===selected;let stroke=isS?'#52a8ff':edgeColor,width=isS?Math.max(3,edgeWidth+1.5):edgeWidth,fill=null;if(isO){stroke='#ff9f43';width=Math.max(width,3);fill='rgba(255,159,67,.20)'}if(isP){stroke='#ff4d5a';width=Math.max(width,4);fill='rgba(255,77,90,.23)'}if(isA){stroke='#ffe08a';width=Math.max(width,5)}ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();if(fill){ctx.save();ctx.fillStyle=fill;ctx.fill();ctx.restore()}if(isA)label(pts,isP?'PENETRATION':isO?'OVERLAP':'COLLISION',isP?'#7b1e28':isO?'#754711':'#645a20','#fff')}
  }
  const resize=()=>{const r=container.getBoundingClientRect(),d=Math.min(globalThis.devicePixelRatio||1,2),w=Math.max(320,Math.floor(r.width||720)),h=Math.max(300,Math.floor(r.height||500));canvas.width=w*d;canvas.height=h*d;canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;paint()};
  const down=e=>{drag=true;lx=e.clientX;ly=e.clientY;downX=e.clientX;downY=e.clientY;moved=false;try{canvas.setPointerCapture?.(e.pointerId)}catch{}},move=e=>{if(!drag)return;if(Math.hypot(e.clientX-downX,e.clientY-downY)>4)moved=true;yaw+=(e.clientX-lx)*.008;pitch=Math.max(-1.45,Math.min(1.45,pitch+(e.clientY-ly)*.008));lx=e.clientX;ly=e.clientY;paint()},up=e=>{if(!drag)return;drag=false;if(!moved&&typeof onSelectPanel==='function'){const rect=canvas.getBoundingClientRect(),d=Math.min(globalThis.devicePixelRatio||1,2),logicalW=canvas.width/d,logicalH=canvas.height/d,point=[(e.clientX-rect.left)*logicalW/Math.max(1,rect.width),(e.clientY-rect.top)*logicalH/Math.max(1,rect.height)];for(let i=lastDraw.length-1;i>=0;i--){if(pointInPolygon(point,lastDraw[i].projected)){selected=lastDraw[i].item.panelId;onSelectPanel(selected,{nodeId:lastDraw[i].item.nodeId,source:'3d-v52'});paint();break}}}},cancel=()=>{drag=false},wheel=e=>{e.preventDefault();zoom=Math.max(.35,Math.min(3,zoom*(e.deltaY>0?.92:1.08)));paint()};
  canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('wheel',wheel,{passive:false});const ro=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;ro?.observe(container);resize();
  return{model,setProgress(v){progress=clamp(v,0,100);paint()},setSelectedPanel(id){selected=id||null;paint()},setAuthoring(value){opts=normalizeAuthoring(value||{});paint()},setView({yaw:ny,pitch:np,zoom:nz}={}){if(Number.isFinite(ny))yaw=ny;if(Number.isFinite(np))pitch=np;if(Number.isFinite(nz))zoom=nz;paint()},getDebugState(){return{progress,selected,authoring:clone(opts),drawnPanels:lastDraw.map(x=>x.item.panelId),penetrationPanels:[...opts.penetrationPanels],overlapPanels:[...opts.overlapPanels],activePanels:[...opts.activePanels]}},repaint:paint,dispose(){disposed=true;ro?.disconnect();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancel);canvas.removeEventListener('wheel',wheel);container.innerHTML=''}};
}
