import { buildTextureProofModel } from './threeArtworkProof.js';
import { renderPanelArtworkCanvas } from './panelArtwork.js';

const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clone=v=>structuredClone(v);
const clamp=(v,min,max)=>Math.min(max,Math.max(min,num(v,min)));
const edgeKey=e=>`${e?.from||''}->${e?.to||''}`;
const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
function mmul(A,B){const C=new Array(16).fill(0);for(let r=0;r<4;r++)for(let c=0;c<4;c++)for(let k=0;k<4;k++)C[r*4+c]+=A[r*4+k]*B[k*4+c];return C}
function tr(x,y,z){const m=I();m[3]=x;m[7]=y;m[11]=z;return m}
function rotAxis(ax,ay,az,a){const n=Math.hypot(ax,ay,az)||1,x=ax/n,y=ay/n,z=az/n,c=Math.cos(a),s=Math.sin(a),t=1-c;return[t*x*x+c,t*x*y-s*z,t*x*z+s*y,0,t*x*y+s*z,t*y*y+c,t*y*z-s*x,0,t*x*z-s*y,t*y*z+s*x,t*z*z+c,0,0,0,0,1]}
function applyM(m,p){const[x,y,z]=p;return[m[0]*x+m[1]*y+m[2]*z+m[3],m[4]*x+m[5]*y+m[6]*z+m[7],m[8]*x+m[9]*y+m[10]*z+m[11]]}
function rotLine(geo,h,a){const p1=[h.x1-geo.width/2,-(h.y1-geo.height/2),0],p2=[h.x2-geo.width/2,-(h.y2-geo.height/2),0],axis=[p2[0]-p1[0],p2[1]-p1[1],p2[2]-p1[2]];return mmul(mmul(tr(...p1),rotAxis(...axis,a)),tr(-p1[0],-p1[1],-p1[2]))}
function smooth(t){return t*t*(3-2*t)}
function normalizedAuthoring(value={}){return{edgeAngles:{...(value.edgeAngles||{})},edgeProgress:{...(value.edgeProgress||{})},explode:clamp(value.explode??0,0,1),dimensionsVisible:value.dimensionsVisible!==false,selectedEdgeKey:value.selectedEdgeKey||null}}

export function buildFoldTransformsV50(graph,geo,progress=100,authoring={}){
  const opts=normalizedAuthoring(authoring),children=new Map();for(const edge of graph?.edges||[]){if(!children.has(edge.from))children.set(edge.from,[]);children.get(edge.from).push(edge)}
  const transforms=new Map(),globalT=smooth(clamp(progress,0,100)/100),visit=(id,M)=>{transforms.set(id,M);for(const edge of children.get(id)||[]){const key=edgeKey(edge),rawProgress=Object.prototype.hasOwnProperty.call(opts.edgeProgress,key)?opts.edgeProgress[key]:globalT*100,t=smooth(clamp(rawProgress,0,100)/100),angle=Number.isFinite(Number(opts.edgeAngles[key]))?Number(opts.edgeAngles[key]):num(edge.angle),R=edge.hinge?rotLine(geo,edge.hinge,angle*Math.PI/180*t):I();visit(edge.to,mmul(M,R))}};
  if(graph?.components?.length){for(const c of graph.components){let M=I();if(c.assembly){const a=c.assembly,t=globalT,flat=[a.flatCenter[0]-geo.width/2,-(a.flatCenter[1]-geo.height/2),0],target=[a.target[0]-geo.width/2,-(a.target[1]-geo.height/2),a.target[2]],pos=flat.map((v,i)=>v+(target[i]-v)*t);M=mmul(mmul(tr(...pos),rotAxis(1,0,0,num(a.rotationX)*Math.PI/180*t)),tr(-flat[0],-flat[1],0));}visit(c.root,M);}}else if(graph?.root)visit(graph.root,I());for(const node of graph?.nodes||[])if(!transforms.has(node.id))transforms.set(node.id,I());return transforms;
}

function affineFromTriangles(src,dst){const[x0,y0]=src[0],[x1,y1]=src[1],[x2,y2]=src[2],[X0,Y0]=dst[0],[X1,Y1]=dst[1],[X2,Y2]=dst[2],det=x0*(y1-y2)+x1*(y2-y0)+x2*(y0-y1);if(Math.abs(det)<1e-9)return null;const a=(X0*(y1-y2)+X1*(y2-y0)+X2*(y0-y1))/det,c=(X0*(x2-x1)+X1*(x0-x2)+X2*(x1-x0))/det,e=(X0*(x1*y2-x2*y1)+X1*(x2*y0-x0*y2)+X2*(x0*y1-x1*y0))/det,b=(Y0*(y1-y2)+Y1*(y2-y0)+Y2*(y0-y1))/det,d=(Y0*(x2-x1)+Y1*(x0-x2)+Y2*(x1-x0))/det,f=(Y0*(x1*y2-x2*y1)+Y1*(x2*y0-x0*y2)+Y2*(x0*y1-x1*y0))/det;return[a,b,c,d,e,f]}
function drawTextureTriangle(ctx,image,src,dst){const m=affineFromTriangles(src,dst);if(!m)return;ctx.save();ctx.beginPath();ctx.moveTo(...dst[0]);ctx.lineTo(...dst[1]);ctx.lineTo(...dst[2]);ctx.closePath();ctx.clip();ctx.transform(...m);ctx.drawImage(image,0,0);ctx.restore()}
function pointInPolygon(point,polygon=[]){let inside=false;const[x,y]=point;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const[xi,yi]=polygon[i],[xj,yj]=polygon[j],intersect=((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi||1e-9)+xi);if(intersect)inside=!inside}return inside}
function panelBounds(panel={}){if(Array.isArray(panel.points)&&panel.points.length>=3){const xs=panel.points.map(p=>num(p?.[0])),ys=panel.points.map(p=>num(p?.[1]));const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);return{x:minX,y:minY,w:maxX-minX,h:maxY-minY}}return{x:num(panel.x),y:num(panel.y),w:Math.max(.001,num(panel.w,1)),h:Math.max(.001,num(panel.h,1))}}
function depthMap(graph){const out=new Map([[graph?.root,0]]),children=new Map();for(const edge of graph?.edges||[]){if(!children.has(edge.from))children.set(edge.from,[]);children.get(edge.from).push(edge.to)}const q=graph?.root?[graph.root]:[];while(q.length){const id=q.shift(),depth=out.get(id)||0;for(const child of children.get(id)||[])if(!out.has(child)){out.set(child,depth+1);q.push(child)}}return out}
function add3(a,b){return[a[0]+b[0],a[1]+b[1],a[2]+b[2]]}

export function mountArtworkProofV50(container,state,geo,graph,{maxTexturePixels=720,onStatus=null,selectedPanelId=null,onSelectPanel=null,materialStyle=null,authoring=null}={}){
  if(typeof document==='undefined')throw new Error('V0.50 3D artwork proof requires a browser document.');if(!container)throw new Error('V0.50 3D artwork proof container is required.');
  container.innerHTML='';const model=buildTextureProofModel(state,geo,graph),canvas=document.createElement('canvas');canvas.className='v17-proof-renderer v50-proof-renderer';container.appendChild(canvas);const ctx=canvas.getContext('2d'),textures=new Map(),face=materialStyle?.face||'#d8c2a0',edgeColor=materialStyle?.edge||'rgba(70,58,44,.88)',edgeWidth=Math.max(1,num(materialStyle?.edgePreviewPx,1.2));for(const panel of model.panels){if(panel.plan)textures.set(panel.nodeId,renderPanelArtworkCanvas(panel.plan,{maxPixels:maxTexturePixels,background:face}))}
  let progress=num(state?.foldProgress,100),yaw=.55,pitch=-.34,zoom=1,drag=false,lx=0,ly=0,downX=0,downY=0,moved=false,disposed=false,lastDraw=[],selected=selectedPanelId,foldAuthoring=normalizedAuthoring(authoring||{});const depths=depthMap(graph),nodeIndex=new Map((graph?.nodes||[]).map((node,index)=>[node.id,index]));onStatus?.({mode:'software-texture-3d-v50',authoring:true,...model.stats});
  const view=p=>{let[x,y,z]=p;const cy=Math.cos(yaw),sy=Math.sin(yaw),cx=Math.cos(pitch),sx=Math.sin(pitch),x1=cy*x+sy*z,z1=-sy*x+cy*z,y1=cx*y-sx*z1,z2=sx*y+cx*z1;return[x1,y1,z2]};
  const panelOffset=(nodeId,panel)=>{const amount=foldAuthoring.explode*Math.max(geo.width,geo.height)*.2;if(amount<=.0001||nodeId===graph.root)return[0,0,0];const b=panelBounds(panel),cx=b.x+b.w/2-geo.width/2,cy=-(b.y+b.h/2-geo.height/2),mag=Math.hypot(cx,cy);let dx,dy;if(mag>.001){dx=cx/mag;dy=cy/mag}else{const a=((nodeIndex.get(nodeId)||1)*2.3999632297);dx=Math.cos(a);dy=Math.sin(a)}return[dx*amount,dy*amount,(depths.get(nodeId)||1)*amount*.12]};
  const projectFactory=(w,h,base,cam)=>p=>{const q=view(p),k=cam/(cam-q[2]);return[w/2+q[0]*base*zoom*k,h/2-q[1]*base*zoom*k]};
  function drawDimensionLabel(pts,panel){if(!pts?.length)return;const cx=pts.reduce((sum,p)=>sum+p[0],0)/pts.length,cy=pts.reduce((sum,p)=>sum+p[1],0)/pts.length,b=panelBounds(panel),text=`${b.w.toFixed(1)} × ${b.h.toFixed(1)} mm`;ctx.save();ctx.font='600 11px system-ui, sans-serif';const tw=ctx.measureText(text).width+14;ctx.fillStyle='rgba(10,17,24,.82)';ctx.fillRect(cx-tw/2,cy-10,tw,20);ctx.fillStyle='#dff3ff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,cx,cy);ctx.restore()}
  function paint(){if(disposed)return;const d=Math.min(globalThis.devicePixelRatio||1,2),w=canvas.width/d,h=canvas.height/d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#181b20';ctx.fillRect(0,0,w,h);const transforms=buildFoldTransformsV50(graph,geo,progress,foldAuthoring),base=Math.min(w,h)*.72/Math.max(100,Math.max(geo.width,geo.height)),cam=Math.max(500,Math.max(geo.width,geo.height)*1.35),project=projectFactory(w,h,base,cam),draw=[];
    for(const item of model.panels){const M=transforms.get(item.nodeId)||I(),offset=panelOffset(item.nodeId,item.panel),world=item.uvMap.points.map(q=>add3(applyM(M,[q[0]-geo.width/2,-(q[1]-geo.height/2),0]),offset)),projected=world.map(project),z=world.reduce((sum,q)=>sum+view(q)[2],0)/Math.max(1,world.length);draw.push({item,projected,z,offset})}
    draw.sort((a,b)=>a.z-b.z);lastDraw=draw;for(const entry of draw){const item=entry.item,texture=textures.get(item.nodeId),uv=item.uvMap.uv,pts=entry.projected;if(texture){for(const tri of item.uvMap.triangles){const src=tri.map(i=>[uv[i][0]*texture.width,uv[i][1]*texture.height]),dst=tri.map(i=>pts[i]);drawTextureTriangle(ctx,texture,src,dst)}}else{ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(...q):ctx.moveTo(...q));ctx.closePath();ctx.fillStyle=face;ctx.fill()}
      ctx.setTransform(d,0,0,d,0,0);ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(...q):ctx.moveTo(...q));ctx.closePath();const isSelected=item.panelId===selected;ctx.strokeStyle=isSelected?'#52a8ff':(item.uvMap.fallback?'#e6a23c':edgeColor);ctx.lineWidth=isSelected?Math.max(3,edgeWidth+1.5):(item.uvMap.fallback?Math.max(2,edgeWidth):edgeWidth);ctx.stroke();if(isSelected){ctx.save();ctx.globalAlpha=.12;ctx.fillStyle='#52a8ff';ctx.fill();ctx.restore();if(foldAuthoring.dimensionsVisible)drawDimensionLabel(pts,item.panel)}}
    const selectedEdge=(graph.edges||[]).find(edge=>edgeKey(edge)===foldAuthoring.selectedEdgeKey);if(selectedEdge?.hinge){const parentM=transforms.get(selectedEdge.from)||I(),parentPanel=geo.panelMap?.[selectedEdge.from]||{},offset=panelOffset(selectedEdge.from,parentPanel),p1=project(add3(applyM(parentM,[selectedEdge.hinge.x1-geo.width/2,-(selectedEdge.hinge.y1-geo.height/2),0]),offset)),p2=project(add3(applyM(parentM,[selectedEdge.hinge.x2-geo.width/2,-(selectedEdge.hinge.y2-geo.height/2),0]),offset));ctx.save();ctx.strokeStyle='#ffd166';ctx.lineWidth=3;ctx.setLineDash([8,5]);ctx.beginPath();ctx.moveTo(...p1);ctx.lineTo(...p2);ctx.stroke();ctx.restore()}
  }
  const resize=()=>{const r=container.getBoundingClientRect(),d=Math.min(globalThis.devicePixelRatio||1,2),w=Math.max(320,Math.floor(r.width||720)),h=Math.max(300,Math.floor(r.height||500));canvas.width=w*d;canvas.height=h*d;canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;paint()};
  const down=e=>{drag=true;lx=e.clientX;ly=e.clientY;downX=e.clientX;downY=e.clientY;moved=false;try{canvas.setPointerCapture?.(e.pointerId)}catch{}},move=e=>{if(!drag)return;if(Math.hypot(e.clientX-downX,e.clientY-downY)>4)moved=true;yaw+=(e.clientX-lx)*.008;pitch=Math.max(-1.45,Math.min(1.45,pitch+(e.clientY-ly)*.008));lx=e.clientX;ly=e.clientY;paint()},up=e=>{if(!drag)return;drag=false;if(!moved&&typeof onSelectPanel==='function'){const rect=canvas.getBoundingClientRect(),d=Math.min(globalThis.devicePixelRatio||1,2),logicalW=canvas.width/d,logicalH=canvas.height/d,point=[(e.clientX-rect.left)*logicalW/Math.max(1,rect.width),(e.clientY-rect.top)*logicalH/Math.max(1,rect.height)];for(let i=lastDraw.length-1;i>=0;i--){if(pointInPolygon(point,lastDraw[i].projected)){selected=lastDraw[i].item.panelId;onSelectPanel(selected,{nodeId:lastDraw[i].item.nodeId,source:'3d-v50'});paint();break}}}},cancel=()=>{drag=false},wheel=e=>{e.preventDefault();const factor=e.deltaY>0?.92:1.08;zoom=Math.max(.35,Math.min(3,zoom*factor));paint()};
  canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('wheel',wheel,{passive:false});const ro=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;ro?.observe(container);resize();
  return{model,setProgress(v){progress=clamp(v,0,100);paint()},setSelectedPanel(panelId){selected=panelId||null;paint()},getSelectedPanel(){return selected},setAuthoring(value){foldAuthoring=normalizedAuthoring(value||{});paint()},getAuthoring(){return clone(foldAuthoring)},getDebugState(){return{progress,selected,authoring:clone(foldAuthoring),drawnPanels:lastDraw.map(entry=>entry.item.panelId)}},setView({yaw:ny,pitch:np,zoom:nz}={}){if(Number.isFinite(ny))yaw=ny;if(Number.isFinite(np))pitch=np;if(Number.isFinite(nz))zoom=nz;paint()},repaint:paint,dispose(){disposed=true;ro?.disconnect();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancel);canvas.removeEventListener('wheel',wheel);container.innerHTML=''}};
}
