import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry, clampElementToPanel } from './geometry.js';
import { markEditorPanels } from './markLayout.js';
import { parseSvgMark, createSvgMarkElement, svgMarkPreviewMarkup, materializeSvgMarksForProduction } from './svgMark.js';
import { buildProductionPdf, downloadBytes } from './export.js';
import { createIndexedDbArtifactStore, createMemoryArtifactStore } from './artifactStore.js';
import { preparePersistentQueue, queueWithClaim, queueWithComplete, queueWithFailure, pausePersistentQueue, finalizePersistentPause, resumePersistentQueue, cancelPersistentQueue, finalizePersistentCancel, persistentQueueProgress, persistentQueueState } from './persistentBatch.js';
import { workerBatchEligibility } from './batchWorkerCore.js';
import { analyzeProjectMerge, applyProjectMerge, mergeSummary } from './projectMerge.js';
import { createRestProjectStore, reviseProjectEnvelope } from './projectStore.js';
import { activeProductionJob, approvalGate } from './productionJobs.js';
import { canProductionAction, normalizeProductionRole } from './permissions.js';

const BLOCK_ID='boxstudio-v15-tools';
const BASE_PREFIX='boxstudio-remote-base-v1:';
const artifactStore=globalThis.indexedDB?createIndexedDbArtifactStore():createMemoryArtifactStore();
let importedSvgMark=null,workerToken=0,activeWorker=null,mergeSession=null;

function clone(value){return structuredClone(value);}
function esc(value=''){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function safeName(value='boxstudio'){return String(value||'boxstudio').trim().replace(/[\\/:*?"<>|\s]+/g,'-').replace(/^-+|-+$/g,'')||'boxstudio';}
function readState(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return parsed?{...clone(defaultState),...parsed,batch:{...defaultState.batch,...(parsed.batch||{})}}:clone(defaultState);}catch{return clone(defaultState)}}
function writeState(state){state.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function actor(state){return String(state.productionActor||'local-user').trim()||'local-user';}
function remoteBaseKey(id){return `${BASE_PREFIX}${String(id||'project')}`;}
function loadRemoteBase(id){try{return JSON.parse(localStorage.getItem(remoteBaseKey(id))||'null');}catch{return null;}}
function saveRemoteBase(envelope){if(envelope?.id)localStorage.setItem(remoteBaseKey(envelope.id),JSON.stringify({id:envelope.id,revision:envelope.revision,state:envelope.state,updatedAt:envelope.updatedAt}));}
function brief(value){if(Array.isArray(value))return`Array(${value.length})`;if(value&&typeof value==='object')return`Object(${Object.keys(value).length})`;const s=String(value??'—');return s.length>48?s.slice(0,45)+'…':s;}
function yieldUi(){return new Promise(resolve=>setTimeout(resolve,0));}

function hideSuperseded(){const oldBatch=document.querySelector('#v14Batch')?.closest('section');if(oldBatch)oldBatch.hidden=true;const oldApproved=document.getElementById('v14ApprovedPdf');if(oldApproved)oldApproved.hidden=true;}

function renderSvgMarks(block){
  const host=block.querySelector('#v15SvgMarks');if(!host)return;const state=readState(),panels=markEditorPanels(state),symbols=(state.elements||[]).filter(element=>element.type==='svg-symbol'),selectedPanel=state.markEditorPanelId||panels[0]?.id||'front',gate=approvalGate(state,activeProductionJob(state)),role=normalizeProductionRole(state.productionRole||'operator'),canApproved=gate.ok&&canProductionAction(role,'export-approved');
  const mark=importedSvgMark;host.innerHTML=`<div class="v15-row"><label class="v15-file">Import SVG Logo<input id="v15SvgFile" type="file" accept="image/svg+xml,.svg"></label><label>Panel<select id="v15SvgPanel">${panels.map(panel=>`<option value="${esc(panel.id)}" ${panel.id===selectedPanel?'selected':''}>${esc(panel.label||panel.id)} · ${Math.round(panel.w)}×${Math.round(panel.h)} mm</option>`).join('')}</select></label><label>Width mm<input id="v15SvgWidth" type="number" min="4" step="1" value="80"></label><button id="v15InsertSvg" ${mark?'':'disabled'}>Insert SVG Mark</button></div>
  <div class="v15-svg-grid"><div class="v15-svg-preview">${mark?svgMarkPreviewMarkup(mark,{stroke:'#111'}):'<span>导入 SVG 后在这里预览安全矢量轮廓。</span>'}</div><div class="v15-svg-meta">${mark?`<b>${esc(mark.name)}</b><span>${mark.segmentCount} segments</span><span>${mark.width.toFixed(2)} × ${mark.height.toFixed(2)} source units</span><span>hash ${esc(mark.sourceHash)}</span>`:'<span>支持 path / line / rect / circle / ellipse / polygon / polyline；Bezier/Arc 会离散成矢量线段。</span>'}</div></div>
  <div class="v15-row"><button id="v15DraftPdf">Draft PDF + SVG Marks</button><button id="v15ApprovedPdf" ${canApproved?'':'disabled'}>Approved PDF + SVG Marks</button><span>${symbols.length} imported SVG mark(s) in project</span></div>
  <div class="v15-symbol-list">${symbols.map(element=>`<div><span><b>${esc(element.label||element.id)}</b><small>${esc(element.panelId)} · ${Number(element.w||0).toFixed(1)}×${Number(element.h||0).toFixed(1)} mm · ${element.svgMark?.segmentCount||0} seg</small></span><button data-v15-remove-svg="${esc(element.id)}" class="danger">Delete</button></div>`).join('')||'<div class="profile-empty">No imported SVG marks in the project.</div>'}</div>
  <p class="v15-note">安全边界：V0.15 将 SVG 转成黑色矢量轮廓线用于生产 PDF。不会执行 script、foreignObject、image、use 或外部 URL；复杂填充、渐变、裁剪、透明混合仍不等同于 Illustrator 完整 SVG 渲染。</p>`;
  host.querySelector('#v15SvgFile').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{importedSvgMark=parseSvgMark(await file.text(),{name:file.name.replace(/\.svg$/i,'')});renderSvgMarks(block);}catch(error){importedSvgMark=null;alert(error?.message||error);renderSvgMarks(block);}};
  host.querySelector('#v15SvgPanel').onchange=event=>{const next=readState();next.markEditorPanelId=event.target.value;writeState(next);};
  host.querySelector('#v15InsertSvg').onclick=()=>{if(!importedSvgMark)return;const current=readState(),panelId=host.querySelector('#v15SvgPanel').value,width=Math.max(4,Number(host.querySelector('#v15SvgWidth').value)||80),element=createSvgMarkElement(importedSvgMark,{panelId,x:10,y:10,width}),geo=generateGeometry(current.structure),clamped=clampElementToPanel(element,geo);current.elements=[...(current.elements||[]),clamped];current.selectedId=clamped.id;current.markEditorPanelId=panelId;writeState(current);renderSvgMarks(block);};
  host.querySelectorAll('[data-v15-remove-svg]').forEach(button=>button.onclick=()=>{const current=readState(),id=button.dataset.v15RemoveSvg;if(!confirm(`Delete SVG mark ${id}?`))return;current.elements=(current.elements||[]).filter(element=>element.id!==id);if(current.selectedId===id)current.selectedId=null;writeState(current);renderSvgMarks(block);});
  host.querySelector('#v15DraftPdf').onclick=()=>{try{const current=readState(),bytes=buildProductionPdf(materializeSvgMarksForProduction(current));downloadBytes(`${safeName(current.variables?.sku||'boxstudio')}-v15-draft.pdf`,bytes,'application/pdf');}catch(error){alert(error?.message||error)}};
  host.querySelector('#v15ApprovedPdf').onclick=()=>{const current=readState(),job=activeProductionJob(current),g=approvalGate(current,job),r=normalizeProductionRole(current.productionRole||'operator');if(!g.ok||!canProductionAction(r,'export-approved')){alert(g.ok?'Current role cannot export approved production files.':g.reason);return;}try{const bytes=buildProductionPdf(materializeSvgMarksForProduction(current));downloadBytes(`${safeName(current.variables?.sku||'production')}-approved-r${job.revision}-v15.pdf`,bytes,'application/pdf');}catch(error){alert(error?.message||error)}};
}

async function workerSnapshot(){const state=readState(),queue=state.batch?.queue,artifacts=queue?.id?await artifactStore.list(queue.id):[];return{state,queue,artifacts};}
function progressText(p,queue){return`${p.percent}% · ${p.completed} completed · ${p.failed} failed · ${p.pending} pending · ${p.artifactCount} persisted · ${Math.round((p.bytes||0)/1024)} KB${queue?.status?` · ${queue.status}`:''}`;}
async function renderWorkerBatch(block){
  const host=block.querySelector('#v15WorkerBatch');if(!host)return;const {state,queue,artifacts}=await workerSnapshot(),p=persistentQueueProgress(queue||{items:[]},artifacts),eligibility=workerBatchEligibility(state),supported=typeof Worker!=='undefined',usable=supported&&eligibility.ok;
  host.innerHTML=`<div class="v15-row"><button id="v15WorkerStart" ${usable?'':'disabled'}>${queue?.kind==='worker-pdf-zip-v15'?'Resume / Reconcile':'Start Worker Batch'}</button><button id="v15WorkerRestart" ${usable?'':'disabled'}>Restart</button><button id="v15WorkerPause" ${queue&&!p.done?'':'disabled'}>Pause</button><button id="v15WorkerCancel" ${queue&&!p.done?'':'disabled'}>Cancel</button><button id="v15WorkerZip" ${p.artifactCount?'':'disabled'}>Export Recovered ZIP</button></div><div class="v15-progress"><i style="width:${p.percent}%"></i></div><div class="v15-mono">${esc(progressText(p,queue))}</div>${usable?'<p>每个订单 PDF 在 module Web Worker 内生成；主线程只负责队列、IndexedDB 和 UI。</p>':`<div class="v15-warning">${!supported?'当前浏览器没有 Worker API。':eligibility.blockers.map(esc).join('<br>')}</div>`}`;
  host.querySelector('#v15WorkerStart').onclick=()=>runWorkerBatch(block,false);host.querySelector('#v15WorkerRestart').onclick=()=>runWorkerBatch(block,true);
  host.querySelector('#v15WorkerPause').onclick=()=>{const current=readState();if(!current.batch?.queue)return;current.batch.queue=pausePersistentQueue(current.batch.queue);writeState(current);renderWorkerBatch(block);};
  host.querySelector('#v15WorkerCancel').onclick=()=>{const current=readState();if(!current.batch?.queue)return;current.batch.queue=cancelPersistentQueue(current.batch.queue);writeState(current);renderWorkerBatch(block);};
  host.querySelector('#v15WorkerZip').onclick=()=>exportWorkerZip(block);
}
function runWorkerJob(worker,payload){return new Promise((resolve,reject)=>{const requestId=`w-${Date.now()}-${Math.random().toString(36).slice(2)}`,onMessage=event=>{if(event.data?.requestId!==requestId)return;cleanup();resolve(event.data);},onError=event=>{cleanup();reject(event.error||new Error(event.message||'PDF worker failed.'));},cleanup=()=>{worker.removeEventListener('message',onMessage);worker.removeEventListener('error',onError);};worker.addEventListener('message',onMessage);worker.addEventListener('error',onError);worker.postMessage({...payload,requestId});});}
async function runWorkerBatch(block,restart=false){
  const token=++workerToken;if(activeWorker){activeWorker.terminate();activeWorker=null;}let state=readState();if(!state.batch?.rows?.length){alert('请先导入 Excel / CSV。');return;}const eligibility=workerBatchEligibility(state);if(!eligibility.ok){alert(eligibility.blockers.join('\n'));return;}if(typeof Worker==='undefined'){alert('Current browser does not support Web Worker.');return;}
  if(restart&&state.batch?.queue?.id)await artifactStore.clearQueue(state.batch.queue.id);let artifacts=state.batch?.queue?.id?await artifactStore.list(state.batch.queue.id):[],queue=preparePersistentQueue(state,artifacts,{restart,kind:'worker-pdf-zip-v15'});if(queue.status==='paused')queue=resumePersistentQueue(queue);writeState(persistentQueueState(state,queue));await renderWorkerBatch(block);
  const worker=new Worker(new URL('./batchPdf.worker.js',import.meta.url),{type:'module'});activeWorker=worker;
  try{while(token===workerToken){state=readState();queue=state.batch.queue;artifacts=await artifactStore.list(queue.id);queue=preparePersistentQueue(state,artifacts,{kind:'worker-pdf-zip-v15'});if(queue.cancelRequested){queue=finalizePersistentCancel(queue);writeState(persistentQueueState(state,queue));break;}if(queue.pauseRequested){queue=finalizePersistentPause(queue);writeState(persistentQueueState(state,queue));break;}const claimed=queueWithClaim(queue);queue=claimed.queue;writeState(persistentQueueState(state,queue));if(!claimed.item)break;const index=claimed.item.index,row=state.batch.rows[index],baseState={...state,batch:{...(state.batch||{}),rows:[],queue:null}};
      try{const result=await runWorkerJob(worker,{baseState,row,index});if(result.ok){await artifactStore.put({queueId:queue.id,index,fileName:result.fileName,mime:'application/pdf',bytes:result.bytes,fingerprint:result.fingerprint});queue=queueWithComplete(queue,index,result.fileName);}else queue=queueWithFailure(queue,index,result.error||'Worker PDF generation failed.');}catch(error){queue=queueWithFailure(queue,index,error?.message||String(error));}
      state=readState();writeState(persistentQueueState(state,queue));await renderWorkerBatch(block);await yieldUi();}}
  finally{worker.terminate();if(activeWorker===worker)activeWorker=null;await renderWorkerBatch(block);}
}
async function exportWorkerZip(block){const {queue,artifacts}=await workerSnapshot();if(!queue||!artifacts.length)return;if(!globalThis.JSZip){alert('JSZip 未加载。');return;}const zip=new globalThis.JSZip();for(const artifact of artifacts)zip.file(artifact.fileName,artifact.bytes);zip.file('boxstudio-worker-artifacts.json',JSON.stringify({queueId:queue.id,kind:queue.kind,status:queue.status,files:artifacts.map(a=>({index:a.index,fileName:a.fileName,byteLength:a.byteLength,fingerprint:a.fingerprint}))},null,2));const bytes=await zip.generateAsync({type:'uint8array',compression:'DEFLATE',compressionOptions:{level:6}});downloadBytes(`boxstudio-${safeName(queue.id)}-worker-recovered.zip`,bytes,'application/zip');await renderWorkerBatch(block);}

function renderMerge(block){
  const host=block.querySelector('#v15Merge');if(!host)return;const state=readState(),endpoint=state.remoteProjectEndpoint||'',projectId=state.projectId||safeName(state.projectName||'boxstudio-project'),session=mergeSession,summary=session?mergeSummary(session.analysis):null;
  host.innerHTML=`<div class="v15-row"><label>REST Endpoint<input id="v15MergeEndpoint" value="${esc(endpoint)}" placeholder="https://your-api.example.com/boxstudio"></label><label>Project ID<input id="v15MergeProjectId" value="${esc(projectId)}"></label><button id="v15CompareRemote">Fetch & Compare</button>${session?'<button id="v15UseRemote">Use Remote</button><button id="v15ApplyMerge">Apply Merge Locally</button><button id="v15PushMerge">Push Merged Revision</button>':''}</div>${session?`<div class="v15-merge-summary">Base ${session.base?`r${session.base.revision}`:'none'} · Remote r${session.remote.revision} · ${summary.conflicts} conflict(s) · ${summary.localOnly} local-only · ${summary.remoteOnly} remote-only</div><div class="v15-conflicts">${session.analysis.entries.map(entry=>`<div class="${entry.status==='conflict'?'conflict':''}"><span><b>${esc(entry.path)}</b><small>${esc(entry.status)} · local ${esc(brief(entry.local))} · remote ${esc(brief(entry.remote))}</small></span>${entry.status==='conflict'?`<select data-v15-resolution="${esc(entry.path)}"><option value="">Choose…</option><option value="local" ${session.resolutions?.[entry.path]==='local'?'selected':''}>Keep Local</option><option value="remote" ${session.resolutions?.[entry.path]==='remote'?'selected':''}>Use Remote</option></select>`:'<span>auto</span>'}</div>`).join('')}</div>`:'<p>Fetch Remote 后按项目域做三方比较。只有存在已保存 Remote Base 时才自动区分 local-only / remote-only；没有 Base 的首次比较会把差异视为冲突，避免静默覆盖。</p>'}`;
  host.querySelector('#v15MergeEndpoint').onchange=e=>{const next=readState();next.remoteProjectEndpoint=e.target.value.trim();writeState(next);};host.querySelector('#v15MergeProjectId').onchange=e=>{const next=readState();next.projectId=e.target.value.trim();writeState(next);};
  host.querySelector('#v15CompareRemote').onclick=()=>compareRemote(block);host.querySelectorAll('[data-v15-resolution]').forEach(select=>select.onchange=()=>{if(mergeSession)mergeSession.resolutions[select.dataset.v15Resolution]=select.value;});
  const useRemote=host.querySelector('#v15UseRemote');if(useRemote)useRemote.onclick=()=>{const current=readState(),remote=mergeSession.remote,next={...current,...clone(remote.state),projectId:remote.id,projectRemoteRevision:Number(remote.revision)||0,remoteProjectEndpoint:host.querySelector('#v15MergeEndpoint').value.trim(),lastRemoteSyncAt:new Date().toISOString()};writeState(next);saveRemoteBase(remote);mergeSession=null;location.reload();};
  const apply=host.querySelector('#v15ApplyMerge');if(apply)apply.onclick=()=>applyMergeLocally(block,false);const push=host.querySelector('#v15PushMerge');if(push)push.onclick=()=>applyMergeLocally(block,true);
}
async function compareRemote(block){try{const state=readState(),endpoint=block.querySelector('#v15MergeEndpoint').value.trim(),id=block.querySelector('#v15MergeProjectId').value.trim();if(!endpoint||!id)throw new Error('REST Endpoint and Project ID are required.');const store=createRestProjectStore({baseUrl:endpoint}),remote=await store.load(id),base=loadRemoteBase(id),analysis=analyzeProjectMerge({baseState:base?.state||null,localState:state,remoteState:remote.state});mergeSession={remote,base,analysis,resolutions:{},endpoint,id};state.remoteProjectEndpoint=endpoint;state.projectId=id;writeState(state);renderMerge(block);}catch(error){alert(error?.message||error)}}
async function applyMergeLocally(block,pushRemote){if(!mergeSession)return;try{const current=readState(),merged=applyProjectMerge(mergeSession.analysis,{localState:current,remoteState:mergeSession.remote.state,resolutions:mergeSession.resolutions});if(merged.unresolved.length)throw new Error(`Resolve conflicts first: ${merged.unresolved.join(', ')}`);let next={...merged.state,projectId:mergeSession.remote.id,projectRemoteRevision:Number(mergeSession.remote.revision)||0,remoteProjectEndpoint:mergeSession.endpoint,lastRemoteSyncAt:new Date().toISOString()};if(pushRemote){const store=createRestProjectStore({baseUrl:mergeSession.endpoint}),envelope=reviseProjectEnvelope(mergeSession.remote,next,{updatedBy:actor(current)}),saved=await store.save(envelope,{expectedRevision:mergeSession.remote.revision});next={...next,projectRemoteRevision:Number(saved.revision)||envelope.revision,lastRemoteSyncAt:new Date().toISOString()};saveRemoteBase(saved);mergeSession=null;}else saveRemoteBase(mergeSession.remote);writeState(next);if(pushRemote)renderMerge(block);else{mergeSession=null;renderMerge(block);}}catch(error){alert(error?.message||error)}}

function install(){hideSuperseded();const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v15-tools';block.innerHTML=`<div class="v15-title"><div><h3>V0.15 Vector & Concurrent Production</h3><p>Safe SVG marks · Web Worker PDF batch · remote conflict resolver.</p></div><span>V0.15</span></div><section><h4>SVG Mark / Logo Import</h4><div id="v15SvgMarks"></div></section><section><h4>Worker Batch PDF</h4><div id="v15WorkerBatch"></div></section><section><h4>Remote Conflict Resolver</h4><div id="v15Merge"></div></section>`;scroll.appendChild(block);renderSvgMarks(block);renderWorkerBatch(block);renderMerge(block);}
function updateVersionLabel(){const version=document.querySelector('.brand small');if(version)version.textContent='V0.15';}
const observer=new MutationObserver(()=>{updateVersionLabel();hideSuperseded();install();});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersionLabel();install();
