import {setUiVersion} from './uiVersion.js';
import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry } from './geometry.js';
import { collectWorkerAssets, transferableWorkerAssets, workerAssetAvailability, describeWorkerAssets } from './workerAssets.js';
import { workerBatchEligibility } from './batchWorkerCore.js';
import { createIndexedDbArtifactStore, createMemoryArtifactStore } from './artifactStore.js';
import { preparePersistentQueue, queueWithClaim, queueWithComplete, queueWithFailure, pausePersistentQueue, finalizePersistentPause, resumePersistentQueue, cancelPersistentQueue, finalizePersistentCancel, persistentQueueProgress, persistentQueueState } from './persistentBatch.js';
import { downloadBytes } from './export.js';
import { analyzeObjectLevelMerge, applyObjectLevelResolutions, objectMergeSummary } from './projectMergeV2.js';
import { createRestProjectStore, reviseProjectEnvelope } from './projectStore.js';
import { buildArtworkAtlas, renderPanelArtworkCanvas } from './panelArtwork.js';

const BLOCK_ID='boxstudio-v16-tools',BASE_PREFIX='boxstudio-remote-base-v1:';
const artifactStore=globalThis.indexedDB?createIndexedDbArtifactStore():createMemoryArtifactStore();
let token=0,activeWorker=null,mergeSession=null;
function clone(v){return structuredClone(v)}
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function safe(v='boxstudio'){return String(v||'boxstudio').trim().replace(/[\\/:*?"<>|\s]+/g,'-').replace(/^-+|-+$/g,'')||'boxstudio'}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,batch:{...defaultState.batch,...(p.batch||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function loadBase(id){try{return JSON.parse(localStorage.getItem(`${BASE_PREFIX}${id}`)||'null')}catch{return null}}
function saveBase(e){if(e?.id)localStorage.setItem(`${BASE_PREFIX}${e.id}`,JSON.stringify({id:e.id,revision:e.revision,state:e.state,updatedAt:e.updatedAt}))}
function actor(s){return String(s.productionActor||'local-user').trim()||'local-user'}
function yieldUi(){return new Promise(r=>setTimeout(r,0))}
function hideSuperseded(){for(const id of ['v15WorkerBatch','v15Merge'])document.getElementById(id)?.closest('section')?.setAttribute('hidden','')}

function workerRequest(worker,data,transfer=[]){return new Promise((resolve,reject)=>{const requestId=`v16-${Date.now()}-${Math.random().toString(36).slice(2)}`,done=()=>{worker.removeEventListener('message',onMessage);worker.removeEventListener('error',onError)},onMessage=e=>{if(e.data?.requestId!==requestId)return;done();e.data?.ok===false?reject(new Error(e.data.error||'Worker failed')):resolve(e.data)},onError=e=>{done();reject(e.error||new Error(e.message||'Worker failed'))};worker.addEventListener('message',onMessage);worker.addEventListener('error',onError);worker.postMessage({...data,requestId},transfer)})}
async function workerSnapshot(){const state=readState(),queue=state.batch?.queue,artifacts=queue?.id?await artifactStore.list(queue.id):[];return{state,queue,artifacts}}
function progressText(p,q){return`${p.percent}% · ${p.completed} completed · ${p.failed} failed · ${p.pending} pending · ${p.artifactCount} persisted · ${Math.round((p.bytes||0)/1024)} KB${q?.status?` · ${q.status}`:''}`}
async function renderWorker(block){const host=block.querySelector('#v16Worker');if(!host)return;const snap=await workerSnapshot(),assets=collectWorkerAssets(),availability=workerAssetAvailability(assets),eligibility=workerBatchEligibility(snap.state,availability),desc=describeWorkerAssets(assets),p=persistentQueueProgress(snap.queue||{items:[]},snap.artifacts),usable=typeof Worker!=='undefined'&&eligibility.ok;host.innerHTML=`<div class="v16-stats"><span>TTF: ${esc(desc.ttf)}</span><span>ICC: ${esc(desc.icc)}</span></div><div class="v16-row"><button id="v16Start" ${usable?'':'disabled'}>${snap.queue?.kind==='worker-pdf-zip-v16'?'Resume / Reconcile':'Start Worker Batch'}</button><button id="v16Restart" ${usable?'':'disabled'}>Restart</button><button id="v16Pause" ${snap.queue&&!p.done?'':'disabled'}>Pause</button><button id="v16Cancel" ${snap.queue&&!p.done?'':'disabled'}>Cancel</button><button id="v16Zip" ${p.artifactCount?'':'disabled'}>Recovered ZIP</button></div><div class="v16-progress"><i style="width:${p.percent}%"></i></div><div class="v16-mono">${esc(progressText(p,snap.queue))}</div>${usable?'<p>TTF / ICC 二进制在 Worker 启动时只传输一次，随后每个订单继续复用同一 Worker Registry。</p>':`<div class="v16-warning">${typeof Worker==='undefined'?'Worker API unavailable.':eligibility.blockers.map(esc).join('<br>')}</div>`}`;host.querySelector('#v16Start').onclick=()=>runWorker(block,false);host.querySelector('#v16Restart').onclick=()=>runWorker(block,true);host.querySelector('#v16Pause').onclick=()=>{const s=readState();if(s.batch?.queue){s.batch.queue=pausePersistentQueue(s.batch.queue);writeState(s);renderWorker(block)}};host.querySelector('#v16Cancel').onclick=()=>{const s=readState();if(s.batch?.queue){s.batch.queue=cancelPersistentQueue(s.batch.queue);writeState(s);renderWorker(block)}};host.querySelector('#v16Zip').onclick=()=>exportZip(block)}
async function runWorker(block,restart=false){const my=++token;if(activeWorker){activeWorker.terminate();activeWorker=null}let state=readState();if(!state.batch?.rows?.length){alert('请先导入 Excel / CSV。');return}const assets=collectWorkerAssets(),availability=workerAssetAvailability(assets),eligibility=workerBatchEligibility(state,availability);if(!eligibility.ok){alert(eligibility.blockers.join('\n'));return}if(typeof Worker==='undefined'){alert('Worker API unavailable.');return}if(restart&&state.batch?.queue?.id)await artifactStore.clearQueue(state.batch.queue.id);let arts=state.batch?.queue?.id?await artifactStore.list(state.batch.queue.id):[],queue=preparePersistentQueue(state,arts,{restart,kind:'worker-pdf-zip-v16'});if(queue.status==='paused')queue=resumePersistentQueue(queue);writeState(persistentQueueState(state,queue));await renderWorker(block);const worker=new Worker(new URL('./batchPdf.worker.js',import.meta.url),{type:'module'});activeWorker=worker;try{const tx=transferableWorkerAssets(assets);await workerRequest(worker,{type:'init-assets',workerAssets:tx.payload},tx.transfer);while(my===token){state=readState();queue=state.batch.queue;arts=await artifactStore.list(queue.id);queue=preparePersistentQueue(state,arts,{kind:'worker-pdf-zip-v16'});if(queue.cancelRequested){queue=finalizePersistentCancel(queue);writeState(persistentQueueState(state,queue));break}if(queue.pauseRequested){queue=finalizePersistentPause(queue);writeState(persistentQueueState(state,queue));break}const claim=queueWithClaim(queue);queue=claim.queue;writeState(persistentQueueState(state,queue));if(!claim.item)break;const index=claim.item.index,row=state.batch.rows[index],baseState={...state,batch:{...(state.batch||{}),rows:[],queue:null}};try{const result=await workerRequest(worker,{baseState,row,index});await artifactStore.put({queueId:queue.id,index,fileName:result.fileName,mime:'application/pdf',bytes:result.bytes,fingerprint:result.fingerprint});queue=queueWithComplete(queue,index,result.fileName)}catch(error){queue=queueWithFailure(queue,index,error?.message||String(error))}state=readState();writeState(persistentQueueState(state,queue));await renderWorker(block);await yieldUi()}}finally{worker.terminate();if(activeWorker===worker)activeWorker=null;await renderWorker(block)}}
async function exportZip(block){const {queue,artifacts}=await workerSnapshot();if(!queue||!artifacts.length||!globalThis.JSZip)return;const zip=new globalThis.JSZip();for(const a of artifacts)zip.file(a.fileName,a.bytes);zip.file('boxstudio-v16-artifacts.json',JSON.stringify({queueId:queue.id,status:queue.status,files:artifacts.map(a=>({index:a.index,fileName:a.fileName,byteLength:a.byteLength,fingerprint:a.fingerprint}))},null,2));const bytes=await zip.generateAsync({type:'uint8array',compression:'DEFLATE',compressionOptions:{level:6}});downloadBytes(`boxstudio-${safe(queue.id)}-v16.zip`,bytes,'application/zip');await renderWorker(block)}

function brief(v){if(Array.isArray(v))return`Array(${v.length})`;if(v&&typeof v==='object')return`Object(${Object.keys(v).length})`;const s=String(v??'—');return s.length>44?s.slice(0,41)+'…':s}
function renderMerge(block){const host=block.querySelector('#v16Merge');if(!host)return;const s=readState(),session=mergeSession,sum=session?objectMergeSummary(session.analysis):null;host.innerHTML=`<div class="v16-row"><label>REST Endpoint<input id="v16Endpoint" value="${esc(s.remoteProjectEndpoint||'')}"></label><label>Project ID<input id="v16ProjectId" value="${esc(s.projectId||safe(s.projectName))}"></label><button id="v16Compare">Fetch & Granular Compare</button>${session?'<button id="v16Apply">Apply Locally</button><button id="v16Push">Push Merged Revision</button>':''}</div>${session?`<div class="v16-stats"><span>Remote r${session.remote.revision}</span><span>${sum.conflicts} conflict(s)</span><span>${sum.fieldLevel} granular domain(s)</span><span>${session.analysis.hasBase?'3-way base available':'no base: conservative'}</span></div><div class="v16-conflicts">${session.analysis.conflicts.slice(0,120).map(c=>`<div><span><b>${esc(c.path)}</b><small>local ${esc(brief(c.local))} · remote ${esc(brief(c.remote))}</small></span><select data-v16-resolve="${esc(c.path)}"><option value="">Choose…</option><option value="local" ${session.resolutions[c.path]==='local'?'selected':''}>Keep Local</option><option value="remote" ${session.resolutions[c.path]==='remote'?'selected':''}>Use Remote</option></select></div>`).join('')||'<div class="profile-empty">No conflicts. Non-conflicting object fields are auto-merged.</div>'}</div>`:'<p>Elements / Master Templates / Production Jobs 按 ID + 字段进行三方合并；Profile Maps 按 key + 字段合并。其余生产域继续保守原子合并。</p>'}`;host.querySelector('#v16Compare').onclick=()=>compareRemote(block);host.querySelectorAll('[data-v16-resolve]').forEach(sel=>sel.onchange=()=>{mergeSession.resolutions[sel.dataset.v16Resolve]=sel.value;renderMerge(block)});host.querySelector('#v16Apply')?.addEventListener('click',()=>applyMerge(block,false));host.querySelector('#v16Push')?.addEventListener('click',()=>applyMerge(block,true))}
async function compareRemote(block){try{const s=readState(),endpoint=block.querySelector('#v16Endpoint').value.trim(),id=block.querySelector('#v16ProjectId').value.trim();if(!endpoint||!id)throw new Error('REST Endpoint and Project ID are required.');const store=createRestProjectStore({baseUrl:endpoint}),remote=await store.load(id),base=loadBase(id),analysis=analyzeObjectLevelMerge({baseState:base?.state||null,localState:s,remoteState:remote.state});mergeSession={endpoint,id,remote,base,analysis,resolutions:{}};s.remoteProjectEndpoint=endpoint;s.projectId=id;writeState(s);renderMerge(block)}catch(error){alert(error?.message||error)}}
async function applyMerge(block,push){if(!mergeSession)return;try{const result=applyObjectLevelResolutions(mergeSession.analysis,mergeSession.resolutions);if(result.unresolved.length)throw new Error(`Resolve conflicts first: ${result.unresolved.slice(0,12).join(', ')}`);let next={...result.state,projectId:mergeSession.remote.id,projectRemoteRevision:Number(mergeSession.remote.revision)||0,remoteProjectEndpoint:mergeSession.endpoint,lastRemoteSyncAt:new Date().toISOString()};if(push){const store=createRestProjectStore({baseUrl:mergeSession.endpoint}),env=reviseProjectEnvelope(mergeSession.remote,next,{updatedBy:actor(next)}),saved=await store.save(env,{expectedRevision:mergeSession.remote.revision});next={...next,projectRemoteRevision:Number(saved.revision)||env.revision,lastRemoteSyncAt:new Date().toISOString()};saveBase(saved)}else saveBase(mergeSession.remote);writeState(next);mergeSession=null;renderMerge(block)}catch(error){alert(error?.message||error)}}

function renderAtlas(block){const host=block.querySelector('#v16Atlas');if(!host)return;try{const state=readState(),geo=generateGeometry(state.structure),atlas=buildArtworkAtlas(state,geo);host.innerHTML=`<div class="v16-stats"><span>${atlas.panelCount} panels</span><span>${atlas.elementCount} artwork elements</span><span>${atlas.commandCount} texture commands</span><span>${atlas.outside.length} out-of-panel commands</span></div><div class="v16-atlas">${atlas.plans.map((p,i)=>`<figure><div data-v16-canvas="${i}"></div><figcaption><b>${esc(p.label||p.panelId)}</b><span>${p.width.toFixed(1)}×${p.height.toFixed(1)} mm · ${p.elements} element(s)</span></figcaption></figure>`).join('')}</div><p>这是统一 Panel Artwork Texture Atlas：文字、运输标志、Barcode/QR、线框和导入 SVG 都进入同一纹理计划。V0.16 将它作为 3D 材质数据源基础；当前折叠 3D 仍未宣称具备印厂级 UV 校样精度。</p>`;atlas.plans.forEach((plan,i)=>{const mount=host.querySelector(`[data-v16-canvas="${i}"]`);try{const canvas=renderPanelArtworkCanvas(plan,{maxPixels:560});mount.appendChild(canvas)}catch{mount.textContent='Canvas unavailable'}})}catch(error){host.innerHTML=`<div class="v16-warning">${esc(error?.message||error)}</div>`}}

function install(){hideSuperseded();const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v16-tools';block.innerHTML=`<div class="v16-title"><div><h3>V0.16 Production Concurrency & Artwork</h3><p>Worker TTF/ICC transfer · object-level merge · panel artwork texture atlas.</p></div><span>V0.16</span></div><section><h4>Worker Batch + Binary Assets</h4><div id="v16Worker"></div></section><section><h4>Granular Remote Merge</h4><div id="v16Merge"></div></section><section><h4>Panel Artwork Texture Atlas</h4><div id="v16Atlas"></div></section>`;scroll.appendChild(block);renderWorker(block);renderMerge(block);renderAtlas(block)}
function updateVersion(){setUiVersion('V0.16')}
const observer=new MutationObserver(()=>{updateVersion();hideSuperseded();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
