import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry } from './geometry.js';
import { productionAppearanceStats } from './productionAppearance.js';
import { crossPanelArtworkDiagnostics, promoteSvgSymbolToCrossPanel } from './crossPanelArtwork.js';
import { exportProductionPdfV19, exportProductionSvgV19, prepareV19ProductionState } from './exportV19.js';

const BLOCK_ID='boxstudio-v19-tools';
function clone(v){return structuredClone(v)}
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,batch:{...defaultState.batch,...(p.batch||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(state){state.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function hideSuperseded(){document.getElementById('boxstudio-v17-tools')?.setAttribute('hidden','')}
function selectedSvg(state){const selected=(state.elements||[]).find(e=>e.id===state.selectedId&&e.type==='svg-symbol');return selected||(state.elements||[]).find(e=>e.type==='svg-symbol')||null}
function render(block){const host=block.querySelector('#v19Workspace');if(!host)return;try{const state=readState(),geo=generateGeometry(state.structure),appearance=productionAppearanceStats(state),cross=crossPanelArtworkDiagnostics(state,geo),prepared=prepareV19ProductionState(state),polyCount=prepared.state.elements.filter(e=>e.type==='production-polygon').length,src=selectedSvg(state),firstCross=(state.elements||[]).find(e=>e.type==='cross-panel-artwork');host.innerHTML=`<div class="v19-stats"><span>${appearance.marks} SVG appearance mark(s)</span><span>${appearance.primitives} fill primitive(s)</span><span>${appearance.gradients} gradient source(s)</span><span>${polyCount} production polygon(s)</span><span>${cross.crossPanel} cross-panel artwork object(s)</span><span class="${appearance.warnings?'warn':'ok'}">${appearance.warnings} appearance warning(s)</span></div>
<section class="v19-export"><h4>Production Appearance Export</h4><p>Solid fills are emitted as vector polygons. Gradients are deterministically tessellated into small vector polygons so SVG and PDF keep vector-only output. This is not native PDF shading or full Illustrator Appearance preservation.</p><div class="v19-actions"><button id="v19Pdf" class="primary">Export V0.19 Production PDF</button><button id="v19Svg">Export V0.19 Production SVG</button></div><div class="v19-note">V0.19 production path keeps CUT / CREASE / PERF / GLUE handling, existing text/barcode/QR output, imported SVG outlines, supported fills, and explicit cross-panel fragments. The V0.18 folded proof remains visible above for visual checking. PDF/X remains the existing Candidate gate rather than third-party certification.</div></section>
<section><h4>Cross-panel Artwork Object</h4><p>Promote one imported SVG mark from panel-local placement to document-global placement. V0.19 clips its vector fill and outline into every intersected panel at export time.</p>${src?`<button id="v19Promote">Promote ${esc(src.label||src.id)} to Cross-panel Artwork</button>`:'<div class="profile-empty">Import/select an SVG mark first.</div>'}${firstCross?`<div class="v19-cross-edit"><label>X mm<input id="v19X" type="number" step="1" value="${Number(firstCross.x)||0}"></label><label>Y mm<input id="v19Y" type="number" step="1" value="${Number(firstCross.y)||0}"></label><label>W mm<input id="v19W" type="number" step="1" min="1" value="${Number(firstCross.w)||1}"></label><label>H mm<input id="v19H" type="number" step="1" min="1" value="${Number(firstCross.h)||1}"></label><button id="v19SaveCross">Save Cross-panel Bounds</button></div>`:''}<div class="v19-list">${cross.items.map(x=>`<div class="v19-row"><span><b>${esc(x.label)}</b><small>${x.panels.length?x.panels.map(esc).join(' · '):'outside all panels'}</small></span><span><small>${x.polygonFragments} fill fragment(s)</small><small>${x.lineFragments} outline fragment(s)</small></span><em>${esc(x.status)}</em></div>`).join('')||'<div class="profile-empty">No cross-panel artwork objects.</div>'}</div></section>
<section><h4>Production Boundary</h4><p>V0.19 supports the V0.18 safe appearance subset in production output: solid fill, linear/radial gradient approximation, basic geometric clipPath and binary geometric mask. Complex curved filled paths, CSS cascade, pattern/filter/blend fidelity, true luminance masks, and ICC display conversion remain outside this serializer.</p></section>`;
host.querySelector('#v19Pdf').onclick=()=>{try{exportProductionPdfV19(readState())}catch(e){alert(e?.message||e)}};host.querySelector('#v19Svg').onclick=()=>{try{exportProductionSvgV19(document.querySelector('#designSvg'),readState())}catch(e){alert(e?.message||e)}};if(src)host.querySelector('#v19Promote').onclick=()=>{const s=readState(),g=generateGeometry(s.structure),source=selectedSvg(s),crossEl=promoteSvgSymbolToCrossPanel(source,g);s.elements=s.elements.map(e=>e.id===source.id?crossEl:e);s.selectedId=crossEl.id;writeState(s);location.reload()};if(firstCross)host.querySelector('#v19SaveCross').onclick=()=>{const s=readState(),el=s.elements.find(e=>e.id===firstCross.id);if(!el)return;el.x=Number(host.querySelector('#v19X').value)||0;el.y=Number(host.querySelector('#v19Y').value)||0;el.w=Math.max(1,Number(host.querySelector('#v19W').value)||1);el.h=Math.max(1,Number(host.querySelector('#v19H').value)||1);writeState(s);location.reload()};}catch(error){host.innerHTML=`<div class="v19-warning">${esc(error?.message||error)}</div>`}}
function install(){hideSuperseded();const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v19-tools';block.innerHTML=`<div class="v19-title"><div><h3>V0.19 Production Appearance</h3><p>Vector fill export · gradient tessellation · cross-panel artwork clipping.</p></div><span>V0.19</span></div><div id="v19Workspace"></div>`;scroll.appendChild(block);render(block)}
function updateVersion(){const v=document.querySelector('.brand small');if(v)v.textContent='V0.19';document.title='BoxStudio V0.19'}
const observer=new MutationObserver(()=>{updateVersion();hideSuperseded();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
