import { STORAGE_KEY, defaultState } from './model.js';
import { orderedElements } from './objectOrder.js';

const NS='http://www.w3.org/2000/svg';
function clone(v){return structuredClone(v)}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n:d}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function rotate(x,y,cx,cy,deg=0){const a=num(deg)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),dx=x-cx,dy=y-cy;return[cx+dx*c-dy*s,cy+dx*s+dy*c]}
export function crossPanelOverlayItems(state){return orderedElements(state?.elements||[]).filter(e=>e?.type==='cross-panel-artwork').map(e=>({id:e.id,label:e.label||e.id,x:num(e.x),y:num(e.y),w:Math.max(1,num(e.w,1)),h:Math.max(1,num(e.h,1)),r:num(e.r),lockAspect:e.lockAspect!==false,zIndex:num(e.zIndex),lineCount:e.svgMark?.lines?.length||0}))}
function svgPoint(svg,event){const pt=svg.createSVGPoint();pt.x=event.clientX;pt.y=event.clientY;const m=svg.getScreenCTM();return m?pt.matrixTransform(m.inverse()):{x:0,y:0}}
function make(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,String(v));return n}
function outlineGroup(el){const g=make('g',{'pointer-events':'none'}),mark=el.svgMark;if(!mark?.lines?.length)return g;const sx=num(el.w)/Math.max(.001,num(mark.width,1)),sy=num(el.h)/Math.max(.001,num(mark.height,1)),cx=num(el.x)+num(el.w)/2,cy=num(el.y)+num(el.h)/2;for(const l of mark.lines){let a=[num(el.x)+num(l.x1)*sx,num(el.y)+num(l.y1)*sy],b=[num(el.x)+num(l.x2)*sx,num(el.y)+num(l.y2)*sy];a=rotate(a[0],a[1],cx,cy,el.r);b=rotate(b[0],b[1],cx,cy,el.r);g.appendChild(make('line',{x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:'#6d5dfc','stroke-width':Math.max(.7,Math.min(2,num(el.w)/180)),opacity:.62}))}return g}
function drawItem(root,el,selected){const g=make('g',{'data-v20-cross-id':el.id,class:'v20-cross-canvas'});g.appendChild(outlineGroup(el));const rect=make('rect',{x:el.x,y:el.y,width:el.w,height:el.h,fill:selected?'rgba(109,93,252,.08)':'rgba(109,93,252,.03)',stroke:selected?'#6d5dfc':'#877cf2','stroke-width':selected?2:1.2,'stroke-dasharray':'10 6','vector-effect':'non-scaling-stroke','data-v20-drag':'move'});g.appendChild(rect);const label=make('text',{x:el.x+4,y:el.y+14,fill:'#5b4bd7','font-size':10,'font-weight':700,'pointer-events':'none'});label.textContent=`CROSS · ${el.label||el.id}`;g.appendChild(label);const size=Math.max(5,Math.min(12,Math.min(el.w,el.h)*.08)),handle=make('rect',{x:el.x+el.w-size/2,y:el.y+el.h-size/2,width:size,height:size,rx:1,fill:'#6d5dfc',stroke:'#fff','stroke-width':1,'vector-effect':'non-scaling-stroke','data-v20-drag':'resize'});g.appendChild(handle);root.appendChild(g)}
function renderOverlay(svg,state){svg.querySelector('#boxstudio-v20-cross-overlay')?.remove();const items=crossPanelOverlayItems(state);if(!items.length)return;const root=make('g',{id:'boxstudio-v20-cross-overlay',class:'ui-only'});for(const el of orderedElements(state.elements||[]).filter(e=>e?.type==='cross-panel-artwork'))drawItem(root,el,state.selectedId===el.id);svg.appendChild(root)}
function installDrag(svg){let drag=null;svg.addEventListener('pointerdown',e=>{const target=e.target.closest?.('[data-v20-drag]');if(!target)return;const group=target.closest('[data-v20-cross-id]');if(!group)return;e.stopPropagation();e.preventDefault();const state=readState(),el=state.elements.find(x=>x.id===group.dataset.v20CrossId);if(!el)return;state.selectedId=el.id;const p=svgPoint(svg,e);drag={state,id:el.id,mode:target.dataset.v20Drag,start:p,orig:{x:num(el.x),y:num(el.y),w:num(el.w),h:num(el.h)},aspect:Math.max(.001,num(el.w))/Math.max(.001,num(el.h))};svg.setPointerCapture?.(e.pointerId);renderOverlay(svg,state)});
  svg.addEventListener('pointermove',e=>{if(!drag)return;e.stopPropagation();const p=svgPoint(svg,e),el=drag.state.elements.find(x=>x.id===drag.id);if(!el)return;const dx=p.x-drag.start.x,dy=p.y-drag.start.y;if(drag.mode==='move'){el.x=drag.orig.x+dx;el.y=drag.orig.y+dy}else{let w=Math.max(4,drag.orig.w+dx),h=Math.max(4,drag.orig.h+dy);if(el.lockAspect!==false){if(Math.abs(dx)>=Math.abs(dy))h=w/drag.aspect;else w=h*drag.aspect}el.w=w;el.h=h}renderOverlay(svg,drag.state)});
  const finish=e=>{if(!drag)return;e?.stopPropagation?.();writeState(drag.state);drag=null;location.reload()};svg.addEventListener('pointerup',finish);svg.addEventListener('pointercancel',finish)}
function install(){const svg=document.querySelector('#designSvg');if(!svg||svg.dataset.v20OverlayInstalled==='1')return;svg.dataset.v20OverlayInstalled='1';renderOverlay(svg,readState());installDrag(svg)}
const observer=new MutationObserver(()=>install());observer.observe(document.documentElement,{childList:true,subtree:true});install();
