import {setUiVersion} from './uiVersion.js';
import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry } from './geometry.js';
import { buildArtworkAtlas } from './panelArtwork.js';
import { buildNativeSvgV20Layer, exportProductionSvgV20 } from './nativeSvgV20.js';
import { exportProductionPdfV19 } from './exportV19.js';
import { moveElementZ, zOrderDiagnostics } from './objectOrder.js';

const BLOCK_ID='boxstudio-v20-tools';
function clone(v){return structuredClone(v)}
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,batch:{...defaultState.batch,...(p.batch||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(state){state.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function hideSuperseded(){document.getElementById('boxstudio-v19-tools')?.setAttribute('hidden','')}
function selectedLayer(state){return(state.elements||[]).find(e=>e.id===state.selectedId)||null}
function render(block){const host=block.querySelector('#v20Workspace');if(!host)return;try{const state=readState(),geo=generateGeometry(state.structure),atlas=buildArtworkAtlas(state,geo),native=buildNativeSvgV20Layer(state,geo),order=zOrderDiagnostics(state),selected=selectedLayer(state),cross=(state.elements||[]).filter(e=>e.type==='cross-panel-artwork').length;host.innerHTML=`<div class="v20-stats"><span>${native.stats.objects} native SVG appearance object(s)</span><span>${native.stats.gradients} native gradient(s)</span><span>${native.stats.primitives} fill primitive(s)</span><span>${cross} cross-panel object(s)</span><span>${atlas.crossPanelFragments||0} 3D atlas cross fragment(s)</span><span>${order.count} ordered object(s)</span></div>
<section><h4>Native SVG Production Appearance</h4><p>V0.20 emits supported linear/radial gradients as native SVG gradient definitions instead of V0.19 triangle tessellation. Cross-panel artwork is clipped by a document-level union of carton panels so one gradient remains continuous across panel boundaries.</p><div class="v20-actions"><button id="v20Svg" class="primary">Export V0.20 Native Gradient SVG</button><button id="v20Pdf">Export PDF · V0.19 Tessellation Fallback</button></div><div class="v20-note">Native PDF shading and ICC RGB→CMYK conversion are not claimed in this release. PDF still uses the tested V0.19 vector-tessellation path.</div></section>
<section><h4>Cross-panel Canvas + Folded 3D</h4><p>Cross-panel artwork now enters the same Panel Artwork Atlas used by the folded texture proof. In the main Design canvas, purple dashed overlays can be dragged directly; the lower-right handle resizes the object with aspect lock.</p><div class="v20-stats"><span>${atlas.panelCount} panel plan(s)</span><span>${atlas.commandCount} artwork command(s)</span><span>${atlas.crossPanelFragments||0} clipped cross-panel fragment(s)</span><span class="${atlas.outside.length?'warn':'ok'}">${atlas.outside.length} out-of-panel command(s)</span></div></section>
<section><h4>Object Z-order</h4>${selected?`<p>Selected: <b>${esc(selected.label||selected.id)}</b> · ${esc(selected.type||'object')} · z ${Number.isFinite(Number(selected.zIndex))?Number(selected.zIndex):'auto'}</p><div class="v20-actions"><button data-z="back">Send to Back</button><button data-z="backward">Backward</button><button data-z="forward">Forward</button><button data-z="front">Bring to Front</button></div>`:'<div class="profile-empty">Select an object in the editor first.</div>'}<div class="v20-list">${order.items.slice(-12).reverse().map(x=>`<div class="v20-row"><span><b>${esc(x.id)}</b><small>${esc(x.type)}</small></span><em>z ${x.zIndex}</em></div>`).join('')}</div></section>
<section><h4>V0.20 Production Boundary</h4><p>Native SVG gradients, direct cross-panel 2D placement, panel clipping, folded-atlas integration and object ordering are implemented. Native PDF shading, true ICC device-link conversion, alpha/luminance mask fidelity and board-stretch simulation remain separate work.</p></section>`;
  host.querySelector('#v20Svg').onclick=()=>{try{exportProductionSvgV20(document.querySelector('#designSvg'),readState())}catch(e){alert(e?.message||e)}};host.querySelector('#v20Pdf').onclick=()=>{try{exportProductionPdfV19(readState())}catch(e){alert(e?.message||e)}};host.querySelectorAll('[data-z]').forEach(btn=>btn.onclick=()=>{const s=readState();if(!s.selectedId)return;const next=moveElementZ(s,s.selectedId,btn.dataset.z);writeState(next);location.reload()});}catch(error){host.innerHTML=`<div class="v20-warning">${esc(error?.message||error)}</div>`}}
function install(){hideSuperseded();const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v20-tools';block.innerHTML=`<div class="v20-title"><div><h3>V0.20 Native SVG & Cross-panel Editing</h3><p>Native SVG gradients · direct canvas editing · folded atlas integration · z-order.</p></div><span>V0.20</span></div><div id="v20Workspace"></div>`;scroll.appendChild(block);render(block)}
function updateVersion(){setUiVersion('V0.20')}
const observer=new MutationObserver(()=>{updateVersion();hideSuperseded();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
