import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry } from './geometry.js';
import { orderedElements } from './objectOrder.js';
import { getCrossSelection, setCrossSelection, toggleCrossSelection, translateCrossSelection, resizeCrossElement, rotateCrossElement, selectionBounds } from './crossPanelTransformV21.js';

const NS='http://www.w3.org/2000/svg';
const clone=v=>structuredClone(v);
const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,crossPanelEdit:{...defaultState.crossPanelEdit,...(p.crossPanelEdit||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function make(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n}
function svgPoint(svg,e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const m=svg.getScreenCTM();return m?p.matrixTransform(m.inverse()):{x:0,y:0}}
function rotatePoint(x,y,cx,cy,deg=0){const a=num(deg)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),dx=x-cx,dy=y-cy;return[cx+dx*c-dy*s,cy+dx*s+dy*c]}
function outlineGroup(el){const g=make('g',{'pointer-events':'none'}),mark=el.svgMark;if(!mark?.lines?.length)return g;const sx=num(el.w)/Math.max(.001,num(mark.width,1)),sy=num(el.h)/Math.max(.001,num(mark.height,1)),cx=num(el.x)+num(el.w)/2,cy=num(el.y)+num(el.h)/2;for(const l of mark.lines){let a=[num(el.x)+num(l.x1)*sx,num(el.y)+num(l.y1)*sy],b=[num(el.x)+num(l.x2)*sx,num(el.y)+num(l.y2)*sy];a=rotatePoint(a[0],a[1],cx,cy,el.r);b=rotatePoint(b[0],b[1],cx,cy,el.r);g.appendChild(make('line',{x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:'#5b4bd7','stroke-width':1,opacity:.62,'vector-effect':'non-scaling-stroke'}))}return g}
function drawItem(root,el,selected){const g=make('g',{'data-v21-id':el.id,class:'v21-cross-item'});g.appendChild(outlineGroup(el));const rect=make('rect',{x:el.x,y:el.y,width:el.w,height:el.h,fill:selected?'rgba(91,75,215,.09)':'rgba(91,75,215,.025)',stroke:selected?'#5b4bd7':'#8f84e8','stroke-width':selected?2:1.15,'stroke-dasharray':'9 6','vector-effect':'non-scaling-stroke','data-v21-drag':'move'});g.appendChild(rect);const label=make('text',{x:el.x+4,y:el.y+13,fill:'#5142c6','font-size':9.5,'font-weight':700,'pointer-events':'none'});label.textContent=`CROSS · ${el.label||el.id}`;g.appendChild(label);if(selected){const hs=Math.max(5,Math.min(11,Math.min(el.w,el.h)*.07));g.appendChild(make('rect',{x:el.x+el.w-hs/2,y:el.y+el.h-hs/2,width:hs,height:hs,rx:1,fill:'#5b4bd7',stroke:'#fff','stroke-width':1,'data-v21-drag':'resize'}));const cx=el.x+el.w/2,hy=el.y-18;g.appendChild(make('line',{x1:cx,y1:el.y,x2:cx,y2:hy+5,stroke:'#5b4bd7','stroke-width':1.2,'vector-effect':'non-scaling-stroke','pointer-events':'none'}));g.appendChild(make('circle',{cx,cy:hy,r:5.5,fill:'#fff',stroke:'#5b4bd7','stroke-width':1.5,'data-v21-drag':'rotate'}))}root.appendChild(g)}
function drawSelectionBox(root,state){const ids=getCrossSelection(state);if(ids.length<2)return;const b=selectionBounds(state,ids);root.appendChild(make('rect',{x:b.x,y:b.y,width:b.w,height:b.h,fill:'none',stroke:'#18a06e','stroke-width':1.4,'stroke-dasharray':'5 4','vector-effect':'non-scaling-stroke','pointer-events':'none'}));const t=make('text',{x:b.x+4,y:b.y-5,fill:'#14835b','font-size':9,'font-weight':700,'pointer-events':'none'});t.textContent=`${ids.length} selected`;root.appendChild(t)}
function drawGuides(root,guides,geo){for(const g of guides||[]){if(g.axis==='x')root.appendChild(make('line',{x1:g.value,y1:0,x2:g.value,y2:geo.height,stroke:'#18a06e','stroke-width':1,'stroke-dasharray':'4 4','vector-effect':'non-scaling-stroke','pointer-events':'none'}));else root.appendChild(make('line',{x1:0,y1:g.value,x2:geo.width,y2:g.value,stroke:'#18a06e','stroke-width':1,'stroke-dasharray':'4 4','vector-effect':'non-scaling-stroke','pointer-events':'none'}))}}
function renderOverlay(svg,state,{guides=[]}={}){svg.querySelector('#boxstudio-v20-cross-overlay')?.remove();svg.querySelector('#boxstudio-v21-cross-overlay')?.remove();const root=make('g',{id:'boxstudio-v21-cross-overlay',class:'ui-only'}),sel=new Set(getCrossSelection(state)),geo=generateGeometry(state.structure);for(const el of orderedElements(state.elements||[]).filter(e=>e?.type==='cross-panel-artwork'))drawItem(root,el,sel.has(el.id));drawSelectionBox(root,state);drawGuides(root,guides,geo);svg.appendChild(root)}
function installDrag(svg){let drag=null;svg.addEventListener('pointerdown',e=>{const target=e.target.closest?.('[data-v21-drag]'),group=target?.closest?.('[data-v21-id]');if(!target||!group)return;e.stopPropagation();e.preventDefault();let state=readState(),id=group.dataset.v21Id;state=toggleCrossSelection(state,id,{additive:e.shiftKey});const ids=getCrossSelection(state);if(!ids.includes(id)){writeState(state);renderOverlay(svg,state);return}const p=svgPoint(svg,e),el=state.elements.find(x=>x.id===id),mode=target.dataset.v21Drag,cx=num(el.x)+num(el.w)/2,cy=num(el.y)+num(el.h)/2;drag={mode,id,ids,base:clone(state),start:p,orig:{x:num(el.x),y:num(el.y),w:num(el.w),h:num(el.h),r:num(el.r)},center:{x:cx,y:cy},startAngle:Math.atan2(p.y-cy,p.x-cx)*180/Math.PI};svg.setPointerCapture?.(e.pointerId);writeState(state);renderOverlay(svg,state)});
  svg.addEventListener('pointermove',e=>{if(!drag)return;e.stopPropagation();const p=svgPoint(svg,e),geo=generateGeometry(drag.base.structure),edit={snap:drag.base.crossPanelEdit?.snap!==false&&!e.altKey,gridMm:num(drag.base.crossPanelEdit?.gridMm,5),toleranceMm:num(drag.base.crossPanelEdit?.toleranceMm,3)};let draft=clone(drag.base),guides=[];if(drag.mode==='move'){const r=translateCrossSelection(drag.base,drag.ids,p.x-drag.start.x,p.y-drag.start.y,geo,edit);draft=r.state;guides=r.guides}else if(drag.mode==='resize'){draft=resizeCrossElement(drag.base,drag.id,drag.orig.w+(p.x-drag.start.x),drag.orig.h+(p.y-drag.start.y),{lockAspect:!e.shiftKey})}else{const angle=Math.atan2(p.y-drag.center.y,p.x-drag.center.x)*180/Math.PI,raw=drag.orig.r+(angle-drag.startAngle);draft=rotateCrossElement(drag.base,drag.id,raw,{snap:!e.altKey,step:num(drag.base.crossPanelEdit?.angleStep,15)})}draft=setCrossSelection(draft,drag.ids);drag.draft=draft;renderOverlay(svg,draft,{guides})});
  const finish=e=>{if(!drag)return;e?.stopPropagation?.();writeState(drag.draft||drag.base);drag=null;location.reload()};svg.addEventListener('pointerup',finish);svg.addEventListener('pointercancel',finish)}
function install(){const svg=document.querySelector('#designSvg');if(!svg||svg.dataset.v21OverlayInstalled==='1')return;svg.dataset.v21OverlayInstalled='1';renderOverlay(svg,readState());installDrag(svg)}
const observer=new MutationObserver(()=>install());observer.observe(document.documentElement,{childList:true,subtree:true});install();
