import {setUiVersion} from './uiVersion.js';
import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry } from './geometry.js';
import { buildNativePdfV21Plan, exportNativeGradientPdfV21 } from './nativePdfV21.js';
import { exportProductionSvgV20 } from './nativeSvgV20.js';
import { exportProductionPdfV19 } from './exportV19.js';
import { getCrossSelection } from './crossPanelTransformV21.js';

const BLOCK_ID='boxstudio-v21-tools';
const clone=v=>structuredClone(v);
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,crossPanelEdit:{...defaultState.crossPanelEdit,...(p.crossPanelEdit||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function hideSuperseded(){document.getElementById('boxstudio-v20-tools')?.setAttribute('hidden','')}
function render(block){const host=block.querySelector('#v21Workspace');if(!host)return;try{const state=readState(),geo=generateGeometry(state.structure),plan=buildNativePdfV21Plan(state,geo),sel=getCrossSelection(state),edit={snap:true,gridMm:5,toleranceMm:3,angleStep:15,...(state.crossPanelEdit||{})};host.innerHTML=`<div class="v21-stats"><span>${plan.stats.objects} appearance object(s)</span><span>${plan.stats.axial} axial shading(s)</span><span>${plan.stats.radial} radial shading(s)</span><span>${plan.stats.solids} solid fill(s)</span><span>${plan.stats.alpha} alpha object(s)</span><span class="${plan.stats.warnings?'warn':'ok'}">${plan.stats.warnings} PDF shading warning(s)</span></div>
<section><h4>Native PDF Gradient Proof</h4><p>V0.21 adds a real PDF ShadingType 2/3 proof path for supported imported SVG gradients. Multi-stop gradients use stitching functions; uniform artwork alpha uses PDF ExtGState.</p><div class="v21-actions"><button id="v21Pdf" class="primary">Export V0.21 Native Gradient Proof PDF</button><button id="v21Svg">Export Native Gradient SVG</button><button id="v21ProductionPdf">Production PDF · V0.19 Serializer</button></div><div class="v21-note">The new native-gradient PDF is a proof/export validation document, not a replacement for the production PDF serializer yet. Production PDF continues to use the tested V0.19 vector-tessellation route.</div>${plan.warnings.length?`<div class="v21-warnings">${plan.warnings.map(x=>`<div>${esc(x)}</div>`).join('')}</div>`:''}</section>
<section><h4>Cross-panel Multi-select & Snapping</h4><p>Shift-click adds/removes Cross-panel objects from the selection. Dragging moves the selected group; the lower-right handle resizes a single object; the top handle rotates. Hold Alt while moving/rotating to bypass snapping.</p><div class="v21-grid"><label><input id="v21Snap" type="checkbox" ${edit.snap!==false?'checked':''}> Enable snap</label><label>Grid mm<input id="v21Grid" type="number" min="0.1" step="0.5" value="${Number(edit.gridMm)||5}"></label><label>Tolerance mm<input id="v21Tol" type="number" min="0" step="0.5" value="${Number(edit.toleranceMm)||3}"></label><label>Angle step<input id="v21Angle" type="number" min="1" step="1" value="${Number(edit.angleStep)||15}"></label><button id="v21SaveEdit">Save Editing Settings</button></div><div class="v21-selection">${sel.length?`Selected: <b>${sel.map(esc).join(' · ')}</b>`:'No Cross-panel selection.'}</div></section>
<section><h4>Color & Transparency Boundary</h4><p>V0.21 native PDF proof supports DeviceRGB axial/radial shading and uniform alpha through ExtGState. Varying gradient-stop opacity still requires a soft-mask implementation, and imported RGB colors are not converted through the loaded CMYK ICC profile. No ICC conversion claim is made.</p></section>`;
host.querySelector('#v21Pdf').onclick=()=>{try{exportNativeGradientPdfV21(readState())}catch(e){alert(e?.message||e)}};host.querySelector('#v21Svg').onclick=()=>{try{exportProductionSvgV20(document.querySelector('#designSvg'),readState())}catch(e){alert(e?.message||e)}};host.querySelector('#v21ProductionPdf').onclick=()=>{try{exportProductionPdfV19(readState())}catch(e){alert(e?.message||e)}};host.querySelector('#v21SaveEdit').onclick=()=>{const s=readState();s.crossPanelEdit={...(s.crossPanelEdit||{}),snap:host.querySelector('#v21Snap').checked,gridMm:Math.max(.1,Number(host.querySelector('#v21Grid').value)||5),toleranceMm:Math.max(0,Number(host.querySelector('#v21Tol').value)||3),angleStep:Math.max(1,Number(host.querySelector('#v21Angle').value)||15)};writeState(s);location.reload()};}catch(error){host.innerHTML=`<div class="v21-warning">${esc(error?.message||error)}</div>`}}
function install(){hideSuperseded();const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v21-tools';block.innerHTML=`<div class="v21-title"><div><h3>V0.21 Native PDF & Cross-panel Transform</h3><p>PDF axial/radial shading proof · alpha ExtGState · multi-select · snapping · rotation.</p></div><span>V0.21</span></div><div id="v21Workspace"></div>`;scroll.appendChild(block);render(block)}
function updateVersion(){setUiVersion('V0.21')}
const observer=new MutationObserver(()=>{updateVersion();hideSuperseded();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
