import { STORAGE_KEY, defaultState } from './model.js';
import { buildNativePdfV22Plan, exportNativeGradientPdfV22 } from './nativePdfV22.js';
import { exportProductionSvgV20 } from './nativeSvgV20.js';
import { exportProductionPdfV19 } from './exportV19.js';
import { getCrossSelection, setCrossSelection } from './crossPanelTransformV21.js';
import { alignCrossSelection, distributeCrossSelection, setCrossClipRect, setCrossClipPolygon, clearCrossClip, parseNormalizedClipPolygon, crossClipText, crossTransformDiagnostics } from './crossPanelTransformV22.js';

const BLOCK_ID='boxstudio-v22-tools',clone=v=>structuredClone(v);
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[ch]))}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,crossPanelEdit:{...defaultState.crossPanelEdit,...(p.crossPanelEdit||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function selectedCross(state){const ids=getCrossSelection(state);return(state.elements||[]).find(e=>e.id===ids.at(-1)&&e.type==='cross-panel-artwork')||null}
function hideSuperseded(){document.getElementById('boxstudio-v21-tools')?.setAttribute('hidden','');document.getElementById('boxstudio-v20-tools')?.setAttribute('hidden','')}
function commit(next){writeState(next);location.reload()}
function render(block){const host=block.querySelector('#v22Workspace');if(!host)return;try{const state=readState(),plan=buildNativePdfV22Plan(state),diag=crossTransformDiagnostics(state),selected=selectedCross(state),clipText=selected?crossClipText(selected):'';host.innerHTML=`<div class="v22-stats"><span>${plan.stats.axial} axial</span><span>${plan.stats.radial} radial</span><span>${plan.stats.softMasks||0} soft mask(s)</span><span>${plan.stats.alpha} alpha object(s)</span><span>${diag.count} selected</span><span>${plan.stats.editableClips||0} editable clip(s)</span></div>
<section><h4>Native PDF Gradient + Soft Mask Proof</h4><p>V0.22 extends the native PDF proof path with luminosity soft masks for gradients whose stops use different opacity values. Color shading remains native PDF axial/radial shading.</p><div class="v22-actions"><button id="v22Pdf" class="primary">Export V0.22 Soft-mask Proof PDF</button><button id="v22Svg">Export Native Gradient SVG</button><button id="v22ProductionPdf">Production PDF · V0.19 Stable</button></div><div class="v22-note">The V0.22 PDF is still an appearance-proof serializer. The established V0.19 production PDF remains the production route until native shading is merged with every production object and PDF/X Candidate resource.</div>${plan.warnings.length?`<div class="v22-warnings">${plan.warnings.map(x=>`<div>${esc(x)}</div>`).join('')}</div>`:''}</section>
<section><h4>Shared Transform · Align · Distribute</h4><p>Multi-selection now has shared resize/rotate handles in the Design canvas. Alignment and distribution operate on the currently selected Cross-panel objects.</p><div class="v22-actions wrap"><button data-align="left">Align Left</button><button data-align="center">Center X</button><button data-align="right">Align Right</button><button data-align="top">Align Top</button><button data-align="middle">Center Y</button><button data-align="bottom">Align Bottom</button><button data-distribute="x">Distribute X</button><button data-distribute="y">Distribute Y</button></div><div class="v22-note">Selection: ${diag.selection.length?diag.selection.map(esc).join(' · '):'none'}${diag.count>1?` · bounds ${diag.bounds.w.toFixed(1)} × ${diag.bounds.h.toFixed(1)} mm`:''}</div></section>
<section><h4>Per-object Clip Polygon</h4>${selected?`<p>Selected Cross-panel object: <b>${esc(selected.label||selected.id)}</b>. Clip coordinates are normalized to the object bounds from 0 to 1 and rotate with the artwork.</p><textarea id="v22Clip" rows="3" placeholder="0,0 1,0 1,1 0,1">${esc(clipText)}</textarea><div class="v22-actions"><button id="v22ApplyClip" class="primary">Apply Polygon Clip</button><button id="v22InsetClip">10% Inset Clip</button><button id="v22ClearClip">Clear Clip</button></div>`:'<div class="profile-empty">Select a Cross-panel object to edit its clip polygon.</div>'}<div class="v22-note">The clip is now used by cross-panel production materialization and folded 3D panel fragments. This is geometric clipping, not RIP trapping or a luminance-mask editor.</div></section>
<section><h4>V0.22 Boundary</h4><p>Varying gradient-stop alpha now has a PDF soft-mask proof path. True ICC RGB→CMYK conversion, full luminance SVG masks, PDF/X-certified native-gradient production output, and board deformation remain separate work.</p></section>`;
  host.querySelector('#v22Pdf').onclick=()=>{try{exportNativeGradientPdfV22(readState())}catch(e){alert(e?.message||e)}};host.querySelector('#v22Svg').onclick=()=>{try{exportProductionSvgV20(document.querySelector('#designSvg'),readState())}catch(e){alert(e?.message||e)}};host.querySelector('#v22ProductionPdf').onclick=()=>{try{exportProductionPdfV19(readState())}catch(e){alert(e?.message||e)}};
  host.querySelectorAll('[data-align]').forEach(btn=>btn.onclick=()=>{const s=readState(),ids=getCrossSelection(s);if(ids.length<2)return alert('Select at least two Cross-panel objects.');commit(alignCrossSelection(s,ids,btn.dataset.align))});host.querySelectorAll('[data-distribute]').forEach(btn=>btn.onclick=()=>{const s=readState(),ids=getCrossSelection(s);if(ids.length<3)return alert('Select at least three Cross-panel objects.');commit(distributeCrossSelection(s,ids,btn.dataset.distribute))});
  if(selected){host.querySelector('#v22ApplyClip').onclick=()=>{try{const s=readState(),id=getCrossSelection(s).at(-1),pts=parseNormalizedClipPolygon(host.querySelector('#v22Clip').value);commit(setCrossSelection(setCrossClipPolygon(s,id,pts),getCrossSelection(s)))}catch(e){alert(e?.message||e)}};host.querySelector('#v22InsetClip').onclick=()=>{const s=readState(),ids=getCrossSelection(s),id=ids.at(-1);commit(setCrossSelection(setCrossClipRect(s,id,{x:.1,y:.1,w:.8,h:.8}),ids))};host.querySelector('#v22ClearClip').onclick=()=>{const s=readState(),ids=getCrossSelection(s),id=ids.at(-1);commit(setCrossSelection(clearCrossClip(s,id),ids))}}
}catch(error){host.innerHTML=`<div class="v22-warning">${esc(error?.message||error)}</div>`}}
function install(){hideSuperseded();const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v22-tools';block.innerHTML=`<div class="v22-title"><div><h3>V0.22 Soft Mask & Shared Transform</h3><p>Gradient soft-mask proof · group transform · align/distribute · editable clip polygon.</p></div><span>V0.22</span></div><div id="v22Workspace"></div>`;scroll.appendChild(block);render(block)}
function updateVersion(){const v=document.querySelector('.brand small');if(v)v.textContent='V0.22';document.title='BoxStudio V0.22'}
const observer=new MutationObserver(()=>{updateVersion();hideSuperseded();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
