import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry } from './geometry.js';
import { orderedElements } from './objectOrder.js';
import { getCrossSelection, setCrossSelection, toggleCrossSelection, translateCrossSelection, resizeCrossElement, rotateCrossElement, selectionBounds } from './crossPanelTransformV21.js';
import { scaleCrossSelection, rotateCrossSelection } from './crossPanelTransformV22.js';
import { crossPanelClipPolygon } from './crossPanelArtwork.js';
import { normalizedClipPointToDocument, moveCrossClipPoint } from './clipEditorV23.js';
import { smartSpacingDelta } from './smartSpacingV23.js';

const NS='http://www.w3.org/2000/svg',clone=v=>structuredClone(v),num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,crossPanelEdit:{...defaultState.crossPanelEdit,...(p.crossPanelEdit||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function make(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n}
function svgPoint(svg,e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const m=svg.getScreenCTM();return m?p.matrixTransform(m.inverse()):{x:0,y:0}}
function rotatePoint(x,y,cx,cy,deg=0){const a=num(deg)*Math.PI/180,c=Math.cos(a),s=Math.sin(a),dx=x-cx,dy=y-cy;return[cx+dx*c-dy*s,cy+dx*s+dy*c]}
function outlineGroup(el){const g=make('g',{'pointer-events':'none'}),mark=el.svgMark;if(!mark?.lines?.length)return g;const sx=num(el.w)/Math.max(.001,num(mark.width,1)),sy=num(el.h)/Math.max(.001,num(mark.height,1)),cx=num(el.x)+num(el.w)/2,cy=num(el.y)+num(el.h)/2;for(const l of mark.lines){let a=[num(el.x)+num(l.x1)*sx,num(el.y)+num(l.y1)*sy],b=[num(el.x)+num(l.x2)*sx,num(el.y)+num(l.y2)*sy];a=rotatePoint(a[0],a[1],cx,cy,el.r);b=rotatePoint(b[0],b[1],cx,cy,el.r);g.appendChild(make('line',{x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:'#5b4bd7','stroke-width':1,opacity:.62,'vector-effect':'non-scaling-stroke'}))}return g}
function drawClip(g,el,{editable=false}={}){const p=crossPanelClipPolygon(el);if(!p?.length)return;g.appendChild(make('polygon',{points:p.map(q=>`${q[0]},${q[1]}`).join(' '),fill:'rgba(0,145,190,.06)',stroke:'#0091be','stroke-width':1.35,'stroke-dasharray':'4 3','vector-effect':'non-scaling-stroke','pointer-events':'none'}));if(editable){(el.crossClip?.points||[]).forEach((q,i)=>{const d=normalizedClipPointToDocument(el,q);g.appendChild(make('circle',{cx:d[0],cy:d[1],r:5,fill:'#fff',stroke:'#0091be','stroke-width':2,'vector-effect':'non-scaling-stroke','data-v23-clip-point':i,'data-v23-clip-id':el.id}));});}}
function drawItem(root,el,selected,single){const g=make('g',{'data-v23-id':el.id,class:'v23-cross-item'});g.appendChild(outlineGroup(el));drawClip(g,el,{editable:selected&&single});const rect=make('rect',{x:el.x,y:el.y,width:el.w,height:el.h,fill:selected?'rgba(91,75,215,.09)':'rgba(91,75,215,.025)',stroke:selected?'#5b4bd7':'#8f84e8','stroke-width':selected?2:1.15,'stroke-dasharray':'9 6','vector-effect':'non-scaling-stroke','data-v23-drag':'move'});g.appendChild(rect);const label=make('text',{x:el.x+4,y:el.y+13,fill:'#5142c6','font-size':9.5,'font-weight':700,'pointer-events':'none'});label.textContent=`CROSS · ${el.label||el.id}`;g.appendChild(label);if(selected&&single){const hs=Math.max(5,Math.min(11,Math.min(el.w,el.h)*.07));g.appendChild(make('rect',{x:el.x+el.w-hs/2,y:el.y+el.h-hs/2,width:hs,height:hs,rx:1,fill:'#5b4bd7',stroke:'#fff','stroke-width':1,'data-v23-drag':'resize'}));const cx=el.x+el.w/2,hy=el.y-18;g.appendChild(make('line',{x1:cx,y1:el.y,x2:cx,y2:hy+5,stroke:'#5b4bd7','stroke-width':1.2,'vector-effect':'non-scaling-stroke','pointer-events':'none'}));g.appendChild(make('circle',{cx,cy:hy,r:5.5,fill:'#fff',stroke:'#5b4bd7','stroke-width':1.5,'data-v23-drag':'rotate'}))}root.appendChild(g)}
function drawSelectionBox(root,state){const ids=getCrossSelection(state);if(ids.length<2)return;const b=selectionBounds(state,ids),cx=b.x+b.w/2,hy=b.y-22,hs=Math.max(6,Math.min(12,Math.min(b.w,b.h)*.04));root.appendChild(make('rect',{x:b.x,y:b.y,width:b.w,height:b.h,fill:'none',stroke:'#18a06e','stroke-width':1.5,'stroke-dasharray':'5 4','vector-effect':'non-scaling-stroke','pointer-events':'none'}));root.appendChild(make('rect',{x:b.x+b.w-hs/2,y:b.y+b.h-hs/2,width:hs,height:hs,rx:1,fill:'#18a06e',stroke:'#fff','stroke-width':1,'data-v23-group':'resize'}));root.appendChild(make('line',{x1:cx,y1:b.y,x2:cx,y2:hy+5,stroke:'#18a06e','stroke-width':1.2,'vector-effect':'non-scaling-stroke','pointer-events':'none'}));root.appendChild(make('circle',{cx,cy:hy,r:6,fill:'#fff',stroke:'#18a06e','stroke-width':1.7,'data-v23-group':'rotate'}));const t=make('text',{x:b.x+4,y:b.y-5,fill:'#14835b','font-size':9,'font-weight':700,'pointer-events':'none'});t.textContent=`${ids.length} selected`;root.appendChild(t)}
function drawGuides(root,guides,geo){for(const g of guides||[]){if(g.kind==='spacing'){if(g.axis==='x'){root.appendChild(make('line',{x1:0,y1:g.value,x2:geo.width,y2:g.value,stroke:'#e07b16','stroke-width':1.1,'stroke-dasharray':'3 3','vector-effect':'non-scaling-stroke','pointer-events':'none'}));const t=make('text',{x:8,y:g.value-4,fill:'#b7600c','font-size':9,'font-weight':700,'pointer-events':'none'});t.textContent=`equal gap ${num(g.gap).toFixed(1)} mm`;root.appendChild(t)}else{root.appendChild(make('line',{x1:g.value,y1:0,x2:g.value,y2:geo.height,stroke:'#e07b16','stroke-width':1.1,'stroke-dasharray':'3 3','vector-effect':'non-scaling-stroke','pointer-events':'none'}));const t=make('text',{x:g.value+4,y:14,fill:'#b7600c','font-size':9,'font-weight':700,'pointer-events':'none'});t.textContent=`equal gap ${num(g.gap).toFixed(1)} mm`;root.appendChild(t)}continue;}if(g.axis==='x')root.appendChild(make('line',{x1:g.value,y1:0,x2:g.value,y2:geo.height,stroke:'#18a06e','stroke-width':1,'stroke-dasharray':'4 4','vector-effect':'non-scaling-stroke','pointer-events':'none'}));else root.appendChild(make('line',{x1:0,y1:g.value,x2:geo.width,y2:g.value,stroke:'#18a06e','stroke-width':1,'stroke-dasharray':'4 4','vector-effect':'non-scaling-stroke','pointer-events':'none'}))}}
function renderOverlay(svg,state,{guides=[]}={}){for(const id of ['boxstudio-v20-cross-overlay','boxstudio-v21-cross-overlay','boxstudio-v22-cross-overlay','boxstudio-v23-cross-overlay'])svg.querySelector(`#${id}`)?.remove();const root=make('g',{id:'boxstudio-v23-cross-overlay',class:'ui-only'}),sel=new Set(getCrossSelection(state)),single=sel.size===1,geo=generateGeometry(state.structure);for(const el of orderedElements(state.elements||[]).filter(e=>e?.type==='cross-panel-artwork'))drawItem(root,el,sel.has(el.id),single);drawSelectionBox(root,state);drawGuides(root,guides,geo);svg.appendChild(root)}
function installDrag(svg){let drag=null;svg.addEventListener('pointerdown',e=>{const clip=e.target.closest?.('[data-v23-clip-point]');if(clip){e.stopPropagation();e.preventDefault();const state=readState(),id=clip.dataset.v23ClipId,index=Number(clip.dataset.v23ClipPoint),p=svgPoint(svg,e);drag={mode:'clip-point',id,index,ids:[id],base:clone(state),start:p};svg.setPointerCapture?.(e.pointerId);return}const groupHandle=e.target.closest?.('[data-v23-group]');if(groupHandle){e.stopPropagation();e.preventDefault();const state=readState(),ids=getCrossSelection(state);if(ids.length<2)return;const p=svgPoint(svg,e),b=selectionBounds(state,ids),center={x:b.x+b.w/2,y:b.y+b.h/2};drag={mode:`group-${groupHandle.dataset.v23Group}`,ids,base:clone(state),start:p,bounds:b,center,startAngle:Math.atan2(p.y-center.y,p.x-center.x)*180/Math.PI};svg.setPointerCapture?.(e.pointerId);return}const target=e.target.closest?.('[data-v23-drag]'),group=target?.closest?.('[data-v23-id]');if(!target||!group)return;e.stopPropagation();e.preventDefault();let state=readState(),id=group.dataset.v23Id;state=toggleCrossSelection(state,id,{additive:e.shiftKey});const ids=getCrossSelection(state);if(!ids.includes(id)){writeState(state);renderOverlay(svg,state);return}const p=svgPoint(svg,e),el=state.elements.find(x=>x.id===id),mode=target.dataset.v23Drag,cx=num(el.x)+num(el.w)/2,cy=num(el.y)+num(el.h)/2;drag={mode,id,ids,base:clone(state),start:p,orig:{x:num(el.x),y:num(el.y),w:num(el.w),h:num(el.h),r:num(el.r)},center:{x:cx,y:cy},startAngle:Math.atan2(p.y-cy,p.x-cx)*180/Math.PI};svg.setPointerCapture?.(e.pointerId);writeState(state);renderOverlay(svg,state)});
svg.addEventListener('pointermove',e=>{if(!drag)return;e.stopPropagation();const p=svgPoint(svg,e),geo=generateGeometry(drag.base.structure),edit={snap:drag.base.crossPanelEdit?.snap!==false&&!e.altKey,gridMm:num(drag.base.crossPanelEdit?.gridMm,5),toleranceMm:num(drag.base.crossPanelEdit?.toleranceMm,3)};let draft=clone(drag.base),guides=[];if(drag.mode==='clip-point'){draft=moveCrossClipPoint(drag.base,drag.id,drag.index,p.x,p.y)}else if(drag.mode==='move'){const baseSnap=translateCrossSelection(drag.base,drag.ids,p.x-drag.start.x,p.y-drag.start.y,geo,edit),smart=smartSpacingDelta(drag.base,drag.ids,baseSnap.delta.x,baseSnap.delta.y,{enabled:drag.base.crossPanelEdit?.smartSpacing!==false&&!e.altKey,toleranceMm:num(drag.base.crossPanelEdit?.spacingToleranceMm,3)}),finalMove=translateCrossSelection(drag.base,drag.ids,smart.dx,smart.dy,geo,{snap:false});draft=finalMove.state;guides=[...baseSnap.guides,...smart.guides]}else if(drag.mode==='resize'){draft=resizeCrossElement(drag.base,drag.id,drag.orig.w+(p.x-drag.start.x),drag.orig.h+(p.y-drag.start.y),{lockAspect:!e.shiftKey})}else if(drag.mode==='rotate'){const angle=Math.atan2(p.y-drag.center.y,p.x-drag.center.x)*180/Math.PI,raw=drag.orig.r+(angle-drag.startAngle);draft=rotateCrossElement(drag.base,drag.id,raw,{snap:!e.altKey,step:num(drag.base.crossPanelEdit?.angleStep,15)})}else if(drag.mode==='group-resize'){const sx=Math.max(.05,(drag.bounds.w+(p.x-drag.start.x))/Math.max(.001,drag.bounds.w)),sy=Math.max(.05,(drag.bounds.h+(p.y-drag.start.y))/Math.max(.001,drag.bounds.h));draft=scaleCrossSelection(drag.base,drag.ids,{scaleX:sx,scaleY:sy,origin:{x:drag.bounds.x,y:drag.bounds.y},lockAspect:e.shiftKey})}else if(drag.mode==='group-rotate'){const angle=Math.atan2(p.y-drag.center.y,p.x-drag.center.x)*180/Math.PI,delta=angle-drag.startAngle;draft=rotateCrossSelection(drag.base,drag.ids,delta,{origin:drag.center,snap:!e.altKey,step:num(drag.base.crossPanelEdit?.angleStep,15)})}draft=setCrossSelection(draft,drag.ids);drag.draft=draft;renderOverlay(svg,draft,{guides})});
const finish=e=>{if(!drag)return;e?.stopPropagation?.();writeState(drag.draft||drag.base);drag=null;location.reload()};svg.addEventListener('pointerup',finish);svg.addEventListener('pointercancel',finish)}
function install(){const svg=document.querySelector('#designSvg');if(!svg||svg.dataset.v23OverlayInstalled==='1')return;svg.dataset.v23OverlayInstalled='1';renderOverlay(svg,readState());installDrag(svg)}
const observer=new MutationObserver(()=>install());observer.observe(document.documentElement,{childList:true,subtree:true});install();
