import {setUiVersion} from './uiVersion.js';
import { STORAGE_KEY, defaultState } from './model.js';
import { exportProductionPdfV23, productionPdfV23Diagnostics } from './productionPdfV23.js';
import { exportNativeGradientPdfV22 } from './nativePdfV22.js';
import { exportProductionSvgV20 } from './nativeSvgV20.js';
import { exportProductionPdfV19 } from './exportV19.js';
import { getCrossSelection } from './crossPanelTransformV21.js';
import { ensureCrossClip } from './clipEditorV23.js';
import { loadRgbCmykDeviceLink, clearRgbCmykDeviceLink, getDeviceLinkInfo } from './iccDeviceLinkV23.js';

const BLOCK_ID='boxstudio-v23-tools',clone=v=>structuredClone(v);
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,crossPanelEdit:{...defaultState.crossPanelEdit,...(p.crossPanelEdit||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}
function hideSuperseded(){for(const id of ['boxstudio-v22-tools','boxstudio-v21-tools','boxstudio-v20-tools'])document.getElementById(id)?.setAttribute('hidden','');}
function selectedCross(state){const id=getCrossSelection(state).at(-1);return(state.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork')||null;}
function commit(s){writeState(s);location.reload();}
function render(block){const host=block.querySelector('#v23Workspace');if(!host)return;try{const state=readState(),diag=productionPdfV23Diagnostics(state),link=getDeviceLinkInfo(),sel=selectedCross(state),edit={smartSpacing:true,spacingToleranceMm:3,...(state.crossPanelEdit||{})};host.innerHTML=`<div class="v23-stats"><span>${diag.nativeAppearanceObjects} native appearance object(s)</span><span>${diag.axial} axial</span><span>${diag.radial} radial</span><span>${diag.softMasks} soft mask(s)</span><span>${esc(diag.colorSpace)}</span><span>${diag.pdfxCandidate?'PDF/X-4 Candidate':'PDF standard'}</span></div>
<section><h4>Integrated Production PDF V0.23</h4><p>The complete production route now combines marks, barcode/QR, dielines, spot separations, text/vector outlines and the V0.22 native gradient/soft-mask appearance path in one PDF serializer.</p><div class="v23-actions"><button id="v23Production" class="primary">Export V0.23 Integrated Production PDF</button><button id="v23Proof">V0.22 Appearance Proof</button><button id="v23Svg">Native Gradient SVG</button><button id="v23Fallback">V0.19 Tessellation Fallback</button></div><div class="v23-note">PDF/X remains a BoxStudio Candidate workflow, not third-party certification. When Candidate mode is enabled, the existing CMYK OutputIntent and outline-text checks still apply.</div></section>
<section><h4>ICC Artwork Conversion · Verified Subset</h4><p>V0.23 can convert imported native SVG RGB appearance colors through a loaded ICC DeviceLink only when it is an RGB→CMYK <code>A2B0</code> LUT8 (<code>mft1</code>) profile. Normal CMYK printer profiles remain OutputIntent profiles and are not silently treated as conversion engines.</p><div class="v23-file"><input id="v23LinkFile" type="file" accept=".icc,.icm,application/vnd.iccprofile"><button id="v23ClearLink">Clear DeviceLink</button>${link?`<span class="v23-badge">${esc(link.name)} · ${link.tagType} · grid ${link.gridPoints}</span>`:'<span class="v23-badge">No conversion DeviceLink loaded</span>'}</div>${link?`<div class="v23-good">Active conversion: ${esc(link.inputColorSpace)} → ${esc(link.outputColorSpace)} · ${esc(link.tagType)} · ${link.gridPoints}³ CLUT.</div>`:'<div class="v23-note">Without a verified DeviceLink, native imported artwork remains DeviceRGB. A CMYK OutputIntent alone does not perform vector color conversion.</div>'}</section>
<section><h4>Live Smart Spacing</h4><p>While dragging Cross-panel artwork, V0.23 can snap the moving selection to equal left/right or top/bottom gaps between neighboring Cross-panel objects. Orange guides identify the matched spacing.</p><div class="v23-grid"><label class="check"><input id="v23Spacing" type="checkbox" ${edit.smartSpacing!==false?'checked':''}> Enable equal-spacing snap</label><label>Spacing tolerance mm<input id="v23SpacingTol" type="number" min="0" step="0.5" value="${Number(edit.spacingToleranceMm)||3}"></label></div><div class="v23-actions"><button id="v23SaveSpacing">Save Spacing Settings</button></div></section>
<section><h4>Graphical Clip-point Editing</h4>${sel?`<p>Selected: <b>${esc(sel.label||sel.id)}</b>. ${Array.isArray(sel.crossClip?.points)&&sel.crossClip.points.length>=3?'Cyan clip points are draggable directly in the Design canvas.':'Create a rectangular clip to expose draggable cyan clip points.'}</p><div class="v23-actions"><button id="v23CreateClip" ${Array.isArray(sel.crossClip?.points)&&sel.crossClip.points.length>=3?'disabled':''}>Create Full Clip</button><button id="v23InsetClip">Create 10% Inset Clip</button></div>`:'<div class="v23-note">Select one Cross-panel artwork object to edit its clip path graphically.</div>'}<div class="v23-note">Clip points are stored as normalized object-space coordinates, so they continue to scale and rotate with the artwork and feed production materialization plus folded 3D fragments.</div></section>
<section><h4>V0.23 Boundary</h4><p>Integrated native PDF appearance is implemented for the current safe SVG subset. Arbitrary SVG filter/mask trees, general ICC profile chaining, certified PDF/X, RIP trapping and calibrated soft proofing are still outside this release.</p></section>`;
  host.querySelector('#v23Production').onclick=()=>{try{exportProductionPdfV23(readState())}catch(e){alert(e?.message||e)}};host.querySelector('#v23Proof').onclick=()=>{try{exportNativeGradientPdfV22(readState())}catch(e){alert(e?.message||e)}};host.querySelector('#v23Svg').onclick=()=>{try{exportProductionSvgV20(document.querySelector('#designSvg'),readState())}catch(e){alert(e?.message||e)}};host.querySelector('#v23Fallback').onclick=()=>{try{exportProductionPdfV19(readState())}catch(e){alert(e?.message||e)}};
  host.querySelector('#v23LinkFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{loadRgbCmykDeviceLink(await file.arrayBuffer(),file.name);render(block)}catch(err){alert(err?.message||err);e.target.value='';}};host.querySelector('#v23ClearLink').onclick=()=>{clearRgbCmykDeviceLink();render(block)};
  host.querySelector('#v23SaveSpacing').onclick=()=>{const s=readState();s.crossPanelEdit={...(s.crossPanelEdit||{}),smartSpacing:host.querySelector('#v23Spacing').checked,spacingToleranceMm:Math.max(0,Number(host.querySelector('#v23SpacingTol').value)||3)};commit(s)};
  if(sel){host.querySelector('#v23CreateClip').onclick=()=>{const s=readState();commit(ensureCrossClip(s,sel.id,{inset:0}))};host.querySelector('#v23InsetClip').onclick=()=>{const s=readState(),next=ensureCrossClip(s,sel.id,{inset:.1}),el=next.elements.find(x=>x.id===sel.id);el.crossClip={type:'polygon',points:[[.1,.1],[.9,.1],[.9,.9],[.1,.9]]};commit(next)};}
}catch(error){host.innerHTML=`<div class="v23-warning">${esc(error?.message||error)}</div>`}}
function install(){hideSuperseded();const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v23-tools';block.innerHTML=`<div class="v23-title"><div><h3>V0.23 Integrated Production & Color</h3><p>Native production PDF · LUT8 DeviceLink · draggable clip points · live equal-spacing snap.</p></div><span>V0.23</span></div><div id="v23Workspace"></div>`;scroll.appendChild(block);render(block)}
function updateVersion(){setUiVersion('V0.23')}
const observer=new MutationObserver(()=>{updateVersion();hideSuperseded();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
