import { STORAGE_KEY, defaultState } from './model.js';
import { buildProductionPdfV24, productionPdfV24Diagnostics, currentDeviceLinkReference, deviceLinkBindingStatus } from './productionPdfV24.js';
import { loadRgbCmykDeviceLink, clearRgbCmykDeviceLink, getDeviceLinkInfo } from './iccDeviceLinkV23.js';
import { collectWorkerAssetsV24, transferableWorkerAssetsV24, workerAssetAvailabilityV24, describeWorkerAssetsV24 } from './workerAssetsV24.js';
import { workerBatchEligibility } from './batchWorkerCore.js';
import { createIndexedDbArtifactStore, createMemoryArtifactStore } from './artifactStore.js';
import { preparePersistentQueue, queueWithClaim, queueWithComplete, queueWithFailure, pausePersistentQueue, finalizePersistentPause, resumePersistentQueue, cancelPersistentQueue, finalizePersistentCancel, persistentQueueProgress, persistentQueueState } from './persistentBatch.js';
import { retryFailedJobs } from './jobQueue.js';
import { attachBatchRunContextV24, batchRunCompatibilityV24, batchRunBaseStateV24 } from './batchRunV24.js';
import { activeProductionJob, recordProductionExport, upsertProductionJob } from './productionJobs.js';
import { productionOutputGateV24 } from './productionOutputV24.js';
import { canProductionAction, normalizeProductionRole } from './permissions.js';
import { downloadBytes } from './export.js';

const BLOCK_ID='boxstudio-v24-tools';
const artifactStore=globalThis.indexedDB?createIndexedDbArtifactStore():createMemoryArtifactStore();
let runToken=0,activeWorker=null;
const clone=v=>structuredClone(v);
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function safe(v='boxstudio'){return String(v||'boxstudio').trim().replace(/[\\/:*?"<>|\s]+/g,'-').replace(/^-+|-+$/g,'')||'boxstudio';}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,batch:{...defaultState.batch,...(p.batch||{})},exportOptions:{...defaultState.exportOptions,...(p.exportOptions||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}
function actor(s){return String(s.productionActor||'local-user').trim()||'local-user';}
function role(s){return normalizeProductionRole(s.productionRole||'operator');}
function yieldUi(){return new Promise(r=>setTimeout(r,0));}
function hideSuperseded(){document.getElementById('boxstudio-v23-tools')?.setAttribute('hidden','');for(const id of ['v16Worker','v15WorkerBatch','v14Batch'])document.getElementById(id)?.closest('section')?.setAttribute('hidden','');for(const id of ['v14ApprovedPdf','v15ApprovedPdf'])document.getElementById(id)?.setAttribute('hidden','');}
function workerRequest(worker,data,transfer=[]){return new Promise((resolve,reject)=>{const requestId=`v24-${Date.now()}-${Math.random().toString(36).slice(2)}`,done=()=>{worker.removeEventListener('message',onMessage);worker.removeEventListener('error',onError)},onMessage=e=>{if(e.data?.requestId!==requestId)return;done();e.data?.ok===false?reject(new Error(e.data.error||'Worker failed')):resolve(e.data)},onError=e=>{done();reject(e.error||new Error(e.message||'Worker failed'))};worker.addEventListener('message',onMessage);worker.addEventListener('error',onError);worker.postMessage({...data,requestId},transfer)})}

function bindCurrentLinkToState(){const ref=currentDeviceLinkReference();if(!ref)throw new Error('No verified DeviceLink is loaded.');const s=readState();s.exportOptions={...(s.exportOptions||{}),deviceLinkRef:ref};writeState(s);return s;}
function removeLinkBinding(){const s=readState();const options={...(s.exportOptions||{})};delete options.deviceLinkRef;s.exportOptions=options;writeState(s);}
function renderOutput(block){const host=block.querySelector('#v24Output');if(!host)return;const s=readState(),diag=productionPdfV24Diagnostics(s),loaded=getDeviceLinkInfo(),declared=s.exportOptions?.deviceLinkRef||null,job=activeProductionJob(s),gate=productionOutputGateV24(s,job),currentRole=role(s),canApproved=gate.ok&&canProductionAction(currentRole,'export-approved');host.innerHTML=`<div class="v24-stats"><span>${diag.nativeAppearanceObjects} native object(s)</span><span>${diag.axial} axial</span><span>${diag.radial} radial</span><span>${diag.softMasks} soft mask(s)</span><span>${esc(diag.colorSpace)}</span><span>${declared?'DeviceLink bound':'RGB native appearance'}</span></div>
<div class="v24-file"><input id="v24LinkFile" type="file" accept=".icc,.icm,application/vnd.iccprofile"><button id="v24UnloadLink">Unload Session</button><button id="v24RemoveBinding" class="danger" ${declared?'':'disabled'}>Remove Binding</button>${loaded?`<span class="v24-badge">loaded ${esc(loaded.name)} · ${esc(loaded.fingerprint)}</span>`:'<span class="v24-badge">no session DeviceLink</span>'}</div>
${declared?`<div class="v24-note">Project binding: ${esc(declared.name||'DeviceLink')} · ${esc(declared.fingerprint||'unknown')} · ${declared.tagType||''} · grid ${declared.gridPoints||'?'}. The binding is part of the production fingerprint.</div>`:'<div class="v24-note">No DeviceLink is declared. V0.24 deliberately keeps imported native appearance in RGB even if an unrelated DeviceLink happens to be loaded elsewhere.</div>'}
<div class="v24-actions"><button id="v24Draft" class="primary">Export V0.24 Production PDF</button><button id="v24Approved" ${canApproved?'':'disabled'}>Export Approved V0.24 PDF</button></div><div class="v24-gate ${gate.ok?'ok':'blocked'}">${esc(gate.reason)}</div><div class="v24-note">Approved export requires: approved revision fingerprint match + role permission + exact DeviceLink content fingerprint match when a DeviceLink is declared.</div>`;
  host.querySelector('#v24LinkFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{loadRgbCmykDeviceLink(await file.arrayBuffer(),file.name);bindCurrentLinkToState();renderOutput(block);renderBatch(block)}catch(err){alert(err?.message||err);e.target.value=''}};
  host.querySelector('#v24UnloadLink').onclick=()=>{clearRgbCmykDeviceLink();renderOutput(block);renderBatch(block)};
  host.querySelector('#v24RemoveBinding').onclick=()=>{clearRgbCmykDeviceLink();removeLinkBinding();renderOutput(block);renderBatch(block)};
  host.querySelector('#v24Draft').onclick=()=>{try{const current=readState(),bytes=buildProductionPdfV24(current);downloadBytes(`${safe(current.variables?.sku||'boxstudio')}-v24-production.pdf`,bytes,'application/pdf')}catch(e){alert(e?.message||e)}};
  host.querySelector('#v24Approved').onclick=()=>{const current=readState(),active=activeProductionJob(current),g=productionOutputGateV24(current,active),r=role(current);if(!g.ok||!canProductionAction(r,'export-approved')){alert(g.ok?'Current role cannot export approved production files.':g.reason);return}try{const fileName=`${safe(current.variables?.sku||'production')}-approved-r${active.revision}-v24.pdf`,bytes=buildProductionPdfV24(current);downloadBytes(fileName,bytes,'application/pdf');const updated=recordProductionExport(active,{actor:actor(current),role:r,format:'pdf',fileName,serializer:'v0.24-native-production'});writeState(upsertProductionJob(current,updated));renderOutput(block)}catch(e){alert(e?.message||e)}};
}

async function batchSnapshot(){const s=readState(),q=s.batch?.queue,a=q?.id?await artifactStore.list(q.id):[];return{state:s,queue:q,artifacts:a};}
function batchText(p,q){return`${p.percent}% · ${p.completed} completed · ${p.failed} failed · ${p.pending} pending · ${p.artifactCount} persisted · ${Math.round((p.bytes||0)/1024)} KB${q?.status?` · ${q.status}`:''}`;}
async function renderBatch(block){const host=block.querySelector('#v24Batch');if(!host)return;const snap=await batchSnapshot(),q=snap.queue,arts=snap.artifacts,p=persistentQueueProgress(q||{items:[]},arts),assets=collectWorkerAssetsV24(),availability=workerAssetAvailabilityV24(assets),base=q?.kind==='worker-pdf-zip-v24'&&q?.context?.baseState?q.context.baseState:snap.state,eligibility=workerBatchEligibility(base,availability),compat=q?.kind==='worker-pdf-zip-v24'?batchRunCompatibilityV24(snap.state,q):{ok:true,reason:'New V0.24 run will capture the current rows.'},desc=describeWorkerAssetsV24(assets),usable=typeof Worker!=='undefined'&&eligibility.ok&&compat.ok;host.innerHTML=`<div class="v24-stats"><span>TTF ${esc(desc.ttf)}</span><span>Output ICC ${esc(desc.icc)}</span><span>DeviceLink ${esc(desc.deviceLink)}</span></div><div class="v24-actions"><button id="v24BatchStart" class="primary" ${usable?'':'disabled'}>${q?.kind==='worker-pdf-zip-v24'?'Resume / Reconcile':'Start V0.24 Native Batch'}</button><button id="v24BatchRestart" ${typeof Worker!=='undefined'?'':'disabled'}>Restart with Current Project</button><button id="v24BatchPause" ${q&&!p.done?'':'disabled'}>Pause</button><button id="v24BatchCancel" ${q&&!p.done?'':'disabled'}>Cancel</button><button id="v24BatchRetry" ${q&&(p.failed||p.cancelled)?'':'disabled'}>Retry Failed / Cancelled</button><button id="v24BatchZip" ${p.artifactCount?'':'disabled'}>Recovered ZIP</button></div><div class="v24-progress"><i style="width:${p.percent}%"></i></div><div class="v24-mono">${esc(batchText(p,q))}</div>${!compat.ok?`<div class="v24-warning">${esc(compat.reason)}</div>`:''}${!eligibility.ok?`<div class="v24-warning">${eligibility.blockers.map(esc).join('<br>')}</div>`:''}<div class="v24-note">V0.24 freezes the base production state when a batch starts. Later project edits do not change remaining rows. Row-table changes are detected and force a restart instead of silently mixing configurations.</div><div class="v24-artifacts">${arts.slice(-8).reverse().map(a=>`<div><span>${esc(a.fileName)}</span><small>${esc(a.serializer||'legacy')} · ${esc(a.colorSpace||'')} ${a.deviceLinkFingerprint?`· ${esc(a.deviceLinkFingerprint)}`:''}</small></div>`).join('')}</div>`;
  host.querySelector('#v24BatchStart').onclick=()=>runBatch(block,false);host.querySelector('#v24BatchRestart').onclick=()=>runBatch(block,true);host.querySelector('#v24BatchPause').onclick=()=>{const s=readState();if(s.batch?.queue){s.batch.queue=pausePersistentQueue(s.batch.queue);writeState(s);renderBatch(block)}};host.querySelector('#v24BatchCancel').onclick=()=>{const s=readState();if(s.batch?.queue){s.batch.queue=cancelPersistentQueue(s.batch.queue);writeState(s);renderBatch(block)}};host.querySelector('#v24BatchRetry').onclick=()=>{const s=readState();if(s.batch?.queue){s.batch.queue=retryFailedJobs(s.batch.queue);writeState(s);renderBatch(block)}};host.querySelector('#v24BatchZip').onclick=()=>exportBatchZip(block);
}
async function runBatch(block,restart=false){const my=++runToken;if(activeWorker){activeWorker.terminate();activeWorker=null}let s=readState();if(!s.batch?.rows?.length){alert('请先导入 Excel / CSV。');return}if(typeof Worker==='undefined'){alert('Worker API unavailable.');return}if(restart&&s.batch?.queue?.id)await artifactStore.clearQueue(s.batch.queue.id);let arts=s.batch?.queue?.id?await artifactStore.list(s.batch.queue.id):[],q=preparePersistentQueue(s,arts,{restart,kind:'worker-pdf-zip-v24'});q=attachBatchRunContextV24(q,s,{restart:restart||!q.context});const compat=batchRunCompatibilityV24(s,q);if(!compat.ok){alert(compat.reason);return}const assets=collectWorkerAssetsV24(),availability=workerAssetAvailabilityV24(assets),eligibility=workerBatchEligibility(batchRunBaseStateV24(q),availability);if(!eligibility.ok){alert(eligibility.blockers.join('\n'));return}if(q.status==='paused')q=resumePersistentQueue(q);writeState(persistentQueueState(s,q));await renderBatch(block);const worker=new Worker(new URL('./batchPdf.worker.js',import.meta.url),{type:'module'});activeWorker=worker;try{const tx=transferableWorkerAssetsV24(assets);await workerRequest(worker,{type:'init-assets',workerAssets:tx.payload},tx.transfer);while(my===runToken){s=readState();q=s.batch.queue;arts=await artifactStore.list(q.id);q=preparePersistentQueue(s,arts,{kind:'worker-pdf-zip-v24'});const liveCompat=batchRunCompatibilityV24(s,q);if(!liveCompat.ok){q.status='blocked-input-changed';q.updatedAt=new Date().toISOString();writeState(persistentQueueState(s,q));break}if(q.cancelRequested){q=finalizePersistentCancel(q);writeState(persistentQueueState(s,q));break}if(q.pauseRequested){q=finalizePersistentPause(q);writeState(persistentQueueState(s,q));break}const claim=queueWithClaim(q);q=claim.queue;writeState(persistentQueueState(s,q));if(!claim.item)break;const index=claim.item.index,row=s.batch.rows[index],baseState=batchRunBaseStateV24(q);try{const result=await workerRequest(worker,{baseState,row,index});await artifactStore.put({queueId:q.id,index,fileName:result.fileName,mime:'application/pdf',bytes:result.bytes,fingerprint:result.fingerprint,serializer:result.serializer,colorSpace:result.colorSpace,deviceLinkFingerprint:result.deviceLinkFingerprint});q=queueWithComplete(q,index,result.fileName)}catch(error){q=queueWithFailure(q,index,error?.message||String(error))}s=readState();writeState(persistentQueueState(s,q));await renderBatch(block);await yieldUi()}}finally{worker.terminate();if(activeWorker===worker)activeWorker=null;await renderBatch(block)}}
async function exportBatchZip(block){const {queue,artifacts}=await batchSnapshot();if(!queue||!artifacts.length)return;if(!globalThis.JSZip){alert('JSZip 未加载。');return}const zip=new globalThis.JSZip();for(const a of artifacts)zip.file(a.fileName,a.bytes);zip.file('boxstudio-v24-artifacts.json',JSON.stringify({queueId:queue.id,status:queue.status,serializer:queue.context?.serializer||'',rowsFingerprint:queue.context?.rowsFingerprint||'',deviceLinkRef:queue.context?.deviceLinkRef||null,files:artifacts.map(a=>({index:a.index,fileName:a.fileName,byteLength:a.byteLength,fingerprint:a.fingerprint,serializer:a.serializer,colorSpace:a.colorSpace,deviceLinkFingerprint:a.deviceLinkFingerprint}))},null,2));const bytes=await zip.generateAsync({type:'uint8array',compression:'DEFLATE',compressionOptions:{level:6}});downloadBytes(`boxstudio-${safe(queue.id)}-v24-native.zip`,bytes,'application/zip');await renderBatch(block)}

function render(block){renderOutput(block);renderBatch(block)}
function install(){hideSuperseded();const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v24-tools';block.innerHTML=`<div class="v24-title"><div><h3>V0.24 Native Production Pipeline</h3><p>V0.23 native PDF in Batch Worker · frozen run context · DeviceLink asset binding · approved-export audit.</p></div><span>V0.24</span></div><section><h4>Production Output & Approval Gate</h4><div id="v24Output"></div></section><section><h4>Native PDF Batch Worker</h4><div id="v24Batch"></div></section>`;scroll.appendChild(block);render(block)}
function updateVersion(){const v=document.querySelector('.brand small');if(v)v.textContent='V0.24';document.title='BoxStudio V0.24'}
const observer=new MutationObserver(()=>{updateVersion();hideSuperseded();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
