import { STORAGE_KEY, defaultState } from './model.js';
import { getCrossSelection } from './crossPanelTransformV21.js';
import { crossClipNodes, ensureBezierClipState, removeClipNodeV25, resetClipNodeHandlesV25, setClipNodeHandlePresetV25, toggleClipNodeSmoothV25, clipPathDiagnosticsV25 } from './clipPathV25.js';
import { loadRgbCmykDeviceLink, clearRgbCmykDeviceLink, getDeviceLinkInfo, convertRgbToCmyk } from './iccDeviceLinkV23.js';
import { currentDeviceLinkReference } from './productionPdfV24.js';
import { buildProductionPdfV25, productionPdfV25Diagnostics } from './productionPdfV25.js';
import { productionOutputGateV24 } from './productionOutputV24.js';
import { activeProductionJob, recordProductionExport, upsertProductionJob } from './productionJobs.js';
import { canProductionAction, normalizeProductionRole } from './permissions.js';
import { downloadBytes } from './export.js';

const BLOCK_ID='boxstudio-v25-tools',clone=v=>structuredClone(v);
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function safe(v='boxstudio'){return String(v||'boxstudio').trim().replace(/[\\/:*?"<>|\s]+/g,'-').replace(/^-+|-+$/g,'')||'boxstudio';}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,crossPanelEdit:{...defaultState.crossPanelEdit,...(p.crossPanelEdit||{})},exportOptions:{...defaultState.exportOptions,...(p.exportOptions||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}
function actor(s){return String(s.productionActor||'local-user').trim()||'local-user';}
function role(s){return normalizeProductionRole(s.productionRole||'operator');}
function selectedCross(state){const id=getCrossSelection(state).at(-1);return(state.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork')||null;}
function selectedNodeIndex(state,el){const nodes=crossClipNodes(el),raw=Number(state.crossPanelEdit?.clipNodeIndex)||0;return nodes.length?Math.max(0,Math.min(nodes.length-1,raw)):0;}
function commit(s,{reload=false}={}){writeState(s);if(reload)location.reload();}
function bindLoadedDeviceLink(){const ref=currentDeviceLinkReference();if(!ref)throw new Error('No verified DeviceLink is loaded.');const s=readState();s.exportOptions={...(s.exportOptions||{}),deviceLinkRef:ref};writeState(s);return s;}
function hexRgb(value){const m=String(value||'').trim().match(/^#?([0-9a-f]{6})$/i);if(!m)return null;const n=parseInt(m[1],16);return[(n>>16&255)/255,(n>>8&255)/255,(n&255)/255];}
function render(block){const host=block.querySelector('#v25Workspace');if(!host)return;try{const s=readState(),el=selectedCross(s),nodes=el?crossClipNodes(el):[],nodeIndex=el?selectedNodeIndex(s,el):0,clipDiag=el?clipPathDiagnosticsV25(el):null,edit={objectGuides:true,objectGuideToleranceMm:3,smartSpacing:true,spacingToleranceMm:3,...(s.crossPanelEdit||{})},icc=getDeviceLinkInfo(),diag=productionPdfV25Diagnostics(s),job=activeProductionJob(s),gate=productionOutputGateV24(s,job),r=role(s),canApproved=gate.ok&&canProductionAction(r,'export-approved');host.innerHTML=`
<section><h4>Bezier Clip Direct Selection</h4>${el?`<div class="v25-stats"><span>${esc(el.label||el.id)}</span><span>${clipDiag.nodeCount} node(s)</span><span>${clipDiag.curvedNodes} curved</span><span>${clipDiag.flattenedPoints} production points</span><span>node ${nodeIndex+1}</span></div><div class="v25-actions"><button id="v25EnsureClip">Convert / Create Bezier Clip</button><button id="v25Smooth">Make Selected Smooth</button><button id="v25Corner">Make Selected Corner</button><button id="v25DeleteNode" class="danger" ${nodes.length>3?'':'disabled'}>Delete Selected Node</button></div><div class="v25-note">Canvas: drag cyan anchor = move node · drag orange handles = edit tangent · Alt while dragging a handle breaks symmetry · click orange diamond = insert node without changing the existing cubic curve shape · Alt+click anchor = delete node.</div>`:'<div class="v25-note">Select one Cross-panel artwork object in the Design canvas to edit its clip path.</div>'}</section>
<section><h4>Illustrator-style Object Smart Guides</h4><p>V0.25 adds object-to-object left/center/right and top/middle/bottom alignment snapping, width/height match hints during resize, while keeping equal-gap spacing, Panel and Grid snapping.</p><div class="v25-grid"><label class="check"><input id="v25ObjectGuides" type="checkbox" ${edit.objectGuides!==false?'checked':''}> Object alignment guides</label><label>Alignment tolerance mm<input id="v25GuideTol" type="number" min="0" step="0.5" value="${Number(edit.objectGuideToleranceMm)||3}"></label><label class="check"><input id="v25Spacing" type="checkbox" ${edit.smartSpacing!==false?'checked':''}> Equal-gap spacing guides</label><label>Spacing tolerance mm<input id="v25SpacingTol" type="number" min="0" step="0.5" value="${Number(edit.spacingToleranceMm)||3}"></label></div><div class="v25-actions"><button id="v25SaveGuides">Save Smart Guide Settings</button></div><div class="v25-note">Magenta = object alignment / size match. Orange = equal spacing. Green = Panel/Grid snap. Hold Alt during a drag to bypass smart snapping for that gesture.</div></section>
<section><h4>ICC DeviceLink V0.25 · LUT8 + LUT16</h4><p>The verified RGB→CMYK DeviceLink subset now accepts both A2B0 LUT8 (<code>mft1</code>) and LUT16 (<code>mft2</code>). mAB/mBA and arbitrary source-profile → printer-profile CMM linking are still not claimed.</p><div class="v25-file"><input id="v25IccFile" type="file" accept=".icc,.icm,application/vnd.iccprofile"><button id="v25ClearIcc">Unload Session</button>${icc?`<span class="v25-badge">${esc(icc.name)} · ${esc(icc.tagType)} · ${icc.precision}-bit · grid ${icc.gridPoints} · ${esc(icc.fingerprint)}</span>`:'<span class="v25-badge">No DeviceLink loaded</span>'}</div><div class="v25-grid"><label>RGB test color<input id="v25Rgb" type="text" value="#FF6600"></label><label>Converted CMYK<div id="v25Cmyk" class="v25-cmyk">${icc?'enter a color and test':'requires loaded DeviceLink'}</div></label></div><div class="v25-actions"><button id="v25TestColor" ${icc?'':'disabled'}>Test DeviceLink Conversion</button></div></section>
<section><h4>V0.25 Production Output</h4><div class="v25-stats"><span>${diag.nativeAppearanceObjects} native object(s)</span><span>${diag.axial} axial</span><span>${diag.radial} radial</span><span>${diag.softMasks} soft mask(s)</span><span>${esc(diag.colorSpace)}</span><span>${icc?`${icc.precision}-bit ${icc.tagType}`:'RGB/no DeviceLink'}</span></div><div class="v25-actions"><button id="v25Pdf" class="primary">Export V0.25 Production PDF</button><button id="v25Approved" ${canApproved?'':'disabled'}>Export Approved V0.25 PDF</button></div><div class="v25-${gate.ok?'good':'warning'}">${esc(gate.reason)}</div><div class="v25-note">V0.25 production reuses the integrated V0.24 approval/binding gate while adding Bezier clip flattening and LUT16 DeviceLink conversion to the shared production path.</div></section>`;
  host.querySelector('#v25EnsureClip')?.addEventListener('click',()=>{let n=ensureBezierClipState(readState(),el.id,{inset:.05});n.crossPanelEdit={...(n.crossPanelEdit||{}),clipNodeIndex:0};commit(n,{reload:true})});
  host.querySelector('#v25Smooth')?.addEventListener('click',()=>{let n=ensureBezierClipState(readState(),el.id);n=setClipNodeHandlePresetV25(n,el.id,selectedNodeIndex(n,n.elements.find(x=>x.id===el.id)),{length:.12,angleDeg:0});commit(n,{reload:true})});
  host.querySelector('#v25Corner')?.addEventListener('click',()=>{let n=ensureBezierClipState(readState(),el.id);n=resetClipNodeHandlesV25(n,el.id,selectedNodeIndex(n,n.elements.find(x=>x.id===el.id)));commit(n,{reload:true})});
  host.querySelector('#v25DeleteNode')?.addEventListener('click',()=>{let n=removeClipNodeV25(readState(),el.id,nodeIndex);n.crossPanelEdit={...(n.crossPanelEdit||{}),clipNodeIndex:Math.max(0,nodeIndex-1)};commit(n,{reload:true})});
  host.querySelector('#v25SaveGuides').onclick=()=>{const n=readState();n.crossPanelEdit={...(n.crossPanelEdit||{}),objectGuides:host.querySelector('#v25ObjectGuides').checked,objectGuideToleranceMm:Math.max(0,Number(host.querySelector('#v25GuideTol').value)||3),smartSpacing:host.querySelector('#v25Spacing').checked,spacingToleranceMm:Math.max(0,Number(host.querySelector('#v25SpacingTol').value)||3)};commit(n,{reload:true})};
  host.querySelector('#v25IccFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{loadRgbCmykDeviceLink(await file.arrayBuffer(),file.name);bindLoadedDeviceLink();render(block)}catch(err){alert(err?.message||err);e.target.value=''}};
  host.querySelector('#v25ClearIcc').onclick=()=>{clearRgbCmykDeviceLink();render(block)};
  host.querySelector('#v25TestColor').onclick=()=>{const rgb=hexRgb(host.querySelector('#v25Rgb').value);if(!rgb){alert('Use a 6-digit RGB hex color, for example #FF6600.');return}const cmyk=convertRgbToCmyk(rgb);host.querySelector('#v25Cmyk').textContent=cmyk?`C ${Math.round(cmyk[0]*100)}% · M ${Math.round(cmyk[1]*100)}% · Y ${Math.round(cmyk[2]*100)}% · K ${Math.round(cmyk[3]*100)}%`:'No DeviceLink loaded';};
  host.querySelector('#v25Pdf').onclick=()=>{try{const n=readState(),bytes=buildProductionPdfV25(n);downloadBytes(`${safe(n.variables?.sku||'boxstudio')}-v25-production.pdf`,bytes,'application/pdf')}catch(err){alert(err?.message||err)}};
  host.querySelector('#v25Approved').onclick=()=>{const n=readState(),active=activeProductionJob(n),g=productionOutputGateV24(n,active),rr=role(n);if(!g.ok||!canProductionAction(rr,'export-approved')){alert(g.ok?'Current role cannot export approved production files.':g.reason);return}try{const fileName=`${safe(n.variables?.sku||'production')}-approved-r${active.revision}-v25.pdf`,bytes=buildProductionPdfV25(n);downloadBytes(fileName,bytes,'application/pdf');const updated=recordProductionExport(active,{actor:actor(n),role:rr,format:'pdf',fileName,serializer:'v0.25-native-production'});writeState(upsertProductionJob(n,updated));render(block)}catch(err){alert(err?.message||err)}};
}catch(error){host.innerHTML=`<div class="v25-warning">${esc(error?.message||error)}</div>`}}
function install(){const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v25-tools';block.innerHTML=`<div class="v25-title"><div><h3>V0.25 Direct Selection & Color Precision</h3><p>Bezier clip nodes · segment insertion/deletion · object Smart Guides · ICC LUT16 DeviceLink.</p></div><span>V0.25</span></div><div id="v25Workspace"></div>`;scroll.appendChild(block);render(block)}
function updateVersion(){const v=document.querySelector('.brand small');if(v)v.textContent='V0.25';document.title='BoxStudio V0.25'}
const observer=new MutationObserver(()=>{updateVersion();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
