import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry } from './geometry.js';
import { normalizeUserGuidesV26, updateUserGuideV26, textBaselinesV26 } from './smartGuidesV26.js';

const NS='http://www.w3.org/2000/svg',clone=v=>structuredClone(v);
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,crossPanelEdit:{...defaultState.crossPanelEdit,...(p.crossPanelEdit||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}
function make(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n;}
function svgPoint(svg,e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const m=svg.getScreenCTM();return m?p.matrixTransform(m.inverse()):{x:0,y:0};}
function render(){const svg=document.querySelector('#designSvg');if(!svg)return;const s=readState(),geo=generateGeometry(s.structure),baselines=s.crossPanelEdit?.textBaselineGuides!==false?textBaselinesV26(s,geo):[],guides=normalizeUserGuidesV26(s.userGuides),key=JSON.stringify([geo.width,geo.height,baselines,guides]),previous=svg.querySelector('#boxstudio-v26-guide-overlay');if(previous?.dataset.renderKey===key)return;previous?.remove();const root=make('g',{id:'boxstudio-v26-guide-overlay',class:'ui-only'});root.dataset.renderKey=key;for(const b of baselines){root.appendChild(make('line',{x1:0,y1:b.value,x2:geo.width,y2:b.value,stroke:'#8b5cf6','stroke-width':.8,'stroke-dasharray':'2 5',opacity:.32,'vector-effect':'non-scaling-stroke','pointer-events':'none'}));}
  for(const g of normalizeUserGuidesV26(s.userGuides)){const line=g.axis==='x'?make('line',{x1:g.value,y1:0,x2:g.value,y2:geo.height}):make('line',{x1:0,y1:g.value,x2:geo.width,y2:g.value});for(const[k,v]of Object.entries({stroke:g.locked?'#6b7280':'#06b6d4','stroke-width':1.25,'stroke-dasharray':'7 4','vector-effect':'non-scaling-stroke','data-v26-guide-id':g.id,'data-v26-guide-axis':g.axis,'pointer-events':g.locked?'none':'stroke'}))line.setAttribute(k,String(v));root.appendChild(line);const t=make('text',{x:g.axis==='x'?g.value+4:8,y:g.axis==='x'?14:g.value-4,fill:g.locked?'#6b7280':'#0891b2','font-size':8.5,'font-weight':700,'pointer-events':'none'});t.textContent=`${g.label} · ${g.value.toFixed(1)} mm`;root.appendChild(t);}svg.appendChild(root);}
function install(){const svg=document.querySelector('#designSvg');if(!svg||svg.dataset.v26GuidesInstalled==='1'){render();return}svg.dataset.v26GuidesInstalled='1';let drag=null;svg.addEventListener('pointerdown',e=>{const line=e.target.closest?.('[data-v26-guide-id]');if(!line)return;e.stopPropagation();e.preventDefault();drag={id:line.dataset.v26GuideId,axis:line.dataset.v26GuideAxis};svg.setPointerCapture?.(e.pointerId);});svg.addEventListener('pointermove',e=>{if(!drag)return;e.stopPropagation();const p=svgPoint(svg,e),s=readState(),value=drag.axis==='x'?p.x:p.y;writeState(updateUserGuideV26(s,drag.id,{value}));render();});const end=e=>{if(!drag)return;e?.stopPropagation?.();drag=null;render();};svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);render();}
const observer=new MutationObserver(()=>install());observer.observe(document.documentElement,{childList:true,subtree:true});install();
