import {setUiVersion} from './uiVersion.js';
import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry } from './geometry.js';
import { getCrossSelection } from './crossPanelTransformV21.js';
import { crossClipNodes, ensureBezierClipState } from './clipPathV25.js';
import { clipNodeNumericV26, setClipNodeNumericV26, setClipSegmentTypeV26, clipSegmentDiagnosticsV26 } from './clipPathV26.js';
import { normalizeUserGuidesV26, addUserGuideV26, updateUserGuideV26, removeUserGuideV26, userGuideSnapV26, textBaselineSnapV26, smartRotationV26, smartGuideDiagnosticsV26 } from './smartGuidesV26.js';
import { loadRgbCmykDeviceLink, clearRgbCmykDeviceLink, getDeviceLinkInfo, convertRgbToCmyk } from './iccDeviceLinkV23.js';
import { currentDeviceLinkReference } from './productionPdfV24.js';
import { buildProductionPdfV26, productionPdfV26Diagnostics } from './productionPdfV26.js';
import { buildNativeCubicClipPdfV26, nativeCubicClipPdfDiagnosticsV26 } from './nativeCubicPdfV26.js';
import { productionOutputGateV24 } from './productionOutputV24.js';
import { activeProductionJob, recordProductionExport, upsertProductionJob } from './productionJobs.js';
import { canProductionAction, normalizeProductionRole } from './permissions.js';
import { downloadBytes } from './export.js';

const BLOCK_ID='boxstudio-v26-tools',clone=v=>structuredClone(v);
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function safe(v='boxstudio'){return String(v||'boxstudio').trim().replace(/[\\/:*?"<>|\s]+/g,'-').replace(/^-+|-+$/g,'')||'boxstudio';}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,crossPanelEdit:{...defaultState.crossPanelEdit,...(p.crossPanelEdit||{})},exportOptions:{...defaultState.exportOptions,...(p.exportOptions||{})},userGuides:normalizeUserGuidesV26(p.userGuides||[])}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}
function commit(s,{reload=true}={}){writeState(s);if(reload)location.reload();}
function role(s){return normalizeProductionRole(s.productionRole||'operator');}
function actor(s){return String(s.productionActor||'local-user').trim()||'local-user';}
function selectedCross(state){const id=getCrossSelection(state).at(-1);return(state.elements||[]).find(e=>e.id===id&&e.type==='cross-panel-artwork')||null;}
function selectedNodeIndex(state,el){const n=crossClipNodes(el).length,raw=Number(state.crossPanelEdit?.clipNodeIndex)||0;return n?Math.max(0,Math.min(n-1,raw)):0;}
function applyDelta(state,ids,dx,dy){const next=clone(state);for(const el of next.elements||[])if(ids.includes(el.id)&&el.type==='cross-panel-artwork'){el.x=Number(el.x||0)+Number(dx||0);el.y=Number(el.y||0)+Number(dy||0);}return next;}
function bindLoadedLink(){const ref=currentDeviceLinkReference();if(!ref)throw new Error('No verified DeviceLink is loaded.');const s=readState();s.exportOptions={...(s.exportOptions||{}),deviceLinkRef:ref};writeState(s);return s;}
function hexRgb(value){const m=String(value||'').trim().match(/^#?([0-9a-f]{6})$/i);if(!m)return null;const n=parseInt(m[1],16);return[(n>>16&255)/255,(n>>8&255)/255,(n&255)/255];}
function guideRows(guides){if(!guides.length)return'<div class="v26-note">No persistent user guides yet.</div>';return`<div class="v26-guide-list">${guides.map(g=>`<div class="v26-guide-row"><span>${g.axis==='x'?'Vertical':'Horizontal'}</span><input data-guide-value="${esc(g.id)}" type="number" step="0.5" value="${Number(g.value).toFixed(2)}"><button data-guide-remove="${esc(g.id)}" class="danger">Remove</button></div>`).join('')}</div>`;}
function render(block){const host=block.querySelector('#v26Workspace');if(!host)return;try{const s=readState(),geo=generateGeometry(s.structure),el=selectedCross(s),idx=el?selectedNodeIndex(s,el):0,node=el?clipNodeNumericV26(el,idx):null,seg=el?clipSegmentDiagnosticsV26(el):null,guides=normalizeUserGuidesV26(s.userGuides),guideDiag=smartGuideDiagnosticsV26(s,geo),edit={userGuideToleranceMm:3,textBaselineGuides:true,textBaselineToleranceMm:3,rotationGuides:true,rotationGuideToleranceDeg:3,...(s.crossPanelEdit||{})},icc=getDeviceLinkInfo(),prod=productionPdfV26Diagnostics(s),cubic=nativeCubicClipPdfDiagnosticsV26(s),job=activeProductionJob(s),gate=productionOutputGateV24(s,job),rr=role(s),canApproved=gate.ok&&canProductionAction(rr,'export-approved');host.innerHTML=`
<section><h4>Bezier Clip Numeric Inspector</h4>${el&&node?`<div class="v26-stats"><span>${esc(el.label||el.id)}</span><span>node ${idx+1}/${seg.nodeCount}</span><span>${seg.curveSegments} curve segment(s)</span><span>${seg.lineSegments} line segment(s)</span></div><div class="v26-grid"><label>Anchor X (0..1)<input id="v26NodeX" type="number" min="0" max="1" step="0.001" value="${node.x}"></label><label>Anchor Y (0..1)<input id="v26NodeY" type="number" min="0" max="1" step="0.001" value="${node.y}"></label><label>In Handle X<input id="v26InX" type="number" step="0.001" value="${node.inX}"></label><label>In Handle Y<input id="v26InY" type="number" step="0.001" value="${node.inY}"></label><label>Out Handle X<input id="v26OutX" type="number" step="0.001" value="${node.outX}"></label><label>Out Handle Y<input id="v26OutY" type="number" step="0.001" value="${node.outY}"></label><label>Outgoing Segment<select id="v26SegmentType"><option value="curve" ${node.segmentType==='curve'?'selected':''}>Curve</option><option value="line" ${node.segmentType==='line'?'selected':''}>Line</option></select></label><label class="check"><input id="v26Smooth" type="checkbox" ${node.smooth?'checked':''}> Mirrored smooth node</label></div><div class="v26-actions"><button id="v26ApplyNode" class="primary">Apply Node / Segment</button><button id="v26CreateClip">Convert / Create Bezier Clip</button></div><div class="v26-note">Numeric handles are normalized object-space offsets. The outgoing segment type applies from the selected node to the next node.</div>`:'<div class="v26-note">Select one Cross-panel artwork object. If it has no Bezier clip, use Convert / Create after selecting it in the canvas.</div>'}</section>
<section><h4>Persistent User Guides</h4><div class="v26-stats"><span>${guideDiag.userGuides} user guide(s)</span><span>${guideDiag.textBaselines} text baseline(s)</span><span>${guideDiag.rotationTargets} rotation target(s)</span></div><div class="v26-grid"><label>New guide axis<select id="v26GuideAxis"><option value="x">Vertical / X</option><option value="y">Horizontal / Y</option></select></label><label>Position mm<input id="v26GuideValue" type="number" step="0.5" value="0"></label></div><div class="v26-actions"><button id="v26AddGuide">Add Guide</button><button id="v26SnapUser" ${getCrossSelection(s).length?'':'disabled'}>Snap Selected to User Guide</button></div>${guideRows(guides)}<div class="v26-note">Cyan user guides persist with the project and can also be dragged directly on the Design canvas.</div></section>
<section><h4>Baseline & Rotation Assist</h4><div class="v26-grid"><label class="check"><input id="v26ShowBaselines" type="checkbox" ${edit.textBaselineGuides!==false?'checked':''}> Show text baselines</label><label>Baseline tolerance mm<input id="v26BaselineTol" type="number" min="0" step="0.5" value="${Number(edit.textBaselineToleranceMm)||3}"></label><label class="check"><input id="v26RotationGuides" type="checkbox" ${edit.rotationGuides!==false?'checked':''}> Rotation-axis assist</label><label>Rotation tolerance °<input id="v26RotationTol" type="number" min="0" step="0.5" value="${Number(edit.rotationGuideToleranceDeg)||3}"></label><label>User-guide tolerance mm<input id="v26UserTol" type="number" min="0" step="0.5" value="${Number(edit.userGuideToleranceMm)||3}"></label></div><div class="v26-actions"><button id="v26SaveAssist">Save Assist Settings</button><button id="v26SnapBaseline" ${getCrossSelection(s).length?'':'disabled'}>Snap Selected to Text Baseline</button><button id="v26SnapRotation" ${el?'':'disabled'}>Snap Selected Rotation</button></div><div class="v26-note">Baseline and rotation assist are deterministic manual snap actions in V0.26. Existing V0.25 live object/spacing guides remain active during drag.</div></section>
<section><h4>Native Cubic PDF Clip Proof</h4><div class="v26-stats"><span>${cubic.nativeClipObjects} native clip object(s)</span><span>${cubic.curvedClipObjects} curved clip object(s)</span><span>${esc(cubic.colorSpace)}</span></div><div class="v26-actions"><button id="v26CubicProof" class="primary">Export Native Cubic Clip Proof PDF</button></div><div class="v26-note">This proof emits actual PDF cubic <code>c</code> operators for Bezier object clips before <code>W n</code>. The main production serializer still uses deterministic flattened clip polygons in V0.26; native cubic production clipping is not claimed yet.</div></section>
<section><h4>ICC DeviceLink & Production</h4><p>V0.26 keeps the verified LUT8/LUT16 RGB→CMYK DeviceLink route. mAB/mBA and general source-profile → printer-profile CMM linking are still outside the verified subset.</p><div class="v26-file"><input id="v26IccFile" type="file" accept=".icc,.icm,application/vnd.iccprofile"><button id="v26ClearIcc">Unload Session</button>${icc?`<span class="v26-badge">${esc(icc.name)} · ${esc(icc.tagType)} · ${icc.precision}-bit · ${esc(icc.fingerprint)}</span>`:'<span class="v26-badge">No DeviceLink loaded</span>'}</div><div class="v26-grid"><label>RGB test color<input id="v26Rgb" type="text" value="#FF6600"></label><label>Converted CMYK<div id="v26Cmyk" class="v26-cmyk">${icc?'enter a color and test':'requires loaded DeviceLink'}</div></label></div><div class="v26-actions"><button id="v26TestColor" ${icc?'':'disabled'}>Test DeviceLink</button><button id="v26Pdf" class="primary">Export V0.26 Production PDF</button><button id="v26Approved" ${canApproved?'':'disabled'}>Export Approved V0.26 PDF</button></div><div class="v26-${gate.ok?'good':'warning'}">${esc(gate.reason)}</div><div class="v26-note">Production serializer: ${esc(prod.serializer)}. Main production clipping remains flattened; the separate cubic proof is for verifying native Bezier clipping behavior.</div></section>`;
  host.querySelector('#v26CreateClip')?.addEventListener('click',()=>{let n=ensureBezierClipState(readState(),el.id,{inset:.05});n.crossPanelEdit={...(n.crossPanelEdit||{}),clipNodeIndex:0};commit(n)});
  host.querySelector('#v26ApplyNode')?.addEventListener('click',()=>{let n=readState();n=setClipNodeNumericV26(n,el.id,idx,{x:Number(host.querySelector('#v26NodeX').value),y:Number(host.querySelector('#v26NodeY').value),inX:Number(host.querySelector('#v26InX').value),inY:Number(host.querySelector('#v26InY').value),outX:Number(host.querySelector('#v26OutX').value),outY:Number(host.querySelector('#v26OutY').value),smooth:host.querySelector('#v26Smooth').checked});n=setClipSegmentTypeV26(n,el.id,idx,host.querySelector('#v26SegmentType').value);commit(n)});
  host.querySelector('#v26AddGuide').onclick=()=>commit(addUserGuideV26(readState(),host.querySelector('#v26GuideAxis').value,Number(host.querySelector('#v26GuideValue').value),{label:'User guide'}));
  for(const input of host.querySelectorAll('[data-guide-value]'))input.onchange=()=>commit(updateUserGuideV26(readState(),input.dataset.guideValue,{value:Number(input.value)}));
  for(const button of host.querySelectorAll('[data-guide-remove]'))button.onclick=()=>commit(removeUserGuideV26(readState(),button.dataset.guideRemove));
  host.querySelector('#v26SnapUser').onclick=()=>{const n=readState(),ids=getCrossSelection(n),r=userGuideSnapV26(n,ids,0,0,{enabled:true,toleranceMm:Number(n.crossPanelEdit?.userGuideToleranceMm)||3});commit(applyDelta(n,ids,r.dx,r.dy));};
  host.querySelector('#v26SnapBaseline').onclick=()=>{const n=readState(),ids=getCrossSelection(n),r=textBaselineSnapV26(n,ids,0,0,generateGeometry(n.structure),{enabled:true,toleranceMm:Number(n.crossPanelEdit?.textBaselineToleranceMm)||3});commit(applyDelta(n,ids,r.dx,r.dy));};
  host.querySelector('#v26SnapRotation').onclick=()=>{const n=readState(),selected=selectedCross(n);if(!selected)return;const r=smartRotationV26(n,selected.id,Number(selected.r)||0,{enabled:true,toleranceDeg:Number(n.crossPanelEdit?.rotationGuideToleranceDeg)||3,step:Number(n.crossPanelEdit?.angleStep)||15});const target=n.elements.find(x=>x.id===selected.id);target.r=r.angle;commit(n);};
  host.querySelector('#v26SaveAssist').onclick=()=>{const n=readState();n.crossPanelEdit={...(n.crossPanelEdit||{}),textBaselineGuides:host.querySelector('#v26ShowBaselines').checked,textBaselineToleranceMm:Math.max(0,Number(host.querySelector('#v26BaselineTol').value)||3),rotationGuides:host.querySelector('#v26RotationGuides').checked,rotationGuideToleranceDeg:Math.max(0,Number(host.querySelector('#v26RotationTol').value)||3),userGuideToleranceMm:Math.max(0,Number(host.querySelector('#v26UserTol').value)||3)};commit(n);};
  host.querySelector('#v26CubicProof').onclick=()=>{try{const n=readState();downloadBytes(`${safe(n.variables?.sku||'boxstudio')}-v26-cubic-clip-proof.pdf`,buildNativeCubicClipPdfV26(n),'application/pdf')}catch(err){alert(err?.message||err)}};
  host.querySelector('#v26IccFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{loadRgbCmykDeviceLink(await file.arrayBuffer(),file.name);bindLoadedLink();render(block)}catch(err){alert(err?.message||err);e.target.value=''}};
  host.querySelector('#v26ClearIcc').onclick=()=>{clearRgbCmykDeviceLink();render(block)};
  host.querySelector('#v26TestColor').onclick=()=>{const rgb=hexRgb(host.querySelector('#v26Rgb').value);if(!rgb){alert('Use a 6-digit RGB hex color, for example #FF6600.');return}const c=convertRgbToCmyk(rgb);host.querySelector('#v26Cmyk').textContent=c?`C ${Math.round(c[0]*100)}% · M ${Math.round(c[1]*100)}% · Y ${Math.round(c[2]*100)}% · K ${Math.round(c[3]*100)}%`:'No DeviceLink loaded';};
  host.querySelector('#v26Pdf').onclick=()=>{try{const n=readState(),bytes=buildProductionPdfV26(n);downloadBytes(`${safe(n.variables?.sku||'boxstudio')}-v26-production.pdf`,bytes,'application/pdf')}catch(err){alert(err?.message||err)}};
  host.querySelector('#v26Approved').onclick=()=>{const n=readState(),active=activeProductionJob(n),g=productionOutputGateV24(n,active),r=role(n);if(!g.ok||!canProductionAction(r,'export-approved')){alert(g.ok?'Current role cannot export approved production files.':g.reason);return}try{const fileName=`${safe(n.variables?.sku||'production')}-approved-r${active.revision}-v26.pdf`,bytes=buildProductionPdfV26(n);downloadBytes(fileName,bytes,'application/pdf');const updated=recordProductionExport(active,{actor:actor(n),role:r,format:'pdf',fileName,serializer:'v0.26-native-production'});writeState(upsertProductionJob(n,updated));render(block)}catch(err){alert(err?.message||err)}};
}catch(error){host.innerHTML=`<div class="v26-warning">${esc(error?.message||error)}</div>`}}
function hideSuperseded(){document.getElementById('boxstudio-v25-tools')?.setAttribute('hidden','');}
function install(){hideSuperseded();const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v26-tools';block.innerHTML=`<div class="v26-title"><div><h3>V0.26 Precision Guides & Cubic Clip Proof</h3><p>Numeric Bezier nodes · persistent guides · baseline/rotation assist · native cubic PDF clip proof.</p></div><span>V0.26</span></div><div id="v26Workspace"></div>`;scroll.appendChild(block);render(block)}
function updateVersion(){setUiVersion('V0.26')}
const observer=new MutationObserver(()=>{updateVersion();hideSuperseded();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
