import { STORAGE_KEY, defaultState } from './model.js';
import { buildProductionPdfV27, productionPdfV27Diagnostics } from './productionPdfV27.js';
import { getDeviceLinkInfo } from './iccDeviceLinkV23.js';
import { collectWorkerAssetsV24, transferableWorkerAssetsV24, workerAssetAvailabilityV24, describeWorkerAssetsV24 } from './workerAssetsV24.js';
import { workerBatchEligibility } from './batchWorkerCore.js';
import { createIndexedDbArtifactStore, createMemoryArtifactStore } from './artifactStore.js';
import { preparePersistentQueue, queueWithClaim, queueWithComplete, queueWithFailure, pausePersistentQueue, finalizePersistentPause, resumePersistentQueue, cancelPersistentQueue, finalizePersistentCancel, persistentQueueProgress, persistentQueueState } from './persistentBatch.js';
import { retryFailedJobs } from './jobQueue.js';
import { attachBatchRunContextV27, batchRunCompatibilityV27, batchRunBaseStateV27 } from './batchRunV27.js';
import { activeProductionJob, recordProductionExport, upsertProductionJob } from './productionJobs.js';
import { productionOutputGateV24 } from './productionOutputV24.js';
import { canProductionAction, normalizeProductionRole } from './permissions.js';
import { liveAssistDiagnosticsV27 } from './liveAssistV27.js';
import { downloadBytes } from './export.js';

const BLOCK_ID='boxstudio-v27-tools',clone=v=>structuredClone(v),artifactStore=globalThis.indexedDB?createIndexedDbArtifactStore():createMemoryArtifactStore();
let runToken=0,activeWorker=null;
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function safe(v='boxstudio'){return String(v||'boxstudio').trim().replace(/[\\/:*?"<>|\s]+/g,'-').replace(/^-+|-+$/g,'')||'boxstudio';}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,batch:{...defaultState.batch,...(p.batch||{})},crossPanelEdit:{...defaultState.crossPanelEdit,...(p.crossPanelEdit||{})},exportOptions:{...defaultState.exportOptions,...(p.exportOptions||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}
function actor(s){return String(s.productionActor||'local-user').trim()||'local-user';}
function role(s){return normalizeProductionRole(s.productionRole||'operator');}
function yieldUi(){return new Promise(r=>setTimeout(r,0));}
function hideSuperseded(){document.getElementById('boxstudio-v24-tools')?.setAttribute('hidden','');}
function workerRequest(worker,data,transfer=[]){return new Promise((resolve,reject)=>{const requestId=`v27-${Date.now()}-${Math.random().toString(36).slice(2)}`,done=()=>{worker.removeEventListener('message',onMessage);worker.removeEventListener('error',onError)},onMessage=e=>{if(e.data?.requestId!==requestId)return;done();e.data?.ok===false?reject(new Error(e.data.error||'Worker failed')):resolve(e.data)},onError=e=>{done();reject(e.error||new Error(e.message||'Worker failed'))};worker.addEventListener('message',onMessage);worker.addEventListener('error',onError);worker.postMessage({...data,requestId},transfer)})}

function renderProduction(block){const host=block.querySelector('#v27Production');if(!host)return;try{const s=readState(),diag=productionPdfV27Diagnostics(s),assist=liveAssistDiagnosticsV27(s),icc=getDeviceLinkInfo(),job=activeProductionJob(s),gate=productionOutputGateV24(s,job),rr=role(s),canApproved=gate.ok&&canProductionAction(rr,'export-approved');host.innerHTML=`<div class="v27-stats"><span>${diag.nativeAppearanceObjects} native object(s)</span><span>${diag.nativeCubicClipObjects} native cubic clip(s)</span><span>${diag.axial} axial</span><span>${diag.radial} radial</span><span>${diag.softMasks} soft mask(s)</span><span>${esc(diag.colorSpace)}</span></div><div class="v27-actions"><button id="v27Pdf" class="primary">Export V0.27 Native Cubic Production PDF</button><button id="v27Approved" ${canApproved?'':'disabled'}>Export Approved V0.27 PDF</button></div><div class="v27-${gate.ok?'good':'warning'}">${esc(gate.reason)}</div><div class="v27-note">Native cubic clipping is now enabled inside the integrated Production serializer for Cross-panel Bezier object clips. Existing Panel/primitive clips, gradients, soft masks, spot dielines, barcode/QR, DeviceLink binding and approval checks remain in the same production document.</div><div class="v27-stats"><span>${assist.userGuides} user guide(s)</span><span>baseline ${assist.textBaselineEnabled?'live':'off'}</span><span>rotation ${assist.rotationEnabled?'live':'off'}</span><span>guide tol ${assist.userGuideToleranceMm} mm</span><span>baseline tol ${assist.baselineToleranceMm} mm</span><span>rotation tol ${assist.rotationToleranceDeg}°</span>${icc?`<span>${esc(icc.tagType)} ${icc.precision}-bit DeviceLink</span>`:''}</div><div class="v27-note">User Guides and Text Baselines now participate during move gestures. Rotation Grid/Object/Orthogonal matching participates during rotate gestures. Alt bypasses the live assist for the current gesture. The V0.26 precision inspector below remains available for creating guides and editing Bezier nodes numerically.</div>`;
  host.querySelector('#v27Pdf').onclick=()=>{try{const n=readState(),bytes=buildProductionPdfV27(n);downloadBytes(`${safe(n.variables?.sku||'boxstudio')}-v27-production-native-cubic.pdf`,bytes,'application/pdf')}catch(err){alert(err?.message||err)}};
  host.querySelector('#v27Approved').onclick=()=>{const n=readState(),active=activeProductionJob(n),g=productionOutputGateV24(n,active),r=role(n);if(!g.ok||!canProductionAction(r,'export-approved')){alert(g.ok?'Current role cannot export approved production files.':g.reason);return}try{const fileName=`${safe(n.variables?.sku||'production')}-approved-r${active.revision}-v27.pdf`,bytes=buildProductionPdfV27(n);downloadBytes(fileName,bytes,'application/pdf');const updated=recordProductionExport(active,{actor:actor(n),role:r,format:'pdf',fileName,serializer:'v0.27-native-cubic-production'});writeState(upsertProductionJob(n,updated));renderProduction(block)}catch(err){alert(err?.message||err)}};
}catch(error){host.innerHTML=`<div class="v27-warning">${esc(error?.message||error)}</div>`}}

async function batchSnapshot(){const s=readState(),q=s.batch?.queue,a=q?.id?await artifactStore.list(q.id):[];return{state:s,queue:q,artifacts:a};}
function batchText(p,q){return`${p.percent}% · ${p.completed} completed · ${p.failed} failed · ${p.pending} pending · ${p.artifactCount} persisted · ${Math.round((p.bytes||0)/1024)} KB${q?.status?` · ${q.status}`:''}`;}
async function renderBatch(block){const host=block.querySelector('#v27Batch');if(!host)return;const snap=await batchSnapshot(),q=snap.queue,arts=snap.artifacts,p=persistentQueueProgress(q||{items:[]},arts),assets=collectWorkerAssetsV24(),availability=workerAssetAvailabilityV24(assets),base=q?.kind==='worker-pdf-zip-v27'&&q?.context?.baseState?q.context.baseState:snap.state,eligibility=workerBatchEligibility(base,availability),compat=q?.kind==='worker-pdf-zip-v27'?batchRunCompatibilityV27(snap.state,q):{ok:true,reason:'New V0.27 run will capture the current rows.'},desc=describeWorkerAssetsV24(assets),usable=typeof Worker!=='undefined'&&eligibility.ok&&compat.ok;host.innerHTML=`<div class="v27-stats"><span>TTF ${esc(desc.ttf)}</span><span>Output ICC ${esc(desc.icc)}</span><span>DeviceLink ${esc(desc.deviceLink)}</span><span>serializer v0.27 native cubic</span></div><div class="v27-actions"><button id="v27BatchStart" class="primary" ${usable?'':'disabled'}>${q?.kind==='worker-pdf-zip-v27'?'Resume / Reconcile':'Start V0.27 Native Cubic Batch'}</button><button id="v27BatchRestart" ${typeof Worker!=='undefined'?'':'disabled'}>Restart with Current Project</button><button id="v27BatchPause" ${q&&!p.done?'':'disabled'}>Pause</button><button id="v27BatchCancel" ${q&&!p.done?'':'disabled'}>Cancel</button><button id="v27BatchRetry" ${q&&(p.failed||p.cancelled)?'':'disabled'}>Retry Failed / Cancelled</button><button id="v27BatchZip" ${p.artifactCount?'':'disabled'}>Recovered ZIP</button></div><div class="v27-progress"><i style="width:${p.percent}%"></i></div><div class="v27-mono">${esc(batchText(p,q))}</div>${!compat.ok?`<div class="v27-warning">${esc(compat.reason)}</div>`:''}${!eligibility.ok?`<div class="v27-warning">${eligibility.blockers.map(esc).join('<br>')}</div>`:''}<div class="v27-note">V0.27 freezes a base state with native cubic clipping enabled. Row changes block continuation instead of mixing configurations. Worker artifacts record serializer, color space, DeviceLink fingerprint and native cubic clip count.</div><div class="v27-artifacts">${arts.slice(-8).reverse().map(a=>`<div><span>${esc(a.fileName)}</span><small>${esc(a.serializer||'legacy')} · ${esc(a.colorSpace||'')} ${a.nativeCubicClipObjects!=null?`· cubic ${a.nativeCubicClipObjects}`:''}</small></div>`).join('')}</div>`;
  host.querySelector('#v27BatchStart').onclick=()=>runBatch(block,false);host.querySelector('#v27BatchRestart').onclick=()=>runBatch(block,true);host.querySelector('#v27BatchPause').onclick=()=>{const s=readState();if(s.batch?.queue){s.batch.queue=pausePersistentQueue(s.batch.queue);writeState(s);renderBatch(block)}};host.querySelector('#v27BatchCancel').onclick=()=>{const s=readState();if(s.batch?.queue){s.batch.queue=cancelPersistentQueue(s.batch.queue);writeState(s);renderBatch(block)}};host.querySelector('#v27BatchRetry').onclick=()=>{const s=readState();if(s.batch?.queue){s.batch.queue=retryFailedJobs(s.batch.queue);writeState(s);renderBatch(block)}};host.querySelector('#v27BatchZip').onclick=()=>exportBatchZip(block);
}
async function runBatch(block,restart=false){const my=++runToken;if(activeWorker){activeWorker.terminate();activeWorker=null}let s=readState();if(!s.batch?.rows?.length){alert('请先导入 Excel / CSV。');return}if(typeof Worker==='undefined'){alert('Worker API unavailable.');return}if(restart&&s.batch?.queue?.id)await artifactStore.clearQueue(s.batch.queue.id);let arts=s.batch?.queue?.id?await artifactStore.list(s.batch.queue.id):[],q=preparePersistentQueue(s,arts,{restart,kind:'worker-pdf-zip-v27'});q=attachBatchRunContextV27(q,s,{restart:restart||!q.context||q.kind!=='worker-pdf-zip-v27'});const compat=batchRunCompatibilityV27(s,q);if(!compat.ok){alert(compat.reason);return}const assets=collectWorkerAssetsV24(),availability=workerAssetAvailabilityV24(assets),eligibility=workerBatchEligibility(batchRunBaseStateV27(q),availability);if(!eligibility.ok){alert(eligibility.blockers.join('\n'));return}if(q.status==='paused')q=resumePersistentQueue(q);writeState(persistentQueueState(s,q));await renderBatch(block);const worker=new Worker(new URL('./batchPdf.worker.js',import.meta.url),{type:'module'});activeWorker=worker;try{const tx=transferableWorkerAssetsV24(assets);await workerRequest(worker,{type:'init-assets',workerAssets:tx.payload},tx.transfer);while(my===runToken){s=readState();q=s.batch.queue;arts=await artifactStore.list(q.id);q=preparePersistentQueue(s,arts,{kind:'worker-pdf-zip-v27'});const liveCompat=batchRunCompatibilityV27(s,q);if(!liveCompat.ok){q.status='blocked-input-changed';q.updatedAt=new Date().toISOString();writeState(persistentQueueState(s,q));break}if(q.cancelRequested){q=finalizePersistentCancel(q);writeState(persistentQueueState(s,q));break}if(q.pauseRequested){q=finalizePersistentPause(q);writeState(persistentQueueState(s,q));break}const claim=queueWithClaim(q);q=claim.queue;writeState(persistentQueueState(s,q));if(!claim.item)break;const index=claim.item.index,row=s.batch.rows[index],baseState=batchRunBaseStateV27(q);try{const result=await workerRequest(worker,{pipeline:'v27-native-cubic',baseState,row,index});await artifactStore.put({queueId:q.id,index,fileName:result.fileName,mime:'application/pdf',bytes:result.bytes,fingerprint:result.fingerprint,serializer:result.serializer,colorSpace:result.colorSpace,deviceLinkFingerprint:result.deviceLinkFingerprint,nativeCubicClipObjects:result.nativeCubicClipObjects});q=queueWithComplete(q,index,result.fileName)}catch(error){q=queueWithFailure(q,index,error?.message||String(error))}s=readState();writeState(persistentQueueState(s,q));await renderBatch(block);await yieldUi()}}finally{worker.terminate();if(activeWorker===worker)activeWorker=null;await renderBatch(block)}}
async function exportBatchZip(block){const {queue,artifacts}=await batchSnapshot();if(!queue||!artifacts.length)return;if(!globalThis.JSZip){alert('JSZip 未加载。');return}const zip=new globalThis.JSZip();for(const a of artifacts)zip.file(a.fileName,a.bytes);zip.file('boxstudio-v27-artifacts.json',JSON.stringify({queueId:queue.id,status:queue.status,serializer:queue.context?.serializer||'',rowsFingerprint:queue.context?.rowsFingerprint||'',nativeCubicClip:true,deviceLinkRef:queue.context?.deviceLinkRef||null,files:artifacts.map(a=>({index:a.index,fileName:a.fileName,byteLength:a.byteLength,fingerprint:a.fingerprint,serializer:a.serializer,colorSpace:a.colorSpace,deviceLinkFingerprint:a.deviceLinkFingerprint,nativeCubicClipObjects:a.nativeCubicClipObjects}))},null,2));const bytes=await zip.generateAsync({type:'uint8array',compression:'DEFLATE',compressionOptions:{level:6}});downloadBytes(`boxstudio-${safe(queue.id)}-v27-native-cubic.zip`,bytes,'application/zip');await renderBatch(block)}

function render(block){renderProduction(block);renderBatch(block)}
function install(){hideSuperseded();const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v27-tools';block.innerHTML=`<div class="v27-title"><div><h3>V0.27 Native Cubic Production & Live Assist</h3><p>Native cubic clip in Production/Approved PDF · Worker Batch · live User Guide/Baseline/Rotation gestures.</p></div><span>V0.27</span></div><section><h4>Production & Live Assist</h4><div id="v27Production"></div></section><section><h4>Recoverable Native Cubic Batch</h4><div id="v27Batch"></div></section>`;scroll.prepend(block);render(block)}
function updateVersion(){const v=document.querySelector('.brand small');if(v)v.textContent='V0.27';document.title='BoxStudio V0.27'}
const observer=new MutationObserver(()=>{updateVersion();hideSuperseded();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
