import { STORAGE_KEY, defaultState } from './model.js';
import { getCrossSelection } from './crossPanelTransformV21.js';
import { groupRotationDiagnosticsV28 } from './liveAssistV28.js';

const BLOCK_ID='boxstudio-v28-tools',clone=v=>structuredClone(v);
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,crossPanelEdit:{...defaultState.crossPanelEdit,...(p.crossPanelEdit||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function render(block){const host=block.querySelector('#v28Workspace');if(!host)return;const state=readState(),ids=getCrossSelection(state),diag=groupRotationDiagnosticsV28(state,ids);host.innerHTML=`<section><h4>Group Rotation Live Assist</h4><div class="v28-stats"><span>${diag.selectionCount} selected</span><span>${diag.targetCount} external target(s)</span><span>${diag.objectRelativeAvailable?'object-relative ready':'grid fallback'}</span></div><p>V0.28 intercepts the shared rotation handle before the V0.27 grid-only path. A selected group can now match an unselected Cross-panel object angle or its +90° / +180° / +270° axes while rotating. <code>Alt</code> bypasses the assist.</p></section><section><h4>Initial Baseline Gap Audit</h4><p>The repository now keeps a canonical comparison against the original 2026-09-30 V1/V2/V3 development documents. It distinguishes implemented, partial, unfinished and deliberately deferred requirements instead of treating every prototype capability as production-complete.</p><div class="v28-actions"><a href="./docs/UNFINISHED_BASELINE_AUDIT.md" target="_blank" rel="noopener">Open unfinished baseline audit</a></div><div class="v28-note">High-priority unfinished groups: hosted Auth/RBAC, Master Data, formal Template Publish workflow, Digital Barcode/QR decode verification, Compare/Impact Analysis, enterprise API/SSO, immutable server audit, certified PDF/X/preflight, full ICC CMM, browser E2E and physical production validation.</div></section>`;}
function install(){const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll||document.getElementById(BLOCK_ID))return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v28-tools';block.innerHTML=`<div class="v28-title"><div><h3>V0.28 Baseline Closure</h3><p>Object-relative Group Rotation · original-plan gap audit.</p></div><span>V0.28</span></div><div id="v28Workspace"></div>`;scroll.prepend(block);render(block);}
function updateVersion(){const v=document.querySelector('.brand small');if(v)v.textContent='V0.28';document.title='BoxStudio V0.28';}
const observer=new MutationObserver(()=>{updateVersion();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
