import { STORAGE_KEY, defaultState } from './model.js';
import { batchImportReviewV29, failedRowsCsvV29, batchDiagnosticsJsonV29 } from './batchReviewV29.js';

const BLOCK_ID='boxstudio-v29-import-review',clone=v=>structuredClone(v);
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,batch:{...defaultState.batch,...(p.batch||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function downloadText(name,text,type='text/plain;charset=utf-8'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);}
function render(block){const host=block.querySelector('#v29Review');if(!host)return;const state=readState(),review=batchImportReviewV29(state),d=review.diagnostics,f=review.formulaWarnings||[],p=review.preflight||{total:0,passed:0,failed:0,warnings:0};host.innerHTML=`<section><h4>Import Detection</h4><div class="v29-stats"><span>Header row ${d.headerRow||'—'}</span><span>${d.recognizedHeaders||0} recognized</span><span>${d.mergedRanges||0} merged range(s)</span><span>${d.fillDownCells||0} fill-down cell(s)</span><span>${d.footerDetected?`Footer row ${d.footerRow}`:'No footer found'}</span></div><p>${review.fileName?`${esc(review.fileName)} · ${esc(review.sheetName||'Sheet')}`:'导入 XLSX / CSV / TSV 后，这里显示 V0.29 自动 Header Detection、Merged Fill-down、Footer Stop 与公式缓存诊断。'}</p>${d.headerFallback?'<div class="v29-warning">Header 只使用 fallback 行；建议检查文件表头。</div>':''}${f.length?`<div class="v29-warning">${f.length} 个公式单元格没有缓存值：${f.slice(0,6).map(x=>esc(x.cell)).join(' · ')}${f.length>6?' …':''}</div>`:''}</section><section><h4>Batch Review</h4><div class="v29-stats"><span>${p.passed||0}/${p.total||0} passed</span><span>${p.failed||0} failed</span><span>${p.warnings||0} warnings</span></div><div class="v29-actions"><button type="button" id="v29FailedCsv" ${p.failed?'':'disabled'}>Download failed_rows.csv</button><button type="button" id="v29DiagJson" ${review.fileName?'':'disabled'}>Download import diagnostics</button><a href="./docs/BASELINE_PROGRESS_V0.29.md" target="_blank" rel="noopener">V0.29 baseline progress</a></div><div class="v29-note"><code>failed_rows.csv</code> includes original source row, preflight errors and canonical cell-lineage JSON. It is not yet the V3.0 requested <code>failed_rows.xlsx</code> workflow.</div></section>`;const failed=host.querySelector('#v29FailedCsv');if(failed)failed.onclick=()=>{const csv=failedRowsCsvV29(readState());if(csv)downloadText('failed_rows.csv','\uFEFF'+csv,'text/csv;charset=utf-8')};const diag=host.querySelector('#v29DiagJson');if(diag)diag.onclick=()=>downloadText('boxstudio-import-diagnostics.json',batchDiagnosticsJsonV29(readState()),'application/json;charset=utf-8');}
function install(){if(document.getElementById(BLOCK_ID))return;const section=[...document.querySelectorAll('.panel-section')].find(el=>el.querySelector('h3')?.textContent?.trim()==='Batch Marks');if(!section)return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='v29-import-review';block.innerHTML=`<div class="v29-title"><div><b>Resilient Import Review</b><small>Header · Merge · Fill-down · Footer · Lineage</small></div><span>V0.29</span></div><div id="v29Review"></div>`;section.appendChild(block);render(block);}
function updateVersion(){const v=document.querySelector('.brand small');if(v)v.textContent='V0.29';document.title='BoxStudio V0.29';}
const observer=new MutationObserver(()=>{updateVersion();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
