import {setUiVersion} from './uiVersion.js';
import { STORAGE_KEY, defaultState } from './model.js';
import { runProductionAcceptanceV31 } from './preflightV31.js';
import { activeProductionJob, recordProductionExport, upsertProductionJob } from './productionJobs.js';
import { productionOutputGateV24 } from './productionOutputV24.js';
import { canProductionAction, normalizeProductionRole } from './permissions.js';
import { downloadBytes } from './export.js';

const BLOCK_ID='boxstudio-v31-acceptance',clone=v=>structuredClone(v);let last=null,lastFingerprint='';
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,exportOptions:{...defaultState.exportOptions,...(p.exportOptions||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s));}
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function safe(v='boxstudio'){return String(v||'boxstudio').trim().replace(/[\\/:*?"<>|\s]+/g,'-').replace(/^-+|-+$/g,'')||'boxstudio';}
function fingerprint(s){return JSON.stringify([s.variables,s.elements,s.structure,s.exportOptions]);}
function actor(s){return String(s.productionActor||'local-user').trim()||'local-user';}
function role(s){return normalizeProductionRole(s.productionRole||'operator');}
function acceptanceFor(s){const fp=fingerprint(s);if(last&&lastFingerprint===fp)return last;last=runProductionAcceptanceV31(s,{toleranceMm:Number(s.exportOptions?.geometryToleranceMm)||.2});lastFingerprint=fp;return last;}
function detail(a){const b=a.digital.barcode,q=a.digital.qr,g=a.geometry;return `<div class="v31-status ${a.digital.ok?'good':'bad'}"><b>Digital Decode ${a.digital.ok?'PASS':'FAIL'}</b><span>${esc(b.type)} · barcode ${b.ok?'PASS':'FAIL'} · QR ${q.ok?'PASS':'FAIL'}</span><small>${esc(a.digital.note)}</small></div><div class="v31-status ${g.ok?'good':'bad'}"><b>Geometry ${g.ok?'PASS':'FAIL'}</b><span>${g.probeCount} probes · max ${Number.isFinite(g.maxErrorMm)?g.maxErrorMm.toFixed(4):'∞'} mm · limit ${g.toleranceMm.toFixed(3)} mm</span><small>${esc(g.note)}</small></div>`;}
function render(block){const host=block.querySelector('#v31Workspace');if(!host)return;const s=readState(),job=activeProductionJob(s),gate=productionOutputGateV24(s,job),rr=role(s),fresh=last&&lastFingerprint===fingerprint(s),a=fresh?last:null,ok=Boolean(a?.ok),approved=ok&&gate.ok&&canProductionAction(rr,'export-approved');host.innerHTML=`<section><h4>Required Production Checks</h4><p>V0.31 reads the generated V0.27 Production PDF artifact. Barcode/QR vector primitives are rasterized in memory and decoded; Preview mm coordinates are independently compared with coordinates parsed back from the PDF.</p><div class="v31-actions"><button id="v31Run" class="primary">Run Required Checks</button><button id="v31Checked" ${ok?'':'disabled'}>Export Checked PDF</button><button id="v31Approved" ${approved?'':'disabled'}>Export Approved Checked PDF</button></div>${a?detail(a):'<div class="v31-note">No current acceptance result. Run the required checks after each artwork, data or export-setting change.</div>'}<div class="v31-${gate.ok?'good':'warning'}">${esc(gate.reason)}</div></section><section><h4>Boundary</h4><div class="v31-note">Digital Decode here is a generated-PDF artifact check. It is not physical scanner ISO grading. Geometry acceptance verifies page, dieline and core mark key points at ≤ ${Number(s.exportOptions?.geometryToleranceMm||.2).toFixed(3)} mm; external RIP / real-sample acceptance remains separate.</div></section>`;
  host.querySelector('#v31Run')?.addEventListener('click',()=>{try{last=null;acceptanceFor(readState());render(block)}catch(err){last=null;alert(err?.message||err);render(block)}});
  host.querySelector('#v31Checked')?.addEventListener('click',()=>{try{const n=readState(),x=acceptanceFor(n);if(!x.ok)throw new Error('V0.31 required checks failed.');downloadBytes(`${safe(n.variables?.sku||'boxstudio')}-v31-checked.pdf`,x.pdf,'application/pdf')}catch(err){alert(err?.message||err)}});
  host.querySelector('#v31Approved')?.addEventListener('click',()=>{try{const n=readState(),x=acceptanceFor(n),active=activeProductionJob(n),g=productionOutputGateV24(n,active),r=role(n);if(!x.ok)throw new Error('V0.31 required checks failed.');if(!g.ok||!canProductionAction(r,'export-approved'))throw new Error(g.ok?'Current role cannot export approved production files.':g.reason);const fileName=`${safe(n.variables?.sku||'production')}-approved-r${active.revision}-v31-checked.pdf`;downloadBytes(fileName,x.pdf,'application/pdf');const updated=recordProductionExport(active,{actor:actor(n),role:r,format:'pdf',fileName,serializer:'v0.27-native-cubic-production',note:'V0.31 digital decode + geometry acceptance passed'});writeState(upsertProductionJob(n,updated));render(block)}catch(err){alert(err?.message||err)}});
}
function install(){if(document.getElementById(BLOCK_ID))return;const scroll=document.querySelector('#boxstudio-profile-manager .profile-manager-scroll');if(!scroll)return;const block=document.createElement('div');block.id=BLOCK_ID;block.className='profile-section v31-tools';block.innerHTML=`<div class="v31-title"><div><h3>V0.31 Production Acceptance</h3><p>PDF artifact digital decode · Preview/PDF geometry acceptance.</p></div><span>V0.31</span></div><div id="v31Workspace"></div>`;scroll.prepend(block);render(block);}
function updateVersion(){setUiVersion('V0.31')}
const observer=new MutationObserver(()=>{updateVersion();install()});observer.observe(document.documentElement,{childList:true,subtree:true});updateVersion();install();
