import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry, resolveElementRect, clampElementToPanel } from './geometry.js';
import { renderTemplate, isPackageNoticeVisible } from './variables.js';
import { barcodeLayout } from './barcode.js';
import { qrMatrix } from './qrcode.js';
import { parseSvgMark, createSvgMarkElement } from './svgMark.js';
import {
  ensureEditorV33, selectionIdsV33, selectedElementsV33, setSelectionV33, selectElementV33, selectAllLayerV33,
  groupSelectionV33, ungroupSelectionV33, copySelectionV33, pasteClipboardV33, duplicateSelectionV33, deleteSelectionV33,
  moveSelectionZV33, alignSelectionV33, distributeSelectionV33, translateSelectionV33, updatePrimaryElementV33,
  setSelectionFlagV33, setLayerStateV33, elementVisibleV33, elementLockedV33, insertTableV33, panelFocusV33, fitAllV33
} from './editorCoreV33.js';

const VERSION='V0.33',NS='http://www.w3.org/2000/svg',clone=v=>structuredClone(v),num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
let session=null,history=[],historyIndex=-1,clipboard=null,host=null,drag=null,scheduled=false;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return ensureEditorV33(p?{...clone(defaultState),...p}:clone(defaultState))}catch{return ensureEditorV33(clone(defaultState))}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function commit(next,{render=true}={}){session=ensureEditorV33(next);history=history.slice(0,historyIndex+1);history.push(clone(session));historyIndex=history.length-1;writeState(session);if(render)renderWorkspace()}
function draft(next){session=ensureEditorV33(next);writeState(session);renderWorkspace()}
function undo(){if(historyIndex<=0)return;historyIndex--;session=clone(history[historyIndex]);writeState(session);renderWorkspace()}
function redo(){if(historyIndex>=history.length-1)return;historyIndex++;session=clone(history[++historyIndex]);writeState(session);renderWorkspace()}
function panelList(g){return (g.bodyPanels||[]).filter(p=>p.kind==='panel')}
function layerOf(el){return el?.group==='artwork'?'artwork':'marks'}
function currentViewBox(g){if(session.editorV33.fitMode==='panel'&&session.editorV33.focusPanelId){const p=g.panelMap[session.editorV33.focusPanelId];if(p){const pad=Math.max(8,Math.min(40,Math.min(p.w,p.h)*.12));return`${p.x-pad} ${p.y-pad} ${p.w+pad*2} ${p.h+pad*2}`}}return`0 0 ${g.width} ${g.height}`}
function line(l,cls){return`<line x1="${l.x1}" y1="${l.y1}" x2="${l.x2}" y2="${l.y2}" class="${cls}"/>`}
function dielineMarkup(g){if(session.editorV33.layers.dieline.visible===false)return'';return`<g class="v33-dieline">${(g.cutLines||[]).map(l=>line(l,'cut')).join('')}${(g.creaseLines||[]).map(l=>line(l,'crease')).join('')}${(g.perfLines||[]).map(l=>line(l,'perf')).join('')}${(g.glueLines||[]).map(l=>line(l,'glue')).join('')}${panelList(g).map(p=>`<text x="${p.x+p.w/2}" y="${p.y+p.h/2}" class="panel-label">${esc(p.label||p.id)}</text>`).join('')}</g>`}
function textMarkup(el,rr){const text=renderTemplate(el.template||'',session.variables||{}),lines=String(text).split('\n'),fs=Math.max(3,num(el.fontSize,7));return`<g class="v33-object-content"><rect width="${el.w}" height="${el.h}" fill="transparent"/>${lines.map((t,i)=>`<text x="0" y="${fs*(i+1)}" font-size="${fs}" font-weight="${el.bold?700:500}">${esc(t)}</text>`).join('')}</g>`}
function iconMarkup(el){const glyph=el.icon==='up'?'↑↑':el.icon==='fragile'?'♢':'☂';return`<g class="v33-object-content"><rect width="${el.w}" height="${el.h}" fill="none" stroke="currentColor"/><text x="${el.w/2}" y="${el.h*.66}" text-anchor="middle" font-size="${Math.min(el.w,el.h)*.5}">${glyph}</text></g>`}
function barcodeMarkup(el){const pad=Math.max(2,el.h*.06),qrSide=Math.max(10,Math.min(el.h-pad*2,el.w*.3)),gap=Math.max(2,el.w*.025),bw=Math.max(12,el.w-pad*2-gap-qrSide),bh=Math.max(8,el.h-pad*2-5),value=renderTemplate(el.barcodeValue||'{{sku}}',session.variables||{});let bars;try{bars=barcodeLayout(el.barcodeType||'CODE39',value,bw,bh)}catch{bars={bars:[]}}const q=qrMatrix(renderTemplate(el.qrValue||'{{qrValue}}',session.variables||{})),quiet=4,cell=qrSide/(q.size+quiet*2),qx=el.w-pad-qrSide;return`<g class="v33-object-content"><rect width="${el.w}" height="${el.h}" fill="#fff" stroke="currentColor"/>${bars.bars.map(b=>`<rect x="${pad+b.x}" y="${pad+b.y}" width="${b.w}" height="${b.h}"/>`).join('')}${q.matrix.map((row,r)=>row.map((on,c)=>on?`<rect x="${qx+(quiet+c)*cell}" y="${pad+(quiet+r)*cell}" width="${cell+.02}" height="${cell+.02}"/>`:'').join('')).join('')}</g>`}
function svgSymbolMarkup(el){const m=el.svgMark;if(!m?.lines?.length)return`<rect width="${el.w}" height="${el.h}" fill="none" stroke="currentColor"/>`;const sx=el.w/Math.max(.001,m.width),sy=el.h/Math.max(.001,m.height);return`<g class="v33-object-content" fill="none" stroke="currentColor" stroke-width="${Math.max(.6,Math.min(el.w,el.h)/90)}">${m.lines.map(l=>`<line x1="${l.x1*sx}" y1="${l.y1*sy}" x2="${l.x2*sx}" y2="${l.y2*sy}"/>`).join('')}</g>`}
function objectContent(el,rr){if(el.type==='text'||el.type==='notice')return textMarkup(el,rr);if(el.type==='shape')return`<rect width="${el.w}" height="${el.h}" fill="${el.fill||'none'}" stroke="currentColor"/>`;if(el.type==='line')return`<line x1="0" y1="0" x2="${el.w}" y2="${el.h}" stroke="currentColor" stroke-width="1.5"/>`;if(el.type==='icon')return iconMarkup(el);if(el.type==='barcode-qr-group')return barcodeMarkup(el);if(el.type==='svg-symbol')return svgSymbolMarkup(el);if(el.type==='cross-panel-artwork')return`<rect width="${el.w}" height="${el.h}" fill="rgba(91,75,215,.06)" stroke="#5b4bd7" stroke-dasharray="7 4"/><text x="5" y="14" font-size="9">CROSS · ${esc(el.label||el.id)}</text>`;return`<rect width="${el.w}" height="${el.h}" fill="none" stroke="#777" stroke-dasharray="4 3"/>`}
function elementMarkup(el,g,selected,primary){if(!elementVisibleV33(session,el))return'';if(el.type==='notice'&&!isPackageNoticeVisible(session.variables||{}))return'';const rr=el.type==='cross-panel-artwork'?{absX:num(el.x),absY:num(el.y)}:resolveElementRect(el,g),locked=elementLockedV33(session,el),rot=num(el.r),cls=`v33-element ${selected?'selected':''} ${locked?'locked':''}`;return`<g data-v33-element="${esc(el.id)}" class="${cls}" transform="translate(${rr.absX} ${rr.absY}) rotate(${rot} ${num(el.w)/2} ${num(el.h)/2})">${objectContent(el,rr)}<rect class="v33-hit" width="${Math.max(1,num(el.w))}" height="${Math.max(1,num(el.h))}"/>${selected?`<rect class="v33-select" x="-3" y="-3" width="${num(el.w)+6}" height="${num(el.h)+6}"/>`:''}${primary&&!locked?`<rect data-v33-handle="resize" class="v33-handle" x="${num(el.w)-4}" y="${num(el.h)-4}" width="8" height="8"/><line class="v33-rotate-line" x1="${num(el.w)/2}" y1="-3" x2="${num(el.w)/2}" y2="-18"/><circle data-v33-handle="rotate" class="v33-rotate" cx="${num(el.w)/2}" cy="-20" r="5"/>`:''}</g>`}
function canvasMarkup(g){const ids=new Set(selectionIdsV33(session)),primary=session.selectedId;return`<svg id="v33Canvas" viewBox="${currentViewBox(g)}" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" fill="#fff"/>${dielineMarkup(g)}${(session.elements||[]).map(el=>elementMarkup(el,g,ids.has(el.id),el.id===primary)).join('')}</svg>`}
function layerRows(){const layers=session.editorV33.layers;return['artwork','marks','dieline'].map(k=>`<div class="v33-layer-row"><button data-layer-visible="${k}" class="iconbtn">${layers[k].visible!==false?'◉':'○'}</button><button data-layer-lock="${k}" class="iconbtn">${layers[k].locked?'🔒':'🔓'}</button><b>${k[0].toUpperCase()+k.slice(1)}</b><span>${k==='dieline'?'CUT / CREASE / PERF':(session.elements||[]).filter(e=>layerOf(e)===k).length+' objects'}</span>${k!=='dieline'?`<button data-select-layer="${k}" class="mini">Select</button>`:''}</div>`).join('')}
function objectRows(){const ids=new Set(selectionIdsV33(session));return[...(session.elements||[])].reverse().slice(0,80).map(el=>`<div class="v33-object-row ${ids.has(el.id)?'selected':''}" data-object-row="${esc(el.id)}"><button data-el-visible="${esc(el.id)}" class="iconbtn">${el.hidden?'○':'◉'}</button><button data-el-lock="${esc(el.id)}" class="iconbtn">${el.locked?'🔒':'🔓'}</button><span>${esc(el.type)}</span><b>${esc(el.label||el.id)}</b>${el.groupId?'<em>G</em>':''}</div>`).join('')}
function inspector(g){const selected=selectedElementsV33(session),el=(session.elements||[]).find(x=>x.id===session.selectedId)||selected.at(-1),panels=panelList(g);if(!el)return`<div class="v33-empty-inspector">Select an object to edit exact geometry.</div>`;return`<div class="v33-inspector-title"><b>${esc(el.label||el.id)}</b><span>${selected.length} selected</span></div><div class="v33-grid5">${['x','y','w','h','r'].map(k=>`<label><span>${k==='r'?'R°':k.toUpperCase()}</span><input data-v33-prop="${k}" type="number" step="0.1" value="${num(el[k])}"></label>`).join('')}</div><label class="v33-field"><span>Panel</span><select data-v33-prop="panelId">${panels.map(p=>`<option value="${esc(p.id)}" ${p.id===el.panelId?'selected':''}>${esc(p.label||p.id)}</option>`).join('')}</select></label><div class="v33-inline"><button data-action="lock">${el.locked?'Unlock':'Lock'}</button><button data-action="hide">${el.hidden?'Show':'Hide'}</button><button data-action="delete" class="danger">Delete</button></div>`}
function toolbar(){return`<div class="v33-toolbar"><div class="v33-brand"><b>BOXSTUDIO</b><span>Professional 2D · ${VERSION}</span></div><div class="v33-toolbar-group"><button data-action="undo" title="Ctrl+Z">↶</button><button data-action="redo" title="Ctrl+Y">↷</button></div><div class="v33-toolbar-group"><button data-action="copy">Copy</button><button data-action="paste">Paste</button><button data-action="duplicate">Duplicate</button><button data-action="group">Group</button><button data-action="ungroup">Ungroup</button></div><div class="v33-toolbar-group"><button data-action="back">To Back</button><button data-action="backward">−1</button><button data-action="forward">+1</button><button data-action="front">To Front</button></div><div class="v33-toolbar-spacer"></div><button data-action="save-close" class="primary">Save & Exit</button></div>`}
function leftTools(){return`<aside class="v33-tools"><button data-tool="select" class="active">↖<span>Select</span></button><button data-action="add-text">T<span>Text</span></button><button data-action="import-svg">▧<span>Image SVG</span></button><button data-action="add-shape">□<span>Shape</span></button><button data-action="add-line">╱<span>Line</span></button><button data-action="add-icon">⇧<span>Icon</span></button><button data-action="add-table">▦<span>Table</span></button><input id="v33SvgFile" type="file" accept="image/svg+xml,.svg" hidden></aside>`}
function rightPanel(g){return`<aside class="v33-right"><section><h3>Transform</h3>${inspector(g)}</section><section><div class="v33-section-head"><h3>Align</h3><span>multi-select</span></div><div class="v33-align"><button data-align="left">L</button><button data-align="center">C</button><button data-align="right">R</button><button data-align="top">T</button><button data-align="middle">M</button><button data-align="bottom">B</button><button data-distribute="horizontal">↔</button><button data-distribute="vertical">↕</button></div></section><section><h3>Layers</h3>${layerRows()}</section><section class="v33-objects"><div class="v33-section-head"><h3>Objects</h3><span>${session.elements?.length||0}</span></div>${objectRows()}</section></aside>`}
function panelBar(g){const panels=panelList(g);return`<div class="v33-panelbar"><span>Panel Focus</span><select id="v33PanelFocus"><option value="">Choose panel…</option>${panels.map(p=>`<option value="${esc(p.id)}" ${p.id===session.editorV33.focusPanelId?'selected':''}>${esc(p.label||p.id)}</option>`).join('')}</select><button data-action="focus-panel">Focus</button><button data-action="fit-all">Fit All</button><span class="v33-status">${selectionIdsV33(session).length} selected · ${(g.width).toFixed(1)} × ${(g.height).toFixed(1)} mm</span></div>`}
function renderWorkspace(){if(!host||!session)return;const g=generateGeometry(session.structure);host.innerHTML=`${toolbar()}<div class="v33-body">${leftTools()}<main class="v33-stage"><div class="v33-canvas-wrap">${canvasMarkup(g)}</div>${panelBar(g)}</main>${rightPanel(g)}</div>`;bindWorkspace(g)}
function svgPoint(svg,e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const m=svg.getScreenCTM();return m?p.matrixTransform(m.inverse()):{x:0,y:0}}
function applyTempTransform(dx,dy){for(const id of drag.ids||[]){const node=host.querySelector(`[data-v33-element="${CSS.escape(id)}"]`);if(!node)continue;const base=node.dataset.baseTransform||node.getAttribute('transform')||'';node.dataset.baseTransform=base;node.setAttribute('transform',`translate(${dx} ${dy}) ${base}`)}}
function startDrag(svg,e){const handle=e.target.closest?.('[data-v33-handle]'),node=e.target.closest?.('[data-v33-element]');if(!node)return;const id=node.dataset.v33Element,clicked=(session.elements||[]).find(x=>x.id===id);if(!clicked)return;e.preventDefault();e.stopPropagation();if(handle){if(elementLockedV33(session,clicked))return;session=selectElementV33(session,id,{additive:false,groupAware:false});writeState(session);const rr=resolveElementRect(clicked,generateGeometry(session.structure)),p=svgPoint(svg,e),center={x:rr.absX+clicked.w/2,y:rr.absY+clicked.h/2};drag={mode:handle.dataset.v33Handle,id,base:clone(session),start:p,center,startAngle:Math.atan2(p.y-center.y,p.x-center.x)*180/Math.PI,orig:clone(clicked)};bindWindowDrag(svg);return}
  session=selectElementV33(session,id,{additive:e.shiftKey,groupAware:!e.altKey});writeState(session);renderWorkspace();const selected=(session.elements||[]).find(x=>x.id===id);if(elementLockedV33(session,selected))return;const p=svgPoint(host.querySelector('#v33Canvas'),e);drag={mode:'move',ids:selectionIdsV33(session),base:clone(session),start:p,last:p};bindWindowDrag(host.querySelector('#v33Canvas'))}
function bindWindowDrag(svg){const move=e=>{if(!drag)return;const p=svgPoint(svg,e);drag.last=p;if(drag.mode==='move')applyTempTransform(p.x-drag.start.x,p.y-drag.start.y);else if(drag.mode==='resize'){const node=host.querySelector(`[data-v33-element="${CSS.escape(drag.id)}"] .v33-select`);if(node){node.setAttribute('width',Math.max(4,drag.orig.w+p.x-drag.start.x)+6);node.setAttribute('height',Math.max(4,drag.orig.h+p.y-drag.start.y)+6)}}};const up=e=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);if(!drag)return;const p=drag.last||svgPoint(svg,e),d=drag;drag=null;if(d.mode==='move')commit(translateSelectionV33(d.base,p.x-d.start.x,p.y-d.start.y));else if(d.mode==='resize')commit(updatePrimaryElementV33(d.base,{w:Math.max(4,d.orig.w+p.x-d.start.x),h:Math.max(4,d.orig.h+p.y-d.start.y)}));else if(d.mode==='rotate'){const a=Math.atan2(p.y-d.center.y,p.x-d.center.x)*180/Math.PI;commit(updatePrimaryElementV33(d.base,{r:num(d.orig.r)+(a-d.startAngle)}))}};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:false})}
function addSimple(type){const g=generateGeometry(session.structure),p=g.panelMap[session.editorV33.focusPanelId]||g.panelMap.front||g.panelMap.base||g.bodyPanels?.[0];if(!p)return;const base={id:`${type}-${Date.now().toString(36)}`,type,group:'artwork',panelId:p.id,x:Math.min(12,Math.max(0,p.w-40)),y:Math.min(12,Math.max(0,p.h-25)),w:Math.min(type==='line'?70:90,Math.max(12,p.w-16)),h:type==='line'?0:Math.min(34,Math.max(10,p.h-16)),r:0,zIndex:session.elements.length,_v33Created:true};if(type==='text'){base.template='Text';base.fontSize=7;base.h=18}if(type==='shape')base.fill='none';if(type==='icon'){base.icon='up';base.group='marks';base.w=36;base.h=36}const next=clone(session);next.elements=[...next.elements,clampElementToPanel(base,g)];commit(setSelectionV33(next,[base.id],{primary:base.id}))}
async function importSvg(file){const text=await file.text(),mark=parseSvgMark(text,{name:file.name}),g=generateGeometry(session.structure),p=g.panelMap[session.editorV33.focusPanelId]||g.panelMap.front||g.panelMap.base||g.bodyPanels?.[0];if(!p)throw new Error('No target panel.');const width=Math.min(100,Math.max(25,p.w*.35)),el=createSvgMarkElement(mark,{panelId:p.id,x:10,y:10,width});el.group='artwork';el.zIndex=session.elements.length;el._v33Created=true;const next=clone(session);next.elements=[...next.elements,clampElementToPanel(el,g)];commit(setSelectionV33(next,[el.id],{primary:el.id}))}
function applyAction(action){if(action==='undo')return undo();if(action==='redo')return redo();if(action==='copy'){clipboard=copySelectionV33(session);return}if(action==='paste')return commit(pasteClipboardV33(session,clipboard));if(action==='duplicate')return commit(duplicateSelectionV33(session));if(action==='group')return commit(groupSelectionV33(session));if(action==='ungroup')return commit(ungroupSelectionV33(session));if(action==='delete')return commit(deleteSelectionV33(session));if(['front','back','forward','backward'].includes(action))return commit(moveSelectionZV33(session,action));if(action==='lock'){const el=session.elements.find(x=>x.id===session.selectedId);return commit(setSelectionFlagV33(session,'locked',!el?.locked))}if(action==='hide'){const el=session.elements.find(x=>x.id===session.selectedId);return commit(setSelectionFlagV33(session,'hidden',!el?.hidden))}if(action==='add-text')return addSimple('text');if(action==='add-shape')return addSimple('shape');if(action==='add-line')return addSimple('line');if(action==='add-icon')return addSimple('icon');if(action==='add-table')return commit(insertTableV33(session,{panelId:session.editorV33.focusPanelId||null}));if(action==='import-svg'){host.querySelector('#v33SvgFile')?.click();return}if(action==='fit-all'){const r=fitAllV33(session);return draft(r.state)}if(action==='focus-panel'){const id=host.querySelector('#v33PanelFocus')?.value;if(!id)return;const r=panelFocusV33(session,id);return draft(r.state)}if(action==='save-close'){writeState(session);closeWorkspace()}}
function bindWorkspace(g){const svg=host.querySelector('#v33Canvas');svg?.addEventListener('pointerdown',e=>startDrag(svg,e));host.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>applyAction(b.dataset.action)));host.querySelectorAll('[data-align]').forEach(b=>b.addEventListener('click',()=>commit(alignSelectionV33(session,b.dataset.align))));host.querySelectorAll('[data-distribute]').forEach(b=>b.addEventListener('click',()=>commit(distributeSelectionV33(session,b.dataset.distribute))));host.querySelectorAll('[data-layer-visible]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.layerVisible,l=session.editorV33.layers[k];commit(setLayerStateV33(session,k,{visible:l.visible===false}))}));host.querySelectorAll('[data-layer-lock]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.layerLock,l=session.editorV33.layers[k];commit(setLayerStateV33(session,k,{locked:!l.locked}))}));host.querySelectorAll('[data-select-layer]').forEach(b=>b.addEventListener('click',()=>commit(selectAllLayerV33(session,b.dataset.selectLayer))));host.querySelectorAll('[data-object-row]').forEach(r=>r.addEventListener('click',e=>{if(e.target.closest('button'))return;commit(selectElementV33(session,r.dataset.objectRow,{additive:e.shiftKey}))}));host.querySelectorAll('[data-el-visible]').forEach(b=>b.addEventListener('click',()=>{let n=setSelectionV33(session,[b.dataset.elVisible],{primary:b.dataset.elVisible}),el=n.elements.find(x=>x.id===b.dataset.elVisible);commit(setSelectionFlagV33(n,'hidden',!el.hidden))}));host.querySelectorAll('[data-el-lock]').forEach(b=>b.addEventListener('click',()=>{let n=setSelectionV33(session,[b.dataset.elLock],{primary:b.dataset.elLock}),el=n.elements.find(x=>x.id===b.dataset.elLock);commit(setSelectionFlagV33(n,'locked',!el.locked))}));host.querySelectorAll('[data-v33-prop]').forEach(inp=>inp.addEventListener('change',()=>{const k=inp.dataset.v33Prop,v=k==='panelId'?inp.value:num(inp.value);commit(updatePrimaryElementV33(session,{[k]:v}))}));host.querySelector('#v33SvgFile')?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{await importSvg(f)}catch(err){alert(err?.message||err)}})}
function onKey(e){if(!host)return;const tag=e.target?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;const mod=e.ctrlKey||e.metaKey,key=e.key.toLowerCase();if(mod&&key==='z'){e.preventDefault();return e.shiftKey?redo():undo()}if(mod&&key==='y'){e.preventDefault();return redo()}if(mod&&key==='c'){e.preventDefault();clipboard=copySelectionV33(session);return}if(mod&&key==='v'){e.preventDefault();return commit(pasteClipboardV33(session,clipboard))}if(mod&&key==='d'){e.preventDefault();return commit(duplicateSelectionV33(session))}if(mod&&key==='g'){e.preventDefault();return commit(e.shiftKey?ungroupSelectionV33(session):groupSelectionV33(session))}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();return commit(deleteSelectionV33(session))}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=e.shiftKey?10:1,dx=e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,dy=e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0;return commit(translateSelectionV33(session,dx,dy))}if(e.key==='Escape')closeWorkspace()}
function openWorkspace(){if(host)return;session=readState();history=[clone(session)];historyIndex=0;host=document.createElement('div');host.id='boxstudio-v33-workspace';host.className='v33-workspace';document.body.appendChild(host);document.body.classList.add('v33-open');window.addEventListener('keydown',onKey);renderWorkspace()}
function closeWorkspace(){if(!host)return;writeState(session);host.remove();host=null;window.removeEventListener('keydown',onKey);document.body.classList.remove('v33-open');location.reload()}
function installEntry(){if(document.getElementById('v33OpenProfessional'))return;const tabbar=document.querySelector('.workspace .tabbar');if(!tabbar)return;const state=readState();if(!['Design','Marks'].includes(state.editorTab))return;const b=document.createElement('button');b.id='v33OpenProfessional';b.className='v33-entry';b.textContent='Professional 2D';b.title='Open V0.33 multi-object professional editor';b.onclick=openWorkspace;tabbar.insertBefore(b,tabbar.querySelector('.spacer'))}
function sync(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;const brand=document.querySelector('.brand small');if(brand&&brand.textContent!==VERSION)brand.textContent=VERSION;const title=`BoxStudio ${VERSION}`;if(document.title!==title)document.title=title;installEntry()})}
const observer=new MutationObserver(sync),observeRoot=document.getElementById('app')||document.body;observer.observe(observeRoot,{childList:true,subtree:true});sync();
