import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry } from './geometry.js';
import { renderTemplate } from './variables.js';
import { applyMarkTemplate, getMarkTemplateCatalog } from './markTemplates.js';
import {
  catalogsV34, getMarkComponentCatalogV34, getMarkBlockCatalogV34, insertMarkComponentV34, insertMarkBlockV34,
  patchMarkElementV34, variableDefinitionsV34, variableUsageMapV34, missingVariablesV34, setVariableV34,
  insertVariableTokenV34, saveMarkRuleV34, deleteMarkRuleV34, markRuleDebugV34, applyMarkRulesV34,
  createMarkBlockFromSelectionV34, saveCustomMarkBlockV34, saveCurrentMarksTemplateV34, applyCustomerMarkPresetV34
} from './marksWorkspaceV34.js';

const VERSION='V0.34',clone=value=>structuredClone(value),num=(value,fallback=0)=>{const n=Number(value);return Number.isFinite(n)?n:fallback};
const esc=(value='')=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let host=null,session=null,history=[],historyIndex=-1,selectedIds=[],activeTab='variables',scheduled=false;

function readState(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return parsed?{...clone(defaultState),...parsed,variables:{...defaultState.variables,...(parsed.variables||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(state){state.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function commit(next,{render=true}={}){session=next;history=history.slice(0,historyIndex+1);history.push(clone(session));historyIndex=history.length-1;writeState(session);if(render)renderWorkspace()}
function undo(){if(historyIndex<=0)return;session=clone(history[--historyIndex]);writeState(session);syncSelection();renderWorkspace()}
function redo(){if(historyIndex>=history.length-1)return;session=clone(history[++historyIndex]);writeState(session);syncSelection();renderWorkspace()}
function markElements(){return (session?.elements||[]).filter(element=>element?.group==='marks')}
function panels(){const geo=generateGeometry(session?.structure||{});return{geo,list:(geo.bodyPanels||[]).filter(panel=>panel?.kind==='panel'||!panel?.kind)}}
function currentPanel(){const {geo,list}=panels(),panel=geo.panelMap?.[session.markEditorPanelId]||geo.panelMap?.front||geo.panelMap?.base||list[0];if(panel)session.markEditorPanelId=panel.id;return{geo,panel,list}}
function syncSelection(){const ids=new Set(markElements().map(x=>x.id));selectedIds=selectedIds.filter(id=>ids.has(id));if(session?.selectedId&&ids.has(session.selectedId)&&!selectedIds.includes(session.selectedId))selectedIds=[session.selectedId];if(!selectedIds.length&&markElements()[0])selectedIds=[markElements()[0].id];if(selectedIds.length)session.selectedId=selectedIds.at(-1)}
function primary(){return markElements().find(element=>element.id===session?.selectedId)||markElements().find(element=>selectedIds.includes(element.id))||null}

function markContent(element){
  if(element.type==='text'||element.type==='notice'){const text=renderTemplate(element.template||'',session.variables||{}),fs=Math.max(3,num(element.fontSize,6));return String(text).split('\n').map((line,index)=>`<text class="v34-text" x="2" y="${fs*(index+1)}" font-size="${fs}" font-weight="${element.bold?700:500}">${esc(line)}</text>`).join('')}
  if(element.type==='icon'){const glyph=element.icon==='up'?'↑↑':element.icon==='fragile'?'◇':'☂';return`<rect class="v34-iconbox" width="${num(element.w)}" height="${num(element.h)}"/><text x="${num(element.w)/2}" y="${num(element.h)*.66}" text-anchor="middle" font-size="${Math.min(num(element.w),num(element.h))*.48}">${glyph}</text>`}
  if(element.type==='barcode-qr-group')return`<rect class="v34-code" width="${num(element.w)}" height="${num(element.h)}"/><text x="6" y="16" font-size="8" font-weight="700">${esc(element.barcodeType||'CODE39')}</text><text x="6" y="28" font-size="6">BARCODE + QR</text>`;
  if(element.type==='svg-symbol')return`<rect class="v34-iconbox" width="${num(element.w)}" height="${num(element.h)}"/><text x="${num(element.w)/2}" y="${num(element.h)/2}" text-anchor="middle" font-size="7">SVG</text>`;
  return`<rect class="v34-iconbox" width="${num(element.w)}" height="${num(element.h)}"/>`;
}
function canvasMarkup(panel){
  if(!panel)return'<div class="v34-inspector-empty">No printable panel is available.</div>';
  const safe=Math.max(0,num(session.structure?.safe)),marks=markElements().filter(element=>element.panelId===panel.id),selected=new Set(selectedIds);
  return`<svg id="v34Canvas" class="v34-paper" viewBox="0 0 ${panel.w} ${panel.h}" xmlns="http://www.w3.org/2000/svg"><rect class="v34-panel-bg" width="${panel.w}" height="${panel.h}"/>${safe?`<rect class="v34-safe" x="${safe}" y="${safe}" width="${Math.max(0,panel.w-safe*2)}" height="${Math.max(0,panel.h-safe*2)}"/>`:''}${marks.map(element=>`<g data-v34-mark="${esc(element.id)}" class="v34-mark ${element.hidden?'hidden-rule':''}" transform="translate(${num(element.x)} ${num(element.y)}) rotate(${num(element.r)} ${num(element.w)/2} ${num(element.h)/2})">${markContent(element)}<rect class="v34-hit" width="${Math.max(2,num(element.w))}" height="${Math.max(2,num(element.h))}"/>${selected.has(element.id)?`<rect class="v34-selected" x="-2" y="-2" width="${num(element.w)+4}" height="${num(element.h)+4}"/>`:''}</g>`).join('')}</svg>`;
}

function componentLibrary(){const catalog=getMarkComponentCatalogV34(session),base=Object.values(catalog).filter(item=>!item.id.startsWith('asset:')),assets=Object.values(catalog).filter(item=>item.id.startsWith('asset:')&&!item.id.includes('asset-this-side-up')&&!item.id.includes('asset-fragile')&&!item.id.includes('asset-keep-dry'));return`<section class="v34-section"><div class="v34-section-head"><h3>Components</h3><span>${base.length}</span></div><div class="v34-library">${base.map(item=>`<button class="v34-card" draggable="true" data-drag-component="${esc(item.id)}" data-add-component="${esc(item.id)}"><b>${esc(item.label)}</b><span>${esc(item.category||'Mark')}</span></button>`).join('')}</div></section><section class="v34-section"><div class="v34-section-head"><h3>Custom Symbols</h3><span>${assets.length}</span></div>${assets.length?`<div class="v34-library">${assets.map(item=>`<button class="v34-card" draggable="true" data-drag-component="${esc(item.id)}" data-add-component="${esc(item.id)}"><b>${esc(item.label)}</b><span>Saved asset</span></button>`).join('')}</div>`:'<div class="v34-note">SVG/custom mark assets saved elsewhere appear here automatically.</div>'}</section>`}
function blockLibrary(){const blocks=Object.values(getMarkBlockCatalogV34(session));return`<section class="v34-section"><div class="v34-section-head"><h3>Reusable Blocks</h3><span>${blocks.length}</span></div><div class="v34-library">${blocks.map(block=>`<button class="v34-card v34-block" draggable="true" data-drag-block="${esc(block.id)}" data-add-block="${esc(block.id)}"><b>${esc(block.label)}</b><span>${esc(block.description||`${block.elements?.length||0} elements`)}</span></button>`).join('')}</div></section>`}

function inspector(panelList){const element=primary();if(!element)return'<div class="v34-inspector-empty">Select a mark to edit style and geometry.</div>';const variableOptions=variableDefinitionsV34(session).map(item=>`<option value="${esc(item.key)}">${esc(item.label)}</option>`).join('');let specific='';if(element.type==='text'||element.type==='notice')specific=`<label class="v34-field"><span>Text / template</span><textarea data-v34-prop="template">${esc(element.template||'')}</textarea></label><div class="v34-inline"><label class="v34-field" style="flex:1"><span>Font mm</span><input data-v34-prop="fontSize" type="number" step="0.1" value="${num(element.fontSize,6)}"></label><label><input data-v34-prop="bold" type="checkbox" ${element.bold?'checked':''}> Bold</label></div>`;else if(element.type==='barcode-qr-group')specific=`<label class="v34-field"><span>Barcode type</span><select data-v34-prop="barcodeType">${['CODE39','EAN13','UPCA','ITF14','GS1_128'].map(value=>`<option value="${value}" ${value===element.barcodeType?'selected':''}>${value}</option>`).join('')}</select></label><label class="v34-field"><span>Barcode value</span><input data-v34-prop="barcodeValue" value="${esc(element.barcodeValue||'')}"></label><label class="v34-field"><span>QR value</span><input data-v34-prop="qrValue" value="${esc(element.qrValue||'')}"></label>`;else if(element.type==='icon')specific=`<label class="v34-field"><span>Handling icon</span><select data-v34-prop="icon">${[['up','This Side Up'],['fragile','Fragile'],['dry','Keep Dry']].map(([value,label])=>`<option value="${value}" ${value===element.icon?'selected':''}>${label}</option>`).join('')}</select></label>`;
  return`<div class="v34-section-head"><h3>${esc(element.id)}</h3><span>${selectedIds.length} selected</span></div><div class="v34-grid5">${['x','y','w','h','r'].map(key=>`<label><span>${key.toUpperCase()}</span><input data-v34-prop="${key}" type="number" step="0.1" value="${num(element[key])}"></label>`).join('')}</div><label class="v34-field"><span>Panel</span><select data-v34-prop="panelId">${panelList.map(panel=>`<option value="${esc(panel.id)}" ${panel.id===element.panelId?'selected':''}>${esc(panel.label||panel.id)}</option>`).join('')}</select></label>${specific}<div class="v34-inline"><select id="v34VariablePicker" style="flex:1">${variableOptions}</select><button data-action="insert-variable">Insert {{var}}</button></div><div class="v34-inline" style="margin-top:8px"><input id="v34BlockName" placeholder="Block name" style="flex:1;border:1px solid #d6dce5;border-radius:7px;padding:7px"><button data-action="save-block">Save Block</button><button class="danger" data-action="delete-selected">Delete</button></div>`}

function variablesPanel(){const defs=variableDefinitionsV34(session),usage=new Map(variableUsageMapV34(session).map(item=>[item.key,item])),missing=missingVariablesV34(session);return`${missing.length?`<div class="v34-missing"><b>${missing.length} missing variable${missing.length===1?'':'s'}:</b> ${missing.map(item=>esc(item.key)).join(', ')}</div>`:''}<div class="v34-vars">${defs.map(item=>{const use=usage.get(item.key),isMissing=Boolean(use?.missing);return`<label class="v34-var ${isMissing?'missing':''} ${item.locked?'locked':''}"><b title="${esc(item.label)}">${esc(item.key)}</b><input data-var-key="${esc(item.key)}" value="${esc(item.value)}" ${item.locked?'disabled':''}><em>${use?.uses?.length||0}×${item.locked?' 🔒':''}</em></label>`}).join('')}</div>`}
function ruleFieldOptions(){return[{key:'customerProfileId',label:'Customer Profile'},{key:'markTemplateId',label:'Mark Template'},{key:'packagingRuleProfileId',label:'Packaging Rule'},...variableDefinitionsV34(session)].map(item=>`<option value="${esc(item.key)}">${esc(item.label||item.key)}</option>`).join('')}
function rulesPanel(){const marks=markElements(),debug=markRuleDebugV34(session);return`<div class="v34-rule-builder"><div class="row"><select id="v34RuleTarget">${marks.map(mark=>`<option value="${esc(mark.id)}">${esc(mark.id)}</option>`).join('')}</select><select id="v34RuleEffect"><option value="show">SHOW</option><option value="hide">HIDE</option></select><select id="v34RuleField">${ruleFieldOptions()}</select></div><div class="row"><select id="v34RuleOp">${[['eq','='],['neq','≠'],['gt','>'],['gte','≥'],['lt','<'],['lte','≤'],['contains','contains'],['in','in list'],['not-empty','not empty'],['empty','empty']].map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select><input id="v34RuleValue" placeholder="Expected value"><button class="primary" data-action="create-rule">Add Rule</button></div><div class="v34-note">Rules can evaluate Package Count, Country, Customer and any project variable. Matching is recalculated when a variable changes.</div></div>${debug.map(item=>`<div class="v34-rule"><div class="head"><b>${esc(item.rule.label)}</b><div><span class="${item.matched?'pass':'fail'}">${item.matched?'MATCH':'NO MATCH'}</span> <button data-delete-rule="${esc(item.rule.id)}">Delete</button></div></div><small>${esc(item.rule.effect.toUpperCase())} · ${item.rule.targetIds.map(esc).join(', ')}</small><div class="v34-rule-debug">${item.trace.map(trace=>`${esc(trace.field)} ${esc(trace.op)} ${esc(trace.expected)} → ${esc(trace.actual)} [${trace.matched?'pass':'fail'}]`).join('<br>')||'Always matches'}</div></div>`).join('')}`}
function objectList(){return`<section class="v34-section"><div class="v34-section-head"><h3>Objects</h3><span>${markElements().length}</span></div><div class="v34-object-list">${markElements().map(mark=>`<div class="v34-object ${selectedIds.includes(mark.id)?'selected':''}" data-object-id="${esc(mark.id)}"><b>${esc(mark.id)}</b><span>${esc(mark.type)}${mark.hidden?' · hidden':''}</span></div>`).join('')}</div></section>`}

function renderWorkspace(){if(!host||!session)return;syncSelection();const {panel,list}=currentPanel(),catalogs=catalogsV34(session),customers=Object.values(catalogs.customers),templates=Object.values(catalogs.templates),missing=missingVariablesV34(session);host.innerHTML=`<div class="v34-top"><div class="v34-brand"><b>BOXSTUDIO</b><span>Marks Studio · ${VERSION}</span></div><button data-action="undo">↶</button><button data-action="redo">↷</button><label>Customer <select id="v34Customer">${customers.map(item=>`<option value="${esc(item.id)}" ${item.id===session.customerProfileId?'selected':''}>${esc(item.label)}</option>`).join('')}</select></label><button data-action="apply-customer">Apply</button><label>Template <select id="v34Template">${templates.map(item=>`<option value="${esc(item.id)}" ${item.id===session.markTemplateId?'selected':''}>${esc(item.label)}</option>`).join('')}</select></label><button data-action="apply-template">Apply</button><label>Panel <select id="v34Panel">${list.map(item=>`<option value="${esc(item.id)}" ${item.id===panel?.id?'selected':''}>${esc(item.label||item.id)}</option>`).join('')}</select></label><span class="v34-spacer"></span><button class="primary" data-action="save-close">Save & Exit</button></div><div class="v34-body"><aside class="v34-left">${componentLibrary()}${blockLibrary()}</aside><main class="v34-stage"><div class="v34-canvas-shell">${canvasMarkup(panel)}</div><div class="v34-stagebar"><b>${esc(panel?.label||panel?.id||'No panel')}</b><span>${panel?`${panel.w.toFixed(1)} × ${panel.h.toFixed(1)} mm`:''}</span><span>${markElements().filter(x=>x.panelId===panel?.id).length} marks</span>${missing.length?`<span class="error">${missing.length} missing variables</span>`:'<span>Variables OK</span>'}<span>Drop components onto the panel</span></div></main><aside class="v34-right"><section class="v34-section">${inspector(list)}</section><div class="v34-tabs"><button data-right-tab="variables" class="${activeTab==='variables'?'active':''}">Variables</button><button data-right-tab="rules" class="${activeTab==='rules'?'active':''}">Rules / Debug</button></div><section class="v34-section">${activeTab==='variables'?variablesPanel():rulesPanel()}</section>${objectList()}<section class="v34-section"><div class="v34-inline"><input id="v34TemplateName" placeholder="Save current marks as template" style="flex:1;border:1px solid #d6dce5;border-radius:7px;padding:7px"><button data-action="save-template">Save Template</button></div></section></aside></div>`;bindWorkspace(panel)}

function selectMark(id,additive=false){if(!additive)selectedIds=[id];else selectedIds=selectedIds.includes(id)?selectedIds.filter(x=>x!==id):[...selectedIds,id];session.selectedId=id;writeState(session);renderWorkspace()}
function addComponent(id,position={}){const next=insertMarkComponentV34(session,id,{panelId:session.markEditorPanelId,...position});selectedIds=[next.selectedId];commit(applyMarkRulesV34(next))}
function addBlock(id,position={}){const before=new Set(markElements().map(x=>x.id)),next=insertMarkBlockV34(session,id,{panelId:session.markEditorPanelId,...position}),created=(next.elements||[]).filter(x=>x.group==='marks'&&!before.has(x.id)).map(x=>x.id);selectedIds=created.length?created:[next.selectedId];commit(applyMarkRulesV34(next))}
function deleteSelected(){const ids=new Set(selectedIds),next=clone(session);next.elements=(next.elements||[]).filter(element=>!ids.has(element.id));selectedIds=[];next.selectedId=(next.elements||[]).find(element=>element.group==='marks')?.id||null;commit(next)}
function insertPickedVariable(){const element=primary(),key=host.querySelector('#v34VariablePicker')?.value;if(!element||!key)return;const field=(element.type==='barcode-qr-group')?'barcodeValue':(element.type==='text'||element.type==='notice')?'template':null;if(!field)return;commit(patchMarkElementV34(session,element.id,{[field]:insertVariableTokenV34(element[field]||'',key)}))}
function saveBlock(){const name=host.querySelector('#v34BlockName')?.value?.trim()||`Reusable Block ${Object.keys(session.customMarkBlocksV34||{}).length+1}`;const block=createMarkBlockFromSelectionV34(session,selectedIds,{label:name});commit(saveCustomMarkBlockV34(session,block))}
function createRule(){const target=host.querySelector('#v34RuleTarget')?.value,field=host.querySelector('#v34RuleField')?.value,op=host.querySelector('#v34RuleOp')?.value,value=host.querySelector('#v34RuleValue')?.value,effect=host.querySelector('#v34RuleEffect')?.value;if(!target||!field)return;const rule={id:`rule-${Date.now().toString(36)}`,label:`${effect==='hide'?'Hide':'Show'} ${target} when ${field} ${op} ${value||''}`.trim(),targetIds:[target],effect,conditions:[{field,op,value}]};activeTab='rules';commit(saveMarkRuleV34(session,rule))}
function saveTemplate(){const name=host.querySelector('#v34TemplateName')?.value?.trim()||`Marks ${new Date().toISOString().slice(0,10)}`;commit(saveCurrentMarksTemplateV34(session,{label:name}))}

function applyAction(action){if(action==='undo')return undo();if(action==='redo')return redo();if(action==='save-close')return closeWorkspace();if(action==='delete-selected')return deleteSelected();if(action==='insert-variable')return insertPickedVariable();if(action==='save-block')return saveBlock();if(action==='create-rule')return createRule();if(action==='save-template')return saveTemplate();if(action==='apply-customer'){const id=host.querySelector('#v34Customer')?.value;selectedIds=[];return commit(applyCustomerMarkPresetV34(session,id,{overwriteDefaults:true}))}if(action==='apply-template'){const id=host.querySelector('#v34Template')?.value;selectedIds=[];return commit(applyMarkRulesV34(applyMarkTemplate(session,id)))}}
function dropPosition(svg,event,panel){const rect=svg.getBoundingClientRect(),x=(event.clientX-rect.left)/Math.max(1,rect.width)*panel.w,y=(event.clientY-rect.top)/Math.max(1,rect.height)*panel.h;return{x:Math.max(0,x),y:Math.max(0,y)}}

function bindWorkspace(panel){
  host.querySelectorAll('[data-add-component]').forEach(button=>button.addEventListener('click',()=>addComponent(button.dataset.addComponent)));
  host.querySelectorAll('[data-add-block]').forEach(button=>button.addEventListener('click',()=>addBlock(button.dataset.addBlock)));
  host.querySelectorAll('[data-drag-component]').forEach(button=>button.addEventListener('dragstart',event=>event.dataTransfer?.setData('application/x-boxstudio-v34',`component:${button.dataset.dragComponent}`)));
  host.querySelectorAll('[data-drag-block]').forEach(button=>button.addEventListener('dragstart',event=>event.dataTransfer?.setData('application/x-boxstudio-v34',`block:${button.dataset.dragBlock}`)));
  const svg=host.querySelector('#v34Canvas');svg?.addEventListener('dragover',event=>event.preventDefault());svg?.addEventListener('drop',event=>{event.preventDefault();if(!panel)return;const data=event.dataTransfer?.getData('application/x-boxstudio-v34')||'',position=dropPosition(svg,event,panel);if(data.startsWith('component:'))addComponent(data.slice(10),position);else if(data.startsWith('block:'))addBlock(data.slice(6),position)});
  host.querySelectorAll('[data-v34-mark]').forEach(node=>node.addEventListener('click',event=>{event.stopPropagation();selectMark(node.dataset.v34Mark,event.shiftKey)}));
  host.querySelectorAll('[data-object-id]').forEach(node=>node.addEventListener('click',event=>selectMark(node.dataset.objectId,event.shiftKey)));
  host.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>applyAction(button.dataset.action)));
  host.querySelectorAll('[data-right-tab]').forEach(button=>button.addEventListener('click',()=>{activeTab=button.dataset.rightTab;renderWorkspace()}));
  host.querySelector('#v34Panel')?.addEventListener('change',event=>{session.markEditorPanelId=event.target.value;writeState(session);renderWorkspace()});
  host.querySelectorAll('[data-v34-prop]').forEach(input=>input.addEventListener('change',()=>{const element=primary();if(!element)return;const key=input.dataset.v34Prop;let value;if(input.type==='checkbox')value=input.checked;else if(['x','y','w','h','r','fontSize'].includes(key))value=num(input.value);else value=input.value;commit(applyMarkRulesV34(patchMarkElementV34(session,element.id,{[key]:value})))}));
  host.querySelectorAll('[data-var-key]').forEach(input=>input.addEventListener('change',()=>{try{commit(applyMarkRulesV34(setVariableV34(session,input.dataset.varKey,input.value)))}catch(error){input.value=session.variables?.[input.dataset.varKey]??'';console.warn(error)}}));
  host.querySelectorAll('[data-delete-rule]').forEach(button=>button.addEventListener('click',()=>{activeTab='rules';commit(deleteMarkRuleV34(session,button.dataset.deleteRule))}));
}

function onKey(event){if(!host)return;const tag=event.target?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;const mod=event.ctrlKey||event.metaKey,key=event.key.toLowerCase();if(mod&&key==='z'){event.preventDefault();return event.shiftKey?redo():undo()}if(mod&&key==='y'){event.preventDefault();return redo()}if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();return deleteSelected()}if(event.key==='Escape')closeWorkspace()}
function openWorkspace(){if(host)return;session=applyMarkRulesV34(readState());selectedIds=[];syncSelection();history=[clone(session)];historyIndex=0;host=document.createElement('div');host.id='boxstudio-v34-marks';host.className='v34-workspace';document.body.appendChild(host);document.body.classList.add('v34-open');window.addEventListener('keydown',onKey);writeState(session);renderWorkspace()}
function closeWorkspace(){if(!host)return;writeState(session);host.remove();host=null;document.body.classList.remove('v34-open');window.removeEventListener('keydown',onKey);location.reload()}

function installEntry(){const brand=document.querySelector('.brand small');if(brand&&brand.textContent!==VERSION)brand.textContent=VERSION;if(document.title!==`BoxStudio ${VERSION}`)document.title=`BoxStudio ${VERSION}`;if(document.getElementById('v34OpenMarksStudio'))return;const marksPage=[...document.querySelectorAll('.page-head h1')].find(node=>node.textContent?.trim()==='Marks Library');if(marksPage){const head=marksPage.closest('.page-head');const button=document.createElement('button');button.id='v34OpenMarksStudio';button.className='primary v34-entry';button.textContent='Open Marks Studio';button.onclick=openWorkspace;head?.appendChild(button);return}const tabbar=document.querySelector('.workspace .tabbar'),active=tabbar?.querySelector('button.active')?.textContent?.trim();if(tabbar&&active==='Marks'){const button=document.createElement('button');button.id='v34OpenMarksStudio';button.className='v34-entry';button.textContent='Marks Studio';button.onclick=openWorkspace;tabbar.insertBefore(button,tabbar.querySelector('.spacer'))}}
function sync(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;installEntry()})}
const root=document.getElementById('app');if(root){new MutationObserver(sync).observe(root,{childList:true,subtree:true});sync()}
