import { STORAGE_KEY, defaultState } from './model.js';
import { generateGeometry, resolveElementRect } from './geometry.js';
import { buildFoldGraph } from './foldgraph.js';
import { mountArtworkProof } from './threeArtworkProof.js';
import { renderTemplate } from './variables.js';
import {
  buildReviewModelV35, ensureReviewStateV35, selectReviewPanelV35, selectReviewElementV35,
  patchReviewElementV35, setReviewMaterialV35, setReviewFoldProgressV35,
  materialCatalogV35, resolveMaterialVisualV35
} from './threeReviewV35.js';

const clone=value=>structuredClone(value);
const esc=(value='')=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const num=(value,fallback=0)=>{const n=Number(value);return Number.isFinite(n)?n:fallback};
let host=null,session=null,proofController=null,proofTimer=0,observer=null;

function readState(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return ensureReviewStateV35(parsed?{...clone(defaultState),...parsed,structure:{...defaultState.structure,...(parsed.structure||{})},variables:{...defaultState.variables,...(parsed.variables||{})}}:clone(defaultState))}catch{return ensureReviewStateV35(clone(defaultState))}}
function persist(){session.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(session))}
function commit(next,{proof=true}={}){session=ensureReviewStateV35(next);persist();render2D();renderInspector();renderDiagnostics();renderTop();if(proof)scheduleProof()}
function scheduleProof(){clearTimeout(proofTimer);proofTimer=setTimeout(()=>mountProof(),90)}
function closeReview(){clearTimeout(proofTimer);proofController?.dispose?.();proofController=null;host?.remove();host=null;injectLauncher()}

function panelShape(panel,selected){
  if(Array.isArray(panel.points)&&panel.points.length>=3)return`<polygon data-v35-panel="${esc(panel.id)}" class="v35-panel ${selected?'selected':''}" points="${panel.points.map(point=>point.join(',')).join(' ')}"/>`;
  return`<rect data-v35-panel="${esc(panel.id)}" class="v35-panel ${selected?'selected':''}" x="${num(panel.x)}" y="${num(panel.y)}" width="${num(panel.w)}" height="${num(panel.h)}"/>`;
}
function elementShape(element,geo,selected){
  let rr;try{rr=resolveElementRect(element,geo)}catch{return''}const x=num(rr.absX),y=num(rr.absY),w=Math.max(2,num(element.w,8)),h=Math.max(2,num(element.h,8)),label=element.type==='text'||element.type==='notice'?renderTemplate(element.template||'',session.variables||{}).split('\n')[0]:(element.type==='barcode-qr-group'?'BARCODE + QR':element.type||'object');
  return`<g data-v35-element="${esc(element.id)}" class="v35-el ${selected?'selected':''}" transform="rotate(${num(element.r)} ${x+w/2} ${y+h/2})"><rect x="${x}" y="${y}" width="${w}" height="${h}"/><text x="${x+2}" y="${y+Math.min(10,h-1)}">${esc(label.slice(0,28))}</text></g>`;
}

function render2D(){if(!host||!session)return;const target=host.querySelector('#v35Dieline');if(!target)return;const model=buildReviewModelV35(session),{geo}=model,panels=(geo.bodyPanels||[]).filter(panel=>panel&&num(panel.w)>0&&num(panel.h)>0),elements=(session.elements||[]).filter(element=>!element.hidden&&element.panelId===model.selectedPanelId);target.innerHTML=`<div class="v35-pane-head"><div><b>2D Dieline</b><span>${esc(model.selectedPanel?.label||model.selectedPanelId||'No panel')}</span></div><span>${elements.length} objects</span></div><div class="v35-svg-wrap"><svg id="v35DielineSvg" viewBox="0 0 ${Math.max(1,geo.width)} ${Math.max(1,geo.height)}" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" class="v35-sheet"/>${panels.map(panel=>panelShape(panel,panel.id===model.selectedPanelId)).join('')}${elements.map(element=>elementShape(element,geo,element.id===session.reviewV35.selectedElementId)).join('')}</svg></div>`;
  target.querySelectorAll('[data-v35-panel]').forEach(node=>node.addEventListener('click',event=>{session=selectReviewPanelV35(session,event.currentTarget.dataset.v35Panel,{source:'2d'});persist();proofController?.setSelectedPanel?.(session.reviewV35.selectedPanelId);render2D();renderInspector();renderDiagnostics();renderTop()}));
  target.querySelectorAll('[data-v35-element]').forEach(node=>node.addEventListener('click',event=>{event.stopPropagation();session=selectReviewElementV35(session,event.currentTarget.dataset.v35Element,{source:'2d'});persist();proofController?.setSelectedPanel?.(session.reviewV35.selectedPanelId);render2D();renderInspector();renderTop()}));
}

function selectedElement(){return(session.elements||[]).find(element=>element.id===session.reviewV35?.selectedElementId)||null}
function renderInspector(){if(!host||!session)return;const target=host.querySelector('#v35Inspector');if(!target)return;const model=buildReviewModelV35(session),element=selectedElement(),items=model.panelElements;target.innerHTML=`<div class="v35-side-head"><div><b>Selection</b><span>2D ↔ 3D linked</span></div><span class="v35-source">${esc(session.reviewV35.lastSelectionSource)}</span></div><div class="v35-object-list">${items.map(item=>`<button data-v35-object="${esc(item.id)}" class="${item.id===element?.id?'active':''}"><b>${esc(item.id)}</b><span>${esc(item.type)}</span></button>`).join('')||'<div class="v35-empty">No artwork on this panel.</div>'}</div>${element?`<div class="v35-inspector-card"><h4>${esc(element.id)}</h4><div class="v35-grid5">${['x','y','w','h','r'].map(key=>`<label><span>${key.toUpperCase()}</span><input data-v35-prop="${key}" type="number" step="0.1" value="${num(element[key])}"></label>`).join('')}</div>${element.type==='text'||element.type==='notice'?`<label class="v35-field"><span>Text / variable template</span><textarea data-v35-prop="template">${esc(element.template||'')}</textarea></label><label class="v35-field"><span>Font mm</span><input data-v35-prop="fontSize" type="number" step="0.1" value="${num(element.fontSize,6)}"></label>`:''}${element.type==='barcode-qr-group'?`<label class="v35-field"><span>Barcode value</span><input data-v35-prop="barcodeValue" value="${esc(element.barcodeValue||'')}"></label><label class="v35-field"><span>QR value</span><input data-v35-prop="qrValue" value="${esc(element.qrValue||'')}"></label>`:''}<div class="v35-live">Live revision <b>${session.reviewV35.liveRevision}</b> · edits refresh 3D proof automatically</div></div>`:'<div class="v35-empty">Select a 2D object to edit exact geometry.</div>'}`;
  target.querySelectorAll('[data-v35-object]').forEach(button=>button.onclick=()=>{commit(selectReviewElementV35(session,button.dataset.v35Object,{source:'2d'}),{proof:false});proofController?.setSelectedPanel?.(session.reviewV35.selectedPanelId)});
  target.querySelectorAll('[data-v35-prop]').forEach(input=>{const apply=()=>{const key=input.dataset.v35Prop,value=input.type==='number'?num(input.value):input.value;session=patchReviewElementV35(session,{[key]:value});persist();render2D();renderDiagnostics();renderTop();scheduleProof()};input.addEventListener(input.tagName==='TEXTAREA'?'input':'change',apply)});
}

function renderDiagnostics(){if(!host||!session)return;const target=host.querySelector('#v35Diagnostics');if(!target)return;const {diagnostics}=buildReviewModelV35(session),issues=diagnostics.issues;target.innerHTML=`<div class="v35-diag-head"><div><b>Fold Direction / Dependency Order</b><span>Graph-derived review sequence, not a factory machine program.</span></div><span class="${diagnostics.ok?'ok':'bad'}">${diagnostics.ok?'GRAPH OK':'CHECK GRAPH'}</span></div>${issues.length?`<div class="v35-issues">${issues.map(issue=>`<div class="${issue.severity}"><b>${esc(issue.code)}</b><span>${esc(issue.detail)}</span></div>`).join('')}</div>`:''}<div class="v35-sequence">${diagnostics.sequence.map(item=>`<div><span class="step">${item.step}</span><b>${esc(item.from)} → ${esc(item.to)}</b><span class="angle ${item.direction}">${item.angle>0?'+':''}${item.angle}°</span><small>${item.fallback?'fallback hinge':'physical hinge'}</small></div>`).join('')||'<div class="v35-empty">No fold edges available.</div>'}</div>`}

function renderTop(){if(!host||!session)return;const material=resolveMaterialVisualV35(session.structure||{}),catalog=materialCatalogV35(),materialSelect=host.querySelector('#v35Material'),flute=host.querySelector('#v35Flute'),thickness=host.querySelector('#v35Thickness'),fold=host.querySelector('#v35Fold'),label=host.querySelector('#v35FoldLabel'),meta=host.querySelector('#v35MaterialMeta');if(materialSelect){materialSelect.innerHTML=catalog.map(item=>`<option value="${esc(item.id)}" ${item.id===material.materialId?'selected':''}>${esc(item.name)}</option>`).join('')}if(flute){const current=catalog.find(item=>item.id===material.materialId),options=current?.flutes||[];flute.disabled=!options.length;flute.innerHTML=options.length?options.map(item=>`<option value="${item.id}" ${item.id===material.flute?'selected':''}>${esc(item.label)} · ${item.thicknessMm} mm</option>`).join(''):'<option value="">N/A</option>'}if(thickness)thickness.value=material.thicknessMm;if(fold)fold.value=num(session.foldProgress,100);if(label)label.textContent=`${num(session.foldProgress,100)}%`;if(meta)meta.textContent=material.label}

function mountProof(){if(!host||!session)return;proofController?.dispose?.();proofController=null;const target=host.querySelector('#v35Proof');if(!target)return;const model=buildReviewModelV35(session);proofController=mountArtworkProof(target,session,model.geo,model.graph,{selectedPanelId:model.selectedPanelId,materialStyle:model.material,onStatus:status=>{const el=host?.querySelector('#v35ProofStatus');if(el)el.textContent=`${status.mode} · ${status.texturedPanels}/${status.panels} textured panels · ${status.seamWarnings} seam warnings`},onSelectPanel:panelId=>{session=selectReviewPanelV35(session,panelId,{source:'3d'});persist();proofController?.setSelectedPanel?.(panelId);render2D();renderInspector();renderDiagnostics();renderTop()}})}

function bindStatic(){
  host.querySelector('#v35Close').onclick=closeReview;
  host.querySelector('#v35Fold').oninput=event=>{session=setReviewFoldProgressV35(session,event.target.value);persist();host.querySelector('#v35FoldLabel').textContent=`${session.foldProgress}%`;proofController?.setProgress?.(session.foldProgress)};
  host.querySelector('#v35Material').onchange=event=>{session=setReviewMaterialV35(session,{materialId:event.target.value,thickness:''});const material=resolveMaterialVisualV35(session.structure);if(material.flute)session.structure.flute=material.flute;persist();renderTop();renderDiagnostics();mountProof()};
  host.querySelector('#v35Flute').onchange=event=>{session=setReviewMaterialV35(session,{flute:event.target.value,thickness:''});persist();renderTop();mountProof()};
  host.querySelector('#v35Thickness').onchange=event=>{session=setReviewMaterialV35(session,{thickness:Math.max(.05,num(event.target.value,.5))});persist();renderTop();mountProof()};
  host.querySelector('#v35ResetView').onclick=()=>{proofController?.setView?.({yaw:.55,pitch:-.34,zoom:1})};
}

function openReview(){if(host)return;session=readState();host=document.createElement('div');host.id='boxstudio-v35-review';host.innerHTML=`<div class="v35-shell"><header class="v35-top"><div class="v35-brand"><b>BOXSTUDIO</b><span>2D ↔ 3D Review · V0.35</span></div><label>Fold <input id="v35Fold" type="range" min="0" max="100" value="100"><b id="v35FoldLabel">100%</b></label><label>Material <select id="v35Material"></select></label><label>Flute <select id="v35Flute"></select></label><label>Thickness <input id="v35Thickness" class="v35-mm" type="number" step="0.05" min="0.05"> mm</label><span class="v35-material-meta" id="v35MaterialMeta"></span><span class="v35-spacer"></span><button id="v35ResetView">Reset View</button><button class="primary" id="v35Close">Save & Exit</button></header><main class="v35-main"><section id="v35Dieline" class="v35-pane v35-2d"></section><section class="v35-pane v35-3d"><div class="v35-pane-head"><div><b>3D Artwork Proof</b><span>Click a face to focus the matching 2D panel</span></div><span id="v35ProofStatus">Preparing proof…</span></div><div id="v35Proof" class="v35-proof"></div></section><aside id="v35Inspector" class="v35-inspector"></aside></main><section id="v35Diagnostics" class="v35-diagnostics"></section></div>`;document.body.appendChild(host);bindStatic();renderTop();render2D();renderInspector();renderDiagnostics();mountProof()}

function injectLauncher(){const toolbar=document.querySelector('.three-toolbar');if(!toolbar||document.querySelector('#v35OpenReview'))return;const button=document.createElement('button');button.id='v35OpenReview';button.className='primary';button.textContent='Open 2D ↔ 3D Review';button.onclick=openReview;toolbar.appendChild(button)}

observer=new MutationObserver(()=>injectLauncher());observer.observe(document.documentElement,{childList:true,subtree:true});injectLauncher();

export {openReview,closeReview};
