import { STORAGE_KEY, defaultState } from './model.js';
import {
  dielineDocumentFromStateV38,moveNodeV38,setEdgeLineTypeV38,setEdgeCurveV38,setCubicHandlesV38,
  insertNodeOnEdgeV38,deleteNodeV38,buildProductionZonesV38,validateDielineDocumentV38,nodeByIdV38,edgeByIdV38
} from './dielineCadV38.js';
import { runPreflightV38 } from './preflightV38.js';
import { buildDielineSvgV38,buildDxfV38,buildDielinePdfV38,exportSummaryV38 } from './productionExportV38.js';

const VERSION='V0.38',clone=v=>structuredClone(v),num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let host=null,state=null,doc=null,selectedNodeId=null,selectedEdgeId=null,report=null,observer=null,drag=null;
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,structure:{...defaultState.structure,...(p.structure||{})},variables:{...defaultState.variables,...(p.variables||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function persist(){state={...state,dielineV38:doc,savedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function download(name,data,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function edgePath(edge,nodes){const a=nodes.get(edge.a),b=nodes.get(edge.b);if(!a||!b)return'';if(edge.curve==='cubic')return`M ${a.x} ${a.y} C ${edge.c1?.x} ${edge.c1?.y} ${edge.c2?.x} ${edge.c2?.y} ${b.x} ${b.y}`;if(edge.curve==='arc'){const ar=edge.arc||{};return`M ${a.x} ${a.y} A ${ar.rx||1} ${ar.ry||1} ${ar.rotation||0} ${ar.largeArc?1:0} ${ar.sweep?1:0} ${b.x} ${b.y}`}return`M ${a.x} ${a.y} L ${b.x} ${b.y}`}
function cubicControls(nodes){const edge=selectedEdgeId?edgeByIdV38(doc,selectedEdgeId):null;if(!edge||edge.curve!=='cubic'||!edge.c1||!edge.c2)return'';const a=nodes.get(edge.a),b=nodes.get(edge.b);if(!a||!b)return'';return`<g class="v38-controls"><line x1="${a.x}" y1="${a.y}" x2="${edge.c1.x}" y2="${edge.c1.y}"/><line x1="${b.x}" y1="${b.y}" x2="${edge.c2.x}" y2="${edge.c2.y}"/><circle data-v38-control="c1" cx="${edge.c1.x}" cy="${edge.c1.y}" r="2.4"/><circle data-v38-control="c2" cx="${edge.c2.x}" cy="${edge.c2.y}" r="2.4"/></g>`}
function canvasMarkup(){const nodes=new Map(doc.nodes.map(n=>[n.id,n])),edges=doc.edges.map(e=>`<path data-v38-edge="${esc(e.id)}" class="v38-edge ${e.lineType.toLowerCase()} ${e.id===selectedEdgeId?'selected':''}" d="${edgePath(e,nodes)}"/>`).join(''),handles=doc.nodes.map(n=>`<circle data-v38-node="${esc(n.id)}" class="v38-node ${n.id===selectedNodeId?'selected':''}" cx="${n.x}" cy="${n.y}" r="2.1"/>`).join(''),zones=[...(doc.zones?.bleed||[]).map(z=>`<rect class="v38-zone bleed" x="${z.x}" y="${z.y}" width="${z.w}" height="${z.h}"/>`),...(doc.zones?.safe||[]).map(z=>`<rect class="v38-zone safe" x="${z.x}" y="${z.y}" width="${z.w}" height="${z.h}"/>`)].join('');return`<svg id="v38Canvas" viewBox="0 0 ${doc.width} ${doc.height}" xmlns="http://www.w3.org/2000/svg"><rect class="v38-sheet" width="100%" height="100%"/>${zones}${edges}${cubicControls(nodes)}${handles}</svg>`}
function topMarkup(){const s=exportSummaryV38(doc);return`<header class="v38-top"><div class="v38-brand"><b>BOXSTUDIO</b><span>Professional Dieline CAD · ${VERSION}</span></div><div class="v38-top-meta"><b>${s.widthMm.toFixed(1)} × ${s.heightMm.toFixed(1)} mm</b><span>${s.nodes} nodes · ${s.edges} edges</span></div><span class="v38-spacer"></span><button data-v38-action="preflight">Run Preflight</button><button data-v38-export="svg">SVG</button><button data-v38-export="dxf">DXF</button><button data-v38-export="pdf">Dieline PDF</button><button data-v38-action="close" class="primary">Save & Exit</button></header>`}
function leftMarkup(){return`<aside class="v38-left"><h3>Node / Edge</h3><button data-v38-action="insert-node">＋ Add Node on Edge</button><button data-v38-action="delete-node" class="danger">− Delete Node</button><h3>Geometry</h3><button data-v38-curve="line">Line</button><button data-v38-curve="cubic">Cubic Bézier</button><button data-v38-curve="arc">Arc</button><h3>Line Type</h3>${['CUT','CREASE','PERF','GLUE'].map(t=>`<button data-v38-line-type="${t}" class="type-${t.toLowerCase()}">${t}</button>`).join('')}<h3>Production Zones</h3><label>Bleed <input id="v38Bleed" type="number" min="0" step="0.1" value="${num(doc.settings?.bleedMm,3)}"> mm</label><label>Safe <input id="v38Safe" type="number" min="0" step="0.1" value="${num(doc.settings?.safeMm,5)}"> mm</label></aside>`}
function inspectorMarkup(){const node=selectedNodeId?nodeByIdV38(doc,selectedNodeId):null,edge=selectedEdgeId?edgeByIdV38(doc,selectedEdgeId):null;if(node)return`<section><div class="v38-section-head"><h3>Node</h3><span>${esc(node.id)}</span></div><div class="v38-grid2"><label>X mm<input data-v38-node-prop="x" type="number" step="0.1" value="${node.x}"></label><label>Y mm<input data-v38-node-prop="y" type="number" step="0.1" value="${node.y}"></label></div><p>Exact millimeter coordinates. Drag the node directly or enter values here.</p></section>`;if(edge){let curve='';if(edge.curve==='cubic')curve=`<div class="v38-grid2"><label>C1 X<input data-v38-handle="c1x" type="number" step="0.1" value="${edge.c1?.x??0}"></label><label>C1 Y<input data-v38-handle="c1y" type="number" step="0.1" value="${edge.c1?.y??0}"></label><label>C2 X<input data-v38-handle="c2x" type="number" step="0.1" value="${edge.c2?.x??0}"></label><label>C2 Y<input data-v38-handle="c2y" type="number" step="0.1" value="${edge.c2?.y??0}"></label></div>`;if(edge.curve==='arc')curve=`<div class="v38-grid2"><label>RX<input data-v38-arc="rx" type="number" step="0.1" value="${edge.arc?.rx??1}"></label><label>RY<input data-v38-arc="ry" type="number" step="0.1" value="${edge.arc?.ry??1}"></label></div>`;return`<section><div class="v38-section-head"><h3>Edge</h3><span>${esc(edge.id)}</span></div><dl><dt>Type</dt><dd>${edge.lineType}</dd><dt>Geometry</dt><dd>${edge.curve}</dd><dt>Nodes</dt><dd>${esc(edge.a)} → ${esc(edge.b)}</dd></dl>${curve}</section>`}return`<section class="v38-empty"><h3>Inspector</h3><p>Select a node or edge on the dieline.</p></section>`}
function preflightMarkup(){if(!report)return`<section><div class="v38-section-head"><h3>Preflight</h3><span>not run</span></div><p>Run structural + artwork + marks + barcode/QR + font/PDF checks against this edited dieline.</p></section>`;return`<section><div class="v38-section-head"><h3>Preflight</h3><span class="${report.ok?'ok':'bad'}">${report.ok?'PASS':'BLOCKED'}</span></div><div class="v38-counts"><b>${report.summary.errors} errors</b><span>${report.summary.warnings} warnings</span><span>${report.summary.passes} passes</span></div><div class="v38-checks">${report.checks.filter(x=>x.severity!=='pass').slice(0,30).map(x=>`<div class="${x.severity}"><b>${esc(x.code)}</b><span>${esc(x.detail||x.title)}</span></div>`).join('')||'<div class="pass">No blocking/warning checks.</div>'}</div></section>`}
function render(){if(!host)return;const stats=validateDielineDocumentV38(doc).stats;host.innerHTML=`<div class="v38-shell">${topMarkup()}<div class="v38-body">${leftMarkup()}<main class="v38-stage"><div class="v38-canvas-wrap">${canvasMarkup()}</div><div class="v38-status"><span>${doc.template}</span><span>${stats.cut} CUT · ${stats.crease} CREASE · ${stats.perf} PERF · ${stats.glue} GLUE</span></div></main><aside class="v38-right">${inspectorMarkup()}${preflightMarkup()}</aside></div></div>`;bind()}
function commit(next,{selectNode=selectedNodeId,selectEdge=selectedEdgeId}={}){doc=next;selectedNodeId=selectNode;selectedEdgeId=selectEdge;report=null;persist();render()}
function selectedEdge(){return selectedEdgeId?edgeByIdV38(doc,selectedEdgeId):null}
function svgPoint(event){const svg=host?.querySelector('#v38Canvas');if(!svg)return{x:0,y:0};const p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;const matrix=svg.getScreenCTM();return matrix?p.matrixTransform(matrix.inverse()):{x:0,y:0}}
function bind(){
  host.querySelectorAll('[data-v38-node]').forEach(el=>{el.onclick=event=>{event.stopPropagation();selectedNodeId=el.dataset.v38Node;selectedEdgeId=null;render()};el.onpointerdown=event=>{event.stopPropagation();selectedNodeId=el.dataset.v38Node;selectedEdgeId=null;drag={kind:'node',id:selectedNodeId};try{el.setPointerCapture?.(event.pointerId)}catch{}}});
  host.querySelectorAll('[data-v38-edge]').forEach(el=>el.onclick=event=>{event.stopPropagation();selectedEdgeId=el.dataset.v38Edge;selectedNodeId=null;render()});
  host.querySelectorAll('[data-v38-control]').forEach(el=>el.onpointerdown=event=>{event.stopPropagation();drag={kind:'control',which:el.dataset.v38Control,edgeId:selectedEdgeId};try{el.setPointerCapture?.(event.pointerId)}catch{}});
  host.onpointerup=event=>{if(!drag)return;const current=drag;drag=null;const p=svgPoint(event);if(current.kind==='node'){commit(moveNodeV38(doc,current.id,{x:p.x,y:p.y}),{selectNode:current.id,selectEdge:null});return}if(current.kind==='control'){const edge=edgeByIdV38(doc,current.edgeId);if(!edge||edge.curve!=='cubic')return;const c1={...edge.c1},c2={...edge.c2};if(current.which==='c1')Object.assign(c1,{x:p.x,y:p.y});else Object.assign(c2,{x:p.x,y:p.y});commit(setCubicHandlesV38(doc,edge.id,{c1,c2}),{selectEdge:edge.id,selectNode:null})}};
  host.querySelector('[data-v38-action="close"]').onclick=closeCad;
  host.querySelector('[data-v38-action="preflight"]').onclick=()=>{report=runPreflightV38(state,{doc});render()};
  host.querySelector('[data-v38-action="insert-node"]').onclick=()=>{if(!selectedEdgeId)return;try{const result=insertNodeOnEdgeV38(doc,selectedEdgeId,.5);commit(result.doc,{selectNode:result.nodeId,selectEdge:null})}catch(error){alert(error.message)}};
  host.querySelector('[data-v38-action="delete-node"]').onclick=()=>{if(!selectedNodeId)return;try{commit(deleteNodeV38(doc,selectedNodeId),{selectNode:null,selectEdge:null})}catch(error){alert(error.message)}};
  host.querySelectorAll('[data-v38-line-type]').forEach(button=>button.onclick=()=>{if(selectedEdgeId)commit(setEdgeLineTypeV38(doc,selectedEdgeId,button.dataset.v38LineType),{selectEdge:selectedEdgeId,selectNode:null})});
  host.querySelectorAll('[data-v38-curve]').forEach(button=>button.onclick=()=>{if(selectedEdgeId)commit(setEdgeCurveV38(doc,selectedEdgeId,button.dataset.v38Curve),{selectEdge:selectedEdgeId,selectNode:null})});
  host.querySelectorAll('[data-v38-node-prop]').forEach(input=>input.onchange=()=>{const n=nodeByIdV38(doc,selectedNodeId);if(n)commit(moveNodeV38(doc,n.id,{x:input.dataset.v38NodeProp==='x'?num(input.value):n.x,y:input.dataset.v38NodeProp==='y'?num(input.value):n.y}),{selectNode:n.id,selectEdge:null})});
  host.querySelectorAll('[data-v38-handle]').forEach(input=>input.onchange=()=>{const e=selectedEdge();if(!e||e.curve!=='cubic')return;const c1={...e.c1},c2={...e.c2},key=input.dataset.v38Handle;if(key==='c1x')c1.x=num(input.value);if(key==='c1y')c1.y=num(input.value);if(key==='c2x')c2.x=num(input.value);if(key==='c2y')c2.y=num(input.value);commit(setCubicHandlesV38(doc,e.id,{c1,c2}),{selectEdge:e.id,selectNode:null})});
  host.querySelectorAll('[data-v38-arc]').forEach(input=>input.onchange=()=>{const e=selectedEdge();if(!e||e.curve!=='arc')return;const arc={...e.arc,[input.dataset.v38Arc]:Math.max(.001,num(input.value,1))};commit(setEdgeCurveV38(doc,e.id,'arc',arc),{selectEdge:e.id,selectNode:null})});
  for(const id of ['v38Bleed','v38Safe'])host.querySelector(`#${id}`).onchange=()=>{const bleed=num(host.querySelector('#v38Bleed').value,3),safe=num(host.querySelector('#v38Safe').value,5);commit(buildProductionZonesV38(doc,{bleed,safe}))};
  host.querySelectorAll('[data-v38-export]').forEach(button=>button.onclick=()=>{const kind=button.dataset.v38Export;if(kind==='svg')download('boxstudio-dieline-v38.svg',buildDielineSvgV38(doc),'image/svg+xml');if(kind==='dxf')download('boxstudio-dieline-v38.dxf',buildDxfV38(doc),'application/dxf');if(kind==='pdf')download('boxstudio-dieline-v38.pdf',buildDielinePdfV38(doc),'application/pdf')});
}
export function openDielineCadV38(){if(host)return;state=readState();doc=state.dielineV38?.schema==='boxstudio-dieline-v38'?clone(state.dielineV38):dielineDocumentFromStateV38(state);selectedNodeId=null;selectedEdgeId=null;report=null;drag=null;host=document.createElement('div');host.id='boxstudio-v38-cad';document.body.appendChild(host);persist();render()}
export function closeCad(){persist();host?.remove();host=null;drag=null;injectLauncher()}
function injectLauncher(){const toolbar=document.querySelector('.three-toolbar')||document.querySelector('.tabbar');if(!toolbar||document.querySelector('#v38OpenCad'))return;const button=document.createElement('button');button.id='v38OpenCad';button.className='primary';button.textContent='Dieline CAD';button.onclick=openDielineCadV38;toolbar.appendChild(button)}
const target=document.querySelector('#app')||document.body;observer=new MutationObserver(()=>injectLauncher());observer.observe(target,{childList:true,subtree:true});injectLauncher();
export function getDielineDocumentV38(){return doc?clone(doc):null}
export { buildDxfV38,buildDielineSvgV38,buildDielinePdfV38 };
