import { STORAGE_KEY, defaultState } from './model.js';
import { buildProductionContextV39, buildProductionPdfV39 } from './productionPdfV39.js';

const clone=v=>structuredClone(v);
let lastContext=null,observer=null;

function readState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return saved?{...clone(defaultState),...saved,structure:{...defaultState.structure,...(saved.structure||{})},variables:{...defaultState.variables,...(saved.variables||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function saveTopology(context){if(!context?.topology?.ok||!context?.topologyGate?.ok)return false;const current=readState(),reconciled=context.reconciled?.state||current,next={...current,...reconciled,structure:current.structure,dielineV38:clone(context.topology.doc),topologyV39:{schema:context.topology.schema,version:1,stats:clone(context.topology.stats),panelIdMap:clone(context.topology.panelIdMap),graph:clone(context.topology.graph),savedAt:new Date().toISOString()},savedAt:new Date().toISOString()};localStorage.setItem(STORAGE_KEY,JSON.stringify(next));return true}
function downloadPdf(bytes){const blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='boxstudio-v0.39-unified-production.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function counts(context){return{panels:context?.topology?.stats?.faces||0,folds:context?.topology?.stats?.foldTreeEdges||0,errors:context?.errors?.length||0,warnings:context?.warnings?.length||0}}
function statusText(context){const c=counts(context);return`V0.39 · ${c.panels} panels · ${c.folds} folds · ${c.errors} errors · ${c.warnings} warnings`}
function paintStatus(context){const c=counts(context),blocked=!context?.ok;document.body.dataset.v39Topology=blocked?'blocked':'pass';document.body.dataset.v39Panels=String(c.panels);document.body.dataset.v39Folds=String(c.folds);for(const el of document.querySelectorAll('[data-v39-status]')){el.textContent=statusText(context);el.classList.toggle('blocked',blocked);el.classList.toggle('pass',!blocked)}for(const button of document.querySelectorAll('[data-v39-full-pdf]'))button.disabled=blocked}

export function rebuildTopologyV39({persist=true}={}){const state=readState(),context=buildProductionContextV39(state,{doc:state.dielineV38||null});lastContext=context;if(persist)saveTopology(context);injectControls();paintStatus(context);return context}
export function buildFullProductionPdfV39({download=false}={}){const context=rebuildTopologyV39({persist:true});if(!context.ok){document.body.dataset.v39Pdf='blocked';return{ok:false,context,bytes:null}}const state=readState(),bytes=buildProductionPdfV39(state,{doc:state.dielineV38||context.topology.doc});document.body.dataset.v39Pdf='pass';document.body.dataset.v39PdfBytes=String(bytes.length);if(download)downloadPdf(bytes);return{ok:true,context,bytes}}

function button(id,text,handler,attrs=''){const b=document.createElement('button');b.id=id;b.textContent=text;if(attrs)b.setAttribute(attrs,'');b.onclick=handler;return b}
function ensureStatus(container){if(!container||container.querySelector('[data-v39-status]'))return;const status=document.createElement('span');status.dataset.v39Status='';status.className='v39-status';status.textContent=lastContext?statusText(lastContext):'V0.39 · topology not rebuilt';container.appendChild(status)}
function injectMain(){const toolbar=document.querySelector('.three-toolbar')||document.querySelector('.tabbar');if(!toolbar)return;if(!document.querySelector('#v39RebuildTopology'))toolbar.appendChild(button('v39RebuildTopology','Rebuild Topology',()=>rebuildTopologyV39({persist:true})));if(!document.querySelector('#v39FullProduction')){const b=button('v39FullProduction','Full Production PDF',()=>buildFullProductionPdfV39({download:true}));b.dataset.v39FullPdf='';toolbar.appendChild(b)}ensureStatus(toolbar)}
function injectCad(){const top=document.querySelector('#boxstudio-v38-cad .v38-top');if(top){if(!top.querySelector('#v39CadRebuild'))top.insertBefore(button('v39CadRebuild','Rebuild Panels',()=>rebuildTopologyV39({persist:true})),top.querySelector('[data-v38-action="close"]'));if(!top.querySelector('#v39CadFullPdf')){const b=button('v39CadFullPdf','Full Production PDF',()=>buildFullProductionPdfV39({download:true}));b.dataset.v39FullPdf='';top.insertBefore(b,top.querySelector('[data-v38-action="close"]'))}}const status=document.querySelector('#boxstudio-v38-cad .v38-status');ensureStatus(status)}
function injectControls(){injectMain();injectCad();if(lastContext)paintStatus(lastContext)}

const target=document.querySelector('#app')||document.body;observer=new MutationObserver(()=>injectControls());observer.observe(target,{childList:true,subtree:true});injectControls();
window.BoxStudioV39={rebuildTopology:rebuildTopologyV39,buildFullProductionPdf:buildFullProductionPdfV39,getLastContext:()=>lastContext?clone(lastContext):null};
