import { STORAGE_KEY, defaultState } from './model.js';
import { runPreflightV40 } from './preflightV40.js';
import { buildProductionPdfV40 } from './productionPdfV40.js';
import { accessBadgeV40, accessPolicyV40 } from './freeAccessV40.js';

const PRODUCT_VERSION='V0.40',clone=v=>structuredClone(v);let observer=null,lastReport=null,join='miter',injecting=false;
function readState(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return raw?{...clone(defaultState),...raw,structure:{...defaultState.structure,...(raw.structure||{})},variables:{...defaultState.variables,...(raw.variables||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function downloadPdf(bytes){const blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='boxstudio-v0.40-production.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function clickTab(tab){const editor=document.querySelector('[data-nav="editor"]');if(editor&&!document.querySelector(`[data-tab="${tab}"]`)){editor.click();setTimeout(()=>document.querySelector(`[data-tab="${tab}"]`)?.click(),0);return}document.querySelector(`[data-tab="${tab}"]`)?.click()}
function step(label,target,tab=null){const b=document.createElement('button');b.className='v40-step';b.textContent=label;b.onclick=()=>{if(target==='templates')document.querySelector('[data-nav="templates"]')?.click();else clickTab(tab)};return b}
function syncProductVersion(top){const small=top?.querySelector('.brand small');if(small&&small.textContent!==PRODUCT_VERSION)small.textContent=PRODUCT_VERSION;if(document.title!==`BoxStudio ${PRODUCT_VERSION}`)document.title=`BoxStudio ${PRODUCT_VERSION}`}
function injectFlow(){const app=document.querySelector('.app'),top=document.querySelector('.topbar');if(!app||!top)return;syncProductVersion(top);if(!top.querySelector('.v40-free-badge')){const badge=document.createElement('span');badge.className='v40-free-badge';badge.textContent=accessBadgeV40();const exp=top.querySelector('#quickExport');top.insertBefore(badge,exp||null)}document.querySelector('#v36OpenHosted')?.remove();if(!app.querySelector('.v40-flow')){const flow=document.createElement('div');flow.className='v40-flow';flow.append(step('1 选择盒型','templates'),step('2 尺寸 / 材料','editor','Structure'),step('3 平面设计','editor','Design'),step('4 3D 检查','editor','3D'),step('5 Preflight','editor','Preflight'),step('6 导出','editor','Export'));top.insertAdjacentElement('afterend',flow)}}
function polygon(points,cls,panelId){const el=document.createElementNS('http://www.w3.org/2000/svg','polygon');el.setAttribute('points',points.map(p=>`${p[0]},${p[1]}`).join(' '));el.setAttribute('class',`v40-zone ${cls}`);el.dataset.panelId=panelId;return el}
function paintZones(report){const svg=document.querySelector('#v38Canvas');if(!svg||!report)return;svg.querySelectorAll('.v40-zone').forEach(x=>x.remove());const anchor=svg.querySelector('.v38-sheet');for(const z of report.zones?.bleed||[])svg.insertBefore(polygon(z.points,'bleed',z.panelId),anchor?.nextSibling||null);for(const z of report.zones?.safe||[])svg.insertBefore(polygon(z.points,'safe',z.panelId),anchor?.nextSibling||null)}
function statusText(report){if(!report)return'Offsets not generated';const s=report.summary;return`${report.ok?'PASS':'BLOCKED'} · ${s.panels} panels · ${s.bleedZones} bleed · ${s.safeZones} safe · ${s.errors} errors · ${s.warnings} warnings`}
function runOffsets(){const state=readState(),doc=state.dielineV38||null;lastReport=runPreflightV40(state,{doc,join});document.body.dataset.v40Production=lastReport.ok?'pass':'blocked';paintZones(lastReport);updateCadStatus();return lastReport}
function updateCadStatus(){const el=document.querySelector('[data-v40-offset-status]');if(el)el.textContent=statusText(lastReport)}
function makeButton(id,text,fn){const b=document.createElement('button');b.id=id;b.textContent=text;b.onclick=fn;return b}
function injectCad(){const host=document.querySelector('#boxstudio-v38-cad');if(!host)return;host.classList.add('v40-active');const top=host.querySelector('.v38-top'),left=host.querySelector('.v38-left');if(top&&!top.querySelector('#v40ProductionPreflight')){const close=top.querySelector('[data-v38-action="close"]');top.insertBefore(makeButton('v40ProductionPreflight','Production Preflight',()=>runOffsets()),close);top.insertBefore(makeButton('v40ProductionPdf','Full Production PDF',()=>{const state=readState(),report=runOffsets();if(!report.ok){alert(`Production blocked: ${report.errors.map(x=>x.code).slice(0,8).join(', ')}`);return}downloadPdf(buildProductionPdfV40(state,{doc:report.dieline,join}))}),close)}if(left&&!left.querySelector('.v40-offset-tools')){const box=document.createElement('section');box.className='v40-offset-tools';box.innerHTML=`<h3>Production Offset</h3><label>Corner join<select id="v40Join"><option value="miter">Miter</option><option value="round">Round</option><option value="bevel">Bevel</option></select></label><button id="v40GenerateOffsets" class="primary">Generate Bleed / Safe</button><p data-v40-offset-status>Offsets not generated</p><small>All users can use production offsets and exports for free. No approval step.</small>`;left.appendChild(box);box.querySelector('#v40Join').value=join;box.querySelector('#v40Join').onchange=e=>{join=e.target.value;runOffsets()};box.querySelector('#v40GenerateOffsets').onclick=runOffsets}if(lastReport&&!host.querySelector('.v40-zone'))paintZones(lastReport);if(lastReport)updateCadStatus()}
function injectFreeNotice(){const page=document.querySelector('.page-head');if(!page||page.querySelector('.v40-public-note'))return;const note=document.createElement('div');note.className='v40-public-note';note.innerHTML='<b>Free for everyone</b><span>Templates, 2D, Dieline CAD, shipping marks, 3D, Preflight and production export do not require login or approval.</span>';page.appendChild(note)}
function inject(){if(injecting)return;injecting=true;try{injectFlow();injectCad();injectFreeNotice();document.body.dataset.v40Access='free-public'}finally{injecting=false}}
function relevantMutation(records){for(const record of records)for(const node of record.addedNodes||[]){if(node.nodeType!==1)continue;const el=node;if(el.id==='boxstudio-v38-cad'||el.matches?.('.app')||el.querySelector?.('#boxstudio-v38-cad,.app'))return true}return false}
observer=new MutationObserver(records=>{if(relevantMutation(records))inject()});observer.observe(document.body,{childList:true,subtree:true});inject();
window.BoxStudioV40={accessPolicy:()=>accessPolicyV40(),runOffsets,buildProductionPdf:()=>{const state=readState(),report=runOffsets();if(!report.ok)return{ok:false,report,bytes:null};const bytes=buildProductionPdfV40(state,{doc:report.dieline,join});return{ok:true,report,bytes}},getLastReport:()=>lastReport?clone(lastReport):null};
