import { STORAGE_KEY, defaultState } from './model.js';
import { closeCad, openDielineCadV38, getDielineDocumentV38 } from './v38Ui.js';
import { applyLiveContinuityV45, setCubicHandleLengthV45, setCircularArcRadiusV45, curveDimensionDiagnosticsV45, cornerOperationEligibilityV45, applyCornerOperationV45 } from './curveConstraintsV45.js';
import { runPreflightV45 } from './preflightV45.js';

const VERSION='V0.45',clone=v=>structuredClone(v),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let observer=null,queued=false,pendingLiveEdge=null,applying=false,liveTimer=null;
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,structure:{...defaultState.structure,...(p.structure||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeDoc(doc){const state=readState();state.dielineV38=doc;state.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function click(el){el?.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}))}
function selectedEdgeId(){return document.querySelector('#boxstudio-v38-cad .v38-edge.selected[data-v38-edge]')?.dataset.v38Edge||null}
function selectedNodeId(){return document.querySelector('#boxstudio-v38-cad .v38-node.selected[data-v38-node]')?.dataset.v38Node||null}
function findInspector(title){return[...document.querySelectorAll('#boxstudio-v38-cad .v38-right section')].find(s=>s.querySelector('.v38-section-head h3')?.textContent===title)||null}
function restoreSelection({edgeId=null,nodeId=null}={}){const cad=document.querySelector('#boxstudio-v38-cad');if(!cad)return false;const target=edgeId?cad.querySelector(`[data-v38-edge="${CSS.escape(edgeId)}"]`):nodeId?cad.querySelector(`[data-v38-node="${CSS.escape(nodeId)}"]`):null;if(!target)return false;click(target);return true}
function reopen(doc,selection={}){applying=true;closeCad();writeDoc(doc);openDielineCadV38();restoreSelection(selection)||queueMicrotask(()=>restoreSelection(selection));queueMicrotask(()=>{applying=false})}
function sameDoc(a,b){try{return JSON.stringify(a)===JSON.stringify(b)}catch{return false}}

function applyLive(edgeId){if(applying||!edgeId)return;const doc=getDielineDocumentV38();if(!doc)return;try{const result=applyLiveContinuityV45(doc,edgeId);if(result.applied.length&& !sameDoc(result.doc,doc))reopen(result.doc,{edgeId})}catch(error){console.warn('[V0.45 live continuity]',error)}}
function scheduleLive(edgeId){if(!edgeId)return;if(liveTimer)clearTimeout(liveTimer);liveTimer=setTimeout(()=>{liveTimer=null;applyLive(edgeId)},0)}

function showPreflight(){
  document.querySelector('#boxstudio-v45-preflight')?.remove();const state=readState(),doc=getDielineDocumentV38(),report=runPreflightV45(state,{doc}),host=document.createElement('div');host.id='boxstudio-v45-preflight';host.innerHTML=`<div class="v45-modal"><header><div><b>V0.45 Curve Constraint Preflight</b><span>${report.ok?'PASS':'BLOCKED'} · ${report.summary.errors} errors · ${report.summary.warnings} warnings</span></div><button data-v45-close>×</button></header><div class="v45-preflight-list">${report.checks.filter(x=>x.severity!=='pass').slice(0,40).map(x=>`<div class="${x.severity}"><b>${esc(x.code)}</b><span>${esc(x.detail||x.title)}</span></div>`).join('')||'<div class="pass"><b>PASS</b><span>No V0.45 curve-constraint blockers.</span></div>'}</div><footer>Fillets: ${report.summary.v45Fillets||0} · Chamfers: ${report.summary.v45Chamfers||0}</footer></div>`;document.body.appendChild(host);host.querySelector('[data-v45-close]').onclick=()=>host.remove();
}

function decorateTop(cad){const brand=cad.querySelector('.v38-brand span');if(brand&&!brand.dataset.v45){brand.dataset.v45='true';brand.textContent='Professional Dieline CAD · V0.45 Live Constraints'}const top=cad.querySelector('.v38-top');if(top&&!top.querySelector('[data-v45-preflight]')){const button=document.createElement('button');button.dataset.v45Preflight='';button.textContent='Constraint Preflight';button.onclick=showPreflight;const close=top.querySelector('[data-v38-action="close"]');top.insertBefore(button,close)}}

function decorateEdge(){const id=selectedEdgeId(),section=findInspector('Edge');if(!id||!section||section.querySelector('.v45-dimensions'))return;let d;try{d=curveDimensionDiagnosticsV45(getDielineDocumentV38(),id)}catch{return}const box=document.createElement('div');box.className='v45-dimensions';let controls='';if(d.curve==='cubic')controls=`<div class="v45-grid"><label>C1 handle<input data-v45-handle-length="c1" type="number" min="0.001" step="0.1" value="${d.c1Length.toFixed(3)}"><em>mm</em></label><label>C2 handle<input data-v45-handle-length="c2" type="number" min="0.001" step="0.1" value="${d.c2Length.toFixed(3)}"><em>mm</em></label></div>`;if(d.curve==='arc'&&d.circular)controls=`<label class="v45-radius">Radius<input data-v45-radius type="number" min="0.001" step="0.1" value="${d.rx.toFixed(3)}"><em>mm</em></label>`;box.innerHTML=`<div class="v45-head"><b>Dimensions & Constraints</b><span>path ${d.pathLength.toFixed(3)} mm · chord ${d.chordLength.toFixed(3)} mm</span></div>${controls}<small>Dimension edits preserve the native curve. Stored G1/C1/G2 continuity is automatically re-solved.</small>`;section.appendChild(box);
  box.querySelectorAll('[data-v45-handle-length]').forEach(input=>input.onchange=()=>{try{const next=setCubicHandleLengthV45(getDielineDocumentV38(),id,input.dataset.v45HandleLength,Number(input.value));reopen(next,{edgeId:id})}catch(error){alert(error.message)}});const radius=box.querySelector('[data-v45-radius]');if(radius)radius.onchange=()=>{try{const next=setCircularArcRadiusV45(getDielineDocumentV38(),id,Number(radius.value));reopen(next,{edgeId:id})}catch(error){alert(error.message)}}
}

function decorateNode(){const id=selectedNodeId(),section=findInspector('Node');if(!id||!section||section.querySelector('.v45-corner-tools'))return;const eligibility=cornerOperationEligibilityV45(getDielineDocumentV38(),id);if(!eligibility.ok)return;const box=document.createElement('div');box.className='v45-corner-tools';box.innerHTML=`<div class="v45-head"><b>Corner Tool</b><span>${eligibility.angleDeg.toFixed(2)}° · native topology</span></div><div class="v45-corner-row"><select data-v45-corner-mode><option value="fillet">Fillet / 圆角</option><option value="chamfer">Chamfer / 倒角</option></select><label><input data-v45-corner-value type="number" min="0.1" step="0.1" value="5"><em>mm</em></label><button data-v45-corner-apply>Apply</button></div><small>Fillet inserts a real CUT Arc; Chamfer inserts a real CUT Line. Both trim the two source edges.</small>`;section.appendChild(box);box.querySelector('[data-v45-corner-apply]').onclick=()=>{const mode=box.querySelector('[data-v45-corner-mode]').value,valueMm=Number(box.querySelector('[data-v45-corner-value]').value);try{const result=applyCornerOperationV45(getDielineDocumentV38(),id,{mode,valueMm});reopen(result.doc,{edgeId:result.connectorEdgeId})}catch(error){alert(error.message)}}
}

function decorate(){document.title='BoxStudio V0.45';document.body.dataset.v45LiveConstraints='true';const cad=document.querySelector('#boxstudio-v38-cad');if(!cad)return;decorateTop(cad);decorateEdge();decorateNode()}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;decorate()})}
observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true});decorate();

document.addEventListener('pointerdown',event=>{if(applying)return;const control=event.target?.closest?.('#boxstudio-v38-cad [data-v38-control]');if(control)pendingLiveEdge=selectedEdgeId()},true);
document.addEventListener('pointerup',()=>{const edgeId=pendingLiveEdge;pendingLiveEdge=null;if(edgeId)scheduleLive(edgeId)});
document.addEventListener('change',event=>{if(applying)return;if(event.target?.matches?.('#boxstudio-v38-cad [data-v38-handle]')){const edgeId=selectedEdgeId();if(edgeId)scheduleLive(edgeId)}});

window.BoxStudioV45={version:VERSION,liveContinuity:true,filletChamfer:true,dimensionConstraints:true,applyLiveContinuity:applyLiveContinuityV45,applyCornerOperation:applyCornerOperationV45,setCubicHandleLength:setCubicHandleLengthV45,setCircularArcRadius:setCircularArcRadiusV45,curveDimensions:curveDimensionDiagnosticsV45,runPreflight:runPreflightV45};