import { STORAGE_KEY, defaultState } from './model.js';
import { closeCad, openDielineCadV38, getDielineDocumentV38 } from './v38Ui.js';
import { cornerOperationEligibilityV45 } from './curveConstraintsV45.js';
import { mixedContinuityEligibilityV46, mixedContinuityDiagnosticsV46, setMixedContinuityV46, clearMixedContinuityV46, applyLiveMixedContinuityV46, applyCornerFeatureV46, applyCornerBatchV46, removeCornerFeatureV46, switchCornerFeatureV46, updateCornerFeatureV46, setFilletRadiusV46, createEqualRadiusConstraintV46 } from './curveConstraintsV46.js';
import { runPreflightV46 } from './preflightV46.js';

const VERSION='V0.46',clone=v=>structuredClone(v),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let observer=null,queued=false,applying=false,pendingLiveEdge=null,liveTimer=null;
const batchNodeIds=new Set(),radiusEdgeIds=new Set();
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,structure:{...defaultState.structure,...(p.structure||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeDoc(doc){const state=readState();state.dielineV38=doc;state.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function click(el){el?.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}))}
function selectedEdgeId(){return document.querySelector('#boxstudio-v38-cad .v38-edge.selected[data-v38-edge]')?.dataset.v38Edge||null}
function selectedNodeId(){return document.querySelector('#boxstudio-v38-cad .v38-node.selected[data-v38-node]')?.dataset.v38Node||null}
function findInspector(title){return[...document.querySelectorAll('#boxstudio-v38-cad .v38-right section')].find(s=>s.querySelector('.v38-section-head h3')?.textContent===title)||null}
function restoreSelection({edgeId=null,nodeId=null}={}){const cad=document.querySelector('#boxstudio-v38-cad');if(!cad)return false;const target=edgeId?cad.querySelector(`[data-v38-edge="${CSS.escape(edgeId)}"]`):nodeId?cad.querySelector(`[data-v38-node="${CSS.escape(nodeId)}"]`):null;if(!target)return false;click(target);return true}
function markMultiSelection(){const cad=document.querySelector('#boxstudio-v38-cad');if(!cad)return;cad.querySelectorAll('.v38-node[data-v38-node]').forEach(el=>el.classList.toggle('v46-batch-selected',batchNodeIds.has(el.dataset.v38Node)));cad.querySelectorAll('.v38-edge[data-v38-edge]').forEach(el=>el.classList.toggle('v46-radius-selected',radiusEdgeIds.has(el.dataset.v38Edge)))}
function reopen(doc,selection={}){applying=true;closeCad();writeDoc(doc);openDielineCadV38();restoreSelection(selection)||queueMicrotask(()=>restoreSelection(selection));setTimeout(()=>{markMultiSelection();applying=false},0)}
function sameDoc(a,b){try{return JSON.stringify(a)===JSON.stringify(b)}catch{return false}}
function currentDoc(){const persisted=readState().dielineV38;return persisted?.schema==='boxstudio-dieline-v38'?persisted:getDielineDocumentV38()}

function applyMixedLive(edgeId){if(applying||!edgeId)return;const doc=currentDoc();if(!doc)return;try{const result=applyLiveMixedContinuityV46(doc,edgeId);if(result.applied.length&&!sameDoc(result.doc,doc))reopen(result.doc,{edgeId})}catch(error){console.warn('[V0.46 mixed live]',error)}}
function scheduleMixedLive(edgeId){if(!edgeId||applying)return;if(liveTimer)clearTimeout(liveTimer);liveTimer=setTimeout(()=>{liveTimer=null;applyMixedLive(edgeId)},0)}

function showPreflight(){
  document.querySelector('#boxstudio-v46-preflight')?.remove();const state=readState(),doc=getDielineDocumentV38(),report=runPreflightV46(state,{doc}),host=document.createElement('div');host.id='boxstudio-v46-preflight';host.innerHTML=`<div class="v46-modal"><header><div><b>V0.46 Advanced Constraint + 3D Consistency</b><span>${report.ok?'PASS':'BLOCKED'} · ${report.summary.errors} errors · ${report.summary.warnings} warnings</span></div><button data-v46-close>×</button></header><div class="v46-preflight-list">${report.checks.filter(x=>x.severity!=='pass').slice(0,60).map(x=>`<div class="${x.severity}"><b>${esc(x.code)}</b><span>${esc(x.detail||x.title)}</span></div>`).join('')||'<div class="pass"><b>PASS</b><span>2D CAD, advanced constraints, Topology and 3D FoldGraph are consistent.</span></div>'}</div><footer>Mixed G1: ${report.summary.v46Mixed||0} · Corner features: ${report.summary.v46Corners||0} · Equal-R groups: ${report.summary.v46EqualRadiusGroups||0} · 3D panels: ${report.acceptance?.summary?.threePanels||0}</footer></div>`;document.body.appendChild(host);host.querySelector('[data-v46-close]').onclick=()=>host.remove();
}
function decorateTop(cad){const brand=cad.querySelector('.v38-brand span');if(brand&&!brand.dataset.v46){brand.dataset.v46='true';brand.textContent='Professional Dieline CAD · V0.46 Advanced Constraints'}const top=cad.querySelector('.v38-top');if(top&&!top.querySelector('[data-v46-preflight]')){const button=document.createElement('button');button.dataset.v46Preflight='';button.textContent='V0.46 Acceptance';button.onclick=showPreflight;const close=top.querySelector('[data-v38-action="close"]');top.insertBefore(button,close)}}

function edgeLabel(edge){return`${edge.id} · ${(edge.curve||'line').toUpperCase()}`}
function decorateMixedNode(id,section,doc){const eligibility=mixedContinuityEligibilityV46(doc,id);if(!eligibility.ok)return;let diag;try{diag=mixedContinuityDiagnosticsV46(doc,id)}catch{return}const old=section.querySelector('.v46-mixed-tools');if(old)return;const stored=eligibility.node.continuityV46?.mode==='g1',box=document.createElement('div');box.className='v46-mixed-tools';box.innerHTML=`<div class="v46-head"><b>Mixed-Curve G1</b><span>${esc(eligibility.key)} · error ${diag.tangentErrorDeg.toFixed(4)}°</span></div><div class="v46-row"><select data-v46-driver>${eligibility.edges.map(e=>`<option value="${esc(e.id)}" ${eligibility.node.continuityV46?.driverEdgeId===e.id?'selected':''}>Driver: ${esc(edgeLabel(e))}</option>`).join('')}</select><button data-v46-g1>${stored?'Re-solve G1':'Apply G1'}</button>${stored?'<button class="subtle" data-v46-g1-clear>Clear</button>':''}</div><small>Line↔Arc solves a tangent circle; Arc↔Cubic and Cubic↔Line preserve the driver and re-solve the opposite tangent entity.</small>`;section.appendChild(box);box.querySelector('[data-v46-g1]').onclick=()=>{try{const result=setMixedContinuityV46(getDielineDocumentV38(),id,'g1',{driverEdgeId:box.querySelector('[data-v46-driver]').value});reopen(result.doc,{nodeId:id})}catch(error){alert(error.message)}};box.querySelector('[data-v46-g1-clear]')?.addEventListener('click',()=>reopen(clearMixedContinuityV46(getDielineDocumentV38(),id),{nodeId:id}))}

function activeBatchNodes(current){const ids=new Set(batchNodeIds);if(current)ids.add(current);return[...ids]}
function decorateCornerNode(id,section,doc){const eligibility=cornerOperationEligibilityV45(doc,id);if(!eligibility.ok||section.querySelector('.v46-corner-tools'))return;const box=document.createElement('div');box.className='v46-corner-tools';const selected=activeBatchNodes(id);box.innerHTML=`<div class="v46-head"><b>Corner Feature</b><span>${eligibility.angleDeg.toFixed(2)}° · composable provenance</span></div><div class="v46-row"><select data-v46-corner-mode><option value="fillet">Fillet / 圆角</option><option value="chamfer">Chamfer / 倒角</option></select><label><input data-v46-corner-value type="number" min="0.1" step="0.1" value="5"><em>mm</em></label><button data-v46-corner-apply>Apply</button></div><div class="v46-batch"><span>Shift-click nodes for batch · ${selected.length} selected</span><button data-v46-corner-batch ${selected.length<2?'disabled':''}>Apply to ${selected.length}</button><button class="subtle" data-v46-batch-clear>Clear</button></div><small>Batch operation is atomic by default and supports adjacent corners without corrupting neighboring restore provenance.</small>`;section.appendChild(box);const values=()=>({mode:box.querySelector('[data-v46-corner-mode]').value,valueMm:Number(box.querySelector('[data-v46-corner-value]').value)});box.querySelector('[data-v46-corner-apply]').onclick=()=>{try{const result=applyCornerFeatureV46(getDielineDocumentV38(),id,values());reopen(result.doc,{edgeId:result.connectorEdgeId})}catch(error){alert(error.message)}};box.querySelector('[data-v46-corner-batch]').onclick=()=>{try{const result=applyCornerBatchV46(getDielineDocumentV38(),activeBatchNodes(id),values());batchNodeIds.clear();reopen(result.doc,{edgeId:result.applied[0]?.connectorEdgeId||null})}catch(error){alert(error.message)}};box.querySelector('[data-v46-batch-clear]').onclick=()=>{batchNodeIds.clear();markMultiSelection();box.remove();decorateCornerNode(id,section,currentDoc())}}
function decorateNode(){const id=selectedNodeId(),section=findInspector('Node');if(!id||!section)return;const legacy=section.querySelector('.v45-corner-tools');if(legacy)legacy.style.display='none';const doc=getDielineDocumentV38();decorateMixedNode(id,section,doc);decorateCornerNode(id,section,doc)}

function selectedFilletIds(current){const doc=getDielineDocumentV38(),ids=new Set(radiusEdgeIds);if(current)ids.add(current);return[...ids].filter(id=>doc.edges?.some(e=>e.id===id&&e.v45Corner?.mode==='fillet'))}
function decorateCornerEdge(id,section,doc,edge){if(section.querySelector('.v46-feature-tools'))return;const legacy=section.querySelector('.v45-dimensions');if(legacy)legacy.style.display='none';const feature=edge.v45Corner,group=(doc.constraintsV46?.equalRadiusGroups||[]).find(g=>g.edgeIds?.includes(id)),selected=feature.mode==='fillet'?selectedFilletIds(id):[];const box=document.createElement('div');box.className='v46-feature-tools';box.innerHTML=`<div class="v46-head"><b>Corner Feature</b><span>${esc(feature.mode)} · ${Number(feature.valueMm).toFixed(3)} mm${group?` · ${esc(group.id)}`:''}</span></div><div class="v46-row"><select data-v46-feature-mode><option value="fillet" ${feature.mode==='fillet'?'selected':''}>Fillet / 圆角</option><option value="chamfer" ${feature.mode==='chamfer'?'selected':''}>Chamfer / 倒角</option></select><label><input data-v46-feature-value type="number" min="0.1" step="0.1" value="${Number(feature.valueMm).toFixed(3)}"><em>mm</em></label><button data-v46-feature-update>Update</button></div><div class="v46-row"><button class="danger" data-v46-feature-remove>Restore / Remove</button>${feature.mode==='fillet'?`<button data-v46-equal-radius ${selected.length<2?'disabled':''}>Equal radius · ${selected.length}</button>`:''}</div>${feature.mode==='fillet'?`<small>Shift-click Fillet edges to build an equal-radius group. Drag the cyan R handle directly on the canvas to change radius${group?' for the whole group':''}.</small>`:'<small>Switching back to Fillet restores native Arc topology without losing the neighboring Corner features.</small>'}`;section.appendChild(box);box.querySelector('[data-v46-feature-update]').onclick=()=>{const mode=box.querySelector('[data-v46-feature-mode]').value,valueMm=Number(box.querySelector('[data-v46-feature-value]').value);try{const result=mode==='fillet'&&feature.mode==='fillet'?setFilletRadiusV46(getDielineDocumentV38(),id,valueMm,{propagateEqual:true}):updateCornerFeatureV46(getDielineDocumentV38(),id,{mode,valueMm});reopen(result.doc,{edgeId:result.connectorEdgeId||result.edgeId||id})}catch(error){alert(error.message)}};box.querySelector('[data-v46-feature-remove]').onclick=()=>{try{const result=removeCornerFeatureV46(getDielineDocumentV38(),id);radiusEdgeIds.delete(id);reopen(result.doc,{nodeId:result.nodeId})}catch(error){alert(error.message)}};box.querySelector('[data-v46-equal-radius]')?.addEventListener('click',()=>{try{const result=createEqualRadiusConstraintV46(getDielineDocumentV38(),selectedFilletIds(id),{radiusMm:Number(box.querySelector('[data-v46-feature-value]').value)});radiusEdgeIds.clear();reopen(result.doc,{edgeId:result.edgeIds[0]})}catch(error){alert(error.message)}})}

function clientToSvg(svg,x,y){const p=svg.createSVGPoint();p.x=x;p.y=y;const m=svg.getScreenCTM();return m?p.matrixTransform(m.inverse()):{x,y}}
function decorateRadiusHandle(id,doc,edge){const existing=document.querySelector('#boxstudio-v38-cad .v46-radius-overlay');if(existing?.dataset.v46RadiusOverlay===id)return;existing?.remove();if(edge.v45Corner?.mode!=='fillet'||!edge.v45Corner.center||!edge.v45Corner.source?.node)return;const path=document.querySelector(`#boxstudio-v38-cad .v38-edge[data-v38-edge="${CSS.escape(id)}"]`),svg=path?.ownerSVGElement;if(!svg)return;const center=edge.v45Corner.center,corner=edge.v45Corner.source.node,radius=Math.max(.001,Number(edge.v45Corner.valueMm)||1),cd=Math.hypot(center.x-corner.x,center.y-corner.y);if(cd<1e-6)return;const ux=(center.x-corner.x)/cd,uy=(center.y-corner.y)/cd,sinHalf=Math.max(.02,Math.min(1,radius/cd)),ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g'),circle=document.createElementNS(ns,'circle'),label=document.createElementNS(ns,'text');g.classList.add('v46-radius-overlay');g.dataset.v46RadiusOverlay=id;circle.setAttribute('cx',center.x);circle.setAttribute('cy',center.y);circle.setAttribute('r','2.4');circle.dataset.v46RadiusHandle=id;label.setAttribute('x',center.x+3.5);label.setAttribute('y',center.y-3.5);label.textContent=`R ${radius.toFixed(2)}`;g.append(circle,label);svg.appendChild(g);let drag=null;circle.addEventListener('pointerdown',event=>{event.preventDefault();event.stopPropagation();circle.setPointerCapture(event.pointerId);drag={start:clientToSvg(svg,event.clientX,event.clientY),radius,center:{...center},target:radius}});circle.addEventListener('pointermove',event=>{if(!drag)return;const p=clientToSvg(svg,event.clientX,event.clientY),projection=(p.x-drag.start.x)*ux+(p.y-drag.start.y)*uy,target=Math.max(.1,drag.radius+projection*sinHalf),dc=(target-drag.radius)/sinHalf;drag.target=target;circle.setAttribute('cx',drag.center.x+ux*dc);circle.setAttribute('cy',drag.center.y+uy*dc);label.setAttribute('x',drag.center.x+ux*dc+3.5);label.setAttribute('y',drag.center.y+uy*dc-3.5);label.textContent=`R ${target.toFixed(2)}`});circle.addEventListener('pointerup',event=>{if(!drag)return;const target=drag.target;drag=null;try{const result=setFilletRadiusV46(getDielineDocumentV38(),id,target,{propagateEqual:true});reopen(result.doc,{edgeId:result.edgeId||id})}catch(error){alert(error.message)}})}
function decorateEdge(){const id=selectedEdgeId(),section=findInspector('Edge');if(!id||!section){document.querySelector('#boxstudio-v38-cad .v46-radius-overlay')?.remove();return;}const doc=getDielineDocumentV38(),edge=doc.edges?.find(e=>e.id===id);if(!edge){document.querySelector('#boxstudio-v38-cad .v46-radius-overlay')?.remove();return;}if(edge.v45Corner){decorateCornerEdge(id,section,doc,edge);decorateRadiusHandle(id,doc,edge)}else document.querySelector('#boxstudio-v38-cad .v46-radius-overlay')?.remove()}

function decorate(){document.title='BoxStudio V0.46';document.body.dataset.v46AdvancedConstraints='true';const cad=document.querySelector('#boxstudio-v38-cad');if(!cad)return;decorateTop(cad);decorateEdge();decorateNode();markMultiSelection();const edgeId=selectedEdgeId();if(edgeId)scheduleMixedLive(edgeId)}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;decorate()})}

window.BoxStudioV46={version:VERSION,mixedCurveG1:true,cornerSwitch:true,cornerRestoreRemove:true,batchCorners:true,equalRadius:true,canvasRadiusDrag:true,cadTopology3dAcceptance:true,setMixedContinuity:setMixedContinuityV46,applyCornerFeature:applyCornerFeatureV46,applyCornerBatch:applyCornerBatchV46,removeCornerFeature:removeCornerFeatureV46,switchCornerFeature:switchCornerFeatureV46,setFilletRadius:setFilletRadiusV46,createEqualRadiusConstraint:createEqualRadiusConstraintV46,runPreflight:runPreflightV46};
observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true});decorate();

document.addEventListener('pointerdown',event=>{if(applying)return;const node=event.target?.closest?.('#boxstudio-v38-cad .v38-node[data-v38-node]'),edge=event.target?.closest?.('#boxstudio-v38-cad .v38-edge[data-v38-edge]');if(event.shiftKey&&node){const id=node.dataset.v38Node;batchNodeIds.has(id)?batchNodeIds.delete(id):batchNodeIds.add(id);setTimeout(markMultiSelection,0)}if(event.shiftKey&&edge){const id=edge.dataset.v38Edge,doc=getDielineDocumentV38(),record=doc.edges?.find(e=>e.id===id);if(record?.v45Corner?.mode==='fillet'){radiusEdgeIds.has(id)?radiusEdgeIds.delete(id):radiusEdgeIds.add(id);setTimeout(markMultiSelection,0)}}const control=event.target?.closest?.('#boxstudio-v38-cad [data-v38-control]');if(control)pendingLiveEdge=selectedEdgeId()},true);
document.addEventListener('pointerup',()=>{const id=pendingLiveEdge;pendingLiveEdge=null;if(id)scheduleMixedLive(id)});
document.addEventListener('change',event=>{if(applying)return;if(event.target?.matches?.('#boxstudio-v38-cad [data-v38-handle]')){const id=selectedEdgeId();if(id)scheduleMixedLive(id)}});
