import { STORAGE_KEY, defaultState } from './model.js';
import { V47_FREE_POLICY, V47_WORKFLOW, V47_TEMPLATE_FILTERS, V47_MARK_QUICK_ACTIONS, searchFreeTemplatesV47, dimensionSummaryV47, templateCategoryV47 } from './freeStudioV47.js';
import { readProjectLibraryV47, saveProjectSnapshotV47, renameProjectSnapshotV47, duplicateProjectSnapshotV47, loadProjectSnapshotV47, newLocalProjectV47 } from './projectWorkspaceV47.js';
import { openReview as openLinkedReviewV35 } from './v35Ui.js';

const clone=v=>structuredClone(v);
let observer=null,queued=false,templateQuery='',templateCategory='all';
function readState(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return parsed?{...clone(defaultState),...parsed,structure:{...defaultState.structure,...(parsed.structure||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(next){next.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(next))}
function reloadWithState(next){writeState(next);location.reload()}
function activePage(){return document.querySelector('.nav [data-nav].active')?.dataset.nav||null}
function activeTab(){return document.querySelector('.tabbar [data-tab].active')?.dataset.tab||null}
function clickNav(id){document.querySelector(`[data-nav="${CSS.escape(id)}"]`)?.click()}
function clickTab(id){document.querySelector(`[data-tab="${CSS.escape(id)}"]`)?.click()}
function clickTool(id){document.querySelector(`[data-tool="${CSS.escape(id)}"]`)?.click()}
function el(tag,cls,html=''){const n=document.createElement(tag);if(cls)n.className=cls;n.innerHTML=html;return n}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setText(node,text){if(node&&node.textContent!==text)node.textContent=text}

function openProfessional2D(){const existing=document.querySelector('#v33OpenProfessional');if(existing){existing.click();return}if(activeTab()!=='Design')clickTab('Design');setTimeout(()=>document.querySelector('#v33OpenProfessional')?.click(),40)}
function projectMenuHtml(state){const projects=readProjectLibraryV47().slice(0,8);return`<button class="v47-project-button" data-v47-project-toggle><span>${esc(state.projectName||'Untitled Packaging')}</span><small>本地自动保存</small><b>⌄</b></button><div class="v47-project-menu" data-v47-project-menu hidden><div class="v47-project-actions"><button data-v47-project-action="new">新建项目</button><button data-v47-project-action="save">保存快照</button><button data-v47-project-action="rename">重命名</button><button data-v47-project-action="duplicate">另存为</button></div><div class="v47-project-list-head"><b>本地项目</b><span>${projects.length}</span></div><div class="v47-project-list">${projects.map(p=>`<button data-v47-open-project="${esc(p.id)}"><b>${esc(p.name)}</b><span>${esc(p.template)} · ${new Date(p.updatedAt).toLocaleString()}</span></button>`).join('')||'<div class="v47-project-empty">还没有手动保存的项目快照。</div>'}</div><div class="v47-project-foot">浏览器本地保存 · 无账号 · 无云端付费依赖</div></div>`}
function bindProjectMenu(host){
  const menu=host.querySelector('[data-v47-project-menu]');host.querySelector('[data-v47-project-toggle]').onclick=e=>{e.stopPropagation();menu.hidden=!menu.hidden};
  host.querySelectorAll('[data-v47-project-action]').forEach(button=>button.onclick=()=>{const action=button.dataset.v47ProjectAction,state=readState();if(action==='save'){const record=saveProjectSnapshotV47(state,{name:state.projectName});state.projectId=record.id;state.projectName=record.name;writeState(state);setText(host.querySelector('.v47-project-button span'),record.name);menu.hidden=true;return}if(action==='new'){const name=prompt('新项目名称','Untitled Packaging');if(name!==null)reloadWithState(newLocalProjectV47(defaultState,{name}));return}if(action==='rename'){const current=state.projectId?saveProjectSnapshotV47(state,{id:state.projectId,name:state.projectName}):saveProjectSnapshotV47(state,{name:state.projectName});const name=prompt('项目名称',current.name);if(name!==null){const renamed=renameProjectSnapshotV47(current.id,name);reloadWithState(renamed.state)}return}if(action==='duplicate'){const current=state.projectId?saveProjectSnapshotV47(state,{id:state.projectId,name:state.projectName}):saveProjectSnapshotV47(state,{name:state.projectName});const name=prompt('另存为',`${current.name} Copy`);if(name!==null)reloadWithState(duplicateProjectSnapshotV47(current.id,{name}).state)}});
  host.querySelectorAll('[data-v47-open-project]').forEach(button=>button.onclick=()=>reloadWithState(loadProjectSnapshotV47(button.dataset.v47OpenProject)));
}
function projectSwitcher(){const top=document.querySelector('.topbar');if(!top||top.querySelector('.v47-project-switcher'))return;const host=el('div','v47-project-switcher',projectMenuHtml(readState()));const save=top.querySelector('.save-state');(save||top.querySelector('#quickExport'))?.before(host);bindProjectMenu(host)}

function decorateShell(){
  document.body.dataset.v47FreeStudio='true';if(document.title!=='BoxStudio Free · 在线纸盒设计与唛头编辑')document.title='BoxStudio Free · 在线纸盒设计与唛头编辑';
  const brand=document.querySelector('.topbar .brand');if(brand&&!brand.dataset.v47){brand.dataset.v47='true';brand.innerHTML='BOXSTUDIO <small>FREE</small>';const pill=el('span','v47-free-pill','永久免费');brand.after(pill)}
  const save=document.querySelector('.topbar .save-state');if(save&&!document.querySelector('.v47-shell-note')){const note=el('span','v47-shell-note','无需登录 · 无水印 · 所有生产导出免费');save.before(note)}
  const exportBtn=document.querySelector('#quickExport');if(exportBtn){setText(exportBtn,'免费导出');if(exportBtn.title!=='SVG / PDF / DXF / PNG / Production PDF — 无付费墙')exportBtn.title='SVG / PDF / DXF / PNG / Production PDF — 无付费墙'}
  const labels={dashboard:'工作台',templates:'盒型库',projects:'项目',editor:'设计器',marks:'唛头库'};for(const [id,label] of Object.entries(labels))setText(document.querySelector(`[data-nav="${id}"]`),label);projectSwitcher()
}

function dashboardHero(){
  if(activePage()!=='dashboard')return;const page=document.querySelector('main.page');if(!page||page.querySelector('.v47-hero'))return;
  const hero=el('section','v47-hero',`<div class="v47-hero-copy"><div class="eyebrow">FREE PACKAGING STUDIO</div><h1>从盒型到刀版、3D、唛头与生产文件</h1><p>面向包装工程、外贸、工厂与设计团队的免费在线纸盒工作台。选择盒型后输入尺寸和材料，直接编辑刀线与图文，验证 3D 折叠，制作运输唛头与条码，最后导出生产文件。</p><div class="v47-hero-actions"><button class="primary" data-v47-go="templates">选择盒型</button><button data-v47-go-tab="Structure">新建设计</button><button data-v47-go-tab="Marks">编辑唛头</button><button data-v47-review>2D ↔ 3D 同屏审查</button></div></div><div class="v47-cap-grid"><div class="v47-cap"><b>参数化盒型</b><span>FEFCO / Mailer / Folding Carton</span></div><div class="v47-cap"><b>专业 2D CAD</b><span>Layers / Objects / Exact Transform</span></div><div class="v47-cap"><b>运输唛头</b><span>变量 / Barcode / QR / Excel Batch</span></div><div class="v47-cap"><b>生产导出</b><span>SVG / PDF / DXF / PNG · Free</span></div></div>`);
  page.prepend(hero);hero.querySelectorAll('[data-v47-go]').forEach(b=>b.onclick=()=>clickNav(b.dataset.v47Go));hero.querySelectorAll('[data-v47-go-tab]').forEach(b=>b.onclick=()=>{clickNav('editor');setTimeout(()=>clickTab(b.dataset.v47GoTab),0)});hero.querySelector('[data-v47-review]').onclick=()=>{clickNav('editor');setTimeout(openLinkedReviewV35,50)}
}

function categoryFromCard(card){
  const engine=card.querySelector('[data-use-template]')?.dataset.useTemplate;if(engine){const record=searchFreeTemplatesV47({}).find(x=>x.id===engine);return record?templateCategoryV47(record):'all'}
  const text=card.textContent.toLowerCase();if(text.includes('import')||text.includes('svg')&&text.includes('dxf'))return'import';if(text.includes('mailer')||text.includes('0427')||text.includes('150010')||text.includes('飞机'))return'mailer';if(text.includes('tuck')||text.includes('carton')||text.includes('ecma')||text.includes('纸盒'))return'folding-carton';return'shipping';
}
function decorateTemplateCards(){const cards=[...document.querySelectorAll('main.page .cards > .card')];for(const card of cards){if(card.dataset.v47Card)return;card.dataset.v47Card='true';card.dataset.v47Category=categoryFromCard(card);card.prepend(el('div','v47-card-meta',`<span class="v47-card-category">${esc(card.dataset.v47Category)}</span><span class="v47-card-free">FREE</span>`))}}
function applyTemplateFilter(){const cards=[...document.querySelectorAll('main.page .cards > .card[data-v47-card]')],q=templateQuery.trim().toLowerCase();let visible=0;for(const card of cards){const category=card.dataset.v47Category,okCategory=templateCategory==='all'||category===templateCategory,okQuery=!q||card.textContent.toLowerCase().includes(q);card.style.display=okCategory&&okQuery?'':'none';if(okCategory&&okQuery)visible++}setText(document.querySelector('[data-v47-template-count]'),`${visible} 个可用盒型 / 入口`)}
function templateLibrary(){if(activePage()!=='templates')return;const page=document.querySelector('main.page');if(!page)return;decorateTemplateCards();if(!page.querySelector('.v47-template-shell')){const shell=el('section','v47-template-shell',`<div class="v47-template-head"><strong>盒型资源库</strong><div class="v47-template-search"><input data-v47-template-search placeholder="搜索盒型、标准、编号，例如 0427 / mailer / RSC"></div><span class="v47-template-count" data-v47-template-count></span></div><div class="v47-filter-row">${V47_TEMPLATE_FILTERS.map(x=>`<button data-v47-category="${x.id}" class="${x.id===templateCategory?'active':''}">${x.label}</button>`).join('')}</div>`);page.querySelector('.page-head')?.after(shell);const input=shell.querySelector('[data-v47-template-search]');input.value=templateQuery;input.oninput=e=>{templateQuery=e.target.value;applyTemplateFilter()};shell.querySelectorAll('[data-v47-category]').forEach(b=>b.onclick=()=>{templateCategory=b.dataset.v47Category;shell.querySelectorAll('[data-v47-category]').forEach(x=>x.classList.toggle('active',x===b));applyTemplateFilter()})}applyTemplateFilter()}

function pageIntro(){const pageName=activePage();if(!['projects','marks'].includes(pageName))return;const page=document.querySelector('main.page');if(!page||page.querySelector('.v47-page-intro'))return;const copy=pageName==='marks'?['免费唛头与包装标识','SKU、净重/毛重、箱规、原产国、CRN、箱号、运输图标、真实一维码、QR 与 Excel 批量字段都可以直接编辑。']:['本地项目工作台','默认自动保存在浏览器；可以手动保存多个本地项目快照、另存为和切换，不要求账号。'];page.prepend(el('div','v47-page-intro',`<div><b>${copy[0]}</b><span>${copy[1]}</span></div><span class="v47-free-pill">${V47_FREE_POLICY.statement}</span>`))}
function workflowBar(){if(activePage()!=='editor')return;const main=document.querySelector('.workspace .main'),tabs=main?.querySelector('.tabbar');if(!main||!tabs||main.querySelector('.v47-workflow'))return;const current=activeTab(),bar=el('div','v47-workflow',V47_WORKFLOW.map((x,i)=>`${i?'<span class="v47-step-sep">›</span>':''}<button class="v47-step ${x.tab===current?'active':''}" ${x.id==='templates'?'data-v47-nav-step="templates"':`data-v47-tab-step="${x.tab}"`} title="${esc(x.description)}"><b>${i+1}</b><span>${x.label}</span></button>`).join(''));tabs.before(bar);bar.querySelectorAll('[data-v47-nav-step]').forEach(b=>b.onclick=()=>clickNav(b.dataset.v47NavStep));bar.querySelectorAll('[data-v47-tab-step]').forEach(b=>b.onclick=()=>clickTab(b.dataset.v47TabStep))}
function dimensionCard(){if(activePage()!=='editor')return;const right=document.querySelector('.workspace .rightpanel');if(!right||right.querySelector('.v47-dimension-card'))return;let d;try{d=dimensionSummaryV47(readState().structure)}catch{return}const fmt=x=>`${x.L} × ${x.W} × ${x.H} mm`;right.prepend(el('section','v47-dimension-card',`<div class="v47-panel-title"><b>尺寸系统</b><span>${esc(d.mode)} input</span></div><div class="v47-dimension-grid"><div class="v47-dim"><span>内尺寸</span><b>${fmt(d.inside)}</b></div><div class="v47-dim"><span>制造尺寸</span><b>${fmt(d.manufacturing)}</b></div><div class="v47-dim"><span>外尺寸</span><b>${fmt(d.external)}</b></div></div><div class="v47-material-line"><span>材料</span><strong>${esc(d.material.name)} · ${d.thicknessMm} mm${d.material.flute?` · ${esc(d.material.flute)} flute`:''}</strong></div>`))}
function markQuickActions(){if(activePage()!=='editor'||activeTab()!=='Marks')return;const right=document.querySelector('.workspace .rightpanel');if(!right||right.querySelector('.v47-mark-actions'))return;const box=el('section','v47-mark-actions',`<div class="v47-panel-title"><b>唛头快速工具</b><span>全部免费</span></div><div class="v47-mark-grid">${V47_MARK_QUICK_ACTIONS.map(x=>`<button class="v47-mark-action" data-v47-tool="${x.tool}"><b>${x.label}</b><span>${x.description}</span></button>`).join('')}</div><div class="v47-workbench-actions"><button data-v47-professional>对象 / 图层 / 精确属性</button><button data-v47-linked-review>2D ↔ 3D 同屏审查</button></div>`);right.prepend(box);box.querySelectorAll('[data-v47-tool]').forEach(b=>b.onclick=()=>clickTool(b.dataset.v47Tool));box.querySelector('[data-v47-professional]').onclick=openProfessional2D;box.querySelector('[data-v47-linked-review]').onclick=openLinkedReviewV35}
function exportFreeNotice(){if(activePage()!=='editor'||activeTab()!=='Export')return;const right=document.querySelector('.workspace .rightpanel');if(!right||right.querySelector('.v47-free-export'))return;right.prepend(el('section','v47-free-export',`<b>生产导出永久免费</b><span>无需登录、无水印、不设下载次数限制。现有 SVG / PDF / DXF / PNG / Production PDF 能力直接开放。</span>`))}
function previewLaunch(){if(activePage()!=='editor'||activeTab()==='3D')return;const right=document.querySelector('.workspace .rightpanel');if(!right||right.querySelector('.v47-preview-launch'))return;const box=el('section','v47-preview-launch',`<div class="v47-panel-title"><b>结构与图文验证</b><span>linked proof</span></div><div class="v47-preview-actions"><button data-v47-linked-review>2D ↔ 3D 同屏审查</button><button data-v47-open-3d>打开 3D 折叠预览</button></div>`);right.prepend(box);box.querySelector('[data-v47-linked-review]').onclick=openLinkedReviewV35;box.querySelector('[data-v47-open-3d]').onclick=()=>clickTab('3D')}
function lineLegend(){if(activePage()!=='editor')return;const status=document.querySelector('.workspace .status');if(!status||status.querySelector('.v47-line-legend'))return;const legend=el('div','v47-line-legend','<span class="cut"><i></i>CUT</span><span class="crease"><i></i>CREASE</span><span class="bleed"><i></i>BLEED</span><span class="safe"><i></i>SAFE</span>');status.querySelector('.right')?.prepend(legend)}
function freeGateAudit(){if(activePage()!=='editor')return;for(const button of document.querySelectorAll('#exportSvg,#exportPdf,#exportDxf,#exportPng,#batchSvg,#batchPdf,#batchCombinedPdf')){button.dataset.v47Free='true';const title='BoxStudio Free — no login/paywall';if(button.title!==title)button.title=title}}

function decorate(){decorateShell();dashboardHero();templateLibrary();pageIntro();workflowBar();dimensionCard();markQuickActions();exportFreeNotice();previewLaunch();lineLegend();freeGateAudit()}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;decorate()})}
observer=new MutationObserver(schedule);observer.observe(document.body,{childList:true,subtree:true});decorate();

window.BoxStudioV47={version:'V0.47',freePolicy:V47_FREE_POLICY,workflow:V47_WORKFLOW,searchTemplates:searchFreeTemplatesV47,dimensionSummary:dimensionSummaryV47,saveProject:saveProjectSnapshotV47,openLinkedReview:openLinkedReviewV35,openProfessional2D,allFeaturesFree:true,noLoginRequired:true,noWatermark:true};
