import { STORAGE_KEY, defaultState, stateForTemplate } from './model.js';
import { generateGeometry } from './geometry.js';
import { previewSvgForGeometryV32 } from './parametricTemplatesV32.js';
import { dimensionSummaryV47, materialChoicesV47 } from './freeStudioV47.js';

const clone=v=>structuredClone(v),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let queued=false,observer=null;
function ensureStyle(){if(document.querySelector('link[data-v47-template-experience]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href=new URL('./v47TemplateExperience.css',import.meta.url).href;link.dataset.v47TemplateExperience='true';document.head.appendChild(link)}
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,structure:{...defaultState.structure,...(p.structure||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function previewForStructure(structure){try{return previewSvgForGeometryV32(generateGeometry(structure))}catch{return'<div class="v47-template-preview-error">Preview unavailable</div>'}}
function structureFromForm(base,host){const materialId=host.querySelector('[data-v47-setup-material]').value,material=materialChoicesV47().find(x=>x.id===materialId)||materialChoicesV47()[0];return {...base,length:Number(host.querySelector('[data-v47-setup-l]').value),width:Number(host.querySelector('[data-v47-setup-w]').value),height:Number(host.querySelector('[data-v47-setup-h]').value),sizeType:host.querySelector('[data-v47-setup-size-type]').value,materialId:material.id,flute:material.defaultFlute||null,thickness:material.defaultThicknessMm}}
function renderSetupPreview(host,structure){const summary=dimensionSummaryV47(structure),fmt=d=>`${d.L} × ${d.W} × ${d.H} mm`;host.querySelector('[data-v47-setup-preview]').innerHTML=previewForStructure(structure);host.querySelector('[data-v47-setup-dims]').innerHTML=`<div><span>内尺寸</span><b>${fmt(summary.inside)}</b></div><div><span>制造尺寸</span><b>${fmt(summary.manufacturing)}</b></div><div><span>外尺寸</span><b>${fmt(summary.external)}</b></div><small>${esc(summary.material.name)} · ${summary.thicknessMm} mm${summary.material.flute?` · ${esc(summary.material.flute)} flute`:''}</small>`}
function closeSetup(){document.querySelector('#boxstudio-v47-template-setup')?.remove()}
function openSetup(engine){
  closeSetup();const current=readState(),draft=stateForTemplate(engine,current.variables),base=clone(draft.structure),materials=materialChoicesV47(),host=document.createElement('div');host.id='boxstudio-v47-template-setup';host.innerHTML=`<div class="v47-setup-modal"><header><div><b>快速设置盒型</b><span>${esc(engine)} · 免费参数化生成</span></div><button data-v47-setup-close>×</button></header><main><section class="v47-setup-form"><label><span>长度 L</span><input data-v47-setup-l type="number" min="1" step="1" value="${base.length}"><em>mm</em></label><label><span>宽度 W</span><input data-v47-setup-w type="number" min="1" step="1" value="${base.width}"><em>mm</em></label><label><span>高度 H</span><input data-v47-setup-h type="number" min="1" step="1" value="${base.height}"><em>mm</em></label><label><span>尺寸口径</span><select data-v47-setup-size-type><option value="internal" ${base.sizeType==='internal'?'selected':''}>内尺寸</option><option value="manufacturing" ${base.sizeType==='manufacturing'?'selected':''}>制造尺寸</option><option value="external" ${base.sizeType==='external'?'selected':''}>外尺寸</option></select></label><label><span>材料</span><select data-v47-setup-material>${materials.map(m=>`<option value="${m.id}" ${m.id===base.materialId?'selected':''}>${esc(m.name)} · ${m.defaultThicknessMm} mm</option>`).join('')}</select></label><div class="v47-setup-policy"><b>FREE</b><span>无需登录 · 不加水印 · 后续 SVG / PDF / DXF / PNG / Production PDF 继续免费</span></div></section><section class="v47-setup-visual"><div data-v47-setup-preview></div><div class="v47-setup-dims" data-v47-setup-dims></div></section></main><footer><button data-v47-setup-cancel>取消</button><button class="primary" data-v47-setup-apply>进入编辑器</button></footer></div>`;document.body.appendChild(host);
  const refresh=()=>{try{renderSetupPreview(host,structureFromForm(base,host))}catch(error){host.querySelector('[data-v47-setup-dims]').innerHTML=`<div class="error">${esc(error.message)}</div>`}};refresh();host.querySelectorAll('input,select').forEach(input=>input.addEventListener(input.tagName==='SELECT'?'change':'input',refresh));host.querySelector('[data-v47-setup-close]').onclick=closeSetup;host.querySelector('[data-v47-setup-cancel]').onclick=closeSetup;host.addEventListener('click',e=>{if(e.target===host)closeSetup()});host.querySelector('[data-v47-setup-apply]').onclick=()=>{const next=stateForTemplate(engine,current.variables);next.structure=structureFromForm(next.structure,host);next.page='editor';next.editorTab='Structure';next.projectName=current.projectName||next.projectName;next.projectId=current.projectId||next.projectId;writeState(next);location.reload()}
}
function decorateCard(card){if(card.dataset.v47Visual==='true')return;const use=card.querySelector('[data-use-template]');if(!use)return;const engine=use.dataset.useTemplate;let structure;try{structure=stateForTemplate(engine).structure}catch{return}card.dataset.v47Visual='true';const visual=document.createElement('div');visual.className='v47-template-preview';visual.innerHTML=previewForStructure(structure);const meta=card.querySelector('.v47-card-meta');if(meta)meta.after(visual);else card.prepend(visual);const actions=card.querySelector('.card-actions');if(actions&&!actions.querySelector('[data-v47-quick-setup]')){const button=document.createElement('button');button.className='mini';button.dataset.v47QuickSetup=engine;button.textContent='快速尺寸 / 材料';button.title='进入编辑器前设置尺寸口径、L/W/H 与材料';button.onclick=e=>{e.preventDefault();e.stopPropagation();openSetup(engine)};actions.appendChild(button)}}
function decorate(){if(document.querySelector('[data-nav="templates"].active'))document.querySelectorAll('main.page .card').forEach(decorateCard)}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;decorate()})}
ensureStyle();observer=new MutationObserver(schedule);observer.observe(document.getElementById('app')||document.body,{subtree:true,childList:true});decorate();
window.BoxStudioV47Template={openSetup,closeSetup,visualTemplateCards:true,quickParametricSetup:true};
