import { STORAGE_KEY, defaultState, cloneState } from './model.js';
import { V47_FREE_POLICY, V47_WORKFLOW, searchTemplatesV47, templateCategoriesV47, materialOptionsV47, fluteOptionsV47, prepareTemplateStateV47, V47_MARK_GROUPS } from './productExperienceV47.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let queued=false;
function readState(){try{return {...cloneState(defaultState),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return cloneState(defaultState)}}
function persistState(state){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function reloadWith(state){persistState(state);location.reload()}
function currentPage(){return document.querySelector('.nav button.active')?.dataset.nav||readState().page}
function addFreeBadge(){const top=document.querySelector('.topbar');if(!top||top.querySelector('[data-v47-free]'))return;const badge=document.createElement('div');badge.dataset.v47Free='';badge.className='v47-free';badge.innerHTML='<b>永久免费</b><span>无需登录 · 无试用期 · 无付费墙</span>';const save=top.querySelector('.save-state');top.insertBefore(badge,save)}
function workflowRail(){const active=document.querySelector('.tabbar button.active')?.textContent||readState().editorTab;return `<div class="v47-flow">${V47_WORKFLOW.map(s=>`<button data-v47-tab="${esc(s.tab)}" class="${s.tab===active?'active':''}"><span>${esc(s.label)}</span></button>`).join('')}</div>`}
function enhanceEditor(){const main=document.querySelector('.workspace .main');if(!main||main.querySelector('.v47-flow'))return;const tabbar=main.querySelector('.tabbar');if(!tabbar)return;tabbar.insertAdjacentHTML('afterend',workflowRail());main.querySelectorAll('[data-v47-tab]').forEach(b=>b.onclick=()=>document.querySelector(`.tabbar button[data-tab="${CSS.escape(b.dataset.v47Tab)}"]`)?.click())}
function categoryName(c){return({all:'全部',shipping:'运输箱',mailer:'邮寄盒', 'folding-carton':'折叠纸盒',rigid:'硬盒',custom:'自定义'})[c]||c}
function templateIcon(t){if(t.category==='mailer')return '▱';if(t.category==='shipping')return '▣';if(t.category==='folding-carton')return '▤';return '□'}
function templateCard(t){return `<article class="v47-template-card"><div class="v47-template-visual"><span>${templateIcon(t)}</span><small>${esc(t.code)}</small></div><div class="v47-template-copy"><div class="v47-template-tags"><span>${esc(categoryName(t.category))}</span><span>${esc(t.standard)}</span><span class="good">可直接生成</span></div><h3>${esc(t.nameZh||t.name)}</h3><p>${esc(t.name)}</p><button class="primary" data-v47-template="${esc(t.id)}">配置尺寸</button></div></article>`}
function configPanel(templateId){const t=searchTemplatesV47({}).find(x=>x.id===templateId);if(!t)return'';const mats=materialOptionsV47(),flutes=fluteOptionsV47();return `<div class="v47-config" data-v47-config><div class="v47-config-head"><div><small>快速开始</small><h3>${esc(t.nameZh||t.name)}</h3></div><button data-v47-close>×</button></div><div class="v47-size-grid"><label>长 L<input data-v47-l type="number" min="25" step="1" value="300"><em>mm</em></label><label>宽 W<input data-v47-w type="number" min="20" step="1" value="200"><em>mm</em></label><label>高 H<input data-v47-h type="number" min="15" step="1" value="70"><em>mm</em></label><label>尺寸口径<select data-v47-size-type><option value="internal">内尺寸</option><option value="external">外尺寸</option><option value="manufacturing">制造尺寸</option></select></label><label>材料<select data-v47-material>${mats.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}</select></label><label>楞型<select data-v47-flute>${flutes.map(f=>`<option value="${esc(f.id)}" ${f.id==='E'?'selected':''}>${esc(f.label)} · ${f.thicknessMm}mm</option>`).join('')}</select></label></div><div class="v47-config-foot"><div><b>免费生成</b><span>刀版、2D 编辑、3D 预览、唛头编辑和导出流程均不需要会员。</span></div><button class="primary" data-v47-start>生成刀版并进入编辑器</button></div></div>`}
function renderTemplateCenter(){const page=document.querySelector('.page');if(!page||page.dataset.v47Templates==='true')return;page.dataset.v47Templates='true';page.innerHTML=`<section class="v47-hero"><div><span class="v47-kicker">FREE PACKAGING DESIGN STUDIO</span><h1>选择盒型，输入尺寸，立即生成刀版</h1><p>参考成熟包装工具的低学习成本流程：先选结构，再设置尺寸 / 材料 / 纸厚，随后进入 2D、3D 与唛头编辑。当前所有已验证引擎全部免费开放。</p><div class="v47-proof"><span>✓ 无需登录</span><span>✓ 无下载次数限制</span><span>✓ 真实参数化刀版</span><span>✓ 2D / 3D 联动</span></div></div><div class="v47-hero-card"><b>从 3 步开始</b><ol><li>选择盒型</li><li>填写 L × W × H</li><li>生成并继续编辑</li></ol></div></section><section class="v47-template-toolbar"><div class="v47-search"><span>⌕</span><input data-v47-search placeholder="搜索盒型、FEFCO 编号、RSC、Mailer…"></div><div class="v47-cats">${templateCategoriesV47().map(c=>`<button data-v47-cat="${esc(c)}" class="${c==='all'?'active':''}">${esc(categoryName(c))}</button>`).join('')}</div></section><section class="v47-template-grid" data-v47-grid>${searchTemplatesV47({}).map(templateCard).join('')}</section><section class="v47-import-card"><div><b>已有刀版文件？</b><span>支持 SVG / DXF / PDF / PDF-compatible AI 导入，再进入 Topology、3D 与生产检查。</span></div><button class="mini" data-v47-import>导入自己的刀版</button></section>`;
 let category='all';const search=page.querySelector('[data-v47-search]'),grid=page.querySelector('[data-v47-grid]');const redraw=()=>{grid.innerHTML=searchTemplatesV47({query:search.value,category}).map(templateCard).join('')||'<div class="v47-empty">没有匹配的已验证模板。可尝试搜索其他关键词或导入自己的刀版。</div>';bindTemplateButtons(page)};search.oninput=redraw;page.querySelectorAll('[data-v47-cat]').forEach(b=>b.onclick=()=>{page.querySelectorAll('[data-v47-cat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');category=b.dataset.v47Cat;redraw()});page.querySelector('[data-v47-import]').onclick=()=>{const s=readState();s.page='editor';s.editorTab='Structure';reloadWith(s)};bindTemplateButtons(page)}
function bindTemplateButtons(page){page.querySelectorAll('[data-v47-template]').forEach(b=>b.onclick=()=>{page.querySelector('[data-v47-config]')?.remove();page.insertAdjacentHTML('beforeend',configPanel(b.dataset.v47Template));const panel=page.querySelector('[data-v47-config]');panel.querySelector('[data-v47-close]').onclick=()=>panel.remove();panel.querySelector('[data-v47-start]').onclick=()=>{const s=readState(),quick={length:panel.querySelector('[data-v47-l]').value,width:panel.querySelector('[data-v47-w]').value,height:panel.querySelector('[data-v47-h]').value,sizeType:panel.querySelector('[data-v47-size-type]').value,materialId:panel.querySelector('[data-v47-material]').value,flute:panel.querySelector('[data-v47-flute]').value};reloadWith(prepareTemplateStateV47(s,b.dataset.v47Template,quick))}})}
function renderMarksHub(){const page=document.querySelector('.page');if(!page||page.dataset.v47Marks==='true')return;page.dataset.v47Marks='true';page.innerHTML=`<section class="v47-marks-head"><div><span class="v47-kicker">SHIPPING MARK EDITOR</span><h1>唛头组件库</h1><p>把运输信息、条码 / QR、搬运图标和自定义变量直接放到纸箱对应面板，支持批量数据驱动。</p></div><button class="primary" data-v47-open-marks>打开唛头编辑器</button></section><section class="v47-mark-groups">${V47_MARK_GROUPS.map(g=>`<article><div class="v47-mark-title"><b>${esc(g.label)}</b><span>${g.items.length} 项</span></div><div class="v47-mark-items">${g.items.map(x=>`<span>${esc(x)}</span>`).join('')}</div></article>`).join('')}</section><section class="v47-mark-workflow"><div><b>单箱设计</b><span>拖拽文字、图标、条码和 QR 到指定面板。</span></div><div><b>变量绑定</b><span>SKU、重量、尺寸、CRN、箱号等可绑定变量。</span></div><div><b>批量唛头</b><span>Excel / CSV → 字段映射 → 多箱批量生成。</span></div><div><b>生产检查</b><span>条码可解码性、越界、尺寸和 PDF 几何进入 Preflight。</span></div></section>`;page.querySelector('[data-v47-open-marks]').onclick=()=>{const s=readState();s.page='editor';s.editorTab='Marks';reloadWith(s)}}
function enhance(){document.body.dataset.v47FreeProduct='true';addFreeBadge();const page=currentPage();if(page==='editor')enhanceEditor();if(page==='templates')renderTemplateCenter();if(page==='marks')renderMarksHub()}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;enhance()})}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});enhance();
window.BoxStudioV47={version:'V0.47',freePolicy:V47_FREE_POLICY,workflow:V47_WORKFLOW,templates:searchTemplatesV47({})};
