import { STORAGE_KEY, defaultState } from './model.js';

const clone=v=>structuredClone(v);let observer=null,queued=false;
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,structure:{...defaultState.structure,...(p.structure||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function save(state){state.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function ensurePreview(state){state.previewV48=state.previewV48||{};state.previewV48.faceStyles=state.previewV48.faceStyles||{};state.previewV48.background=state.previewV48.background||'#181b20';return state.previewV48}
function selectedPanelId(){return readState().reviewV35?.selectedPanelId||null}
function panelColor(state,id){return state.previewV48?.faceStyles?.[id]?.face||'#d8c2a0'}
function emit(state){globalThis.dispatchEvent(new CustomEvent('boxstudio:v48-preview-change',{detail:{faceStyles:state.previewV48?.faceStyles||{},background:state.previewV48?.background||'#181b20'}}))}
function setFace(id,color,{all=false}={}){const state=readState(),preview=ensurePreview(state);if(all){const buttons=document.querySelectorAll('#v35Dieline [data-v35-panel]');for(const el of buttons)preview.faceStyles[el.dataset.v35Panel]={...(preview.faceStyles[el.dataset.v35Panel]||{}),face:color}}else if(id)preview.faceStyles[id]={...(preview.faceStyles[id]||{}),face:color};save(state);emit(state)}
function setBackground(color){const state=readState(),preview=ensurePreview(state);preview.background=color;save(state);emit(state)}
function setFold(value){const slider=document.querySelector('#boxstudio-v35-review #v35Fold');if(!slider)return;slider.value=String(value);slider.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:String(value)}))}
function updateSelection(host){const id=selectedPanelId(),state=readState(),label=host.querySelector('.v48-face-label'),input=host.querySelector('[data-v48-face-color]');if(label)label.textContent=id||'No face';if(input&&id)input.value=panelColor(state,id)}
function inject(){const review=document.querySelector('#boxstudio-v35-review');if(!review)return;const top=review.querySelector('.v35-top');if(!top||top.querySelector('.v48-appearance'))return;const state=readState(),preview=ensurePreview(state),id=state.reviewV35?.selectedPanelId,host=document.createElement('div');host.className='v48-appearance';host.innerHTML=`<span>Face</span><span class="v48-face-label">${id||'No face'}</span><input data-v48-face-color type="color" value="${id?panelColor(state,id):'#d8c2a0'}" title="Selected face color"><button data-v48-all-face>Apply all</button><span>Scene</span><select data-v48-scene><option value="#181b20">Dark studio</option><option value="#eef1f2">Light studio</option><option value="#d7d0c2">Warm paper</option><option value="#24323a">Blueprint</option></select><div class="v48-fold-presets"><button data-v48-fold="0">Flat</button><button data-v48-fold="50">50%</button><button data-v48-fold="100">Box</button></div>`;const spacer=top.querySelector('.v35-spacer');top.insertBefore(host,spacer||null);host.querySelector('[data-v48-scene]').value=preview.background||'#181b20';host.querySelector('[data-v48-face-color]').oninput=e=>setFace(selectedPanelId(),e.target.value);host.querySelector('[data-v48-all-face]').onclick=()=>setFace(selectedPanelId(),host.querySelector('[data-v48-face-color]').value,{all:true});host.querySelector('[data-v48-scene]').onchange=e=>setBackground(e.target.value);host.querySelectorAll('[data-v48-fold]').forEach(b=>b.onclick=()=>setFold(Number(b.dataset.v48Fold)));const mo=new MutationObserver(()=>updateSelection(host));const dieline=review.querySelector('#v35Dieline');if(dieline)mo.observe(dieline,{subtree:true,attributes:true,attributeFilter:['class'],childList:true});host._v48Observer=mo;emit(state)}
function decorate(){inject()}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;decorate()})}
observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true});decorate();
window.BoxStudioV48Appearance={version:'V0.48',setFaceColor:setFace,setBackground,setFold,free:true};
