import { STORAGE_KEY, defaultState } from './model.js';
import { materialChoicesV47 } from './freeStudioV47.js';
import { bendProfileV48, advancedStructureParamsV48, normalizeParametricStructureV48, validateParametricStructureV48 } from './parametricControlsV48.js';
import { runPreflightV48 } from './preflightV48.js';

const clone=v=>structuredClone(v),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let observer=null,queued=false;
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return p?{...clone(defaultState),...p,structure:{...defaultState.structure,...(p.structure||{})},variables:{...defaultState.variables,...(p.variables||{})}}:clone(defaultState)}catch{return clone(defaultState)}}
function writeState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function activeTab(){return document.querySelector('.tabbar [data-tab].active')?.dataset.tab||null}
function activeEditor(){return Boolean(document.querySelector('.workspace'))}
function rightPanel(){return document.querySelector('.workspace .rightpanel')}
function fmt(v){return Number(v).toFixed(2).replace(/\.00$/,'')}

function paramValues(host){return{
  materialId:host.querySelector('[data-v48-material]').value,
  flute:host.querySelector('[data-v48-flute]').value||'CUSTOM',
  thickness:Number(host.querySelector('[data-v48-thickness]').value),
  bendRadiusMode:host.querySelector('[data-v48-bend-mode]').value,
  bendRadiusMm:Number(host.querySelector('[data-v48-bend-radius]').value),
  scoreAllowanceMm:Number(host.querySelector('[data-v48-score]').value),
  flapRatio:Number(host.querySelector('[data-v48-flap]').value),
  tuckRatio:Number(host.querySelector('[data-v48-tuck]').value),
  dustFlapRatio:Number(host.querySelector('[data-v48-dust]').value),
  wingRatio:Number(host.querySelector('[data-v48-wing]').value),
  glue:Number(host.querySelector('[data-v48-glue]').value),
}}
function renderParamOutput(host,structure){const report=validateParametricStructureV48(structure),b=report.bend,a=report.advanced;host.querySelector('[data-v48-output]').innerHTML=`<b>${b.mode==='auto'?'AUTO':'MANUAL'} R${fmt(b.radiusMm)} mm</b> · 板厚 ${fmt(b.thicknessMm)} mm · Score ${fmt(b.scoreAllowanceMm)} mm<br>Flap ${fmt(a.flapDepthMm)} · Tuck ${fmt(a.tuckDepthMm)} · Dust ${fmt(a.dustFlapDepthMm)} · Wing ${fmt(a.wingMm)} mm${report.issues.length?`<br>${report.issues.map(x=>`${x.severity.toUpperCase()}: ${esc(x.detail)}`).join('<br>')}`:''}`;const radius=host.querySelector('[data-v48-bend-radius]');radius.disabled=b.mode==='auto';if(b.mode==='auto')radius.value=b.radiusMm}
function parametricPanel(){
  if(!activeEditor()||activeTab()!=='Structure')return;const right=rightPanel();if(!right||right.querySelector('.v48-parametric'))return;const state=readState(),s=normalizeParametricStructureV48(state.structure),materials=materialChoicesV47(),b=bendProfileV48(s),a=advancedStructureParamsV48(s),host=document.createElement('section');host.className='v48-parametric';host.innerHTML=`<div class="v48-title"><b>制造参数 · Parametric Controls</b><span>V0.48 · 2D / 3D shared</span></div><div class="v48-grid"><label class="v48-field v48-wide"><span>材料 / Material</span><select data-v48-material>${materials.map(m=>`<option value="${esc(m.id)}" ${m.id===s.materialId?'selected':''}>${esc(m.name)} · ${m.defaultThicknessMm} mm</option>`).join('')}</select></label><label class="v48-field"><span>楞型 / Flute</span><input data-v48-flute value="${esc(s.flute||'CUSTOM')}"></label><label class="v48-field"><span>板厚 mm</span><input data-v48-thickness type="number" min="0.1" max="20" step="0.05" value="${fmt(s.thickness)}"></label><label class="v48-field"><span>折弯半径</span><select data-v48-bend-mode><option value="auto" ${b.mode==='auto'?'selected':''}>Auto by board</option><option value="manual" ${b.mode==='manual'?'selected':''}>Manual</option></select></label><label class="v48-field"><span>Radius mm</span><input data-v48-bend-radius type="number" min="0.05" step="0.05" value="${fmt(b.radiusMm)}"></label><label class="v48-field"><span>Score allowance mm</span><input data-v48-score type="number" min="0" step="0.05" value="${fmt(b.scoreAllowanceMm)}"></label><label class="v48-field"><span>Glue mm</span><input data-v48-glue type="number" min="0" max="80" step="1" value="${fmt(a.glueMm)}"></label><label class="v48-field"><span>Flap ratio ${fmt(a.flapRatio)}</span><input data-v48-flap type="range" min="0.18" max="0.78" step="0.01" value="${a.flapRatio}"></label><label class="v48-field"><span>Tuck ratio ${fmt(a.tuckRatio)}</span><input data-v48-tuck type="range" min="0.28" max="1.15" step="0.01" value="${a.tuckRatio}"></label><label class="v48-field"><span>Dust flap ratio ${fmt(a.dustFlapRatio)}</span><input data-v48-dust type="range" min="0.22" max="0.90" step="0.01" value="${a.dustFlapRatio}"></label><label class="v48-field"><span>Wing ratio ${fmt(a.wingRatio)}</span><input data-v48-wing type="range" min="0.25" max="1.35" step="0.01" value="${a.wingRatio}"></label></div><div class="v48-output" data-v48-output></div><div class="v48-actions"><button data-v48-check>制造参数检查</button><button class="primary" data-v48-apply>应用并重建刀版</button></div>`;right.prepend(host);
  const draft=()=>normalizeParametricStructureV48(readState().structure,paramValues(host));const refresh=()=>{const d=draft();renderParamOutput(host,d);host.querySelectorAll('input[type=range]').forEach(input=>{const span=input.closest('label')?.querySelector('span');if(span)span.textContent=span.textContent.replace(/\s[\d.]+$/,'')+` ${fmt(input.value)}`})};
  host.querySelectorAll('input,select').forEach(x=>x.addEventListener(x.tagName==='SELECT'?'change':'input',refresh));host.querySelector('[data-v48-material]').addEventListener('change',()=>{const m=materials.find(x=>x.id===host.querySelector('[data-v48-material]').value);if(m){host.querySelector('[data-v48-thickness]').value=m.defaultThicknessMm;host.querySelector('[data-v48-flute]').value=m.defaultFlute||'CUSTOM'}refresh()});
  host.querySelector('[data-v48-check]').onclick=()=>{const report=runPreflightV48({...readState(),structure:draft()});alert(report.ok?`PASS · R${report.summary.bendRadiusMm} mm · ${report.summary.boardThicknessMm} mm board`:`BLOCKED\n${report.errors.map(x=>x.code+': '+x.detail).join('\n')}`)};
  host.querySelector('[data-v48-apply]').onclick=()=>{const next=readState(),structure=draft(),validation=validateParametricStructureV48(structure);if(!validation.ok){alert(validation.issues.map(x=>x.detail).join('\n'));return}next.structure=structure;delete next.dielineV38;writeState(next);location.reload()};refresh();
}

function markPreview(v){return`${v.shipTo||'SHIP TO'}\nPO: ${v.poNumber||'-'}    SKU: ${v.sku||'-'}\nCARTON: ${v.cartonNo||'-'}    QTY: ${v.quantity||'-'}\nN.W.: ${v.netWeight||'-'}    G.W.: ${v.grossWeight||'-'}\nMEAS: ${v.dimensionLine||'-'}\nMADE IN: ${v.countryOfOrigin||'-'}`}
function closeMarkStudio(){document.querySelector('#boxstudio-v48-shipping')?.remove()}
function openMarkStudio(){closeMarkStudio();const state=readState(),v=state.variables||{},host=document.createElement('div');host.id='boxstudio-v48-shipping';host.innerHTML=`<div class="v48-mark-modal"><header><div><b>Shipping Mark Studio · 唛头编辑</b><span>变量一次填写，可继续用于条码 / QR / 批量数据</span></div><button data-v48-mark-close>×</button></header><main class="v48-mark-form"><label><span>SHIP TO / 收货信息</span><textarea data-v48-var="shipTo">${esc(v.shipTo||'')}</textarea></label><label><span>PO Number</span><input data-v48-var="poNumber" value="${esc(v.poNumber||'')}"></label><label><span>SKU</span><input data-v48-var="sku" value="${esc(v.sku||'')}"></label><label><span>Carton No.</span><input data-v48-var="cartonNo" value="${esc(v.cartonNo||'')}"></label><label><span>Quantity</span><input data-v48-var="quantity" value="${esc(v.quantity||'')}"></label><label><span>Net Weight</span><input data-v48-var="netWeight" value="${esc(v.netWeight||'')}"></label><label><span>Gross Weight</span><input data-v48-var="grossWeight" value="${esc(v.grossWeight||'')}"></label><label><span>MEAS / Dimension</span><input data-v48-var="dimensionLine" value="${esc(v.dimensionLine||'')}"></label><label><span>Country of Origin</span><input data-v48-var="countryOfOrigin" value="${esc(v.countryOfOrigin||'')}"></label><div class="v48-mark-preview" data-v48-mark-preview></div></main><footer><button data-v48-mark-cancel>取消</button><button data-v48-mark-save>只保存变量</button><button class="primary" data-v48-mark-insert>保存并插入 Shipping Mark</button></footer></div>`;document.body.appendChild(host);const values=()=>Object.fromEntries([...host.querySelectorAll('[data-v48-var]')].map(x=>[x.dataset.v48Var,x.value]));const refresh=()=>host.querySelector('[data-v48-mark-preview]').textContent=markPreview(values());host.querySelectorAll('[data-v48-var]').forEach(x=>x.addEventListener('input',refresh));const save=()=>{const next=readState();next.variables={...next.variables,...values()};writeState(next);return next};host.querySelector('[data-v48-mark-close]').onclick=closeMarkStudio;host.querySelector('[data-v48-mark-cancel]').onclick=closeMarkStudio;host.querySelector('[data-v48-mark-save]').onclick=()=>{save();closeMarkStudio()};host.querySelector('[data-v48-mark-insert]').onclick=()=>{save();closeMarkStudio();document.querySelector('[data-tool="mark"]')?.click()};host.addEventListener('click',e=>{if(e.target===host)closeMarkStudio()});refresh()}
function shippingMarkPanel(){if(!activeEditor()||activeTab()!=='Marks')return;const right=rightPanel();if(!right||right.querySelector('.v48-shipping-mark'))return;const host=document.createElement('section');host.className='v48-shipping-mark';host.innerHTML=`<div class="v48-title"><b>Shipping Mark Studio</b><span>唛头专用工作流</span></div><button class="v48-mark-open" data-v48-open-mark>编辑收货 / PO / SKU / 箱号 / 重量 / MEAS / 产地</button>`;right.prepend(host);host.querySelector('[data-v48-open-mark]').onclick=openMarkStudio}
function decorate(){if(!activeEditor())return;parametricPanel();shippingMarkPanel()}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;decorate()})}
observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true});decorate();
window.BoxStudioV48={version:'V0.48',normalizeStructure:normalizeParametricStructureV48,validateStructure:validateParametricStructureV48,bendProfile:bendProfileV48,openShippingMarkStudio:openMarkStudio,runPreflight:runPreflightV48,free:true};
