import { STORAGE_KEY, defaultState, cloneState } from './model.js';
import { mountArtworkProof } from './threeArtworkProof.js';
import { disposeThreePreview } from './threePreview.js';
import { ensureLinkedWorkspaceV49, selectLinkedPanelV49, setLinkedFoldProgressV49, buildLinkedWorkspaceModelV49, cycleLinkedPanelV49, linkedWorkspaceAcceptanceV49, V49_FOLD_PRESETS, V49_PRODUCT_VERSION } from './linkedWorkspaceV49.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clampFold=v=>Math.max(0,Math.min(100,num(v,100)));
let proof=null,activeCanvas=null,animation=0,queued=false,retryTimer=0;

function readState(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'),base=cloneState(defaultState),merged=parsed?{...base,...parsed,structure:{...base.structure,...(parsed.structure||{})},variables:{...base.variables,...(parsed.variables||{})}}:base;return ensureLinkedWorkspaceV49(merged)}catch{return ensureLinkedWorkspaceV49(cloneState(defaultState))}}
function persist(state){state.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function polygon(panel){if(Array.isArray(panel?.points)&&panel.points.length>=3)return`<polygon points="${panel.points.map(p=>`${num(p[0])},${num(p[1])}`).join(' ')}"/>`;return`<rect x="${num(panel?.x)}" y="${num(panel?.y)}" width="${Math.max(.01,num(panel?.w,1))}" height="${Math.max(.01,num(panel?.h,1))}"/>`}
function lineSvg(l,cls){return`<line class="${cls}" x1="${num(l.x1)}" y1="${num(l.y1)}" x2="${num(l.x2)}" y2="${num(l.y2)}"/>`}

function panelMapSvg(model){const g=model.review.geo;return `<svg class="v49-map-svg" viewBox="0 0 ${Math.max(1,g.width)} ${Math.max(1,g.height)}" xmlns="http://www.w3.org/2000/svg"><rect class="sheet" width="100%" height="100%"/>${(g.creaseLines||[]).map(l=>lineSvg(l,'crease')).join('')}${(g.cutLines||[]).map(l=>lineSvg(l,'cut')).join('')}${model.records.map(r=>{const p=g.panelMap?.[r.nodeId]||g.panelMap?.[r.panelId];return`<g class="panel-hit ${r.selected?'selected':''}" data-v49-panel="${esc(r.panelId)}">${polygon(p)}<title>${esc(r.label)}</title></g>`}).join('')}</svg>`}
function selectedCard(model){const r=model.selected;if(!r)return'<div class="v49-empty">没有可联动面板。</div>';return `<div class="v49-selected-card"><div><span>当前面</span><b>${esc(r.label)}</b><small>${esc(r.panelId)} · ${esc(r.role)}</small></div><div class="v49-metrics"><span><b>${r.bounds.w.toFixed(1)} × ${r.bounds.h.toFixed(1)}</b><small>面板尺寸 mm</small></span><span><b>${r.artworkCount}</b><small>图文对象</small></span><span><b>${r.hinges}</b><small>关联折线</small></span></div><button class="primary" data-v49-edit-face>在 2D 中编辑此面</button></div>`}
function panelList(model){return `<div class="v49-panel-list">${model.records.map(r=>`<button data-v49-list-panel="${esc(r.panelId)}" class="${r.selected?'active':''}"><span>${esc(r.label)}</span><small>${esc(r.role)} · ${r.artworkCount} objects</small></button>`).join('')}</div>`}

let currentState=null;
function commitSelection(root,panelId,source){currentState=selectLinkedPanelV49(currentState,panelId,{source});persist(currentState);proof?.setSelectedPanel?.(currentState.linkedV49.selectedPanelId);renderSelection(root);window.dispatchEvent(new CustomEvent('boxstudio:v49-panel-selection',{detail:{panelId:currentState.linkedV49.selectedPanelId,source}}))}
function renderSelection(root){const model=buildLinkedWorkspaceModelV49(currentState),map=root.querySelector('[data-v49-map]'),info=root.querySelector('[data-v49-info]'),list=root.querySelector('[data-v49-list]'),badge=root.querySelector('[data-v49-selected-badge]');if(map)map.innerHTML=panelMapSvg(model);if(info)info.innerHTML=selectedCard(model);if(list)list.innerHTML=panelList(model);if(badge)badge.textContent=model.selected?`${model.selected.label} · ${model.selected.panelId}`:'No panel';bindSelection(root);return model}
function bindSelection(root){root.querySelectorAll('[data-v49-panel],[data-v49-list-panel]').forEach(el=>el.onclick=event=>{event.preventDefault();const id=el.dataset.v49Panel||el.dataset.v49ListPanel;commitSelection(root,id,'2d')});const edit=root.querySelector('[data-v49-edit-face]');if(edit)edit.onclick=()=>{currentState=selectLinkedPanelV49(currentState,currentState.linkedV49.selectedPanelId,{source:'2d-edit'});currentState.page='editor';currentState.editorTab='Design';persist(currentState);if(window.BoxStudioEditor?.reloadFromStorage)window.BoxStudioEditor.reloadFromStorage({history:false});else location.reload()}}
function updateFoldUi(root,value){const v=Math.round(clampFold(value));const main=document.querySelector('#foldRange'),mainLabel=document.querySelector('#foldLabel'),local=root.querySelector('[data-v49-fold]'),label=root.querySelector('[data-v49-fold-label]');if(main)main.value=String(v);if(mainLabel)mainLabel.textContent=`${v}%`;if(local)local.value=String(v);if(label)label.textContent=`${v}%`;root.querySelectorAll('[data-v49-fold-preset]').forEach(b=>b.classList.toggle('active',Number(b.dataset.v49FoldPreset)===v))}
function emitFold(value){window.dispatchEvent(new CustomEvent('boxstudio:v49-fold',{detail:{progress:value}}))}
function setFold(root,value){currentState=setLinkedFoldProgressV49(currentState,value);persist(currentState);proof?.setProgress?.(currentState.foldProgress);updateFoldUi(root,currentState.foldProgress);emitFold(currentState.foldProgress)}
function setFoldTransient(root,value){const v=clampFold(value);currentState.foldProgress=v;currentState.linkedV49={...(currentState.linkedV49||{}),lastFoldProgress:v};proof?.setProgress?.(v);updateFoldUi(root,v);emitFold(v)}
function stopAnimation(){if(animation){clearTimeout(animation);animation=0}}
function playFold(root){stopAnimation();const start=clampFold(currentState.foldProgress),end=start>=50?0:100,duration=matchMedia('(prefers-reduced-motion: reduce)').matches?0:1600,started=performance.now();const tick=()=>{if(!root.isConnected){stopAnimation();return;}const t=duration?Math.min(1,(performance.now()-started)/duration):1,s=t*t*(3-2*t);setFoldTransient(root,start+(end-start)*s);if(t<1)animation=setTimeout(tick,16);else{animation=0;setFold(root,end)}};animation=setTimeout(tick,0)}

function bindControls(root){const main=document.querySelector('#foldRange'),local=root.querySelector('[data-v49-fold]');if(main)main.oninput=e=>{stopAnimation();setFold(root,e.target.value)};if(local)local.oninput=e=>{stopAnimation();setFold(root,e.target.value)};root.querySelectorAll('[data-v49-fold-preset]').forEach(b=>b.onclick=()=>{stopAnimation();setFold(root,b.dataset.v49FoldPreset)});root.querySelector('[data-v49-play]').onclick=()=>playFold(root);root.querySelector('[data-v49-prev]').onclick=()=>{currentState=cycleLinkedPanelV49(currentState,-1);persist(currentState);proof?.setSelectedPanel?.(currentState.linkedV49.selectedPanelId);renderSelection(root)};root.querySelector('[data-v49-next]').onclick=()=>{currentState=cycleLinkedPanelV49(currentState,1);persist(currentState);proof?.setSelectedPanel?.(currentState.linkedV49.selectedPanelId);renderSelection(root)};root.querySelector('[data-v49-reset]').onclick=()=>proof?.setView?.({yaw:.55,pitch:-.34,zoom:1})}

function mountLinkedProof(root,canvas){const model=buildLinkedWorkspaceModelV49(currentState);proof?.dispose?.();canvas.innerHTML='';proof=mountArtworkProof(canvas,currentState,model.review.geo,model.review.graph,{selectedPanelId:model.selected?.panelId||null,materialStyle:model.review.material,onStatus:status=>{const el=root.querySelector('[data-v49-status]');if(el)el.textContent=`${status.panels} panels · ${status.texturedPanels} textured · ${status.seamWarnings} seam warnings`},onSelectPanel:panelId=>{currentState=selectLinkedPanelV49(currentState,panelId,{source:'3d'});persist(currentState);proof?.setSelectedPanel?.(panelId);renderSelection(root);window.dispatchEvent(new CustomEvent('boxstudio:v49-panel-selection',{detail:{panelId,source:'3d'}}))}})}

function enhance3D(){const canvas=document.querySelector('#threeCanvas'),page=canvas?.closest('.three-page');if(!canvas||!page||canvas.dataset.v49Linked==='true')return;if(!canvas.querySelector('canvas')){clearTimeout(retryTimer);retryTimer=setTimeout(schedule,40);return}disposeThreePreview();stopAnimation();proof?.dispose?.();proof=null;currentState=readState();canvas.dataset.v49Linked='true';page.classList.add('v49-linked-page');const grid=document.createElement('div');grid.className='v49-linked-grid';canvas.parentNode.insertBefore(grid,canvas);const side=document.createElement('aside');side.className='v49-map-pane';side.innerHTML=`<div class="v49-pane-head"><div><span>2D PANEL MAP</span><b>点击 2D 或 3D 面板双向联动</b></div><span data-v49-selected-badge></span></div><div data-v49-map class="v49-map"></div><div class="v49-nav"><button data-v49-prev>← 上一面</button><button data-v49-next>下一面 →</button></div><div data-v49-info></div><div data-v49-list></div>`;const stage=document.createElement('section');stage.className='v49-proof-pane';stage.innerHTML=`<div class="v49-proof-head"><div><span>LIVE 3D</span><b>点击箱体任意面同步定位 2D</b></div><span data-v49-status>Preparing linked proof…</span></div><div class="v49-foldbar"><div class="v49-fold-presets">${V49_FOLD_PRESETS.map(p=>`<button data-v49-fold-preset="${p.progress}">${esc(p.label)}</button>`).join('')}</div><label><span>Fold</span><input data-v49-fold type="range" min="0" max="100" value="${currentState.foldProgress}"><b data-v49-fold-label>${currentState.foldProgress}%</b></label><button data-v49-play>▶ 开合动画</button><button data-v49-reset>重置视角</button></div>`;grid.append(side,stage);stage.appendChild(canvas);const help=page.querySelector('.three-help');if(help)help.textContent='V0.49：2D 面板图与 3D 箱体双向选面 · 拖动旋转 · 滚轮缩放 · 0% 展开 / 100% 成型';renderSelection(page);bindControls(page);mountLinkedProof(page,canvas);updateFoldUi(page,currentState.foldProgress);const acceptance=linkedWorkspaceAcceptanceV49(currentState);page.dataset.v49Acceptance=acceptance.ok?'pass':'fail';document.body.dataset.v49LinkedWorkspace='true';window.BoxStudioV49={version:V49_PRODUCT_VERSION,getState:()=>structuredClone(currentState),getAcceptance:()=>linkedWorkspaceAcceptanceV49(currentState),selectPanel:id=>commitSelection(page,id,'api'),setFold:v=>setFold(page,v),play:()=>playFold(page)} }
function cleanupIfNeeded(){const canvas=document.querySelector('#threeCanvas');if(activeCanvas&&activeCanvas!==canvas){stopAnimation();proof?.dispose?.();proof=null;activeCanvas=null}}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;cleanupIfNeeded();const canvas=document.querySelector('#threeCanvas');if(canvas){activeCanvas=canvas;enhance3D()}})}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
