import { STORAGE_KEY } from './model.js';
import { buildLinkedWorkspaceModelV49 } from './linkedWorkspaceV49.js';
import { mountArtworkProofV50 } from './threeArtworkProofV50.js';
import { ensureFoldAuthoringV50, selectFoldEdgeV50, setFoldEdgeAngleV50, flipFoldDirectionV50, moveFoldEdgeV50, setFoldTimelineV50, setSequenceEnabledV50, setExplodeV50, setDimensionsVisibleV50, buildFoldAuthoringModelV50, rendererAuthoringV50, foldAuthoringAcceptanceV50, V50_PRODUCT_VERSION } from './foldAuthoringV50.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
let proof=null,authoringState=null,graph=null,geo=null,linked=null,root=null,playTimer=0,queued=false;

function baseState(){return window.BoxStudioV49?.getState?.()||null}
function mergeBase(){const base=baseState();if(!base)return null;const saved=authoringState?.foldAuthoringV50||readPersistedAuthoring();return saved?{...base,foldAuthoringV50:structuredClone(saved)}:base}
function readPersistedAuthoring(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')?.foldAuthoringV50||null}catch{return null}}
function persistAuthoring(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');raw.foldAuthoringV50=structuredClone(authoringState.foldAuthoringV50);raw.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(raw))}catch{}}
function stopPlay(){if(playTimer){clearTimeout(playTimer);playTimer=0}}

function rebuildBase(){const merged=mergeBase();if(!merged)return null;linked=buildLinkedWorkspaceModelV49(merged);graph=linked.review.graph;geo=linked.review.geo;authoringState=ensureFoldAuthoringV50(merged,graph);return linked}
function currentModel(){return buildFoldAuthoringModelV50(authoringState,graph,geo)}
function applyProof({persist=true,render=true}={}){const model=currentModel();authoringState=model.state;if(persist)persistAuthoring();proof?.setAuthoring?.(rendererAuthoringV50(model));if(model.sequenceEnabled)proof?.setProgress?.(100);else proof?.setProgress?.(num(baseState()?.foldProgress,100));proof?.setSelectedPanel?.(baseState()?.linkedV49?.selectedPanelId||model.panelId||null);if(render)renderAuthoring(model);const acceptance=foldAuthoringAcceptanceV50(authoringState,graph,geo);if(root)root.dataset.v50Acceptance=acceptance.ok?'pass':'fail';return model}

function timelineRows(model){return `<div class="v50-timeline-list">${model.edges.map(edge=>`<button data-v50-edge-row="${esc(edge.key)}" class="${edge.key===model.selectedEdge?.key?'active':''}"><b>${edge.order}</b><span>${esc(edge.label)}</span><small>${edge.angle.toFixed(0)}°${model.sequenceEnabled?` · ${Math.round(edge.localProgress||0)}%`:''}</small></button>`).join('')}</div>`}
function renderAuthoring(model=currentModel()){
  if(!root)return;const selected=model.selectedEdge,select=root.querySelector('[data-v50-edge]'),angle=root.querySelector('[data-v50-angle]'),timeline=root.querySelector('[data-v50-timeline]'),timelineLabel=root.querySelector('[data-v50-timeline-label]'),explode=root.querySelector('[data-v50-explode]'),explodeLabel=root.querySelector('[data-v50-explode-label]'),sequence=root.querySelector('[data-v50-sequence]'),dims=root.querySelector('[data-v50-dimensions]'),rows=root.querySelector('[data-v50-timeline-rows]'),dimension=root.querySelector('[data-v50-panel-dimension]');
  if(select){select.innerHTML=model.edges.map(edge=>`<option value="${esc(edge.key)}" ${edge.key===selected?.key?'selected':''}>${edge.order}. ${esc(edge.label)} · ${edge.angle.toFixed(0)}°</option>`).join('')}
  if(angle)angle.value=selected?String(selected.angle):'0';if(timeline)timeline.value=String(model.timeline);if(timelineLabel)timelineLabel.textContent=`${Math.round(model.timeline)}%`;if(explode)explode.value=String(model.explode);if(explodeLabel)explodeLabel.textContent=`${Math.round(model.explode)}%`;if(sequence)sequence.checked=model.sequenceEnabled;if(dims)dims.checked=model.dimensionsVisible;if(rows)rows.innerHTML=timelineRows(model);if(dimension)dimension.textContent=model.panelBounds?`${model.panelBounds.w.toFixed(1)} × ${model.panelBounds.h.toFixed(1)} mm`:'—';
  bindDynamic();
}
function selectEdge(key){authoringState=selectFoldEdgeV50(authoringState,graph,key,{source:'v50-ui'});applyProof()}
function bindDynamic(){if(!root)return;root.querySelectorAll('[data-v50-edge-row]').forEach(button=>button.onclick=()=>selectEdge(button.dataset.v50EdgeRow));}

function bindControls(){
  const select=root.querySelector('[data-v50-edge]'),angle=root.querySelector('[data-v50-angle]'),flip=root.querySelector('[data-v50-flip]'),up=root.querySelector('[data-v50-up]'),down=root.querySelector('[data-v50-down]'),timeline=root.querySelector('[data-v50-timeline]'),sequence=root.querySelector('[data-v50-sequence]'),explode=root.querySelector('[data-v50-explode]'),dims=root.querySelector('[data-v50-dimensions]'),play=root.querySelector('[data-v50-play]'),reset=root.querySelector('[data-v49-reset]');
  select.onchange=()=>selectEdge(select.value);
  angle.onchange=()=>{authoringState=setFoldEdgeAngleV50(authoringState,graph,authoringState.foldAuthoringV50.selectedEdgeKey,angle.value);applyProof()};
  flip.onclick=()=>{authoringState=flipFoldDirectionV50(authoringState,graph,authoringState.foldAuthoringV50.selectedEdgeKey);applyProof()};
  up.onclick=()=>{authoringState=moveFoldEdgeV50(authoringState,graph,authoringState.foldAuthoringV50.selectedEdgeKey,-1);applyProof()};
  down.onclick=()=>{authoringState=moveFoldEdgeV50(authoringState,graph,authoringState.foldAuthoringV50.selectedEdgeKey,1);applyProof()};
  timeline.oninput=()=>{stopPlay();authoringState=setFoldTimelineV50(authoringState,graph,timeline.value,{enableSequence:true});applyProof({persist:false});};timeline.onchange=()=>persistAuthoring();
  sequence.onchange=()=>{authoringState=setSequenceEnabledV50(authoringState,graph,sequence.checked);applyProof()};
  explode.oninput=()=>{authoringState=setExplodeV50(authoringState,graph,explode.value);applyProof({persist:false});};explode.onchange=()=>persistAuthoring();
  dims.onchange=()=>{authoringState=setDimensionsVisibleV50(authoringState,graph,dims.checked);applyProof()};
  play.onclick=()=>playSequence();reset?.addEventListener('click',()=>proof?.setView?.({yaw:.55,pitch:-.34,zoom:1}));
}

function playSequence(){stopPlay();authoringState=setSequenceEnabledV50(authoringState,graph,true);let start=num(authoringState.foldAuthoringV50.timeline,0),end=start>=99?0:100,step=0,steps=12;const tick=()=>{step++;const t=Math.min(1,step/steps),s=t*t*(3-2*t),value=start+(end-start)*s;authoringState=setFoldTimelineV50(authoringState,graph,value,{enableSequence:true});applyProof({persist:false,render:step===steps||step%2===0});if(step<steps)playTimer=setTimeout(tick,45);else{playTimer=0;persistAuthoring();renderAuthoring(currentModel())}};playTimer=setTimeout(tick,0)}

function mountRenderer(){const canvas=root.querySelector('#threeCanvas'),model=currentModel();if(!canvas)return;canvas.innerHTML='';proof=mountArtworkProofV50(canvas,authoringState,geo,graph,{selectedPanelId:baseState()?.linkedV49?.selectedPanelId||model.panelId||null,materialStyle:linked.review.material,authoring:rendererAuthoringV50(model),onStatus:status=>{const el=root.querySelector('[data-v49-status]');if(el)el.textContent=`${status.panels} panels · V0.50 fold authoring · ${status.seamWarnings} seam warnings`},onSelectPanel:panelId=>window.BoxStudioV49?.selectPanel?.(panelId)});canvas.dataset.v50Renderer='true'}

function authoringMarkup(){return `<div class="v50-authoring" data-v50-authoring><div class="v50-authoring-head"><div><span>V0.50 FOLD AUTHORING</span><b>单折线角度 / 方向 / 顺序 / 爆炸图 / 尺寸联动</b></div><span class="v50-panel-dimension" data-v50-panel-dimension>—</span></div><div class="v50-controls"><label class="wide"><span>Fold edge</span><select data-v50-edge></select></label><label><span>Angle</span><input data-v50-angle type="number" min="-180" max="180" step="1"></label><button data-v50-flip>↔ 翻转方向</button><div class="v50-order"><button data-v50-up>↑ 提前</button><button data-v50-down>↓ 延后</button></div><label class="toggle"><input data-v50-sequence type="checkbox"><span>顺序折叠 Timeline</span></label><label class="wide"><span>Timeline <b data-v50-timeline-label>100%</b></span><input data-v50-timeline type="range" min="0" max="100" value="100"></label><button class="primary" data-v50-play>▶ 播放顺序</button><label class="wide"><span>Exploded view <b data-v50-explode-label>0%</b></span><input data-v50-explode type="range" min="0" max="100" value="0"></label><label class="toggle"><input data-v50-dimensions type="checkbox" checked><span>3D 尺寸标注</span></label></div><div data-v50-timeline-rows></div></div>`}

function enhance(){if(!window.BoxStudioV49||document.body.dataset.v49LinkedWorkspace!=='true')return false;const page=document.querySelector('.three-page.v49-linked-page');if(!page||page.dataset.v50Ready==='true')return Boolean(page);root=page;if(!rebuildBase())return false;const foldbar=root.querySelector('.v49-foldbar');if(!foldbar)return false;foldbar.insertAdjacentHTML('afterend',authoringMarkup());mountRenderer();bindControls();applyProof({persist:true});root.dataset.v50Ready='true';document.body.dataset.v50FoldAuthoring='true';const acceptance=foldAuthoringAcceptanceV50(authoringState,graph,geo);root.dataset.v50Acceptance=acceptance.ok?'pass':'fail';window.BoxStudioV50={version:V50_PRODUCT_VERSION,getState:()=>structuredClone(authoringState),getModel:()=>structuredClone(currentModel()),getAcceptance:()=>foldAuthoringAcceptanceV50(authoringState,graph,geo),getProof:()=>proof,selectEdge, setEdgeAngle:value=>{authoringState=setFoldEdgeAngleV50(authoringState,graph,authoringState.foldAuthoringV50.selectedEdgeKey,value);return applyProof()},flipEdge:()=>{authoringState=flipFoldDirectionV50(authoringState,graph,authoringState.foldAuthoringV50.selectedEdgeKey);return applyProof()},setTimeline:value=>{authoringState=setFoldTimelineV50(authoringState,graph,value,{enableSequence:true});return applyProof()},setExplode:value=>{authoringState=setExplodeV50(authoringState,graph,value);return applyProof()},setDimensions:visible=>{authoringState=setDimensionsVisibleV50(authoringState,graph,visible);return applyProof()},play:playSequence};return true}

window.addEventListener('boxstudio:v49-panel-selection',()=>{if(!root)return;const saved=authoringState?.foldAuthoringV50,recent=baseState();if(!recent)return;authoringState=ensureFoldAuthoringV50({...recent,foldAuthoringV50:saved},graph);proof?.setSelectedPanel?.(recent.linkedV49?.selectedPanelId||null);applyProof({persist:true})});
window.addEventListener('boxstudio:v49-fold',event=>{if(!root)return;authoringState=setSequenceEnabledV50(authoringState,graph,false);proof?.setAuthoring?.(rendererAuthoringV50(currentModel()));proof?.setProgress?.(num(event.detail?.progress,100));persistAuthoring();renderAuthoring(currentModel())});
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;if(!document.querySelector('.three-page.v49-linked-page')){stopPlay();proof?.dispose?.();proof=null;root=null;return}enhance()})}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
