import { STORAGE_KEY } from './model.js';
import { buildLinkedWorkspaceModelV49 } from './linkedWorkspaceV49.js';
import { ensureFoldSequenceV51, buildFoldSequenceModelV51, setCurrentStepV51, stepFoldV51, setEdgeStepV51, moveEdgeStepV51, splitEdgeStepV51, mergeEdgeWithPreviousV51, setCollisionBlockingV51, setCollisionEnabledV51, rendererAuthoringV51, scanFoldSequenceV51, foldSequenceAcceptanceV51, V51_PRODUCT_VERSION } from './foldSequenceV51.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
let root=null,sequenceState=null,linked=null,graph=null,geo=null,lastReport=null,playTimer=0,queued=false,preflightCache={token:null,result:null};

function readProject(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}}
function v50State(){return window.BoxStudioV50?.getState?.()||readProject()}
function persistedV51(){return readProject()?.foldSequenceV51||null}
function stopPlay(){if(playTimer){clearTimeout(playTimer);playTimer=0}}
function rebuild(){const base=v50State();if(!base)return false;linked=buildLinkedWorkspaceModelV49(base);graph=linked.review.graph;geo=linked.review.geo;const old=sequenceState?.foldSequenceV51||persistedV51();sequenceState=ensureFoldSequenceV51(old?{...base,foldSequenceV51:structuredClone(old)}:base,graph);return true}
function persist(){try{const raw=readProject()||{};raw.foldSequenceV51=structuredClone(sequenceState.foldSequenceV51);if(sequenceState.foldAuthoringV50)raw.foldAuthoringV50=structuredClone(sequenceState.foldAuthoringV50);raw.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(raw))}catch{}}
function model(){return buildFoldSequenceModelV51(sequenceState,graph,geo)}
function selectedEdgeKey(){return window.BoxStudioV50?.getModel?.()?.selectedEdge?.key||model().edges[0]?.key||null}

function collisionClass(report=lastReport){if(!report)return'';if(report.penetrations?.length)return'error';if(report.overlaps?.length)return'warning';return''}
function collisionText(report=lastReport){if(!report)return'未检测';return `${report.penetrations.length} 穿插 · ${report.overlaps.length} 搭接 · ${report.samples} samples`}
function hitRows(report=lastReport){if(!report)return'<div class="v51-clear">点击“检测折叠碰撞”检查整个折叠路径。</div>';const hits=[...(report.penetrations||[]),...(report.overlaps||[])];if(!hits.length)return'<div class="v51-clear">✓ 当前折叠路径未发现非相邻面板穿插或共面搭接。</div>';return `<div class="v51-collisions">${hits.map(hit=>`<button class="v51-hit ${hit.type}" data-v51-hit-panel="${esc(hit.a)}"><span>${hit.type==='penetration'?'穿插':'搭接'} · ${esc(hit.a)} ↔ ${esc(hit.b)}</span><small>${hit.firstTimeline.toFixed(1)}–${hit.lastTimeline.toFixed(1)}%</small></button>`).join('')}</div>`}
function keyframesMarkup(m){return `<div class="v51-keyframes">${m.keyframes.map(k=>`<button data-v51-keyframe="${k.step}" class="${k.step===m.currentStep?'active':''}"><b>${esc(k.label)}</b><small>${Math.round(k.timeline)}% · ${k.edgeKeys.length} folds</small></button>`).join('')}</div>`}
function markup(){return `<div class="v51-sequence" data-v51-sequence><div class="v51-head"><div><span>V0.51 FOLD SEQUENCE + COLLISION</span><b>关键帧 / 单步播放 / Step 分组 / 折叠路径穿插检测</b></div><span class="v51-collision-badge" data-v51-collision-badge>未检测</span></div><div class="v51-controls"><button data-v51-prev>← 上一步</button><button data-v51-next>下一步 →</button><button class="primary" data-v51-play>▶ 单步播放</button><label><span>当前折线 Step</span><input data-v51-step type="number" min="1" step="1"></label><button data-v51-step-up>Step −</button><button data-v51-step-down>Step +</button><button data-v51-merge>与上一步合并</button><button data-v51-split>拆分为新一步</button><button class="primary wide" data-v51-scan>检测折叠碰撞</button><label class="toggle"><input data-v51-collision-enable type="checkbox" checked><span>启用碰撞检测</span></label><label class="toggle"><input data-v51-block type="checkbox"><span>穿插按 Error 处理</span></label></div><div data-v51-keyframes></div><div data-v51-collisions></div></div>`}

function applyRenderer(){const m=model(),proof=window.BoxStudioV50?.getProof?.();proof?.setAuthoring?.(rendererAuthoringV51(m,lastReport));proof?.setProgress?.(100);return m}
function render(){if(!root)return;const m=applyRenderer(),stepInput=root.querySelector('[data-v51-step]'),badge=root.querySelector('[data-v51-collision-badge]'),keyframes=root.querySelector('[data-v51-keyframes]'),hits=root.querySelector('[data-v51-collisions]'),enable=root.querySelector('[data-v51-collision-enable]'),block=root.querySelector('[data-v51-block]'),selected=m.edges.find(e=>e.key===selectedEdgeKey());if(stepInput){stepInput.max=String(Math.max(1,m.stepCount));stepInput.value=String(selected?.step||1)}if(badge){badge.className=`v51-collision-badge ${collisionClass()}`;badge.textContent=collisionText()}if(keyframes)keyframes.innerHTML=keyframesMarkup(m);if(hits)hits.innerHTML=hitRows();if(enable)enable.checked=m.collisionEnabled;if(block)block.checked=m.blockOnPenetration;bindDynamic();root.dataset.v51Acceptance=foldSequenceAcceptanceV51(sequenceState,graph,geo,{skipCollision:true}).ok?'pass':'fail'}
function bindDynamic(){root?.querySelectorAll('[data-v51-keyframe]').forEach(b=>b.onclick=()=>setStep(Number(b.dataset.v51Keyframe)));root?.querySelectorAll('[data-v51-hit-panel]').forEach(b=>b.onclick=()=>window.BoxStudioV49?.selectPanel?.(b.dataset.v51HitPanel))}

function syncFromV50(){const fresh=v50State();if(!fresh)return;const keep=sequenceState?.foldSequenceV51||persistedV51();sequenceState=ensureFoldSequenceV51(keep?{...fresh,foldSequenceV51:structuredClone(keep)}:fresh,graph)}
function setStep(step){stopPlay();syncFromV50();sequenceState=setCurrentStepV51(sequenceState,graph,geo,step);persist();window.BoxStudioV50?.setTimeline?.(sequenceState.foldAuthoringV50.timeline);syncFromV50();sequenceState.foldSequenceV51.currentStep=Math.max(0,Math.min(model().stepCount,Math.round(num(step,0))));persist();render()}
function moveStep(delta){const key=selectedEdgeKey();if(!key)return;syncFromV50();sequenceState=moveEdgeStepV51(sequenceState,graph,key,delta);lastReport=null;persist();render()}
function setSelectedStep(value){const key=selectedEdgeKey();if(!key)return;syncFromV50();sequenceState=setEdgeStepV51(sequenceState,graph,key,value);lastReport=null;persist();render()}
function splitSelected(){const key=selectedEdgeKey();if(!key)return;syncFromV50();sequenceState=splitEdgeStepV51(sequenceState,graph,key);lastReport=null;persist();render()}
function mergeSelected(){const key=selectedEdgeKey();if(!key)return;syncFromV50();sequenceState=mergeEdgeWithPreviousV51(sequenceState,graph,key);lastReport=null;persist();render()}
function replaceEdgeSteps(rows=[]){syncFromV50();const incoming=new Map((rows||[]).map(row=>[row.key,Math.max(1,Math.round(num(row.step,1)))])),current=sequenceState.foldSequenceV51?.edgeSteps||[];sequenceState.foldSequenceV51={...sequenceState.foldSequenceV51,edgeSteps:current.map(row=>({...row,step:incoming.get(row.key)??row.step})),currentStep:0,lastSource:'runtime-sequence-replace'};sequenceState=ensureFoldSequenceV51(sequenceState,graph);sequenceState.foldSequenceV51.currentStep=0;sequenceState.foldSequenceV51.lastSource='runtime-sequence-replace';lastReport=null;persist();render();window.dispatchEvent(new CustomEvent('boxstudio:v51-sequence-replaced',{detail:{steps:model().stepCount}}));return model()}
function scan(){syncFromV50();lastReport=scanFoldSequenceV51(sequenceState,graph,geo);render();window.dispatchEvent(new CustomEvent('boxstudio:v51-collision-scan',{detail:{penetrations:lastReport.penetrations.length,overlaps:lastReport.overlaps.length,samples:lastReport.samples}}));return lastReport}
function playSteps(){stopPlay();const m=model();let step=m.currentStep>=m.stepCount?0:m.currentStep;const tick=()=>{if(step>m.stepCount){playTimer=0;return}setStep(step);step++;if(step<=m.stepCount)playTimer=setTimeout(tick,260);else playTimer=0};tick()}

function bind(){const prev=root.querySelector('[data-v51-prev]'),next=root.querySelector('[data-v51-next]'),play=root.querySelector('[data-v51-play]'),step=root.querySelector('[data-v51-step]'),up=root.querySelector('[data-v51-step-up]'),down=root.querySelector('[data-v51-step-down]'),merge=root.querySelector('[data-v51-merge]'),split=root.querySelector('[data-v51-split]'),scanButton=root.querySelector('[data-v51-scan]'),enable=root.querySelector('[data-v51-collision-enable]'),block=root.querySelector('[data-v51-block]');prev.onclick=()=>{syncFromV50();const nextState=stepFoldV51(sequenceState,graph,geo,-1);setStep(nextState.foldSequenceV51.currentStep)};next.onclick=()=>{syncFromV50();const nextState=stepFoldV51(sequenceState,graph,geo,1);setStep(nextState.foldSequenceV51.currentStep)};play.onclick=playSteps;step.onchange=()=>setSelectedStep(step.value);up.onclick=()=>moveStep(-1);down.onclick=()=>moveStep(1);merge.onclick=mergeSelected;split.onclick=splitSelected;scanButton.onclick=scan;enable.onchange=()=>{syncFromV50();sequenceState=setCollisionEnabledV51(sequenceState,graph,enable.checked);lastReport=null;persist();render()};block.onchange=()=>{syncFromV50();sequenceState=setCollisionBlockingV51(sequenceState,graph,block.checked);persist();render()}}

function enhance3D(){if(!window.BoxStudioV50||document.body.dataset.v50FoldAuthoring!=='true')return false;const page=document.querySelector('.three-page.v49-linked-page');if(!page)return false;if(page.dataset.v51Ready==='true'){root=page;return true}root=page;if(!rebuild())return false;const anchor=root.querySelector('[data-v50-authoring]');if(!anchor)return false;anchor.insertAdjacentHTML('afterend',markup());bind();lastReport=scanFoldSequenceV51(sequenceState,graph,geo);persist();render();page.dataset.v51Ready='true';document.body.dataset.v51FoldSequence='true';window.BoxStudioV51={version:V51_PRODUCT_VERSION,getState:()=>structuredClone(sequenceState),getModel:()=>structuredClone(model()),getAcceptance:(options={})=>foldSequenceAcceptanceV51(sequenceState,graph,geo,options),scanCollisions:scan,setStep,nextStep:()=>setStep(model().currentStep+1),previousStep:()=>setStep(model().currentStep-1),setSelectedEdgeStep:setSelectedStep,replaceEdgeSteps,mergeSelected,splitSelected,setBlocking:enabled=>{sequenceState=setCollisionBlockingV51(sequenceState,graph,enabled);persist();render()},play:playSteps};return true}

function preflightResult(){const raw=readProject();if(!raw)return null;const token=JSON.stringify([raw.structure,raw.foldAuthoringV50,raw.foldSequenceV51,raw.linkedV49?.selectedPanelId]);if(preflightCache.token===token)return preflightCache.result;const linkedModel=buildLinkedWorkspaceModelV49(raw),state=ensureFoldSequenceV51(raw,linkedModel.review.graph),result=foldSequenceAcceptanceV51(state,linkedModel.review.graph,linkedModel.review.geo);preflightCache={token,result};return result}
function enhancePreflight(){const list=document.querySelector('.review-page .preflight');if(!list||list.querySelector('.v51-preflight'))return false;const result=preflightResult();if(!result)return false;const severity=result.errors.length?'error':result.collisions.penetrations.length||result.collisions.overlaps.length?'warning':'pass',icon=severity==='error'?'×':severity==='warning'?'!':'✓',detail=result.collisions.enabled?`${result.summary.penetrations} penetration · ${result.summary.overlaps} overlap/contact · ${result.summary.samples} path samples${result.summary.blocking?' · penetration is blocking':''}`:'Collision scan disabled.';const wrap=document.createElement('div');wrap.className=`check ${severity} v51-preflight v51-preflight-note ${severity}`;wrap.innerHTML=`<div class="icon">${icon}</div><div><strong>V0.51 Fold Sequence Collision Check</strong><p>${esc(detail)}</p></div>`;list.appendChild(wrap);const score=document.querySelector('.review-head .score');if(score&&!score.querySelector('[data-v51-score]'))score.insertAdjacentHTML('beforeend',`<span data-v51-score class="${severity}">V0.51 ${severity.toUpperCase()}</span>`);return true}

function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;if(document.querySelector('.three-page.v49-linked-page'))enhance3D();else{stopPlay();root=null}enhancePreflight()})}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
