import { buildLinkedWorkspaceModelV49 } from './linkedWorkspaceV49.js';
import { ensureFoldSequenceV51, buildFoldSequenceModelV51, rendererAuthoringV51, scanFoldSequenceV51 } from './foldSequenceV51.js';
import { mountCollisionProofV52 } from './threeCollisionProofV52.js';
import { collisionEventsV52, locateCollisionV52, collisionHighlightV52, suggestSequenceV52, applySequenceSuggestionV52, collisionOptimizationAcceptanceV52, V52_PRODUCT_VERSION } from './collisionOptimizationV52.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let root=null,linked=null,graph=null,geo=null,state=null,proof=null,report=null,activeEventId=null,optimization=null,queued=false,rescanTimer=0,pollTimer=0;
let foldModeV77='uniform';

function v50State(){return window.BoxStudioV50?.getState?.()||null}
function v51State(){return window.BoxStudioV51?.getState?.()||null}
function rebuild(){const base=v50State();if(!base)return false;linked=buildLinkedWorkspaceModelV49(base);graph=linked.review.graph;geo=linked.review.geo;const seq=v51State()?.foldSequenceV51;state=ensureFoldSequenceV51(seq?{...base,foldSequenceV51:structuredClone(seq)}:base,graph);return true}
function model(){return buildFoldSequenceModelV51(state,graph,geo)}
function currentSelectedPanel(){return window.BoxStudioV49?.getState?.()?.linkedV49?.selectedPanelId||state?.linkedV49?.selectedPanelId||null}

function currentAuthoring(){const m=model(),base=rendererAuthoringV51(m,report),highlight=activeEventId?collisionHighlightV52(report||{},activeEventId):{penetrationPanels:[],overlapPanels:[],activePanels:[]};return{...base,...(foldModeV77==='uniform'?{edgeProgress:{}}:{}),penetrationPanels:highlight.penetrationPanels,collisionPanels:highlight.penetrationPanels,overlapPanels:highlight.overlapPanels,activePanels:highlight.activePanels}}
function refreshProof(){if(!proof)return;proof.setAuthoring(currentAuthoring());proof.setProgress(foldModeV77==='uniform'?(window.BoxStudioV49?.getState?.()?.foldProgress??100):100);proof.setSelectedPanel(currentSelectedPanel())}
function runScan({render=true}={}){if(!rebuild())return null;report=scanFoldSequenceV51(state,graph,geo);activeEventId=null;optimization=null;if(render)renderAll();return report}

function eventRows(){const events=collisionEventsV52(report||{});if(!report)return'<div class="v52-empty">尚未检测折叠路径。</div>';if(!events.length)return'<div class="v52-empty pass">✓ 当前路径没有可视化碰撞事件。</div>';return `<div class="v52-events">${events.map(event=>`<button data-v52-event="${esc(event.id)}" class="v52-event ${event.type} ${event.id===activeEventId?'active':''}"><span><b>${event.type==='penetration'?'穿插':'搭接'}</b>${esc(event.a)} ↔ ${esc(event.b)}</span><small>${event.firstTimeline.toFixed(1)}% · ${event.occurrences} samples</small></button>`).join('')}</div>`}
function optimizerRows(){if(!optimization)return'<div class="v52-empty">点击“分析避碰顺序”生成候选方案，不会自动改动当前 Step。</div>';if(!optimization.suggestions.length)return'<div class="v52-empty pass">当前顺序没有可比较的邻域候选。</div>';return `<div class="v52-suggestions">${optimization.suggestions.map(s=>`<div class="v52-suggestion ${s.improved?'improved':''}"><div><b>#${s.rank} · ${s.penetrations} 穿插 / ${s.overlaps} 搭接</b><small>Step order: ${s.order.join(' → ')} · score ${Math.round(s.score)}${s.improved?` · 改善 ${Math.round(s.improvement)}`:' · 未优于当前'}</small></div><button data-v52-apply="${s.rank-1}" ${s.improved?'':'class="secondary"'}>应用方案</button></div>`).join('')}</div>`}
function markup(){return `<div class="v52-panel" data-v52-panel><div class="v52-head"><div><span>V0.52 COLLISION VISUALIZATION + OPTIMIZER</span><b>3D 冲突高亮 / 定位关键帧 / 避碰折叠顺序建议</b></div><span class="v52-status" data-v52-status>未检测</span></div><div class="v52-actions"><button class="primary" data-v52-scan>重新检测</button><button data-v52-optimize>分析避碰顺序</button><button data-v52-clear>清除定位</button></div><div class="v52-grid"><section><h4>Collision events</h4><div data-v52-events></div></section><section><h4>Sequence suggestions</h4><div data-v52-optimizer></div></section></div></div>`}

function statusText(){if(!report)return'未检测';return `${report.penetrations?.length||0} 穿插 · ${report.overlaps?.length||0} 搭接 · ${report.samples||0} samples`}
function renderAll(){if(!root)return;refreshProof();const status=root.querySelector('[data-v52-status]'),events=root.querySelector('[data-v52-events]'),optimizer=root.querySelector('[data-v52-optimizer]');if(status){status.textContent=statusText();status.className=`v52-status ${(report?.penetrations?.length||0)?'error':(report?.overlaps?.length||0)?'warning':'pass'}`}if(events)events.innerHTML=eventRows();if(optimizer)optimizer.innerHTML=optimizerRows();bindDynamic()}
function bindDynamic(){root?.querySelectorAll('[data-v52-event]').forEach(button=>button.onclick=()=>jumpToEvent(button.dataset.v52Event));root?.querySelectorAll('[data-v52-apply]').forEach(button=>button.onclick=()=>applySuggestion(Number(button.dataset.v52Apply)))}

function jumpToEvent(id){if(!report||!rebuild())return;const m=model(),loc=locateCollisionV52(report,id,m.stepCount);if(!loc)return;activeEventId=id;window.BoxStudioV51?.setStep?.(loc.completedStep);window.BoxStudioV50?.setTimeline?.(loc.timeline);window.BoxStudioV49?.selectPanel?.(loc.panels[0]);setTimeout(()=>{rebuild();renderAll()},0)}
function optimize(){if(!rebuild())return;report=scanFoldSequenceV51(state,graph,geo);optimization=suggestSequenceV52(state,graph,geo,{limit:3,maxPasses:2});renderAll()}
function applySuggestion(index){if(!optimization?.suggestions?.[index]||!rebuild())return null;const suggestion=optimization.suggestions[index],applied=applySequenceSuggestionV52(state,graph,suggestion),replace=window.BoxStudioV51?.replaceEdgeSteps;if(typeof replace!=='function')throw new Error('V0.51 runtime replaceEdgeSteps API is required.');window.BoxStudioV50?.setTimeline?.(0);replace(applied.foldSequenceV51.edgeSteps);activeEventId=null;optimization=null;rebuild();report=scanFoldSequenceV51(state,graph,geo);renderAll();window.dispatchEvent(new CustomEvent('boxstudio:v52-sequence-applied',{detail:{order:[...suggestion.order],score:suggestion.score,penetrations:report.penetrations.length,overlaps:report.overlaps.length}}));return model()}

function mountProof(){const holder=root.querySelector('#threeCanvas');if(!holder)return false;try{window.BoxStudioV50?.getProof?.()?.dispose?.()}catch{}proof?.dispose?.();const m=model();proof=mountCollisionProofV52(holder,state,geo,graph,{selectedPanelId:currentSelectedPanel(),materialStyle:linked.review.material,authoring:currentAuthoring(),onSelectPanel:panelId=>window.BoxStudioV49?.selectPanel?.(panelId),onStatus:status=>{const el=root?.querySelector('[data-v49-status]');if(el)el.textContent=`${status.panels} panels · V0.52 collision view`}});holder.dataset.v52Renderer='true';proof.setProgress(100);return true}
function bindStatic(){root.querySelector('[data-v52-scan]').onclick=()=>runScan();root.querySelector('[data-v52-optimize]').onclick=optimize;root.querySelector('[data-v52-clear]').onclick=()=>{activeEventId=null;renderAll()}}
function scheduleRescan(){clearTimeout(rescanTimer);rescanTimer=setTimeout(()=>runScan(),80)}
function poll(ms=900){clearInterval(pollTimer);const start=Date.now();pollTimer=setInterval(()=>{if(Date.now()-start>ms){clearInterval(pollTimer);pollTimer=0;return}if(rebuild())renderAll()},50)}
function bindCompatibility(){root.addEventListener('input',event=>{if(event.target.matches('[data-v50-timeline]'))foldModeV77='sequence';if(event.target.matches('[data-v50-timeline],[data-v50-explode]'))setTimeout(()=>{if(rebuild())renderAll()},0)});root.addEventListener('change',event=>{if(event.target.matches('[data-v50-angle],[data-v51-step]'))scheduleRescan();else if(event.target.matches('[data-v50-dimensions],[data-v50-sequence]'))setTimeout(()=>{if(rebuild())renderAll()},0)});root.addEventListener('click',event=>{if(event.target.closest('[data-v50-flip],[data-v50-up],[data-v50-down],[data-v51-step-up],[data-v51-step-down],[data-v51-merge],[data-v51-split]'))scheduleRescan();if(event.target.closest('[data-v51-prev],[data-v51-next],[data-v51-keyframe]'))setTimeout(()=>{if(rebuild())renderAll()},0);if(event.target.closest('[data-v50-play],[data-v51-play]')){foldModeV77='sequence';poll(1800)}});window.addEventListener('boxstudio:v49-panel-selection',()=>setTimeout(()=>{if(rebuild())renderAll()},0));window.addEventListener('boxstudio:v49-fold',()=>{foldModeV77='uniform';if(rebuild())refreshProof();});window.addEventListener('boxstudio:v51-collision-scan',()=>scheduleRescan());window.addEventListener('boxstudio:v51-sequence-replaced',()=>setTimeout(()=>{if(rebuild()){report=scanFoldSequenceV51(state,graph,geo);activeEventId=null;renderAll()}},0))}

function enhance(){if(!window.BoxStudioV51||document.body.dataset.v51FoldSequence!=='true')return false;const page=document.querySelector('.three-page.v49-linked-page');if(!page)return false;if(page.dataset.v52Ready==='true'){root=page;return true}root=page;if(!rebuild())return false;const anchor=root.querySelector('[data-v51-sequence]');if(!anchor)return false;anchor.insertAdjacentHTML('afterend',markup());report=scanFoldSequenceV51(state,graph,geo);mountProof();bindStatic();bindCompatibility();renderAll();page.dataset.v52Ready='true';page.dataset.v52Acceptance=collisionOptimizationAcceptanceV52(state,graph,geo).ok?'pass':'fail';document.body.dataset.v52CollisionOptimization='true';window.BoxStudioV52={version:V52_PRODUCT_VERSION,getState:()=>structuredClone(state),getReport:()=>structuredClone(report),getOptimization:()=>structuredClone(optimization),getProof:()=>proof,scan:()=>runScan(),jumpToCollision:jumpToEvent,optimize,applySuggestion,clearFocus:()=>{activeEventId=null;renderAll()},getAcceptance:()=>collisionOptimizationAcceptanceV52(state,graph,geo)};return true}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;if(!document.querySelector('.three-page.v49-linked-page')){proof?.dispose?.();proof=null;root=null;clearInterval(pollTimer);return}enhance()})}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
