import { buildLinkedWorkspaceModelV49 } from './linkedWorkspaceV49.js';
import { buildFoldSequenceModelV51, rendererAuthoringV51 } from './foldSequenceV51.js';
import { collisionEventsV52, collisionHighlightV52, locateCollisionV52, stateAtTimelineV52 } from './collisionOptimizationV52.js';
import { buildCollisionRepairsV53, previewRepairV53, collisionRepairAcceptanceV53, V53_PRODUCT_VERSION } from './collisionRepairV53.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let root=null,linked=null,graph=null,geo=null,state=null,report=null,eventId=null,assistant=null,preview=null,queued=false;

function rebuild(){const base=window.BoxStudioV51?.getState?.()||window.BoxStudioV50?.getState?.();if(!base)return false;linked=buildLinkedWorkspaceModelV49(base);graph=linked.review.graph;geo=linked.review.geo;state=window.BoxStudioV51?.getState?.()||base;report=window.BoxStudioV52?.getReport?.()||window.BoxStudioV51?.scanCollisions?.()||null;const events=collisionEventsV52(report||{});if(!events.some(x=>x.id===eventId))eventId=events[0]?.id||null;assistant=buildCollisionRepairsV53(state,graph,geo,report||{},eventId,{limit:8});return true}
function selectedRepair(){return preview?.repair||null}
function scoreBadge(){const repair=selectedRepair();if(!repair)return `<span class="v53-score">选择方案查看 Before / After</span>`;return `<span class="v53-score ${repair.improved?'improved':'warning'}">${repair.improved?'改善':'试算'} ${Math.round(repair.improvement)} pts</span>`}
function eventMarkup(){const events=collisionEventsV52(report||{});if(!events.length)return'<div class="v53-empty">当前折叠路径没有可修复的碰撞事件。</div>';return `<div class="v53-events">${events.map(e=>`<button class="v53-event ${e.type} ${e.id===eventId?'active':''}" data-v53-event="${esc(e.id)}"><span>${e.type==='penetration'?'穿插':'搭接'} · ${esc(e.a)} ↔ ${esc(e.b)}</span><small>${e.firstTimeline.toFixed(1)}–${e.lastTimeline.toFixed(1)}% · ${e.occurrences} samples</small></button>`).join('')}</div>`}
function repairMarkup(){if(!assistant?.repairs?.length)return'<div class="v53-empty">没有生成可用修复方案。</div>';return `<div class="v53-repairs">${assistant.repairs.map(r=>`<div class="v53-repair-card ${r.improved?'improved':''} ${r.risk==='geometry'?'geometry':''}" data-v53-repair-card="${esc(r.id)}"><div class="v53-repair-top"><div><b>#${r.rank} · ${esc(r.title)}</b><small>${esc(r.detail)}</small></div><span class="v53-risk">${r.risk==='geometry'?'几何变化':'低风险'}</span></div><div class="v53-compare"><div class="v53-metric"><small>Before</small><b>${assistant.baseline.penetrations} 穿插 / ${assistant.baseline.overlaps} 搭接</b><small>score ${Math.round(assistant.baseline.score)}</small></div><div class="v53-metric"><small>After trial</small><b>${r.penetrations} 穿插 / ${r.overlaps} 搭接</b><small>score ${Math.round(r.score)}${r.removedTargetEvent?' · 当前冲突已消失':''}</small></div></div><div class="v53-repair-actions"><button data-v53-preview="${esc(r.id)}">试算预览</button><button class="primary" data-v53-apply="${esc(r.id)}">确认应用</button></div></div>`).join('')}</div>`}
function markup(){return `<div class="v53-repair" data-v53-repair><div class="v53-head"><div><span>V0.53 COLLISION REPAIR ASSISTANT</span><b>冲突定位 / 修复试算 / Before-After 对比 / 确认后应用</b></div><div data-v53-score>${scoreBadge()}</div></div><div class="v53-layout"><section><h4>Collision to repair</h4><div data-v53-events>${eventMarkup()}</div></section><section><h4>Repair candidates</h4><div data-v53-repairs>${repairMarkup()}</div></section></div><div class="v53-actions"><button data-v53-restore>恢复当前项目视图</button><span data-v53-preview-state></span></div></div>`}

function refreshMarkup(){if(!root)return;const events=root.querySelector('[data-v53-events]'),repairs=root.querySelector('[data-v53-repairs]'),score=root.querySelector('[data-v53-score]'),stateLabel=root.querySelector('[data-v53-preview-state]');if(events)events.innerHTML=eventMarkup();if(repairs)repairs.innerHTML=repairMarkup();if(score)score.innerHTML=scoreBadge();if(stateLabel)stateLabel.innerHTML=preview?`<span class="v53-preview-badge">PREVIEW · 尚未写入项目</span>`:'';bindDynamic()}
function restoreProjectView(){preview=null;window.BoxStudioV52?.scan?.();refreshMarkup()}
function renderTrial(repair){const proof=window.BoxStudioV52?.getProof?.();if(!proof)return;const stepCount=buildFoldSequenceModelV51(repair.state,graph,geo).stepCount,loc=locateCollisionV52(repair.report,eventId,stepCount)||assistant.location||{timeline:0},trial=stateAtTimelineV52(repair.state,graph,geo,loc.timeline),model=buildFoldSequenceModelV51(trial,graph,geo),base=rendererAuthoringV51(model,repair.report),highlight=collisionHighlightV52(repair.report,eventId);proof.setAuthoring({...base,penetrationPanels:highlight.penetrationPanels,collisionPanels:highlight.penetrationPanels,overlapPanels:highlight.overlapPanels,activePanels:[assistant.event?.a,assistant.event?.b].filter(Boolean)});proof.setProgress(100)}
function previewRepair(id){const next=previewRepairV53(assistant,id);if(!next)return;preview=next;renderTrial(next.repair);refreshMarkup()}
function applyRepair(id){const repair=assistant?.repairs?.find(x=>x.id===id);if(!repair)return false;const v50=window.BoxStudioV50,v51=window.BoxStudioV51;if(!v50||!v51)return false;const targetAngle=repair.state?.foldAuthoringV50?.edges?.find(x=>x.key===repair.edgeKey)?.angle,currentAngle=v50.getState?.()?.foldAuthoringV50?.edges?.find(x=>x.key===repair.edgeKey)?.angle;if(Number.isFinite(targetAngle)&&targetAngle!==currentAngle){v50.selectEdge?.(repair.edgeKey);v50.setEdgeAngle?.(targetAngle)}if(repair.state?.foldSequenceV51?.edgeSteps)v51.replaceEdgeSteps?.(repair.state.foldSequenceV51.edgeSteps);preview=null;report=window.BoxStudioV52?.scan?.()||v51.scanCollisions?.()||report;rebuild();refreshMarkup();return true}
function selectEvent(id){restoreProjectView();eventId=id;rebuild();const event=collisionEventsV52(report||{}).find(x=>x.id===id);if(event){const count=buildFoldSequenceModelV51(state,graph,geo).stepCount,loc=locateCollisionV52(report,id,count);if(loc){window.BoxStudioV51?.setStep?.(loc.completedStep);window.BoxStudioV50?.setTimeline?.(loc.timeline)}window.BoxStudioV49?.selectPanel?.(event.a)}refreshMarkup()}
function bindDynamic(){root?.querySelectorAll('[data-v53-event]').forEach(b=>b.onclick=()=>selectEvent(b.dataset.v53Event));root?.querySelectorAll('[data-v53-preview]').forEach(b=>b.onclick=()=>previewRepair(b.dataset.v53Preview));root?.querySelectorAll('[data-v53-apply]').forEach(b=>b.onclick=()=>applyRepair(b.dataset.v53Apply));const restore=root?.querySelector('[data-v53-restore]');if(restore)restore.onclick=restoreProjectView}
function enhance(){if(!window.BoxStudioV52||document.body.dataset.v52CollisionOptimization!=='true')return false;const page=document.querySelector('.three-page.v49-linked-page');if(!page)return false;if(page.dataset.v53Ready==='true'){root=page;return true}if(!rebuild())return false;root=page;const anchor=root.querySelector('[data-v52-panel]');if(!anchor)return false;anchor.insertAdjacentHTML('afterend',markup());bindDynamic();page.dataset.v53Ready='true';document.body.dataset.v53CollisionRepair='true';const acceptance=collisionRepairAcceptanceV53(state,graph,geo,report||{});page.dataset.v53Acceptance=acceptance.ok?'pass':'fail';window.BoxStudioV53={version:V53_PRODUCT_VERSION,getAssistant:()=>structuredClone(assistant),getPreview:()=>preview?structuredClone(preview):null,getAcceptance:()=>collisionRepairAcceptanceV53(state,graph,geo,report||{}),selectEvent,previewRepair,applyRepair,restore:restoreProjectView};return true}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;if(!document.querySelector('.three-page.v49-linked-page')){root=null;preview=null;return}enhance()})}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
