import { buildLinkedWorkspaceModelV49 } from './linkedWorkspaceV49.js';
import { buildFoldSequenceModelV51, rendererAuthoringV51 } from './foldSequenceV51.js';
import { collisionHighlightV52 } from './collisionOptimizationV52.js';
import { buildRepairPlansV54, previewRepairPlanV54, repairPlanAcceptanceV54, V54_PRODUCT_VERSION } from './repairPlanV54.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let root=null,linked=null,graph=null,geo=null,state=null,report=null,bundle=null,preview=null,undoSnapshot=null,queued=false,searching=false;

function currentState(){return window.BoxStudioV51?.getState?.()||window.BoxStudioV50?.getState?.()||null}
function rebuild({keepBundle=false}={}){const base=currentState();if(!base)return false;linked=buildLinkedWorkspaceModelV49(base);graph=linked.review.graph;geo=linked.review.geo;state=currentState()||base;report=window.BoxStudioV52?.getReport?.()||window.BoxStudioV51?.scanCollisions?.()||null;if(!keepBundle)bundle=null;return true}
function profileLabel(id){return id==='safe'?'Safe · 仅顺序':id==='balanced'?'Balanced · 有限几何':'Aggressive · 高风险几何'}
function scoreDelta(plan){return Math.round((plan.baseline?.collisionScore||0)-(plan.after?.collisionScore||0))}
function actionList(plan){if(!plan.actions?.length)return'<li>无需修改，或当前搜索深度未找到更优组合。</li>';return plan.actions.map((a,i)=>`<li><b>${i+1}. ${esc(a.title)}</b><span>${esc(a.detail||a.kind)}</span></li>`).join('')}
function planCard(plan){const cls=plan.profile.id,delta=scoreDelta(plan);return `<article class="v54-plan ${cls} ${plan.improved?'improved':''}" data-v54-plan="${cls}"><header><div><span>${esc(profileLabel(cls))}</span><b>${plan.after.penetrations} 穿插 / ${plan.after.overlaps} 搭接</b></div><em>${plan.cleared?'路径无冲突':plan.improved?`改善 ${delta} pts`:'未改善'}</em></header><div class="v54-compare"><div><small>Before</small><b>${plan.baseline.penetrations} / ${plan.baseline.overlaps}</b><span>score ${Math.round(plan.baseline.collisionScore)}</span></div><i>→</i><div><small>After Plan</small><b>${plan.after.penetrations} / ${plan.after.overlaps}</b><span>score ${Math.round(plan.after.collisionScore)}</span></div></div><details><summary>${plan.actions.length} 个修复动作 · 查看计划</summary><ol>${actionList(plan)}</ol></details><div class="v54-buttons"><button data-v54-preview="${cls}">整套预览</button><button class="primary" data-v54-apply="${cls}" ${!plan.changed?'disabled':''}>确认应用计划</button></div></article>`}
function plansMarkup(){if(searching)return'<div class="v54-empty">正在试算 Safe / Balanced / Aggressive 三套完整路径…</div>';if(!bundle)return'<div class="v54-empty">点击“生成整套修复方案”，系统会对完整 Fold Sequence 做组合试算。</div>';return `<div class="v54-plan-grid">${bundle.plans.map(planCard).join('')}</div>`}
function markup(){return `<section class="v54-assistant" data-v54-assistant><div class="v54-head"><div><span>V0.54 REPAIR PLAN / AUTO SEARCH</span><b>整条折叠路径 · Safe / Balanced / Aggressive · Preview / Apply / Undo</b></div><span data-v54-state>尚未生成方案</span></div><div class="v54-toolbar"><button class="primary" data-v54-search>生成整套修复方案</button><button data-v54-restore>恢复当前项目视图</button><button data-v54-undo disabled>撤销上次 Repair Plan</button></div><div data-v54-plans>${plansMarkup()}</div><div class="v54-foot" data-v54-foot></div></section>`}
function statusMarkup(){if(preview)return `<span class="preview">PREVIEW · ${esc(profileLabel(preview.profile.id))} · 尚未提交</span>`;if(undoSnapshot)return'<span class="applied">Repair Plan 已应用 · 可撤销</span>';if(bundle)return `<span>${bundle.evaluated} states evaluated</span>`;return'<span>等待分析</span>'}
function refresh(){if(!root)return;const plans=root.querySelector('[data-v54-plans]'),status=root.querySelector('[data-v54-state]'),foot=root.querySelector('[data-v54-foot]'),undo=root.querySelector('[data-v54-undo]');if(plans)plans.innerHTML=plansMarkup();if(status)status.innerHTML=statusMarkup();if(foot)foot.innerHTML=bundle?`<b>${bundle.evaluated}</b> 个状态已完整扫描 · 所有方案均需人工确认后才提交`:'';if(undo)undo.disabled=!undoSnapshot;bindDynamic()}
function proof(){return window.BoxStudioV52?.getProof?.()||null}
function renderState(trialState,trialReport){const p=proof();if(!p)return;const model=buildFoldSequenceModelV51(trialState,graph,geo),base=rendererAuthoringV51(model,trialReport),highlight=collisionHighlightV52(trialReport||{},null);p.setAuthoring({...base,penetrationPanels:highlight.penetrationPanels,collisionPanels:highlight.penetrationPanels,overlapPanels:highlight.overlapPanels,activePanels:[]});p.setProgress(100)}
function restoreProjectView(){preview=null;window.BoxStudioV52?.scan?.();refresh()}
function generatePlans(){if(searching||!rebuild())return;searching=true;preview=null;refresh();setTimeout(()=>{try{bundle=buildRepairPlansV54(state,graph,geo,report,{maxDepth:3,beamWidth:4});}finally{searching=false;refresh()}},0)}
function previewPlan(profile){if(!bundle&&rebuild())bundle=buildRepairPlansV54(state,graph,geo,report,{maxDepth:3,beamWidth:4});const next=previewRepairPlanV54(bundle,profile);if(!next)return false;preview=next;renderState(next.state,next.report);refresh();return true}
function applyRuntimeState(target){const v50=window.BoxStudioV50,v51=window.BoxStudioV51;if(!v50||!v51)return false;const current=v50.getState?.();const targetAngles=new Map((target?.foldAuthoringV50?.edges||[]).map(e=>[e.key,e.angle]));for(const edge of current?.foldAuthoringV50?.edges||[]){const angle=targetAngles.get(edge.key);if(Number.isFinite(angle)&&Math.abs(Number(angle)-Number(edge.angle))>.0001){v50.selectEdge?.(edge.key);v50.setEdgeAngle?.(angle)}}if(target?.foldSequenceV51?.edgeSteps)v51.replaceEdgeSteps?.(target.foldSequenceV51.edgeSteps);return true}
function applyPlan(profile){if(!bundle)return false;const plan=bundle.plans.find(p=>p.profile.id===profile);if(!plan?.changed)return false;undoSnapshot=structuredClone(currentState());if(!applyRuntimeState(plan.state)){undoSnapshot=null;return false}preview=null;window.BoxStudioV52?.scan?.();rebuild();bundle=null;refresh();return true}
function undoPlan(){if(!undoSnapshot)return false;const snap=undoSnapshot;undoSnapshot=null;if(!applyRuntimeState(snap))return false;preview=null;window.BoxStudioV52?.scan?.();rebuild();bundle=null;refresh();return true}
function bindDynamic(){root?.querySelectorAll('[data-v54-preview]').forEach(b=>b.onclick=()=>previewPlan(b.dataset.v54Preview));root?.querySelectorAll('[data-v54-apply]').forEach(b=>b.onclick=()=>applyPlan(b.dataset.v54Apply));const search=root?.querySelector('[data-v54-search]'),restore=root?.querySelector('[data-v54-restore]'),undo=root?.querySelector('[data-v54-undo]');if(search)search.onclick=generatePlans;if(restore)restore.onclick=restoreProjectView;if(undo)undo.onclick=undoPlan}
function enhance(){if(!window.BoxStudioV53||document.body.dataset.v53CollisionRepair!=='true')return false;const page=document.querySelector('.three-page.v49-linked-page');if(!page)return false;if(page.dataset.v54Ready==='true'){root=page;return true}if(!rebuild())return false;root=page;const anchor=root.querySelector('[data-v53-repair]');if(!anchor)return false;anchor.insertAdjacentHTML('afterend',markup());bindDynamic();page.dataset.v54Ready='true';document.body.dataset.v54RepairPlan='true';const acceptance=repairPlanAcceptanceV54(state,graph,geo,report);page.dataset.v54Acceptance=acceptance.ok?'pass':'fail';window.BoxStudioV54={version:V54_PRODUCT_VERSION,getBundle:()=>bundle?structuredClone(bundle):null,getPreview:()=>preview?structuredClone(preview):null,getUndoSnapshot:()=>undoSnapshot?structuredClone(undoSnapshot):null,getAcceptance:()=>repairPlanAcceptanceV54(state,graph,geo,report),generate:()=>{bundle=buildRepairPlansV54(state,graph,geo,report,{maxDepth:3,beamWidth:4});refresh();return structuredClone(bundle)},previewPlan,applyPlan,restore:restoreProjectView,undo:undoPlan};return true}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;if(!document.querySelector('.three-page.v49-linked-page')){root=null;preview=null;return}enhance()})}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
