import { buildLinkedWorkspaceModelV49 } from './linkedWorkspaceV49.js';
import { buildManufacturingProfilesV55, manufacturingAcceptanceV55, manufacturingPreflightChecksV55, V55_PRODUCT_VERSION } from './manufacturingIntelligenceV55.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let root=null,linked=null,graph=null,geo=null,state=null,report=null,bundle=null,overrideThickness=null,queued=false;
const v64Runtime=window.BoxStudioUiRuntimeV64;
function currentState(){return window.BoxStudioV51?.getState?.()||window.BoxStudioV50?.getState?.()||null}
function rebuild(){const base=currentState();if(!base)return false;linked=buildLinkedWorkspaceModelV49(base);graph=linked.review.graph;geo=linked.review.geo;state=currentState()||base;report=window.BoxStudioV52?.getReport?.()||window.BoxStudioV51?.scanCollisions?.()||{};bundle=buildManufacturingProfilesV55(state,graph,geo,report,Number.isFinite(overrideThickness)?{thicknessMm:overrideThickness}:{});return true}
function statusText(p){return p.status==='pass'?'PASS':p.status==='review'?'REVIEW':'FAIL'}
function issueRows(p){return p.issues.map(x=>`<li class="${x.severity}"><span>${x.severity.toUpperCase()}</span><div><b>${esc(x.title)}</b><small>${esc(x.detail)}</small>${x.recommendation?`<em>${esc(x.recommendation)}</em>`:''}</div></li>`).join('')}
function profileCard(p){return `<article class="v55-profile ${p.profile.id} ${p.status}" data-v55-profile="${p.profile.id}"><header><div><span>${esc(p.profile.label)}</span><b>${p.score}/100</b></div><em>${statusText(p)}</em></header><p>${esc(p.profile.description)}</p><div class="v55-thresholds"><span>Min panel <b>${p.thresholds.minPanelMm}mm</b></span><span>Action flap <b>${p.thresholds.minActionPanelMm}mm</b></span><span>Glue <b>${p.thresholds.minGlueMm}mm</b></span><span>Concurrent ≤ <b>${p.thresholds.maxConcurrentFolds}</b></span></div><details><summary>${p.errors.length} errors · ${p.warnings.length} warnings · 查看制造检查</summary><ul>${issueRows(p)}</ul></details></article>`}
function contextMarkup(){const c=bundle.context,t=Number.isFinite(overrideThickness)?overrideThickness:c.material.thicknessMm,crease=t*Number(c.crease.factor||0);return `<div class="v55-context"><div><small>Material</small><b>${esc(c.material.name)} · ${esc(c.material.flute||'CUSTOM')}</b></div><div><small>Board T</small><b>${Number(t).toFixed(2)} mm${Number.isFinite(overrideThickness)?' · FACTORY':''}</b></div><div><small>Crease advisory</small><b>${Number(crease).toFixed(2)} mm</b></div><div><small>Process family</small><b>${esc(c.process)}</b></div><div><small>Fold path</small><b>${c.penetrationCount} penetration / ${c.overlapCount} overlap</b></div></div>`}
function markup(){return `<section class="v55-manufacturing" data-v55-manufacturing><div class="v55-head"><div><span>V0.55 MANUFACTURING INTELLIGENCE</span><b>纸厚 / 压痕 / 胶舌 / 插接余量 / Fold Feasibility · Safe / Machine / Manual</b></div><span>Engineering advisory · Factory override required</span></div><div data-v55-context>${contextMarkup()}</div><div class="v55-toolbar"><label>工厂实测厚度 <input type="number" min="0.1" step="0.05" data-v55-thickness placeholder="${bundle.context.material.thicknessMm}"> mm</label><button data-v55-recalc>按实测厚度重算</button><button data-v55-reset>恢复工程预设</button></div><div class="v55-profile-grid" data-v55-profiles>${bundle.profiles.map(profileCard).join('')}</div><div class="v55-note">三个分数代表各自工艺 Profile 下的可行性，不用于跨 Profile 简单排名。当前阈值是可审计的工程启发式，不替代纸板供应商数据、压痕矩阵、模切机/糊盒机规格或实样验收。Manufacturing Preflight 默认只给 Advisory；可由调用方启用 blocking。</div></section>`}
function refresh(){if(!root||!rebuild())return;const ctx=root.querySelector('[data-v55-context]'),profiles=root.querySelector('[data-v55-profiles]');if(ctx)ctx.innerHTML=contextMarkup();if(profiles)profiles.innerHTML=bundle.profiles.map(profileCard).join('');bind()}
function recalc(){const input=root?.querySelector('[data-v55-thickness]'),value=Number(input?.value);overrideThickness=Number.isFinite(value)&&value>0?Math.max(.1,value):null;refresh()}
function reset(){overrideThickness=null;const input=root?.querySelector('[data-v55-thickness]');if(input)input.value='';refresh()}
function bind(){const r=root?.querySelector('[data-v55-recalc]'),x=root?.querySelector('[data-v55-reset]');if(r)r.onclick=recalc;if(x)x.onclick=reset}
function enhance(){if(!window.BoxStudioV54||document.body.dataset.v54RepairPlan!=='true')return false;const page=document.querySelector('.three-page.v49-linked-page');if(!page)return false;if(page.dataset.v55Ready==='true'){root=page;return true}if(!rebuild())return false;root=page;const anchor=root.querySelector('[data-v54-assistant]');if(!anchor)return false;anchor.insertAdjacentHTML('afterend',markup());bind();page.dataset.v55Ready='true';document.body.dataset.v55Manufacturing='true';const acceptance=manufacturingAcceptanceV55(state,graph,geo,report);page.dataset.v55Acceptance=acceptance.ok?'pass':'fail';window.BoxStudioV55={version:V55_PRODUCT_VERSION,getBundle:()=>structuredClone(bundle),getAcceptance:()=>manufacturingAcceptanceV55(state,graph,geo,report),getPreflightChecks:(profile='safe',blocking=false)=>manufacturingPreflightChecksV55(bundle,profile,{blocking}),setFactoryThickness:value=>{const v=Number(value);overrideThickness=Number.isFinite(v)&&v>0?Math.max(.1,v):null;refresh();return structuredClone(bundle)},resetFactoryOverride:()=>{overrideThickness=null;refresh();return structuredClone(bundle)},refresh:()=>{refresh();return structuredClone(bundle)}};return true}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;if(!document.querySelector('.three-page.v49-linked-page')){root=null;return}enhance()})}
if(v64Runtime?.register)v64Runtime.register('v55',enhance);else{new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule()}
