import { buildLinkedWorkspaceModelV49 } from './linkedWorkspaceV49.js';
import { createFactoryDatabaseV56, normalizeFactoryDatabaseV56, upsertFactoryProfileV56, duplicateFactoryProfileV56, deleteFactoryProfileV56, selectFactoryProfileV56, exportFactoryDatabaseV56, importFactoryDatabaseV56, evaluateFactoryCapabilityV56, factoryPreflightChecksV56, factoryAcceptanceV56, V56_PRODUCT_VERSION, V56_STORAGE_KEY } from './factoryProfilesV56.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const splitCsv=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
let root=null,linked=null,graph=null,geo=null,state=null,report=null,db=null,evaluation=null,queued=false;
function currentState(){return window.BoxStudioV51?.getState?.()||window.BoxStudioV50?.getState?.()||null}
function loadDb(){try{return normalizeFactoryDatabaseV56(JSON.parse(localStorage.getItem(V56_STORAGE_KEY)||'null')||createFactoryDatabaseV56())}catch{return createFactoryDatabaseV56()}}
function saveDb(){try{localStorage.setItem(V56_STORAGE_KEY,JSON.stringify(db))}catch{}}
function selected(){return db?.profiles?.find(x=>x.id===db.selectedId)||db?.profiles?.[0]||null}
function rebuild(){const base=currentState();if(!base)return false;linked=buildLinkedWorkspaceModelV49(base);graph=linked.review.graph;geo=linked.review.geo;state=currentState()||base;report=window.BoxStudioV52?.getReport?.()||window.BoxStudioV51?.scanCollisions?.()||{};const p=selected();evaluation=p?evaluateFactoryCapabilityV56(state,graph,geo,report,p):null;return true}
function statusText(x){return x==='pass'?'PASS':x==='review'?'REVIEW':'FAIL'}
function profileList(){return db.profiles.map(p=>`<button type="button" class="v56-profile-row ${p.id===db.selectedId?'active':''}" data-v56-select="${esc(p.id)}"><span>${p.builtIn?'BASELINE':'CUSTOM'} · ${esc(p.mode)}</span><b>${esc(p.name)}</b><small>${esc(p.materials.categories.join(' / '))} · ${p.materials.thicknessMinMm}–${p.materials.thicknessMaxMm} mm</small></button>`).join('')}
function issueList(){if(!evaluation)return'';return evaluation.issues.map(x=>`<li class="${x.severity}"><span>${x.severity.toUpperCase()}</span><div><b>${esc(x.title)}</b><small>${esc(x.detail)}</small>${x.recommendation?`<em>${esc(x.recommendation)}</em>`:''}</div></li>`).join('')}
function inspector(){const p=selected();if(!p)return'<div class="v56-empty">No factory profile.</div>';const ro=p.builtIn?'disabled':'';return `<div class="v56-inspector" data-v56-inspector><div class="v56-profile-title"><div><span>${p.builtIn?'内置基线 · 复制后编辑':'自定义工厂 Profile'}</span><b>${esc(p.name)}</b></div><em>${esc(p.id)}</em></div><div class="v56-fields"><label>名称<input data-v56-field="name" value="${esc(p.name)}" ${ro}></label><label>模式<select data-v56-field="mode" ${ro}><option value="machine" ${p.mode==='machine'?'selected':''}>Machine</option><option value="manual" ${p.mode==='manual'?'selected':''}>Manual</option></select></label><label>材料类别<input data-v56-field="categories" value="${esc(p.materials.categories.join(', '))}" ${ro}></label><label>楞型<input data-v56-field="flutes" value="${esc(p.materials.flutes.join(', '))}" ${ro}></label><label>纸厚 Min mm<input type="number" step="0.05" data-v56-field="thicknessMinMm" value="${p.materials.thicknessMinMm}" ${ro}></label><label>纸厚 Max mm<input type="number" step="0.05" data-v56-field="thicknessMaxMm" value="${p.materials.thicknessMaxMm}" ${ro}></label><label>坯料 Max W<input type="number" data-v56-field="maxWidthMm" value="${p.blank.maxWidthMm}" ${ro}></label><label>坯料 Max H<input type="number" data-v56-field="maxHeightMm" value="${p.blank.maxHeightMm}" ${ro}></label><label>糊盒最小面 mm<input type="number" data-v56-field="minPanelMm" value="${p.folderGluer.minPanelMm}" ${ro}></label><label>同步折叠上限<input type="number" data-v56-field="maxConcurrentFolds" value="${p.folderGluer.maxConcurrentFolds}" ${ro}></label><label>胶宽 Min mm<input type="number" data-v56-field="glueMinWidthMm" value="${p.glue.minWidthMm}" ${ro}></label><label>胶宽 Max mm<input type="number" data-v56-field="glueMaxWidthMm" value="${p.glue.maxWidthMm}" ${ro}></label></div><div class="v56-toggles"><label><input type="checkbox" data-v56-field="creaseRequired" ${p.crease.required?'checked':''} ${ro}> 必须匹配压痕矩阵</label><label><input type="checkbox" data-v56-field="gateEnabled" ${p.productionGate.enabled?'checked':''} ${ro}> 启用工厂 Production Gate</label><label>Gate Profile <select data-v56-field="gateProfile" ${ro}><option value="safe" ${p.productionGate.manufacturingProfile==='safe'?'selected':''}>Safe</option><option value="machine" ${p.productionGate.manufacturingProfile==='machine'?'selected':''}>Machine</option><option value="manual" ${p.productionGate.manufacturingProfile==='manual'?'selected':''}>Manual</option></select></label></div>${p.builtIn?'<p class="v56-lock-note">内置基线不可直接修改。复制为 Custom Profile 后再录入真实工厂/设备参数。</p>':'<button type="button" class="primary" data-v56-save>保存工厂参数</button>'}</div>`}
function evaluationMarkup(){if(!evaluation)return'';const p=evaluation.profile;return `<div class="v56-eval ${evaluation.status}" data-v56-evaluation><header><div><span>FACTORY CAPABILITY RESULT</span><b>${esc(p.name)}</b></div><strong>${evaluation.score}/100 · ${statusText(evaluation.status)}</strong></header><div class="v56-metrics"><span>Blank <b>${evaluation.context.blank.widthMm}×${evaluation.context.blank.heightMm} mm</b></span><span>Board <b>${evaluation.context.material.thicknessMm} mm</b></span><span>Min panel <b>${evaluation.context.minPanelMm} mm</b></span><span>Glue <b>${evaluation.context.glueMm} mm</b></span><span>Concurrent <b>${evaluation.context.maxConcurrentFolds}</b></span><span>Gate <b>${evaluation.gate.enabled?(evaluation.gate.blocked?'BLOCKED':'READY'):'ADVISORY'}</b></span></div><details open><summary>${evaluation.errors.length} errors · ${evaluation.warnings.length} warnings · 查看工厂检查</summary><ul>${issueList()}</ul></details></div>`}
function markup(){return `<section class="v56-factory" data-v56-factory><div class="v56-head"><div><span>V0.56 FACTORY PROFILE / MACHINE CAPABILITY DATABASE</span><b>工厂 · 设备 · 材料 · 压痕矩阵 · Production Gate</b></div><span>Local profile database · Free core workflow</span></div><div class="v56-toolbar"><button data-v56-new>新建 Custom</button><button data-v56-duplicate>复制当前</button><button data-v56-delete>删除 Custom</button><button data-v56-export>导出 JSON</button><label class="v56-import">导入 JSON<input type="file" accept="application/json,.json" data-v56-import></label><button data-v56-reset>恢复内置基线</button></div><div class="v56-layout"><aside data-v56-list>${profileList()}</aside><main data-v56-inspector-wrap>${inspector()}${evaluationMarkup()}</main></div><div class="v56-note">工厂 Profile 是可审计能力数据，不是品牌/机型认证。内置基线只用于起步；真实生产应复制为 Custom 并录入设备铭牌、纸板供应商、胶系统和压痕矩阵。只有显式启用 Production Gate 后，Factory Error 才成为硬门禁。</div></section>`}
function refresh(){if(!root||!rebuild())return;const list=root.querySelector('[data-v56-list]'),wrap=root.querySelector('[data-v56-inspector-wrap]');if(list)list.innerHTML=profileList();if(wrap)wrap.innerHTML=`${inspector()}${evaluationMarkup()}`;bind()}
function mergeSelected(patch={}){const p=selected();if(!p||p.builtIn)return false;const next={...structuredClone(p),...patch,materials:{...p.materials,...(patch.materials||{})},blank:{...p.blank,...(patch.blank||{})},dieCutter:{...p.dieCutter,...(patch.dieCutter||{})},folderGluer:{...p.folderGluer,...(patch.folderGluer||{})},glue:{...p.glue,...(patch.glue||{})},crease:{...p.crease,...(patch.crease||{})},productionGate:{...p.productionGate,...(patch.productionGate||{})}};db=upsertFactoryProfileV56(db,next);saveDb();refresh();return true}
function saveForm(){const q=s=>root?.querySelector(`[data-v56-field="${s}"]`),p=selected();if(!p||p.builtIn)return false;return mergeSelected({name:q('name')?.value||p.name,mode:q('mode')?.value||p.mode,materials:{categories:splitCsv(q('categories')?.value),flutes:splitCsv(q('flutes')?.value),thicknessMinMm:Number(q('thicknessMinMm')?.value),thicknessMaxMm:Number(q('thicknessMaxMm')?.value)},blank:{maxWidthMm:Number(q('maxWidthMm')?.value),maxHeightMm:Number(q('maxHeightMm')?.value)},folderGluer:{minPanelMm:Number(q('minPanelMm')?.value),maxConcurrentFolds:Number(q('maxConcurrentFolds')?.value)},glue:{minWidthMm:Number(q('glueMinWidthMm')?.value),maxWidthMm:Number(q('glueMaxWidthMm')?.value)},crease:{required:Boolean(q('creaseRequired')?.checked)},productionGate:{enabled:Boolean(q('gateEnabled')?.checked),manufacturingProfile:q('gateProfile')?.value||'machine'}})}
function createCustom(){db=duplicateFactoryProfileV56(db,'generic-corrugated-machine','New Factory Profile');saveDb();refresh()}
function duplicateCurrent(){db=duplicateFactoryProfileV56(db,db.selectedId);saveDb();refresh()}
function deleteCurrent(){db=deleteFactoryProfileV56(db,db.selectedId);saveDb();refresh()}
function resetDb(){db=createFactoryDatabaseV56();saveDb();refresh()}
function exportDb(){const text=exportFactoryDatabaseV56(db);try{const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='boxstudio-factory-profiles-v56.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}catch{}return text}
async function importFile(file){if(!file)return false;const text=await file.text();db=importFactoryDatabaseV56(text);saveDb();refresh();return true}
function bind(){root?.querySelectorAll('[data-v56-select]').forEach(b=>b.onclick=()=>{db=selectFactoryProfileV56(db,b.dataset.v56Select);saveDb();refresh()});const map={'[data-v56-new]':createCustom,'[data-v56-duplicate]':duplicateCurrent,'[data-v56-delete]':deleteCurrent,'[data-v56-export]':exportDb,'[data-v56-reset]':resetDb,'[data-v56-save]':saveForm};for(const [s,fn] of Object.entries(map)){const el=root?.querySelector(s);if(el)el.onclick=fn}const imp=root?.querySelector('[data-v56-import]');if(imp)imp.onchange=()=>importFile(imp.files?.[0])}
function enhance(){if(!window.BoxStudioV55||document.body.dataset.v55Manufacturing!=='true')return false;const page=document.querySelector('.three-page.v49-linked-page');if(!page)return false;if(page.dataset.v56Ready==='true'){root=page;return true}db=loadDb();if(!rebuild())return false;root=page;const anchor=root.querySelector('[data-v55-manufacturing]');if(!anchor)return false;anchor.insertAdjacentHTML('afterend',markup());bind();page.dataset.v56Ready='true';document.body.dataset.v56Factory='true';page.dataset.v56Acceptance=factoryAcceptanceV56(db).ok?'pass':'fail';window.BoxStudioV56={version:V56_PRODUCT_VERSION,getDatabase:()=>structuredClone(db),getSelectedProfile:()=>structuredClone(selected()),getEvaluation:()=>structuredClone(evaluation),getAcceptance:()=>factoryAcceptanceV56(db),getPreflightChecks:(blocking=null)=>factoryPreflightChecksV56(evaluation,blocking===null?evaluation?.gate?.enabled===true:Boolean(blocking)),selectProfile:id=>{db=selectFactoryProfileV56(db,id);saveDb();refresh();return structuredClone(selected())},createProfile:()=>{createCustom();return structuredClone(selected())},duplicateSelected:()=>{duplicateCurrent();return structuredClone(selected())},deleteSelected:()=>{deleteCurrent();return structuredClone(selected())},updateSelected:patch=>{mergeSelected(patch);return structuredClone(selected())},exportDatabase:()=>exportFactoryDatabaseV56(db),importDatabase:text=>{db=importFactoryDatabaseV56(text);saveDb();refresh();return structuredClone(db)},resetDatabase:()=>{resetDb();return structuredClone(db)},refresh:()=>{refresh();return structuredClone(evaluation)}};return true}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;if(!document.querySelector('.three-page.v49-linked-page')){root=null;return}enhance()})}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
