import { buildLinkedWorkspaceModelV49 } from './linkedWorkspaceV49.js';
import { createRoutingDatabaseV57, normalizeRoutingDatabaseV57, updateRoutingMetaV57, normalizeRoutingJobV57, routeFactoryJobV57, buildManufacturingJobTicketV57, exportJobTicketV57, routingAcceptanceV57, V57_PRODUCT_VERSION, V57_STORAGE_KEY } from './factoryRoutingV57.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let root=null,state=null,graph=null,geo=null,report=null,factoryDb=null,routingDb=null,job=null,result=null,queued=false;
function currentState(){return window.BoxStudioV51?.getState?.()||window.BoxStudioV50?.getState?.()||null}
function loadRouting(db){try{return normalizeRoutingDatabaseV57(db,JSON.parse(localStorage.getItem(V57_STORAGE_KEY)||'null')||createRoutingDatabaseV57(db))}catch{return createRoutingDatabaseV57(db)}}
function save(){try{localStorage.setItem(V57_STORAGE_KEY,JSON.stringify({routingDb,job}))}catch{}}
function restore(db){try{const x=JSON.parse(localStorage.getItem(V57_STORAGE_KEY)||'null');routingDb=normalizeRoutingDatabaseV57(db,x?.routingDb||x||createRoutingDatabaseV57(db));job=normalizeRoutingJobV57(x?.job||{});return}catch{}routingDb=createRoutingDatabaseV57(db);job=normalizeRoutingJobV57({})}
function rebuild(){const base=currentState();if(!base||!window.BoxStudioV56)return false;factoryDb=window.BoxStudioV56.getDatabase();if(!routingDb)restore(factoryDb);else routingDb=normalizeRoutingDatabaseV57(factoryDb,routingDb);const linked=buildLinkedWorkspaceModelV49(base);state=currentState()||base;graph=linked.review.graph;geo=linked.review.geo;report=window.BoxStudioV52?.getReport?.()||window.BoxStudioV51?.scanCollisions?.()||{};result=routeFactoryJobV57(state,graph,geo,report,factoryDb,routingDb,job);return true}
function money(v,c){return v==null?'未录入':`${Number(v).toFixed(2)} ${esc(c||'USD')}`}
function candidateCard(c){const reasons=c.reasons.length?`<details><summary>${c.reasons.length} 条路由说明</summary><ul>${c.reasons.map(x=>`<li>${esc(x.detail)}</li>`).join('')}</ul></details>`:'<small class="v57-clear">能力与当前路由约束均通过</small>';return `<article class="v57-candidate ${c.status}" data-v57-candidate="${esc(c.factoryId)}"><header><div><span>${c.status.toUpperCase()} · ${esc(c.mode)}</span><b>${esc(c.factoryName)}</b></div><strong>${c.routeScore}</strong></header><div class="v57-metrics"><span>Capability <b>${c.capabilityScore}</b></span><span>Priority <b>${c.planning.priority}</b></span><span>Load <b>${c.planning.loadPercent==null?'—':`${c.planning.loadPercent}%`}</b></span><span>Lead <b>${c.planning.leadDays==null?'—':`${c.planning.leadDays}d`}</b></span><span>Cost <b>${money(c.estimatedCost,c.currency)}</b></span><span>Planning <b>${c.planningCompleteness.filled}/${c.planningCompleteness.total}</b></span></div>${reasons}</article>`}
function planningRows(){return factoryDb.profiles.map(p=>{const m=routingDb.factories[p.id];return `<tr data-v57-plan-row="${esc(p.id)}"><td><b>${esc(p.name)}</b><small>${p.mode}</small></td><td><input type="number" min="0" max="100" value="${m.priority}" data-v57-plan="priority"></td><td><input type="number" min="0" max="100" value="${m.loadPercent??''}" placeholder="—" data-v57-plan="loadPercent"></td><td><input type="number" min="0" value="${m.leadDays??''}" placeholder="—" data-v57-plan="leadDays"></td><td><input type="number" min="0" step="0.01" value="${m.costPer1000??''}" placeholder="—" data-v57-plan="costPer1000"></td><td><input type="number" min="0" step="0.01" value="${m.setupCost??''}" placeholder="—" data-v57-plan="setupCost"></td><td><input type="number" min="0" value="${m.capacityPerDay??''}" placeholder="—" data-v57-plan="capacityPerDay"></td><td><label><input type="checkbox" ${m.enabled?'checked':''} data-v57-plan="enabled"> Route</label><label><input type="checkbox" ${m.backupAllowed?'checked':''} data-v57-plan="backupAllowed"> Backup</label></td></tr>`}).join('')}
function hero(){const p=result.primary,b=result.backup;return `<div class="v57-route-hero"><div><small>PRIMARY FACTORY</small><b>${p?esc(p.factoryName):'No route'}</b><span>${p?`${p.status} · route ${p.routeScore}`:'当前没有可承接工厂'}</span></div><div><small>BACKUP FACTORY</small><b>${b?esc(b.factoryName):'Not available'}</b><span>${b?`${b.status} · route ${b.routeScore}`:'需要补充第二工厂能力'}</span></div><div><small>ROUTING MATRIX</small><b>${result.summary.compatible} / ${result.summary.conditional} / ${result.summary.incompatible}</b><span>Compatible / Conditional / Incompatible</span></div></div>`}
function markup(){return `<section class="v57-routing" data-v57-routing><div class="v57-head"><div><span>V0.57 FACTORY JOB ROUTING / AUTO FACTORY SELECTION</span><b>能力优先 · 多工厂比较 · Primary / Backup · Manufacturing Job Ticket</b></div><span>Planning metadata is user/factory supplied · 未录入不造假</span></div><div data-v57-hero>${hero()}</div><div class="v57-job"><label>Job ID<input data-v57-job="jobId" value="${esc(job.jobId)}"></label><label>数量<input type="number" min="1" data-v57-job="quantity" value="${job.quantity}"></label><label>目标交期 d<input type="number" min="0" data-v57-job="targetLeadDays" value="${job.targetLeadDays??''}" placeholder="—"></label><label>预算上限<input type="number" min="0" step="0.01" data-v57-job="maxTotalCost" value="${job.maxTotalCost??''}" placeholder="—"></label><label>币种<input data-v57-job="currency" value="${esc(job.currency)}"></label><label>工艺偏好<select data-v57-job="preferMode"><option value="machine" ${job.preferMode==='machine'?'selected':''}>Machine</option><option value="manual" ${job.preferMode==='manual'?'selected':''}>Manual</option><option value="any" ${job.preferMode==='any'?'selected':''}>Any</option></select></label><button data-v57-route>自动选厂</button><button data-v57-ticket>导出 Job Ticket</button></div><details class="v57-planning"><summary>工厂 Routing Planning Metadata · 优先级 / 负载 / 交期 / 成本 / 产能</summary><div class="v57-table-wrap"><table><thead><tr><th>Factory</th><th>Priority</th><th>Load %</th><th>Lead d</th><th>Cost/1000</th><th>Setup</th><th>Capacity/day</th><th>Flags</th></tr></thead><tbody data-v57-plans>${planningRows()}</tbody></table></div><button data-v57-save-plan>保存 Planning Metadata 并重算</button></details><div class="v57-grid" data-v57-results>${result.candidates.map(candidateCard).join('')}</div><div class="v57-note">路由顺序固定为：硬能力兼容 → 条件能力/交期/负载 → 用户录入优先级与成本。成本、交期、负载未录入时保持空值，不参与虚假比较。Incompatible 工厂不会因为优先级或价格被选为 Primary。</div></section>`}
function refresh(){if(!root||!rebuild())return;const heroNode=root.querySelector('[data-v57-hero]'),plans=root.querySelector('[data-v57-plans]'),results=root.querySelector('[data-v57-results]');if(heroNode)heroNode.innerHTML=hero();if(plans)plans.innerHTML=planningRows();if(results)results.innerHTML=result.candidates.map(candidateCard).join('');bind()}
function readJob(){const q=k=>root?.querySelector(`[data-v57-job="${k}"]`);job=normalizeRoutingJobV57({jobId:q('jobId')?.value,quantity:q('quantity')?.value,targetLeadDays:q('targetLeadDays')?.value===''?null:q('targetLeadDays')?.value,maxTotalCost:q('maxTotalCost')?.value===''?null:q('maxTotalCost')?.value,currency:q('currency')?.value,preferMode:q('preferMode')?.value});save();refresh();return result}
function readPlanning(){root?.querySelectorAll('[data-v57-plan-row]').forEach(row=>{const id=row.dataset.v57PlanRow,q=k=>row.querySelector(`[data-v57-plan="${k}"]`),val=k=>q(k)?.value===''?null:Number(q(k)?.value);routingDb=updateRoutingMetaV57(factoryDb,routingDb,id,{priority:val('priority'),loadPercent:val('loadPercent'),leadDays:val('leadDays'),costPer1000:val('costPer1000'),setupCost:val('setupCost'),capacityPerDay:val('capacityPerDay'),enabled:Boolean(q('enabled')?.checked),backupAllowed:Boolean(q('backupAllowed')?.checked),currency:job.currency})});save();refresh();return result}
function exportTicket(){if(!result?.primary)return null;const text=exportJobTicketV57(buildManufacturingJobTicketV57(result));try{const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${job.jobId||'job'}-manufacturing-ticket-v57.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}catch{}return text}
function bind(){const route=root?.querySelector('[data-v57-route]'),saveBtn=root?.querySelector('[data-v57-save-plan]'),ticket=root?.querySelector('[data-v57-ticket]');if(route)route.onclick=readJob;if(saveBtn)saveBtn.onclick=readPlanning;if(ticket)ticket.onclick=exportTicket}
function enhance(){if(!window.BoxStudioV56||document.body.dataset.v56Factory!=='true')return false;const page=document.querySelector('.three-page.v49-linked-page');if(!page)return false;if(page.dataset.v57Ready==='true'){root=page;return true}factoryDb=window.BoxStudioV56.getDatabase();restore(factoryDb);if(!rebuild())return false;root=page;const anchor=root.querySelector('[data-v56-factory]');if(!anchor)return false;anchor.insertAdjacentHTML('afterend',markup());bind();page.dataset.v57Ready='true';document.body.dataset.v57Routing='true';page.dataset.v57Acceptance=routingAcceptanceV57(result).ok?'pass':'fail';window.BoxStudioV57={version:V57_PRODUCT_VERSION,getRoutingDatabase:()=>structuredClone(routingDb),getJob:()=>structuredClone(job),getResult:()=>structuredClone(result),getAcceptance:()=>routingAcceptanceV57(result),setJob:patch=>{job=normalizeRoutingJobV57({...job,...patch});save();refresh();return structuredClone(result)},updatePlanning:(factoryId,patch)=>{routingDb=updateRoutingMetaV57(factoryDb,routingDb,factoryId,patch);save();refresh();return structuredClone(result)},route:()=>{refresh();return structuredClone(result)},getTicket:()=>buildManufacturingJobTicketV57(result),exportTicket:()=>exportJobTicketV57(buildManufacturingJobTicketV57(result)),resetPlanning:()=>{routingDb=createRoutingDatabaseV57(factoryDb);save();refresh();return structuredClone(result)},refresh:()=>{refresh();return structuredClone(result)}};return true}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;if(!document.querySelector('.three-page.v49-linked-page')){root=null;return}enhance()})}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule();
