import { STORAGE_KEY, defaultState, cloneState } from './model.js';
import { buildLinkedWorkspaceModelV49 } from './linkedWorkspaceV49.js';
import { resolveElementRect } from './geometry.js';
import { cleanSvg, downloadText, exportPng } from './export.js';
import { V60_PRODUCT_VERSION,V60_IMAGE_LIMITS,processArtworkFileV60,createImageElementV60,normalizeImageElementV60,imagePreserveAspectRatioV60,imageEffectiveDpiV60,imagePreflightChecksV60,imageAcceptanceV60 } from './artworkImageV60.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let queued=false,drag=null;
const v64Runtime=window.BoxStudioUiRuntimeV64;
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'),b=cloneState(defaultState);return p?{...b,...p,structure:{...b.structure,...(p.structure||{})},variables:{...b.variables,...(p.variables||{})},elements:Array.isArray(p.elements)?p.elements:[]}:b}catch{return cloneState(defaultState)}}
function saveState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function currentPage(){return document.querySelector('.nav button.active')?.dataset.nav||readState().page}
function currentTab(){return document.querySelector('.tabbar button.active')?.dataset.tab||readState().editorTab}
function reload(){if(window.BoxStudioEditor?.reloadFromStorage)window.BoxStudioEditor.reloadFromStorage();else location.reload()}
function imageElements(){return(readState().elements||[]).filter(x=>x?.type==='image').map(normalizeImageElementV60)}
function currentModel(){const state=readState(),model=buildLinkedWorkspaceModelV49(state);return{state,model,geo:model.review.geo}}
function targetPanel(state,geo){const selected=state.elements?.find(x=>x.id===state.selectedId),ids=[selected?.panelId,state.markEditorPanelId,state.linkedV49?.selectedPanelId,'front','base'];for(const id of ids)if(id&&geo.panelMap?.[id])return geo.panelMap[id];return(geo.bodyPanels||[]).find(p=>p.kind==='panel')||geo.bodyPanels?.[0]||null}
function ensurePicker(){if(document.querySelector('#v60ArtworkFile'))return;const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp';input.id='v60ArtworkFile';input.hidden=true;document.body.appendChild(input);input.onchange=async()=>{const file=input.files?.[0];if(!file)return;input.value='';await addFile(file)}}
async function addFile(file,{replaceId=null}={}){const asset=await processArtworkFileV60(file),{state,geo}=currentModel();if(replaceId){const i=state.elements.findIndex(x=>x.id===replaceId&&x.type==='image');if(i<0)throw new Error('V60_IMAGE_NOT_FOUND');state.elements[i]=normalizeImageElementV60({...state.elements[i],...asset,id:replaceId});state.selectedId=replaceId}else{const panel=targetPanel(state,geo);if(!panel)throw new Error('V60_IMAGE_NO_TARGET_PANEL');const el=createImageElementV60(asset,panel,{panelId:panel.id});state.elements.push(el);state.selectedId=el.id;state.page='editor';state.editorTab='Design'}saveState(state);reload()}
function enableImageTool(){ensurePicker();const b=document.querySelector('.toolbar [data-tool="image"]');if(!b)return;b.disabled=false;b.removeAttribute('aria-disabled');b.title='上传图片 / Logo · PNG / JPEG / WebP';b.classList.add('v60-image-tool');b.onclick=e=>{e.preventDefault();e.stopPropagation();document.querySelector('#v60ArtworkFile')?.click()}}
function svgPoint(svg,evt){const pt=svg.createSVGPoint();pt.x=evt.clientX;pt.y=evt.clientY;return pt.matrixTransform(svg.getScreenCTM().inverse())}
function renderImageNode(svg,layer,el,geo,state){const rr=resolveElementRect(el,geo),ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.dataset.v60Image=el.id;g.dataset.elementId=el.id;g.setAttribute('class','v60-image-node element-hit');g.setAttribute('transform',`translate(${rr.absX} ${rr.absY}) rotate(${el.r||0} ${el.w/2} ${el.h/2})`);const image=document.createElementNS(ns,'image');image.setAttribute('href',el.src);image.setAttributeNS('http://www.w3.org/1999/xlink','href',el.src);image.setAttribute('width',String(el.w));image.setAttribute('height',String(el.h));image.setAttribute('preserveAspectRatio',imagePreserveAspectRatioV60(el.fit));image.setAttribute('opacity',String(el.opacity));image.setAttribute('class','v60-raster-image');g.appendChild(image);const hit=document.createElementNS(ns,'rect');hit.setAttribute('width',String(el.w));hit.setAttribute('height',String(el.h));hit.setAttribute('fill','transparent');hit.setAttribute('class','v60-image-hit');g.appendChild(hit);if(state.selectedId===el.id){const sel=document.createElementNS(ns,'rect');sel.setAttribute('x','-2');sel.setAttribute('y','-2');sel.setAttribute('width',String(el.w+4));sel.setAttribute('height',String(el.h+4));sel.setAttribute('class','v60-image-selection ui-only');g.appendChild(sel)}g.addEventListener('pointerdown',e=>startDrag(e,svg,g,el,geo));layer.appendChild(g)}
function imageSignature(state){const rows=(state.elements||[]).filter(x=>x?.type==='image').map(x=>{const e=normalizeImageElementV60(x);return[e.id,e.panelId,e.x,e.y,e.w,e.h,e.r,e.fit,e.opacity,e.name,e.pixelWidth,e.pixelHeight,e.src.length]});return JSON.stringify([state.selectedId,Boolean(state.hiddenGroups?.marks),rows])}
function injectImages(){const svg=document.querySelector('#designSvg'),layer=svg?.querySelector('#artwork-layer');if(!svg||!layer)return;const state=readState(),images=(state.elements||[]).filter(x=>x?.type==='image'),sig=imageSignature(state),count=layer.querySelectorAll('[data-v60-image]').length;if(svg.dataset.v60ImageSig===sig&&count===(state.hiddenGroups?.marks?0:images.length))return;layer.querySelectorAll('[data-v60-image]').forEach(n=>n.remove());svg.dataset.v60ImageSig=sig;if(state.hiddenGroups?.marks)return;const geo=buildLinkedWorkspaceModelV49(state).review.geo;for(const raw of images)if(geo.panelMap?.[raw.panelId])renderImageNode(svg,layer,normalizeImageElementV60(raw),geo,state)}
function startDrag(evt,svg,node,el,geo){const state=readState(),p=svgPoint(svg,evt),rr=resolveElementRect(el,geo);state.selectedId=el.id;saveState(state);drag={id:el.id,start:p,origX:rr.absX,origY:rr.absY,lastX:rr.absX,lastY:rr.absY,node,geo,moved:false};try{node.setPointerCapture?.(evt.pointerId)}catch{}node.addEventListener('pointermove',moveDrag);node.addEventListener('pointerup',endDrag,{once:true});node.addEventListener('pointercancel',endDrag,{once:true});evt.stopPropagation();evt.preventDefault()}
function moveDrag(evt){if(!drag)return;const svg=document.querySelector('#designSvg');if(!svg)return;const p=svgPoint(svg,evt),dx=p.x-drag.start.x,dy=p.y-drag.start.y;drag.lastX=drag.origX+dx;drag.lastY=drag.origY+dy;drag.moved=Math.abs(dx)+Math.abs(dy)>.4;const state=readState(),el=state.elements.find(x=>x.id===drag.id);if(el)drag.node.setAttribute('transform',`translate(${drag.lastX} ${drag.lastY}) rotate(${el.r||0} ${el.w/2} ${el.h/2})`)}
function endDrag(){if(!drag)return;const d=drag;drag=null;const state=readState(),el=state.elements.find(x=>x.id===d.id),panel=d.geo.panelMap?.[el?.panelId];if(el&&panel&&d.moved){el.x=Math.max(0,Math.min(Math.max(0,panel.w-el.w),d.lastX-panel.x));el.y=Math.max(0,Math.min(Math.max(0,panel.h-el.h),d.lastY-panel.y))}if(el)state.selectedId=el.id;saveState(state);reload()}
function inspectorHtml(el){const dpi=imageEffectiveDpiV60(el),tone=dpi<V60_IMAGE_LIMITS.minDpi?'bad':dpi<V60_IMAGE_LIMITS.warnDpi?'warn':'good';return `<section class="panel-section v60-image-inspector" data-v60-image-inspector><div class="section-title"><h3>图片 / Logo</h3><span class="v60-dpi ${tone}">${dpi} DPI</span></div><div class="v60-image-source"><div class="v60-thumb"><img src="${esc(el.src)}" alt=""></div><div><b>${esc(el.name)}</b><span>${el.pixelWidth} × ${el.pixelHeight} px · ${(el.assetBytes/1024).toFixed(0)} KB</span></div></div><div class="field"><label>适配</label><select data-v60-fit><option value="contain" ${el.fit==='contain'?'selected':''}>Contain · 完整显示</option><option value="cover" ${el.fit==='cover'?'selected':''}>Cover · 填满裁切</option><option value="stretch" ${el.fit==='stretch'?'selected':''}>Stretch · 拉伸</option></select></div><div class="field"><label>透明度 <b data-v60-opacity-label>${Math.round(el.opacity*100)}%</b></label><input data-v60-opacity type="range" min="0" max="100" value="${Math.round(el.opacity*100)}"></div><div class="row"><button class="mini" data-v60-ratio>恢复原比例</button><button class="mini" data-v60-replace>替换图片</button></div><button class="mini danger full" data-v60-delete>删除图片</button>${el.pdfTransparencyFlattened?`<div class="notice v60-pdf-note">透明 PNG/WebP 在普通 Production PDF 中以 <b>${esc(el.pdfMatte)}</b> 展平；SVG / PNG / 3D 保留透明度。</div>`:'<div class="notice">Production PDF 使用原 JPEG 数据作为 Image XObject；SVG / PNG / 3D 使用同一 artwork 元素。</div>'}</section>`}
function enhanceInspector(){if(currentPage()!=='editor'||!['Design','Marks'].includes(currentTab()))return;const state=readState(),el=normalizeImageElementV60(state.elements?.find(x=>x.id===state.selectedId&&x.type==='image')||{});if(!el.id)return;const right=document.querySelector('.rightpanel');if(!right||right.querySelector('[data-v60-image-inspector]'))return;right.insertAdjacentHTML('afterbegin',inspectorHtml(el));const card=right.querySelector('[data-v60-image-inspector]');card.querySelector('[data-v60-fit]').onchange=e=>updateSelected(x=>x.fit=e.target.value);const op=card.querySelector('[data-v60-opacity]'),lab=card.querySelector('[data-v60-opacity-label]');op.oninput=e=>{lab.textContent=`${e.target.value}%`};op.onchange=e=>updateSelected(x=>x.opacity=Number(e.target.value)/100);card.querySelector('[data-v60-ratio]').onclick=()=>updateSelected(x=>{const a=Math.max(.05,x.pixelWidth/x.pixelHeight);x.h=Math.max(1,x.w/a)});card.querySelector('[data-v60-delete]').onclick=()=>{const s=readState();s.elements=s.elements.filter(x=>x.id!==el.id);s.selectedId=null;saveState(s);reload()};card.querySelector('[data-v60-replace]').onclick=()=>{const input=document.querySelector('#v60ArtworkFile');input.onchange=async()=>{const f=input.files?.[0];if(f){input.value='';await addFile(f,{replaceId:el.id})}};input.click()}}
function updateSelected(fn){const s=readState(),i=s.elements.findIndex(x=>x.id===s.selectedId&&x.type==='image');if(i<0)return;const el=normalizeImageElementV60(s.elements[i]);fn(el);s.elements[i]=normalizeImageElementV60(el);saveState(s);reload()}
function preflightHtml(checks){const count=t=>checks.filter(x=>x.severity===t).length;return `<section class="v60-preflight" data-v60-preflight><div class="v60-preflight-head"><div><span>RASTER ARTWORK</span><b>图片 / Logo 印前检查</b></div><div><i class="pass">${count('pass')} Pass</i><i class="warning">${count('warning')} Warn</i><i class="error">${count('error')} Error</i></div></div>${checks.length?checks.map(x=>`<div class="v60-preflight-row ${x.severity}"><b>${x.severity==='pass'?'✓':x.severity==='warning'?'!':'×'} ${esc(x.title)}</b><span>${esc(x.detail)}</span></div>`).join(''):'<div class="notice">当前项目没有 Raster Artwork。</div>'}</section>`}
function enhancePreflight(){if(currentPage()!=='editor'||currentTab()!=='Preflight')return;const host=document.querySelector('.review-page');if(!host||host.querySelector('[data-v60-preflight]'))return;host.querySelector('.review-head')?.insertAdjacentHTML('afterend',preflightHtml(imagePreflightChecksV60(readState())))}
async function switchToDesignAndCapture(){const tab=document.querySelector('.tabbar [data-tab="Design"]');tab?.click();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));injectImages();const svg=document.querySelector('#designSvg');if(!svg)throw new Error('V60_DESIGN_SVG_UNAVAILABLE');return svg}
async function exportSvgWithImages(){const svg=await switchToDesignAndCapture(),s=readState(),text=cleanSvg(svg,s.exportOptions||{});downloadText('boxstudio-production.svg',text,'image/svg+xml;charset=utf-8');return text}
async function exportPngWithImages(){const svg=await switchToDesignAndCapture(),s=readState();await exportPng(svg,s.exportOptions||{});return true}
function enhanceExports(){if(currentPage()!=='editor'||currentTab()!=='Export')return;const svg=document.querySelector('#exportSvg'),png=document.querySelector('#exportPng');if(svg&&!svg.dataset.v60){svg.dataset.v60='true';svg.onclick=async()=>{try{await exportSvgWithImages()}catch(e){alert(e?.message||e)}}}if(png&&!png.dataset.v60){png.dataset.v60='true';png.onclick=async()=>{try{await exportPngWithImages()}catch(e){alert(e?.message||e)}}}const grid=document.querySelector('.export-grid');if(grid&&!document.querySelector('[data-v60-export-note]'))grid.insertAdjacentHTML('beforebegin','<div class="notice v60-export-note" data-v60-export-note><b>Raster artwork:</b> SVG / PNG / 3D 保留嵌入图像；普通 Production PDF 以 JPEG XObject 嵌入。透明 PNG/WebP 的 PDF companion 会在白色背景上展平，并在 Preflight 明确提示；PDF/X-4 Candidate 暂不接受 RGB raster artwork。</div>')}
function nudge3d(){if(currentPage()!=='editor')return;if(!document.querySelector('.v17-proof-renderer'))return;setTimeout(()=>{for(const canvas of document.querySelectorAll('.v17-proof-renderer')){const host=canvas.parentElement;if(!host)continue;const h=host.style.minHeight;host.style.minHeight=`${Math.max(1,host.getBoundingClientRect().height+1)}px`;requestAnimationFrame(()=>host.style.minHeight=h)}},180)}
function addDesignCallout(){if(v64Runtime?.policy?.suppressLegacyArtworkCallout===true){document.querySelector('[data-v60-artwork-callout]')?.remove();return}if(currentPage()!=='editor'||currentTab()!=='Design')return;const main=document.querySelector('.workspace .main');if(!main||main.querySelector('[data-v60-artwork-callout]'))return;const canvas=main.querySelector('.canvas-shell');canvas?.insertAdjacentHTML('beforebegin',`<div class="v60-artwork-callout" data-v60-artwork-callout><div><span>ARTWORK</span><b>上传 Logo / 图片</b><small>PNG · JPEG · WebP → 2D 面板 → 实时 3D → SVG / PNG / Production PDF</small></div><button data-v60-upload>上传图片</button></div>`);main.querySelector('[data-v60-upload]')?.addEventListener('click',()=>document.querySelector('#v60ArtworkFile')?.click())}
function enhance(){const brand=document.querySelector('.brand small');if(brand&&brand.textContent!==V60_PRODUCT_VERSION)brand.textContent=V60_PRODUCT_VERSION;enableImageTool();if(currentPage()==='editor'){addDesignCallout();injectImages();enhanceInspector();enhancePreflight();enhanceExports();nudge3d()}document.body.dataset.v60Acceptance=imageAcceptanceV60().ok?'pass':'fail'}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;enhance()})}
if(v64Runtime?.register)v64Runtime.register('v60',enhance);else{new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});enhance()}
window.BoxStudioV60={version:V60_PRODUCT_VERSION,limits:V60_IMAGE_LIMITS,getImages:imageElements,getChecks:()=>imagePreflightChecksV60(readState()),getAcceptance:imageAcceptanceV60,addFile,exportSvgWithImages,exportPngWithImages,injectImages};