import { STORAGE_KEY,defaultState,cloneState } from './model.js';
import { buildLinkedWorkspaceModelV49 } from './linkedWorkspaceV49.js';
import { V61_PRODUCT_VERSION,V61_SWATCHES,normalizeColorV61,printablePanelsV61,panelFillForV61,upsertPanelFillV61,removePanelFillV61,clearPanelFillsV61,applyAllPanelFillsV61,syncPanelFillsV61,artworkStatsV61,artworkAcceptanceV61 } from './artworkStudioV61.js';

const VIEW_KEY='boxstudio-v61-artwork-view';
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let queued=false;
const v64Runtime=window.BoxStudioUiRuntimeV64;
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'),b=cloneState(defaultState);return p?{...b,...p,structure:{...b.structure,...(p.structure||{})},variables:{...b.variables,...(p.variables||{})},elements:Array.isArray(p.elements)?p.elements:[]}:b}catch{return cloneState(defaultState)}}
function saveState(s){s.savedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function currentPage(){return document.querySelector('.nav button.active')?.dataset.nav||readState().page}
function currentTab(){return document.querySelector('.tabbar button.active')?.dataset.tab||readState().editorTab}
function model(){const state=readState(),linked=buildLinkedWorkspaceModelV49(state);return{state,linked,geo:linked.review.geo}}
function currentPanel(state,geo){const ids=[state.linkedV49?.selectedPanelId,state.markEditorPanelId,state.elements?.find(x=>x.id===state.selectedId)?.panelId,'front','base'];for(const id of ids)if(id&&geo.panelMap?.[id])return geo.panelMap[id];return printablePanelsV61(geo)[0]||null}
function persist(next,{refresh=true}={}){saveState(next);if(refresh){location.reload();return}injectPanelFills();updateStudio()}
function fillSignature(state){return JSON.stringify((state.elements||[]).filter(e=>e?.v61PanelFill===true).map(e=>[e.panelId,e.fillColor,e.points]))}
function ensureVersionBadge(){const brand=document.querySelector('.brand');if(!brand)return;brand.querySelector('small')?.remove();let badge=brand.querySelector('[data-v61-version]');if(!badge){badge=document.createElement('span');badge.dataset.v61Version='true';badge.className='v61-version-badge';brand.appendChild(badge)}if(badge.textContent!==V61_PRODUCT_VERSION)badge.textContent=V61_PRODUCT_VERSION}
function injectPanelFills(){
  if(currentPage()!=='editor'||!['Design','Marks'].includes(currentTab()))return;const svg=document.querySelector('#designSvg'),layer=svg?.querySelector('#artwork-layer');if(!svg||!layer)return;const {state,geo}=model(),sig=fillSignature(state);if(svg.dataset.v61FillSig===sig)return;layer.querySelectorAll('[data-v61-panel-fill]').forEach(n=>n.remove());
  for(const raw of(state.elements||[]).filter(e=>e?.v61PanelFill===true)){const p=geo.panelMap?.[raw.panelId];if(!p)continue;const ns='http://www.w3.org/2000/svg',poly=document.createElementNS(ns,'polygon'),pts=(raw.points||[]).map(q=>`${p.x+Number(q[0]||0)},${p.y+Number(q[1]||0)}`).join(' ');poly.setAttribute('points',pts);poly.setAttribute('fill',normalizeColorV61(raw.fillColor));poly.setAttribute('class','v61-panel-fill');poly.dataset.v61PanelFill=raw.panelId;layer.insertBefore(poly,layer.firstChild)}svg.dataset.v61FillSig=sig;
}
function viewMode(){const mobile=window.innerWidth<=760;return localStorage.getItem(VIEW_KEY)|| (mobile?'2d':'split')}
function setView(mode){if(!['2d','split','3d'].includes(mode))mode='split';localStorage.setItem(VIEW_KEY,mode);document.body.dataset.v61ArtworkView=mode;if(mode==='3d'){document.querySelector('.tabbar [data-tab="3D"]')?.click();return}if(currentTab()!=='Design')document.querySelector('.tabbar [data-tab="Design"]')?.click();queueMicrotask(()=>applyView())}
function applyView(){const mode=viewMode();document.body.dataset.v61ArtworkView=mode;document.querySelectorAll('[data-v61-view]').forEach(b=>b.classList.toggle('active',b.dataset.v61View===mode));const mini=document.querySelector('[data-v58-mini3d]');if(mini)mini.hidden=mode==='2d'}
function swatches(color){return V61_SWATCHES.map(c=>`<button type="button" data-v61-swatch="${c}" class="${c===color?'active':''}" title="${c}" style="--sw:${c}"></button>`).join('')}
function studioHtml(){const {state,geo}=model(),panels=printablePanelsV61(geo),panel=currentPanel(state,geo),fill=panel?panelFillForV61(state,panel.id):null,color=normalizeColorV61(fill?.fillColor||'#ffffff'),stats=artworkStatsV61(state,geo);return `<section class="v61-artwork-studio" data-v61-studio><div class="v61-artwork-head"><div><span>ARTWORK WORKSPACE</span><b>2D 设计 · 面板配色 · Logo · 唛头 · 实时 3D</b><small>同一份 Artwork 数据贯穿展开图、3D 和生产导出。</small></div><div class="v61-view-switch"><button data-v61-view="2d">2D</button><button data-v61-view="split">2D + 3D</button><button data-v61-view="3d">3D</button></div></div><div class="v61-artwork-grid"><div class="v61-panel-style"><label>目标面<select data-v61-panel>${panels.map(p=>`<option value="${esc(p.id)}" ${p.id===panel?.id?'selected':''}>${esc(p.label||p.id)}</option>`).join('')}</select></label><label>面板底色<div class="v61-color-line"><input data-v61-color type="color" value="${color}"><code>${color}</code></div></label><div class="v61-swatches">${swatches(color)}</div><div class="v61-panel-actions"><button class="primary" data-v61-apply>应用到当前面</button><button data-v61-all>应用到全部面</button><button data-v61-clear>清除当前面</button><button data-v61-clear-all>清除全部底色</button></div></div><div class="v61-quick-tools"><span>常用设计</span><div><button data-v61-tool="text"><b>T</b>文字</button><button data-v61-tool="image"><b>▧</b>Logo / 图片</button><button data-v61-tool="marks"><b>▥</b>唛头</button><button data-v61-tool="3d"><b>◈</b>完整 3D</button></div><p>图片支持 PNG / JPEG / WebP；唛头支持变量、条码 / QR 和 Excel / CSV 批量数据。</p></div><div class="v61-artwork-summary"><span>当前 Artwork</span><div><b>${stats.styledPanels}</b><small>配色面</small></div><div><b>${stats.images}</b><small>图片</small></div><div><b>${stats.texts}</b><small>文字</small></div><div><b>${stats.marks}</b><small>唛头对象</small></div></div></div></section>`}
function bindStudio(host){
  const select=host.querySelector('[data-v61-panel]'),color=host.querySelector('[data-v61-color]');const setColor=c=>{color.value=normalizeColorV61(c);host.querySelector('.v61-color-line code').textContent=color.value;host.querySelectorAll('[data-v61-swatch]').forEach(b=>b.classList.toggle('active',b.dataset.v61Swatch===color.value))};color.oninput=e=>setColor(e.target.value);host.querySelectorAll('[data-v61-swatch]').forEach(b=>b.onclick=()=>setColor(b.dataset.v61Swatch));
  host.querySelector('[data-v61-apply]').onclick=()=>{const {state,geo}=model();persist(upsertPanelFillV61(state,geo,select.value,color.value))};
  host.querySelector('[data-v61-all]').onclick=()=>{const {state,geo}=model();persist(applyAllPanelFillsV61(state,geo,color.value))};
  host.querySelector('[data-v61-clear]').onclick=()=>persist(removePanelFillV61(readState(),select.value));host.querySelector('[data-v61-clear-all]').onclick=()=>persist(clearPanelFillsV61(readState()));
  host.querySelectorAll('[data-v61-view]').forEach(b=>b.onclick=()=>setView(b.dataset.v61View));
  host.querySelector('[data-v61-tool="text"]').onclick=()=>document.querySelector('.toolbar [data-tool="text"]')?.click();host.querySelector('[data-v61-tool="image"]').onclick=()=>document.querySelector('#v60ArtworkFile')?.click();host.querySelector('[data-v61-tool="marks"]').onclick=()=>document.querySelector('.tabbar [data-tab="Marks"]')?.click();host.querySelector('[data-v61-tool="3d"]').onclick=()=>document.querySelector('.tabbar [data-tab="3D"]')?.click();applyView();
}
function ensureStudio(){if(currentPage()!=='editor'||currentTab()!=='Design')return;const main=document.querySelector('.workspace .main'),canvas=main?.querySelector('.canvas-shell');if(!main||!canvas)return;if(!main.querySelector('[data-v61-studio]')){canvas.insertAdjacentHTML('beforebegin',studioHtml());bindStudio(main.querySelector('[data-v61-studio]'))}injectPanelFills();applyView()}
function updateStudio(){const old=document.querySelector('[data-v61-studio]');if(!old)return;const shell=document.createElement('div');shell.innerHTML=studioHtml();const next=shell.firstElementChild;old.replaceWith(next);bindStudio(next);injectPanelFills()}
function syncExistingFills(){if(currentPage()!=='editor')return;const {state,geo}=model(),synced=syncPanelFillsV61(state,geo);if(fillSignature(synced)!==fillSignature(state))saveState(synced)}
function enhance(){ensureVersionBadge();syncExistingFills();ensureStudio();if(currentPage()==='editor'&&['Design','Marks'].includes(currentTab()))injectPanelFills();applyView();document.body.dataset.v61Acceptance=artworkAcceptanceV61().ok?'pass':'fail'}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;enhance()})}
if(v64Runtime?.register)v64Runtime.register('v61',enhance);else{new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});enhance()}
window.BoxStudioV61={version:V61_PRODUCT_VERSION,swatches:V61_SWATCHES,getState:readState,getStats:()=>{const {state,geo}=model();return artworkStatsV61(state,geo)},applyPanelColor:(panelId,color)=>{const {state,geo}=model(),next=upsertPanelFillV61(state,geo,panelId,color);persist(next);return next},applyAllColors:color=>{const {state,geo}=model(),next=applyAllPanelFillsV61(state,geo,color);persist(next);return next},clearPanel:panelId=>persist(removePanelFillV61(readState(),panelId)),clearAll:()=>persist(clearPanelFillsV61(readState())),setView,getView:viewMode,getAcceptance:artworkAcceptanceV61};
