import { STORAGE_KEY,defaultState,cloneState } from './model.js';
import { V63_PRODUCT_VERSION,V63_ADVANCED_INSPECTOR_KEY,V63_STAGES,stageForTabV63,nextStageV63,workspaceSummaryV63,studioShellAcceptanceV63 } from './studioShellV63.js';

const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let queued=false;
function readState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'),b=cloneState(defaultState);return p?{...b,...p,structure:{...b.structure,...(p.structure||{})},variables:{...b.variables,...(p.variables||{})},elements:Array.isArray(p.elements)?p.elements:[]}:b}catch{return cloneState(defaultState)}}
function currentPage(){return document.querySelector('.nav button.active')?.dataset.nav||readState().page}
function currentTab(){return document.querySelector('.tabbar button.active')?.dataset.tab||readState().editorTab||'Design'}
function advancedOpen(){return localStorage.getItem(V63_ADVANCED_INSPECTOR_KEY)==='1'}
function goTab(tab){const button=document.querySelector(`.tabbar [data-tab="${tab}"]`);if(button){button.click();return true}return false}
function ensureVersionBadge(){const brand=document.querySelector('.brand');if(!brand)return;let badge=brand.querySelector('[data-v63-version]');if(!badge){badge=document.createElement('span');badge.dataset.v63Version='true';badge.className='v63-version-badge';brand.appendChild(badge)}if(badge.textContent!==V63_PRODUCT_VERSION)badge.textContent=V63_PRODUCT_VERSION;document.body.dataset.v63='true'}
function stageButton(stage,index,current){return `<button data-v63-stage="${stage.tab}" class="${stage.id===current.id?'active':''}"><i>${index+1}</i><span><b>${esc(stage.label)}</b><small>${esc(stage.hint)}</small></span></button>`}
function stagebarHtml(){const state=readState(),summary=workspaceSummaryV63(state),current=stageForTabV63(currentTab()),next=nextStageV63(currentTab()),p=summary.preflight,a=summary.artwork,s=summary.structure;return `<section class="v63-stagebar" data-v63-stagebar><div class="v63-stage-row">${V63_STAGES.map((x,i)=>stageButton(x,i,current)).join('')}</div><div class="v63-work-status"><span><b>${esc(s.template||'structure')}</b><small>${s.length} × ${s.width} × ${s.height} mm${s.materialId?` · ${esc(s.materialId)}`:''}</small></span><span><b>${a.images+a.texts+a.marks+a.styledPanels}</b><small>Artwork objects</small></span><span class="${p.error?'error':p.warning?'warn':'ok'}"><b>${p.error?p.error:p.warning}</b><small>${p.error?'Preflight errors':p.warning?'Preflight warnings':'Preflight ready'}</small></span><button data-v63-next="${next.tab}" ${current.id==='export'?'disabled':''}>${current.id==='export'?'流程完成':`下一步 · ${esc(next.label)}`} →</button></div></section>`}
function bindStagebar(root){root.querySelectorAll('[data-v63-stage]').forEach(b=>b.onclick=()=>goTab(b.dataset.v63Stage));root.querySelector('[data-v63-next]')?.addEventListener('click',e=>goTab(e.currentTarget.dataset.v63Next))}
function ensureStagebar(){if(currentPage()!=='editor')return;const main=document.querySelector('.workspace .main'),tabs=main?.querySelector('.tabbar');if(!main||!tabs)return;if(main.querySelector('[data-v63-stagebar]'))return;const shell=document.createElement('div');shell.innerHTML=stagebarHtml();const bar=shell.firstElementChild;tabs.insertAdjacentElement('beforebegin',bar);bindStagebar(bar)}
function markSecondaryPanels(){const right=document.querySelector('.rightpanel');if(!right)return;for(const section of right.querySelectorAll('.panel-section')){const title=section.querySelector('h3')?.textContent?.trim();section.classList.toggle('v63-secondary-panel',['Data','Layers','Project'].includes(title))}right.classList.toggle('v63-advanced-open',advancedOpen())}
function inspectorHtml(){const summary=workspaceSummaryV63(readState()),x=summary.selected,p=summary.preflight,size=x.objectSize?`${x.objectSize.w.toFixed(1)} × ${x.objectSize.h.toFixed(1)} mm`:x.panelSize?`${x.panelSize.w.toFixed(1)} × ${x.panelSize.h.toFixed(1)} mm`:'—';return `<section class="v63-inspector" data-v63-inspector><div class="v63-inspector-head"><div><span>CONTEXT</span><b>${esc(x.elementId||x.panelLabel)}</b><small>${esc(x.typeLabel)} · ${esc(x.panelLabel)} · ${size}</small></div><span class="v63-preflight-pill ${p.error?'error':p.warning?'warn':'ok'}">${p.error?`${p.error} errors`:p.warning?`${p.warning} warnings`:'ready'}</span></div><div class="v63-inspector-actions"><button data-v63-inspector-go="Design">Artwork</button><button data-v63-inspector-go="Marks">唛头</button><button data-v63-inspector-go="3D">3D</button><button data-v63-advanced>${advancedOpen()?'收起数据 / 图层':'数据 / 图层'}</button></div></section>`}
function bindInspector(root){root.querySelectorAll('[data-v63-inspector-go]').forEach(b=>b.onclick=()=>goTab(b.dataset.v63InspectorGo));root.querySelector('[data-v63-advanced]').onclick=()=>{const next=!advancedOpen();localStorage.setItem(V63_ADVANCED_INSPECTOR_KEY,next?'1':'0');document.querySelector('.rightpanel')?.classList.toggle('v63-advanced-open',next);root.querySelector('[data-v63-advanced]').textContent=next?'收起数据 / 图层':'数据 / 图层'}}
function ensureInspector(){if(currentPage()!=='editor')return;const right=document.querySelector('.rightpanel');if(!right)return;markSecondaryPanels();if(right.querySelector('[data-v63-inspector]'))return;const shell=document.createElement('div');shell.innerHTML=inspectorHtml();const card=shell.firstElementChild;right.prepend(card);bindInspector(card)}
function enableImageTool(){if(currentPage()!=='editor')return;const button=document.querySelector('.toolbar [data-tool="image"]');if(!button)return;button.disabled=false;button.removeAttribute('disabled');button.removeAttribute('aria-disabled');button.dataset.v63Image='true';button.title='Logo / 图片';button.onclick=e=>{e.preventDefault();e.stopPropagation();if(currentTab()!=='Design'){goTab('Design');return}const input=document.querySelector('#v60ArtworkFile');if(input)input.click()}}
function compactArtwork(){if(currentPage()!=='editor'||currentTab()!=='Design')return;document.querySelector('[data-v61-studio]')?.classList.add('v63-consolidated-artwork')}
function enhance(){ensureVersionBadge();if(currentPage()==='editor'){ensureStagebar();ensureInspector();enableImageTool();compactArtwork()}document.body.dataset.v63Acceptance=studioShellAcceptanceV63(readState()).ok?'pass':'fail'}
function schedule(){if(queued)return;queued=true;queueMicrotask(()=>{queued=false;enhance()})}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});enhance();
window.BoxStudioV63={version:V63_PRODUCT_VERSION,stages:V63_STAGES,getState:readState,getSummary:()=>workspaceSummaryV63(readState()),getAcceptance:()=>studioShellAcceptanceV63(readState()),go:goTab,setAdvanced:on=>{localStorage.setItem(V63_ADVANCED_INSPECTOR_KEY,on?'1':'0');markSecondaryPanels();return advancedOpen()}};
