import {LIGHT_RIGS_V74,lightingSettingsV74,disposePhysicalStudioV74} from './studioLightingV74.js';
import {recordSceneAnimationV72,animationMimeV72} from './sceneAnimationV72.js';
import {DESIGN_PRESETS_V71,createArtworkProjectV71,designCategoryLabelV71} from './designTemplatesV71.js';
import {STANDARD_TEMPLATE_CATALOG} from './templates.js';
import {generateGeometry} from './geometry.js';
import {buildFoldGraph} from './foldgraph.js';
import {prepareSceneV71,renderSceneV71,SCENES_V71,sceneSettingsV71} from './scene3dV71.js';
import {buildArtworkGlbV71,foldedMeshesV71} from './threeExportV71.js';
import {iconV67} from './uiIconsV67.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),editor=()=>window.BoxStudioEditor;
const STORE='boxstudio-design-templates-v71';
let dialog=null;
function stored(){try{const rows=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(rows)?rows.filter(r=>r.id&&r.name&&r.state?.structure).slice(0,20):[];}catch{return[];}}
function feedback(message){const n=document.querySelector('[data-v67-toast]');if(n){n.textContent=message;n.dataset.visible='true';setTimeout(()=>{n.dataset.visible='false';},3200);}else alert(message);}
function close(){if(!dialog)return;const d=dialog;dialog=null;d.close();d.remove();}
function createDialog(title,kind='templates'){
 close();const d=document.createElement('dialog');d.className=`v67-dialog v71-dialog v71-${kind}`;d.setAttribute('aria-labelledby','v71-dialog-title');d.innerHTML=`<header><div><span class="v71-eyebrow">BOXSTUDIO · FREE TO CREATE</span><h2 id="v71-dialog-title">${esc(title)}</h2></div><button data-v71-close aria-label="关闭窗口">${iconV67('close')}</button></header><div class="v71-content"></div>`;document.body.append(d);dialog=d;d.querySelector('[data-v71-close]').onclick=close;d.addEventListener('cancel',e=>{e.preventDefault();close();});d.addEventListener('close',()=>{if(dialog===d)dialog=null;d.remove();},{once:true});d.showModal();return d;
}
function preserve(){if(editor().getState().page==='mark-studio')throw new Error('请先切换到纸盒工作台。');window.BoxStudioV66.saveProject();}
function openDesignTemplates(){
 const d=createDialog('设计模板'),content=d.querySelector('.v71-content'),templates=STANDARD_TEMPLATE_CATALOG.filter(t=>t.engine),current=editor().getState();let category='all';
 content.innerHTML=`<p class="v71-intro">选择原创设计，创建可继续编辑的新项目。当前项目会先保存。</p><div class="v71-template-config"><label>纸盒结构<select data-v71-structure>${templates.map(t=>`<option value="${esc(t.id)}" ${t.id===current.structure.template?'selected':''}>${esc(t.nameZh)}</option>`).join('')}</select></label><label>新项目名称<input data-v71-project-name placeholder="使用模板默认名称" maxlength="120"></label></div><nav class="v71-filter" aria-label="设计类别">${[['all','全部'],['food','食品'],['care','护理'],['gift','礼品'],['industrial','工业'],['minimal','极简'],['saved','我的模板']].map(([id,name])=>`<button data-v71-filter="${id}" aria-pressed="${id==='all'}">${name}</button>`).join('')}</nav><div class="v71-preset-grid" data-v71-presets></div><footer class="v71-template-footer"><p role="status" data-v71-status></p><button data-v71-save-design>将当前设计保存为模板</button></footer>`;
 const status=message=>{d.querySelector('[data-v71-status]').textContent=message;};
 function render(){const rows=category==='saved'?stored():DESIGN_PRESETS_V71.filter(p=>category==='all'||p.category===category);d.querySelector('[data-v71-presets]').innerHTML=rows.map(p=>`<article class="v71-preset"><div class="v71-design-preview ${esc(p.layout||'corner')}" style="--paper:${esc(p.background||'#f4f1eb')};--accent:${esc(p.accent||'#c7c0b4')}"><span>${esc(p.brand||p.name)}</span><small>${esc(p.subtitle||'YOUR PACKAGING DESIGN')}</small></div><div><small>${category==='saved'?'已保存设计':esc(designCategoryLabelV71(p.category))}</small><h3>${esc(p.name)}</h3><button data-v71-use="${esc(p.id)}">创建新设计 ${iconV67('arrow',16)}</button>${category==='saved'?`<button data-v71-remove="${esc(p.id)}" aria-label="删除模板 ${esc(p.name)}">删除模板</button>`:''}</div></article>`).join('')||'<p class="v71-empty">还没有保存的设计模板。</p>';
  d.querySelectorAll('[data-v71-use]').forEach(b=>b.onclick=()=>{try{preserve();let next;if(category==='saved'){const record=stored().find(r=>r.id===b.dataset.v71Use);next=structuredClone(record.state);next.projectId='';next.projectRemoteRevision=0;next.page='editor';next.editorTab='Design';next.projectName=d.querySelector('[data-v71-project-name]').value.trim()||record.name+' / 副本';}else next=createArtworkProjectV71(editor().getState(),b.dataset.v71Use,{templateId:d.querySelector('[data-v71-structure]').value,title:d.querySelector('[data-v71-project-name]').value});editor().commitState(next);close();requestAnimationFrame(()=>editor().fitCanvas());feedback('新设计已创建，原项目已保存。');}catch(e){status('创建失败：'+e.message);}});
  d.querySelectorAll('[data-v71-remove]').forEach(b=>b.onclick=()=>{try{localStorage.setItem(STORE,JSON.stringify(stored().filter(r=>r.id!==b.dataset.v71Remove)));render();status('模板已删除，源项目仍保留。');}catch(e){status(e.message);}});
 }
 d.querySelectorAll('[data-v71-filter]').forEach(b=>b.onclick=()=>{category=b.dataset.v71Filter;d.querySelectorAll('[data-v71-filter]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));render();});
 d.querySelector('[data-v71-save-design]').onclick=()=>{try{const s=editor().getState();if(!(s.elements||[]).length)throw new Error('当前设计没有图文内容。');const rows=stored();if(rows.length>=20)throw new Error('已保存 20 个模板，请先删除不再使用的模板。');const name=d.querySelector('[data-v71-project-name]').value.trim()||s.projectName;rows.unshift({id:'design-'+crypto.randomUUID(),name,state:structuredClone(s)});localStorage.setItem(STORE,JSON.stringify(rows));category='saved';d.querySelectorAll('[data-v71-filter]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.v71Filter==='saved')));render();status('设计模板已保存，可重复创建新项目。');}catch(e){status('保存失败：'+e.message);}};render();
}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function openScene(){
 const source=editor().getState(),geo=generateGeometry(source.structure),graph=buildFoldGraph(geo),debug=window.BoxStudioV52?.getProof?.()?.getDebugState?.(),authoring=debug?.authoring||{},progress=debug?.progress??source.foldProgress??100,d=createDialog('3D 场景与导出','scene'),content=d.querySelector('.v71-content');let animationAbort=null;let activeAuthoring=authoring;let scene=null,settings=sceneSettingsV71(source.sceneV71),drag=null,disposed=false,busy=false;
 content.innerHTML=`<div class="v71-scene-layout"><div class="v71-scene-stage"><div data-v71-scene-canvas tabindex="0" role="img" aria-label="3D 包装场景，拖动旋转，方向键调整角度"></div><div class="v71-scene-hint">拖动旋转 · 滚轮缩放 · 方向键微调</div></div><aside class="v71-scene-controls"><h3>摄影棚灯光</h3><label>灯光方案<select data-v74-rig>${Object.entries(LIGHT_RIGS_V74).map(([id,s])=>`<option value="${id}" ${settings.lightRig===id?'selected':''}>${s.label}</option>`).join('')}</select></label>${[['key','主光亮度',0,8,.1],['fill','补光亮度',0,5,.1],['azimuth','灯光方向 · °',-180,180,1],['elevation','灯光高度 · °',10,85,1],['temperature','色温 · K',2700,7500,100],['exposure','曝光',.3,2,.05],['roughness','纸面粗糙度',.25,1,.05]].map(([key,label,min,max,step])=>`<label>${label}<input data-v74-light="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${settings[key]}"><output data-v74-value="${key}">${settings[key]}</output></label>`).join('')}<h3>场景设置</h3><label>背景场景<select data-v71-scene>${Object.entries(SCENES_V71).map(([id,s])=>`<option value="${id}" ${settings.preset===id?'selected':''}>${s.label}</option>`).join('')}</select></label><label>背景颜色<input data-v71-background type="color" value="${settings.background||'#f4f5f7'}"></label><label class="v71-check"><input data-v71-shadow type="checkbox" ${settings.shadow?'checked':''}>落地阴影</label><label>图文对比度<input data-v71-contrast type="range" min="50" max="180" value="${Math.round(settings.contrast*100)}"><output data-v71-contrast-value>${Math.round(settings.contrast*100)}%</output></label><label>折叠进度<input data-v71-fold type="range" min="0" max="100" value="${progress}"><output data-v71-fold-value>${Math.round(progress)}%</output></label><div class="v71-view-buttons"><button data-v71-view="iso">透视</button><button data-v71-view="front">正面</button><button data-v71-view="top">顶面</button></div><label>图片分辨率<select data-v71-resolution><option value="1600">1600 × 1200</option><option value="2400">2400 × 1800</option><option value="3200">3200 × 2400</option></select></label><button class="primary" data-v71-render disabled>${iconV67('image',18)} 导出场景 PNG</button><button data-v71-glb disabled>${iconV67('box',18)} 导出贴图 GLB</button><details class="v72-animation-controls"><summary>动画导出</summary><div class="v72-animation-fields"><label>动画内容<select data-v72-animation-mode><option value="assembly">展开 → 组装</option><option value="turntable">360° 旋转展示</option></select></label><label>动画时长<select data-v72-seconds><option value="6">6 秒</option><option value="10">10 秒</option></select></label><button data-v72-video disabled>导出动画 WebM · 1280 × 960</button><button data-v72-cancel hidden>取消动画导出</button><small>WebM 视频使用实体背景；透明场景的视频使用白底。</small></div></details><p class="v71-scene-status" role="status" data-v71-scene-status>正在准备图文贴图…</p></aside></div>`;
 const target=d.querySelector('[data-v71-scene-canvas]'),status=message=>{if(!disposed)d.querySelector('[data-v71-scene-status]').textContent=message;};
 d.addEventListener('close',()=>{disposed=true;animationAbort?.abort();disposePhysicalStudioV74();},{once:true});
 const currentProgress=()=>Number(d.querySelector('[data-v71-fold]').value);
 function paint(){if(disposed||!scene||busy)return;const rect=target.getBoundingClientRect(),width=Math.max(320,Math.round(rect.width*(devicePixelRatio||1))),height=Math.max(240,Math.round(rect.height*(devicePixelRatio||1)));const canvas=renderSceneV71(scene.meshes,scene.textures,settings,width,height);target.replaceChildren(canvas);}
 function persistScene(){const now=editor().getState();if(now.projectId===source.projectId&&now.structure.template===source.structure.template){now.sceneV71={...settings};editor().commitState(now);}}
 const changeSettings=()=>{for(const input of d.querySelectorAll('[data-v74-light]')){settings[input.dataset.v74Light]=Number(input.value);d.querySelector('[data-v74-value="'+input.dataset.v74Light+'"]').value=input.value;}settings.lightRig=d.querySelector('[data-v74-rig]').value;const preset=d.querySelector('[data-v71-scene]').value;settings=sceneSettingsV71({...settings,preset,background:preset==='transparent'?null:d.querySelector('[data-v71-background]').value,shadow:d.querySelector('[data-v71-shadow]').checked,contrast:Number(d.querySelector('[data-v71-contrast]').value)/100});d.querySelector('[data-v71-background]').disabled=preset==='transparent';d.querySelector('[data-v71-contrast-value]').value=Math.round(settings.contrast*100)+'%';paint();};
 d.querySelector('[data-v74-rig]').onchange=()=>{const rig=d.querySelector('[data-v74-rig]').value;Object.assign(settings,lightingSettingsV74({lightRig:rig}));for(const input of d.querySelectorAll('[data-v74-light]'))input.value=settings[input.dataset.v74Light];changeSettings();};for(const input of d.querySelectorAll('[data-v74-light]'))input.oninput=changeSettings;
 d.querySelector('[data-v71-scene]').onchange=()=>{const preset=d.querySelector('[data-v71-scene]').value;d.querySelector('[data-v71-background]').value=SCENES_V71[preset].background||'#ffffff';changeSettings();};for(const attr of ['background','shadow','contrast'])d.querySelector(`[data-v71-${attr}]`).addEventListener('input',changeSettings);
 d.querySelector('[data-v71-fold]').oninput=()=>{if(!scene)return;const p=currentProgress();d.querySelector('[data-v71-fold-value]').value=p+'%';activeAuthoring={edgeAngles:authoring.edgeAngles};scene.meshes=foldedMeshesV71(source,geo,graph,{progress:p,authoring:activeAuthoring});paint();};
 d.querySelectorAll('[data-v71-view]').forEach(b=>b.onclick=()=>{const views={iso:[.6,.45],front:[0,0],top:[0,1.45]};[settings.yaw,settings.pitch]=views[b.dataset.v71View];settings.zoom=1;paint();});
 target.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};target.setPointerCapture(e.pointerId);});target.addEventListener('pointermove',e=>{if(!drag)return;settings.yaw+=(e.clientX-drag.x)*.008;settings.pitch=Math.min(1.5,Math.max(-1.5,settings.pitch+(e.clientY-drag.y)*.008));drag={x:e.clientX,y:e.clientY};paint();});for(const name of ['pointerup','pointercancel'])target.addEventListener(name,()=>{drag=null;});target.addEventListener('wheel',e=>{e.preventDefault();settings.zoom=Math.max(.3,Math.min(3,settings.zoom*(e.deltaY>0?.92:1.08)));paint();},{passive:false});target.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key))return;e.preventDefault();if(e.key==='Home')settings=sceneSettingsV71({preset:settings.preset});else if(e.key==='ArrowLeft')settings.yaw-=.08;else if(e.key==='ArrowRight')settings.yaw+=.08;else settings.pitch+=e.key==='ArrowUp'?-.08:.08;settings=sceneSettingsV71(settings);paint();});
 const ro=new ResizeObserver(paint);ro.observe(target);d.addEventListener('close',()=>ro.disconnect(),{once:true});
 async function exportFile(kind){if(busy||!scene)return;busy=true;d.querySelectorAll('[data-v71-glb],[data-v71-render],[data-v72-video]').forEach(b=>b.disabled=true);status(kind==='glb'?'正在生成嵌入贴图的 3D 文件…':'正在生成高分辨率图片…');try{await new Promise(r=>requestAnimationFrame(r));let blob;if(kind==='glb'){const bytes=await buildArtworkGlbV71(source,geo,graph,{progress:currentProgress(),authoring:activeAuthoring,maxPixels:1024});blob=new Blob([bytes],{type:'model/gltf-binary'});}else{const width=Number(d.querySelector('[data-v71-resolution]').value),canvas=renderSceneV71(scene.meshes,scene.textures,settings,width,width*.75);blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('图片编码失败。')),'image/png'));}if(disposed)return;download(blob,'boxstudio-scene.'+(kind==='glb'?'glb':'png'));persistScene();status(kind==='glb'?'已导出 GLB，包含全部面板和图文贴图。':'已导出场景 PNG。');}catch(e){status('导出失败：'+e.message);}finally{busy=false;if(!disposed)d.querySelectorAll('[data-v71-glb],[data-v71-render],[data-v72-video]').forEach(b=>b.disabled=b.hasAttribute('data-v72-video')&&!animationMimeV72());}}
 d.querySelector('[data-v72-cancel]').onclick=()=>animationAbort?.abort();
 d.querySelector('[data-v72-video]').onclick=async()=>{if(busy||!scene)return;busy=true;animationAbort=new AbortController();const disabled=[...d.querySelectorAll('input,select,[data-v71-glb],[data-v71-render],[data-v72-video],[data-v71-view]')].map(el=>[el,el.disabled]);disabled.forEach(([el])=>el.disabled=true);d.querySelector('[data-v72-cancel]').hidden=false;status('正在录制动画 0%…');try{const blob=await recordSceneAnimationV72({state:source,geo,graph,textures:scene.textures,settings,progress:currentProgress(),authoring:activeAuthoring,mode:d.querySelector('[data-v72-animation-mode]').value,seconds:Number(d.querySelector('[data-v72-seconds]').value),signal:animationAbort.signal,onProgress:p=>status(`正在录制动画 ${p}%…`)});if(disposed)return;download(blob,'boxstudio-animation.webm');status('动画 WebM 已导出 · 1280 × 960。');}catch(e){status(e.name==='AbortError'?'动画导出已取消。':'动画导出失败：'+e.message);}finally{busy=false;animationAbort=null;if(!disposed){disabled.forEach(([el,value])=>el.disabled=value);d.querySelector('[data-v72-cancel]').hidden=true;paint();}}};
 d.querySelector('[data-v71-glb]').onclick=()=>exportFile('glb');d.querySelector('[data-v71-render]').onclick=()=>exportFile('png');
 try{scene=await prepareSceneV71(source,geo,graph,{progress,authoring,maxPixels:1024});if(disposed)return;paint();d.querySelectorAll('[data-v71-glb],[data-v71-render],[data-v72-video]').forEach(b=>b.disabled=false);d.querySelector('[data-v72-video]').disabled=!animationMimeV72();status(`${scene.meshes.panels.length} 个面板 · ${target.querySelector('canvas')?.dataset.renderer==='physical-webgl'?'PBR 棚拍、实体投影与图文贴图已就绪':'此设备使用兼容渲染；摄影棚灯光需要 WebGL 支持'}`);}catch(e){status('场景准备失败：'+e.message);}
}
function enhance(){if(!editor())return;const s=editor().getState(),nav=document.querySelector('[data-v66-navigation]');
 if(nav&&!nav.querySelector('[data-v71-design-library]')){const b=document.createElement('button');b.dataset.v71DesignLibrary='true';b.textContent='设计模板';b.onclick=openDesignTemplates;nav.querySelector('[data-v66-library]')?.after(b);}const button=nav?.querySelector('[data-v71-design-library]');if(button)button.hidden=s.page==='mark-studio';
 for(const palette of document.querySelectorAll('[data-v61-studio]'))if(!palette.querySelector('[data-v71-design-presets]')){const b=document.createElement('button');b.dataset.v71DesignPresets='true';b.className='v71-open-presets';b.textContent='浏览设计模板';b.onclick=openDesignTemplates;palette.prepend(b);}
 if(s.page==='editor'&&['3D','Export'].includes(s.editorTab)){const host=document.querySelector(s.editorTab==='3D'?'.three-page.v49-linked-page':'.workspace .review-page');if(host&&!host.querySelector('[data-v71-scene-open]')){const b=document.createElement('button');b.dataset.v71SceneOpen='true';b.className='v71-scene-open';b.innerHTML=iconV67('image',18)+' 3D 场景 · 图片 / 模型 / 动画';b.onclick=()=>openScene().catch(e=>feedback(e.message));host.prepend(b);}}
 if(s.page==='templates'){const page=document.querySelector('.page');if(page&&!page.querySelector('[data-v71-design-center]')){const section=document.createElement('section');section.dataset.v71DesignCenter='true';section.className='v71-design-center';section.innerHTML='<div><span class="v71-eyebrow">ARTWORK TEMPLATES</span><h2>从完整包装设计开始</h2><p>16 款原创设计 · 自定义模板 · 每个元素均可继续编辑</p></div><button data-open>浏览设计模板</button>';section.querySelector('button').onclick=openDesignTemplates;page.querySelector('.v47-template-toolbar')?.before(section);}}
}
window.BoxStudioUiRuntimeV64?.register('v71',enhance);
window.BoxStudioV71={version:'V0.71',openDesignTemplates,openScene,storedDesignTemplates:stored};
