import { collectWorkerAssets as collectLegacyAssets, hydrateWorkerAssets as hydrateLegacyAssets } from './workerAssets.js';
import { getDeviceLinkSource, loadRgbCmykDeviceLink, clearRgbCmykDeviceLink } from './iccDeviceLinkV23.js';

function toBytes(value){if(value instanceof Uint8Array)return new Uint8Array(value);if(value instanceof ArrayBuffer)return new Uint8Array(value.slice(0));if(ArrayBuffer.isView(value))return new Uint8Array(value.buffer.slice(value.byteOffset,value.byteOffset+value.byteLength));if(Array.isArray(value))return Uint8Array.from(value);return null;}
function copyAsset(asset){if(!asset)return null;const bytes=toBytes(asset.bytes);return bytes?{name:String(asset.name||'asset.bin'),bytes,fingerprint:String(asset.fingerprint||'')}:null;}

export function collectWorkerAssetsV24(){const legacy=collectLegacyAssets(),deviceLink=copyAsset(getDeviceLinkSource?.());return{ttf:legacy.ttf||null,icc:legacy.icc||null,deviceLink};}
export function workerAssetAvailabilityV24(assets=collectWorkerAssetsV24()){return{hasTtf:Boolean(assets?.ttf?.bytes?.byteLength),hasIcc:Boolean(assets?.icc?.bytes?.byteLength),hasDeviceLink:Boolean(assets?.deviceLink?.bytes?.byteLength),ttfName:assets?.ttf?.name||'',iccName:assets?.icc?.name||'',deviceLinkName:assets?.deviceLink?.name||'',deviceLinkFingerprint:assets?.deviceLink?.fingerprint||''};}
export function transferableWorkerAssetsV24(assets=collectWorkerAssetsV24()){const payload={ttf:null,icc:null,deviceLink:null},transfer=[];for(const key of ['ttf','icc','deviceLink']){const asset=copyAsset(assets?.[key]);if(!asset)continue;const buffer=asset.bytes.buffer.slice(asset.bytes.byteOffset,asset.bytes.byteOffset+asset.bytes.byteLength);payload[key]={name:asset.name,bytes:buffer,fingerprint:asset.fingerprint||''};transfer.push(buffer);}return{payload,transfer};}
export function hydrateWorkerAssetsV24(assets={}){hydrateLegacyAssets({ttf:assets.ttf||null,icc:assets.icc||null});if(assets?.deviceLink?.bytes){const bytes=toBytes(assets.deviceLink.bytes);loadRgbCmykDeviceLink(bytes,assets.deviceLink.name||'Worker DeviceLink');}else clearRgbCmykDeviceLink();return workerAssetAvailabilityV24({ttf:assets.ttf||null,icc:assets.icc||null,deviceLink:assets.deviceLink||null});}
export function describeWorkerAssetsV24(assets=collectWorkerAssetsV24()){const a=workerAssetAvailabilityV24(assets);return{ttf:a.hasTtf?`${a.ttfName} (${Math.round(assets.ttf.bytes.byteLength/1024)} KB)`:'not loaded',icc:a.hasIcc?`${a.iccName} (${Math.round(assets.icc.bytes.byteLength/1024)} KB)`:'not loaded',deviceLink:a.hasDeviceLink?`${a.deviceLinkName} · ${a.deviceLinkFingerprint||'unidentified'} (${Math.round(assets.deviceLink.bytes.byteLength/1024)} KB)`:'not loaded'};}
