import {ARTWORK_CATALOG_V74,artworkSvgV74,createArtworkV74} from './artworkLibraryV74.js';
import {FONTS_V74,fontOptionsV74,loadFontV74,fontTextSvgV74,fontGlyphIssuesV74,prepareFontsV74,getFontV74} from './fontSystemV74.js';
import {standaloneMarkUiV67} from './standaloneMarkUiV67.js';
import {insertStandaloneMarkV67} from './standaloneMarksV67.js';
import {generateGeometry} from './geometry.js';
import {renderTemplate} from './variables.js';
import {iconV67} from './uiIconsV67.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inMarks=()=>window.BoxStudioEditor.getState().page==='mark-studio';
const state=()=>inMarks()?standaloneMarkUiV67.getState():window.BoxStudioEditor.getState();
const commit=s=>inMarks()?standaloneMarkUiV67.commit(s):window.BoxStudioEditor.commitState(s);
function modal(title,content){const d=document.createElement('dialog');d.className='v67-dialog v74-resource-dialog';d.setAttribute('aria-label',title);d.innerHTML='<header><div><span class="v67-eyebrow">FREE RESOURCE LIBRARY</span><h2>'+title+'</h2></div><button data-v74-close aria-label="关闭窗口">'+iconV67('close')+'</button></header>'+content;document.body.append(d);const close=()=>{d.close();d.remove();};d.querySelector('[data-v74-close]').onclick=close;d.addEventListener('cancel',e=>{e.preventDefault();close();});d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d;}
export function openArtworkLibraryV74(){
 const initial=state(),marks=inMarks(),geo=marks?null:generateGeometry(initial.structure),panels=marks?[{id:'label',label:'当前唛头',w:initial.artboard.width,h:initial.artboard.height}]:geo.panels.filter(p=>p.kind==='panel'),selected=initial.elements.find(e=>e.id===initial.selectedId);let category='全部';
 const d=modal('包装素材库','<p class="v74-resource-intro">32 款免费矢量素材 · 可改色、缩放 · SVG、PDF 和 3D 贴图共用原始曲线</p><div class="v74-resource-toolbar"><label>搜索素材<input data-v74-search type="search" placeholder="叶片、食品、礼品…"></label><label>插入到<select data-v74-panel>'+panels.map(p=>'<option value="'+esc(p.id)+'" '+(selected?.panelId===p.id?'selected':'')+'>'+esc(p.label)+'</option>').join('')+'</select></label><label>素材颜色<input data-v74-color type="color" value="'+(selected?.fillColor||'#111111')+'"></label></div><nav class="v74-resource-filter" aria-label="素材分类">'+['全部','自然','食品','护理','装饰','行业'].map(c=>'<button data-v74-category="'+c+'" aria-pressed="'+(c==='全部')+'">'+c+'</button>').join('')+'</nav><div class="v74-asset-grid" data-v74-assets></div><p role="status" data-v74-status></p><footer><span>Lucide 0.468.0 · ISC · 免费商用</span><a href="/assets/artwork-v74/LICENSE" target="_blank" rel="noopener">素材许可 ↗</a>'+(selected?.assetIdV74?'<button data-v74-recolor>应用颜色到所选素材</button>':'')+'</footer>');
 function render(){const query=d.querySelector('[data-v74-search]').value.trim().toLowerCase(),color=d.querySelector('[data-v74-color]').value,rows=ARTWORK_CATALOG_V74.filter(t=>(category==='全部'||t.category===category)&&(t.label+t.id).toLowerCase().includes(query));d.querySelector('[data-v74-assets]').innerHTML=rows.map(t=>'<button data-v74-asset="'+t.id+'" aria-label="添加'+t.label+'"><svg viewBox="0 0 40 40" aria-hidden="true">'+artworkSvgV74({assetIdV74:t.id,w:40,h:40,fillColor:color})+'</svg><span>'+t.label+'</span></button>').join('')||'<p>没有匹配素材，请更换关键词。</p>';d.querySelector('[data-v74-status]').textContent=rows.length+' 款素材';
  d.querySelectorAll('[data-v74-asset]').forEach(b=>b.onclick=()=>{try{let next=state(),el;const panel=panels.find(p=>p.id===d.querySelector('[data-v74-panel]').value);if(!panel)throw new Error('请选择有效印刷面。');el=createArtworkV74(b.dataset.v74Asset,panel,{color:d.querySelector('[data-v74-color]').value});if(marks){next=insertStandaloneMarkV67(next,'fragile');const slot=next.elements.findIndex(e=>e.id===next.selectedId),position=next.elements[slot];Object.assign(el,{x:position.x,y:position.y,w:position.w,h:position.h,group:'marks'});next.elements[slot]=el;}else next.elements.push(el);next.selectedId=el.id;commit(next);d.querySelector('[data-v74-status]').textContent='已添加 '+el.name+'，可继续调整位置和尺寸。';}catch(e){d.querySelector('[data-v74-status]').textContent=e.message;}});
 }
 for(const b of d.querySelectorAll('[data-v74-category]'))b.onclick=()=>{category=b.dataset.v74Category;d.querySelectorAll('[data-v74-category]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));render();};d.querySelector('[data-v74-search]').oninput=render;d.querySelector('[data-v74-color]').oninput=render;
 d.querySelector('[data-v74-recolor]')?.addEventListener('click',()=>{const next=state(),e=next.elements.find(e=>e.id===selected.id);if(e?.locked){d.querySelector('[data-v74-status]').textContent='请先解锁该图层。';return;}if(e){e.fillColor=d.querySelector('[data-v74-color]').value;commit(next);d.querySelector('[data-v74-status]').textContent='所选素材颜色已更新。';}});render();return d;
}
export function openFontLibraryV74(){
 const initial=state(),selected=initial.elements.find(e=>e.id===initial.selectedId),isText=selected&&['text','notice'].includes(selected.type),previewText=isText?renderTemplate(selected.template,initial.variables):'纸盒设计 · PACKAGING 2026',d=modal('免费字体','<p class="v74-resource-intro">4 个字体家族 · 400 / 700 两种字重 · OFL 免费商用。中英字体覆盖 GB2312，超出字集时导出会提示缺字。</p><label>字体<select data-v74-font>'+fontOptionsV74(selected?.fontIdV74)+'</select></label><div class="v74-font-preview" data-v74-font-preview></div><div class="v74-font-sources">'+FONTS_V74.map(f=>'<p><b>'+f.label+'</b><span>'+f.kind+' · OFL-1.1</span><a href="'+f.source+'" target="_blank" rel="noopener">源字体 ↗</a></p>').join('')+'</div><p role="status" data-v74-status>'+(isText?'应用到当前文字对象，画布与导出保持一致。':'请先在画布或图层中选择文字对象。')+'</p><button class="primary" data-v74-apply-font '+(!isText?'disabled':'')+'>应用字体</button>');let token=0;
 async function preview(){const current=++token,id=d.querySelector('[data-v74-font]').value;try{d.querySelector('[data-v74-status]').textContent='正在加载字体…';await loadFontV74(id,selected?.bold);if(current!==token||!d.open)return;const el={fontIdV74:id,bold:selected?.bold,fontSize:10},issues=fontGlyphIssuesV74(el,previewText);d.querySelector('[data-v74-font-preview]').innerHTML=id?'<svg viewBox="0 0 260 48">'+(fontTextSvgV74(el,previewText,8,8)||'')+'</svg>':'<p>'+esc(previewText)+'</p>';d.querySelector('[data-v74-status]').textContent=issues[0]||(isText?'字体已就绪，可应用到当前文字。':'请先选择文字对象。');d.querySelector('[data-v74-apply-font]').disabled=!isText||issues.length>0;}catch(e){d.querySelector('[data-v74-status]').textContent=e.message;d.querySelector('[data-v74-apply-font]').disabled=true;}}
 d.querySelector('[data-v74-font]').onchange=preview;d.querySelector('[data-v74-apply-font]').onclick=async()=>{const b=d.querySelector('[data-v74-apply-font]');b.disabled=true;try{const next=state(),e=next.elements.find(e=>e.id===selected.id);if(!e||e.locked)throw new Error('文字对象不存在或已锁定。');const id=d.querySelector('[data-v74-font]').value;await loadFontV74(id,e.bold);e.fontIdV74=id;commit(next);d.close();}catch(e){d.querySelector('[data-v74-status]').textContent=e.message;b.disabled=false;}};preview();return d;
}
let loadingKey='';
function enhance(){if(!window.BoxStudioEditor)return;const s=state(),nav=document.querySelector('[data-v66-navigation]');if(nav&&!nav.querySelector('[data-v74-resources]')){const b=document.createElement('button');b.dataset.v74Resources='true';b.textContent='素材库';b.onclick=openArtworkLibraryV74;nav.append(b);const f=document.createElement('button');f.dataset.v74Fonts='true';f.textContent='字体';f.onclick=openFontLibraryV74;nav.append(f);}
 const needs=(s.elements||[]).filter(e=>e.fontIdV74&&!getFontV74(e.fontIdV74,e.bold)),key=needs.map(e=>e.fontIdV74+e.bold).sort().join(',');if(key&&key!==loadingKey){loadingKey=key;prepareFontsV74(s).then(()=>{loadingKey='';if(inMarks())standaloneMarkUiV67.refresh();else window.BoxStudioEditor.reloadFromStorage({history:false});}).catch(()=>{loadingKey='';});}
}
window.BoxStudioUiRuntimeV64?.register('v74',enhance);
window.BoxStudioV74={openArtworkLibrary:openArtworkLibraryV74,openFontLibrary:openFontLibraryV74,switchMarkFace:face=>standaloneMarkUiV67.switchFace(face)};
