import {applyDielineV77} from './dielineApplyV77.js';
import {moveMarkSelectionV68,alignMarkSelectionV68} from './standaloneLayoutV68.js';
import {PAPER_PRESETS_V77,paperAppearanceV77,validatePaperV77} from './paperMaterialsV77.js';
import {PAPER_FINISHES_V75} from './studioConfigV75.js';
import {generateGeometry,resolveElementRect} from './geometry.js';
import {dielineDocumentFromStateV38} from './dielineCadV38.js';
import {buildDielineSvgV38,buildDielinePdfV38,buildDxfV38} from './productionExportV38.js';
import {buildFoldGraph} from './foldgraph.js';
import {buildArtworkGlbV71} from './threeExportV71.js';
import {standaloneMarkUiV67 as marks} from './standaloneMarkUiV67.js';
import {PX_MM_V77} from './editorGeometryV77.js';
import {setUiVersion} from './uiVersion.js';
import {openDielineCadV38,getDielineDocumentV38,closeCad} from './v38Ui.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const editor=()=>window.BoxStudioEditor;const key='boxstudio-paper-presets-v77';
function custom(){try{return JSON.parse(localStorage.getItem(key)||'[]').map(validatePaperV77);}catch{return[];}}
function download(name,data,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function dialog(title){const d=document.createElement('dialog');d.className='v77-dialog';d.innerHTML=`<header><div><small>BOXSTUDIO WORKBENCH</small><h2>${title}</h2></div><button data-close aria-label="关闭">×</button></header><main></main>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d;}
export function openPaperV77(){const d=dialog('纸张与 3D 外观'),initial=editor().getState(),paper=paperAppearanceV77(initial.structure),main=d.querySelector('main');main.innerHTML=`<div class="v77-paper-presets">${[...PAPER_PRESETS_V77,...custom()].map(p=>`<button data-paper="${esc(p.id)}"><i style="background:${p.face};--paper-inner:${p.inner}"></i><b>${esc(p.name)}</b><small>${p.thickness} mm · ${PAPER_FINISHES_V75[p.finish]?.label||'自然纸面'}</small></button>`).join('')}</div><form class="v77-paper-form"><label>材质名称<input name="name" maxlength="60" value="${esc(paper.name)}"></label><label>外侧纸色<input name="face" type="color" value="${paper.face}"></label><label>内侧纸色<input name="inner" type="color" value="${paper.inner}"></label><label>纸张厚度 · mm<input name="thickness" type="number" min=".1" max="15" step=".01" value="${initial.structure.thickness||paper.thickness}"></label><label>纸面效果<select name="finish">${Object.entries(PAPER_FINISHES_V75).map(([id,p])=>`<option value="${id}" ${id===paper.finish?'selected':''}>${p.label}</option>`).join('')}</select></label><label>楞型<select name="flute">${['F','E','B','C','EB','BC','AA'].map(f=>`<option ${f===initial.structure.flute?'selected':''}>${f}</option>`).join('')}</select></label><label><input type="checkbox" name="savePreset">保存为我的材质预设</label><p role="status"></p><button type="submit" class="primary">应用材质</button></form>`;const form=main.querySelector('form');let selected=paper.id;for(const b of main.querySelectorAll('[data-paper]'))b.onclick=()=>{const p=[...PAPER_PRESETS_V77,...custom()].find(p=>p.id===b.dataset.paper);selected=p.id;for(const k of ['name','face','inner','thickness','finish'])form.elements[k].value=p[k];main.querySelectorAll('[data-paper]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));};form.onsubmit=e=>{e.preventDefault();try{const f=form.elements,p=validatePaperV77({id:selected,name:f.name.value,face:f.face.value,inner:f.inner.value,thickness:Number(f.thickness.value),finish:f.finish.value});if(f.savePreset.checked){p.id='custom-'+Date.now().toString(36);const rows=custom().filter(n=>n.name!==p.name);rows.push(p);localStorage.setItem(key,JSON.stringify(rows.slice(-40)));}const s=editor().getState();s.structure={...s.structure,materialId:PAPER_PRESETS_V77.some(n=>n.id===selected)?selected:'kraft-paperboard',paperV77:p,thickness:p.thickness,flute:f.flute.value};s.sceneV71={...s.sceneV71,finish:p.finish};editor().commitState(s);d.close();}catch(error){form.querySelector('[role="status"]').textContent=error.message;}};return d;}
async function exportStructure(kind,button){button.disabled=true;const original=button.textContent;try{const state=editor().getState(),doc=state.dielineV38||dielineDocumentFromStateV38(state);if(kind==='ai')download('boxstudio-dieline.ai',buildDielinePdfV38(doc),'application/postscript');else if(kind==='svg')download('boxstudio-dieline.svg',buildDielineSvgV38(doc),'image/svg+xml');else if(kind==='pdf')download('boxstudio-dieline.pdf',buildDielinePdfV38(doc),'application/pdf');else if(kind==='dxf')download('boxstudio-dieline.dxf',buildDxfV38(doc),'application/dxf');else{button.textContent='正在生成…';const geo=generateGeometry(state.structure);download('boxstudio-box.glb',await buildArtworkGlbV71(state,geo,buildFoldGraph(geo),{background:paperAppearanceV77(state.structure).face}),'model/gltf-binary');}}catch(e){button.closest('section').querySelector('[role="status"]').textContent=e.message;}finally{button.disabled=false;button.textContent=original;}}
function openDownloads(){const d=dialog('刀版文件下载');d.querySelector('main').innerHTML='<section class="v77-downloads"><div>'+[['ai','AI · PDF 兼容'],['pdf','PDF'],['dxf','DXF'],['glb','3D GLB'],['svg','SVG']].map(([id,label])=>`<button data-v77-export="${id}">${label}</button>`).join('')+'</div><p role="status">原尺寸 · 免费下载</p></section>';d.querySelectorAll('[data-v77-export]').forEach(b=>b.onclick=()=>exportStructure(b.dataset.v77Export,b));return d;}
function openWorkbench(){const d=dialog('设计工具');d.querySelector('main').innerHTML='<div class="v77-tool-menu"><button data-paper>纸张材质与自定义预设</button><button data-text>文字预设</button><button data-cad>自定义刀版 CAD</button><button data-download>刀版文件下载</button></div>';for(const [selector,fn]of [['[data-paper]',openPaperV77],['[data-text]',()=>window.BoxStudioV77Text.openPresets()],['[data-cad]',openDielineCadV38],['[data-download]',openDownloads]])d.querySelector(selector).onclick=()=>{d.close();fn();};}
function move(dx,dy,unit='px'){const s=editor().getState(),inMarks=s.page==='mark-studio';if(unit==='px'){dx*=PX_MM_V77;dy*=PX_MM_V77;}if(inMarks){marks.commit(moveMarkSelectionV68(marks.getState(),marks.getSelection(),dx,dy));return;}const e=s.elements.find(e=>e.id===s.selectedId);if(!e)return;if(e.locked)throw new Error('请先解锁所选对象。');e.x+=dx;e.y+=dy;editor().commitState(s);}
function align(direction){const s=editor().getState();if(s.page==='mark-studio'){marks.commit(alignMarkSelectionV68(marks.getState(),marks.getSelection(),direction,{target:'safe'}));return;}const e=s.elements.find(e=>e.id===s.selectedId),panel=generateGeometry(s.structure).panelMap[e?.panelId];if(!e||!panel)return;if(e.locked)throw new Error('请先解锁所选对象。');const a=(e.r||0)*Math.PI/180,w=Math.abs(Math.cos(a))*e.w+Math.abs(Math.sin(a))*e.h,h=Math.abs(Math.sin(a))*e.w+Math.abs(Math.cos(a))*e.h;if(w>panel.w||h>panel.h)throw new Error('对象大于当前面，请先缩小。');const cx=['left','center','right'].includes(direction)?direction==='left'?w/2:direction==='right'?panel.w-w/2:panel.w/2:e.x+e.w/2,cy=['top','middle','bottom'].includes(direction)?direction==='top'?h/2:direction==='bottom'?panel.h-h/2:panel.h/2:e.y+e.h/2;e.x=cx-e.w/2;e.y=cy-e.h/2;editor().commitState(s);}
function tools(){const s=editor().getState();if(s.page!=='editor')return;const w=document.querySelector('.workspace'),right=w?.querySelector('.rightpanel');if(!right)return;
 if(!right.querySelector('[data-v77-paper-open]')){const block=document.createElement('section');block.className='v77-side-tools';block.innerHTML=`<button data-v77-paper-open>纸张材质 · 自定义预设</button><button data-v77-studio-open>灯光与高清渲染</button>`;const mini=right.querySelector('[data-v58-mini3d]');mini?mini.after(block):right.prepend(block);block.querySelector('[data-v77-paper-open]').onclick=openPaperV77;block.querySelector('[data-v77-studio-open]').onclick=()=>window.BoxStudioV71.openScene();}
 if(['Structure','3D'].includes(s.editorTab)&&!right.querySelector('[data-v77-downloads]')){const block=document.createElement('section');block.dataset.v77Downloads='true';block.className='v77-downloads';block.innerHTML='<h3>文件格式</h3><div>'+[['ai','AI 刀版'],['pdf','PDF 刀版'],['dxf','DXF 刀版'],['glb','3D GLB'],['svg','SVG 刀版']].map(([id,label])=>`<button data-v77-export="${id}"><b>${id.toUpperCase()}</b>${label}</button>`).join('')+'</div><p role="status">原尺寸 · 免费下载 · AI 为 PDF 兼容矢量文件</p>';right.querySelector('.v77-side-tools').after(block);block.querySelectorAll('[data-v77-export]').forEach(b=>b.onclick=()=>exportStructure(b.dataset.v77Export,b));}
 const main=w.querySelector('.main'),bar=main.querySelector('.tabbar');if(bar&&!bar.querySelector('[data-v77-measure]')){const b=document.createElement('button');b.dataset.v77Measure='true';b.textContent='尺寸';b.title='显示或隐藏刀版尺寸';b.setAttribute('aria-pressed',String(s.dimensionsV77!==false));b.onclick=()=>{const next=editor().getState();next.dimensionsV77=next.dimensionsV77===false;editor().commitState(next);};bar.prepend(b);const menu=document.createElement('button');menu.dataset.v77Workbench='true';menu.textContent='工具';menu.onclick=openWorkbench;bar.prepend(menu);}
 if(s.editorTab==='Structure'&&!w.querySelector('[data-v77-structure-library]')){const lib=document.createElement('aside');lib.className='v77-structure-library';lib.dataset.v77StructureLibrary='true';lib.innerHTML=`<small>STRUCTURE LIBRARY</small><h2>刀版与盒型</h2><button data-library>浏览盒型库</button><button data-design>设计模板</button><button data-cad>自定义刀版 CAD</button><h3>${s.structure.template==='imported'?'刀版展开尺寸':'成品尺寸'} · mm</h3>${(s.structure.template==='imported'?[['length','展开宽'],['width','展开高'],['thickness','纸厚']]:[['length','长 L'],['width','宽 W'],['height','高 H'],['thickness','纸厚']]).map(([k,label])=>`<label>${label}<input data-size="${k}" type="number" step=".1" min=".1" value="${s.structure[k]}"></label>`).join('')}<label><input type="checkbox" data-advanced ${s.advancedDimensionsV77?'checked':''}>显示高级尺寸</label><p>蓝色尺寸标注随参数实时更新。CAD 可调整节点、曲线和割线 / 折线。</p>`;main.before(lib);lib.querySelector('[data-library]').onclick=()=>document.querySelector('[data-v66-library]').click();lib.querySelector('[data-design]').onclick=()=>window.BoxStudioV71.openDesignTemplates();lib.querySelector('[data-cad]').onclick=()=>openDielineCadV38();lib.querySelectorAll('[data-size]').forEach(input=>{if(s.structure.template==='imported'&&input.dataset.size!=='thickness'){input.disabled=true;input.title='自定义刀版通过 CAD 节点调整';}});lib.querySelectorAll('[data-size]').forEach(input=>input.onchange=()=>{const next=editor().getState(),value=Number(input.value);if(!Number.isFinite(value)||value<=0)return;next.structure[input.dataset.size]=value;editor().commitState(next);requestAnimationFrame(()=>editor().fitCanvas());});lib.querySelector('[data-advanced]').onchange=e=>{const next=editor().getState();next.advancedDimensionsV77=e.target.checked;editor().commitState(next);};}
}
function nudgeTools(){const s=editor().getState(),inMarks=s.page==='mark-studio',e=(inMarks?marks.getState():s).elements.find(n=>n.id===(inMarks?marks.getState().selectedId:s.selectedId));if(!e)return;const target=inMarks&&document.querySelector('[data-inspector="object"][aria-selected="true"]')?document.querySelector('.v67-inspector-content'):inMarks?null:document.querySelector('.rightpanel');if(!target||target.querySelector('[data-v77-nudge]'))return;const section=document.createElement('section');section.className='v77-nudge';section.dataset.v77Nudge='true';section.innerHTML='<h3>精确移动与吸附</h3><div><label>移动量<input data-step type="number" min=".1" max="1000" value="1" step=".1"></label><label>单位<select data-unit><option value="px">px · 96 dpi</option><option value="mm">mm</option></select></label></div><div>'+[['-1','0','←','左移'],['0','-1','↑','上移'],['0','1','↓','下移'],['1','0','→','右移']].map(([x,y,icon,label])=>`<button data-x="${x}" data-y="${y}" aria-label="${label}">${icon}</button>`).join('')+'</div><div class="v77-align">'+[['left','左对齐'],['center','水平居中'],['right','右对齐'],['top','顶对齐'],['middle','垂直居中'],['bottom','底对齐']].map(([id,label])=>`<button data-align="${id}">${label}</button>`).join('')+'</div><label><input data-smart type="checkbox" checked>实时吸附边缘与中心</label><small>方向键 1 px · Shift 10 px · Alt 拖动暂时关闭吸附</small><p role="status"></p>';target.append(section);section.querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>{try{const n=Number(section.querySelector('[data-step]').value);if(!Number.isFinite(n)||n<=0)throw new Error('请输入有效移动量。');move(Number(b.dataset.x)*n,Number(b.dataset.y)*n,section.querySelector('[data-unit]').value);}catch(error){section.querySelector('[role="status"]').textContent=error.message;}});section.querySelectorAll('[data-align]').forEach(b=>b.onclick=()=>{try{align(b.dataset.align);}catch(error){section.querySelector('[role="status"]').textContent=error.message;}});section.querySelector('[data-smart]').checked=inMarks?marks.getSmartGuides():s.smartGuidesV77!==false;section.querySelector('[data-smart]').onchange=e=>{if(inMarks){marks.setSmartGuides(e.target.checked);return;}const next=editor().getState();next.smartGuidesV77=e.target.checked;editor().commitState(next);};}
function cadTools(){const top=document.querySelector('#boxstudio-v38-cad .v38-top');if(!top||top.querySelector('[data-v77-apply-dieline]'))return;const button=document.createElement('button'),status=document.createElement('span');button.dataset.v77ApplyDieline='true';button.className='primary';button.textContent='应用刀版到 2D / 3D';status.dataset.v77CadStatus='true';status.setAttribute('role','status');top.querySelector('[data-v38-action="close"]').before(button,status);button.onclick=()=>{try{const next=applyDielineV77(editor().getState(),getDielineDocumentV38());closeCad();editor().commitState(next);editor().fitCanvas();}catch(e){status.textContent=e.message;}};}
function enhance(){if(!editor())return;cadTools();setUiVersion('V0.77');document.body.dataset.v77='true';tools();nudgeTools();}
window.BoxStudioUiRuntimeV64?.register('v77-workbench',enhance);
window.addEventListener('keydown',e=>{const s=editor()?.getState();if(!s||s.page!=='editor'||!s.selectedId||e.defaultPrevented||e.target?.closest?.('input,textarea,select,[contenteditable]')||document.querySelector('dialog[open]'))return;const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(d&&!e.ctrlKey&&!e.metaKey){e.preventDefault();if(s.elements.find(n=>n.id===s.selectedId)?.locked)return;move(d[0]*(e.shiftKey?10:1),d[1]*(e.shiftKey?10:1));}});
window.BoxStudioV77={openPaper:openPaperV77,openDownloads,openWorkbench,move,align,customPaperPresets:custom};
